<div id="invite_friends" style="display: none;">
<!--    <div class="invite-left f-left">
       <img class="full-width" src="<?php //echo $this->getUrl()?>skin/frontend/new-yogasmoga/yogasmoga-theme/images/popups/dummy-in.png"/>
   </div> -->
   <div class="invite-right f-right">
        <div class="invite-form">
            <p class="c-align smogi-love-msg">SHARE THE SMOGI LOVE<br>WITH YOUR FRIENDS<span>THEY WILL RECEIVE $25 SMOGI BUCKS<br>UPON SIGN UP</span></p>
            <form id="invite-friend-form" class="bl" action="" method="post">
                <table width="100%" cellpadding="0" cellspacing="0">
                    <tr>
                        <td>
                            <input type="text" id="friendname" name="friendname" class="watermark" watermark="Friend's Name" value="" maxlength="30" class="requiredfield">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <input type="text" id="friendemail" name="friendemail" class="watermark" watermark="Friend's Email" value="" maxlength="30" class="requiredfield">
                        </td>
                    </tr>
                    <tr>
                        <td class="no-padding">
                            <input class="pointer" type="submit" id="send-invite" value="" style="background-image: url(<?php echo Mage::getUrl('/', array('_secure'=>true));?>skin/frontend/new-yogasmoga/yogasmoga-theme/images/new-elements/send-share.jpg); width:315px; margin-top:20px; height:39px; border:none;">
                        </td>
                        <td align="center" class="form-loader no-padding c-align"></td>
                    </tr>
                    <tr>
                        <td>
                            <p style="min-height:15px;  margin: 0 auto; font-size: 12px; visibility:hidden" class="err-msg">All fields are required.</p>
                        </td>
                        </tr>                        
                </table>
            </form>
        </div>
        <div class="invite-message no-display">
            <p class="c-align smogi-love-msg">Thank you for<br />sharing SMOGI love.</p>
            <p class="mtop10"><input class="pointer" type="button" id="continue-shopping" value=""style="background-image: url(<?php echo $this->getUrl()?>skin/frontend/new-yogasmoga/yogasmoga-theme/images/new-elements/contineu-shop.jpg); width:315px; margin-top:20px; height:39px; border:none;"></p>
        </div>       
   </div>
    
</div>