<div id="signing_popup" style="display: none; display:block;">
    <div class="sign-up-block f-left" style="width:50%;">
        <p class="l-align">SIGN UP</p>
        <form action="">
            <table>
                <tr>
                    <td>
                        <label for="fname">First Name</label>
                        <input type="text" id="fname">
                    </td>                    
                </tr>
                <tr>
                    <td>
                        <label for="lname">Last Name</label>
                        <input type="text" id="lname">
                    </td>                    
                </tr>
                <tr>
                    <td>
                        <label for="email">Email</label>
                        <input type="text" id="email">
                    </td>                    
                </tr>
                <tr>
                    <td>
                        <label for="spassword">Select a Password</label>
                        <input type="text" id="spassword">
                    </td>                    
                </tr>
            </table>
        </form>

    </div>
    <div class="sign-in-block f-right" style="width:50%;">
        <p class="l-align">SIGN IN</p>
        <form action="">
            <table>
                <tr>
                    <td>
                        <label for="firstname">First Name</label>
                        <input type="text" id="firstname">
                    </td>                    
                </tr>                
                <tr>
                    <td>
                        <label for="password">Password</label>
                        <input type="text" id="password">
                    </td>                    
                </tr>
            </table>
        </form>
    </div>
    <div class="clear-fix"></div>
    
</div>