<div id="signup" style="display: none;">
    <div id="sign_up_box">
<!--        <img nopin="nopin" style="width:50%; margin-top: 8%;" src="--><?php //echo $this->getSkinUrl('images/red_popup_text.png') ?><!--" alt="FEEL THE SMOGI LOVE. Sign up and get $25 SMOGI bucks toward your first order." />-->
        <form action="" method="post" id="popup-register" style="display: block; ">
            <table width="100%" cellspacing="0" padding="0" align="center">
                <tr>
                    <td class="inputholder">
                        <input type="text" id="pfirstname" name="pfirstname" class="watermark" watermark="First Name" value="" maxlength="30" class="requiredfield no-bg">
                    </td>
                </tr>
                <tr height="5"></tr>
                <tr>

                    <td class="inputholder">
                        <input type="text" id="plastname" name="plastname" class="watermark" watermark="Last Name" value="" maxlength="30" class="requiredfield no-bg">
                    </td>
                </tr>
                <tr height="5"></tr>
                <tr>
                    <td class="inputholder">
                        <input type="text" name="email" id="pemail_address" class="watermark" watermark="Email Address" autocomplete="off" value="" class="requiredfield" defaulterrormsg="Email Address is required" autocapitalize="off">
                    </td>
                </tr>
                <tr height="5"></tr>
                <tr class="fake_password">
                    <td class="inputholder">
                        <input type="text" autocomplete="off" maxlength="30" class="watermark f_password requiredfield" watermark="Select a password" name="password" id="f_password" defaulterrormsg="Password is required">
                    </td>
                </tr>
                <tr class="orig_password">
                    <td class="inputholder">
                        <input type="password" autocomplete="off" maxlength="30" class="requiredfield o_password" name="password" id="p_password" defaulterrormsg="Password is required">
                    </td>
                </tr>
                <tr>
                    <td class="gender_tr">
                        <p class="gender_p">Select Gender <span class="gender_radio"><input type="radio" value="1" name="gender"/>M</span> <span class="gender_radio"><input type="radio" value="2" name="gender"/>F</span></p>
                    </td>
                </tr>
                <tr height="5"></tr>
                <input style="display: none;" type="password" class="requiredfield" name="confirmation" id="confirmation" defaulterrormsg="Password is required"/>
                <input style="display: none;" id="is_subscribed" class="checkbox" type="checkbox" checked="checked" value="1" name="is_subscribed"/>

            </table>

            <button type="submit" id="signup-button">Sign up</button>
            <p style="margin: 0px auto; font-size: 12px; visibility: hidden; min-height: 20px; width: 236px;" id="err-msg">All fields are required.</p>

            <p class="link_red_popup" style="color:#ff9f9f">Already Signed up? <br/><a onclick="jQuery('#signin').click()">Sign in here</a> </p>

        </form>
    </div>
    <div id="thank_you_box" style="display:none;">
        <img nopin="nopin" style="width:46%; padding-top: 12%; margin-top: 6%; padding-left:6%; padding-right: 6%;   background: #f00;" src="<?php echo $this->getSkinUrl('images/thank_you_text.png') ?>" alt="THANK YOU! Your SMOGI Bucks are waiting to be used at Checkout." />
        <table width="78%" cellspacing="0" cellpadding="0" style="margin:12% auto !important;">
            <tr>
                <td style="text-align:left;padding-right: 15px">
                    <a style="background:#FF4D4D; color: #fff;  width: 170px;  margin:  0 auto;   text-align: center; height:42px; display:block; line-height:42px; font-family:AVANTGARDEGOTHICITCW01B;" href="<?php echo Mage::helper('core/url')->getHomeUrl(); ?>women">
                        SHOP WOMEN
                    </a>
                </td>
                <td  style="text-align:right;padding-left: 15px">
                    <a style="background:#FF4D4D; color: #fff;  width: 170px;  margin:  0 auto;   text-align: center; height:42px; display:block; line-height:42px; font-family:AVANTGARDEGOTHICITCW01B;" href="<?php echo Mage::helper('core/url')->getHomeUrl(); ?>mens">
                        SHOP MEN
                    </a>
                </td>
            </tr>
        </table>
        <table width="60%" ceelspacing="0" cellpadding="0" style="margin:5% auto 0;">
            <tr>
                <td style="text-align:center;">
                    <a href="<?php echo Mage::helper('core/url')->getHomeUrl(); ?>smogi-bucks">
                        <img src="<?php echo $this->getSkinUrl('images/learn_bucks.png') ?>" alt="Learn more about SMOGI Bucks" style="width:75%; margin:0 auto !important;" /></a>
                </td>
            </tr>
        </table>
    </div>
</div>