<h3>Upload Products</h3><br/>

<form action="<?php echo $this->getUrl('*/*/saveProducts')?>" target="ifr" method="post" enctype="multipart/form-data" onsubmit="return upload()">
    <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
    Select file : <input type="file" name="file"/> &nbsp; <input type="submit" value="Upload Products"/>
</form>

<br/><br/>
<div id="message"></div>
<br/>

<iframe name="ifr" id="ifr" style="visibility: hidden; width:0px; height:0px;"></iframe>

<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
<script type="text/javascript">
    function upload(){

        $("#message").show();
        $("#message").html("Uploading, please wait....");

        $("#ifr").load(function(){
            $("#message").show();
            $("#message").html("Products uploaded successfully").fadeOut(10000, function(){$("#message").html("")});
        });

        return true;
    }
</script>
