<div class="page-title">
    <h1><?php echo $this->__("My Payment Method") ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="stripe-payment-dashboard">
<script type="text/javascript" src="https://js.stripe.com/v1/"></script>
		<form action="<?php echo $this->getUrl("stripe/save") ?>" method="post" name="stripe-payment" id="stripe-payment">
		<div class="fieldset">
			<input type="hidden" name="customer_id" value="<?php echo $this->getCustomer()->getEntityId() ?>" />
				<h2 class="legend"><?php echo $this->__("Payment Information") ?> <?php if ($this->getIsStripeCustomer()) :?> | <span><a id="stripe-update-payment" class="use"><?php echo $this->__("Edit") ?></a></span> | <span><a id="stripe-delete-payment" class="use"><?php echo $this->__("Delete") ?></a></span><?php endif; ?></h2>
				<ul id="payment_form_stripe">
					<li id="stripe-change-payment-form" <?php if ($this->getIsStripeCustomer()): ?> style="display: none;"<?php endif; ?>>
							<ul class="form-list">
								<li class="wide">
									<label for="firstname">Cardholder Name<span class="required">*</span></label>
						        	<div class="input-box">
						            	<input type="text" id="fullname" name="fullname" value="<?php echo $this->getCustomer()->getName() ?>" title="Full Name" maxlength="255" class="input-text required-entry">
						        	</div>
					        	</li>
				        	 <?php if ($this->sendAddressData()) : ?>
				        	 	<?php if ($this->getBillingAddress()->getEntityId()==0) : ?>
				        	 	<li class="wide">
				        	 		<label for="also_save_as_primary_billing_address">Save this address as Primary Billing Address?</label>
				        	 		<input type="checkbox" name="also_save_as_primary_billing_address" id="also_save_as_primary_billing_address" checked="checked" />
				        	 		<input type="hidden" name="firstname" value="<?php echo $this->getCustomer()->getFirstname() ?>" />
				        	 		<input type="hidden" name="lastname" value="<?php echo $this->getCustomer()->getLastname() ?>" />
				        	 	</li>
				        	 	<li class="wide">
				        	 		<label for="telephone">Telephone <span class="required">*</span></label>
				        	 		<div class="input-box">
				        	 			<input type="text" id="telephone" name="telephone" value="" title="Telephone" class="input-text required-entry">
				        	 		</div>
				        	 	</li>
				        	 	<?php endif; ?>
								<li class="wide">
								 	<label for="street_1">Street Address<span class="required">*</span></label>
								 	<div class="input-box">
										<input type="text" name="street[]" value="<?php echo $this->getBillingAddress()->getStreet1(); ?>" title="Street Address" id="street_1" class="input-text  required-entry">
								 	</div>
						  		</li>
								<li class="wide">
							 		<div class="input-box">
										<input type="text" name="street[]" value="<?php echo $this->getBillingAddress()->getStreet2() ?>" title="Street Address 2" id="street_2" class="input-text ">
							 		</div>
						  		</li>
								<li class="fields">
							 		<div class="field">
										<label for="city">City</label>
										<div class="input-box">
								    		<input type="text" name="city" value="<?php echo $this->getBillingAddress()->getCity() ?>" title="City" class="input-text  required-entry" id="city">
										</div>							 		</div>

							 		<div class="field">
										<label for="region_id">State/Province<span class="required">*</span></label>
										<div class="input-box">
								    		<select id="region_id" name="region_id" title="State/Province" class="validate-select required-entry" style="" defaultvalue="0">
									  		<option value="">Please select region, state or province</option>
										    <script type="text/javascript">
										    //<![CDATA[
											   $('region_id').setAttribute('defaultValue',  "<?php echo $this->getBillingAddress()->getRegionId() ?>");
										    //]]>
										    </script>
								    		<input type="text" id="region" name="region" value="<?php echo $this->getBillingAddress()->getRegion() ?>" title="State/Province" class="input-text required-entry" style="display: none; ">
										</div>
							 		</div>
						 			</li>
								  <li class="fields">
									 <div class="field">
										<label for="zip">Zip/Postal Code<span class="required">*</span></label>
										<div class="input-box">
										    <input type="text" name="postcode" value="<?php echo $this->getBillingAddress()->getPostcode() ?>" title="Zip/Postal Code" id="zip" class="input-text validate-zip-international  required-entry">
										</div>
									 </div>
									 <div class="field">
										<label for="country">Country<span class="required">*</span></label>
										<div class="input-box">
										    <?php echo $this->getCountryHtmlSelect() ?>
										</div>
									 </div>
								  </li>
							  <?php endif; // if($this->sendAddressData()) ?>
					        </ul>
							<ul class="form-list">
							<?php if ($this->getAlwaysCreateStripeCustomer()) : ?>
									<input type="hidden" name="create_stripe_customer" value="<?php if ($this->getIsStripeCustomer()) : ?>0<?php else : ?>1 <?php endif; ?>" />
							<?php else : ?>
									<label for="stripe_create_stripe_customer"><?php echo Mage::helper('payment')->__("Save card for later use?")?></label>
									<input type="checkbox" value="1" name="create_stripe_customer" id="stripe_create_stripe_customer" <?php if ($this->getAlwaysChecked()) : ?>checked="checked"<?php endif; ?> />
							<?php endif; ?>
							<input type="hidden" name="stripe_token" value="<?php echo $this->getInfoData('stripe_token') ?>" id="stripe_token" />
						    <li>
						        <div class="input-box">
						            <label for="stripe_cc_number"><?php echo Mage::helper('payment')->__('Credit Card Number') ?> <span class="required">*</span></label><br/>
						            <input type="text" id="stripe_cc_number" name="cc_number" title="<?php echo Mage::helper('payment')->__('Credit Card Number') ?>" class="input-text validate-cc-number" value="<?php echo $this->getInfoData('cc_number')?>"/>
						        </div>
						    </li>
						    <li>
						        <div class="input-box">
						            <label for="stripe_expiration"><?php echo Mage::helper('payment')->__('Expiration Date') ?> <span class="required">*</span></label><br/>
						            <select id="stripe_expiration" style="width:140px;" name="cc_exp_month" class="validate-cc-exp required-entry">
						            <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
						            <?php foreach ($this->getCcMonths() as $k=>$v): ?>
						                <option value="<?php echo $k ?>" <?php if($k==$_ccExpMonth): ?>selected="selected"<?php endif ?>><?php echo $v ?></option>
						            <?php endforeach ?>
						            </select>
						            <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
						            <select id="stripe_expiration_yr" style="width:103px;" name="cc_exp_year" class="required-entry">
						            <?php foreach ($this->getCcYears() as $k=>$v): ?>
						                <option value="<?php echo $k ? $k : '' ?>" <?php if($k==$_ccExpYear): ?>selected="selected"<?php endif ?>><?php echo $v ?></option>
						            <?php endforeach ?>
						            </select>
						        </div>
						    </li>
						    <?php if($this->hasVerification()): ?>
						    <li>
						        <div class="input-box">
						            <label for="stripe_cc_cid"><?php echo Mage::helper('payment')->__('Card Verification Number') ?> <span class="required">*</span></label><br/>
						            <input type="text" title="<?php echo Mage::helper('payment')->__('Card Verification Number') ?>" class="required-entry input-text validate-cc-cvn" id="stripe_cc_cid" name="cc_cid" style="width:3em;" value="<?php echo $this->getInfoData('cc_cid')?>"/>
						        </div>
						    </li>
						    <?php endif; ?>
							</ul>
							<ul id="stripe-buttons-container">
								<li>
									<button type="submit" id="stripe_save_payment" title="Save Payment" class="button" name="save_payment" onclick="javascript:saveStripePayment(); return false;"><span><span>Save Payment</span></span></button>
								</li>
							</ul>
					</li>
					<?php if ($this->getIsStripeCustomer()) : ?>
						<li id="stripe-payment-details">
							<ul>
								<li>
									<input type="hidden" name="stripe_customer_id" value="<?php echo $this->getStripeCustomerId() ?>" id="stripe_stripe_customer_id" />
								</li>
								<li>
									<?php echo $this->getPaymentHtml(); ?>
								</li>
							</ul>
						</li>
					<?php else: ?>
						<input type="hidden" name="stripe_customer_id" value="" id="stripe_stripe_customer_id" /> 
					<?php endif; ?> 
				</ul>
			</div>
		</form>
		<span class="please-wait" id="stripe-please-wait" style="display:none;">
			<img src="<?php $this->getSkinUrl("images/opc-ajax-loader.gif") ?>" alt="Loading next step..." title="Loading next step..." class="v-middle"> Loading next step...
		</span>
</div>

<div class="buttons-set">
	<p class="back-link"><a href="<?php echo $this->escapeHtml($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
</div>




<script type="text/javascript">
//<![CDATA[
	Stripe.setPublishableKey('<?php echo $this->getPublishableKey() ?>');

	var loadWaiting = false;
	
	var form = new VarienForm('stripe-payment');
	
	<?php if ($this->getIsStripeCustomer()) : ?>
		$('stripe-update-payment').observe('click',function(event){
			Event.stop(event);
			if ($('stripe-change-payment-form').visible()) {
				$('stripe-change-payment-form').hide();
				$('stripe-payment-details').show();
				$('stripe_create_stripe_customer').value = '0';
				$('stripe_create_stripe_customer').checked = '';
				$(this).update("Edit");
			} else {
				$(this).update("Use Existing");
				$('stripe-change-payment-form').show();
				$('stripe-payment-details').hide();
				$('stripe_create_stripe_customer').value = "1";
				$('stripe_create_stripe_customer').checked = 'checked';
			}
		});	

		$('stripe-delete-payment').observe('click',function(event) {
			var request = new Ajax.Request(
                    '<?php echo $this->getUrl("stripe/index/delete") ?>',
                        {
                            method:'post',
                            onComplete: stripeComplete,
                            onSuccess: stripeSuccess,
                            onFailure: stripeFailure,
                            parameters: {stripe_customer_id:$F('stripe_stripe_customer_id')}
                        }
                    );
         });
		
	<?php endif; ?>

	saveStripePayment = function() {
	         var validator = new Validation($('stripe-payment'));
	         if (validator.validate()) {
		         setLoading(true);
	             if ($F('stripe_stripe_customer_id') == ""||$F("stripe_create_stripe_customer")=="1") {
	            	 Stripe.createToken({
	            		 name: $F("fullname"),
		            	 <?php if ($this->sendAddressData()) : ?>
			            	address_line1: $F("street_1"),
			            	address_line2: $F("street_2"),
			            	address_state: $F("region"),
			            	address_zip: $F("zip"),
			            	address_country: $F("country"),
		            	 <?php endif; ?>
	     				number: $F('stripe_cc_number'),
	     				<?php if ($this->hasVerification()) : ?>
	     				cvc: $F('stripe_cc_cid'),
	     				<?php endif; ?>
	     				exp_month: $F('stripe_expiration'),
	     				exp_year: $F('stripe_expiration_yr')
	     			}, stripeResponseHandler.bind(this));
	             } else {
	            	 var request = new Ajax.Request(
	                         '<?php echo $this->getUrl("stripe/index/save") ?>',
		                         {
		                             method:'post',
		                             onComplete: stripeComplete,
		                             onSuccess: stripeSuccess,
		                             onFailure: stripeFailure,
		                             parameters: Form.serialize($('stripe-payment'))
		                         }
		                     );
		             }
		         }
	    };

	    function disableEnableAll(element, isDisabled) {
	        var descendants = element.descendants();
	        for (var k in descendants) {
	            descendants[k].disabled = isDisabled;
	        }
	        element.disabled = isDisabled;
	    }
	    
	    function setLoading(state)
	    {
		    loadWaiting = state;
	    	var container = $('stripe-buttons-container');
	    	if (loadWaiting) {
            	container.addClassName('disabled');
            	container.setStyle({opacity:.5});
                disableEnableAll(container, true);
                Element.show('stripe-please-wait');
	    	} else {
		    	container.removeClassName('disabled');
		    	container.setStyle({opacity:1});
	            disableEnableAll(container, false);
	            Element.hide('stripe-please-wait');
	    	}
	    }

	    function stripeComplete(transport) {
		    setLoading(false);
	    }

	    function stripeSuccess(transport) {
		    setLoading(false);
	    	window.location.reload();
	    } 
	   

		function stripeFailure(transport) {
			if (transport && transport.responseText){
	            try{
	                response = eval('(' + transport.responseText + ')');
	            }
	            catch (e) {
	                response = {};
	            }
	        }
	        
			 if (response.error) {
	            if (response.fields) {
	                var fields = response.fields.split(',');
	                for (var i=0;i<fields.length;i++) {
	                    var field = null;
	                    if (field = $(fields[i])) {
	                        Validation.ajaxError(field, response.error);
	                    }
	                }
	                return;
	            }
	            alert(response.error);
	            return;
	        }
		}
		
		function stripeResponseHandler(status, response) {
		    if (response.error) {
		        alert(response.error.message);
		    } else {
		        var token = response['id'];
		        $('stripe_token').value = token;
		        var request = new Ajax.Request(
        			'<?php echo $this->getUrl("stripe/index/save") ?>',	
                 {
                     method:'post',
                     onComplete: stripeComplete,
                     onSuccess: stripeSuccess,
                     onFailure: stripeFailure,
                     parameters: Form.serialize($('stripe-payment'))
                 }
             );
	    }
	}
	
	<?php if ($this->sendAddressData()) : ?>
		var regionUpdater = new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
	<?php endif; ?>
		
//]]>
</script>
