<tr class="reward-point">
    <td colspan="<?php echo $this->getColspan(); ?>" style="<?php echo $this->getTotal()->getStyle() ?>" class="a-right totals-rewards">
        <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?><strong><?php endif; ?>
            <?php //echo $this->escapeHtml($this->getTotal()->getTitle()); ?>
            <?php $str = $this->getTotal()->getTitle();
				//coded by shivaji chauhan
				if(strpos($str, "smogi bucks used")!==FALSE){
					if(Mage::getSingleton('giftcards/session')->getActive() == "1" && Mage::helper('giftcards')->getCustomerBalance(Mage::getSingleton('customer/session')->getCustomer()->getId()))
					{
						echo "SMOGI Bucks, Gift Card";
					}else{
						echo "SMOGI Bucks";
					}
				}else{
					echo  $str;
				}
				//coded by shivaji chauhan
			?>
			<?php //echo $this->__('SMOGI Bucks'); ?>
        <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?></strong><?php endif; ?>
    </td>
    <td style="<?php echo $this->getTotal()->getStyle() ?>" class="a-right">
        <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?><strong><?php endif; ?>
            <?php 
				$str = $this->helper('checkout')->formatPrice($this->getTotal()->getValue());
				
				if(strpos($str, "-")!==FALSE)
					$str = str_replace("-", "&ndash;", $str);
					
				echo $str;
			?>
        <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?></strong><?php endif; ?>
    </td>
</tr>
			
			<?php
			if(Mage::getSingleton('checkout/session')->getQuote()->getCouponCode()) { ?>
			<tr class="finalsale_row">
			<td>
            <span class='finalsale_txt_review'>These items are final sale. No exchanges or returns.</span>
			</td>
			<td>&nbsp;</td>
			</tr>
			<?php } ?>
			
