<tr class="reward-point">
    <td colspan="<?php echo $this->getColspan(); ?>" style="<?php echo $this->getTotal()->getStyle() ?>" class="a-right totals-rewards">
        <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?><strong><?php endif; ?>
            <?php //echo $this->escapeHtml($this->getTotal()->getTitle()); ?>
            <?php $str = $this->getTotal()->getTitle();
			
				if(strpos($str, "smogi bucks used")!==FALSE)
					echo "SMOGI Bucks";
				else
					echo  $str;
			?>
			<?php //echo $this->__('SMOGI Bucks'); ?>
        <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?></strong><?php endif; ?>
    </td>
    <td style="<?php echo $this->getTotal()->getStyle() ?>" class="a-right">
        <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?><strong><?php endif; ?>
            <?php 
				$str = $this->helper('checkout')->formatPrice($this->getTotal()->getValue());
				
				if(strpos($str, "-")!==FALSE)
					$str = str_replace("-", "&ndash;", $str);
					
				echo $str;
			?>
        <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?></strong><?php endif; ?>
    </td>
</tr>
