<tr class="reward-point">
    <td colspan="<?php echo $this->getColspan(); ?>" style="<?php echo $this->getTotal()->getStyle() ?>" class="a-right totals-rewards">
        <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?><strong><?php endif; ?>
            <?php //echo $this->escapeHtml($this->getTotal()->getTitle()); ?>
            <?php $str = $this->getTotal()->getTitle();
			
				if(strpos($str, "smogi bucks used")!==FALSE)
					echo "SMOGI Bucks";
				else
					echo  $str;
			?>
			<?php //echo $this->__('SMOGI Bucks'); ?>
        <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?></strong><?php endif; ?>
    </td>
    <td style="<?php echo $this->getTotal()->getStyle() ?>" class="a-right">
        <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?><strong><?php endif; ?>
            <?php 
				//$str = $this->helper('checkout')->formatPrice($this->getTotal()->getValue());
                $number = $this->getTotal()->getValue();
                $number = number_format((float)$number, 2, '.', '');

				if(strpos($number, "-")!==FALSE)
					$number = str_replace("-", "&ndash;$", $number);
					
				echo "<span class='price'>$number</span>";
			?>
        <?php if ($this->getRenderingArea() == $this->getTotal()->getArea()): ?></strong><?php endif; ?>
    </td>
</tr>
			<?php
			if(Mage::getSingleton('checkout/session')->getQuote()->getCouponCode()) { ?>
			<tr class="finalsale_row">
			<td>
            <span class='finalsale_txt_review'>These Items are Final Sale</span>
			</td>
			<td>&nbsp;</td>
			</tr>
			<?php } ?>