<?php
$storeId = Mage::app()->getStore()->getStoreId();
$catId  = Mage::getModel('catalog/layer')->getCurrentCategory()->getId();
$_helper = Mage::helper('catalog/output');

$productCollection = Mage::getModel('catalog/category')->load($catId)
    ->getProductCollection()
    ->addAttributeToSelect('*');

$cities = array();
$latlongs = array();
$cityTimes = array();

$resourceModel = Mage::getResourceModel('catalog/product');

/***************** get all colors from database ***********************/
$allColors = array();
$allColorAttribute = Mage::getModel('eav/config')->getAttribute('catalog_product', 'color'); //here, "color" is the attribute_code
$allColorOptions = $allColorAttribute->getSource()->getAllOptions(true, true);
foreach ($allColorOptions as $instance) {
    if (!array_key_exists($instance['value'], $allColors)) {
        $allColors[$instance['value']] = $instance['label'];
    }
}
/***************** get all sizes from database ***********************/
$allSizes = array();
$allSizeAttribute = Mage::getModel('eav/config')->getAttribute('catalog_product', 'size'); //here, "color" is the attribute_code
$allSizeOptions = $allSizeAttribute->getSource()->getAllOptions(true, true);
foreach ($allSizeOptions as $instance) {
    if ($instance['label'] != "") {
        if(is_numeric($instance['label']) && intval($instance['label'])>12)
            continue;

        if(strpos(strtoupper($instance['label']), "T")!==false)
            continue;

        $allSizes[$instance['label']] = $instance['value'];
    }
}
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
    <?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<div class="wrapper">
    <?php echo $this->getChildHtml('global_notices') ?>
    <div class="shopping-cart"></div>
    <div class="page">

        <div id="top_banner">
            <p>YOGASMOGA 2015 Holiday Giftsets: Available Until 12.30.2015</p>
        </div>

        <?php echo $this->getChildHtml('header') ?>

        <div class="ys_in_wanderland">
            <h1 class="page-title">YS IN WANDERLAND</h1>

            <p class="page-sub-title">2015 HOLIDAY GIFT SETS</p>

            <p class="line"></p>
        </div>
        <div class="top_banners">
            <div class="gift_sets_container">
                <?php
                $first = true;
                foreach($productCollection as $_product_single)
                {
                    $_product = Mage::getModel('catalog/product')->load($_product_single->getId());

                    if($first){
                        $first = false;
                        $firstProduct = $_product;
                    }

                    $_gallery = Mage::getModel('catalog/product')->load($_product->getId())->getMediaGalleryImages();
                    if (isset($_gallery)) {
                        foreach ($_gallery as $_image) {
                            $imageLabelData = json_decode(trim($_image->getLabel()), true);
                            $dataMap = $imageLabelData['dataMap'];
                            $person = $imageLabelData['person'];
                            break;
                        }
                    }

                    $personClass = "person." . $person;
                ?>
                <div class="gift_set_link <?php echo $personClass;?> active" data-map="<?php echo $dataMap;?>">
                    <!--top,left-->
                    <p class="pname"><?php echo $_product->getName();?></p>SET

                    <p class="pprice">$<?php echo round($_product->getPrice(),0);?></p>
                </div>
                <?php } ?>
            </div>
            <div class="map_data_section">
                <div class="map_data_container">
                    <div class="box coordinate">
                        <div class="time">
                            <div></div>
                        </div>
                        <p class="latlong"></p>
                    </div>
                    <div class="box set_name">
                        <p class="page-title_fixed">YS IN WANDERLAND</p>
                        <p class="product_name"><?php echo $firstProduct->getName();?></p>
                        <p class="product_price">$<?php echo round($firstProduct->getPrice(),0);?></p>
                    </div>
                    <div class="box map">
                        <span class="world_map">
                            <i></i>
                        </span>

                        <div class="temprature">
                            <div><span class="temp"></span> 42&deg;F</div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="setmargin" style="height: 160px; display: none;"></div>
        <div id="fullpage" class="slider set_section">

        <?php
        foreach($productCollection as $_product_single)
        {
            $_product = Mage::getModel('catalog/product')->load($_product_single->getId());
            $setProductUrl = $_product->getProductUrl();

            $_childProducts = Mage::getModel('catalog/product_type_configurable')->getUsedProducts(null, $_product_single);
            foreach($_childProducts as $simple) {
                $stock = Mage::getModel('cataloginventory/stock_item')->loadByProduct($simple)->getQty();
                break;
            }

            $bundled_product_ids = $resourceModel->getAttributeRawValue($_product->getId(), 'bundle_products', $storeId);

            if(isset($bundled_product_ids))
                $bundled_product_ids = trim($bundled_product_ids);

            $ar_bundled_product_ids = explode(",", $bundled_product_ids);

            $ar_bundle_sizes = array();

            /************ get color code of configurable product **************/
            $productAttributeOptions = $_product->getTypeInstance(true)->getConfigurableAttributesAsArray($_product);
            foreach ($productAttributeOptions as $productAttribute) {
                foreach ($productAttribute['values'] as $attribute) {
                    if ($productAttribute['label'] == 'Color') {
                        $gift_simple_color = $attribute['value_index'];
                        break;
                    }
                }
            }
            /************ get color code of configurable product **************/

            $gift_simple_id = $_product_single->getId();
            $gift_bundle_count = count($ar_bundled_product_ids);

            for($i=0;$i<count($ar_bundled_product_ids);$i++) {

                $ar_id_color_code = explode(":", $ar_bundled_product_ids[$i]);          // id:color_code

                $bundle_configurable_id = $ar_id_color_code[0];
                $bundle_color_id = $ar_id_color_code[1];

                $_bundle_product = Mage::getModel('catalog/product')->load(intval($bundle_configurable_id));
                $bundledProductUrl = $_bundle_product->getProductUrl() . '?color=' . $bundle_color_id;

                $_gallery = Mage::getModel('catalog/product')->load($_bundle_product->getId())->getMediaGalleryImages();

                $bundle_product_images = array();

                if (isset($_gallery)) {
                    foreach ($_gallery as $_image) {
                        $imageLabelData = json_decode(trim($_image->getLabel()), true);

                        if ($imageLabelData == NULL || strcasecmp($imageLabelData['type'], "product image") != 0)
                            continue;

                        if ($imageLabelData['color'] == $ar_id_color_code[1]) {
                            $url = $this->helper('catalog/image')->init($_bundle_product, 'thumbnail', $_image->getFile())->constrainOnly(TRUE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize(100, 100)->setQuality(100);
                            $bundle_product_images[] = $url;
                        }
                    }
                }

                $_childProducts = Mage::getModel('catalog/product_type_configurable')->getUsedProducts(null, $_bundle_product);
                $ar_child_sizes = array();
                foreach ($_childProducts as $_childProduct) {
                    $size = $_childProduct->getAttributeText('size');

                    if(is_numeric($size) && intval($size)>12)
                        continue;

                    if(strpos(strtoupper($size), "T")!==false)
                        continue;

                    if (is_numeric($size))
                        $ar_child_sizes[] = intval($size);
                    else
                        $ar_child_sizes[] = $size;
                }

                $ar_child_sizes = array_unique($ar_child_sizes);
                ksort($ar_child_sizes);

                $ar_bundle_sizes[$i] = array(
                    "product" => $_bundle_product,
                    "price" => round($_bundle_product->getPrice(),2),
                    "sizes" => $ar_child_sizes,
                    "images" => $bundle_product_images,
                    "color" => $allColors[$bundle_color_id],
                    "color_code" => $bundle_color_id,
                    "url" => $bundledProductUrl
                );
            }

            // main set images
            $_gallery = Mage::getModel('catalog/product')->load($_product->getId())->getMediaGalleryImages();
            if(isset($_gallery)) {
                foreach ($_gallery as $_image) {
                    $imageLabelData = json_decode(trim($_image->getLabel()), true);
                    $city = $imageLabelData["city"];
                    $latlong = $imageLabelData["latlong"];
                    $cityTime = $imageLabelData["cityTime"];

                    $cities[] = $city;
                    $latlongs[] = $latlong;
                    $cityTimes[] = $cityTime;
                    break;                    // we want to read first image only
                }
            }
            ?>

            <div class="section contain_product">
                <div class="product_set">
                    <div class="side2 flipped">

                        <span class="reverse_flip">&plus;</span>

                        <div class="product_container">
                            <div class="thumbnails">
                                <div class="thumbnail">
                                    <img src="http://cdn.yogasmoga.com/media/catalog/product/cache/1/thumbnail/138x180/17c2151a3f12ebf0226ce1e5826e3ed5/u/-/u--me-twist-bra-c6-helix-2.jpg" />
                                </div>
                                <div class="thumbnail">
                                    <img src="http://cdn.yogasmoga.com/media/catalog/product/cache/1/thumbnail/138x180/17c2151a3f12ebf0226ce1e5826e3ed5/u/-/u--me-twist-bra-c6-helix-2.jpg" />
                                </div>
                                <div class="thumbnail">
                                    <img src="http://cdn.yogasmoga.com/media/catalog/product/cache/1/thumbnail/138x180/17c2151a3f12ebf0226ce1e5826e3ed5/u/-/u--me-twist-bra-c6-helix-2.jpg" />
                                </div>
                            </div>
                            <div class="product_slider">
                                <div class="slider">
                                    <img src="http://cdn.yogasmoga.com/media/catalog/product/cache/1/thumbnail/771x700/17c2151a3f12ebf0226ce1e5826e3ed5/u/-/u--me-twist-bra-c6-helix-1_013.jpg" />
                                </div>
                            </div>
                            <div class="product_filters">
                                <p class="product_name"><?php echo $_product->getName();?></p>

                                <p class="product_price">$<?php echo round($_product->getPrice(),0);?> <span><?php echo round($stock,2);?> SETS REMAINING</span></p>

                                <?php
                                    $sizeDivCount = -1;
                                    foreach($ar_bundle_sizes as $product=>$data) {
                                        ++$sizeDivCount;
                                ?>
                                <div class="set_item">

                                    <div class="product_detail product-detail-<?php echo $sizeDivCount;?>" rel="<?php echo $data["product"]->getId();?>">
                                        <p class="pname"><a href="<?php echo $data["url"];?>" target="_blank"><?php echo $data["product"]->getName();?></a> <span class="pcolor product-color-<?php echo $sizeDivCount;?>" rel="<?php echo $data["color_code"];?>"><?php echo $data["color"];?></span></p>

                                        <p class="psize">
                                            <span class="gap">SIZE:</span>
                                            <span class="sizes">
                                                <?php
                                                    foreach($allSizes as $key => $value){
                                                    foreach ($data["sizes"] as $size) {

                                                        if($size==$key) {
                                                            ?>
                                                            <span class="size size-<?php echo $sizeDivCount; ?>"
                                                                  rel="<?php echo $value; ?>"><?php echo $key; ?></span>
                                                            <?php
                                                        }
                                                    }
                                                }
                                                ?>
                                            </span>

                                        </p>

                                        <!--<span class="size-chart-bundle">SIZE CHART</span>-->

                                    </div>
                                </div>

                                <?php } ?>

                                <div class="add_to_wishlist" rel="<?php echo $gift_simple_id;?>:<?php echo $gift_simple_color;?>:<?php echo $gift_bundle_count;?>">ADD TO WISHLIST +</div>
                                <div class="add_to_bag" rel="<?php echo $gift_simple_id;?>:<?php echo $gift_simple_color;?>:<?php echo $gift_bundle_count;?>">ADD TO BAG</div>
                                <p class="free_shipping">Free and fast shipping to US and Canada</p>
                            </div>
                        </div>
                    </div>
                    <div class="side1">
                        <p class="product_name"><?php echo $_product->getName();?></p>

                        <p class="product_price">$<?php echo round($_product->getPrice(),0);?></p>

                        <p class="buy_product"><a class="quick_look" href="">QUICK LOOK <b>&gt;</b></a><a class="buy_gift_set" href="<?php echo $setProductUrl;?>">GET <?php echo $_product->getName();?> <b>&gt;</b></a></p>

                        <p class="toggle_description">SEE DETAILS <b>&gt;</b></p>
                    </div>
                </div>

                <div class="description_box">
                    <div class="rel_container">
<!--                        <span class="close_desc">&plus;</span>-->
                        <div class="set_desc">

                            <b><?php echo $_product->getName();?></b><br/>
                            <p><?php echo $_product->getDescription();?></p>

                        </div>
                        <div class="middle_desc">
                            <?php
                                foreach($ar_bundle_sizes as $data){
                            ?>
                            <div>
                                <b><?php echo $data["product"]->getName();?></b><br/>
                                <span class="desc_product_color"><?php echo $data["color"];?></span><br/>
                                $<?php echo $data["price"];?><br/>
                                <a href="<?php echo $data["url"];?>" target="_blank">Sold Individually</a>
                            </div>
                            <?php } ?>
                        </div>
                        <div class="right_desc">
                            <p>SEE <?php echo $_product->getName();?> SET &gt;</p>
                            <b><?php echo round($stock,0);?> left</b>
                        </div>
                    </div>
                </div>
            </div>

            <?php } ?>

                <script type="text/javascript">
                    <?php foreach($cities as $city){ ?>
                    cities.push("<?php echo $city;?>");
                    temperatures.push('');
                    <?php } ?>

                    <?php foreach($latlongs as $latlong){ ?>
                    latlongs.push("<?php echo $latlong;?>");
                    <?php } ?>

                    <?php foreach($cityTimes as $cityTime){ ?>
                    cityTimes.push("<?php echo $cityTime;?>");
                    <?php } ?>
                </script>

                <?php echo $this->getChildHtml('footer') ?>
                <?php echo $this->getChildHtml('before_body_end') ?>
            </div>
        </div>
        <?php echo $this->getAbsoluteFooter() ?>
</body>
</html>