<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
    <?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
<div class="wrapper">
    <?php echo $this->getChildHtml('global_notices') ?>
    <div class="shopping-cart"></div>
    <div class="page">
        <?php echo $this->getChildHtml('header') ?>
        <div class="top-fixed-header">
            <div id="weather"></div>
        </div>

        <div id="fullpage">
            <?php
            $catId  = Mage::getModel('catalog/layer')->getCurrentCategory()->getId();
            $_helper = Mage::helper('catalog/output');
            $productCollection = Mage::getModel('catalog/category')->load($catId)
                ->getProductCollection()
                ->addAttributeToSelect('*');

            ?>
            <?php 
			$cities = array();
			
			foreach($productCollection as $_product)
            { 
				$_gallery = Mage::getModel('catalog/product')->load($_product->getId())->getMediaGalleryImages();
				
				if(isset($_gallery)){
					foreach ($_gallery as $_image) {
						$imageLabelData = json_decode(trim($_image->getLabel()), true);
						$city = $imageLabelData["city"];
						
						$cities[] = $city;
						break;					// we want to read first image only
					}
				}
			?>
                <div class="section combos">
					<a href="<?php echo $_product->getProductUrl();?>">
                        <img src="<?php echo $this->helper('adaptiveResize/image')->init($_product, 'image')->resize(400); ?>" width="400" height="400"/>
                        <span style="display:block"><?php echo $_product->getName(); ?></span>
                    </a>
                </div>
            <?php 
			}
			?>
			
			<script type="text/javascript">
				<?php foreach($cities as $city){ ?>
					cities.push("<?php echo $city;?>");
					temperatures.push('');
				<?php } ?>
			</script>
        </div>
        <?php echo $this->getChildHtml('footer') ?>
        <?php echo $this->getChildHtml('before_body_end') ?>
    </div>
</div>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>