<div class="2-columns-wrapper" style="padding:29px 40px 0 40px;">
    <h1 style="display:none;">Help</h1>
    <div class="side-menu-bar f-left l-align" style="margin-top:0;">
        <ul>
            <li data-blockid="faq"><a href="#faq" class="current">FAQ</a></li>
            <li data-blockid="shipping-returns"><a href="#shipping-returns">Shipping and Returns</a></li>
            <li data-blockid="size-chart"><a href="#size-chart">Size Charts</a></li>
            <li data-blockid="product-care"><a href="#product-care">Product Care</a></li>
            <li data-blockid="email-us"><a href="#email-us">Email Us</a></li>
        </ul>
        <div class="contact-summary">
            <div><span class="call-icon"></span><span><a href="mailto:hello@yogasmoga.com">Contact us</a></span><br />888-990-YOGA (9642)<br /><a href="mailto:hello@yogasmoga.com">hello@yogasmoga.com</a></div>
            <div><span class="chat-icon"></span><span><a href="javascript:void($zopim.livechat.window.show())">Chat With Us</a></span><br /><span class="chat-status"><img alt="" src="http://192.168.2.101/skin/frontend/new-yogasmoga/yogasmoga-theme/images/footer/offline.png" class="online-status-icon"> offline now</span></div>
            <div><span class="email-us"></span><span><a href="mailto:hello@yogasmoga.com">Email Us</a></span><br />Any unanswered questions,<br />comments or suggestions?</div>
        </div>
    </div>
    <div class="pg-content"></div>
    <div class="new-bot-divider"></div>
</div>
<div class="clear-fix"></div>