<!DOCTYPE HTML>
<html>
<head>
    <meta name="viewport" content="width=device-width">

    <?php
    if ($this->getRequest()->getParam('video') == 'true') {
        ?>
        <meta property="og:image"
              content="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/homepage/video/youtube_fbthumb01.png"/>
        <meta property="og:image"
              content="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/homepage/video/youtube_fbthumb02.png"/>
        <meta property="og:image"
              content="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/homepage/video/youtube_fbthumb03.png"/>
        <meta property="og:title" content="YOGASMOGA | Did You Take a Breath Today?"/>
        <meta property="og:description" content="YOGASMOGA makes technical performance clothes for women & men for yoga, running, spin, workouts, and more. Free shipping to US and Canada."/>
    <?php
    } else {
        ?>
        <meta property="og:image"
              content="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/homepage/main_section/Untitled_Panorama2_c_1.jpg"/>
        <meta property="og:image"
              content="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/homepage/main_section/yogasmoga_mood_2395.jpg"/>
        <meta property="og:image"
              content="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/Yogasmoga_op.jpeg"/>
        <meta property="og:title" content="YOGASMOGA"/>
        <meta property="og:description" content="YOGASMOGA makes technical performance apparel for women & men for yoga, running, spin, workouts, and more. Free shipping to US and Canada."/>
    <?php
    }
    ?>
    <?php echo $this->getChildHtml('head') ?>
    <?php
    //if(Mage::getSingleton('core/session')->getShowVideo())
    if ($this->getRequest()->getParam('video') == 'true') {
//Mage::getSingleton('core/session')->setShowVideo(false);
        ?>
        <script type="text/javascript">
            var loc = window.location;
            history.replaceState("", document.title, loc.pathname + "breathe");
            jQuery(window).load(function () {
                setTimeout(function () {
                    $j("#hmpagevideo").trigger('click')
                }, 1000);
            });
        </script>
    <?php
    }
    ?>
    <script type="text/javascript">
        jQuery(window).load(function () {

            jQuery(".slider_li").css('cursor', 'pointer');
            jQuery(".slider_li").click(function(){
                if(jQuery(this).attr("moveto")!=undefined) {
                    var redirectWindow = window.open(jQuery(this).attr('rel'), '_blank');
                    redirectWindow.location;
                }
                else
                    window.location = jQuery(this).attr('rel');
            });

            jQuery("div.showloading").removeClass('showloading');
            setTimeout(function () {
                setfullscreenheight();
            }, 50);
//            var bannerImg = document.getElementById("bannerimg").complete;
//            if(bannerImg){
//                jQuery(".share-strip, .new-arrivals-block").animate({opacity:1},100);
//            }

            jQuery('.namaskar-overlay1').fadeOut('slow');
        });
        jQuery(document).ready(function () {
            setTimeout(function () {
                jQuery("div.page-overlayy").remove();
                jQuery("body").css('overflow', 'auto');
            }, 500);
        });
    </script>
    <div class="namaskar-overlay1">&nbsp;</div>
</head>
<body class="<?php echo $this->getBodyClass() ? $this->getBodyClass() : '' ?>"
      style="margin-right:17px;overflow:hidden;">
<?php echo $this->getChildHtml('after_body_start') ?>
<div class="wrapper">
<!-- pageOverlay -->
<div class="page-overlayy" style="background:#fff; position:fixed; top:0; left:0; right:0; bottom:0; z-index:999;">
    &nbsp;</div>
<!-- pageOverlay -->
<?php echo $this->getChildHtml('global_notices') ?>
<!-- shopping cart -->
<div class="shopping-cart"></div>
<!-- shopping cart -->
<div class="page">
<!-- header -->
<?php echo $this->getChildHtml('header') ?>
<!-- header -->
<!-- pagewrapper -->
<div id="pagecontainer">
<!-- sliderBanner -->

    <div class="flexslider home-slider" id="bucket1_slider">
    <ul class="slides">

        <li class="slider_li" rel="/women/bottoms/leggings" style="width: 100%; float: left; margin-right: -100%; position: relative; opacity: 0; display: block; z-index: 1;">

            <img draggable="false" src="<?php echo Mage::getUrl('/', array('_secure'=>true));?>media/wysiwyg/new-design-images/homepage/homepage-Womens.jpg"/>
            <div style="top: 16%; left:14%" class="over-the-slide ">
                <div style="float: left; text-align:center; padding-left:30px !important">
                    <div style="text-transform: uppercase; color: #666666!important;" class="avant_demi_bold">LOVE MORE
                        <div style="font-size: 25px; line-height: 32px; font-family: AvantGardeGothicITCW01X;">With our selection of
                            women’s leggings</div>
                    </div>

                    <div class="text-align-middle">

                        <a href="/women/bottoms/leggings" class="learn-more shop-mens1"
                           style="color: #666666 !important; border: none !important;margin: 32px 0 0!important; background: none !important;">SHOP
                            WOMEN’S LEGGINGS <span style="color:#ff0000"> &gt;</span></a>
                    </div>
                </div>

            </div>
        </li>

        <li class="slider_li" rel="/men" style="width: 100%; float: left; margin-right: -100%; position: relative; opacity: 0; display: block; z-index: 1;">

            <img draggable="false" src="<?php echo Mage::getUrl('/', array('_secure'=>true));?>media/wysiwyg/new-design-images/homepage/homepage-mens.jpg"/>
            <div class="over-the-slide " style="top: 17%; left:5%">
                <div style="float: left; text-align:CENTER; padding-left:30px !important">
                    <div style="text-transform: uppercase; color: rgb(255, 255, 255);" class="avant_demi_bold">BREATHE.<br><span
                            class="avant_extra_light">RUN. yoga.</span>
                    </div>

                    <div class="text-align-middle">

                        <a style="color: #fff !important; border: none !important;margin: 32px 0 0!important; background: none !important;"
                           class="learn-more shop-mens1" href="/men">SHOP MEN <span
                                style="color:#ff0000"> &gt;</span></a>
                    </div>
                </div>

            </div>
        </li>

        <li class="slider_li" rel="/women/rangoli-collection" style="width: 100%; float: left; margin-right: -100%; position: relative; opacity: 0; display: block; z-index: 1;">

            <img draggable="false" src="<?php echo Mage::getUrl('/', array('_secure'=>true));?>media/wysiwyg/new-design-images/homepage/rangoli-banner-slide-2.jpg">
            <div class="over-the-slide " style="padding-left: 10%; top: 33%;">
                <div style="">
                    <div class="avant_demi_bold" style="color:#fff;">COLOR INGRAINED</div>

                    <div style="font-family: itcavantgardeprobk; font-size: 28px; line-height: 36px; color: rgb(255, 255, 255); margin-top: 9% ! important;"><span style="font-family:AvantGardeGothicITCW01D;">RANGOLI </span><span style="font-family:AvantGardeGothicITCW01B"> COLLECTION</span></div>
                    <div class="text-align-middle">
                        <a href="/women/rangoli-collection" class="learn-more shop-mens1" style="color: rgb(255, 255, 255) ! important;border:none;">DISCOVER MORE <span style="color:red;"> &gt;</span></a>
                    </div>
                </div>
            </div>
        </li>

        <li class="slider_li" rel="/made-in-usa" style="width: 100%; float: left; margin-right: -100%; position: relative; opacity: 0; display: block; z-index: 1;">
            <img draggable="false" src="<?php echo Mage::getUrl('/', array('_secure'=>true));?>media/wysiwyg/new-design-images/homepage/homepage-made-in-usa.jpg"/>
            <div style="padding-left: 10%; top: 60%;" class="over-the-slide ">
                <div style="">
                    <div class="avant_demi_bold" style="color: rgb(85, 85, 85); font: 20px/25px gothambook;">Researched, developed,
                        designed, manufactured,<br>dyed, cut, stitched, packed &amp; shipped <br>in the USA
                    </div>

                    <div class="text-align-middle">
                        <a style="border-width: medium medium 1px; border-style: none none solid; border-color: -moz-use-text-color -moz-use-text-color rgb(217, 13, 61); -moz-border-top-colors: none; -moz-border-right-colors: none; -moz-border-bottom-colors: none; -moz-border-left-colors: none; border-image: none; color: rgb(85, 85, 85);"
                           class="learn-more shop-mens1" href="/made-in-usa">LEARN MORE </a>
                    </div>
                </div>
            </div>

        </li>

<?php /*
        <li class="slider_li" rel="/women/bottoms/leggings" style="width: 100%; float: left; margin-right: -100%; position: relative; opacity: 0; display: block; z-index: 1;">

            <img draggable="false" src="<?php echo Mage::getUrl('/', array('_secure'=>true));?>media/wysiwyg/new-design-images/homepage/homepage-Womens.jpg"/>
            <div style="top: 16%; left:14%" class="over-the-slide ">
                <div style="float: left; text-align:center; padding-left:30px !important">
                    <div style="text-transform: uppercase; color: #666666!important;" class="avant_demi_bold">MOVE BR <span
                            class="avant_extra_light">(EASY)</span><!--<BR>UNITING <SPAN CLASS="avant_extra_light">PEOPLE</SPAN>-->
                        <p style="font-size: 25px; line-height: 32px; font-family: AvantGardeGothicITCW01X;">With our selection of
                            women’s leggings</p>
                    </div>

                    <div class="text-align-middle">

                        <a href="/women/bottoms/leggings" class="learn-more shop-mens1"
                           style="color: #666666 !important; border: none !important;margin: 32px 0 0!important; background: none !important;">SHOP
                            WOMEN’S LEGGINGS <span style="color:#ff0000"> &gt;</span></a>
                    </div>
                </div>

            </div>
        </li>
*/ ?>
    </ul>
    </div>
<!-- sliderBanner -->

<!-- signup new -->

<div class="share-strip">
   <div class="sign-up-new">
        <a href="javascript:void(0)">Sign up</a><span>& WE’LL SURPRISE YOU</span>
   </div>
</div>
<!-- signup new -->
<div class="clear-fix"></div>
<!-- middleContainer -->
<div class="cubix">
<!-- gridfull -->
<div class="gridfull ysfabricpart overridefix">
    <!-- grid6 -->
    <div class="grid65 f-left" id="grid1-left">
        <!-- slider -->
        <div class="sliderImg">
            <ul class="gridslider12">


                <li>
                    <img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/new-design-images/homepage/febric-tech.jpg' ?>" title="Fabric Tech. Zari Mesh"
                         alt="Fabric Tech. Zari Mesh"/>

                    <div class="contentSlider sliderContent" style="top:38.919552%;">
                        <div>
                            <h3 class="small-text">ys fabric tech</h3>

                           <!-- <h3 style="color: #fff!important;" class="large-text">AURUM® <br>
                                SAME GREAT TECH</h3>-->
                            <p class="large-text">AURUM<sup>&reg;</sup> <br>
                                SAME GREAT TECH</p>
                            <p class="large-text" style="margin-top: -10px;"><span>COLOR INFUSED</span></p>
                            <a href="/women/bottoms/rangoli/rangoli-run-jump-n-play-crop?color=274" class="shopnow-btn" style="margin-top:2.240325865580448065173116089613%; background: none !important;">SHOP NOW <span style="color:#ff0000"> &gt;</span></a>
                        </div>
                    </div>
                </li>


            </ul>
        </div>
        <!-- slider -->
    </div>
    <!-- grid6 -->
    <!-- grid35 -->
    <div class="grid35" id="grid1-right">
        <!-- partOne -->
        <div class="compressBox">
            <div style="top:27.894308943089430894308943089431%;font-family:FreightText-LightItalic;text-transform:none;" class="ctext">
                Consider the clothes<br>you wear.
                <span style="margin-top: 7px; border: none !important;"><a href="/women/rangoli-collection" class="learn-more" style="border: none !important">LEARN MORE <span style="color:#ff0000"> &gt;</span></a></span>
            </div>

        </div>
        <!-- partOne -->
        <!-- partTwo -->
        <a href="<?php echo $this->getBaseUrl() . 'ys-fabric-tech'; ?>">
            <div class="iconspartone" id="iconspartone">
                <div class="row">
<span>
<img src="<?php echo $this->getSkinUrl('images/new-elements/pilling.png') ?>" alt="Yogasmoga Anti-Pilling"/>
<span class="iconstxt">RESISTANCE TO PILLING</span>
</span>
<span>
<img src="<?php echo $this->getSkinUrl('images/new-elements/moisture.png') ?>" alt="Yogasmoga Moisture Wicking"/>
<span class="iconstxt">ADVANCED MOISTURE MANAGEMENT</span>
</span>
                </div>
                <div class="row">
<span>
<img src="<?php echo $this->getSkinUrl('images/new-elements/stretch.png') ?>" alt="Yogasmoga Stretch"/>
<span class="iconstxt">HIGH QUALITY STRETCH</span>
</span>
<span>
<img src="<?php echo $this->getSkinUrl('images/new-elements/usa.png') ?>" alt="Yogasmoga USA"/>
<span class="iconstxt">PROUDLY MADE IN THE USA</span>
</span>
                </div>
            </div>
        </a>
        <!-- partTwo -->
    </div>
    <!-- grid35 -->
</div>
<!-- gridfull -->
<!-- gridfull -->
<div class="gridfull yscolorpart overridefix">
    <!-- grid35 -->
    <div class="grid35">
        <!-- partOne -->
        <div class="multicolorcont">
            <div class="ctext" style="top: 38%;font-family:FreightText-LightItalic;text-transform:none;">
                Color your world&mdash;  <br>Colors that don’t bleed.
                <span style="margin-top: 2.1910569105691056910569105691057%; border: none !important;"><a class="learn-more white" href="/women/rangoli-collection" style="background: none !important;border:none;">LEARN MORE <span style="color:#ff0000"> &gt;</span></a></span>
            </div>
        </div>
        <!-- partOne -->
        <!-- partTwo -->
        <a href="<?php echo $this->getBaseUrl() . 'ys-color-tech'; ?>">
            <div class="iconspartone" id="iconsparttwo">
                <div class="row">
<span>
<img src="<?php echo $this->getSkinUrl('images/new-elements/eco.png') ?>" alt="Yogasmoga Eco"/>
<span class="iconstxt">ECO-FRIENDLY DYEING</span>
</span>
<span>
<img src="<?php echo $this->getSkinUrl('images/new-elements/colors.png') ?>" alt="Yogasmoga Colors"/>
<span class="iconstxt">COLORS THAT WON’T FADE</span>
</span>
                </div>
                <div class="row">
<span>
<img src="<?php echo $this->getSkinUrl('images/new-elements/accuracy.png') ?>" alt="Yogasmoga Accuracy"/>
<span class="iconstxt">COLOR ACCURACY</span>
</span>
<span>
<img src="<?php echo $this->getSkinUrl('images/new-elements/mis.png') ?>" alt="Yogasmoga Icon"/>
<span class="iconstxt">DYEING PROUDLY DONE IN THE USA</span>
</span>
                </div>
            </div>
        </a>
        <!-- partTwo -->
    </div>
    <!-- grid35 -->
    <!-- grid6 -->
    <div class="grid65 f-right ">
        <!-- slider -->
        <div class="sliderImg">
            <ul class="gridslider22">


                <li>
                    <!--<img class="img-responsive" src="<?php /*echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'wysiwyg/new-design-images/right-1.jpg'*/?>" alt="Mens Sunday Tee" />-->
                   <img class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/new-design-images/homepage/color-tech.jpg' ?>"
                         alt="long sleeve tee Rudhira"/>

                    <div class="contentSlider" style="top:36.659877800407331975560081466395%">
                        <div>
                            <p class="small-text">YS COLOR TECH</p>

                            <p class="large-text"> PAINT IT<br/><span class="aurum">NOT PLAIN, JUST PUNCH</span></p>
                            <a href="/women/rangoli-collection" class="shopnow-btn" style="margin-top:1.0366598778004073319755600814664%;background: none !important;">SHOP NOW <span style="color:#ff0000"> &gt;</span></a>
                        </div>
                    </div>
                </li>

            </ul>
        </div>
        <!-- slider -->
    </div>
    <!-- grid6 -->
</div>
<!-- gridfull -->
<!-- gridfull -->
<div class="gridfull factorypart overridefix">
    <!-- grid6 -->
    <div class="grid65 f-left">
        <!-- slider -->
        <div class="sliderImg">
            <img class="img-responsive"
                 src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/new-design-images/factoryimg.jpg' ?>"
                 alt="Made in USA and NYC. YOGASMOGA" title="Made in USA and NYC. YOGASMOGA"/>

            <div class="contentSlider mistext" style="top:38.911201629327902240325865580448%">
                <div>
                    <p class="small-text">RESPONSIBLE PRODUCTION</p>

                    <h2 class="large-text" style="margin-bottom: 6px;">MADE IN USA <br/><span>2 US FACTORIES 2000 US WORKERS</span>
                    </h2>
                    <a href="/made-in-usa" class="learn-more">LEARN MORE</a>
                </div>
            </div>
        </div>
        <!-- slider -->
    </div>
    <!-- grid6 -->
    <!-- grid35 -->
    <div class="grid35">
        <!-- partOne --><a href="<?php echo $this->getBaseUrl() . 'made-in-usa'; ?>">
            <div class="factorythread">
                <div class="ctext" style="top:27.994308943089430894308943089431%;">STREAMLINING<br/>HELPING<br/>REDUCING<br/>RAISING
                </div>
            </div>
        </a>
        <!-- partOne -->
        <!-- partTwo -->
        <a href="<?php echo $this->getBaseUrl() . 'made-in-usa'; ?>">
            <div class="usamap"></div>
        </a>
        <!-- partTwo -->
    </div>
    <!-- grid35 -->
</div>
<!-- gridfull -->
<!-- gridfull -->
<div class="gridfull namaskarpart overridefix">
    <!-- grid35 -->
    <div class="grid35">
        <!-- partOne -->
        <div class="supportnamaskar">
            <div class="ctext"><a href="/women/accessories/namaskar-bracelet" class="learn-more">SUPPORT NAMASKÁR</a>
            </div>
        </div>
        <!-- partOne -->
        <!-- partTwo -->
        <a href="<?php echo $this->getBaseUrl() . 'namaskar'; ?>">
            <div class="raisingfunds">
                <div class="ctext" style="top:34.734693877551020408163265306122%;">RAISING THE FUNDS &<br/>MAKING
                    CHANGES<br/>IN THE WORLD
                </div>
            </div>
        </a>
        <!-- partTwo -->
    </div>
    <!-- grid35 -->
    <!-- grid6 -->
    <div class="grid65 f-right">
        <!-- slider -->
        <div class="sliderImg">
            <img class="img-responsive"
                 src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/new-design-images/namaskar.jpg' ?>"
                 alt="Namaskar Bracelet"/>

            <div class="contentSlider mistext" style="top:38.085539714867617107942973523422%;">
                <div>
                    <p class="small-text" style="margin-bottom:3.1549898167006109979633401221996%;">GIVING IS A CORE
                        VALUE</p>

                    <p class="large-text" style="margin-bottom:4.5329938900203665987780040733198%;">NAMASKÁR FOUNDATION<br/>
                        <span>WE HAVE CREATED THE NAMASKÁR FOUNDATION BECAUSE WE CARE.</span></p>
                    <a href="/namaskar" class="learn-more">LEARN MORE</a>
                </div>
            </div>
        </div>
        <!-- slider -->
    </div>
    <!-- grid6 -->
</div>
<!-- gridfull -->
</div>
<div class="text"></div>
<!-- middleContainer -->
</div>
<!-- pagewrapper -->
<!-- footer -->
<?php echo $this->getChildHtml('footer'); ?>
<!-- footer -->
</div>
<?php echo $this->getChildHtml('before_body_end'); ?>
</div>
</div>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
