<?php
/**
 * J2T RewardsPoint2
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@j2t-design.com so we can send you a copy immediately.
 *
 * @category   Magento extension
 * @package    RewardsPoint2
 * @copyright  Copyright (c) 2009 J2T DESIGN. (http://www.j2t-design.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 ?>
 <?php
    //echo Mage::getModel('core/cookie')->get('afterlogindest');
    if(Mage::getModel('core/cookie')->get('afterlogindest') == "cart")
    {
        //Mage::getModel('core/cookie')->delete('afterlogindest');
        
        Mage::app()->getFrontController()->getResponse()->setRedirect(Mage::helper('core/url')->getHomeUrl()."checkout/cart");
        Mage::getModel('core/cookie')->set('afterlogindest', 'cart123', 0,'/');
    }
    if(Mage::getModel('core/cookie')->get('afterlogindest') == "giftofys")
    {
        Mage::app()->getFrontController()->getResponse()->setRedirect(Mage::helper('core/url')->getHomeUrl()."gift_of_ys#redeemcard");
        Mage::getModel('core/cookie')->set('afterlogindest', 'cart123', 0,'/');
    }
    
    //if(Mage::getSingleton('core/session')->getRedirect() == "cart")
//    {
//        Mage::app()->getFrontController()->getResponse()->setRedirect(Mage::helper('core/url')->getHomeUrl()."checkout/cart");
//        Mage::getSingleton('core/session')->setRedirect('');
//    }
    //if(Mage::getSingleton('core/session')->getRedirect() == "giftofys")
//    {
//        Mage::app()->getFrontController()->getResponse()->setRedirect(Mage::helper('core/url')->getHomeUrl()."gift_of_ys#redeemcard");
//        Mage::getSingleton('core/session')->setRedirect('');
//    }
?>
 <div class="myheader" style="margin-bottom: 7px;">MY ACCOUNT</div>
 <div class="account-nav">
	 <ul class="sub-nav">
	<li><a href="<?php echo Mage::getUrl('',array('_secure'=>true)); ?>sales/order/history">View Past Orders</a></li>
	<li><a href="<?php echo Mage::getUrl('',array('_secure'=>true)); ?>wishlist">Wish list</a></li>
	<li><a href="<?php echo Mage::getUrl('',array('_secure'=>true)); ?>rewardpoints/index/referral/">Refer A Friend</a></li>
    <li><a href="<?php echo Mage::getUrl('',array('_secure'=>true)); ?>customer/address">Address Book</a></li>
	</ul>
</div>
 <div class="myaccountdashboard">
    <?php echo $this->getChildHtml('hello'); ?>
    <table style="width: 100%;">
        <?php echo $this->getChildHtml('info') ?> 
        <?php //echo $this->getChildHtml('address') ?>
    </table> 
 </div>
 
<?php /* 
<div class="page-head">
    <h3><?php echo $this->__('My Dashboard') ?></h3>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php echo $this->getChildHtml('hello') ?>

<?php echo $this->getChildHtml('top') ?>

<div class="account-box ad-account-info box">
        <div class="box-account box-recent">
            <div class="box-head">
                <h2><?php echo $this->__('Points') ?></h2>
            </div>
            <?php echo $this->getChildHtml('points') ?>
        </div>
</div>

<div class="account-box ad-account-info box">
    <div class="head box-title">
        <h3><?php echo $this->__('Account Information') ?></h3>
    </div>
    <?php echo $this->getChildHtml('info') ?>
    <?php echo $this->getChildHtml('address') ?>
</div>


<?php echo $this->getChildHtml('info1') ?>
<?php echo $this->getChildHtml('info2') ?>
*/ ?>