<?php
$root = Mage::getBaseDir();

include_once($root . '/Ipinfo/Host.php');
include_once($root . '/Ipinfo/Ipinfo.php');

$ipInfo = new Ipinfo\Ipinfo();

if (!empty($_SERVER['HTTP_CLIENT_IP'])) {
    $ip = $_SERVER['HTTP_CLIENT_IP'];
} elseif (!empty($_SERVER['HTTP_X_FORWARDED_FOR'])) {
    $ip = $_SERVER['HTTP_X_FORWARDED_FOR'];
} else {
    $ip = $_SERVER['REMOTE_ADDR'];
}

$host = $ipInfo->getFullIpDetails($ip);

if (isset($host)) {
    $request_city = $host->getCity();
    $request_state = $host->getRegion();
    $request_zip = $host->getPostal();
}
else {
    $request_city = "N/A";
    $request_state = "N/A";
    $request_zip = "N/A";
}
?>

<div id="signing_popup" style="display: none;">
    <div class="signing_popup_wrapper">  
        <div class="sign-up-block f-left">
			<p class="c-align form-heading">NEW to YOGASMOGA</p>
			<p class="c-align" style="margin:0;"><img src="<?php echo $this->getSkinUrl('images/spread-heart.png')?>"/></p>
            <p class="c-align form-heading">Spread the SMOGI Love To Your Friends, <br/>Get 25% Off</p>
            <form id="sign-up-form" class="bl" action="" method="post">
                <input type="hidden" id="location_city" name="location_city" value="<?php echo $request_city;?>"/>
                <input type="hidden" id="location_state" name="location_state" value="<?php echo $request_state;?>"/>
                <input type="hidden" id="location_zip" name="location_zip" value="<?php echo $request_zip;?>"/>
                <table width="100%" cellpadding="0" cellspacing="0">
                    <tr>
                        <td>
                            <input type="text" id="fname" name="fname" class="watermark" watermark="First Name" value="" maxlength="30" class="requiredfield">
                        </td>                    
                    </tr>
                    <tr>
                        <td>
                            <input type="text" id="lname" name="lname" class="watermark" watermark="Last Name" value="" maxlength="30" class="requiredfield">
                        </td>                    
                    </tr>
                    <tr>
                        <td>
                            <input type="text" name="signup_email" id="signup_email" class="watermark" watermark="Email" autocomplete="off" value="" class="requiredfield" autocapitalize="off">
                        </td>                    
                    </tr>
                    <tr class="fake_password">
                        <td class="inputholder">
                            <input id="fake-pswd2" type="text" autocomplete="off" maxlength="30" class="watermark f_password" watermark="Select a password" class="requiredfield" name="password" defaulterrormsg="Password is required">
                        </td>
                    </tr> 
                    <tr class="orig_password">
                        <td>
                            <input type="password" autocomplete="off" maxlength="30"  class="o_password requiredfield" name="s_password" id="s_password">
                        </td>                    
                    </tr>
                    <tr>
                        <td>
                            <p class="gender_p"> Select Gender  <span class="gender_radio"><input type="radio" value="1" name="gender" />M</span>  <span class="gender_radio"><input type="radio" value="2" name="gender" />F</span> </p>
                        </td>
                    </tr>

<!--                    <tr>-->
<!--                        <td class="intouchCheckbox">&nbsp;</td>-->
                        <!--                        <td class="intouchCheckbox"><input class="f-left" style="width:auto; margin-top: 3px; margin-right: 3px;" type="checkbox" name="in_touch" id="in_touch" class="checkbox" checked="checked">-->
<!--                            <label class="lh-normal checkboxDyn" style="width:auto;" for="in_touch">-->
<!--                                -->
<!--                            Let's stay in touch!</label>           -->
<!--                        </td>                    -->
<!--                    </tr>-->
                    <tr>
                        <td class="no-padding signup-button-bg-gold">
                            <input type="submit" id="sign-up-button" value="" style="background-image: url('<?php echo $this->getSkinUrl('images/new-elements/signup-btnv4.png',array('_secure'=>true))?>'); width:315px; height:39px; background-size:100% 100%; border:none;">
                        </td>
                        <td align="center" class="form-loader no-padding c-align"></td>
                    </tr>
                    <tr>
                        <td style="padding: 0px;">
                            <p style="min-height: 15px; margin: 0px auto;  visibility: hidden;font: 12px GraphikRegular !important;line-height: 40px !important;" class="err-msg">All fields are required.</p>
                        </td>
                    </tr>
                </table>            
            </form>
        </div>
		<div class="sign-in-block f-right">
		<p class="c-align form-heading">ALREADY a SMOGI</p>
			<p class="c-align" style="margin:0;"><img src="<?php echo $this->getSkinUrl('images/spread-heart.png')?>"/></p>
            <p class="c-align form-heading">Spread the SMOGI Love To Your Friends, <br/>Get 25% Off</p>
            <form id="sign-in-form" class="bl" action="ds" method="post">
                <table width="100%" cellpadding="0" cellspacing="0">
                    <tr>
                        <td>                        
                            <input type="text" id="si_email" name="si_email" class="watermark" watermark="Email" value=""  class="requiredfield">
                        </td>                    
                    </tr>
                    <tr class="fake_password">
                        <td class="inputholder no-padding">
                            <input id="fake-pswd1" type="text" autocomplete="off" maxlength="30" class="watermark f_password requiredfield" watermark="Password" name="password" defaulterrormsg="Password is required">
                        </td>
                    </tr>                 
                    <tr class="orig_password">
                        <td class="no-padding">                      
                            <input type="password" autocomplete="off" maxlength="30" class="requiredfield o_password" name="si_password" id="si_password">
                        </td>                    
                    </tr>
                    <tr>
                        <td>
                            <a class="forgot-link" href="<?php echo $this->getUrl().'customer/account/forgotpassword'; ?>" class="f-left"><?php echo $this->__('Forgot Your Password?') ?></a>
                        </td>
                    </tr>
                    <tr>
                        <td class="no-padding signin-button-bg-gold">
                            <input type="submit" id="sign-in-button" value=""  style="background-image: url(<?php echo $this->getUrl()?>skin/frontend/yogasmoga2016/yogasmoga-theme/images/new-elements/sign-in-btnv4.png); width:315px; height:39px; background-size:100% 100%; border:none;">
                        </td>
                        <td align="center" class="form-loader no-padding c-align"></td>                    
                    </tr>                
                    <tr>
                        <td style="padding: 0px;">
                            <p style="min-height: 15px; margin: 0px auto;  visibility: hidden;font: 12px GraphikRegular !important;line-height: 40px !important;" class="err-msg">All fields are required.</p>
                        </td>               
                    </tr>
                    <tr>
                        <td style="padding: 0px;">
                            <p style="min-height:15px; margin: 0 auto; font-size: 12px; " class="err-msg-reset"><?php echo Mage::getSingleton('core/session')->getResetError();Mage::getSingleton('core/session')->setResetError(' '); ?></p>
                        </td>
                    </tr>
                </table>            
            </form>
        </div>
    </div>
    <div class="thank-you-block no-display">
        <img nopin="nopin" src="<?php echo Mage::getUrl('/', array('_secure'=>true));?>skin/frontend/new-yogasmoga/yogasmoga-theme/images/new-elements/thankuimg.jpg" alt="Thank You" />
        <p style="text-transform: none;"><img src="<?php echo Mage::getUrl('/', array('_secure'=>true));?>skin/frontend/new-yogasmoga/yogasmoga-theme/images/new-elements/ysmoga-logosml.png" alt="YOGASMOGA" /><strong style="text-transform: uppercase;">Thank You for Signing up</strong><?php /* ?><br />You have earned $25 SMOGI Bucks.<br />You can use them at Check Out.<?php */ ?></p>
    </div>
</div>
