<?php
$root = Mage::getBaseDir();

include_once($root . '/Ipinfo/Host.php');
include_once($root . '/Ipinfo/Ipinfo.php');

$ipInfo = new Ipinfo\Ipinfo();

if (!empty($_SERVER['HTTP_CLIENT_IP'])) {
    $ip = $_SERVER['HTTP_CLIENT_IP'];
} elseif (!empty($_SERVER['HTTP_X_FORWARDED_FOR'])) {
    $ip = $_SERVER['HTTP_X_FORWARDED_FOR'];
} else {
    $ip = $_SERVER['REMOTE_ADDR'];
}

$host = $ipInfo->getFullIpDetails($ip);

if (isset($host)) {
    $request_city = $host->getCity();
    $request_state = $host->getRegion();
    $request_zip = $host->getPostal();
}
else {
    $request_city = "N/A";
    $request_state = "N/A";
    $request_zip = "N/A";
}
?>
<?php  ?>
<div id="signup" class="mage-signup" style="display: none;">
    <div id="sign_up_box">
        <!--        <img nopin="nopin" style="width:50%; margin-top: 8%;" src="--><?php //echo $this->getSkinUrl('images/red_popup_text.png') ?><!--" alt="FEEL THE SMOGI LOVE. Sign up and earn 50% Off on your first order." />-->
        <form action="" method="post" id="popup-register" style="display: block; ">
            <div class="form-inner">
                <input type="hidden" id="plocation_city" name="location_city" value="<?php echo $request_city;?>"/>
                <input type="hidden" id="plocation_state" name="location_state" value="<?php echo $request_state;?>"/>
                <input type="hidden" id="plocation_zip" name="location_zip" value="<?php echo $request_zip;?>"/>

                <?php  $currentUrl = Mage::helper('core/url')->getCurrentUrl();
                $categoryName = explode('/', $currentUrl);
                $urlKey = $categoryName[3];?>
                <?php if (strtolower($urlKey)!='test1'){?>
                    <!--<svg xml:space="preserve" enable-background="new 0 0 308 127.979" viewBox="0 0 308 127.979" height="127.979px" width="280px" y="0px" x="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" id="Layer_1" version="1.1" >
                            <g>
                                <text transform="matrix(1 0 0 1 128.9932 30.103)">
                                    <tspan font-size="30.7692" font-family="'ITCAvantGardeProBk'" fill="#FFFFFF" y="0" x="0">FEEL</tspan>
                                    <tspan font-size="30.7692" font-family="'ITCAvantGardeProBk'" fill="#FFFFFF" y="35.23" x="-90.599">THE</tspan>
                                    <tspan font-size="30.7692" font-family="'ITCAvantGardeProBk'" fill="#FFFFFF" y="35.23" x="-32.923">SM</tspan>
                                    <tspan font-size="30.7692" font-family="'ITCAvantGardeProBk'" fill="#FFFFFF" y="35.23" x="8.477">   </tspan>
                                    <tspan letter-spacing="-1" font-size="30.7692" font-family="'ITCAvantGardeProBk'" fill="#FFFFFF" y="35.23" x="37.368">GI</tspan><tspan font-size="30.7692" font-family="'ITCAvantGardeProBk'" fill="#FFFFFF" y="35.23" x="69.983"> </tspan>
                                    <tspan font-size="30.7692" font-family="'ITCAvantGardeProBk'" fill="#FFFFFF" y="35.23" x="79.614">L   </tspan>
                                    <tspan font-size="30.7692" font-family="'ITCAvantGardeProBk'" fill="#FFFFFF" y="35.23" x="117.644">VE</tspan><tspan font-size="30.7692" font-family="'ITCAvantGardeProBk'" fill="#FFFFFF" y="35.23" x="155.981"/></text>
                            </g>
                        <g>
                            <g>
                                <g>
                                    <text transform="matrix(1 0 0 1 1.5195 97.6025)" y="" x=""><tspan font-size="16.6667" font-family="'ITCAvantGardeProBk'" fill="#FFFFFF" y="0" x="23">Sign up and get $25 SMOGI Bucks </tspan><tspan font-size="16.6667" font-family="'ITCAvantGardeProBk'" fill="#FFFFFF" y="22" x="69.583">toward your first order.</tspan></text>
                                </g>
                            </g>
                        </g>
                        <path d="M152.829,41.421c-6.257,0-11.967,4.6-11.967,12.024v0.03c0,5.829,4.787,11.503,11.934,11.503
                            c7.058,0,12.026-5.457,12.026-11.777S159.822,41.421,152.829,41.421z M154.657,60.207l-1.844,3.18l-1.854-3.237
                            c-3.047-0.902-4.833-3.873-4.833-7.017v-0.03c0-3.469,2.363-7.209,6.733-7.209c4.539,0,6.703,4.104,6.703,7.309
                            C159.563,55.928,157.956,59.317,154.657,60.207z" fill="#FFFFFF"/>
                        <path d="M234.316,41.421c-6.257,0-11.967,4.6-11.967,12.024v0.03c0,5.829,4.787,11.503,11.934,11.503
                            c7.058,0,12.026-5.457,12.026-11.777S241.31,41.421,234.316,41.421z M236.145,60.207l-1.844,3.18l-1.854-3.237
                            c-3.047-0.902-4.833-3.873-4.833-7.017v-0.03c0-3.469,2.363-7.209,6.733-7.209c4.539,0,6.703,4.104,6.703,7.309
                            C241.05,55.928,239.443,59.317,236.145,60.207z" fill="#FFFFFF"/>
                    </svg>-->
                   <!-- <img class="svg-logontext" src="<?php echo $this->getSkinUrl('images/25bucks.svg') ?>" alt=""/>-->
                    <svg class="svg-logontext" width="410px" height="165px" viewBox="0 0 410 165" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                        <!-- Generator: Sketch 39.1 (31720) - http://www.bohemiancoding.com/sketch -->
                        <title>Group</title>
                        <desc>Created with Sketch.</desc>
                        <defs></defs>
                        <g id="SIGNUP-25-SMB" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                            <g id="PopupSMB-Desktop_v3" transform="translate(-599.000000, -154.000000)">
                                <g id="Group" transform="translate(594.000000, 154.000000)">
                                    <g id="Text" transform="translate(0.000000, 96.500000)" font-size="32" font-family="AvantGardeGothicITCW01D, ITCAvantGardeStd-Demi, ITC Avant Garde Gothic Std" line-spacing="34" letter-spacing="0.129999995" font-weight="500">
                                        <text id="SIGN-UP-NOW-TO-RECEI">
                                            <tspan x="18" y="24" fill="#AE8536">SPREAD THE SMOGI LOVE</tspan>
                                            <tspan x="110" y="60" fill="#FFFFFF">GET 35% OFF</tspan>
                                        </text>
                                    </g>
                                    <g id="YS-logotype" transform="translate(91.000000, 0.000000)" fill="#AE8536">
                                        <path d="M107.979394,18.9071263 C108.390606,23.1630445 111.450947,24.0480368 113.020436,24.0480368 C115.648266,24.0480368 118.074585,22.0145432 118.074585,19.1772645 C118.074585,15.5975202 115.030628,14.8136225 112.125926,13.8308501 C110.060032,13.2226251 105.66284,11.9117095 105.66284,7.09562762 C105.59567,2.55631304 109.327713,0.0405483376 113.167883,0.0405483376 C116.303585,0.0405483376 119.935691,1.81053299 120.33216,6.63655857 L117.538862,6.63655857 C117.240691,4.99252788 116.419904,2.4717913 113.05484,2.4717913 C110.536777,2.4717913 108.467606,4.20863018 108.467606,6.8420624 C108.443032,9.95279386 110.903755,10.7234332 114.730819,12.0111468 C117.112904,12.9491724 120.882628,14.3031775 120.882628,18.9949627 C120.882628,23.1564153 117.784606,26.4792798 113.06467,26.4792798 C108.846053,26.4792798 105.343372,23.791157 105.174628,18.9071263 L107.979394,18.9071263 L107.979394,18.9071263 Z" id="Fill-3"></path>
                                        <polygon id="Fill-5" points="124.304377 26.0165647 124.304377 0.499285934 128.254313 0.499285934 137.618823 21.906488 146.914526 0.499285934 150.857909 0.499285934 150.857909 26.0165647 148.208781 26.0165647 148.271036 3.31336266 138.485483 26.0165647 136.689909 26.0165647 126.879781 3.31336266 126.950228 26.0165647"></polygon>
                                        <path d="M218.686553,3.71525524 L213.681553,16.5095263 L223.747255,16.5095263 L218.686553,3.71525524 Z M209.938043,26.0173934 L206.894085,26.0173934 L217.431617,0.500114578 L220.156106,0.500114578 L230.592064,26.0173934 L227.523532,26.0173934 L224.59917,18.8496184 L212.850936,18.8496184 L209.938043,26.0173934 Z" id="Fill-7"></path>
                                        <path d="M79.2241532,11.5003703 L66.6649617,11.5003703 L66.6649617,16.7042578 L71.7944723,16.7042578 C71.4520681,17.9488818 70.7394085,18.9846875 69.7154723,19.6708051 C68.6915362,20.3966977 67.3596,20.8093627 65.758983,20.8093627 C62.5888766,20.8093627 58.8388128,18.4991018 58.8388128,13.156002 C58.8388128,8.12281535 62.5577489,5.74129105 65.7278553,5.74129105 C67.5004936,5.74129105 68.8930468,6.39757749 69.9546638,7.32565934 C70.4969404,7.8427335 70.9425574,8.42941381 71.2833234,9.05089719 L78.5114936,9.05089719 C77.1123872,4.1204624 71.9304511,0.0170148338 65.8982383,0.0170148338 C58.4652809,0.0170148338 52.3970255,5.53578721 52.3970255,13.156002 C52.3970255,20.5011069 58.1621957,26.5336389 65.7933872,26.5336389 C69.9546638,26.5336389 75.6100681,24.4321964 78.0658766,18.8090148 C79.1586213,16.3297105 79.3634085,13.3283601 79.2241532,11.5003703" id="Fill-9"></path>
                                        <path d="M197.138021,13.992933 L197.138021,16.3396542 L205.170596,16.3396542 C204.764298,18.3433166 203.545404,20.2508563 201.769489,21.6562373 C200.016511,23.0483601 197.681936,23.9731274 195.014787,23.9731274 C189.492085,23.9731274 184.650915,19.7205238 184.650915,13.2256082 C184.650915,6.82847263 189.485532,2.55598159 195.001681,2.55598159 C197.228128,2.55598159 199.221936,3.21558261 200.866787,4.35414015 C201.939872,5.07671816 202.886809,6.01142916 203.681383,7.11352634 L206.897362,7.11352634 C204.903553,2.9454445 200.155766,0.0435314578 195.057383,0.0435314578 C187.762043,0.0435314578 181.829766,5.5821913 181.829766,13.2256082 C181.829766,20.7745596 187.662106,26.4888921 195.02134,26.4888921 C200.116447,26.4888921 205.13783,23.6930455 207.34134,18.9266824 C208.088404,17.319112 208.409511,15.4762066 208.457021,13.992933 L197.138021,13.992933 Z" id="Fill-11"></path>
                                        <polygon id="Fill-13" points="26.1624702 0.611152941 19.6977468 0.611152941 13.5180872 11.3885033 7.42525745 0.611152941 0.796704255 0.611152941 10.2627894 17.3464573 10.2627894 26.0157361 16.7094915 26.0157361 16.7094915 17.1028358"></polygon>
                                        <path d="M168.321017,20.5214916 L166.438613,23.8078957 L164.543102,20.4601719 C161.430336,19.5287754 159.603634,16.4545043 159.603634,13.2062179 L159.603634,13.1747294 C159.603634,9.58835601 162.021762,5.72190077 166.487762,5.72190077 C171.125783,5.72190077 173.335847,9.96290332 173.335847,13.2774813 C173.335847,16.0965299 171.695911,19.6000389 168.321017,20.5214916 M166.451719,0.0373994885 C159.50206,0.0373994885 153.156932,5.20814118 153.156932,13.550934 L153.156932,13.5840798 C153.156932,20.1403151 158.474847,26.5192205 166.417315,26.5192205 C174.261485,26.5192205 179.782549,20.3822793 179.782549,13.2774813 C179.782549,6.17434066 174.225443,0.0373994885 166.451719,0.0373994885" id="Fill-15"></path>
                                        <path d="M38.8632106,20.5214916 L36.9808064,23.8078957 L35.0836574,20.4601719 C31.9692532,19.5287754 30.1392745,16.4545043 30.1392745,13.2062179 L30.1392745,13.1747294 C30.1392745,9.58835601 32.5606787,5.72190077 37.0250404,5.72190077 C41.6630617,5.72190077 43.8780404,9.96290332 43.8780404,13.2774813 C43.8780404,16.0965299 42.2315511,19.6000389 38.8632106,20.5214916 M36.9922745,0.0373994885 C30.0393383,0.0373994885 23.6942106,5.20814118 23.6942106,13.550934 L23.6942106,13.5840798 C23.6942106,20.1403151 29.0154021,26.5192205 36.9578702,26.5192205 C44.8020404,26.5192205 50.321466,20.3822793 50.321466,13.2774813 C50.321466,6.17434066 44.7659979,0.0373994885 36.9922745,0.0373994885" id="Fill-17"></path>
                                        <path d="M88.425817,0.496302813 L78.4371149,26.0168962 L85.4260936,26.0168962 L86.5843702,22.3277708 L95.4115191,22.3277708 L96.6074766,26.0168962 L103.661987,26.0168962 L93.9829234,0.496302813 L88.425817,0.496302813 Z M90.9143915,8.26070179 L93.7420936,17.1570292 L88.1866255,17.1570292 L90.9143915,8.26070179 Z" id="Fill-2"></path>
                                    </g>
                                </g>
                            </g>
                        </g>
                    </svg>
                <?php } else{?>
                    <div class="svg-text-head" style="position:relative;top:-12px"><img src="<?php echo $this->getSkinUrl('images/signin-popup.png');?>"></div>
                <?php }?>

                <table width="100%" cellspacing="0" padding="0" align="center" >
                    <tr>
                        <td class="inputholder">
                            <input type="text" id="pfirstname" name="pfirstname" class="watermark" watermark="First Name" value="" maxlength="30" class="requiredfield no-bg">
                        </td>
                    </tr>
                    <tr height="5"></tr>
                    <tr>

                        <td class="inputholder">
                            <input type="text" id="plastname" name="plastname" class="watermark" watermark="Last Name" value="" maxlength="30" class="requiredfield no-bg">
                        </td>
                    </tr>
                    <tr height="5"></tr>
                    <tr>
                        <td class="inputholder">
                            <input type="text" name="email" id="pemail_address" class="watermark" watermark="Email Address" autocomplete="off" value="" class="requiredfield" defaulterrormsg="Email Address is required" autocapitalize="off">
                        </td>
                    </tr>
                    <tr height="5"></tr>
                    <tr class="fake_password">
                        <td class="inputholder">
                            <input type="text" autocomplete="off" maxlength="30" class="watermark f_password requiredfield" watermark="Select a password" name="password" id="f_password" defaulterrormsg="Password is required">
                        </td>
                    </tr>
                    <tr class="orig_password">
                        <td class="inputholder">
                            <input type="password" autocomplete="off" maxlength="30" class="requiredfield o_password" name="password" id="p_password" defaulterrormsg="Password is required">
                        </td>
                    </tr>
                    <tr>
                        <td class="gender_tr">
                            <p class="gender_p">Gender <label><span class="gender_radio"><input type="radio" value="1" name="gender"/>M</span>Male</label> <label><span class="gender_radio"><input type="radio" value="2" name="gender"/>F</span>Female</label></p>
                        </td>
                    </tr>
                    <tr height="5"></tr>
                    <input style="display: none;" type="password" class="requiredfield" name="confirmation" id="confirmation" defaulterrormsg="Password is required"/>
                    <input style="display: none;" id="is_subscribed" class="checkbox" type="checkbox" checked="checked" value="1" name="is_subscribed"/>

                </table>
                <p style="margin: 0px auto; font-size: 12px; visibility: hidden; min-height: 20px; width: 236px;" id="err-msg">All fields are required.</p>
                <button type="submit" id="signup-button">Sign up</button>

            </div>
            <?php if (strtolower($urlKey)!='test1'){?>
                <!--<p class="link_red_popup" style="color:#ff9f9f">Already Signed up? <br/><a onclick="jQuery('#signin').click()">Sign in here</a> </p>-->
                <p class="close-text" onclick="jQuery('.ui-icon-closethick').click()">No Thank You, I’m not interested in Made in the USA apparel.</p>
                <?php /* ?><p class="opensignin" onclick="jQuery('#signin').click()">I’m already signed up.</p><?php */ ?>
                <p class="opensignin" onclick="jQuery('.ui-icon-closethick').click()">I’m already signed up.</p>
            <?php }
            else{ ?>
                <p class="link_red_popup" style="color:#fff">Already Signed up? <br/><a style="color:#fff;" onclick="jQuery('#signin').click()">Sign in here</a> </p>
            <?php }

            ?>
    </form>
    </div>
    <div id="thank_you_box" style="display:none;">
        <img nopin="nopin" style="width:46%; padding-top: 12%; margin-top: 6%; padding-left:6%; padding-right: 6%;" src="<?php echo $this->getSkinUrl('images/Thank_You_15_off.png') ?>" alt="THANK YOU! Your SMOGI Bucks are waiting to be used at Checkout." />
        <table width="78%" cellspacing="0" cellpadding="0" style="margin:12% auto !important;">
            <tr>
                <td style="text-align:left;padding-right: 15px">
                    <a style="background:#1eaa18; color: #fff;  width: 170px;  margin:  0 auto;   text-align: center; height:42px; display:block; line-height:42px; font-family:AVANTGARDEGOTHICITCW01B;" href="<?php echo Mage::helper('core/url')->getHomeUrl(); ?>women">
                        SHOP WOMEN
                    </a>
                </td>
                <td  style="text-align:right;padding-left: 15px">
                    <a style="background:#1eaa18; color: #fff;  width: 170px;  margin:  0 auto;   text-align: center; height:42px; display:block; line-height:42px; font-family:AVANTGARDEGOTHICITCW01B;" href="<?php echo Mage::helper('core/url')->getHomeUrl(); ?>mens">
                        SHOP MEN
                    </a>
                </td>
            </tr>
        </table>
        <table width="60%" ceelspacing="0" cellpadding="0" style="margin:5% auto 0;">
            <tr>
                <td style="text-align:center;">
                <?php /* ?>    <a href="<?php echo Mage::helper('core/url')->getHomeUrl(); ?>smogi-bucks">
                        <img src="<?php echo $this->getSkinUrl('images/learn_bucks.png') ?>" alt="Learn more about SMOGI Bucks" style="width:75%; margin:0 auto !important;" /></a><?php */?>
                </td>
            </tr>
        </table>
    </div>
</div>
<script>
	jQuery(function($){
		// Open login popup.
        $(".opensignin").click(function(){
            $("#signup").dialog( "close" );
            $("#signing_popup").dialog( "open" );
        });
	})
</script>
<?php  ?>

<?php /*?>
<div id="signup" class="mc-signup" style="display:none;">

    <div class="signup-content">

        <form action="" method="post" id="popup-mailsignup" style="display: block;">
            <img class="svg-logontext" src="<?php echo $this->getSkinUrl('images/25-offv2.svg') ?>" alt=""/>
            <div class="fields-area">
                <p><input type="text" name="email" id="Memail_address" class="watermark" placeholder="Your Email Address" autocomplete="off" value="" class="requiredfield" defaulterrormsg="Email Address is required" autocapitalize="off"/></p>
                <p class="button-area"><span class="form-loader-mail"></span><input type="submit" value="Sign Up" id="signup-button-mailc"/></p>
            </div>

            <p style="margin: 0px auto; font-size: 12px; visibility: hidden; min-height: 20px; width: 236px;" id="err-msg">All fields are required.</p>
            <p class="close-text">No Thank You, I&rsquo;m not interested in
                Made in the USA apparel.</p>
            <p class="opensignin">I’m already signed up.</p>
        </form>
    </div>

    <!--signup-content-->
    <div class="signup-thankyou">
        <div class="signup-thankyou-content">
            <img class="svg-logo" src="<?php echo $this->getSkinUrl('images/m.svg') ?>" alt=""/>
            <p class="signup-title">
			<span class="spn_line"><span class="strong">Thank You</span>
				<span class="strong"><small>Please Check Your email</small><small> &amp; Feel the SMOGI LOVE</small></span></span>
                <!--<span class="spn_line"><span class="highlight">SMOGILOVE</span></span>-->
            </p>
            <!--<small>We've also emailed it to you in case you forget.</small>-->
            <p class="mc-shoplinks">
                <a href="/women"><img src="<?php echo $this->getSkinUrl('images/new-elements/mc-shopwomen3.jpg') ?>" alt=""/></a>
                <a href="/men"><img src="<?php echo $this->getSkinUrl('images/new-elements/mc-shopmen3.jpg') ?>" alt=""/></a>
            </p>
            <p class="close-text conti">Continue to the site.</p>
        </div>
    </div>
    <!--signup-thankyou-->

</div>

<script type="application/javascript">
    jQuery(document).ready(function($){
        //$("#signup").dialog( "open" );
        $("#popup-mailsignup").submit(function(event){
            event.preventDefault();

            $("#err-msg").css("visibility","hidden");

            var formid = "#popup-mailsignup";
            var email_id = $.trim($("#Memail_address").val());
            if(email_id == "" || email_id == "Email Address")
            {
                event.preventDefault();
                $("#err-msg").css("visibility","visible");
                $("#err-msg").text("Please enter an email address.");
                return;
            }
            if(!validateEmail(email_id)){
                event.preventDefault();
                $("#err-msg").css("visibility","visible");
                $("#err-msg").text("Enter a valid email.");
                return;
            }

            if(window.location.href.indexOf('https://') >= 0)
                _usesecureurl = true;
            else
                _usesecureurl = false;
            var url = homeUrl + 'mailchimp_signup.php';
            if(_usesecureurl){
                url = securehomeUrl + 'mailchimp_signup.php';
            }


            jQuery.ajax({
                url     :   url,
                type    :   'POST',
                data    :   {'email':email_id},
                beforeSend: function() {

                    jQuery("#popup-mailsignup #signup-button-mailc").attr("value","SIGNING UP...");
                    //jQuery("#popup-mailsignup").parent().hide();
                    jQuery("#popup-mailsignup .form-loader-mail").show();
                },
                success: function (data) {
                    data = eval('(' + data + ')');
                    var status = data.status;
                    jQuery("#popup-mailsignup .form-loader-mail").hide();

                    if (status == "success") {
                        jQuery("#popup-mailsignup").parent().hide();
                        $(".signup-thankyou").show();
                        jQuery("#popup-mailsignup #signup-button-mailc").attr("value","SIGN UP");
                        $('.ui-icon-closethick,.close-text').click(function(){
                            $(".signup-thankyou").hide();
                            $(".signup-content").show();
                            $("#Memail_address").val('');
                        });
                    }
                    else
                    {
                        $("#signup-button-mailc").val("SIGN UP");
                        jQuery("#signup-button-mailc").parent().show();
                        $("#popup-mailsignup #err-msg").html(data.error).css("visibility","visible");
                    }
                }
            });
        });

        $(".close-text").click(function(){
            $("#signup").dialog( "close" );
        });
        // Open login popup.
        $(".opensignin").click(function(){
            $("#signup").dialog( "close" );
            $("#signing_popup").dialog( "open" );
        });

        $('#Memail_address').on('focus keypress',function(){
            if($(this).val().length > 0){
                $('#signup-button-mailc').addClass('on');
            }
            else{
                $('#signup-button-mailc').removeClass('on');
            }

        });
    });

</script>
<!-- Shivaji New Code -->
 <?php */?>
