<?php $_order = $this->getOrder() ?>
<?php
    if ($_order)
    {
        //echo $_order->getId();
        $write = Mage::getSingleton('core/resource')->getConnection('core_read');
        $readresult = $write->query("SELECT increment_id, customer_id FROM sales_flat_order WHERE entity_id=".$_order->getId());
        $row = $readresult->fetch();
        $increment_id = $row['increment_id'];
        $customerId = $row['customer_id'];
        $readresult = $write->query("SELECT * FROM rewardpoints_account WHERE order_id='".$increment_id."'");
        $row = $readresult->fetch();
        if($row['points_current'] > 0)
            echo "You have earned ".$row['points_current']." SMOGI Bucks with this order. ";
        
        $available_points = 0;
        $store_id = Mage::app()->getStore()->getId();        
        if (Mage::getStoreConfig('rewardpoints/default/flatstats', $store_id)){
            $reward_flat_model = Mage::getModel('rewardpoints/flatstats');
            $available_points = $reward_flat_model->collectPointsCurrent($customerId, $store_id);
        }
        else
        {
            $reward_model = Mage::getModel('rewardpoints/stats');        
            $available_points = $reward_model->getPointsCurrent($customerId, $store_id);    
        }
        if($available_points > 0)
            echo "You have ".$available_points." SMOGI Bucks available.";
    }
?>