<div class="namaskar-overlay1">&nbsp;</div>
<script type="text/javascript">
    jQuery(window).load(function(){
        jQuery('body').css('overflow','auto');
        jQuery('.namaskar-overlay1').fadeOut('slow');
    })
</script>
<!-- startCMSPages -->
<div class="gridCMSPages">
	<!-- gridBlockOne -->
	<div class="gridFullWidth ystopsection">
		<!-- BlockLeft -->
		<div class="block33">
			<!-- leftNavigation -->
			<div class="cmsNavigation">
				<ul>
					<li><a href="/our-story">our story</a></li>
					<li><a href="/our-core-values">our core values</a></li>
					<li><a href="/our-ethics">our ethics</a></li>
                    <!--<li><a href="/our-stores" >our stores</a></li>-->
					<li><a href="/made-in-usa">made in usa</a></li>
					<li><a href="/principles-of-yoga">principles of yoga</a></li>
					<li><a href="/namaskar" class="current">NAMASKÁR foundation</a></li>
					<li><a href="/press">press</a></li>
				</ul>
			</div>
			<!-- leftNavigation -->

			<!-- CMSheadingBlock -->
			<div class="headingBlock">
				<div class="positionAbs h1">NAMASKÁR<br />FOUNDATION</div>
				<h1 style="display:none">NAMASKÁR Foundation</h1>
			</div>
			<!-- CMSheadingBlock -->
		</div>
		<!-- BlockLeft -->

		<!-- BlockRight -->
		<div class="block66 posRel">
			<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/namaskar-img1.jpg" alt="" class="img-responsive" />
			<div id="ysbannertxtFour" class="positionAbs" style="top:48.4%;">
				<div class="h4"><img src="<?php echo $this->getSkinUrl('images/new-elements/namaskartext.png')?>" alt="" /></div>
			</div>			
		</div>
		<!-- BlockRight -->
	</div>
	<!-- gridBlockOne -->

	<!-- gridBlockContent -->
	<div class="gridBlockContent">
		<span>what is NAMASKÁR</span>
		<div class="h3">GIVING IS A CORE VALUE OF YOGASMOGA
			<span>WE HAVE CREATED THE NAMASKÁR FOUNDATION BECAUSE WE CARE</span>
		</div>
	</div>
	<!-- gridBlockContent -->

	<!-- gridBlockTwo -->
	<div class="gridFullWidth ysbottomsection namaskarblock1 mrgnbtm0">
		<!-- BlockLeft -->
		<div class="block66 posRel f-left">
			<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/namaskar2.jpg" alt="" class="img-responsive" />
			<div id="ysbannertxtSix" class="positionAbs">
				<div class="h4">jOINING HANDS<br />TO MAKE A CHANGE
					<span class="smallHead">NAMASKÁR</span>
				</div>
			</div>			
		</div>
		<!-- BlockLeft -->

		<!-- BlockRight -->
		<div class="block33">
			<!-- imageNamFound -->
			<div class="namaskarsideImage">
				<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/namaskar3.jpg" alt="" class="img-responsive" />
			</div>
			<!-- imageNamFound -->

			<!-- joybalanceText -->
			<div class="joybalanceText bgf3f3f4">
				<div class="contnttxt">
					<p>We recognize that textile production is typically done in the most economically challenged locations of the world. It is our absolute obligation and duty to give back. We welcome you to join us on this journey.</p>
				</div>
			</div>
			<!-- joybalanceText -->
		</div>
		<!-- BlockRight -->
	</div>	
	<!-- gridBlockTwo -->

	<!-- gridBlockThree -->
	<div class="gridFullWidth eqaulcontbg disInline">
		<!-- BlockLeft -->
		<div class="block50 bgf3f3f4 posRel" id="imgcontb1">
			<!-- contentPart -->
			<div class="textContainer positionAbs">
				<div class="cntntheading">
					the NAMASKÁR foundation
					<span>RAISING THE FUNDS</span>
				</div>
				<div class="contnttxt">
					<p>YOGASMOGA has coordinated the manufacture and sales of hand woven bracelets that are being made on handlooms in remote villages of the Himalayas. These hand woven bracelets are sold by YOGASMOGA for $10 and Net Proceeds of all sales will be donated to the NAMASKÁR FOUNDATION.</p>
					<a href="/women/accessories/namaskar-bracelets/namaskar-bracelet" class="grnbtn mrgn24top">ADD BRACELET TO BAG</a>
				</div>
			</div>
			<!-- contentPart -->
		</div>
		<!-- BlockLeft -->

		<!-- BlockRight -->
		<div class="block50" id="imgcontb2">
			<!-- contentPart -->
			<div class="textContainer">
				<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/namaskar4.jpg" alt="" class="img-responsive" />
			</div>
			<!-- contentPart -->
		</div>
		<!-- BlockRight -->
	</div>	
	<!-- gridBlockThree -->

	<!-- gridBlockFour -->
	<div class="gridFullWidth namaskarblock2">
		<!-- BlockLeft -->
		<div class="block100 posRel">
			<!-- contentPart -->
			<div class="textContainer">
				<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/namaskar5.jpg" alt="" class="img-responsive" />
					<div id="ysnamaskartxt" class="positionAbs">
						<span class="topHead">Namaskár Foundation's focus</span>
						<div class="h4">
							the Namaskár Foundation<br />FOCUSES ITS ENERGIES ON<br />THREE EQUALLY IMPORTANT CAUSES.
							<span class="smallHead">FOR TODAY & TOMORROW</span>
						</div>
					</div>
			</div>
			<!-- contentPart -->
		</div>
		<!-- BlockLeft -->
	</div>
	<div class="gridFullWidth">
		<!-- BlockLeft -->
		<div class="block100">
			<!-- contentPart -->
			<div class="textContainer">
				<div class="coloumn-list">
					<ul>
						<li><span><span>1</span>HEALTH</span>In our travels to the developing world we have realized that people (especially women) lack even a basic level of health care. The Namaskár Foundation seeks to provide basic health initiatives, immunization, care and education around early child birth so that each child born has an opportunity to a successful future that they deserve.</li>
						<li><span><span>2</span>EDUCATION</span>Education is the foundation of well-being. The Namaskár Foundation seeks to provide education that gives children and young adults a chance to grow into productive, fulfilled adults. NAMASKÁR intends to develop education programs, including work with existing education based charities.</li>
						<li><span><span>3</span>MICROLENDING</span>The Namaskár Foundation seeks to provide micro loans ($10 - $50) to individuals in developing economies who have no access to banks. These micro loans provide an opportunity to individuals to jump-start small cottage industries that over time generate income. One of the very first micro lending projects that NAMASKÁR is working on is setting up handlooms for women in the remote villages of the Himalayas so that these women can earn a living producing Namaskár bracelets.</li>
					</ul>
				</div>
			</div>
			<!-- contentPart -->
		</div>
		<!-- BlockLeft -->
	</div>
	<!-- gridBlockFour -->

	<!-- gridBlockFive -->
	<div class="gridFullWidth marginbottom50">
		<!-- BlockLeft -->
		<div class="block50">
			<!-- contentPart -->
			<div class="textContainer">
				<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/namaskar6.jpg" alt="" class="img-responsive" />
				<div class="cntntheading">
					NAMASKÁR
					<span>THE MEANING</span>
				</div>
				<div class="contnttxt">
					<p>While many are familiar with the greeting – Namasté -fewer in the west are familiar with the traditional Indian greeting – Namaskár. More respectful than Namasté, it is not simply a greeting but a profound philosophy of shunning arrogance and negating one’s ego. The gesture, Namaskár, represents the belief that there is a divine spark within each of us that is located in the heart chakra. This gesture is an acknowledgement of the soul in one – by the soul in another. We join our hands together to recognize each other’s soul, aiming to connect and honor each other.</p>
				</div>
			</div>
			<!-- contentPart -->
		</div>
		<!-- BlockLeft -->

		<!-- BlockRight -->
		<div class="block50">
			<!-- contentPart -->
			<div class="textContainer">
				<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/namaskar7.jpg" alt="" class="img-responsive" />
				<div class="cntntheading">
					support NAMASKÁR
					<span>JOIN US</span>
				</div>
				<div class="contnttxt">
					<p>We bring the Namaskár bracelet to you as a traditional symbol of the deep Yoga culture that connects two people – our SMOGIs and the weavers of the Himalayas. The weavers (mostly women) have lost much of their business to machine manufacturing and today we give you an opportunity to connect directly with these hard working people so you can help them attain the means they need to continue their craft, while you proudly wear a hand made (and beautiful) Namaskár bracelet.</p>
					<a class="grnbtn mrgntop7" href="/women/accessories/namaskar-bracelets/namaskar-bracelet">ADD BRACELET TO BAG</a>
				</div>
			</div>
			<!-- contentPart -->
		</div>
		<!-- BlockRight -->
	</div>
	<!-- gridBlockFive -->

	<!-- namaskarCopyright -->
	<div class="namaskar-copyright">Namaskár Foundation, Inc. is recognized exclusively for charitable & educational<br/> purposes. It holds a tax-exempt status as a 501(c)(3) organization.</div>
	<!-- namaskarCopyright -->

	<!-- bottomDivider -->
	<div class="bottomdivider"></div>
	<!-- bottomDivider -->

</div>
<!-- endCMSPages -->