<div class="namaskar-overlay1">&nbsp;</div>
<script type="text/javascript">
    jQuery(window).load(function(){
        jQuery('body').css('overflow','auto');
        jQuery('.namaskar-overlay1').fadeOut('slow');
    })
</script>
<!-- startCMSPages -->
<div class="gridCMSPages">
    <!-- gridBlockOne -->
    <div class="gridFullWidth ystopsection">
        <!-- BlockLeft -->
        <div class="block33">
            <!-- leftNavigation -->
            <div class="cmsNavigation">
                <ul>
                    <li><a href="/our-story" class="current">our story</a></li>
                    <li><a href="/our-core-values">our core values</a></li>
                    <li><a href="/our-ethics">our ethics</a></li>
                    <!--<li><a href="/our-stores">our stores</a></li>-->
                    <li><a href="/made-in-usa">made in usa</a></li>
                    <li><a href="/principles-of-yoga">principles of yoga</a></li>
                    <li><a href="/namaskar">namask&Aacute;r foundation</a></li>
                    <li><a href="/press">press</a></li>
                </ul>
            </div>
            <!-- leftNavigation -->

            <!-- CMSheadingBlock -->
            <div class="headingBlock">
                <div class="positionAbs h1">our story</div>
                <h1 style="display:none;">About YOGASMOGA</h1>
            </div>
            <!-- CMSheadingBlock -->
        </div>
        <!-- BlockLeft -->

        <!-- BlockRight -->
        <div class="block66 posRel">
            <img src="<?php echo Mage::getBaseUrl("media") ?>/wysiwyg/new-design-images/newstoryBanner.jpg" alt="" class="img-responsive" />
            <div class="positionAbs" id="ysbannertxt" style="top:32.4%;">
                <span class="topHead">WHO WE ARE</span>
                <div class="h4">
                    WE ARE YOGASMOGA<br />WE MAKE THINGS FOR LIFE
                    <span class="smallHead">ONE BREATH AT A TIME</span>
                </div>
                <!--div class="htext white">
                    Honoring the tenets of Yoga, we aspire to create world-class products.<br />Growing up in the Himalayas, the birthplace & capital of Yoga, our founders instinctively<br />infuse the timeless principles, spirit and practice of Yoga into everything we do. From our<br />cosmopolitan aesthetic, to our product technology, right down to creating our very own way<br />to give back, we've meticulously designed every part of the whole, one breath at a time.
                </div-->
            </div>
            <div class="htext white" style="position:absolute; width:100%; margin:0; bottom:40px;">
                Honoring the tenets of Yoga, we aspire to create world-class products.<br />Growing up in the Himalayas, the birthplace & capital of Yoga, our founders instinctively<br />infuse the timeless principles, spirit and practice of Yoga into everything we do. From our<br />cosmopolitan aesthetic, to our product technology, right down to creating our very own way<br />to give back, we've meticulously designed every part of the whole, one breath at a time.
            </div>
        </div>
        <!-- BlockRight -->
    </div>
    <!-- gridBlockOne -->


    <!-- gridBlockTwo -->
    <div class="gridFullWidth marginbottom50">
        <!-- BlockLeft -->
        <div class="block50">
            <!-- contentPart -->
            <div class="textContainer">
                <img src="<?php echo Mage::getBaseUrl("media") ?>/wysiwyg/new-design-images/storyImgNew2.jpg" alt="" class="img-responsive" />
                <div class="cntntheading">
                    IMAGINE IT AS A PRACTICE,<br />A WAY OF BEING
                    <span>BUILDING A PATHWAY TO<br />GREATER GOOD</span>
                </div>
                <div class="contnttxt">
                    <p>We take the stand that physically, mentally, and emotionally Karma works in harmony with innovation, so that technology becomes a pathway to greater good. In the act of balancing science with spirituality you cause a chemical reaction that can promote something as great as change. Connecting, interacting and creating a positive impact beyond the Yoga mat.</p>
                    <p>We engineer, design, and manufacture fabrics that do more than cover someone up. They open them up to greater good. While we work with the most technically advanced fabric and manufacturing technologies, we also pursue a relentless focus on the deep traditions of Yoga. We embody the soul of Yoga and instinctively embed this into everything we create, including investing much time into creating the <a href="/namaskar" class="f11">namask&Aacute;r foundation</a>.</p>
                </div>
            </div>
            <!-- contentPart -->
        </div>
        <!-- BlockLeft -->

        <!-- BlockRight -->
        <div class="block50">
            <!-- contentPart -->
            <div class="textContainer">
                <img src="<?php echo Mage::getBaseUrl("media") ?>/wysiwyg/new-design-images/storyImgNew3.jpg" alt="" class="img-responsive" />
                <div class="cntntheading">
                    WE MAKE THINGS FROM<br />THE HEART AND WITH LOVE
                    <span>FOR WHEREVER LIFE<br />TAKES YOU</span>
                </div>
                <div class="contnttxt">
                    <p>A lot of people think of themselves as clothing companies who sell Yoga apparel. We think of ourselves differently. We are a Yoga and wellness company that makes things for life. Our focus is not on building a brand; our goal is to have a love affair with our consumers.  We create our products from the heart and with love and we want everyone to feel that. We are building YOGASMOGA from the ground up with a purpose and passion and our products reflect this love and care.</p>
                    <p>We strive to become your partner in the pursuit of wellness-wherever you are today and wherever you are going tomorrow. From Yoga class, to the gym, to life. Whether you're on the go, or simply being, we're happy to be with you. We hope to bring a little more Yoga into your journey, Everyday.</p>
                </div>
            </div>
            <!-- contentPart -->
        </div>
        <!-- BlockRight -->
    </div>
    <!-- gridBlockTwo -->


    <!-- gridBlockOne -->
    <div class="gridFullWidth ysbottomsection">
        <!-- BlockLeft -->
        <div class="block66 f-left">
            <img src="<?php echo Mage::getBaseUrl("media") ?>/wysiwyg/new-design-images/newstoryImg2.jpg" alt="" class="img-responsive" />
        </div>
        <!-- BlockLeft -->

        <!-- BlockRight -->
        <div class="block33">
            <!-- leftNavigation -->
            <div class="joybalance">
                <div class="cntntheading positionAbs white">A BIT MORE ABOUT US<span>JOY, ENERGY AND<br />BALANCE</span></div>
            </div>
            <!-- leftNavigation -->

            <!-- CMSheadingBlock -->
            <div class="joybalanceText">
                <div class="contnttxt">
                    <p>Staying true to the spirit of Yoga, everything we create intends to balance the joy of life with the energy required to live it. Take our name as an example, in Hindi, it's traditional to rhyme words and similar items-so our name is a jubilant nod of respect to our culture.</p>
                    <p>To combine that joy with energy, our iconic logo is based on traditional symbology that conveys a balanced and powerful energy center. We see this as a beautiful metaphor for our human experience.</p>
                </div>
            </div>
            <!-- CMSheadingBlock -->
        </div>
        <!-- BlockRight -->
    </div>
    <!-- gridBlockOne -->

    <!-- bottomDivider -->
    <div class="bottomdivider"></div>
    <!-- bottomDivider -->

</div>
<!-- endCMSPages -->