<div class="namaskar-overlay1">&nbsp;</div>
<script type="text/javascript">
    jQuery(window).load(function(){
        jQuery('body').css('overflow','auto');
        jQuery('.namaskar-overlay1').fadeOut('slow');
    })
</script>
<!-- startCMSPages -->
<div class="gridCMSPages">
	<!-- gridBlockOne -->
	<div class="gridFullWidth ystopsection">
		<!-- BlockLeft -->
		<div class="block33">
			<!-- leftNavigation -->
			<div class="cmsNavigation">
				<ul>
					<li><a href="/our-story">our story</a></li>
					<li><a href="/our-core-values" class="current">our core values</a></li>
					<li><a href="/our-ethics">our ethics</a></li>
                    <!--<li><a href="/our-stores" >our stores</a></li>-->
					<li><a href="/made-in-usa">made in usa</a></li>
					<li><a href="/principles-of-yoga">principles of yoga</a></li>
					<li><a href="/namaskar">namaskÁr foundation</a></li>
					<li><a href="/press">press</a></li>
				</ul>
			</div>
			<!-- leftNavigation -->

			<!-- CMSheadingBlock -->
			<div class="headingBlock">
				<div class="positionAbs h1">our<br /> core values</div>
				<h1 style="display:none">YOGASMOGA Core Values</h1>
			</div>
			<!-- CMSheadingBlock -->
		</div>
		<!-- BlockLeft -->

		<!-- BlockRight -->
		<div class="block66 posRel">
			<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/cv-banner.jpg" alt="" class="img-responsive" />
			<div class="positionAbs" id="ysbannertxtTwo" style="top:32.2%;">
				<span class="topHead">WHAT WE BELIEVE IN</span>
				<div class="h4">
					A CORE OF AUTHENTICITY
					<span class="smallHead">CREATING PRODUCTS FROM THE HEART & WITH LOVE</span>
				</div>
				<!--div class="htext white" style="margin-top:92px;">
					While we labor to work with the most technologically advanced fabrics and manufacturing<br />techniques, we pursue a relentless focus on the deep-rooted traditions of YOGA .<br />We strive to apply the principles, practice and spirit of Yoga to everything we do,<br />and in everything we create. We hope this will bring Yoga to life<br />in new and meaningful ways.
				</div-->
			</div>
<div class="htext white" style="position:absolute; width:100%; margin:0; bottom:40px;">
					While we labor to work with the most technologically advanced fabrics and manufacturing<br />techniques, we pursue a relentless focus on the deep-rooted traditions of YOGA .<br />We strive to apply the principles, practice and spirit of Yoga to everything we do,<br />and in everything we create. We hope this will bring Yoga to life<br />in new and meaningful ways.
				</div>
		</div>
		<!-- BlockRight -->
	</div>
	<!-- gridBlockOne -->

	<!-- gridBlockTwo -->
	<div class="gridFullWidth marginbottom50">
		<!-- BlockLeft -->
		<div class="block50">
			<!-- contentPart -->
			<div class="textContainer">
				<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/lasting-cnctn.jpg" alt="" class="img-responsive" />
				<div class="cntntheading">
					DEEP, DIRECT AND<br />LASTING CONNECTIONS
				</div>
				<div class="contnttxt">
					<p>We put in great love, care and devotion to create products that will delight our SMOGIs (that’s you and all of our YOGASMOGA community). We aim to touch the daily lives of our SMOGIs, building deep connections and long-lasting bonds.</p>
				</div>
			</div>
			<!-- contentPart -->
		</div>
		<!-- BlockLeft -->

		<!-- BlockRight -->
		<div class="block50">
			<!-- contentPart -->
			<div class="textContainer">
				<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/cv-reputation.jpg" alt="" class="img-responsive" />
				<div class="cntntheading">
					A RESPONSIBILITY BASED<br />REPUTATION
				</div>
				<div class="contnttxt">
					<p>We strive to earn the respect of our SMOGIs by constantly delivering at a superior level with everything we do. We know this respect is earned through action and over a long period of time. We take this responsibility seriously. We make real things for life and at times mistakes will happen. Our promise is to rectify any mistake immediately and proactively.</p>
				</div>
			</div>
			<!-- contentPart -->
		</div>
		<!-- BlockRight -->
	</div>
	<!-- gridBlockTwo -->

	<!-- gridBlockThree -->
	<div class="gridFullWidth marginbottom50">
		<!-- BlockLeft -->
		<div class="block50">
			<!-- contentPart -->
			<div class="textContainer">
				<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/cv-innovation.jpg" alt="" class="img-responsive" />
				<div class="cntntheading">
					A MANTRA OF INNOVATION
				</div>
				<div class="contnttxt">
					<p>We are committed to using the most innovative and pioneering techniques to develop our fabric technology. Our unyielding commitment to using the best technologies is more than a best practice for us, it’s our mantra--an everyday practice that yields far superior products for our SMOGIs.</p>
				</div>
			</div>
			<!-- contentPart -->
		</div>
		<!-- BlockLeft -->

		<!-- BlockRight -->
		<div class="block50">
			<!-- contentPart -->
			<div class="textContainer">
				<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/cv-culture.jpg" alt="" class="img-responsive" />
				<div class="cntntheading">
					COLLABORATION AS CULTURE
				</div>
				<div class="contnttxt">
					<p>We inspire our people to be creative through constant collaboration. This drives us to deliver the very best, for everyone. Our people take pride in the work we do together.</p>
				</div>
			</div>
			<!-- contentPart -->
		</div>
		<!-- BlockRight -->
	</div>
	<!-- gridBlockThree -->

	<!-- gridBlockFour -->
	<div class="gridFullWidth">
		<!-- BlockLeft -->
		<div class="block50">
			<!-- contentPart -->
			<div class="textContainer">
				<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/cv-breathe.jpg" alt="" class="img-responsive" />
				<div class="cntntheading">
					EAT, SLEEP & BREATHE THE DETAILS
				</div>
				<div class="contnttxt">
					<p>We have an uncompromising determination to achieve excellence in everything we undertake–one breath at a time. We believe that if we pay keen attention to the smallest details and strive for ever-present awareness in our everyday actions, the results will show.</p>
				</div>
			</div>
			<!-- contentPart -->
		</div>
		<!-- BlockLeft -->

		<!-- BlockRight -->
		<div class="block50">
			<!-- contentPart -->
			<div class="textContainer">
				<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/cv-namaskar.jpg" alt="" class="img-responsive" />
				<div class="cntntheading">
					THE GIFT OF NAMASKáR
				</div>
				<div class="contnttxt">
					<p>We recognize that textile production is typically done in the most challenged economic locations in the world and we feel it is our absolute obligation and duty to give back to those who have joined us on this journey. Which is why we have created the <a href="/namaskar" class="f11">Namaskár Foundation</a>.</p>
				</div>
			</div>
			<!-- contentPart -->
		</div>
		<!-- BlockRight -->
	</div>
	<!-- gridBlockFour -->

	<!-- bottomDivider -->
	<div class="bottomdivider"></div>
	<!-- bottomDivider -->

</div>
<!-- endCMSPages -->