<div class="namaskar-overlay1">&nbsp;</div>
<script type="text/javascript">
    jQuery(window).load(function(){
        jQuery('body').css('overflow','auto');
        jQuery('.namaskar-overlay1').fadeOut('slow');
    })
</script>
<!-- startCMSPages -->
<div class="gridCMSPages">
	<!-- gridBlockOne -->
	<div class="gridFullWidth ystopsection">
		<!-- BlockLeft -->
		<div class="block33">
			<!-- leftNavigation -->
			<div class="cmsNavigation">
				<ul>
					<li><a href="/our-story">our story</a></li>
					<li><a href="/our-core-values">our core values</a></li>
					<li><a href="/our-ethics">our ethics</a></li>
                    <!--<li><a href="/our-stores">our stores</a></li>-->
					<li><a href="/made-in-usa">made in usa</a></li>
					<li><a href="/principles-of-yoga" class="current">principles of yoga</a></li>
					<li><a href="/namaskar">namaskÁr foundation</a></li>
					<li><a href="/press">press</a></li>
				</ul>
			</div>
			<!-- leftNavigation -->

			<!-- CMSheadingBlock -->
			<div class="headingBlock">
				<div class="positionAbs h1">PRINCIPLES OF<br />Yoga</div>
				<h1 style="display:none">Principles of Yoga</h1>
			</div>
			<!-- CMSheadingBlock -->
		</div>
		<!-- BlockLeft -->

		<!-- BlockRight -->
		<div class="block66 posRel">
			<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/poyBanner.jpg" alt="" class="img-responsive" />
			<div id="ysbannertxtFour" class="positionAbs" style="top:32.4%">
				<span class="topHead">PRINCIPLES OF YOGA</span>
				<div class="h4">
					FINDING YOUR INTERNAL CENTER
					<span class="smallHead">RELAXED SENSE OF SELF THROUGH INTERNAL SILENCE</span>
				</div>
			</div>			
		</div>
		<!-- BlockRight -->
	</div>
	<!-- gridBlockOne -->

	<!-- gridBlockTwo -->
	<div class="gridFullWidth marginbottom50">
		<!-- BlockOne -->
		<div class="block30">
			<!-- contentPart -->
			<div class="textContainer">
				<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/poy-body.jpg" alt="" class="img-responsive" />
				<div class="iconBlock">
					<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/Icon-Yoga-Relaxed.png" alt="" style="height:44px;" />
				</div>
				<div class="cntntheading">
					RELAXED BODY<br />AND MIND
				</div>
				<div class="contnttxt">
					<p>Yoga helps in finding your internal center and thus the benefits of Yoga are wide spread. The Yoga practice creates a more relaxed sense of self through internal silence, making the stresses of our lives manageable. The effectiveness of Yoga lies in its simplicity and its ability to elicit a sense of wholeness, balance and calm.</p>
				</div>
			</div>
			<!-- contentPart -->
		</div>
		<!-- BlockOne -->

		<!-- BlockTwo -->
		<div class="block30">
			<!-- contentPart -->
			<div class="textContainer">
				<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/poy-exercise.jpg" alt="" class="img-responsive" />
				<div class="iconBlock">
					<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/Icon-Yoga-Exercise.png" alt="" />
				</div>
				<div class="cntntheading">
					EXERCISE<br />AND ELONGATION
				</div>
				<div class="contnttxt">
					<p>Asanas are Yoga postures that restore your body’s flexibility and vitality. Each Asana has evolved over thousands of years to strengthen and elongate the muscular system. The transitions from one Asana to another are equally important as the Asana itself, requiring a concentration and technique that is guaranteed to make you sweat.</p>
				</div>
			</div>
			<!-- contentPart -->
		</div>
		<!-- BlockTwo -->

		<!-- BlockThree -->
		<div class="block30">
			<!-- contentPart -->
			<div class="textContainer">
				<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/poy-breathing.jpg" alt="" class="img-responsive" />
				<div class="iconBlock">
					<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/Icon-Yoga-Breathing.png" alt="" />
				</div>
				<div class="cntntheading">
					CONSCIOUS BREATHING
				</div>
				<div class="contnttxt">
					<p>Pranayama is the core principle of regulating your breath in your Yoga practice. ‘Prana’ means breath + ‘Ayama’ means to extend, leading to a set of breathing techniques that make you deeply aware and in control. This consciousness and awareness of our breathing is the core element to sustain life.</p>
				</div>
			</div>
			<!-- contentPart -->
		</div>
		<!-- BlockThree -->
	</div>
	<!-- gridBlockTwo -->

	<!-- gridBlockTwo -->
	<div class="gridFullWidth iconrh">
		<!-- BlockOne -->
		<div class="block30">
			<!-- contentPart -->
			<div class="textContainer">
				<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/poy-diet.jpg" alt="" class="img-responsive" />
				<div class="iconBlock">
					<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/Icon-Yoga-Diet.png" alt="" />
				</div>
				<div class="cntntheading">
					PROPER DIET
				</div>
				<div class="contnttxt">
					<p>Our bodies are made out of five elements – air, space, fire, water and earth. The three body types are a combination of these elements – Vata constitutes air and space – Pitta is made up of fire and water – and Kapha is water and earth. When thinking about food we must take into consideration not just taste, but suitability to each body type. Do you know what body type you are?</p>
				</div>
			</div>
			<!-- contentPart -->
		</div>
		<!-- BlockOne -->

		<!-- BlockTwo -->
		<div class="block30">
			<!-- contentPart -->
			<div class="textContainer">
				<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/poy-positive.jpg" alt="" class="img-responsive" />
				<div class="iconBlock">
					<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/Icon-Yoga-Thinking.png" alt="" />
				</div>
				<div class="cntntheading">
					POSITIVE THINKING
				</div>
				<div class="contnttxt">
					<p>Yoga focuses and sharpens your mind. This mental clarity promotes clear decision-making, develops confidence and enhances self-image. The practice increases productivity and effectiveness in your life.</p>
				</div>
			</div>
			<!-- contentPart -->
		</div>
		<!-- BlockTwo -->

		<!-- BlockThree -->
		<div class="block30">
			<!-- contentPart -->
			<div class="textContainer">
				<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/poy-meditation.jpg" alt="" class="img-responsive" />
				<div class="iconBlock">
					<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/Icon-Yoga-Meditation.png" alt="" />
				</div>
				<div class="cntntheading">
					MEDITATION AND<br />FEELING GROUNDED
				</div>
				<div class="contnttxt">
					<p>Embrace your inner peace and love. Yoga inspires creativity and imagination and helps develop a deeper appreciation for life. Closing your eyes in meditation improves your patience and compassion.</p>
				</div>
			</div>
			<!-- contentPart -->
		</div>
		<!-- BlockThree -->
	</div>
	<!-- gridBlockTwo -->

	<!-- bottomDivider -->
	<div class="bottomdivider"></div>
	<!-- bottomDivider -->

</div>
<!-- endCMSPages -->