				<!--  added --><div class="namaskar-overlay1">&nbsp;</div>
<script type="text/javascript">
    jQuery(window).load(function(){
        jQuery('body').css('overflow','auto');
        jQuery('.namaskar-overlay1').fadeOut('slow');
    })
</script>
<!-- startCMSPages -->
<div class="gridCMSPages">
	<!-- gridBlockOne -->
	<div class="gridFullWidth ystopsection">
		<!-- BlockLeft -->
		<div class="block33">
			<!-- leftNavigation -->
			<div class="cmsNavigation">
				<ul>
					<li><a href="/ys-fabric-tech" class="current">YS Fabric Tech</a></li>
					<li><a href="/ys-color-tech">Ys Color Tech</a></li>
					
				</ul>
			</div>
			<!-- leftNavigation -->

			<!-- CMSheadingBlock -->
			<div class="headingBlock">
				<h1 class="positionAbs">YS Fabric<br />Tech</h1>
			</div>
			<!-- CMSheadingBlock -->
		</div>
		<!-- BlockLeft -->

		<!-- BlockRight -->
		<div class="block66 posRel">
			<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/newfab.jpg" alt="" class="img-responsive" />
			<div class="positionAbs" id="ysbannertxt" style="top:32.4%;">
				<span class="topHead">Ys Fabric Tech</span>
				<h4>
					Look Closer, Go Deeper
					<span class="smallHead">consider the clothes you wear</span>
				</h4>
				<!--a href="javascript:void(0)" class="linkheader" id="discoverFabric">Discover Our Fabrics</a-->
			</div>
<div style="position:absolute; width:100%; margin:0; bottom:40px;">
<a href="javascript:void(0)" class="linkheader" id="discoverFabric">Discover Our Fabrics</a></div>
		</div>
		<!-- BlockRight -->
	</div>
	<!-- gridBlockOne -->

	<!-- gridBlockTwo -->
	<div class="gridFullWidth marginbottom50">
		<!-- BlockOne -->
		<div class="block30">
			<!-- contentPart -->
			<div class="textContainer">
				<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/ft-aurum.jpg" alt="" class="img-responsive" />
				<div class="iconBlock">
					<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/Icon-Fabric-Aurum.png" alt="" />
				</div>
				<div class="cntntheading">
					DISCOVER AURUM<sup>&reg;</sup>
                                        <span>THIS IS IT, AURUM<sup>&reg;</sup><br />EXCLUSIVELY OURS</span>
				</div>
				<div class="contnttxt">
					<p>AURUM<sup>&reg;</sup> is a technical blend of Supplex<sup>&reg;</sup> and Lycra<sup>&reg;</sup>. Our competitors use a form of Nylon that is inferior and falls apart quickly. Supplex<sup>&reg;</sup> fibers are technically far superior, giving you the soft feel and breathability of cotton with the performance benefits of advanced fiber technology.</p>
				</div>
			</div>
			<!-- contentPart -->
		</div>
		<!-- BlockOne -->

		<!-- BlockTwo -->
		<div class="block30">
			<!-- contentPart -->
			<div class="textContainer">
				<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/poy-body.jpg" alt="" class="img-responsive" />
				<div class="iconBlock">
					<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/Icon-Fabric-Moisture.png" alt="" />
				</div>
				<div class="cntntheading">
					ADVANCED MOISTURE<br />MANAGEMENT
				</div>
				<div class="contnttxt">
					<p>Take on the world and still look calm, cool and alluring. Our exclusive nanotechnology embeds moisture-wicking &amp; antimicrobial treatments into the tiniest pores of our fabric. And that means moisture &amp; bacteria make a quick exit so you’ll always make a serene entrance.</p>
				</div>
			</div>
			<!-- contentPart -->
		</div>
		<!-- BlockTwo -->

		<!-- BlockThree -->
		<div class="block30">
			<!-- contentPart -->
			<div class="textContainer">
				<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/ft-nano.jpg" alt="" class="img-responsive" />
				<div class="iconBlock">
					<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/Icon-Fabric-Nano.png" alt="" />
				</div>
				<div class="cntntheading">
					NANOTECHNOLOGY
				</div>
				<div class="contnttxt">
					<p>We use advanced nanotechnology to reach deep within the micro spaces between each weave as opposed to applying it topically on the fibers. This means far advanced moisture management. Go ahead and compare, you will see the stark difference. It’s our challenge.</p>
				</div>
			</div>
			<!-- contentPart -->
		</div>
		<!-- BlockThree -->
	</div>
	<!-- gridBlockTwo -->

	<!-- gridBlockThree -->
	<div class="gridFullWidth iconrh">
		<!-- BlockOne -->
		<div class="block30">
			<!-- contentPart -->
			<div class="textContainer">
				<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/ft-pilling.jpg" alt="" class="img-responsive" />
				<div class="iconBlock">
					<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/Icon-Fabric-NoPilling.png" alt="" />
				</div>
				<div class="cntntheading">
					RESISTANCE TO PILLING
				</div>
				<div class="contnttxt">
					<p>Leave the Pilling to Grandma’s Sweater. Your favorite things should stay your favorite things, for life. Aurum&trade; contains pilling resistant Supplex<sup>&reg;</sup> technology which generic nylons just can’t compare to. Wear it &amp; wash it till your heart’s content, and always look razor sharp. You will stay feeling good, and looking good longer.</p>
				</div>
			</div>
			<!-- contentPart -->
		</div>
		<!-- BlockOne -->

		<!-- BlockTwo -->
		<div class="block30">
			<!-- contentPart -->
			<div class="textContainer">
				<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/ft-usa.jpg" alt="" class="img-responsive" />
				<div class="iconBlock">
					<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/Icon-Fabric-MadeInUSA.png" alt="" />
				</div>
				<div class="cntntheading">
					FABRIC PROUDLY MADE<br />IN THE USA
				</div>
				<div class="contnttxt">
					<p>Science teaches, the fabric of our society can be more than the spirituality that binds us. We know that yoga pants can be hip and trendy. But, they can also create jobs for people in need when they’re manufactured in a town that’s desperate for opportunity. Not only are our fabrics made by our fellow Americans, but they are also eco-friendly as they haven’t accumulated frequent flyer miles.</p>
					<p>We are a proud American company with a deep Indian soul.</p>
				</div>
			</div>
			<!-- contentPart -->
		</div>
		<!-- BlockTwo -->

		<!-- BlockThree -->
		<div class="block30">
			<!-- contentPart -->
			<div class="textContainer">
				<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/ft-stretch.jpg" alt="" class="img-responsive" />
				<div class="iconBlock">
					<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/Icon-Fabric-Stretch.png" alt="" />
				</div>
				<div class="cntntheading">
					HIGH QUALITY STRETCH
				</div>
				<div class="contnttxt">
					<p>We use a superior form of Lycra<sup>&reg;</sup> with very high memory retention. Our fabrics always bounce back for that snug feeling. You can reach, bend, and move through life anyway you wish and our clothes will gracefully follow.</p>
				</div>
			</div>
			<!-- contentPart -->
		</div>
		<!-- BlockThree -->
	</div>
	<!-- gridBlockThree -->

	<!-- gridBlockFour -->
	<div class="gridBottomDesp">
		<a name="discoverFabric"></a>
		<!-- BlockOne -->
		<div class="block30">
			<!-- contentPart -->
			<div class="textContainer">
				<strong>DISCOVER OUR FABRICS</strong>
			</div>
			<!-- contentPart -->
		</div>
		<!-- BlockOne -->

		<!-- BlockTwo -->
		<div class="block66">
			<!-- contentPart -->
			<div class="textContainer">
				<p>Just as good alignment is a foundation of yoga, great fabric technology is the true foundation for our apparel. The fiber makes the fabric, the fabric makes our clothes and our clothes make you feel like making a difference every day. This is why we delve so deeply into the process - assuming responsibility for each step of the production process - from sourcing fiber to bringing you the finished apparel. We research &amp; develop it, we manufacture it, we dye it, we cut it, we stitch it, we pack it, and we ship it - why? - so in the end you enjoy it.</p>
                                <p>Within these fibers there is enlightenment. Sometimes in life it’s as simple as the choices you make. Choices that show that you are someone who cares. Someone with a vision to see, fabrics that are cool and dry, and anti-bacterial are all the more ingenuous when they are spun in a mill that is committed to lessening its carbon footprint.</p>
				<p class="goldtext">Gold is the YOGASMOGA color. We chose it because it reflects the high quality of our products. All our fabric names are derived from the properties that are embodied by Gold.</p>
			</div>
			<!-- contentPart -->
		</div>
		<!-- BlockTwo -->
	</div>
	<!-- gridBlockFour -->

	<!-- gridBlockFive
	<div class="gridBottomDesp nogridborder">
		<div class="textContainer">
			<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/aurum-technology.jpg" alt="" class="img-responsive" />
		</div>
	</div>
	gridBlockFive -->

	<!-- AURUMTable -->
	<table cellpadding="0" cellspacing="0" border="0" class="fabrictable nogridborder">
		<tr>
			<td width="31.9%">
				<table width="100%" cellpadding="0" cellspacing="0" border="0" class="aurumheadingcell">
					<tr>
						<td class="gbold">TECHNOLOGIES</td>
					</tr>
					<tr>
						<td>Aurum<sup>&reg;</sup></td>
					</tr>
					<tr>
						<td>Aurum<sup>&reg;</sup> 24 </td>
					</tr>
					<tr>
						<td>Aurum<sup>&reg;</sup> 1064</td>
					</tr>
					<tr>
						<td>Auro mesh</td>
					</tr>
					<tr>
						<td>Aurum<sup>&reg;</sup> stripe</td>
					</tr>
					<tr>
						<td>Aurum<sup>&reg;</sup> Mini stripe <small>*new</small></td>
					</tr>
					<tr>
						<td>koura<sup>&trade;</sup></td>
					</tr>
					<tr>
						<td>koura<sup>&trade;</sup> 24 <small>*new</small></td>
					</tr>
					<tr>
						<td>Airh<sup>&trade;</sup></td>
					</tr>
                                         <tr>
						<td>Aurum<sup>&reg;</sup> Helix</td>
					</tr>
				</table>
			</td>
			<td width="68.00847457627119%">
				<table width="100%" cellpadding="0" cellspacing="0" border="0" class="aurumiconcell">
				<tr class="headingcell">
					<td colspan="7">YS FABRIC TECH</td>
					<td colspan="4">YS color TECH</td>
				</tr>
				<tr>
					<td>ADVANCED<br />MOISTURE<br />MGMT</td>
					<td>NANO<br />TECHNO<br />LOGY</td>
					<td>PILLING<br />RESISTANCE</td>
					<td>COOL<br />SMOOTH &<br />SUPPLE<BR />FEEL</td>
					<td>HIGH<br />QUALITY<br />STRETCH</td>
					<td>LIGHT<br />WEIGHT<br />FABRIC</td>
					<td>SUPERIOR<br />SUPPORT</td>
					<td>ECO-<br />FRIENDLY<br />DYEING</td>
					<td>COLORS<br />THAT WON'T<br />BLEED</td>
					<td>COLOR<br />ACCURACY</td>
					<td>COLORS<br />THAT WON'T<br />FADE</td>
<!-- 					<td colspan="7">
						<table width="100%" cellpadding="0" cellspacing="0" border="0">
							<tr>
								<td>ADVANCED<br />MOISTURE<br />MGMT</td>
								<td>NANO<br />TECHNO<br />LOGY</td>
								<td>PILLING<br />RESISTANCE</td>
								<td>COOL<br />SMOOTH &<br />SUPPLE<BR />FEEL</td>
								<td>HIGH<br />QUALITY<br />STRETCH</td>
								<td>LIGHT<br />WEIGHT<br />FABRIC</td>
								<td>SUPERIOR<br />SUPPORT</td>
							</tr>
						</table>						
					</td>

					<td colspan="4">
						<table width="100%" cellpadding="0" cellspacing="0" border="0">
							<tr>
								<td>ECO-<br />FRIENDLY<br />DYEING</td>
								<td>COLORS<br />THAT WON'T<br />BLEED</td>
								<td>COLOR<br />ACCURACY</td>
								<td>COLORS<br />THAT WON'T<br />FADE</td>
							</tr>
						</table>
					</td> -->
				</tr>
				<tr>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/moisture.png')?>" alt="" /></td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/cloud.png')?>" alt="" /></td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/resistance.png')?>" alt="" /></td>
					<td align="center" valign="middle">&nbsp;</td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/strech.png')?>" alt="" /></td>
					<td align="center" valign="middle">&nbsp;</td>
					<td align="center" valign="middle">&nbsp;</td>

					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/deiyng.png')?>" alt="" /></td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/bleed.png')?>" alt="" /></td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/accuracy-icon.jpg')?>" alt="" /></td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/fade-icon.png')?>" alt="" /></td>
				</tr>
				<tr>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/moisture.png')?>" alt="" /></td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/cloud.png')?>" alt="" /></td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/resistance.png')?>" alt="" /></td>
					<td align="center" valign="middle">&nbsp;</td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/strech.png')?>" alt="" /></td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/lfabric.png')?>" alt="" /></td>
					<td align="center" valign="middle">&nbsp;</td>

					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/deiyng.png')?>" alt="" /></td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/bleed.png')?>" alt="" /></td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/accuracy-icon.jpg')?>" alt="" /></td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/fade-icon.png')?>" alt="" /></td>
				</tr>
				<tr>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/moisture.png')?>" alt="" /></td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/cloud.png')?>" alt="" /></td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/resistance.png')?>" alt="" /></td>
					<td align="center" valign="middle">&nbsp;</td>
					<td align="center" valign="middle">&nbsp;</td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/lfabric.png')?>" alt="" /></td>
					<td align="center" valign="middle">&nbsp;</td>

					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/deiyng.png')?>" alt="" /></td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/bleed.png')?>" alt="" /></td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/accuracy-icon.jpg')?>" alt="" /></td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/fade-icon.png')?>" alt="" /></td>
				</tr>
				<tr>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/moisture.png')?>" alt="" /></td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/cloud.png')?>" alt="" /></td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/resistance.png')?>" alt="" /></td>
					<td align="center" valign="middle">&nbsp;</td>
					<td align="center" valign="middle">&nbsp;</td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/lfabric.png')?>" alt="" /></td>
					<td align="center" valign="middle">&nbsp;</td>

					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/deiyng.png')?>" alt="" /></td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/bleed.png')?>" alt="" /></td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/accuracy-icon.jpg')?>" alt="" /></td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/fade-icon.png')?>" alt="" /></td>
				</tr>
				<tr>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/moisture.png')?>" alt="" /></td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/cloud.png')?>" alt="" /></td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/resistance.png')?>" alt="" /></td>
					<td align="center" valign="middle">&nbsp;</td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/strech.png')?>" alt="" /></td>
					<td align="center" valign="middle">&nbsp;</td>
					<td align="center" valign="middle">&nbsp;</td>

					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/deiyng.png')?>" alt="" /></td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/bleed.png')?>" alt="" /></td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/accuracy-icon.jpg')?>" alt="" /></td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/fade-icon.png')?>" alt="" /></td>
				</tr>
				<tr>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/moisture.png')?>" alt="" /></td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/cloud.png')?>" alt="" /></td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/resistance.png')?>" alt="" /></td>
					<td align="center" valign="middle">&nbsp;</td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/strech.png')?>" alt="" /></td>
					<td align="center" valign="middle">&nbsp;</td>
					<td align="center" valign="middle">&nbsp;</td>

					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/deiyng.png')?>" alt="" /></td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/bleed.png')?>" alt="" /></td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/accuracy-icon.jpg')?>" alt="" /></td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/fade-icon.png')?>" alt="" /></td>
				</tr>
				<tr>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/moisture.png')?>" alt="" /></td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/cloud.png')?>" alt="" /></td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/resistance.png')?>" alt="" /></td>
					<td align="center" valign="middle">&nbsp;</td>
					<td align="center" valign="middle">&nbsp;</td>
					<td align="center" valign="middle">&nbsp;</td>
					<td align="center" valign="middle">&nbsp;</td>

					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/deiyng.png')?>" alt="" /></td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/bleed.png')?>" alt="" /></td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/accuracy-icon.jpg')?>" alt="" /></td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/fade-icon.png')?>" alt="" /></td>
				</tr>
				<tr>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/moisture.png')?>" alt="" /></td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/cloud.png')?>" alt="" /></td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/resistance.png')?>" alt="" /></td>
					<td align="center" valign="middle">&nbsp;</td>
					<td align="center" valign="middle">&nbsp;</td>
					<td align="center" valign="middle">&nbsp;</td>
					<td align="center" valign="middle">&nbsp;</td>

					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/deiyng.png')?>" alt="" /></td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/bleed.png')?>" alt="" /></td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/accuracy-icon.jpg')?>" alt="" /></td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/fade-icon.png')?>" alt="" /></td>
				</tr>
				<tr>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/moisture.png')?>" alt="" /></td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/cloud.png')?>" alt="" /></td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/resistance.png')?>" alt="" /></td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/cool-supple.png')?>" alt="" /></td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/strech.png')?>" alt="" /></td>
					<td align="center" valign="middle">&nbsp;</td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/superior-support.png')?>" alt="" /></td>

					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/deiyng.png')?>" alt="" /></td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/bleed.png')?>" alt="" /></td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/accuracy-icon.jpg')?>" alt="" /></td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/fade-icon.png')?>" alt="" /></td>
	    			</tr>
                                <tr>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/moisture.png')?>" alt="" /></td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/cloud.png')?>" alt="" /></td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/resistance.png')?>" alt="" /></td>
					<td align="center" valign="middle">&nbsp;</td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/strech.png')?>" alt="" /></td>
					<td align="center" valign="middle">&nbsp;</td>
					<td align="center" valign="middle">&nbsp;</td>

					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/deiyng.png')?>" alt="" /></td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/bleed.png')?>" alt="" /></td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/accuracy-icon.jpg')?>" alt="" /></td>
					<td align="center" valign="middle"><img src="<?php echo $this->getSkinUrl('images/fabric-table-icons/fade-icon.png')?>" alt="" /></td>
				</tr>

				</table>
			</td>
		</tr>
	</table>
	<!-- AURUMTable -->

</div>
<!-- endCMSPages -->