<script type="text/javascript" src="https://js.stripe.com/v1/"></script>
<div id="customer_info_tabs_customer_edit_tab_stripe_content">
	<div class="entry-edit">
		<div class="entry-edit-head">
			<h4 class="icon-head head-edit-form fieldset-legend">Stripe Tab<?php if ($this->getIsStripeCustomer()) : ?> | <a id="stripe-update-payment" class="use"><?php echo $this->__("Edit") ?></a> | <a id="stripe-delete-payment" class="use"><?php echo $this->__('Delete')?></a><?php endif; ?></h4>
		</div>
		<div class="fieldset">
			<div class="hor-scroll">
				<form action="<?php echo $this->getUrl("adminhtml/stripe/save") ?>" method="post" name="stripe-payment" id="stripe-payment">
					<input type="hidden" name="stripe[customer_id]" value="<?php echo $this->getCustomer()->getEntityId() ?>" id="customer_id" />
					<input type="hidden" name="stripe[stripe_token]" value="" id="stripe_token" />
					<table cellspacing="0" class="form-list" id="stripe-change-payment-form" <?php if ($this->getIsStripeCustomer()): ?>style="display: none;"<?php endif; ?>>
						<tr>
							<td class="label">
								<label for="firstname">Cardholder Name<span class="required">*</span></label>
							</td>
				        	<td class="value">
				            	<input type="text" id="fullname" name="fullname" value="<?php echo $this->getCustomer()->getName() ?>" title="Full Name" maxlength="255" class="input-text required-entry stripe-toggle-valid">
				        	</td>
				        </tr>
			        	<?php if ($this->sendAddressData()) : ?>
			        		<?php if ($this->getBillingAddress()->getEntityId()==0) : ?>
			        		<tr>
			        			<td class="label">
			        			</td>
			        			<td class="value">
			        	 			<label for="also_save_as_primary_billing_address">Save this address as Primary Billing Address?</label>
			        	 			<input type="checkbox" name="also_save_as_primary_billing_address" id="also_save_as_primary_billing_address" checked="checked" />
				        	 		<input type="hidden" name="firstname" value="<?php echo $this->getCustomer()->getFirstname() ?>" />
				        	 		<input type="hidden" name="lastname" value="<?php echo $this->getCustomer()->getLastname() ?>" />
			        	 		</td>
		        	 		</tr>
		        	 		<tr>
		        	 			<td class="label">
				        	 		<label for="telephone">Telephone <span class="required">*</span></label>
				        	 	</td>
				        	 	<td class="value">
			        	 			<input type="text" id="telephone" name="telephone" value="" title="Telephone" class="input-text required-entry stripe-toggle-valid" />
			        	 		</td>
		        	 		</tr>
		        	 		<?php endif; ?>
						<tr>
							<td class="label">
						 		<label for="street_1">Street Address<span class="required">*</span></label>
						 	</td>
						 	<td class="value">
						 		<div class="multi-value">
						 			<input type="text" name="street[]" value="<?php echo $this->getBillingAddress()->getStreet1(); ?>" title="Street Address" id="street_1" class="input-text  required-entry stripe-toggle-valid">	
						 		</div>
						 		<br />
						 		<div class="multi-value">
						 			<input type="text" name="street[]" value="<?php echo $this->getBillingAddress()->getStreet2() ?>" title="Street Address 2" id="street_2" class="input-text ">
						 		</div>
							</td>
				  		</tr>
						<tr>
					 		<td class="label">
								<label for="city">City</label>
							</td>
							<td class="value">
					    		<input type="text" name="city" value="<?php echo $this->getBillingAddress()->getCity() ?>" title="City" class="input-text  required-entry stripe-toggle-valid" id="city">
					    	</td>
					   </tr>
					   <tr>
							<td class="label">
								<label for="region_id">State/Province<span class="required">*</span></label>
							</td>
							<td class="value">
					    		<select id="region_id" name="region_id" title="State/Province" class="validate-select required-entry stripe-toggle-valid" style="" defaultvalue="0">
						  		<option value="">Please select region, state or province</option>
						  		</select>
							    <script type="text/javascript">
							    //<![CDATA[
								   $('region_id').setAttribute('defaultValue',  "<?php echo $this->getBillingAddress()->getRegionId() ?>");
							    //]]>
							    </script>
					    		<input type="text" id="region" name="region" value="<?php echo $this->getBillingAddress()->getRegion() ?>" title="State/Province" class="input-text required-entry stripe-toggle-valid" style="display: none; ">
					    	</td>
				 		</tr>
						<tr>
						 	<td class="label">
								<label for="zip">Zip/Postal Code<span class="required">*</span></label>
							</td>
							<td class="value">
							    <input type="text" name="postcode" value="<?php echo $this->getBillingAddress()->getPostcode() ?>" title="Zip/Postal Code" id="zip" class="input-text validate-zip-international  required-entry stripe-toggle-valid">
							</td>
						</tr>
						<tr>
							<td class="label">
								<label for="country">Country<span class="required">*</span></label>
							</td>
							<td class="value">
							    <?php echo $this->getCountryHtmlSelect() ?>
							</td>
					  	</tr>
					  <?php endif; ?>
				  	  <?php if ($this->getAlwaysCreateStripeCustomer()) : ?>
				  	  		<tr>
					  			<td colspan="2">
									<input type="hidden" name="create_stripe_customer" value="<?php if ($this->getIsStripeCustomer()) : ?>0<?php else : ?>1 <?php endif; ?>" />
								</td>
							</tr>
					  <?php else : ?>
					  	<tr>
							<td class="label">
								<label for="create_stripe_customer"><?php echo Mage::helper('payment')->__("Save card for later use?")?></label>
							</td>
							<td class="value">
								<input type="checkbox" value="1" name="stripe[create_stripe_customer]" id="stripe_create_stripe_customer" <?php if ($this->getAlwaysChecked()) : ?>checked="checked"<?php endif; ?> />
							</td>
						</tr>
					 <?php endif; ?>
					  	
						<tr>		
							<td class="label">
					            <label for="stripe_cc_number"><?php echo Mage::helper('payment')->__('Credit Card Number') ?> <span class="required">*</span></label><br/>
					       	</td>
					       	<td class="value">
					            <input type="text" id="stripe_cc_number" name="stripe[cc_number]" title="<?php echo Mage::helper('payment')->__('Credit Card Number') ?>" class="input-text validate-cc-number" value="<?php echo $this->getInfoData('cc_number')?>"/>
					        </td>
					   	</tr>
					   	<tr>
							<td class="label">
					            <label for="stripe_expiration"><?php echo Mage::helper('payment')->__('Expiration Date') ?> <span class="required">*</span></label>
					        </td>
					        <td class="value">
					        	<div class="multi-value">
							            <select id="stripe_expiration" style="width:140px;" name="stripe[cc_exp_month]" class="validate-cc-exp required-entry stripe-toggle-valid">
							            <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
							            <?php foreach ($this->getCcMonths() as $k=>$v): ?>
							                <option value="<?php echo $k ?>" <?php if($k==$_ccExpMonth): ?>selected="selected"<?php endif ?>><?php echo $v ?></option>
							            <?php endforeach ?>
							            </select>
							            <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
							            <select id="stripe_expiration_yr" style="width:103px;" name="stripe[cc_exp_year]" class="required-entry stripe-toggle-valid">
							            <?php foreach ($this->getCcYears() as $k=>$v): ?>
							                <option value="<?php echo $k ? $k : '' ?>" <?php if($k==$_ccExpYear): ?>selected="selected"<?php endif ?>><?php echo $v ?></option>
							            <?php endforeach ?>
							            </select>
							    </div>
							</td>
						</tr>
					    <?php if($this->hasVerification()): ?>
					        <tr>
					        	<td class="label">
					            	<label for="stripe_cc_cid"><?php echo Mage::helper('payment')->__('Card Verification Number') ?> <span class="required">*</span></label>
					            </td>
					            <td class="value">
					            	<input type="text" title="<?php echo Mage::helper('payment')->__('Card Verification Number') ?>" class="required-entry stripe-toggle-valid input-text validate-cc-cvn" id="stripe_cc_cid" name="stripe[cc_cid]" style="width:3em;" value="<?php echo $this->getInfoData('cc_cid')?>"/>
					            </td>
					        </tr>
					    <?php endif; ?>
					</table>
					<table class="form-list" cellspacing="0" id="stripe-payment-details">
						<?php if ($this->getIsStripeCustomer()) : ?>
							<tr>
								<td class="value">
									<input type="hidden" name="stripe[stripe_customer_id]" value="<?php echo $this->getStripeCustomerId() ?>" id="stripe_stripe_customer_id" />
									<?php echo $this->getPaymentHtml(); ?>
								</td>
							</tr>
						<?php else: ?>
							<tr>
								<td>
									<input type="hidden" name="stripe[stripe_customer_id]" value="" id="stripe_stripe_customer_id" />
								</td>
							</tr> 
						<?php endif; ?>
					</table>
					<ul id="stripe-buttons-container">
						<li>
							<button id="stripe_save_payment" title="Save Payment" type="button" class="scalable save" name="save_payment" onclick="javascript:saveStripePayment(); return false;"><span><span><span>Save Payment</span></span></span></button>
						</li>
					</ul>								
				</form>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
//<![CDATA[
	Stripe.setPublishableKey('<?php echo $this->getPublishableKey() ?>');

	var loadWaiting = false;
	
	var form = new varienForm('stripe-payment');
	
	<?php if ($this->getIsStripeCustomer()) : ?>
		$('stripe-payment').disabled = true;
		$('stripe-update-payment').observe('click',function(event){
			Event.stop(event);
			if ($('stripe-change-payment-form').visible()) {
				$('stripe-change-payment-form').hide();
				$('stripe-payment-details').show();
				$('stripe_create_stripe_customer').value = '0';
				$('stripe-payment').disabled = true;
				$(this).update("Edit");
			} else {
				$(this).update("Use Existing");
				$('stripe-change-payment-form').show();
				$('stripe-payment-details').hide();
				$('stripe_create_stripe_customer').value = "1";
				$('stripe-payment').disabled = false;
			}
		});	
		$('stripe-delete-payment').observe('click',function(){
		 var request = new Ajax.Request(
                 '<?php echo $this->getUrl("adminhtml/stripe/delete") ?>',
                     {
                         method:'post',
                         onComplete: stripeComplete,
                         onSuccess: stripeSuccess,
                         onFailure: stripeFailure,
                         parameters: {stripe_customer_id:$F('stripe_stripe_customer_id'),customer_id:$F('customer_id')}
                     }
                 );
		});
		
	<?php endif; ?>

	saveStripePayment = function() {
	         var validator = new Validation($('stripe-payment'));
	         if (validator.validate()) {
//		         setLoading(true);
	             if ($F('stripe_stripe_customer_id') == ""||$F("stripe_create_stripe_customer")=="1") {
	            	 Stripe.createToken({
	            		 name: $F("fullname"),
		            	 <?php if ($this->sendAddressData()) : ?>
			            	address_line1: $F("street_1"),
			            	address_line2: $F("street_2"),
			            	address_state: $F("region"),
			            	address_zip: $F("zip"),
			            	address_country: $F("country_id"),
		            	 <?php endif; ?>
	     				number: $F('stripe_cc_number'),
	     				<?php if ($this->hasVerification()) : ?>
	     				cvc: $F('stripe_cc_cid'),
	     				<?php endif; ?>
	     				exp_month: $F('stripe_expiration'),
	     				exp_year: $F('stripe_expiration_yr')
	     			}, stripeResponseHandler.bind(this));
	             } else {
	            	 var request = new Ajax.Request(
	                         '<?php echo $this->getUrl("adminhtml/stripe/save") ?>',
		                         {
		                             method:'post',
		                             onComplete: stripeComplete,
		                             onSuccess: stripeSuccess,
		                             onFailure: stripeFailure,
		                             parameters: Form.serialize($('stripe-payment'))
		                         }
		                     );
		             }
		         }
	    };

	    function disableEnableAll(element, isDisabled) {
	        var descendants = element.descendants();
	        for (var k in descendants) {
	            descendants[k].disabled = isDisabled;
	        }
	        element.disabled = isDisabled;
	    }
	    
	    function setLoading(state)
	    {
		    loadWaiting = state;
	    	var container = $('stripe-buttons-container');
            container.addClassName('disabled');
            container.setStyle({opacity:.5});
            disableEnableAll(container, true);
            Element.show('stripe-please-wait');
	    }

	    function stripeComplete(transport) {
		//    setLoading(false);
	    }

	    function stripeSuccess(transport) {
		  //  setLoading(false);
	    	window.location.reload();
	    } 
	   

		function stripeFailure(transport) {
			if (transport && transport.responseText){
	            try{
	                response = eval('(' + transport.responseText + ')');
	            }
	            catch (e) {
	                response = {};
	            }
	        }
	        
			 if (response.error) {
	            if (response.fields) {
	                var fields = response.fields.split(',');
	                for (var i=0;i<fields.length;i++) {
	                    var field = null;
	                    if (field = $(fields[i])) {
	                        Validation.ajaxError(field, response.error);
	                    }
	                }
	                return;
	            }
	            alert(response.error);
	            return;
	        }
		}
		
		function stripeResponseHandler(status, response) {
		    if (response.error) {
		        alert(response.error.message);
		    } else {
		        var token = response['id'];
		        $('stripe_token').value = token;
		        var request = new Ajax.Request(
        			'<?php echo $this->getUrl("adminhtml/stripe/save") ?>',	
                 {
                     method:'post',
                     onComplete: stripeComplete,
                     onSuccess: stripeSuccess,
                     onFailure: stripeFailure,
                     parameters: Form.serialize($('stripe-payment'))
                 }
             );
	    }
	}
	
	<?php if ($this->sendAddressData()) : ?>
		var regionUpdater = new RegionUpdater('country_id', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
	<?php endif; ?>
		
//]]>
</script>