<div id="invite_friends" style="display: none;">
   <div class="invite-left f-left">
       <img class="full-width" src="<?php echo $this->getUrl()?>skin/frontend/new-yogasmoga/yogasmoga-theme/images/popups/dummy-in.png"/>
   </div>
   <div class="invite-right f-right">
        <div class="invite-form">
            <p class="c-align smogi-love-msg" style="font-size:18px;">Share the SMOGI Love with your<br /> friends - they will receive $25<br /> SMOGI Bucks upon sign-up!</p>
            <form id="invite-friend-form" class="bl" action="" method="post">
                <table width="100%" cellpadding="0" cellspacing="0">
                    <tr>
                        <td>
                            <input type="text" id="friendname" name="friendname" class="watermark" watermark="Friend's Name" value="" maxlength="30" class="requiredfield">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <input type="text" id="friendemail" name="friendemail" class="watermark" watermark="Friend's Email" value="" maxlength="30" class="requiredfield">
                        </td>
                    </tr>
                    <tr>
                        <td class="no-padding">
                            <input class="pointer" type="submit" id="send-invite" value="" style="background-image: url(<?php echo $this->getUrl()?>skin/frontend/new-yogasmoga/yogasmoga-theme/images/popups/send-invite.png); width:100%; height:39px; background-size:100% 100%; border:none;">
                        </td>
                        <td align="center" class="form-loader no-padding c-align"></td>
                    </tr>
                    <tr>
                        <td>
                            <p style="min-height:15px;  margin: 0 auto; font-size: 12px; visibility:hidden" class="err-msg">All fields are required.</p>
                        </td>
                        </tr>                        
                </table>
            </form>
        </div>
        <div class="invite-message mt100 no-display">
            <p>Thank you for sharing SMOGI love.</p>
            <p class="mtop10"><input class="pointer" type="button" id="continue-shopping" value="" style="background-image: url(<?php echo $this->getUrl()?>skin/frontend/new-yogasmoga/yogasmoga-theme/images/popups/continue-shopping.png); width:100%; height:39px; background-size:100% 100%; border:none;"></p>
        </div>       
   </div>
    
</div>