<div class="custom-block">
    <div class="ys-bottom">
        <div style="display: none" class="account-nav l-align ys_static_page_dropdown">
            <ul class="sub-nav static_page">
                <li><a rel="faq" class="active_link" data-heading="HELP" href="#faq">FAQ</a></li>
                <li><a rel="shipping-returns" data-heading="HELP" href="#shipping-returns">SHIPING AND RETURNS</a></li>
                <li><a rel="size-chart" data-heading="HELP" href="#size-chart">SIZE CHARTS</a></li>
                <li><a rel="product-care" data-heading="HELP" href="#product-care">PRODUCT CARE</a></li>
                <li><a rel="email-us" data-heading="HELP" href="#email-us">EMAIL US</a></li>
            </ul>
        </div>
    </div>
</div>
<!-- START OF PAGE ACCORDION -->

<div class="help_page" id="faq">
    <p>FAQ</p>
    <ul>
        <li>
            <span class="toggle">
                <svg height="44px" width="44px">
                    <line y2="109.657" x2="288.374" y1="109.657" x1="272.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                    <line y2="21.39" x2="30.374" y1="21.39" x1="14.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                    <line y2="29.39" x2="22.374" y1="13.39" x1="22.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                </svg>
            </span>

            <p>WHERE DOES THE NAME YOGASMOGA<span>...</span></p>

            <div class="answer_content">
                <span> COME FROM AND WHAT DOES IT MEAN?</span>

                <div>
                    <p>Our founders have a real and authentic connection to Yoga. They are Indian by heritage and
                        American & Indian by citizenship. In their formative years, they grew up in the upper Ganges
                        plains area of the Himalayan ranges in India. This mystical area is considered the true home,
                        birthplace and capital of Yoga and has a culture that has fascinated many men, women, Yogi's,
                        saints and famous musicians for centuries.
                    </p>

                    <p>When naming their company our founders wanted to include the word YOGA prominently in the name.
                        They rhymed the word YOGA with SMOGA as a nod to traditional Indian culture where it is common
                        to rhyme similar things. The word SMOGA represents all things that go with YOGA&mdash;so our
                        name
                        is a jubilant nod of respect to our culture and clearly defines who we are.</p>
                </div>
            </div>
        </li>
        <li>
            <span class="toggle">
                <svg height="44px" width="44px">
                    <line y2="109.657" x2="288.374" y1="109.657" x1="272.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                    <line y2="21.39" x2="30.374" y1="21.39" x1="14.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                    <line y2="29.39" x2="22.374" y1="13.39" x1="22.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                </svg>
            </span>

            <p>ARE YOU AN AMERICAN COMPANY?</p>

            <div class="answer_content">
                <!-- <span>CAME FROM ?</span>-->
                <div>
                    <p>Yes. We are very proud to be an American Company. Our headquarters are in New York City.</p>

                    <p>If you are in the New York region and want to connect with us, please feel free to drop us a line
                        at <a href="mailto:hello@yogasmoga.com">hello@yogasmoga.com</a>.</p>
                </div>
            </div>
        </li>

        <li>
            <span class="toggle">
                <svg height="44px" width="44px">
                    <line y2="109.657" x2="288.374" y1="109.657" x1="272.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                    <line y2="21.39" x2="30.374" y1="21.39" x1="14.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                    <line y2="29.39" x2="22.374" y1="13.39" x1="22.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                </svg>
            </span>

            <p>ARE YOU AN ENVIRONMENTALLY<span>...</span></p>

            <div class="answer_content">
                <span> FRIENDLY COMPANY?</span>

                <div>
                    <p>Yes, we work extremely hard to reduce our carbon footprint. We manufacture in factories which
                        have the highest eco standards. Furthermore, we do not ship our goods from across the globe,
                        thus reducing our Carbon footprint significantly.</p>
                </div>
            </div>
        </li>
        <li>
            <span class="toggle">
                <svg height="44px" width="44px">
                    <line y2="109.657" x2="288.374" y1="109.657" x1="272.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                    <line y2="21.39" x2="30.374" y1="21.39" x1="14.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                    <line y2="29.39" x2="22.374" y1="13.39" x1="22.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                </svg>
            </span>

            <p>DO YOU HAVE A PHYSICAL STORE?</p>

            <div class="answer_content">
                <!-- <span>COMPANY?</span>-->
                <div>
                    <p>With open hearts, we introduced 2 retail locations: Greenwich, CT and Brentwood, Los Angeles in the year 2014.
                        In 2015, we expanded to 10 more retail location in cities such as: Newport Beach, La Jolla, San Francisco, Malibu, Short Hills, Corte Madera and Boston.
                    </p>

                    <p>Additionally, if you are in the New York City area we encourage you to set up an appointment to visit us at our headquarters in New York City! Please contact <a
                            href="mailto:hello@yogasmoga.com">hello@yogasmoga.com</a>.
                    </p>
                </div>
            </div>
        </li>
        <li>
            <span class="toggle">
                <svg height="44px" width="44px">
                    <line y2="109.657" x2="288.374" y1="109.657" x1="272.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                    <line y2="21.39" x2="30.374" y1="21.39" x1="14.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                    <line y2="29.39" x2="22.374" y1="13.39" x1="22.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                </svg>
            </span>

            <p>HOW DO I CONNECT ONLINE WITH<span>...</span></p>

            <div class="answer_content">
                <span>YOGASMOGA?</span>

                <div>
                    <p>Connect with us at <a href="http://facebook.com/yogasmoga">facebook.com/yogasmoga</a> or
                        <a href="http://www.twitter.com/yogasmoga">@yogasmoga</a> and get your SMOGA on.</p>
                </div>
            </div>
        </li>
        <!--<li>
            <span class="toggle">
                <svg height="44px" width="44px">
                    <line y2="109.657" x2="288.374" y1="109.657" x1="272.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                    <line y2="21.39" x2="30.374" y1="21.39" x1="14.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                    <line y2="29.39" x2="22.374" y1="13.39" x1="22.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                </svg>
            </span>

            <p>HOW DOES YOUR PRODUCT COMPARE<span>...</span></p>

            <div class="answer_content">
                <span>TO YOUR COMPETITORS?</span>

                <div>
                    <p>We spend significant time and resource in developing our fabric and dyeing technology. Our
                        technology is developed in advanced research labs in the USA. We strongly believe that superior
                        raw materials we use leads to superior products. It is our opinion that the fabric we produce in
                        the USA is far superior to what our competitors deliver by importing from China. Many of the
                        performance attributes have been stringently tested in our research and development labs.</p>
                </div>
            </div>
        </li>-->
    </ul>
</div>

<div class="help_page" id="shipping-returns">
    <p>SHIPPING AND RETURNS</p>
    <ul>
        <li>
            <span class="toggle">
                <svg height="44px" width="44px">
                    <line y2="109.657" x2="288.374" y1="109.657" x1="272.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                    <line y2="21.39" x2="30.374" y1="21.39" x1="14.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                    <line y2="29.39" x2="22.374" y1="13.39" x1="22.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                </svg>
            </span>

            <p>DO YOU OFFER FREE DELIVERY?</p>

            <div class="answer_content">
                <!-- <span>CAME FROM ?</span>-->
                <div>
                    <p>Yes. We offer Free 3-5 business day delivery to our SMOGIs to all locations within the United
                        States of America including Alaska, Hawaii, Puerto Rico and PO/APO/FPO addresses.</p>

                    <p>We are also pleased to offer Free International 6-10 business day delivery to all our Canadian
                        SMOGIs. </p>

                    <p>For all our International SMOGIs we offer the $35 YS International Priority Shipping
                        Service&mdash;which means 6-10 business days service in most instances via a complimentary
                        upgrade to expedited service.</p>

                    <p style="font-family: graphik-semibold;">Just Remember to have your order in to us by 3:00 PM EST
                        so you
                        can receive your order in time.</p>

                    <p><span style="font-family: graphik-semibold;">Note:</span> Shipping charges do not include
                        international
                        taxes or duties. Recipient is responsible for all applicable taxes and duties.</p>
                </div>
            </div>
        </li>
        <li>
            <span class="toggle">
                <svg height="44px" width="44px">
                    <line y2="109.657" x2="288.374" y1="109.657" x1="272.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                    <line y2="21.39" x2="30.374" y1="21.39" x1="14.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                    <line y2="29.39" x2="22.374" y1="13.39" x1="22.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                </svg>
            </span>

            <p>DO YOU OFFER FREE RETURNS?</p>

            <div class="answer_content">
                <!--<span>CAME FROM ?</span>-->
                <div>
                    <p>Yes. We offer Free Returns within the United States of America including Alaska, Hawaii, Puerto
                        Rico and PO/APO/FPO addresses to complement our Free Delivery service. To receive a free return
                        label, please contact <a href="mailto:hello@yogasmoga.com">hello@yogasmoga.com</a> and we will
                        be happy to email a return label to you.</p>

                    <p>At this point we are unable to offer Free Returns to our Canadian &amp; International SMOGIs due
                        to customs related logistics.</p>

                    <p>Please direct returns to:</p>

                    <p>YOGASMOGA<br>502 Bedford Street, 2nd Floor<br>Fall River, MA
                        02720<br>USA</p>
                </div>
            </div>
        </li>
        <li>
            <span class="toggle">
                <svg height="44px" width="44px">
                    <line y2="109.657" x2="288.374" y1="109.657" x1="272.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                    <line y2="21.39" x2="30.374" y1="21.39" x1="14.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                    <line y2="29.39" x2="22.374" y1="13.39" x1="22.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                </svg>
            </span>

            <p>WHAT IS YOUR RETURN POLICY?</p>

            <div class="answer_content">
                <!--<span>CAME FROM ?</span>-->
                <div><p>We accept returns on unworn and undamaged products within one month of the shipping date. Once we receive your returned items, a full refund will be issued back to the original method of payment used to place the order per item returned. Please allow 5 - 7 business days for your bank to process the refund.</p>
                </div>
            </div>
        </li>
        <li>
            <span class="toggle">
                <svg height="44px" width="44px">
                    <line y2="109.657" x2="288.374" y1="109.657" x1="272.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                    <line y2="21.39" x2="30.374" y1="21.39" x1="14.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                    <line y2="29.39" x2="22.374" y1="13.39" x1="22.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                </svg>
            </span>

            <p>DO YOU OFFER GUARANTEED EXPEDITED<span>...</span></p>

            <div class="answer_content">
                <span>SHIPPING OPTIONS?</span>

                <div><p>Yes. We offer 2 business day and 1 business day Guaranteed shipping options to all locations
                        within the United States of America including Alaska, Hawaii, Puerto Rico and PO/APO/FPO
                        addresses.</p>

                    <p>If you are a Canadian SMOGI looking for faster service, a good route to go is the YS Prime
                        Service which means delivery within 3/6 business days in most instances.</p>

                    <p>Just remember to have your orders in to us by 4:00 PM EST for
                        all Guaranteed and YS Prime Service deliveries so you can receive your order in time.</p>
                </div>
            </div>
        </li>

        <li>
            <span class="toggle">
                <svg height="44px" width="44px">
                    <line y2="109.657" x2="288.374" y1="109.657" x1="272.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                    <line y2="21.39" x2="30.374" y1="21.39" x1="14.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                    <line y2="29.39" x2="22.374" y1="13.39" x1="22.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                </svg>
            </span>

            <p>HOW DO I CONTACT YOU REGARDING <span>...</span></p>

            <div class="answer_content">
                <span>MY ORDER?</span>

                <div><p>You can contact us at <a href="mailto:hello@yogasmoga.com">hello@yogasmoga.com</a> and we will
                        get right off the mat and get back to you.</p>
                </div>
            </div>
        </li>
        <li>
            <span class="toggle">
                <svg height="44px" width="44px">
                    <line y2="109.657" x2="288.374" y1="109.657" x1="272.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                    <line y2="21.39" x2="30.374" y1="21.39" x1="14.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                    <line y2="29.39" x2="22.374" y1="13.39" x1="22.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                </svg>
            </span>

            <p>HOW FAST ARE RETURNS OR<span>...</span></p>

            <div class="answer_content">
                <span> EXCHANGES PROCESSED?</span>

                <div><p>We process returns and exchanges as soon as they are received in our warehouse. If an exchange
                        is needed faster you can contact a fellow SMOGI at <a href="mailto:hello@yogasmoga.com">hello@yogasmoga.com</a>.
                    </p>
                </div>
            </div>
        </li>
        <li>
            <span class="toggle">
                <svg height="44px" width="44px">
                    <line y2="109.657" x2="288.374" y1="109.657" x1="272.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                    <line y2="21.39" x2="30.374" y1="21.39" x1="14.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                    <line y2="29.39" x2="22.374" y1="13.39" x1="22.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                </svg>
            </span>

            <p>HOW ARE INTERNATIONAL TAXES AND <span>...</span></p>

            <div class="answer_content">
                <span>DUTIES HANDLED?</span>

                <div><p>SMOGIs outside the United States of America are individually responsible for applicable taxes
                        and duties in their home jurisdictions. SMOGIs can contact the customs office in the destination
                        country for information about any applicable duties or taxes as they vary by country and by
                        individual orders.</p>
                </div>
            </div>
        </li>
    </ul>
</div>

<div class="help_page" id="size-chart">
    <p>SIZE CHARTS</p>
    <ul>
        <li>
            <span class="toggle">
                <svg height="44px" width="44px">
                    <line y2="109.657" x2="288.374" y1="109.657" x1="272.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                    <line y2="21.39" x2="30.374" y1="21.39" x1="14.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                    <line y2="29.39" x2="22.374" y1="13.39" x1="22.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                </svg>
            </span>

            <p>Women</p>

            <div class="answer_content" style="padding: 20px 0;">
                <div style="padding: 4px 0;">
                    <video width="100%" height="auto" controls="controls" style="top: 30%;"
                           src="/media/how_to_measure_video/HOW_TO_MEASURE.mp4"></video>
                </div>
                <div style="padding: 0 0 10px;">
                    <div class="size-chart">

                        <table width="100%" cellspacing="0" cellpadding="0" border="0" class="chart-table">

                            <tbody>
                            <tr>
                                <th>SIZE</th>
                                <th>BUST</th>
                                <th>WAIST</th>
                                <th>HIPS</th>


                            </tr>
                            <tr>

                                <td>2 / XXS</td>
                                <td>30"</td>
                                <td>22.5"</td>
                                <td>33"</td>

                            </tr>
                            <tr>

                                <td>4 / XS</td>
                                <td>32"</td>
                                <td>24.5"</td>
                                <td>35"</td>

                            </tr>
                            <tr>

                                <td>6 / S</td>
                                <td>34"</td>
                                <td>26.5"</td>
                                <td>37"</td>

                            </tr>
                            <tr>

                                <td>8 / M</td>
                                <td>36"</td>
                                <td>28.5"</td>
                                <td>39"</td>

                            </tr>
                            <tr>

                                <td>10 / L</td>
                                <td>38"</td>
                                <td>30.5"</td>
                                <td>41"</td>

                            </tr>
                            <tr>

                                <td>12 / XL</td>
                                <td>40"</td>
                                <td>32.5"</td>
                                <td>43"</td>

                            </tr>

                            <tr>

                                <td>14</td>
                                <td>42"</td>
                                <td>34.5"</td>
                                <td>45"</td>

                            </tr>

                            <tr>

                                <td>16</td>
                                <td>44"</td>
                                <td>36.5"</td>
                                <td>47"</td>

                            </tr>

                            <tr>

                                <td>18</td>
                                <td>46"</td>
                                <td>38.5"</td>
                                <td>49"</td>

                            </tr>


                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </li>
        <li>
            <span class="toggle">
                <svg height="44px" width="44px">
                    <line y2="109.657" x2="288.374" y1="109.657" x1="272.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                    <line y2="21.39" x2="30.374" y1="21.39" x1="14.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                    <line y2="29.39" x2="22.374" y1="13.39" x1="22.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                </svg>
            </span>

            <p>Men</p>

            <div class="answer_content" style="padding: 0;">

                <div>
                    <div class="size-chart" style="padding: 0 0 30px;">

                        <table width="100%" cellspacing="0" cellpadding="0" border="0" class="chart-table">

                            <tbody>
                            <tr>
                                <th>SIZE</th>
                                <th>CHEST</th>
                                <th>WAIST</th>
                            </tr>
                            <tr>

                                <td>S / 30-32</td>
                                <td>36"</td>
                                <td>29-31"</td>


                            </tr>
                            <tr>

                                <td>M / 34</td>
                                <td>39"</td>
                                <td>33"</td>


                            </tr>
                            <tr>

                                <td>L / 36</td>
                                <td>42"</td>
                                <td>35"</td>


                            </tr>
                            <tr>

                                <td>XL / 38</td>
                                <td>45"</td>
                                <td>37"</td>


                            </tr>
                            <tr>

                                <td>XXL / 40</td>
                                <td>48"</td>
                                <td>39"</td>


                            </tr>


                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </li>

    </ul>
</div>

<div class="help_page" id="product-care">
    <p>PRODUCT CARE</p>
    <ul>
        <li>
            <span class="toggle">
                <svg height="44px" width="44px">
                    <line y2="109.657" x2="288.374" y1="109.657" x1="272.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                    <line y2="21.39" x2="30.374" y1="21.39" x1="14.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                    <line y2="29.39" x2="22.374" y1="13.39" x1="22.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                </svg>
            </span>

            <p>1. DO NOT USE FABRIC SOFTENER</p>

            <div class="answer_content">
                <!--<span>CAME FROM ?</span>-->
                <div>
                    <p>Your YOGASMOGAs are highly technical performance wear. Our products are built
                        with nanotechnologies placed within the tiny pores between each weave. These nanotechnologies
                        are
                        constantly working to keep you dry and odor-free.</p>

                    <p>Most Fabric Softeners contain silicone that block the tiny pores in the fabric, thus severely
                        affecting the performance of your product.</p>
                </div>
            </div>
        </li>
        <li>
            <span class="toggle">
                <svg height="44px" width="44px">
                    <line y2="109.657" x2="288.374" y1="109.657" x1="272.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                    <line y2="21.39" x2="30.374" y1="21.39" x1="14.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                    <line y2="29.39" x2="22.374" y1="13.39" x1="22.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                </svg>
            </span>

            <p>2. DO NOT USE EXCESSIVE HEAT IN <span>...</span></p>

            <div class="answer_content">
                <span>WASHING AND DRYING</span>

                <div><p>The washing instructions for your YOGASMOGAs call for cold wash and hang dry or very gentle dry.
                        Excessive heat destroy the high performance fibers and will cause significant damage to your
                        product.</p></div>
            </div>
        </li>
        <li>
            <span class="toggle">
                <svg height="44px" width="44px">
                    <line y2="109.657" x2="288.374" y1="109.657" x1="272.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                    <line y2="21.39" x2="30.374" y1="21.39" x1="14.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                    <line y2="29.39" x2="22.374" y1="13.39" x1="22.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                </svg>
            </span>

            <p>3. WASH YOUR TECHNICAL PRODUCTS</p>

            <div class="answer_content">
                <span> TOGETHER</span>

                <div><p>Avoid washing your YOGASMOGAs with abrasive textiles such as denim, cotton or apparel that has
                        hardware, zippers, Velcro that can harm the performance of the fabric.</p></div>
            </div>
        </li>
        <li>
            <span class="toggle">
                <svg height="44px" width="44px">
                    <line y2="109.657" x2="288.374" y1="109.657" x1="272.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                    <line y2="21.39" x2="30.374" y1="21.39" x1="14.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                    <line y2="29.39" x2="22.374" y1="13.39" x1="22.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                </svg>
            </span>

            <p>4. COLORS THAT STAY TRUE TO YOU</p>

            <div class="answer_content">
                <!--  <span>CAME FROM ?</span>-->
                <div><p>Always remember to wash only like colors together, so they always stay bright and true to
                        you.</p></div>
            </div>
        </li>
    </ul>
</div>

<div class="help_page" id="email-us">
    <p>EMAIL US</p>

    <div style="padding: 20px 12px; font:15px/22px GraphikRegular;"> If you have any questions about our product, please email us at
        <a href="mailto:hello@yogasmoga.com" style="color: #AD8536;">hello@yogasmoga.com</a></div>
</div>

<script type="text/javascript">

    var type = window.location.hash.substr(1);
    jQuery(".sign-in-box .h1").html("HELP");
    jQuery(document).ready(function ($) {

        var questionPos = type.indexOf("?");
        if(questionPos>-1)
            type = type.substring(0,questionPos);

        if (type == "") {
            type = "faq";
        }
        $(".help_page").hide();
        $(".help_page#" + type).show();
    });
</script>