<div class="main-container">

    <!-- START OF PAGE ACCORDION -->

    <div class="help_page" id="faq">
        <div class="terms_condition">
            <p>TERMS &amp; CONDITIONS</p>
            <p>Effective date of current policy:<br/>January 1 2013</p>
        </div>
        <ul>
            <li>
                <span class="toggle"><img alt="arrow" src="<?php echo $this->getSkinUrl("images/black-arrw.png"); ?>" ></span>
                <p>1. WHERE DOES THE NAME YOGASMOGA<span>...</span></p>
                <div class="answer_content">
                    <span>CAME FROM ?</span>
                    <p>we spent significant time and bla bla bla...</p>
                </div>
            </li>
            <li>
                <span class="toggle"><img alt="arrow" src="<?php echo $this->getSkinUrl("images/black-arrw.png"); ?>" ></span>
                <p>1. WHERE DOES THE NAME YOGASMOGA<span>...</span></p>
                <div class="answer_content">
                    <span>CAME FROM ?</span>
                    <p>we spent significant time and bla bla bla...</p>
                </div>
            </li>
            <li>
                <span class="toggle"><img alt="arrow" src="<?php echo $this->getSkinUrl("images/black-arrw.png"); ?>" ></span>
                <p>1. WHERE DOES THE NAME YOGASMOGA<span>...</span></p>
                <div class="answer_content">
                    <span>CAME FROM ?</span>
                    <p>we spent significant time and bla bla bla...</p>
                </div>
            </li>
            <li>
                <span class="toggle"><img alt="arrow" src="<?php echo $this->getSkinUrl("images/black-arrw.png"); ?>" ></span>
                <p>1. WHERE DOES THE NAME YOGASMOGA<span>...</span></p>
                <div class="answer_content">
                    <span>CAME FROM ?</span>
                    <p>we spent significant time and bla bla bla...</p>
                </div>
            </li>
        </ul>
    </div>

    <!-- END OF PAGE ACCORDION -->
</div>
<script type="text/javascript">

    var type = window.location.hash.substr(1);
    jQuery(".custom-block .sign-in-box h1").html("TERMS");
    jQuery(".sign-in-box .arrow-icon").hide();

</script>