<!--Ys color tech code added by fahim-->
<ul>
<?php $collection = Mage::getModel('catalog/category')->getCollection()->addAttributeToSelect('*')->addAttributeToSort('position', 'ASC');
		foreach($collection as $category):
				if($category->getId()!=3 && $category->getId()!=5 && $category->getId()!=9 && $category->getId()!=43  && $category->getId()!=136  && $category->getId()!=137):
					if($category->getLevel()==2 && $category->getIsActive()):

						$url = $category->getUrl();
						$name = $category->getName();
						$colorString = trim($category->getYsColorTech());
						$arr = explode(',',$colorString);
						$bg = $arr[0];
						$textclr = $arr[1];
						$img = $arr[2];
						$borderClass ="";
							if(strtolower($bg) =="#fff" || strtolower($bg) =="#ffffff" || strtolower($bg) =="#fefefe"){
								$borderClass ="ys-color-white";
							}
						$collection = Mage::getModel('catalog/category')
							->load($category->getId())
							->getProductCollection()
							->addAttributeToFilter('type_id', 'simple')
							->addAttributeToFilter(
								'status',
								array('eq' => Mage_Catalog_Model_Product_Status::STATUS_ENABLED)
							)
							->addAttributeToSelect('*');
						$productCount = count($collection);
						?>
						<?php if($productCount > 0):?>

							<li count="<?=$productCount?>"> <a href="<?php echo $url; ?>" style="background: <?php echo $bg; ?>;color:<?php echo $textclr; ?>;">
									<?php if($category->getId()==119): ?>
										<?php echo $name;?>&trade;
									<?php else: ?>
										<?php echo $name;?>
									<?php endif; ?>
								</a>
							</li>
						<?php else: ?>
							<li> <a class="prevent-link" href="javascript:void(0)" style="background: <?php echo $bg; ?>;color:<?php echo $textclr; ?>;"><?php echo $name; ?></a></li>
						<?php endif; ?>
				<?php endif; ?>

			<?php endif; ?>
		<?php endforeach ?>
</ul>		