<div class="ys-bottom">


    <div class="account-nav l-align ys_static_page_dropdown" style="display: none;">
        <ul class="sub-nav">
            <li><a data-heading="YS FABRIC TECH" rel="tab1" href="/ys-fabric-tech">YS Fabric Tech</a></li>
            <li><a data-heading="YS COLOR TECH" rel="tab2" href="/ys-color-tech">YS Color Tech</a></li>
            <li><a data-heading="YS DESIGN ELEMENTS" rel="tab3" href="/design-elements">YS Design Elements</a></li>


        </ul>

    </div>
    <div class="clearfix"></div>
    <div class="ys-block">

        <!-- --------------------------------1st-box--------------------------- -->
      


        <!----------------------------------1st-box ends----------------------------->

        <!----------------------------------2nd-box----------------------------->

          <div class="page_block" id="tab3" rel="yogas_principles">
            <div class="block_thumbnail">
                <img src="<?php echo $this->getSkinUrl('images/febric-design-progressive.jpg'); ?>"
                     class="img-responsive"/>

                <div class="overlay-text">
<!--                    <p class="text">Learn More</p>-->
                </div>
            </div>
            <div style="display:block;" class="block_content has_slider">
                <p>We sweat the details. </p>

                <p>
                    Don't forget to breathe when you see our beautiful design features. Every detail matters. Every
                    stitch. Every Inch. Come; meet us at the corner of awesome and sexy.
                </p>

                <div class="flexslider">
                    <div class="slides">
                        <li>
                            <img src="<?php echo $this->getSkinUrl('images/gusset-progressive.jpg'); ?>"
                                 rel="design-block-1"
                                 class="img-responsive"/>
                        </li>
                        <li>
                            <img src="<?php echo $this->getSkinUrl('images/de-pocket-new-progressive.jpg'); ?>"
                                 rel="design-block-2"
                                 class="img-responsive"/>
                        </li>
                        <li>
                            <img src="<?php echo $this->getSkinUrl('images/de-waistband-new-progressive.jpg'); ?>"
                                 rel="design-block-3"
                                 class="img-responsive"/>
                        </li>
                        <li>
                            <img src="<?php echo $this->getSkinUrl('images/de-cut-new-progressive.jpg'); ?>"
                                 rel="design-block-4"
                                 class="img-responsive"/>
                        </li>
                        <li>
                            <img src="<?php echo $this->getSkinUrl('images/de-bra-new-progressive.jpg'); ?>"
                                 rel="design-block-5"
                                 class="img-responsive"/>
                        </li>
                        <li>
                            <img src="<?php echo $this->getSkinUrl('images/de-back-cut-new-progressive.jpg'); ?>"
                                 rel="design-block-6"
                                 class="img-responsive"/>
                        </li>
                    </div>
                </div>
                <div class="slide_related_content">
                    <div rel="design-block-1">
                        <p class="title">
                            THE YS GUSSET
                        </p>

                        <p>
                            Soft to the touch, our advanced YS Gusset is lined with soft, delicate & highly
                            breathable antimicrobial and moisture wicking Auro Mesh fabric that lets you feel
                            sexy all day long.
                        </p>
                    </div>
                    <div rel="design-block-2">
                        <p class="title">
                            UP-&-IN POCKET
                        </p>

                        <p>
                            Our secret pockets discretely hold your essentials, so all the attention stays on
                            your bottom.
                        </p>

                        <p>
                            This smooth, sleek pocket goes up & in, to keep you looking super sexy & slim.
                        </p>

                        <p>
                            Our slim pockets keep your essentials invisible to the naked eye, making your
                            beautiful shape very visible.
                        </p>
                    </div>
                    <div rel="design-block-3">
                        <p class="title">
                            SKINNY-NO MUFFIN <br/>WAISTBAND
                        </p>

                        <p>
                            A Waistband That Banishes Muffin Top. Our crafted waistband is designed to
                            highlight your curves while toning and hugging in your waist for a super-sexy fit.
                        </p>

                        <p>
                            Our skinny holds you in using high memory retention Lycra<sup>&reg;</sup> as opposed to bulky and
                            extra fabric.
                        </p>
                    </div>
                    <div rel="design-block-4">
                        <p class="title">
                            THE SLIMMIE CUT
                        </p>

                        <p>
                            The Slimmie Cut strategically cinches in your waist, strikes a slimming effect on
                            the thighs and HIGH-lighting your tush.
                        </p>
                    </div>
                    <div rel="design-block-5">
                        <p class="title">
                            SPORTS BRA KEY ZONE<br/> VENTS
                        </p>

                        <p>
                            Highly breathable Zari Mesh vents strategically placed to cool you down, so you look
                            hot.
                        </p>
                    </div>
                    <div rel="design-block-6">
                        <p class="title">
                            NO DIG-IN RACER BACK CUT
                        </p>

                        <p>
                            Our perfect racer back cut showcases your sexy shoulders and provides freedom of
                            movement. The straps are designed to sit at a specific angle so they don't dig
                            in.
                        </p>
                    </div>
                </div>

            </div>
        </div>

        <!----------------------------------2nd-box ends----------------------------->
        <!-- page block end -------------------------------------------------------------------------------------------->


       
    </div>


    <!--------------------------------------our-story-block ends here------------------------------------>

    <style>
        .inner-aurum li .innr-txt {
            font-family: AvantGarde-demi !important;
        }

        .upper-aurum li ul p {
            font-size: 14px !important;
            line-height: 20px !important;
        }

        .inner-aurum {
            clear: both;
        }

        .upper-aurum li:first-child {
            border-top: 1px solid rgba(0, 0, 0, 0.2) !important;
        }

        .inside-content .title {
            font: 24px/26px ITCAvantGardeStd-Bk !important;
            color: #434343 !important;
        }

        .textContainer .our-breath {
            position: relative;
        !important;
        }

        .flexslider.new-slider .slides li > a {
            padding: 0 10px 24px !important;
        }

        .inner-aurum li .innr-txt {
            display: inline-block;
            font-family: AvantGarde-demi !important;
            font-size: 12px !important;
            height: 44px !important;
            letter-spacing: 1px;
            line-height: 50px !important;
            text-transform: uppercase;
            vertical-align: top;
        }

        .txt-cnt .bottom-text {
            bottom: 4px;
            color: #fff;
            font-family: freighttextbook;
            font-size: 18px;
            left: 0;
            line-height: 22px;
            position: absolute;
            bottom: 15px;
            right: 0;
            text-transform: capitalize;
        }

        .txt-cnt .bottom-text span {
            color: #ff0000;
            position: relative;
            bottom: 0;
        }
    </style>

    <style>
        .page_block, .slide_related_content {
            float: left;
            width: 100%;
        }

        .block_thumbnail {
            position: relative;
            line-height: 0;
        }

        .overlay-text {
            bottom: 20px;
            color: #fff;
            font: 16px freighttextmedium;
            left: 0;
            letter-spacing: 1px;
            position: absolute;
            width: 100%;
        }

        .overlay-text .text::after {
            content: ">";
            color: #B8153E;
        }

        .block_content {
            padding: 14px 14px 30px;
            float: left;
            text-align: left;
            width: 100%;
            display: none;
        }

        .account-nav.l-align.ys_static_page_dropdown {
            display: none;
        }

        .slide_related_content > div {
            display: none;
            float: left;
            padding: 25px 0 20px;
            width: 100%;
            text-align: left;
        }

        .block_content p {
            font: 18px/1.65em freighttextbook;
            letter-spacing: normal;
            margin: 20px 0;
        }

        .slide_related_content > div address {
            font: 22px/28px freighttextbook;
            margin: 25px 0 20px;
        }

        .slide_related_content > div p.store_hours {
            font: 15px/22px GraphikRegular;
        }

        .slide_related_content > div p.store_hours span {
            font: 15px/22px Graphik-Semibold;
        }

        .block_content p.title {
            font: 19px/21px ITCAvantGardeStd-Bk;
            margin: 0;
            letter-spacing: 1px;
        }

        .block_content p.sub-title {
            font: 19px/21px freighttextbookitalic;
            margin: 0;
            letter-spacing: 1px;
        }

        .block_content p.sub-title-namaskar {
            font: 19px/21px freighttextbookitalic;
            letter-spacing: 1px;
        }
        .slide_related_content div:first-child {
            display: block;
        }

        .add_bracelet {
            background: #00b900;
            border: none;
            color: #fff;
            font: 16px ITCAvantGardeStd-Bk;
            height: 44px;
            margin: 10px 0 25px;
            letter-spacing: 1px;
            width: 100%;
        }

        .block_content > div > div p:last-child {
            margin-bottom: 0;
        }

        .block_content > div > div {
            padding-bottom: 0;
        }

        .block_thumbnail .close-icn {
            height: 44px;
            position: fixed;
            right: 0;
            top: 88px;
            width: 44px;
            display: none;
            z-index: 5;
        }
		.flex-direction-nav{display:block;}

    </style>
    <script type="text/javascript">
        jQuery(document).ready(function ($) {
            $(".sign-in-box h1").html("YS DESIGN ELEMENTS");
            $(".flexslider").flexslider({
                after: function (slider) {
                    slideContent(slider);
                }
            });


            var closebtnHtml = '<span class="close-icn" style="display:block;"><svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="44px" height="44px" viewBox="0 0 44 44" enable-background="new 0 0 44 44" xml:space="preserve"><g><rect fill="#555555" width="44" height="44"/><line fill="none" stroke="#FFFFFF" stroke-miterlimit="10" x1="14" y1="14" x2="30" y2="30"/><line fill="none" stroke="#FFFFFF" stroke-miterlimit="10" x1="30" y1="14" x2="14" y2="30"/></g></svg></span>';
            $(".page_block .block_thumbnail").append(closebtnHtml);
            $(".page_block .block_thumbnail .close-icn").bind("click", function (e) {
                window.location.href = '/';
            });

        });
        function slideContent(slider) {
            var current_slide = slider.currentSlide + 1;
            var rel_value = slider.find(".slides li:nth-child(" + current_slide + ") img").attr("rel");
            slider.next().children("div").hide();
            if (rel_value != undefined) {
                slider.next().children("div[rel=" + rel_value + "]").fadeIn();
                slider.next().css("min-height", slider.next().children("div[rel=" + rel_value + "]").height());
            }
        }


    </script>
