<div class="ys-bottom">
    <div class="account-nav l-align ys_static_page_dropdown">
        <ul class="sub-nav">
            <li><a href="/our-story" data-heading="YS STORY" rel="our_story">Our Story</a></li>
            <li><a href="/our-core-values" data-heading="YS CORE VALUES" rel="our_core_values">Our Core Values</a></li>
            <li><a href="/our-ethics" data-heading="YS ETHICS" rel="our_core_ethics">Our Ethics</a></li>

            <li><a href="/our-stores" data-heading="YS STORES" rel="our_stores">Our Stores</a></li>
            <li><a href="/made-in-usa" data-heading="MADE IN USA" rel="made_in_usa">Made in USA</a></li>
            <li><a href="/principles-of-yoga" data-heading="YOGA PRINCIPLES" rel="principles_of_yoga">Principles of
                    Yoga</a></li>
            <li><a href="/namaskar" data-heading="NAMASK&Aacute;R" rel="namaskar_foundation">NAMASK&Aacute;R
                    Foundation</a></li>
            <li><a href="/press" data-heading="PRESS" rel="press">Press</a></li>


        </ul>

    </div>

</div>




<div class="page_block" id="namaskar_foundation">
    <div class="block_thumbnail">
        <img src="<?php echo $this->getSkinUrl('images/namaskar-block.jpg'); ?>" class="img-responsive"/>

        <div class="overlay-text">
<!--            <p class="text">Learn More</p>-->
        </div>
    </div>
    <div class="block_content" style="padding-top: 30px; display: block;">
        <p class="title">
            GIVING IS A CORE VALUE <br/>OF YOGASMOGA
        </p>

        <p class="sub-title-namaskar">
            We have Created the NAMASK&Aacute;R Foundation because We Care
        </p>

        <p>
            We recognize that textile production is typically done in the most economically challenged locations of the
            world. It is our absolute obligation and duty to give back. We welcome you to join us on this journey.
        </p>

        <p class="sub-title-namaskar">
            Joining hands to make a change.
        </p>
        <img src="<?php echo $this->getSkinUrl('images/namaskar1.jpg'); ?>" class="img-responsive"
            />

        <p class="title">
            THE NAMASK&Aacute;R FOUNDATION
        </p>

        <p class="sub-title">
            Raising The Funds
        </p>

        <p>
            YOGASMOGA has coordinated the manufacture and sales of hand woven bracelets that are being made on handlooms
            in remote villages of the Himalayas.
        </p>

        <p>
            These hand woven bracelets are sold by YOGASMOGA for &dollar;10 and Net Proceeds of all sales will be
            donated to the NAMASK&Aacute;R Foundation.
        </p>
        <img src="<?php echo $this->getSkinUrl('images/namaskar2-progressive.jpg'); ?>" class="img-responsive"/>
        <button onclick="window.location='/women/accessories/namaskar-bracelets/namaskar-bracelet'"
                class="add_bracelet">ADD BRACELET TO BAG
        </button>
        <p class="title">
            THE NAMASK&Aacute;R FOUNDATION
        </p>

        <p class="sub-title">
            Making Change in The World
        </p>

        <p>
            The NAMASK&Aacute;R Foundation focuses its energies on three equally important causes.
        </p>
        <p style="padding: 15px; margin: 0"></p>
        <div class="flexslider">
            <div class="slides">
                <li>
                    <img src="<?php echo $this->getSkinUrl('images/namaskar-block2.jpg'); ?>" class="img-responsive"
                         rel="namaskar-block1"/>
                </li>
                <li>
                    <img src="<?php echo $this->getSkinUrl('images/namaskar-block-4.jpg'); ?>" class="img-responsive"
                         rel="namaskar-block2"/>
                </li>
                <li>
                    <img src="<?php echo $this->getSkinUrl('images/namaskar-block5.jpg'); ?>" class="img-responsive"
                         rel="namaskar-block3"/>
                </li>
            </div>
        </div>
        <div class="slide_related_content">
            <div rel="namaskar-block1">
                <p class="title">1. HEALTH</p>

                <p>
                    In our travels to the developing world we have realized that people (especially women) lack even a
                    basic level of health care.
                </p>

                <p>
                    The NAMASK&Aacute;R Foundation seeks to provide basic health initiatives, immunization, care and
                    education around early child birth so that each child born has an opportunity to a successful future
                    that they deserve.
                </p>
                <img src="<?php echo $this->getSkinUrl('images/namaskar6.jpg'); ?>" class="img-responsive"
                    />

                <p class="title">
                    NAMASK&Aacute;R&mdash;The Meaning
                </p>

                <p>
                    While many are familiar with the greeting&mdash;Namast&eacute;&mdash;fewer in the west are familiar
                    with the
                    traditional Indian greeting&mdash;NAMASK&Aacute;R. More respectful than Namast&eacute;, it is not
                    simply a
                    greeting but a profound philosophy of shunning arrogance and negating one&rsquo;s ego.
                </p>

                <p>
                    The gesture, NAMASK&Aacute;R, represents the belief that there is a divine spark within each of us
                    that is located in the heart chakra. This gesture is an acknowledgement of the soul in one&mdash;by the
                    soul in another.
                </p>

                <p>
                    We join our hands together to recognize each other&rsquo;s soul, aiming to connect and honor each other.
                </p>
                <img src="<?php echo $this->getSkinUrl('images/namaskar-block-3.jpg'); ?>" class="img-responsive"/>

                <p class="title">
                    SUPPORT NAMASK&Aacute;R
                </p>

                <p>
                    We bring the NAMASK&Aacute;R bracelet to you as a traditional symbol of the deep Yoga culture that
                    connects two people&mdash;our SMOGIs and the weavers of the Himalayas.
                </p>

                <p>
                    The weavers (mostly women) have lost much of their business to machine manufacturing and today we
                    give you an opportunity to connect directly with these hard working people so you can help them
                    attain the means they need to continue their craft, while you proudly wear a hand made (and
                    beautiful) NAMASK&Aacute;R bracelet.
                </p>

            </div>
            <div rel="namaskar-block2">
                <p class="title">2. EDUCATION</p>

                <p>
                    Education is the foundation of well-being.
                </p>

                <p>
                    The NAMASK&Aacute;R Foundation seeks to provide education that gives children and young adults a
                    chance to grow into productive, fulfilled adults. NAMASK&Aacute;R intends to develop education
                    programs, including work with existing education based charities.
                </p>
            </div>
            <div rel="namaskar-block3">
                <p class="title">3. MICROLENDING</p>

                <p>
                    The NAMASK&Aacute;R Foundation seeks to provide micro loans ($10 - $50) to individuals in developing
                    economies who have no access to banks. These micro loans provide an opportunity to individuals to
                    jump-start small cottage industries that over time generate income.
                </p>

                <p>
                    One of the very first micro lending projects that NAMASK&Aacute;R is working on is setting up
                    handlooms for women in the remote villages of the Himalayas so that these women can earn a living
                    producing NAMASK&Aacute;R bracelets.
                </p>
            </div>
        </div>

    </div>
</div>



<style>
    .page_block, .slide_related_content {
        float: left;
        width: 100%;
    }

    .block_thumbnail {
        position: relative;
        line-height: 0;
    }

    .overlay-text {
        bottom: 20px;
        color: #fff;
        font: 16px freighttextmedium;
        left: 0;
        letter-spacing: 1px;
        position: absolute;
        width: 100%;
    }

    .overlay-text .text::after {
        content: " >";
        color: #B8153E;
    }

    .block_content {
        padding: 14px 14px 30px;
        float: left;
        text-align: left;
        width: 100%;
        display: none;
    }

    .account-nav.l-align.ys_static_page_dropdown {
        display: none;
    }

    .slide_related_content > div {
        display: none;
        float: left;
        padding: 30px 0 20px;
        width: 100%;
        text-align: left;
    }

    .block_content p {
        font: 18px/1.65em freighttextbook;
        letter-spacing: normal;
        margin: 20px 0 0;
    }

    .slide_related_content > div address {
        font: 18px/1.65em freighttextbook;
        margin: 20px 0 20px;
    }

    .slide_related_content > div p.store_hours {
        font: 12px/18px GraphikRegular;
    }

    .slide_related_content > div p.store_hours span {
        font: 12px/18px Graphik-Semibold;
    }

    .block_content p.title {
        font: 19px/21px ITCAvantGardeStd-Bk;
        margin: 0;
        letter-spacing: 1px;
    }

    .block_content p.sub-title {
        font: 19px/21px freighttextbookitalic;
        margin: 0;
        letter-spacing: 1px;
    }

    .block_content p.sub-title-namaskar {
        font: 19px/21px freighttextbookitalic;
        letter-spacing: 1px;
    }

    .slide_related_content div:first-child {
        display: block;
    }

    .add_bracelet {
        background: #00b900;
        border: none;
        color: #fff;
        font: 14px/50px ITCAvantGardeStd-Bk;
        height: 44px;
        margin: 10px 0 25px;
        letter-spacing: 1px;
        width: 100%;
    }

    .block_content > div > div p:last-child {
        margin-bottom: 0;
    }

    .block_content > div > div {
        padding-bottom: 0;
    }

    .block_thumbnail .close-icn {
        height: 44px;
        position: fixed;
        right: 0;
        top: 88px;
        width: 44px;
        display: none;
        z-index: 5;
    }

    .block_content img {
        margin: 30px 0;
    }

    .flexslider img {
        margin: 0 !important;
    }
</style>
<script type="text/javascript">
    jQuery(document).ready(function ($) {
        $(".sign-in-box .h1").html("NAMASKAR");
        $(".flexslider").flexslider({
            after: function (slider) {
                slideContent(slider);
            }
        });


        var closebtnHtml = '<span class="close-icn" style="display:block;"><svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="44px" height="44px" viewBox="0 0 44 44" enable-background="new 0 0 44 44" xml:space="preserve"><g><rect fill="#555555" width="44" height="44"/><line fill="none" stroke="#FFFFFF" stroke-miterlimit="10" x1="14" y1="14" x2="30" y2="30"/><line fill="none" stroke="#FFFFFF" stroke-miterlimit="10" x1="30" y1="14" x2="14" y2="30"/></g></svg></span>';
        $(".page_block .block_thumbnail").append(closebtnHtml);
        $(".page_block .block_thumbnail .close-icn").bind("click", function (e) {
            window.location.href = '/';
        });

    });
    function slideContent(slider) {
        var current_slide = slider.currentSlide + 1;
        var rel_value = slider.find(".slides li:nth-child(" + current_slide + ") img").attr("rel");
        slider.next().children("div").hide();
        if(rel_value!= undefined){
            slider.next().children("div[rel=" + rel_value + "]").fadeIn();
            slider.next().css("min-height", slider.next().children("div[rel=" + rel_value + "]").height());
        }
    }


</script>
