<div class="ys-bottom">
    <div class="account-nav l-align ys_static_page_dropdown">
        <ul class="sub-nav">
            <li><a href="/our-story" data-heading="YS STORY" rel="our_story">Our Story</a></li>
            <li><a href="/our-core-values" data-heading="YS CORE VALUES" rel="our_core_values">Our Core Values</a></li>
            <li><a href="/our-ethics" data-heading="YS ETHICS" rel="our_core_ethics">Our Ethics</a></li>

            <li><a href="/our-stores" data-heading="YS STORES" rel="our_stores">Our Stores</a></li>
            <li><a href="/made-in-usa" data-heading="MADE IN USA" rel="made_in_usa">Made in USA</a></li>
            <li><a href="/principles-of-yoga" data-heading="YOGA PRINCIPLES" rel="principles_of_yoga">Principles of
                    Yoga</a></li>
            <li><a href="/namaskar" data-heading="NAMASK&aacute;R" rel="namaskar_foundation">NAMASK&aacute;R
                    Foundation</a></li>
            <li><a href="/press" data-heading="PRESS" rel="press">Press</a></li>


        </ul>

    </div>

</div>


<div class="page_block" rel="our_stores">
    <div class="block_thumbnail">
        <img src="<?php echo $this->getSkinUrl('images/our-stores.jpg'); ?>" class="img-responsive"/>

        <div class="overlay-text">
<!--            <p class="text">Learn More</p>-->
        </div>
    </div>
    <div style="display:block;" class="block_content has_slider">
        <div class="flexslider">
            <div class="slides">
                <li>
                    <img src="<?php echo Mage::getBaseUrl('media'); ?>wysiwyg/mobile/ourstores/townhouse.jpg" class="img-responsive"
                         rel="townhouse"/>
                </li>
                <li>
                    <img src="<?php echo Mage::getBaseUrl('media'); ?>wysiwyg/mobile/ourstores/brentwood.jpg" class="img-responsive"
                         rel="brentwood"/>
                </li>
                <li>
                    <img src="<?php echo Mage::getBaseUrl('media'); ?>wysiwyg/mobile/ourstores/beverly-hills.jpg" class="img-responsive"
                         rel="beverly-hills"/>
                </li>
               <!-- <li>
                    <img src="<?php echo Mage::getBaseUrl('media'); ?>wysiwyg/mobile/ourstores/la-jo-la-pop-up-progressive.jpg" class="img-responsive"
                         rel="la-jo-la-pop-up"/>
                </li>-->
                <li>
                    <img src="<?php echo Mage::getBaseUrl('media'); ?>wysiwyg/mobile/ourstores/fashion-island.jpg" class="img-responsive"
                         rel="new-port-beach"/>
                </li>
              
              
                <li>
                    <img src="<?php echo Mage::getBaseUrl('media'); ?>wysiwyg/mobile/ourstores/boston.jpg" class="img-responsive"
                         rel="prudent-center"/>
                </li>
				<li>
                    <img src="<?php echo Mage::getBaseUrl('media'); ?>wysiwyg/mobile/ourstores/malibu-ourstore.jpg" class="img-responsive"
                         rel="malibu"/>
                </li>
               
                <li>
                    <img src="<?php echo Mage::getBaseUrl('media'); ?>wysiwyg/mobile/ourstores/san-francisco-ourstore.jpg" class="img-responsive"
                         rel="san-francisco"/>
                </li>
                
                
				<li>
                    <img src="<?php echo Mage::getBaseUrl('media'); ?>wysiwyg/mobile/ourstores/la-jo-la-ca-holiday-progressive.jpg" class="img-responsive"
                         rel="la-jo-la-ca-holiday"/>
                </li>
				  <li>
                    <img src="<?php echo Mage::getBaseUrl('media'); ?>wysiwyg/mobile/ourstores/short-hills-new-jersy-progressive.jpg" class="img-responsive"
                         rel="short-hills-new-jersy"/>
                </li>
				  <li>
                    <img src="<?php echo Mage::getBaseUrl('media'); ?>wysiwyg/mobile/ourstores/westchester-progressive.jpg" class="img-responsive"
                         rel="westchester"/>
                </li>
				 <li>
                    <img src="<?php echo Mage::getBaseUrl('media'); ?>wysiwyg/mobile/ourstores/corte-madera-progressive.jpg" class="img-responsive"
                         rel="corte-madera"/>
                </li>
                <li>
                    <img src="<?php echo Mage::getBaseUrl('media'); ?>wysiwyg/mobile/ourstores/walnut-creek-progressive.jpg" class="img-responsive"
                         rel="walnut-creek"/>
                </li>
            </div>
        </div>
        <div class="slide_related_content">
            <div rel="townhouse">
                <p class="title">YOGASMOGA TOWNHOUSE</p>

                <div>
                    <address>
                        68 Greenwich Ave<br/>
                        Greenwich, CT 06830<br/>
                        <a href="mailto:greenwich@yogasmoga.com">greenwich@yogasmoga.com</a><br/>
                        <a href="tel:2038619642">203 861 YOGA (9642)</a>
                    </address>
                </div>

                <p class="store_hours">
                    <span>Store Hours</span><br/>
                    Monday&ndash;Saturday 10am&ndash;6pm<br/>
                   Sunday 11am&ndash;6pm
                </p>
            </div>
            <div rel="brentwood">
                <p class="title">YOGASMOGA BRENTWOOD</p>

                <div>
                    <address>
                        11911 San Vincent Blvd <br/>
                        Brentwood, CA 90049 <br/>
                        <a href="mailto:brentwood@yogasmoga.com">brentwood@yogasmoga.com</a><br/>
                        <a href="tel:3104719642">310 471 YOGA (9642)</a>
                    </address>
                </div>

                <p class="store_hours">
                    <span>Store Hours</span><br/>
                    Monday&ndash;Saturday 10am&ndash;8pm<br/>
                    Sunday 10am&ndash;7pm
                </p>
            </div>
            <div rel="beverly-hills">
                <p class="title">YOGASMOGA BEVERLY HILLS</p>

                <div>
                    <address>
                        9458 Dayton Way<br/>
                        Beverly Hills, CA 90210<br/>
                        <a href="mailto:beverlyhills@yogasmoga.com">beverlyhills@yogasmoga.com</a><br/>
                        <a href="tel:3102739642">310 273 YOGA (9642)</a>
                    </address>
                </div>

                <p class="store_hours">
                    <span>Store Hours</span><br/>
                    Monday&ndash;Saturday 11am&ndash;7pm<br/>
                    Sunday 11am&ndash;6pm
                </p>
            </div>
            <!--
			<div rel="la-jo-la-pop-up">
                <p class="title">YOGASMOGA <br/>LA JOLLA POP-UP<br/>(UNTIL 11.18)</p>

                <div>
                    <address>
                        7863 Girard Ave, #101<br/>
                        La Jolla, CA 92037<br/>
                        <a href="mailto:lajolla@yogasmoga.com">lajolla@yogasmoga.com</a>
                    </address>
                </div>

                <p class="store_hours">
                    <span>Store Hours</span><br/>
                    Monday&ndash;Saturday 10am&ndash;7pm<br/>
                    Sunday 10am&ndash;6pm
                </p>
            </div>-->
            <div rel="new-port-beach">
                <p class="title">YOGASMOGA NEWPORT BEACH AT FASHION ISLAND</p>

                <div>
                    <address>
                        1119 Newport Center Drive<br/>
                        Newport Beach, CA 92660<br/>
                        <a href="mailto:fashionisland@yogasmoga.com">fashionisland@yogasmoga.com</a><br/>
                        <a href="tel:9497219642">949 721 YOGA (9642)</a>
                    </address>
                </div>

                <p class="store_hours">
                    <span>Store Hours</span><br/>
                    Monday&ndash;Friday 10am&ndash;9pm<br/>
                    Saturday 10am&ndash;7pm<br/>
                    Sunday 11am&ndash;6pm
                </p>
            </div>
           
           
            <div rel="prudent-center">
                <p class="title">YOGASMOGA X &ldquo;THE PRU&rdquo;</p>

                <div>
                    <address>
                        800 Boylston Street<br/>
                        Boston, MA 02199<br/>
                        <a href="mailto:boston.pru@yogasmoga.com">boston.pru@yogasmoga.com</a><br/>
                        <a href="tel:8889909642">888 990 YOGA (9642)</a>
                    </address>
                </div>
                <p class="store_hours">
                    <span>Store Hours</span><br/>
                    Monday&ndash;Saturday 10am&ndash;9pm<br/>
                    Sunday 11am&ndash;8pm
                </p>
            </div>

           
          
            <div rel="malibu">
                <p class="title">YOGASMOGA X MALIBU COUNTRY MART</p>

                <div>
                    <address>
                        3900 Cross Creek Rd<br/>
                        Malibu, CA 90265<br/>
                        <a href="mailto:malibu@yogasmoga.com">malibu@yogasmoga.com</a><br/>
                        <a href="tel:8889909642">888 990 YOGA (9642)</a>
                    </address>
                </div>
                <p class="store_hours">
                    <span>Store Hours</span><br/>
                    Monday&ndash;Saturday 10am&ndash;7pm<br/>
                    Sunday 10am&ndash;6pm
                </p>
            </div>
			 <div rel="san-francisco">
                <p class="title">YOGASMOGA <br/>SAN FRANCISCO</p>

                <div>
                    <address>
                        66 Kearny St<br/>
                        San Francisco, CA 94108<br/>
                        <a style="font-size: 18px;" href="mailto:sanfran.unionsquare@yogasmoga.com">sanfran.unionsquare@yogasmoga.com</a><br/>
                        <a href="tel:8889909642">888 990 YOGA (9642)</a>
                    </address>
                </div>
                <p class="store_hours">
                    <span>Store Hours</span><br/>
                    Monday–Saturday 10am&ndash;8pm<br/>
                        Sunday 11am&ndash;7pm
                </p>
            </div>
			  <div rel="la-jo-la-ca-holiday">
                <p class="title">YOGASMOGA X LA PLAZA LA JOLLA</p>

                <div>
                    <address>
                        7863 Girard Ave<br/>
                        La Jolla, CA 92037<br/>
                        <a href="mailto:lajolla@yogasmoga.com">lajolla@yogasmoga.com</a><br/>
                        <a href="tel:8889909642">888 990 YOGA (9642)</a>
                    </address>
                </div>
                <p class="store_hours">
                    <span>Store Hours</span><br/>
                    Monday&ndash;Saturday 10am&ndash;7pm<br/>
                    Sunday 10am&ndash;6pm
                </p>
            </div>
			 <div rel="short-hills-new-jersy">
                <p class="title">YOGASMOGA X THE MALL <br/>AT SHORT HILLS</p>

                <div>
                    <address>
                        1200 Morris Turnpike<br/>
                        Short Hills, NJ 07078<br/>
                        <a href="mailto:shorthills@yogasmoga.com">shorthills@yogasmoga.com</a><br/>
                        <a href="tel:8889909642">888 990 YOGA (9642)</a>
                    </address>
                </div>

                <p class="store_hours">
                    <span>Store Hours</span><br/>
                    Monday&ndash;Saturday 10am&ndash;9pm<br/>
                    Sunday 11am&ndash;6pm
                </p>
            </div>
			 <div rel="westchester">
                <p class="title">YOGASMOGA <br/>X THE WESTCHESTER</p>

                <div>
                    <address>
                        125 Westchester Ave<br/>
                        White Plains, NY 10601<br/>
                        <a href="mailto:westchester@yogasmoga.com">westchester@yogasmoga.com</a><br/>
                        <a href="tel:8889909642">888 990 YOGA (9642)</a>
                    </address>
                </div>

                <p class="store_hours">
                    <span>Store Hours</span><br/>
                    Monday&ndash;Saturday 10am&ndash;9pm<br/>
                    Sunday 11am&ndash;7pm
                </p>
            </div>
			            <div rel="corte-madera">
                <p class="title">YOGASMOGA X THE VILLAGE AT CORTE MADERA</p>

                <div>
                    <address>
                        1618 Redwood Hwy<br/>
                        Corte Madera, CA 94925<br/>
                        <a href="mailto:cortemadera@yogasmoga.com">cortemadera@yogasmoga.com</a><br/>
                        <a href="tel:8889909642">888 990 YOGA (9642)</a>
                    </address>
                </div>
                <p class="store_hours">
                    <span>Store Hours</span><br/>
                    Monday&ndash;Friday 10am&ndash;8pm<br/>
                    Saturday 10am&ndash;7pm<br/>
                    Sunday 11am&ndash;6pm
                </p>
            </div>
            <div rel="walnut-creek">
                <p class="title">YOGASMOGA X WALNUT CREEK AT BROADWAY PLAZA</p>

                <div>
                    <address>
                        1275 Broadway Plaza<br/>
                        Walnut Creek, CA 94596<br/>
                        <a href="mailto:walnutcreek@yogasmoga.com">walnutcreek@yogasmoga.com</a><br/>
                        <a href="tel:8889909642">888 990 YOGA (9642)</a>
                    </address>
                </div>
                <p class="store_hours">
                    <span>Store Hours</span><br/>
                    Monday&ndash;Friday 10am&ndash;9pm<br/>
                    Saturday 10am&ndash;7pm<br/>
                    Sunday 11am&ndash;6pm
                </p>
            </div>
        </div>
    </div>
</div>

<style>
    .page_block, .slide_related_content {
        float: left;
        width: 100%;
    }

    .block_thumbnail {
        position: relative;
        line-height: 0;
    }

    .overlay-text {
        bottom: 20px;
        color: #fff;
        font: 16px freighttextmedium;
        left: 0;
        letter-spacing: 1px;
        position: absolute;
        width: 100%;
    }

    .overlay-text .text::after {
        content: ">";
        color: #B8153E;
    }

    .block_content {
        padding: 14px 14px 30px;
        float: left;
        text-align: left;
        width: 100%;
        display: none;
    }

    .account-nav.l-align.ys_static_page_dropdown {
        display: none;
    }

    .slide_related_content > div {
        display: none;
        float: left;
        padding: 30px 0 20px;
        width: 100%;
        text-align: left;
    }

    .block_content p {
        font: 18px/1.65em freighttextbook;
        letter-spacing: normal;
        margin: 20px 0 0;
    }

    .slide_related_content > div address {
        font: 18px/1.65em freighttextbook;
        margin: 20px 0 20px;
    }

    .slide_related_content > div p.store_hours {
        font: 12px/18px GraphikRegular;
    }

    .slide_related_content > div p.store_hours span {
        font: 12px/18px Graphik-Semibold;
    }

    .block_content p.title {
        font: 19px/21px ITCAvantGardeStd-Bk;
        margin: 0;
        letter-spacing: 1px;
    }

    .block_content p.sub-title {
        font: 19px/21px freighttextbookitalic;
        margin: 0;
        letter-spacing: 1px;
    }

    .block_content p.sub-title-namaskar {
        font: 19px/21px freighttextbookitalic;
        letter-spacing: 1px;
    }

    .slide_related_content div:first-child {
        display: block;
    }

    .add_bracelet {
        background: #00b900;
        border: none;
        color: #fff;
        font: 14px ITCAvantGardeStd-Bk;
        height: 44px;
        margin: 10px 0 25px;
        letter-spacing: 1px;
        width: 100%;
    }

    .block_content > div > div p:last-child {
        margin-bottom: 0;
    }

    .block_content > div > div {
        padding-bottom: 0;
    }

    .block_thumbnail .close-icn {
        height: 44px;
        position: fixed;
        right: 0;
        top: 88px;
        width: 44px;
        display: none;
        z-index: 5;
    }

    .block_content img {
        margin: 30px 0;
    }

    .flexslider img {
        margin: 0 !important;
    }
</style>
<script type="text/javascript">
    jQuery(document).ready(function ($) {
        $(".sign-in-box h1").html("OUR STORES");
        $(".flexslider").flexslider({
            after: function (slider) {
                slideContent(slider);
            }
        });


        var closebtnHtml = '<span class="close-icn" style="display:block;"><svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="44px" height="44px" viewBox="0 0 44 44" enable-background="new 0 0 44 44" xml:space="preserve"><g><rect fill="#555555" width="44" height="44"/><line fill="none" stroke="#FFFFFF" stroke-miterlimit="10" x1="14" y1="14" x2="30" y2="30"/><line fill="none" stroke="#FFFFFF" stroke-miterlimit="10" x1="30" y1="14" x2="14" y2="30"/></g></svg></span>';
        $(".page_block .block_thumbnail").append(closebtnHtml);
        $(".page_block .block_thumbnail .close-icn").bind("click", function (e) {
            window.location.href = '/';
        });

    });
    function slideContent(slider) {
        var current_slide = slider.currentSlide + 1;
        var rel_value = slider.find(".slides li:nth-child(" + current_slide + ") img").attr("rel");
        slider.next().children("div").hide();
        if(rel_value!= undefined){
            slider.next().children("div[rel=" + rel_value + "]").fadeIn();
            slider.next().css("min-height", slider.next().children("div[rel=" + rel_value + "]").height());
        }
    }


</script>
