<div class="ys-bottom">
    <div class="account-nav l-align ys_static_page_dropdown">
        <ul class="sub-nav">
            <li><a href="/our-story" data-heading="YS STORY" rel="our_story">Our Story</a></li>
            <li><a href="/our-core-values" data-heading="YS CORE VALUES" rel="our_core_values">Our Core Values</a></li>
            <li><a href="/our-ethics" data-heading="YS ETHICS" rel="our_core_ethics">Our Ethics</a></li>

            
            <li><a href="/made-in-usa" data-heading="MADE IN USA" rel="made_in_usa">Made in USA</a></li>
            <li><a href="/principles-of-yoga" data-heading="YOGA PRINCIPLES" rel="principles_of_yoga">Principles of
                    Yoga</a></li>
            <li><a href="/namaskar" data-heading="NAMASK&aacute;R" rel="namaskar_foundation">NAMASK&aacute;R
                    Foundation</a></li>
            <li><a href="/press" data-heading="PRESS" rel="press">Press</a></li>


        </ul>

    </div>

</div>




<div  class="page_block" rel="our_core_values">
    <div class="block_thumbnail">
        <img src="<?php echo $this->getSkinUrl('images/our-core-values.jpg'); ?>" class="img-responsive"/>

        <div class="overlay-text">
<!--            <p class="text">Learn More</p>-->
        </div>
    </div>
    <div style="display:block"  class="block_content has_slider">
        <div class="flexslider">
            <div class="slides">
                <li>
                    <img src="<?php echo $this->getSkinUrl('images/our-core-values1.jpg'); ?>" class="img-responsive"
                         rel="our-core-values-block1"/>
                </li>
                <li>
                    <img src="<?php echo $this->getSkinUrl('images/our-core-values2.jpg'); ?>" class="img-responsive"
                         rel="our-core-values-block2"/>
                </li>
                <li>
                    <img src="<?php echo $this->getSkinUrl('images/our-core-values3.jpg'); ?>" class="img-responsive"
                         rel="our-core-values-block3"/>
                </li>
                <li>
                    <img src="<?php echo $this->getSkinUrl('images/our-core-values4.jpg'); ?>" class="img-responsive"
                         rel="our-core-values-block4"/>
                </li>
                <li>
                    <img src="<?php echo $this->getSkinUrl('images/our-core-values5.jpg'); ?>" class="img-responsive"
                         rel="our-core-values-block5"/>
                </li>
                <li>
                    <img src="<?php echo $this->getSkinUrl('images/our-core-values6.jpg'); ?>" class="img-responsive"
                         rel="our-core-values-block6"/>
                </li>
                <li>
                    <img src="<?php echo $this->getSkinUrl('images/our-core-values7.jpg'); ?>" class="img-responsive"
                         rel="our-core-values-block7"/>
                </li>
            </div>
        </div>
        <div  class="slide_related_content">
            <div rel="our-core-values-block1">
                <p class="title">DEEP, DIRECT AND LASTING <br/>CONNECTIONS</p>

                <p>
                    We put in great love, care and devotion to create products that will delight our SMOGI&rsquo;s (that&rsquo;s you
                    and all of our YOGASMOGA community). We aim to touch the daily lives of our SMOGI&rsquo;s, building deep
                    connections and long-lasting bonds.
                </p>
            </div>
            <div rel="our-core-values-block2">
                <p class="title">A RESPONSIBILITY BASED <br/>REPUTATION</p>

                <p>
                    We strive to earn the respect of our SMOGI&rsquo;s by constantly delivering at a superior level with
                    everything we do. We know this respect is earned through action and over a long period of time. We
                    take this responsibility seriously. We make real things for life and at times mistakes will happen.
                    Our promise is to rectify any mistake immediately and proactively.
                </p>
            </div>
            <div rel="our-core-values-block3">
                <p class="title">A MANTRA OF INNOVATION</p>

                <p>
                    We are committed to using the most innovative and pioneering techniques to develop our fabric
                    technology. Our unyielding commitment to using the best technologies is more than a best practice
                    for us, it&rsquo;s our mantra&mdash;an everyday practice that yields far superior products for our
                    SMOGI&rsquo;s.
                </p>
            </div>
            <div rel="our-core-values-block4">
                <p class="title">A CORE OF AUTHENTICITY</p>

                <p>
                    While we labor to work with the most technologically advanced fabrics and manufacturing techniques,
                    we pursue a relentless focus on the deep-rooted traditions of Yoga . We strive to apply the
                    principles, practice and spirit of Yoga to everything we do, and everything we create. We hope this
                    will bring Yoga to life in new and meaningful ways.
                </p>
            </div>
            <div rel="our-core-values-block5">
                <p class="title">COLLABORATION <br/>AS CULTURE</p>

                <p>
                    We inspire our people to be creative through constant collaboration. This drives us to deliver the
                    very best, for everyone. Our people take pride in the work we do together.
                </p>
            </div>
            <div rel="our-core-values-block6">
                <p class="title">EAT, SLEEP & BREATHE <br/>THE DETAILS</p>

                <p>
                    We have an uncompromising determination to achieve excellence in everything we undertake&mdash;one
                    breath
                    at a time. We believe that if we pay keen attention to the smallest details and strive for
                    ever-present awareness in our everyday actions, the results will show.
                </p>
            </div>
            <div rel="our-core-values-block7">
                <p class="title">THE GIFT OF NAMASK&Aacute;R</p>

                <p>
                    We recognize that textile production is typically done in the most challenged economic locations in
                    the world and we feel it is our absolute obligation and duty to give back to those who have joined
                    us on this journey. Which is why we have created the NAMASK&Aacute;R Foundation.
                </p>
            </div>
        </div>

    </div>
</div>


<!-- page block end -------------------------------------------------------------------------------------------->




<!-- page block end -------------------------------------------------------------------------------------------->

<style>
    .page_block, .slide_related_content {
        float: left;
        width: 100%;
    }

    .block_thumbnail {
        position: relative;
        line-height: 0;
    }

    .overlay-text {
        bottom: 20px;
        color: #fff;
        font: 16px freighttextmedium;
        left: 0;
        letter-spacing: 1px;
        position: absolute;
        width: 100%;
    }

    .overlay-text .text::after {
        content: " >";
        color: #B8153E;
    }

    .block_content {
        padding: 14px 14px 30px;
        float: left;
        text-align: left;
        width: 100%;
        display: none;
    }

    .account-nav.l-align.ys_static_page_dropdown {
        display: none;
    }

    .slide_related_content > div {
        display: none;
        float: left;
        padding: 30px 0 20px;
        width: 100%;
        text-align: left;
    }

    .block_content p {
        font: 18px/1.65em freighttextbook;
        letter-spacing: normal;
        margin: 20px 0 0;
    }

    .slide_related_content > div address {
        font: 18px/1.65em freighttextbook;
        margin: 20px 0 20px;
    }

    .slide_related_content > div p.store_hours {
        font: 12px/18px GraphikRegular;
    }

    .slide_related_content > div p.store_hours span {
        font: 12px/18px Graphik-Semibold;
    }

    .block_content p.title {
        font: 19px/21px ITCAvantGardeStd-Bk;
        margin: 0;
        letter-spacing: 1px;
    }

    .block_content p.sub-title {
        font: 19px/21px freighttextbookitalic;
        margin: 0;
        letter-spacing: 1px;
    }

    .block_content p.sub-title-namaskar {
        font: 19px/21px freighttextbookitalic;
        letter-spacing: 1px;
    }

    .slide_related_content div:first-child {
        display: block;
    }

    .add_bracelet {
        background: #00b900;
        border: none;
        color: #fff;
        font: 14px ITCAvantGardeStd-Bk;
        height: 44px;
        margin: 10px 0 25px;
        letter-spacing: 1px;
        width: 100%;
    }

    .block_content > div > div p:last-child {
        margin-bottom: 0;
    }

    .block_content > div > div {
        padding-bottom: 0;
    }

    .block_thumbnail .close-icn {
        height: 44px;
        position: fixed;
        right: 0;
        top: 88px;
        width: 44px;
        display: none;
        z-index: 5;
    }

    .block_content img {
        margin: 30px 0;
    }

    .flexslider img {
        margin: 0 !important;
    }
</style>
<script type="text/javascript">
    jQuery(document).ready(function ($) {
        $(".sign-in-box .h1").html("OUR CORE VALUES");
        $(".flexslider").flexslider({
            after: function (slider) {
                slideContent(slider);
            }
        });


        var closebtnHtml = '<span class="close-icn" style="display:block;"><svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="44px" height="44px" viewBox="0 0 44 44" enable-background="new 0 0 44 44" xml:space="preserve"><g><rect fill="#555555" width="44" height="44"/><line fill="none" stroke="#FFFFFF" stroke-miterlimit="10" x1="14" y1="14" x2="30" y2="30"/><line fill="none" stroke="#FFFFFF" stroke-miterlimit="10" x1="30" y1="14" x2="14" y2="30"/></g></svg></span>';
        $(".page_block .block_thumbnail").append(closebtnHtml);
        $(".page_block .block_thumbnail .close-icn").bind("click", function (e) {
            window.location.href = '/';
        });

    });
    function slideContent(slider) {
        var current_slide = slider.currentSlide + 1;
        var rel_value = slider.find(".slides li:nth-child(" + current_slide + ") img").attr("rel");
        slider.next().children("div").hide();
        if(rel_value!= undefined){
            slider.next().children("div[rel=" + rel_value + "]").fadeIn();
            slider.next().css("min-height", slider.next().children("div[rel=" + rel_value + "]").height());
        }
    }


</script>
