<div class="ys-bottom">
    <div class="account-nav l-align ys_static_page_dropdown">
        <ul class="sub-nav">
            <li><a href="/our-story" data-heading="YS STORY" rel="our_story">Our Story</a></li>
            <li><a href="/our-core-values" data-heading="YS CORE VALUES" rel="our_core_values">Our Core Values</a></li>
            <li><a href="/our-ethics" data-heading="YS ETHICS" rel="our_core_ethics">Our Ethics</a></li>

            <!--<li><a href="/our-stores" data-heading="YS STORES" rel="our_stores">Our Stores</a></li>-->
            <li><a href="/made-in-usa" data-heading="MADE IN USA" rel="made_in_usa">Made in USA</a></li>
            <li><a href="/principles-of-yoga" data-heading="YOGA PRINCIPLES" rel="principles_of_yoga">Principles of
                    Yoga</a></li>
            <li><a href="/namaskar" data-heading="NAMASK&aacute;R" rel="namaskar_foundation">NAMASK&aacute;R
                    Foundation</a></li>
            <li><a href="/press" data-heading="PRESS" rel="press">Press</a></li>


        </ul>

    </div>

</div>







<div class="page_block" rel="our_ethics">
    <div class="block_thumbnail">
        <img src="<?php echo $this->getSkinUrl('images/our-ethics.jpg'); ?>" class="img-responsive"/>

        <div class="overlay-text">
<!--            <p class="text">Learn More</p>-->
        </div>
    </div>
    <div style="display:block" class="block_content has_slider">
        <div class="flexslider">
            <div class="slides">
                <li>
                    <img src="<?php echo $this->getSkinUrl('images/our-ethics1.jpg'); ?>" class="img-responsive"
                         rel="our-ethics-block1"/>
                </li>
                <li>
                    <img src="<?php echo $this->getSkinUrl('images/our-ethics2.jpg'); ?>" class="img-responsive"
                         rel="our-ethics-block2"/>
                </li>
                <li>
                    <img src="<?php echo $this->getSkinUrl('images/our-ethics3.jpg'); ?>" class="img-responsive"
                         rel="our-ethics-block3"/>
                </li>
                <li>
                    <img src="<?php echo $this->getSkinUrl('images/our-ethics4.jpg'); ?>" class="img-responsive"
                         rel="our-ethics-block4"/>
                </li>
                <li>
                    <img src="<?php echo $this->getSkinUrl('images/our-ethics5.jpg'); ?>" class="img-responsive"
                         rel="our-ethics-block5"/>
                </li>
            </div>
        </div>
        <div class="slide_related_content">
            <div rel="our-ethics-block1">
                <p class="title">PRESERVE THE ENVIRONMENT</p>

                <p>
                    We believe that if we don&rsquo;t take good care of our world, it may fast disappear. We have a
                    responsibility to our planet.
                </p>

                <p>
                    Fabric dyeing processes inherently use chemicals to develop dye pigments. We do not use any harmful
                    formaldehyde based dyes that can destroy our groundwater.
                </p>

                <p>
                    We have developed a dyeing process that is as efficient and eco-friendly as possible. We use the
                    most advanced computerized color matching and dyeing apparatus and high performance dye-jets. The
                    dye-jets are custom programmed to use exact amount of pigmentation so that residual water after the
                    dyeing is clear and run off can be released without adding harmful chemicals.
                </p>

                <p>
                    Unlike many companies who have their dyeing facilities located in China, our dye-lab is located in
                    the USA, in a geographical area with the toughest environmental and pollution standards. We are very
                    proud to have developed processes that meet and exceed these strict environmental regulations.
                </p>
            </div>
            <div rel="our-ethics-block2">
                <p class="title">CONTRIBUTE TO REDUCING THE CARBON FOOTPRINT</p>

                <p>Significant work has been done to solve for and create a supply chain as close to YOGASMOGA HQ (New York City) as possible.</p>
				<p>We do not produce any cut & sow garments in China and do not ship goods 12,500 miles across the globe &mdash; this reduces our fossil fuel usage dramatically. While we can make cheap clothing in China, we have made the conscious decision not to do so. We manufacture our clothing as close to home as possible with goods travelling 1/4th the distance as compared to our competitors, dramatically reducing our carbon footprint.</p>
            </div>
            <div rel="our-ethics-block3">
                <p class="title">RESPONSIBLE PRODUCTION</p>

                <p>
                    YOGASMOGA has a very vigorous selection process of production partners. We work only with the best
                    manufacturers who have demonstrated a commitment to adhere to the highest ethical standards.
                </p>

                <p>
                    We conduct regular audits of our partner factories.
                </p>

                <p>
                    Our production facilities have been awarded the Platinum Certificate of Compliance from WRAP
                    (Worldwide Responsible Accredited Production). Our facilities are also participating suppliers of
                    the Fair Labor Association. (Just in case you were wondering&mdash;Yes its kind of a big deal to
                    achieve these certifications)
                </p>

                <p>
                    Our production facilities have an extensive green environment program including recycling, energy
                    saving production measures, use of clean fuels like LPG&rsquo;s, reforestation and use of biodegradable
                    chemicals.
                </p>
            </div>
            <div rel="our-ethics-block4">
                <p class="title">ACCURATE REPRESENTATION OF VISUAL IMAGES</p>

                <p>
                    As a rule, YOGASMOGA does not allow any body retouching in our photography. All photographers have
                    to commit to this rule. No exceptions.
                </p>

                <p>
                    We make an extraordinary effort to work with teachers and everyday practitioners of yoga for visual
                    representation of our products.
                </p>
            </div>
            <div rel="our-ethics-block5">
                <p class="title">ACCOUNTABILITY FOR EACH COMPONENT IN THE SUPPLY CHAIN</p>

                <p>
                    YOGASMOGA is committed to owning every piece of the supply chain. We assume responsibility for every
                    step in the production process from sourcing fiber to bringing you the finished apparel. We research
                    & develop it, we manufacture it, we dye it, we cut it, we stitch it, we pack it, we ship it&mdash;
                    why?&mdash;so you can proudly enjoy it.
                </p>

                <p>
                    We require a Manufacturer&rsquo;s Affidavit of Origin on all yarns that we purchase, ensuring adherence to
                    the highest quality yarns. We strongly believe that sourcing the best raw materials available to us
                    results in the best performing products. Life is sometimes as simple as the choices you make.
                </p>

                <p>
                    We work directly with all our suppliers even for the smallest components such as trims, labels and
                    threads that make up the product. We believe that sub contracting even these smaller items can and
                    will compromise quality. We look closer and go deeper to deliver the very best to you.
                </p>
            </div>
        </div>

    </div>
</div>

<style>
    .page_block, .slide_related_content {
        float: left;
        width: 100%;
    }

    .block_thumbnail {
        position: relative;
        line-height: 0;
    }

    .overlay-text {
        bottom: 20px;
        color: #fff;
        font: 16px freighttextmedium;
        left: 0;
        letter-spacing: 1px;
        position: absolute;
        width: 100%;
    }

    .overlay-text .text::after {
        content: ">";
        color: #B8153E;
    }

    .block_content {
        padding: 14px 14px 30px;
        float: left;
        text-align: left;
        width: 100%;
        display: none;
    }

    .account-nav.l-align.ys_static_page_dropdown {
        display: none;
    }

    .slide_related_content > div {
        display: none;
        float: left;
        padding: 30px 0 20px;
        width: 100%;
        text-align: left;
    }

    .block_content p {
        font: 18px/1.65em freighttextbook;
        letter-spacing: normal;
        margin: 20px 0 0;
    }

    .slide_related_content > div address {
        font: 18px/1.65em freighttextbook;
        margin: 20px 0 20px;
    }

    .slide_related_content > div p.store_hours {
        font: 12px/18px GraphikRegular;
    }

    .slide_related_content > div p.store_hours span {
        font: 12px/18px Graphik-Semibold;
    }

    .block_content p.title {
        font: 19px/21px ITCAvantGardeStd-Bk;
        margin: 0;
        letter-spacing: 1px;
    }

    .block_content p.sub-title {
        font: 19px/21px freighttextbookitalic;
        margin: 0;
        letter-spacing: 1px;
    }

    .block_content p.sub-title-namaskar {
        font: 19px/21px freighttextbookitalic;
        letter-spacing: 1px;
    }

    .slide_related_content div:first-child {
        display: block;
    }

    .add_bracelet {
        background: #00b900;
        border: none;
        color: #fff;
        font: 14px ITCAvantGardeStd-Bk;
        height: 44px;
        margin: 10px 0 25px;
        letter-spacing: 1px;
        width: 100%;
    }

    .block_content > div > div p:last-child {
        margin-bottom: 0;
    }

    .block_content > div > div {
        padding-bottom: 0;
    }

    .block_thumbnail .close-icn {
        height: 44px;
        position: fixed;
        right: 0;
        top: 88px;
        width: 44px;
        display: none;
        z-index: 5;
    }

    .block_content img {
        margin: 30px 0;
    }

    .flexslider img {
        margin: 0 !important;
    }
</style>
<script type="text/javascript">
    jQuery(document).ready(function ($) {
        $(".sign-in-box .h1").html("OUR ETHICS");
        $(".flexslider").flexslider({
            after: function (slider) {
                slideContent(slider);
            }
        });


        var closebtnHtml = '<span class="close-icn" style="display:block;"><svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="44px" height="44px" viewBox="0 0 44 44" enable-background="new 0 0 44 44" xml:space="preserve"><g><rect fill="#555555" width="44" height="44"/><line fill="none" stroke="#FFFFFF" stroke-miterlimit="10" x1="14" y1="14" x2="30" y2="30"/><line fill="none" stroke="#FFFFFF" stroke-miterlimit="10" x1="30" y1="14" x2="14" y2="30"/></g></svg></span>';
        $(".page_block .block_thumbnail").append(closebtnHtml);
        $(".page_block .block_thumbnail .close-icn").bind("click", function (e) {
            window.location.href = '/';
        });

    });
    function slideContent(slider) {
        var current_slide = slider.currentSlide + 1;
        var rel_value = slider.find(".slides li:nth-child(" + current_slide + ") img").attr("rel");
        slider.next().children("div").hide();
        if(rel_value!= undefined){
            slider.next().children("div[rel=" + rel_value + "]").fadeIn();
            slider.next().css("min-height", slider.next().children("div[rel=" + rel_value + "]").height());
        }
    }


</script>
