<div class="ys-bottom">
    <div class="account-nav l-align ys_static_page_dropdown">
        <ul class="sub-nav">
            <li><a href="/our-story" data-heading="YS STORY" rel="our_story">Our Story</a></li>
            <li><a href="/our-core-values" data-heading="YS CORE VALUES" rel="our_core_values">Our Core Values</a></li>
            <li><a href="/our-ethics" data-heading="YS ETHICS" rel="our_core_ethics">Our Ethics</a></li>

            <li><a href="/our-stores" data-heading="YS STORES" rel="our_stores">Our Stores</a></li>
            <li><a href="/made-in-usa" data-heading="MADE IN USA" rel="made_in_usa">Made in USA</a></li>
            <li><a href="/principles-of-yoga" data-heading="YOGA PRINCIPLES" rel="principles_of_yoga">Principles of
                    Yoga</a></li>
            <li><a href="/namaskar" data-heading="NAMASK&aacute;R" rel="namaskar_foundation">NAMASK&aacute;R
                    Foundation</a></li>
            <li><a href="/press" data-heading="PRESS" rel="press">Press</a></li>


        </ul>

    </div>

</div>


<div class="page_block" rel="our_stores">
    <div class="block_thumbnail">
        <img src="<?php echo $this->getSkinUrl('images/our-stores.jpg'); ?>" class="img-responsive"/>

        <div class="overlay-text">
            <p class="text">Learn More</p>
        </div>
    </div>
    <div style="display:block;" class="block_content has_slider">
        <div class="flexslider">
            <div class="slides">
                <li>
                    <img src="<?php echo $this->getSkinUrl('images/our-stores2.jpg'); ?>" class="img-responsive"
                         rel="our-stores-block2"/>
                </li>
                <li>
                    <img src="<?php echo $this->getSkinUrl('images/our-stores1.jpg'); ?>" class="img-responsive"
                         rel="our-stores-block1"/>
                </li>
                <li>
                    <img src="<?php echo $this->getSkinUrl('images/our-stores3.jpg'); ?>" class="img-responsive"
                         rel="our-stores-block3"/>
                </li>
                <li>
                    <img src="<?php echo $this->getSkinUrl('images/our-stores5.jpg'); ?>" class="img-responsive"
                         rel="our-stores-block8"/>
                </li>
                <li>
                    <img src="<?php echo $this->getSkinUrl('images/our-stores4.jpg'); ?>" class="img-responsive"
                         rel="our-stores-block4"/>
                </li>
                <!--<li>
                    <img src="<?php /*echo $this->getSkinUrl('images/our-stores5.jpg'); */?>" class="img-responsive"
                         rel="our-stores-block5"/>
                </li>
                <li>
                    <img src="<?php /*echo $this->getSkinUrl('images/our-stores5.jpg'); */?>" class="img-responsive"
                         rel="our-stores-block6"/>
                </li>
                <li>
                    <img src="<?php /*echo $this->getSkinUrl('images/our-stores5.jpg'); */?>" class="img-responsive"
                         rel="our-stores-block7"/>
                </li>-->
            </div>
        </div>
        <div class="slide_related_content">
            <div rel="our-stores-block1">
                <p class="title">YOGASMOGA BRENTWOOD</p>

                <div>
                    <address>
                        11911 San Vicente Blvd, No 150 <br/>
                        Brentwood, Los Angeles, CA 90049 <br/>
                        <a href="mailto:brentwood@yogasmoga.com">brentwood@yogasmoga.com</a><br/>
                        <a href="tel:3104719642">310 471 YOGA (9642)</a>
                    </address>
                </div>

                <p class="store_hours">
                    <span>Store Hours</span><br/>
                    Monday&mdash;Friday 10am&mdash;8pm<br/>
                    Saturday&mdash;Sunday 10am&mdash;7pm
                </p>
            </div>
            <div rel="our-stores-block2">
                <p class="title">YOGASMOGA TOWNHOUSE</p>

                <div>
                    <address>
                        68 Greenwich Ave,<br/>
                        Greenwich, CT 06830<br/>
                        <a href="mailto:greenwich@yogasmoga.com">greenwich@yogasmoga.com</a><br/>
                        <a href="tel:2038619642">203 861 YOGA (9642)</a>
                    </address>
                </div>

                <p class="store_hours">
                    <span>Store Hours</span><br/>
                    Monday&mdash;Saturday 10am&mdash;6pm<br/>
                    Sunday 11am&mdash;6pm
                </p>
            </div>
            <div rel="our-stores-block3">
                <p class="title">YOGASMOGA BEVERLY HILLS</p>

                <div>
                    <address>
                        9458 Dayton Way,<br/>
                        Beverly Hills, CA 90210<br/>
                        <a href="mailto:beverlyhills@yogasmoga.com">beverlyhills@yogasmoga.com</a><br/>
                        <a href="tel:3102739642">310 273 YOGA (9642)</a>
                    </address>
                </div>

                <p class="store_hours">
                    <span>Store Hours</span><br/>
                    Monday&mdash;Saturday 11am&mdash;7pm<br/>
                    Sunday 11am&mdash;6pm
                </p>
            </div>
            <div rel="our-stores-block4">
                <p class="title">YOGASMOGA NEWPORT</p>

                <div>
                    <address>
                        1119 Newport Center Drive<br/>
                        Newport Beach, CA 92660<br/>
                        <a href="mailto:fashionisland@yogasmoga.com">fashionisland@yogasmoga.com</a><br/>
                        <a href="tel:8889909642">888 990 YOGA (9642))</a>
                    </address>
                </div>

                <p class="store_hours">
                    <span>Store Hours</span><br/>
                    Monday&mdash;Friday 11am&mdash;7pm<br/>
                    Saturday&mdash;Sunday 11am&mdash;6pm
                </p>
            </div>
            <div rel="our-stores-block5">
                <p class="title">YOGASMOGA SAN FRANCISCO</p>

                <div>
                    <address>
                        1119 Newport Center Drive<br/>
                        Newport Beach, CA 92660<br/>
                        <a href="mailto:sanfrancisco@yogasmoga.com">sanfrancisco@yogasmoga.com</a><br/>
                        <a href="tel:8889909642">888 990 YOGA (9642))</a>
                    </address>
                </div>

                <p class="store_hours">
                    <span>Coming Summer 2015</span>
                </p>
            </div>
            <div rel="our-stores-block6">
                <p class="title">YOGASMOGA LA JOLLA</p>

                <div>
                    <address>
                        1119 Newport Center Drive<br/>
                        Newport Beach, CA 92660<br/>
                        <a href="mailto:sanfrancisco@yogasmoga.com">sanfrancisco@yogasmoga.com</a><br/>
                        <a href="tel:8889909642">888 990 YOGA (9642))</a>
                    </address>
                </div>

                <p class="store_hours">
                    <span>Coming Fall 2015</span>
                </p>
            </div>
            <div rel="our-stores-block7">
                <p class="title">YOGASMOGA WESTCHESTER</p>

                <div>
                    <address>
                        1119 Newport Center Drive<br/>
                        Newport Beach, CA 92660<br/>
                        <a href="mailto:sanfrancisco@yogasmoga.com">sanfrancisco@yogasmoga.com</a><br/>
                        <a href="tel:8889909642">888 990 YOGA (9642))</a>
                    </address>
                </div>

                <p class="store_hours">
                    <span>Coming Fall 2015</span>
                </p>
            </div>
            <div rel="our-stores-block8">
                <p class="title">YOGASMOGA SOUTH STREET SEAPORT</p>

                <div>
                    <address>
                        19 FULTON STREET<br/>
                        NEW YORK, NY 10038<br/>
                        <a href="tel:6467624716">646 762 4716</a>
                    </address>
                </div>

                <p class="store_hours">
                    <span>AUGUST 1ST-SEPTEMBER 10TH</span><br/>
                    <span>Store Hours</span><br/>
                    Monday&mdash;Saturday 11am&mdash;7pm<br/>
                    Sunday 12am&mdash;6pm
                </p>
            </div>
        </div>

    </div>
</div>

<style>
    .page_block, .slide_related_content {
        float: left;
        width: 100%;
    }

    .block_thumbnail {
        position: relative;
        line-height: 0;
    }

    .overlay-text {
        bottom: 20px;
        color: #fff;
        font: 16px freighttextmedium;
        left: 0;
        letter-spacing: 1px;
        position: absolute;
        width: 100%;
    }

    .overlay-text .text::after {
        content: ">";
        color: #B8153E;
    }

    .block_content {
        padding: 14px 14px 30px;
        float: left;
        text-align: left;
        width: 100%;
        display: none;
    }

    .account-nav.l-align.ys_static_page_dropdown {
        display: none;
    }

    .slide_related_content > div {
        display: none;
        float: left;
        padding: 25px 0 20px;
        width: 100%;
        text-align: left;
    }

    .block_content p {
        font: 22px/28px freighttextbook;
        letter-spacing: normal;
        margin: 20px 0;
    }

    .slide_related_content > div address {
        font: 22px/28px freighttextbook;
        margin: 25px 0 20px;
    }

    .slide_related_content > div p.store_hours {
        font: 15px/22px GraphikRegular;
    }

    .slide_related_content > div p.store_hours span {
        font: 15px/22px Graphik-Semibold;
    }

    .block_content p.title {
        font: 24px/26px ITCAvantGardeStd-Bk;
        margin: 0;
    }

    .block_content p.sub-title {
        font: 24px/28px freighttextbookitalic;
        margin: 0;
    }

    .block_content p.sub-title-namaskar {
        font: 24px/28px freighttextbookitalic;
    }

    .slide_related_content div:first-child {
        display: block;
    }

    .add_bracelet {
        background: #00b900;
        border: none;
        color: #fff;
        font: 16px ITCAvantGardeStd-Bk;
        height: 44px;
        margin: 10px 0 25px;
        letter-spacing: 1px;
        width: 100%;
    }

    .block_content > div > div p:last-child {
        margin-bottom: 0;
    }

    .block_content > div > div {
        padding-bottom: 0;
    }

    .block_thumbnail .close-icn {
        height: 44px;
        position: fixed;
        right: 0;
        top: 88px;
        width: 44px;
        display: none;
        z-index: 5;
    }
	.flex-direction-nav{display:block;}

</style>
<script type="text/javascript">
    jQuery(document).ready(function ($) {
        $(".sign-in-box h1").html("OUR STORES");
        $(".flexslider").flexslider({
            after: function (slider) {
                slideContent(slider);
            }
        });

        var closebtnHtml = '<span class="close-icn"><svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="44px" height="44px" viewBox="0 0 44 44" enable-background="new 0 0 44 44" xml:space="preserve"><g><rect fill="#555555" width="44" height="44"/><line fill="none" stroke="#FFFFFF" stroke-miterlimit="10" x1="14" y1="14" x2="30" y2="30"/><line fill="none" stroke="#FFFFFF" stroke-miterlimit="10" x1="30" y1="14" x2="14" y2="30"/></g></svg></span>';
        $(".page_block .block_thumbnail").append(closebtnHtml);
        $(".page_block .block_thumbnail .close-icn").bind("click", function (e) {
            window.location.href = 'http://yogasmoga.com';
        });

    });
    function slideContent(slider) {
        var current_slide = slider.currentSlide + 1;
        var rel_value = slider.find(".slides li:nth-child(" + current_slide + ") img").attr("rel");
        slider.next().children("div").hide();
        if(rel_value!= undefined){
            slider.next().children("div[rel=" + rel_value + "]").fadeIn();
            slider.next().css("min-height", slider.next().children("div[rel=" + rel_value + "]").height());
        }
    }


</script>
