<div class="ys-bottom account-nav-box">
    <div class="account-nav l-align ys_static_page_dropdown">
        <!--  <ul class="sub-nav">
              <li><a href="javascript:void(0)"  rel="beverly-hills">BEVERLY HILLS, CA</a></li>
              <li><a href="javascript:void(0)"  rel="brentwood">BRENTWOOD, CA</a></li>
              <li><a href="javascript:void(0)"  rel="corte-madera">CORTE MADERA, CA</a></li>

              <li><a href="javascript:void(0)" rel="la-jo-la-ca-holiday">LA JOLLA, CA</a></li>
              <li><a href="javascript:void(0)" rel="malibu">MALIBU, CA</a></li>
              <li><a href="javascript:void(0)"  rel="new-port-beach">NEWPORT BEACH, CA</a></li>
              <li><a href="javascript:void(0)"  rel="san-francisco">SAN FRANCISCO, CA</a></li>
              <li><a href="javascript:void(0)"  rel="walnut-creek">WALNUT CREEK, CA</a></li>
              <li><a href="javascript:void(0)"  rel="townhouse">GREENWICH, CT</a></li>
              <li><a href="javascript:void(0)" rel="short-hills-new-jersy">SHORT HILLS, NJ</a></li>
              <li><a href="javascript:void(0)"  rel="westchester">WESTCHESTER, NY</a></li>


          </ul>-->

    </div>

</div>


<div class="page_block" rel="our_stores">
    <div class="block_thumbnail">
        <img src="<?php echo Mage::getBaseUrl('media'); ?>wysiwyg/mobile/ourstores/our-store.jpg" class="img-responsive"/>

        <div class="overlay-text">
            <!--            <p class="text">Learn More</p>-->
        </div>
    </div>
    <div style="display:block;" class="block_content has_slider">
        <div class="flexslider">
            <div class="slides">
                <li>
                    <img src="<?php echo Mage::getBaseUrl('media'); ?>wysiwyg/mobile/ourstores/townhouse.jpg" class="img-responsive"
                         rel="townhouse"/>
                </li>
                <!--<li>
                    <img src="<?php echo Mage::getBaseUrl('media'); ?>wysiwyg/mobile/ourstores/brentwood.jpg" class="img-responsive"
                         rel="brentwood"/>
                </li>-->
                <li>
                    <img src="<?php echo Mage::getBaseUrl('media'); ?>wysiwyg/mobile/ourstores/beverly-hills.jpg" class="img-responsive"
                         rel="beverly-hills"/>
                </li>
                <!-- <li>
                    <img src="<?php echo Mage::getBaseUrl('media'); ?>wysiwyg/mobile/ourstores/la-jo-la-pop-up-progressive.jpg" class="img-responsive"
                         rel="la-jo-la-pop-up"/>
                </li>-->
                <li>
                    <img src="<?php echo Mage::getBaseUrl('media'); ?>wysiwyg/mobile/ourstores/ys-store-fashion-island.jpg" class="img-responsive"
                         rel="new-port-beach"/>
                </li>



                <li>
                    <img src="<?php echo Mage::getBaseUrl('media'); ?>wysiwyg/mobile/ourstores/malibu-ourstore.jpg" class="img-responsive"
                         rel="malibu"/>
                </li>

                <li>
                    <img src="<?php echo Mage::getBaseUrl('media'); ?>wysiwyg/mobile/ourstores/ys-store-san-francisco.jpg" class="img-responsive"
                         rel="san-francisco"/>
                </li>


                <li>
                    <img src="<?php echo Mage::getBaseUrl('media'); ?>wysiwyg/mobile/ourstores/la-jolla-ys-store.jpg" class="img-responsive"
                         rel="la-jo-la-ca-holiday"/>
                </li>
              <?php /*?>  <li>
                    <img src="<?php echo Mage::getBaseUrl('media'); ?>wysiwyg/mobile/ourstores/ys-store-cortemadera.jpg" class="img-responsive"
                         rel="corte-madera"/>
                </li><?php */?>

                <li>
                    <img src="<?php echo Mage::getBaseUrl('media'); ?>wysiwyg/mobile/ourstores/ys-store-westchester.jpg" class="img-responsive"
                         rel="westchester"/>
                </li>
                <li>
                    <img src="<?php echo Mage::getBaseUrl('media'); ?>wysiwyg/mobile/ourstores/ys-store-shorthills.jpg" class="img-responsive"
                         rel="short-hills-new-jersy"/>
                </li>
                <!--<li>
                    <img src="<?php echo Mage::getBaseUrl('media'); ?>wysiwyg/mobile/ourstores/ys-store-walnut-creek.jpg" class="img-responsive"
                         rel="walnut-creek"/>
                </li>-->
            </div>
        </div>
        <div class="slide_related_content">
            <div rel="townhouse">
                <p class="title">YOGASMOGA TOWNHOUSE</p>

                <div>
                    <address>
                        68 Greenwich Ave<br/>
                        Greenwich, CT 06830<br/>
                        <a href="mailto:greenwich@yogasmoga.com">greenwich@yogasmoga.com</a><br/>
                        <a href="tel:2038619642">203 861 YOGA (9642)</a>
                    </address>
                </div>

                <p class="store_hours">
                    <span>Store Hours</span><br/>
                    Monday&ndash;Saturday 12pm&ndash;6pm<br/>
                    Sunday 12pm&ndash;5pm
                </p>
            </div>
           <!-- <div rel="brentwood">
                <p class="title">YOGASMOGA BRENTWOOD</p>

                <div>
                    <address>
                        11911 San Vicente Blvd <br/>
                        Los Angeles, CA 90049 <br/>
                        <a href="mailto:brentwood@yogasmoga.com">brentwood@yogasmoga.com</a><br/>
                        <a href="tel:3104719642">310 471 YOGA (9642)</a>
                    </address>
                </div>

                <p class="store_hours">
                    <span>Store Hours</span><br/>
                    Monday&ndash;Friday 10am&ndash;8pm<br/>
                    Saturday&ndash;Sunday 10am&ndash;7pm
                </p>
            </div>-->
            <div rel="beverly-hills">
                <p class="title">YOGASMOGA BEVERLY HILLS</p>

                <div>
                    <address>
                        9458 Dayton Way<br/>
                        Beverly Hills, CA 90210<br/>
                        <a href="mailto:beverlyhills@yogasmoga.com">beverlyhills@yogasmoga.com</a><br/>
                        <a href="tel:3102739642">310 273 YOGA (9642)</a>
                    </address>
                </div>

                <p class="store_hours">
                    <span>Store Hours</span><br/>
                    Monday&ndash;Saturday 12pm&ndash;6pm<br/>
                    Sunday 12pm&ndash;5pm
                </p>
            </div>
            <!--
			<div rel="la-jo-la-pop-up">
                <p class="title">YOGASMOGA <br/>LA JOLLA POP-UP<br/>(UNTIL 11.18)</p>

                <div>
                    <address>
                        7863 Girard Ave, #101<br/>
                        La Jolla, CA 92037<br/>
                        <a href="mailto:lajolla@yogasmoga.com">lajolla@yogasmoga.com</a>
                    </address>
                </div>

                <p class="store_hours">
                    <span>Store Hours</span><br/>
                    Monday&ndash;Saturday 10am&ndash;7pm<br/>
                    Sunday 10am&ndash;6pm
                </p>
            </div>-->
            <div rel="new-port-beach">
                <p class="title">YOGASMOGA NEWPORT BEACH AT FASHION ISLAND</p>

                <div>
                    <address>
                        1119 Newport Center Drive<br/>
                        Newport Beach, CA 92660<br/>
                        <a href="mailto:fashionisland@yogasmoga.com">fashionisland@yogasmoga.com</a><br/>
                        <a href="tel:9497219642">949 721 YOGA (9642)</a>
                    </address>
                </div>

                <p class="store_hours">
                    <span>Store Hours</span><br/>
                    Monday&ndash;Friday 10am&ndash;9pm<br/>
                    Saturday 10am&ndash;7pm<br/>
                    Sunday 11am&ndash;6pm
                </p>
            </div>






            <div rel="malibu">
                <p class="title">YOGASMOGA MALIBU</p>

                <div>
                    <address>
                        3900 Cross Creek Road<br/>
                        Malibu, CA 90265<br/>
                        <a href="mailto:malibu@yogasmoga.com">malibu@yogasmoga.com</a><br/>
                        <a href="tel:4243465002">424 346 5003</a>
                    </address>
                </div>
                <p class="store_hours">
                    <span>Store Hours</span><br/>
                    Monday&ndash;Saturday 12pm&ndash;6pm<br/>
                    Sunday 12pm&ndash;5pm
                </p>
            </div>
            <div rel="san-francisco">
                <p class="title">YOGASMOGA <br/>SAN FRANCISCO</p>

                <div>
                    <address>
                        66 Kearny Street<br/>
                        San Francisco, CA 94108<br/>
                        <a style="font-size: 18px;" href="mailto:sanfran.unionsquare@yogasmoga.com">sanfran.unionsquare@yogasmoga.com</a><br/>
                        <a href="tel:4159349642">415 934 YOGA (9642)</a>
                    </address>
                </div>
                <p class="store_hours">
                    <span>Store Hours</span><br/>
                    Monday–Saturday 10am&ndash;6pm<br/>
                    Sunday 11pm&ndash;5pm
                </p>
            </div>
            <div rel="la-jo-la-ca-holiday">
                <p class="title">YOGASMOGA LA JOLLA</p>

                <div>
                    <address>
                        7863 Girard Ave<br/>Suite No. 101<br/>
                        La Jolla, CA 92037<br/>
                        <a href="mailto:lajolla@yogasmoga.com">lajolla@yogasmoga.com</a><br/>
                        <a href="tel:8587329642">858 732 YOGA (9642)</a>
                    </address>
                </div>
                <p class="store_hours">
                    <span>Store Hours</span><br/>
                    Monday&ndash;Saturday 10am&ndash;7pm<br/>
                    Sunday 10am&ndash;6pm
                </p>
            </div>
        <!--    <div rel="corte-madera">
                <p class="title">YOGASMOGA CORTE MADERA</p>

                <div>
                    <address>
                        1530 Redwood Hwy<br/>
                        Corte Madera, CA 94925<br/>
                        <a href="mailto:cortemadera@yogasmoga.com">cortemadera@yogasmoga.com</a><br/>
                        <a href="tel:4155486110">415 548 6110</a>
                    </address>
                </div>
                <p class="store_hours">
                    <span>Store Hours</span><br/>
                    Monday&ndash;Friday 10am&ndash;8pm<br/>
                    Saturday 10am&ndash;7pm<br/>
                    Sunday 11am&ndash;6pm
                </p>
            </div>-->

            <div rel="westchester">
                <p class="title">YOGASMOGA WESTCHESTER</p>

                <div>
                    <address>
                        125 Westchester Ave<br/>
                        White Plains, NY 10601<br/>
                        <a href="mailto:westchester@yogasmoga.com">westchester@yogasmoga.com</a><br/>
                        <a href="tel:9146379642">914 367 YOGA (9642)</a>
                    </address>
                </div>

                <p class="store_hours">
                    <span>Store Hours</span><br/>
                    Monday&ndash;Saturday 10am&ndash;9pm<br/>
                    Sunday 11am&ndash;6:30pm
                </p>
            </div>
            <div rel="short-hills-new-jersy">
                <p class="title">YOGASMOGA SHORT HILLS</p>

                <div>
                    <address>
                        1200 Morris Tpke<br/>
                        Short Hills, NJ 07078<br/>
                        <a href="mailto:shorthills@yogasmoga.com">shorthills@yogasmoga.com</a><br/>
                        <a href="tel:973 315 9671">973 315 9671</a>
                    </address>
                </div>

                <p class="store_hours">
                    <span>Store Hours</span><br/>
                    Monday&ndash;Friday 10am&ndash;9pm<br/>
                    Saturday 10am&ndash;8pm<br/>
                    Sunday 11am&ndash;6pm
                </p>
            </div>
        <!--   <div rel="walnut-creek">
                <p class="title">YOGASMOGA WALNUT CREEK</p>

                <div>
                    <address>
                        1166 Broadway Plaza<br/>
                        Walnut Creek, CA 94596<br/>
                        <a href="mailto:walnutcreek@yogasmoga.com">walnutcreek@yogasmoga.com</a><br/>
                        <a href="tel:3233948677">323 394 8677</a>
                    </address>
                </div>
                <p class="store_hours">
                    <span>Store Hours</span><br/>
                    Monday&ndash;Friday 10am&ndash;9pm<br/>
                    Saturday 10am&ndash;7pm<br/>
                    Sunday 11am&ndash;6pm
                </p>
            </div>-->
        </div>
    </div>
</div>

<style>
    .page_block, .slide_related_content {
        float: left;
        width: 100%;
    }

    .block_thumbnail {
        position: relative;
        line-height: 0;
    }

    .overlay-text {
        bottom: 20px;
        color: #fff;
        font: 16px freighttextmedium;
        left: 0;
        letter-spacing: 1px;
        position: absolute;
        width: 100%;
    }

    .overlay-text .text::after {
        content: ">";
        color: #B8153E;
    }

    .block_content {
        padding: 14px 14px 30px;
        float: left;
        text-align: left;
        width: 100%;
        display: none;
    }

    .account-nav.l-align.ys_static_page_dropdown {
        display: none;
    }

    .slide_related_content > div {
        display: none;
        float: left;
        padding: 30px 0 20px;
        width: 100%;
        text-align: left;
    }

    .block_content p {
        font: 18px/1.65em freighttextbook;
        letter-spacing: normal;
        margin: 20px 0 0;
    }

    .slide_related_content > div address {
        font: 18px/1.65em freighttextbook;
        margin: 20px 0 20px;
    }

    .slide_related_content > div p.store_hours {
        font: 12px/18px GraphikRegular;
    }

    .slide_related_content > div p.store_hours span {
        font: 12px/18px Graphik-Semibold;
    }

    .block_content p.title {
        font: 19px/21px ITCAvantGardeStd-Bk;
        margin: 0;
        letter-spacing: 1px;
    }

    .block_content p.sub-title {
        font: 19px/21px freighttextbookitalic;
        margin: 0;
        letter-spacing: 1px;
    }

    .block_content p.sub-title-namaskar {
        font: 19px/21px freighttextbookitalic;
        letter-spacing: 1px;
    }

    .slide_related_content div:first-child {
        display: block;
    }

    .add_bracelet {
        background: #00b900;
        border: none;
        color: #fff;
        font: 14px ITCAvantGardeStd-Bk;
        height: 44px;
        margin: 10px 0 25px;
        letter-spacing: 1px;
        width: 100%;
    }

    .block_content > div > div p:last-child {
        margin-bottom: 0;
    }

    .block_content > div > div {
        padding-bottom: 0;
    }

    .block_thumbnail .close-icn {
        height: 44px;
        position: fixed;
        right: 0;
        top: 88px;
        width: 44px;
        display: none;
        z-index: 5;
    }

    .block_content img {
        margin: 30px 0;
    }

    .flexslider img {
        margin: 0 !important;
    }

    .account-nav-box{height: 100%;left: 0;overflow: auto;position: fixed;top: 0;width: 100%; z-index: -1;}
    .account-nav-box.showanb{z-index:9;}
    .account-nav-box .account-nav{position:absolute;}
    .account-nav .flex-control-nav{display:block!important; position:static;}
    .account-nav .flex-control-nav li{display:block;margin:0 0px !important;}
    .account-nav .flex-control-nav a{background:#fff;border-radius:0;}

    .account-nav .sub-nav.flex-control-nav li a {
        color: #656565!important;
        display: block!important;
        font-family: Avantgarde-demi!important;
        font-size: 12px!important;
        height: 44px!important;
        line-height: 50px!important;
        padding: 0 14px!important;
        text-decoration: none!important;
        text-transform: uppercase!important;
        width: 100%!important;
        text-indent:0!important;
        position:static!important;
    }
    .account-nav .sub-nav.flex-control-nav li a.active_link{color:#ae8637 !important;}
    .ui-loader{display:none!important;}
</style>
<script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>
<script type="text/javascript">
    jQuery(document).ready(function ($) {
        $(".sign-in-box .h1").html("YS Stores");

        $(".flexslider").flexslider({
            after: function (slider) {
                slideContent(slider);
                $('.account-nav .flex-control-nav.flex-control-paging li a').removeClass('active_link');
                $('.account-nav .flex-control-nav.flex-control-paging li a.flex-active').addClass('active_link');

            }
        });


        var closebtnHtml = '<span class="close-icn" style="display:block;"><svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="44px" height="44px" viewBox="0 0 44 44" enable-background="new 0 0 44 44" xml:space="preserve"><g><rect fill="#555555" width="44" height="44"/><line fill="none" stroke="#FFFFFF" stroke-miterlimit="10" x1="14" y1="14" x2="30" y2="30"/><line fill="none" stroke="#FFFFFF" stroke-miterlimit="10" x1="30" y1="14" x2="14" y2="30"/></g></svg></span>';
        $(".page_block .block_thumbnail").append(closebtnHtml);
        $(".page_block .block_thumbnail .close-icn").bind("click", function (e) {
            window.location.href = '/';
        });

    });
    function slideContent(slider) {
        var current_slide = slider.currentSlide + 1;
        var rel_value = slider.find(".slides li:nth-child(" + current_slide + ") img").attr("rel");
        slider.next().children("div").hide();
        if(rel_value!= undefined){
            slider.next().children("div[rel=" + rel_value + "]").fadeIn();
            slider.next().css("min-height", slider.next().children("div[rel=" + rel_value + "]").height());
        }
    }

    jQuery(window).load(function(){

        jQuery('.flex-control-nav.flex-control-paging').appendTo('.account-nav');
        jQuery('.account-nav .flex-control-nav.flex-control-paging').addClass('sub-nav');
        jQuery('.account-nav .flex-control-nav.flex-control-paging li:nth-child(1) a').text('GREENWICH, CT');
        //jQuery('.account-nav .flex-control-nav.flex-control-paging li:nth-child(2) a').text('BRENTWOOD, CA');
        jQuery('.account-nav .flex-control-nav.flex-control-paging li:nth-child(2) a').text('Beverly Hills, CA');
        jQuery('.account-nav .flex-control-nav.flex-control-paging li:nth-child(3) a').text('NEWPORT BEACH, CA');
        jQuery('.account-nav .flex-control-nav.flex-control-paging li:nth-child(4) a').text('MALIBU, CA');
        jQuery('.account-nav .flex-control-nav.flex-control-paging li:nth-child(5) a').text('SAN FRANCISCO. CA');
        jQuery('.account-nav .flex-control-nav.flex-control-paging li:nth-child(6) a').text('LA JOLLA, CA');
        //jQuery('.account-nav .flex-control-nav.flex-control-paging li:nth-child(7) a').text('CORTE MADERA, CA');
        jQuery('.account-nav .flex-control-nav.flex-control-paging li:nth-child(7) a').text('WESTCHESTER, NY');
        jQuery('.account-nav .flex-control-nav.flex-control-paging li:nth-child(8) a').text('SHORT HILLS, NJ');
        //jQuery('.account-nav .flex-control-nav.flex-control-paging li:nth-child(11) a').text('WALNUT CREEK, CA');
        jQuery(".account-nav .flex-control-nav.flex-control-paging li a").attr("href","#");


        jQuery(".l-align li").on("click tap", "a", function (e) {
            e.preventDefault();
            jQuery(".ys_static_page_dropdown li a").removeClass('active_link');
            jQuery(this).addClass('active_link');
            jQuery(".account-nav.l-align.ys_static_page_dropdown").slideUp('',function(){
                jQuery(".account-nav-box").removeClass('showanb');
            });

            jQuery(".arrow-icon").removeClass("active");
        });



    });
</script>

