<div class="ys-bottom">
    <div class="account-nav l-align ys_static_page_dropdown">
        <ul class="sub-nav">
            <li><a href="/our-story" data-heading="YS STORY" rel="our_story">Our Story</a></li>
            <li><a href="/our-core-values" data-heading="YS CORE VALUES" rel="our_core_values">Our Core Values</a></li>
            <li><a href="/our-ethics" data-heading="YS ETHICS" rel="our_ethics">Our Ethics</a></li>

            <li><a href="/our-stores" data-heading="YS STORES" rel="our_stores">Our Stores</a></li>
            <li><a href="/made-in-usa" data-heading="MADE IN USA" rel="made_in_usa">Made in USA</a></li>
            <li><a href="/principles-of-yoga" data-heading="YOGA PRINCIPLES" rel="principles_of_yoga">Principles of
                    Yoga</a></li>
            <li><a href="/namaskar" data-heading="NAMASK&aacute;R" rel="namaskar_foundation">NAMASK&aacute;R
                    Foundation</a></li>
            <li><a href="/press" data-heading="PRESS" rel="press">Press</a></li>

        </ul>

    </div>

</div>

<div class="page_block" id="our_story">
    <div class="block_thumbnail">
        <img src="<?php echo $this->getSkinUrl('images/our-story-thumbnail.jpg'); ?>" class="img-responsive"/>

        <div class="overlay-text">
            <p class="text">Learn More</p>
        </div>
    </div>
    <div class="block_content has_slider">
        <div class="flexslider">
            <div class="slides">
                <li>
                    <img src="<?php echo $this->getSkinUrl('images/our-story-slide1.jpg'); ?>" class="img-responsive"
                         rel="our-story-block1"/>
                </li>
                <li>
                    <img src="<?php echo $this->getSkinUrl('images/our-story-slide2.jpg'); ?>" class="img-responsive"
                         rel="our-story-block2"/>
                </li>
                <li>
                    <img src="<?php echo $this->getSkinUrl('images/our-story-slide3.jpg'); ?>" class="img-responsive"
                         rel="our-story-block3"/>
                </li>
                <li>
                    <img src="<?php echo $this->getSkinUrl('images/our-story-slide4.jpg'); ?>" class="img-responsive"
                         rel="our-story-block4"/>
                </li>
            </div>
        </div>
        <div class="slide_related_content">
            <div rel="our-story-block1">
                <p class="title">WE ARE YOGASMOGA <br>WE MAKE THINGS FOR LIFE</p>

                <p class="sub-title">One Breath at a Time</p>

                <p>
                    What if Yoga worked beyond breathing and poses to hold a new position?
                </p>

                <p>
                    Honoring the tenets of Yoga, we aspire to create world-class products. Growing up in the Himalayas,
                    the birthplace & capital of Yoga, our founders instinctively infuse the timeless principles, spirit
                    and practice of Yoga into everything we do. From our cosmopolitan aesthetic, to our product
                    technology, right down to creating our very own way to give back, we&rsquo;ve meticulously designed
                    every
                    part of the whole, one breath at a time.
                </p>
            </div>
            <div rel="our-story-block2">
                <p class="title">IMAGINE IT AS A PRACTICE,<br/> A WAY OF BEING</p>

                <p class="sub-title">Building a pathway to greater good</p>

                <p>
                    We take the stand that physically, mentally, and emotionally Karma works in harmony with innovation,
                    so that technology becomes a pathway to greater good. In the act of balancing science with
                    spirituality you cause a chemical reaction that can promote something as great as change.
                    Connecting, interacting and creating a positive impact beyond the Yoga mat.
                </p>

                <p>
                    We engineer, design, and manufacture fabrics that do more than cover someone up. They open them up
                    to greater good. While we work with the most technically advanced fabric and manufacturing
                    technologies, we also pursue a relentless focus on the deep traditions of Yoga. We embody the soul
                    of Yoga and instinctively embed this into everything we create including investing much time into
                    creating the NAMASK&Aacute;R Foundation.
                </p>
            </div>
            <div rel="our-story-block3">
                <p class="title">MAKE THINGS FROM <br/>THE HEART & WITH LOVE</p>

                <p class="sub-title">For wherever life takes you</p>

                <p>
                    A lot of people think of themselves as clothing companies who sell Yoga apparel. We think of
                    ourselves differently. We are a Yoga and wellness company that makes things for life. Our focus is
                    not on building a brand; our goal is to have a love affair with our consumers. We create our
                    products from the heart and with love and we want everyone to feel that. We are building YOGASMOGA
                    from the ground up with a purpose and passion and our products reflect this love and care.
                </p>

                <p>
                    We strive to become your partner in the pursuit of wellness&mdash;wherever you are today and
                    wherever you
                    are going tomorrow. From Yoga class, to the gym, to life. Whether you&rsquo;re on the go, or simply
                    being,
                    we&rsquo;re happy to be with you. We hope to bring a little more Yoga into your journey, everyday.
                </p>
            </div>
            <div rel="our-story-block4">
                <p class="title">A BIT MORE ABOUT US</p>

                <p class="sub-title">Joy, energy & balance</p>

                <p>
                    Staying true to the spirit of Yoga, everything we create intends to balance the joy of life with the
                    energy required to live it. Take our name as an example, in Hindi, it&rsquo;s traditional to rhyme
                    words
                    and similar items&mdash;so our name is a jubilant nod of respect to our culture.
                </p>

                <p>
                    To combine that joy with energy, our iconic logo is based on traditional symbology that conveys a
                    balanced and powerful energy center. We see this as a beautiful metaphor for our human experience.
                </p>
            </div>
        </div>

    </div>
</div>

<!-- page block end -------------------------------------------------------------------------------------------->


<div class="page_block" id="our_core_values">
    <div class="block_thumbnail">
        <img src="<?php echo $this->getSkinUrl('images/our-core-values.jpg'); ?>" class="img-responsive"/>

        <div class="overlay-text">
            <p class="text">Learn More</p>
        </div>
    </div>
    <div class="block_content has_slider">
        <div class="flexslider">
            <div class="slides">
                <li>
                    <img src="<?php echo $this->getSkinUrl('images/our-core-values1.jpg'); ?>" class="img-responsive"
                         rel="our-core-values-block1"/>
                </li>
                <li>
                    <img src="<?php echo $this->getSkinUrl('images/our-core-values2.jpg'); ?>" class="img-responsive"
                         rel="our-core-values-block2"/>
                </li>
                <li>
                    <img src="<?php echo $this->getSkinUrl('images/our-core-values3.jpg'); ?>" class="img-responsive"
                         rel="our-core-values-block3"/>
                </li>
                <li>
                    <img src="<?php echo $this->getSkinUrl('images/our-core-values4.jpg'); ?>" class="img-responsive"
                         rel="our-core-values-block4"/>
                </li>
                <li>
                    <img src="<?php echo $this->getSkinUrl('images/our-core-values5.jpg'); ?>" class="img-responsive"
                         rel="our-core-values-block5"/>
                </li>
                <li>
                    <img src="<?php echo $this->getSkinUrl('images/our-core-values6.jpg'); ?>" class="img-responsive"
                         rel="our-core-values-block6"/>
                </li>
                <li>
                    <img src="<?php echo $this->getSkinUrl('images/our-core-values7.jpg'); ?>" class="img-responsive"
                         rel="our-core-values-block7"/>
                </li>
            </div>
        </div>
        <div class="slide_related_content">
            <div rel="our-core-values-block1">
                <p class="title">DEEP, DIRECT AND LASTING <br/>CONNECTIONS</p>

                <p>
                    We put in great love, care and devotion to create products that will delight our SMOGI&rsquo;s (that&rsquo;s
                    you
                    and all of our YOGASMOGA community). We aim to touch the daily lives of our SMOGI&rsquo;s, building
                    deep
                    connections and long-lasting bonds.
                </p>
            </div>
            <div rel="our-core-values-block2">
                <p class="title">A RESPONSIBILITY BASED <br/>REPUTATION</p>

                <p>
                    We strive to earn the respect of our SMOGI&rsquo;s by constantly delivering at a superior level with
                    everything we do. We know this respect is earned through action and over a long period of time. We
                    take this responsibility seriously. We make real things for life and at times mistakes will happen.
                    Our promise is to rectify any mistake immediately and proactively.
                </p>
            </div>
            <div rel="our-core-values-block3">
                <p class="title">A MANTRA OF INNOVATION</p>

                <p>
                    We are committed to using the most innovative and pioneering techniques to develop our fabric
                    technology. Our unyielding commitment to using the best technologies is more than a best practice
                    for us, it&rsquo;s our mantra&mdash;an everyday practice that yields far superior products for our
                    SMOGI&rsquo;s.
                </p>
            </div>
            <div rel="our-core-values-block4">
                <p class="title">A CORE OF AUTHENTICITY</p>

                <p>
                    While we labor to work with the most technologically advanced fabrics and manufacturing techniques,
                    we pursue a relentless focus on the deep-rooted traditions of Yoga . We strive to apply the
                    principles, practice and spirit of Yoga to everything we do, and everything we create. We hope this
                    will bring Yoga to life in new and meaningful ways.
                </p>
            </div>
            <div rel="our-core-values-block5">
                <p class="title">COLLABORATION <br/>AS CULTURE</p>

                <p>
                    We inspire our people to be creative through constant collaboration. This drives us to deliver the
                    very best, for everyone. Our people take pride in the work we do together.
                </p>
            </div>
            <div rel="our-core-values-block6">
                <p class="title">EAT, SLEEP & BREATHE <br/>THE DETAILS</p>

                <p>
                    We have an uncompromising determination to achieve excellence in everything we undertake&mdash;one
                    breath
                    at a time. We believe that if we pay keen attention to the smallest details and strive for
                    ever-present awareness in our everyday actions, the results will show.
                </p>
            </div>
            <div rel="our-core-values-block7">
                <p class="title">THE GIFT OF NAMASK&Aacute;R</p>

                <p>
                    We recognize that textile production is typically done in the most challenged economic locations in
                    the world and we feel it is our absolute obligation and duty to give back to those who have joined
                    us on this journey. Which is why we have created the NAMASK&Aacute;R Foundation.
                </p>
            </div>
        </div>

    </div>
</div>


<!-- page block end -------------------------------------------------------------------------------------------->


<div class="page_block" id="our_ethics">
    <div class="block_thumbnail">
        <img src="<?php echo $this->getSkinUrl('images/our-ethics.jpg'); ?>" class="img-responsive"/>

        <div class="overlay-text">
            <p class="text">Learn More</p>
        </div>
    </div>
    <div class="block_content has_slider">
        <div class="flexslider">
            <div class="slides">
                <li>
                    <img src="<?php echo $this->getSkinUrl('images/our-ethics1.jpg'); ?>" class="img-responsive"
                         rel="our-ethics-block1"/>
                </li>
                <li>
                    <img src="<?php echo $this->getSkinUrl('images/our-ethics2.jpg'); ?>" class="img-responsive"
                         rel="our-ethics-block2"/>
                </li>
                <li>
                    <img src="<?php echo $this->getSkinUrl('images/our-ethics3.jpg'); ?>" class="img-responsive"
                         rel="our-ethics-block3"/>
                </li>
                <li>
                    <img src="<?php echo $this->getSkinUrl('images/our-ethics4.jpg'); ?>" class="img-responsive"
                         rel="our-ethics-block4"/>
                </li>
                <li>
                    <img src="<?php echo $this->getSkinUrl('images/our-ethics5.jpg'); ?>" class="img-responsive"
                         rel="our-ethics-block5"/>
                </li>
            </div>
        </div>
        <div class="slide_related_content">
            <div rel="our-ethics-block1">
                <p class="title">PRESERVE THE ENVIRONMENT</p>

                <p>
                    We believe that if we don&rsquo;t take good care of our world, it may fast disappear. We have a
                    responsibility to our planet.
                </p>

                <p>
                    Fabric dyeing processes inherently use chemicals to develop dye pigments. We do not use any harmful
                    formaldehyde based dyes that can destroy our groundwater.
                </p>

                <p>
                    We have developed a dyeing process that is as efficient and eco-friendly as possible. We use the
                    most advanced computerized color matching and dyeing apparatus and high performance dye-jets. The
                    dye-jets are custom programmed to use exact amount of pigmentation so that residual water after the
                    dyeing is clear and run off can be released without adding harmful chemicals.
                </p>

                <p>
                    Unlike many companies who have their dyeing facilities located in China, our dye-lab is located in
                    the USA, in a geographical area with the toughest environmental and pollution standards. We are very
                    proud to have developed processes that meet and exceed these strict environmental regulations.
                </p>
            </div>
            <div rel="our-ethics-block2">
                <p class="title">CONTRIBUTE TO REDUCING THE CARBON FOOTPRINT</p>

                <p>
                    Significant work has been done to solve for and create a supply chain as close to YOGASMOGA HQ (New
                    York City) as possible.
                </p>

                <p>
                    We do not produce in China and do not ship goods 12,500 miles across the globe&mdash;this reduces
                    our
                    fossil fuel usage dramatically. While we can make cheap goods in China, we have made the conscious
                    decision not to do so. We manufacture as close to home as possible with goods travelling 1/4th the
                    distance as compared to our competitors, dramatically reducing our carbon footprint.
                </p>

                <p>
                    We source trims such as elastics and threads as close to our production facilities as possible, thus
                    reducing fossil fuel usage.
                </p>
            </div>
            <div rel="our-ethics-block3">
                <p class="title">RESPONSIBLE PRODUCTION</p>

                <p>
                    YOGASMOGA has a very vigorous selection process of production partners. We work only with the best
                    manufacturers who have demonstrated a commitment to adhere to the highest ethical standards.
                </p>

                <p>
                    We conduct regular audits of our partner factories.
                </p>

                <p>
                    Our production facilities have been awarded the Platinum Certificate of Compliance from WRAP
                    (Worldwide Responsible Accredited Production). Our facilities are also participating suppliers of
                    the Fair Labor Association. (Just in case you were wondering&mdash;Yes its kind of a big deal to
                    achieve these certifications)
                </p>

                <p>
                    Our production facilities have an extensive green environment program including recycling, energy
                    saving production measures, use of clean fuels like LPG&rsquo;s, reforestation and use of
                    biodegradable
                    chemicals.
                </p>
            </div>
            <div rel="our-ethics-block4">
                <p class="title">ACCURATE REPRESENTATION OF VISUAL IMAGES</p>

                <p>
                    As a rule, YOGASMOGA does not allow any body retouching in our photography. All photographers have
                    to commit to this rule. No exceptions.
                </p>

                <p>
                    We make an extraordinary effort to work with teachers and everyday practitioners of yoga for visual
                    representation of our products.
                </p>
            </div>
            <div rel="our-ethics-block5">
                <p class="title">ACCOUNTABILITY FOR EACH COMPONENT IN THE SUPPLY CHAIN</p>

                <p>
                    YOGASMOGA is committed to owning ever piece of the supply chain. We assume responsibility for every
                    step in the production process from sourcing fiber to bringing you the finished apparel. We research
                    & develop it, we manufacture it, we dye it, we cut it, we stitch it, we pack it, we ship it&mdash;
                    why?&mdash;so you can proudly enjoy it.
                </p>

                <p>
                    We require a Manufacturer&rsquo;s Affidavit of Origin on all yarns that we purchase, ensuring
                    adherence to
                    the highest quality yarns. We strongly believe that sourcing the best raw materials available to us
                    results in the best performing products. Life is sometimes as simple as the choices you make.
                </p>

                <p>
                    We work directly with all our suppliers even for the smallest components such as trims, labels and
                    threads that make up the product. We believe that sub contracting even these smaller items can and
                    will compromise quality. We look closer and go deeper to deliver the very best to you.
                </p>
            </div>
        </div>

    </div>
</div>

<!-- page block end -------------------------------------------------------------------------------------------->


<div class="page_block" id="our_stores">
    <div class="block_thumbnail">
        <img src="<?php echo $this->getSkinUrl('images/our-stores.jpg'); ?>" class="img-responsive"/>

        <div class="overlay-text">
            <p class="text">Learn More</p>
        </div>
    </div>
    <div class="block_content has_slider">
        <div class="flexslider">
            <div class="slides">
                <li>
                    <img src="<?php echo Mage::getBaseUrl('media'); ?>wysiwyg/mobile/ourstores/townhouse.jpg" class="img-responsive"
                         rel="townhouse"/>
                </li>
                <li>
                    <img src="<?php echo Mage::getBaseUrl('media'); ?>wysiwyg/mobile/ourstores/brentwood.jpg" class="img-responsive"
                         rel="brentwood"/>
                </li>
                <li>
                    <img src="<?php echo Mage::getBaseUrl('media'); ?>wysiwyg/mobile/ourstores/beverly-hills.jpg" class="img-responsive"
                         rel="beverly-hills"/>
                </li>
               <!-- <li>
                    <img src="<?php echo Mage::getBaseUrl('media'); ?>wysiwyg/mobile/ourstores/la-jo-la-pop-up-progressive.jpg" class="img-responsive"
                         rel="la-jo-la-pop-up"/>
                </li>-->
                <li>
                    <img src="<?php echo Mage::getBaseUrl('media'); ?>wysiwyg/mobile/ourstores/fashion-island.jpg" class="img-responsive"
                         rel="new-port-beach"/>
                </li>
              
              
                <li>
                    <img src="<?php echo Mage::getBaseUrl('media'); ?>wysiwyg/mobile/ourstores/boston.jpg" class="img-responsive"
                         rel="prudent-center"/>
                </li>
				<li>
                    <img src="<?php echo Mage::getBaseUrl('media'); ?>wysiwyg/mobile/ourstores/malibu-ourstore.jpg" class="img-responsive"
                         rel="malibu"/>
                </li>
               
                <li>
                    <img src="<?php echo Mage::getBaseUrl('media'); ?>wysiwyg/mobile/ourstores/san-francisco-ourstore.jpg" class="img-responsive"
                         rel="san-francisco"/>
                </li>
                
                
				<li>
                    <img src="<?php echo Mage::getBaseUrl('media'); ?>wysiwyg/mobile/ourstores/la-jo-la-ca-holiday-progressive.jpg" class="img-responsive"
                         rel="la-jo-la-ca-holiday"/>
                </li>
				  <li>
                    <img src="<?php echo Mage::getBaseUrl('media'); ?>wysiwyg/mobile/ourstores/short-hills-new-jersy-progressive.jpg" class="img-responsive"
                         rel="short-hills-new-jersy"/>
                </li>
				  <li>
                    <img src="<?php echo Mage::getBaseUrl('media'); ?>wysiwyg/mobile/ourstores/westchester-progressive.jpg" class="img-responsive"
                         rel="westchester"/>
                </li>
				 <li>
                    <img src="<?php echo Mage::getBaseUrl('media'); ?>wysiwyg/mobile/ourstores/corte-madera-progressive.jpg" class="img-responsive"
                         rel="corte-madera"/>
                </li>
                <li>
                    <img src="<?php echo Mage::getBaseUrl('media'); ?>wysiwyg/mobile/ourstores/walnut-creek-progressive.jpg" class="img-responsive"
                         rel="walnut-creek"/>
                </li>
            </div>
        </div>
        <div class="slide_related_content">
            <div rel="townhouse">
                <p class="title">YOGASMOGA TOWNHOUSE</p>

                <div>
                    <address>
                        68 Greenwich Ave,<br/>
                        Greenwich, CT 06830<br/>
                        <a href="mailto:greenwich@yogasmoga.com">greenwich@yogasmoga.com</a><br/>
                        <a href="tel:2038619642">203 861 YOGA (9642)</a>
                    </address>
                </div>

                <p class="store_hours">
                    <span>Store Hours</span><br/>
                    Monday&ndash;Friday 10am&ndash;6pm<br/>
                    Saturday&ndash;Sunday 11am&ndash;6pm
                </p>
            </div>
            <div rel="brentwood">
                <p class="title">YOGASMOGA BRENTWOOD</p>

                <div>
                    <address>
                        11911 San Vicente Blvd, No 150 <br/>
                        Brentwood, Los Angeles, CA 90049 <br/>
                        <a href="mailto:brentwood@yogasmoga.com">brentwood@yogasmoga.com</a><br/>
                        <a href="tel:3104719642">310 471 YOGA (9642)</a>
                    </address>
                </div>

                <p class="store_hours">
                    <span>Store Hours</span><br/>
                    Monday&ndash;Friday 10am&ndash;8pm<br/>
                    Saturday&ndash;Sunday 11am&ndash;7pm
                </p>
            </div>
            <div rel="beverly-hills">
                <p class="title">YOGASMOGA BEVERLY HILLS</p>

                <div>
                    <address>
                        9458 Dayton Way,<br/>
                        Beverly Hills, CA 90210<br/>
                        <a href="mailto:beverlyhills@yogasmoga.com">beverlyhills@yogasmoga.com</a><br/>
                        <a href="tel:3102739642">310 273 YOGA (9642)</a>
                    </address>
                </div>

                <p class="store_hours">
                    <span>Store Hours</span><br/>
                    Monday&ndash;Friday 11am&ndash;7pm<br/>
                    Saturday&ndash;Sunday 11am&ndash;6pm
                </p>
            </div>
            <!--
			<div rel="la-jo-la-pop-up">
                <p class="title">YOGASMOGA <br/>LA JOLLA POP-UP<br/>(UNTIL 11.18)</p>

                <div>
                    <address>
                        7863 Girard Ave, #101<br/>
                        La Jolla, CA 92037<br/>
                        <a href="mailto:lajolla@yogasmoga.com">lajolla@yogasmoga.com</a>
                    </address>
                </div>

                <p class="store_hours">
                    <span>Store Hours</span><br/>
                    Monday&ndash;Saturday 10am&ndash;7pm<br/>
                    Sunday 10am&ndash;6pm
                </p>
            </div>-->
            <div rel="new-port-beach">
                <p class="title">YOGASMOGA NEWPORT BEACH AT FASHION ISLAND</p>

                <div>
                    <address>
                        1119 Newport Center Drive<br/>
                        Newport Beach, CA 92660<br/>
                        <a href="mailto:fashionisland@yogasmoga.com">fashionisland@yogasmoga.com</a><br/>
                        <a href="tel:9497219642">949 721 YOGA (9642)</a>
                    </address>
                </div>

                <p class="store_hours">
                    <span>Store Hours</span><br/>
                    Monday&ndash;Friday 10am&ndash;9pm<br/>
                    Saturday 10am&ndash;7pm<br/>
                    Sunday 11am&ndash;6pm
                </p>
            </div>
           
           
            <div rel="prudent-center">
                <p class="title">YOGASMOGA AT &ldquo;THE PRU&rdquo;</p>

                <div>
                    <address>
                        800 Boylston Street, #131<br/>
                        Boston, MA 02199<br/>
                        <a href="mailto:boston.pru@yogasmoga.com">boston.pru@yogasmoga.com</a><br/>
                        <a href="tel:8889909642">888 990 YOGA (9642)</a>
                    </address>
                </div>
                <p class="store_hours">
                    <span>Store Hours</span><br/>
                    Monday&ndash;Saturday 10am&ndash;9pm<br/>
                    Sunday 11am&ndash;8pm
                </p>
            </div>

           
          
            <div rel="malibu">
                <p class="title">YOGASMOGA MALIBU</p>

                <div>
                    <address>
                        3900 Cross Creek Rd, STE 3A<br/>
                        Maibu, CA 90265<br/>
                        <a href="mailto:malibu@yogasmoga.com">malibu@yogasmoga.com</a><br/>
                        <a href="tel:8889909642">888 990 YOGA (9642)</a>
                    </address>
                </div>
                <p class="store_hours">
                    <span>Store Hours</span><br/>
                    Monday&ndash;Saturday 10am&ndash;7pm<br/>
                    Sunday 11am&ndash;6pm
                </p>
            </div>
			 <div rel="san-francisco">
                <p class="title">YOGASMOGA <br/>SAN FRANCISCO</p>

                <div>
                    <address>
                        66 Kearny St<br/>
                        San Francisco, CA 94108<br/>
                        <a style="font-size: 18px;" href="mailto:sanfran.unionsquare@yogasmoga.com">sanfran.unionsquare@yogasmoga.com</a><br/>
                        <a href="tel:8889909642">888 990 YOGA (9642)</a>
                    </address>
                </div>
                <p class="store_hours">
                    <span>Store Hours</span><br/>
                    Monday–Saturday 10am&ndash;8pm<br/>
                        Sunday 11am&ndash;7pm
                </p>
            </div>
			  <div rel="la-jo-la-ca-holiday">
                <p class="title">YOGASMOGA LA JOLLA</p>

                <div>
                    <address>
                        7863 Girard Ave,#101<br/>
                        La Jolla, CA 92037<br/>
                        <a href="mailto:lajolla@yogasmoga.com">lajolla@yogasmoga.com</a><br/>
                        <a href="tel:8889909642">888 990 YOGA (9642)</a>
                    </address>
                </div>
                <p class="store_hours">
                    <span>Store Hours</span><br/>
                    Monday&ndash;Saturday 10am&ndash;7pm<br/>
                    Sunday 10am&ndash;6pm
                </p>
            </div>
			 <div rel="short-hills-new-jersy">
                <p class="title">YOGASMOGA X THE MALL <br/>AT SHORT HILLS</p>

                <div>
                    <address>
                        1200 Morris Tpke, #179<br/>
                        Short Hills, NJ 07078<br/>
                        <a href="mailto:shorthills@yogasmoga.com">shorthills@yogasmoga.com</a><br/>
                        <a href="tel:8889909642">888 990 YOGA (9642)</a>
                    </address>
                </div>

                <p class="store_hours">
                    <span>Store Hours</span><br/>
                    Monday&ndash;Saturday 10am&ndash;9pm<br/>
                    Sunday 11am&ndash;6pm
                </p>
            </div>
			 <div rel="westchester">
                <p class="title">YOGASMOGA <br/>AT THE WESTCHESTER</p>

                <div>
                    <address>
                        125 Westchester Ave, #3350<br/>
                        White Plains, NY 10601<br/>
                        <a href="mailto:westchester@yogasmoga.com">westchester@yogasmoga.com</a><br/>
                        <a href="tel:8889909642">888 990 YOGA (9642)</a>
                    </address>
                </div>

                <p class="store_hours">
                    <span>Store Hours</span><br/>
                    Monday&ndash;Saturday 10am&ndash;9pm<br/>
                    Sunday 11am&ndash;7pm
                </p>
            </div>
			            <div rel="corte-madera">
                <p class="title">YOGASMOGA X THE VILLAGE AT CORTE MADERA</p>

                <div>
                    <address>
                        1618 Redwood Hwy<br/>
                        Corte Madera, CA 94925<br/>
                        <a href="mailto:cortemadera@yogasmoga.com">cortemadera@yogasmoga.com</a><br/>
                        <a href="tel:8889909642">888 990 YOGA (9642)</a>
                    </address>
                </div>
                <p class="store_hours">
                    <span>Store Hours</span><br/>
                    Monday&ndash;Friday 10am&ndash;8pm<br/>
                    Saturday 10am&ndash;7pm<br/>
                    Sunday 11am&ndash;6pm
                </p>
            </div>
            <div rel="walnut-creek">
                <p class="title">YOGASMOGA <br/>AT WALNUT CREEK</p>

                <div>
                    <address>
                        1275 Broadway Plaza,#E04<br/>
                        Walnut Creek, CA 94925<br/>
                        <a href="mailto:walnutcreek@yogasmoga.com">walnutcreek@yogasmoga.com</a><br/>
                        <a href="tel:8889909642">888 990 YOGA (9642)</a>
                    </address>
                </div>
                <p class="store_hours">
                    <span>Store Hours</span><br/>
                    Monday&ndash;Friday 10am&ndash;9pm<br/>
                    Saturday 10am&ndash;7pm<br/>
                    Sunday 11am&ndash;6pm
                </p>
            </div>
        </div>
    </div>
</div>

<!-- page block end -------------------------------------------------------------------------------------------->


<div class="page_block" id="made_in_usa">
    <div class="block_thumbnail">
        <img src="<?php echo $this->getSkinUrl('images/madeinusa-2.jpg'); ?>" class="img-responsive"/>

        <div class="overlay-text">
            <p class="text" style="color: #666;">Learn More</p>
        </div>
    </div>
    <div class="block_content">
        <div class="slide_related_content">
            <div rel="made-in-usa-block1" style="padding-top: 16px;">
                <p style="margin-top: 0">
                    At YOGASMOGA, we understand that decisions we make as a company have serious consequences.
                </p>

                <p>
                    Made in USA is a lens that reflects our human values. values worth fighting for and something that
                    consumers appreciate and support.
                </p>

                <p>
                    We are a team based domestically in the United States that researches & develops it, designs it,
                    manufactures it, dyes it, cuts it, stitches it, packs it & ships it&mdash;so you can enjoy it.
                </p>

                <p>
                    Look closer, go deeper, consider the clothes you wear.
                </p>

                <p>
                    In life, sometimes it is as simple as the choices you make.
                </p>
            </div>
        </div>
    </div>

</div>

<!-- page block end -------------------------------------------------------------------------------------------->

<div class="page_block" id="principles_of_yoga">
    <div class="block_thumbnail">
        <img src="<?php echo $this->getSkinUrl('images/principles-of-yogas.jpg'); ?>" class="img-responsive"/>

        <div class="overlay-text">
            <p class="text">Learn More</p>
        </div>
    </div>
    <div class="block_content has_slider">
        <div class="flexslider">
            <div class="slides">
                <li>
                    <img src="<?php echo $this->getSkinUrl('images/our-story-slide1.jpg'); ?>" class="img-responsive"
                         rel="principles-of-yoga1"/>
                </li>
                <li>
                    <img src="<?php echo $this->getSkinUrl('images/principles-of-yoga-2.jpg'); ?>"
                         class="img-responsive"
                         rel="principles-of-yoga2"/>
                </li>
                <li>
                    <img src="<?php echo $this->getSkinUrl('images/principles-of-yoga-3.jpg'); ?>"
                         class="img-responsive"
                         rel="principles-of-yoga3"/>
                </li>
                <li>
                    <img src="<?php echo $this->getSkinUrl('images/principles-of-yoga-4.jpg'); ?>"
                         class="img-responsive"
                         rel="principles-of-yoga4"/>
                </li>
                <li>
                    <img src="<?php echo $this->getSkinUrl('images/principles-of-yoga-5.jpg'); ?>"
                         class="img-responsive"
                         rel="principles-of-yoga5"/>
                </li>
                <li>
                    <img src="<?php echo $this->getSkinUrl('images/principles-of-yoga-6.jpg'); ?>"
                         class="img-responsive"
                         rel="principles-of-yoga6"/>
                </li>
            </div>
        </div>
        <div class="slide_related_content">
            <div rel="principles-of-yoga1">
                <p class="title">RELAXED BODY AND MIND</p>

                <p>
                    Yoga helps in finding your internal center and thus the benefits of Yoga are wide spread. The Yoga
                    practice creates a more relaxed sense of self through internal silence, making the stresses of our
                    lives manageable. The effectiveness of Yoga lies in its simplicity and its ability to elicit a sense
                    of wholeness, balance and calm.
                </p>
            </div>
            <div rel="principles-of-yoga2">
                <p class="title">EXERCISE AND ELONGATION</p>

                <p>
                    Asanas are Yoga postures that restore your body&rsquo;s flexibility and vitality. Each Asana has
                    evolved
                    over thousands of years to strengthen and elongate the muscular system. The transitions from one
                    Asana to another are equally important as the Asana itself, requiring a concentration and technique
                    that is guaranteed to make you sweat.
                </p>
            </div>
            <div rel="principles-of-yoga3">
                <p class="title">CONSCIOUS BREATHING</p>

                <p>
                    Pranayama is the core principle of regulating your breath in your Yoga practice. &lsquo;Prana&rsquo;
                    means
                    breath + &lsquo;Ayama&rsquo; means to extend, leading to a set of breathing techniques that make you
                    deeply
                    aware and in control. This consciousness and awareness of our breathing is the core element to
                    sustain life.
                </p>
            </div>
            <div rel="principles-of-yoga4">
                <p class="title">BALANCED DIET</p>

                <p>
                    Our bodies are made out of five elements&mdash;air, space, fire, water and earth. The three body
                    types are a combination of these elements&mdash;Vata constitutes air and space&mdash;Pitta is made
                    up of fire and water&mdash;and Kapha is water and earth. When thinking about food we must take into
                    consideration not just taste, but suitability to each body type. Do you know what body type you are?
                </p>
            </div>
            <div rel="principles-of-yoga5">
                <p class="title">POSITIVE THINKING</p>

                <p>
                    Yoga focuses and sharpens your mind. This mental clarity promotes clear decision-making, develops
                    confidence and enhances self-image. The practice increases productivity and effectiveness in your
                    life.
                </p>
            </div>
            <div rel="principles-of-yoga6">
                <p class="title">MEDITATION AND FEELING GROUNDED</p>

                <p>
                    Embrace your inner peace and love. Yoga inspires creativity and imagination and helps develop a
                    deeper appreciation for life. Closing your eyes in meditation improves your patience and compassion.
                </p>
            </div>
        </div>

    </div>
</div>


<!-- page block end -------------------------------------------------------------------------------------------->

<div class="page_block" id="namaskar_foundation">
    <div class="block_thumbnail">
        <img src="<?php echo $this->getSkinUrl('images/namaskar-block.jpg'); ?>" class="img-responsive"/>

        <div class="overlay-text">
            <p class="text">Learn More</p>
        </div>
    </div>
    <div class="block_content" style="padding-top: 30px;">
        <p class="title">
            GIVING IS A CORE VALUE <br/>OF YOGASMOGA
        </p>

        <p class="sub-title-namaskar">
            We have Created the NAMASK&Aacute;R Foundation because We Care
        </p>

        <p>
            We recognize that textile production is typically done in the most economically challenged locations of the
            world. It is our absolute obligation and duty to give back. We welcome you to join us on this journey.
        </p>

        <p class="sub-title-namaskar">
            Joining hands to make a change.
        </p>
        <img src="<?php echo $this->getSkinUrl('images/namaskar1.jpg'); ?>" class="img-responsive"
            />

        <p class="title">
            THE NAMASK&Aacute;R FOUNDATION
        </p>

        <p class="sub-title">
            Raising The Funds
        </p>

        <p>
            YOGASMOGA has coordinated the manufacture and sales of hand woven bracelets that are being made on handlooms
            in remote villages of the Himalayas.
        </p>

        <p>
            These hand woven bracelets are sold by YOGASMOGA for &dollar;10 and Net Proceeds of all sales will be
            donated to the NAMASK&Aacute;R Foundation.
        </p>
        <img src="<?php echo $this->getSkinUrl('images/namaskar2-progressive.jpg'); ?>" class="img-responsive"/>
        <button onclick="window.location='/women/accessories/namaskar-bracelets/namaskar-bracelet'"
                class="add_bracelet">ADD BRACELET TO BAG
        </button>
        <p class="title">
            THE NAMASK&Aacute;R FOUNDATION
        </p>

        <p class="sub-title">
            Making Change in The World
        </p>

        <p>
            The NAMASK&Aacute;R Foundation focuses its energies on three equally important causes.
        </p>

        <p style="padding: 15px; margin: 0"></p>

        <div class="flexslider">
            <div class="slides">
                <li>
                    <img src="<?php echo $this->getSkinUrl('images/namaskar-block2.jpg'); ?>" class="img-responsive"
                         rel="namaskar-block1"/>
                </li>
                <li>
                    <img src="<?php echo $this->getSkinUrl('images/namaskar-block-4.jpg'); ?>" class="img-responsive"
                         rel="namaskar-block2"/>
                </li>
                <li>
                    <img src="<?php echo $this->getSkinUrl('images/namaskar-block5.jpg'); ?>" class="img-responsive"
                         rel="namaskar-block3"/>
                </li>
            </div>
        </div>
        <div class="slide_related_content">
            <div rel="namaskar-block1">
                <p class="title">1. HEALTH</p>

                <p>
                    In our travels to the developing world we have realized that people (especially women) lack even a
                    basic level of health care.
                </p>

                <p>
                    The NAMASK&Aacute;R Foundation seeks to provide basic health initiatives, immunization, care and
                    education around early child birth so that each child born has an opportunity to a successful future
                    that they deserve.
                </p>
                <img src="<?php echo $this->getSkinUrl('images/namaskar6.jpg'); ?>" class="img-responsive"
                    />

                <p class="title">
                    NAMASK&Aacute;R&mdash;The Meaning
                </p>

                <p>
                    While many are familiar with the greeting&mdash;Namast&eacute;&mdash;fewer in the west are familiar
                    with the
                    traditional Indian greeting&mdash;NAMASK&Aacute;R. More respectful than Namast&eacute;, it is not
                    simply a
                    greeting but a profound philosophy of shunning arrogance and negating one&rsquo;s ego.
                </p>

                <p>
                    The gesture, NAMASK&Aacute;R, represents the belief that there is a divine spark within each of us
                    that is located in the heart chakra. This gesture is an acknowledgement of the soul in one&mdash;by
                    the
                    soul in another.
                </p>

                <p>
                    We join our hands together to recognize each other&rsquo;s soul, aiming to connect and honor each
                    other.
                </p>
                <img src="<?php echo $this->getSkinUrl('images/namaskar-block-3.jpg'); ?>" class="img-responsive"/>

                <p class="title">
                    SUPPORT NAMASK&Aacute;R
                </p>

                <p>
                    We bring the NAMASK&Aacute;R bracelet to you as a traditional symbol of the deep Yoga culture that
                    connects two people&mdash;our SMOGIs and the weavers of the Himalayas.
                </p>

                <p>
                    The weavers (mostly women) have lost much of their business to machine manufacturing and today we
                    give you an opportunity to connect directly with these hard working people so you can help them
                    attain the means they need to continue their craft, while you proudly wear a hand made (and
                    beautiful) NAMASK&Aacute;R bracelet.
                </p>

            </div>
            <div rel="namaskar-block2">
                <p class="title">2. EDUCATION</p>

                <p>
                    Education is the foundation of well-being.
                </p>

                <p>
                    The NAMASK&Aacute;R Foundation seeks to provide education that gives children and young adults a
                    chance to grow into productive, fulfilled adults. NAMASK&Aacute;R intends to develop education
                    programs, including work with existing education based charities.
                </p>
            </div>
            <div rel="namaskar-block3">
                <p class="title">3. MICROLENDING</p>

                <p>
                    The NAMASK&Aacute;R Foundation seeks to provide micro loans ($10 - $50) to individuals in developing
                    economies who have no access to banks. These micro loans provide an opportunity to individuals to
                    jump-start small cottage industries that over time generate income.
                </p>

                <p>
                    One of the very first micro lending projects that NAMASK&Aacute;R is working on is setting up
                    handlooms for women in the remote villages of the Himalayas so that these women can earn a living
                    producing NAMASK&Aacute;R bracelets.
                </p>
            </div>
        </div>

    </div>
</div>


<!-- page block end -------------------------------------------------------------------------------------------->


<div class="page_block" id="press">
    <div class="block_thumbnail">
        <img src="<?php echo $this->getSkinUrl('images/press.jpg'); ?>" class="img-responsive"/>

        <div class="overlay-text">
            <p class="text">Learn More</p>
        </div>
    </div>
    <div class="block_content has_slider">
        <div class="flexslider">
            <div class="slides">
                <li>
                    <a href="http://bostinno.streetwise.co/2015/11/06/boston-yoga-yogasmoga-apparel-opens-in-the-pru-november-16/"
                       target="_blank"><img src="<?php echo Mage::getBaseUrl('media').'wysiwyg/mobile/presspage/press-bostinno.jpg'; ?>"
                                            class="img-responsive"/></a>
                </li>
                <li>
                    <a href="http://www.bizjournals.com/newyork/news/2015/07/02/yogasmoga-assumes-warrior-pose-vs-lululemon-others.html?ana=twt"
                       target="_blank"><img src="<?php echo $this->getSkinUrl('images/press-upstart.jpg'); ?>"
                                            class="img-responsive"/></a>
                </li>
                <li>
                    <a href="http://www.bloomberg.com/news/articles/2015-04-27/yoga-wars-what-a-lululemon-challenger-from-goldman-sachs-means-for-retail"
                       target="_blank"><img src="<?php echo $this->getSkinUrl('images/press-bloomberg1.jpg'); ?>"
                                            class="img-responsive"/></a>
                </li>
                <li>
                    <a href="http://www.businessinsider.com/yogasmoga-raises-65-million-at-a-74-million-valuation-2015-4"
                       target="_blank"><img src="<?php echo $this->getSkinUrl('images/press-business-insider.jpg'); ?>"
                                            class="img-responsive"/></a>
                </li>
                <li>
                    <a href="http://wellandgood.com/2015/03/29/yogasmoga-activewear-become-the-next-lululemon/"
                       target="_blank"><img src="<?php echo $this->getSkinUrl('images/press-wellgood.jpg'); ?>"
                                            class="img-responsive"/></a>
                </li>
                <li>
                    <a href="http://www.cnbc.com/2015/02/17/starting-a-business-that-runs-in-their-blood.html"
                       target="_blank"><img src="<?php echo $this->getSkinUrl('images/press-cnbc.jpg'); ?>"
                                            class="img-responsive"/></a>
                </li>
                <li>
                    <a href="https://www.yahoo.com/?err=404&err_url=http%3a%2f%2ffinance.yahoo.com%2fnews%2fyogasmoga-releases-proprietary-fabric-technology-141700438.html%3b_ylt%3dAwrBJR6RiPJT1W4A9AyTmYlQ"
                       target="_blank"><img src="<?php echo $this->getSkinUrl('images/press-yahoo.jpg'); ?>"
                                            class="img-responsive"/></a>
                </li>
                <li>
                    <a href="http://upstart.bizjournals.com/resources/executive-forum/2014/07/03/why-an-india-born-entrepreneur-sells-made-in-the.html?page=all"
                       target="_blank"><img src="<?php echo $this->getSkinUrl('images/press-upstart2.jpg'); ?>"
                                            class="img-responsive"/></a>
                </li>
                <li>
                    <a href="http://greenwichfreepress.com/tag/yogasmoga/" target="_blank"><img
                            src="<?php echo $this->getSkinUrl('images/press-greenwich-free.jpg'); ?>"
                            class="img-responsive"/></a>
                </li>
                <li>
                    <a href="https://www.yahoo.com/?err=404&err_url=http%3a%2f%2ffinance.yahoo.com%2fnews%2fyogasmoga-announces-growth-physical-retail-150000281.html"
                       target="_blank"><img src="<?php echo $this->getSkinUrl('images/press-yahoo2.jpg'); ?>"
                                            class="img-responsive"/></a>
                </li>
                <li>
                    <a href="http://wellandgood.com/2014/05/14/yoga-pants-not-just-for-women/" target="_blank"><img
                            src="<?php echo $this->getSkinUrl('images/press-wellgood2.jpg'); ?>"
                            class="img-responsive"/></a>
                </li>
                <li>
                    <a href="http://www.bloomberg.com/news/videos/b/ff5d8da1-44b8-48bd-8a3b-e690334b67a6"
                       target="_blank"><img src="<?php echo $this->getSkinUrl('images/press-bloomberg2.jpg'); ?>"
                                            class="img-responsive"/></a>
                </li>
                <li>
                    <a href="http://www.self.com/flash/fitness-blog/2014/03/fitness-yoga-smoga/" target="_blank"><img
                            src="<?php echo $this->getSkinUrl('images/press-self.jpg'); ?>"
                            class="img-responsive"/></a>
                </li>
                <li>
                    <a href="http://wellandgood.com/2013/10/21/the-ultimate-guide-to-yoga-pants/" target="_blank"><img
                            src="<?php echo $this->getSkinUrl('images/press-wellgood3.jpg'); ?>"
                            class="img-responsive"/></a>
                </li>
                <li>
                    <a href="http://q.equinox.com/articles/2013/02/yogasmoga" target="_blank"><img
                            src="<?php echo $this->getSkinUrl('images/press-equinox.jpg'); ?>"
                            class="img-responsive"/></a>
                </li>
                <li>
                    <a href="http://wellandgood.com/2013/02/14/a-hot-new-yoga-fashion-brand-launches-with-indian-roots-and-modern-flair/"
                       target="_blank"><img src="<?php echo $this->getSkinUrl('images/press-wellgood4.jpg'); ?>"
                                            class="img-responsive"/></a>
                </li>
                <li>
                    <a href="http://www.theblogstudio.com/2013/04/1604/" target="_blank"><img
                            src="<?php echo $this->getSkinUrl('images/press-blog-studio.jpg'); ?>"
                            class="img-responsive"/></a>
                </li>
            </div>
        </div>

    </div>
</div>


<style>
    .page_block, .slide_related_content {
        float: left;
        width: 100%;
    }

    .block_thumbnail {
        position: relative;
        line-height: 0;
    }

    .overlay-text {
        bottom: 20px;
        color: #fff;
        font: 16px freighttextbook;
        left: 0;
        letter-spacing: 1px;
        position: absolute;
        width: 100%;
    }

    .overlay-text .text::after {
        content: " >";
        color: #B8153E;
    }

    .block_content {
        padding: 14px 14px 30px;
        float: left;
        text-align: left;
        width: 100%;
        display: none;
    }

    .account-nav.l-align.ys_static_page_dropdown {
        display: none;
    }

    .slide_related_content > div {
        display: none;
        float: left;
        padding: 30px 0 20px;
        width: 100%;
        text-align: left;
    }

    .block_content p {
        font: 18px/1.65em freighttextbook;
        letter-spacing: normal;
        margin: 20px 0 0;
    }

    .slide_related_content > div address {
        font: 18px/1.65em freighttextbook;
        margin: 20px 0 20px;
    }

    .slide_related_content > div p.store_hours {
        font: 12px/18px GraphikRegular;
    }

    .slide_related_content > div p.store_hours span {
        font: 12px/18px Graphik-Semibold;
    }

    .block_content p.title {
        font: 19px/21px ITCAvantGardeStd-Bk;
        margin: 0;
        letter-spacing: 1px;
    }

    .block_content p.sub-title {
        font: 19px/21px freighttextbookitalic;
        margin: 0;
        letter-spacing: 1px;
    }

    .block_content p.sub-title-namaskar {
        font: 19px/21px freighttextbookitalic;
        letter-spacing: 1px;
    }

    .slide_related_content div:first-child {
        display: block;
    }

    .add_bracelet {
        background: #00b900;
        border: none;
        color: #fff;
        font: 14px/50px ITCAvantGardeStd-Bk;
        height: 44px;
        margin: 10px 0 25px;
        letter-spacing: 1px;
        width: 100%;
    }

    .block_content > div > div p:last-child {
        margin-bottom: 0;
    }

    .block_content > div > div {
        padding-bottom: 0;
    }

    .block_thumbnail .close-icn {
        height: 44px;
        position: fixed;
        right: 0;
        top: 88px;
        width: 44px;
        display: none;
        z-index: 5;
    }

    .block_content img {
        margin: 30px 0;
    }

    .flexslider img {
        margin: 0 !important;
    }
</style>
<script type="text/javascript">
    jQuery(document).ready(function ($) {
        $(".sign-in-box h1").html("YS STORY");
        $(".flexslider").flexslider({
            slideshow: false,
            after: function (slider) {
                slideContent(slider);
            }
        });

        var closebtnHtml = '<span class="close-icn"><svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="44px" height="44px" viewBox="0 0 44 44" enable-background="new 0 0 44 44" xml:space="preserve"><g><rect fill="#555555" width="44" height="44"/><line fill="none" stroke="#FFFFFF" stroke-miterlimit="10" x1="14" y1="14" x2="30" y2="30"/><line fill="none" stroke="#FFFFFF" stroke-miterlimit="10" x1="30" y1="14" x2="14" y2="30"/></g></svg></span>';
        $(".page_block .block_thumbnail").append(closebtnHtml);
        $(".page_block .block_thumbnail .close-icn").bind("click", function (e) {
            var obj = $(this);
            e.stopPropagation();
            obj.fadeOut();
            obj.parent().parent().find(".block_content").hide();
            $(".page_block .block_thumbnail .overlay-text .text").show();
        });

    });
    function slideContent(slider) {
        var current_slide = slider.currentSlide + 1;
        var rel_value = slider.find(".slides li:nth-child(" + current_slide + ") img").attr("rel");
        slider.next().children("div").hide();
        if (rel_value != undefined) {
            slider.next().children("div[rel=" + rel_value + "]").fadeIn();
            slider.next().css("min-height", slider.next().children("div[rel=" + rel_value + "]").height());
        }
    }


</script>
