<div class="ys-bottom">
    <div class="account-nav l-align ys_static_page_dropdown">
        <ul class="sub-nav">
            <li><a href="/our-story" data-heading="YS STORY" rel="our_story">Our Story</a></li>
            <li><a href="/our-core-values" data-heading="YS CORE VALUES" rel="our_core_values">Our Core Values</a></li>
            <li><a href="/our-ethics" data-heading="YS ETHICS" rel="our_core_ethics">Our Ethics</a></li>

            <li><a href="/our-stores" data-heading="YS STORES" rel="our_stores">Our Stores</a></li>
            <li><a href="/made-in-usa" data-heading="MADE IN USA" rel="made_in_usa">Made in USA</a></li>
            <li><a href="/principles-of-yoga" data-heading="YOGA PRINCIPLES" rel="principles_of_yoga">Principles of
                    Yoga</a></li>
            <li><a href="/namaskar" data-heading="NAMASK&aacute;R" rel="namaskar_foundation">NAMASK&aacute;R
                    Foundation</a></li>
            <li><a href="/press" data-heading="PRESS" rel="press">Press</a></li>


        </ul>

    </div>

</div>







<div class="page_block" rel="press">
    <div class="block_thumbnail">
        <img src="<?php echo $this->getSkinUrl('images/press.jpg'); ?>" class="img-responsive"/>

        <div class="overlay-text">
<!--            <p class="text">Learn More</p>-->
        </div>
    </div>
    <div style="display:block;" class="block_content has_slider">
        <div class="flexslider">
            <div class="slides">
                <li>
                    <a href="http://www.bizjournals.com/newyork/news/2015/07/02/yogasmoga-assumes-warrior-pose-vs-lululemon-others.html?ana=twt" target="_blank"><img src="<?php echo Mage::getBaseUrl('media').'wysiwyg/mobile/presspage/press-upstart.jpg'; ?>" class="img-responsive"/></a>
                </li>
                <li>
                    <a href="http://www.bloomberg.com/news/articles/2015-04-27/yoga-wars-what-a-lululemon-challenger-from-goldman-sachs-means-for-retail" target="_blank"><img src="<?php echo Mage::getBaseUrl('media').'wysiwyg/mobile/presspage/press-bloomberg1.jpg'; ?>"
                                                                                                                                                                               class="img-responsive"/></a>
                </li>
                <li>
                    <a href="http://www.businessinsider.com/yogasmoga-raises-65-million-at-a-74-million-valuation-2015-4" target="_blank"><img src="<?php echo Mage::getBaseUrl('media').'wysiwyg/mobile/presspage/press-business-insider.jpg'; ?>"
                                                                                                                                               class="img-responsive"/></a>
                </li>
                <li>
                    <a href="http://wellandgood.com/2015/03/29/yogasmoga-activewear-become-the-next-lululemon/" target="_blank"><img src="<?php echo Mage::getBaseUrl('media').'wysiwyg/mobile/presspage/press-wellgood.jpg'; ?>" class="img-responsive"/></a>
                </li>
                <li>
                    <a href="http://www.cnbc.com/2015/02/17/starting-a-business-that-runs-in-their-blood.html" target="_blank"><img src="<?php echo Mage::getBaseUrl('media').'wysiwyg/mobile/presspage/press-cnbc.jpg'; ?>"
                                                                                                                                    class="img-responsive"/></a>
                </li>
                <li>
                    <a href="https://www.yahoo.com/?err=404&err_url=http%3a%2f%2ffinance.yahoo.com%2fnews%2fyogasmoga-releases-proprietary-fabric-technology-141700438.html%3b_ylt%3dAwrBJR6RiPJT1W4A9AyTmYlQ" target="_blank"><img src="<?php echo Mage::getBaseUrl('media').'wysiwyg/mobile/presspage/press-yahoo.jpg'; ?>"
                                                                                                                                                                                                                                    class="img-responsive"/></a>
                </li>
				
				<li>
                    <a href="http://www.huffingtonpost.com/laura-dunn/women-in-business-qa-tapa_b_8060760.html?ir=India&adsSiteOverride=in&m=true" target="_blank"><img src="<?php echo Mage::getBaseUrl('media').'wysiwyg/mobile/presspage/press-huffington-post.jpg'; ?>" class="img-responsive"/></a>
                </li>
				
                <li>
                    <a href="http://upstart.bizjournals.com/resources/executive-forum/2014/07/03/why-an-india-born-entrepreneur-sells-made-in-the.html?page=all" target="_blank"><img src="<?php echo Mage::getBaseUrl('media').'wysiwyg/mobile/presspage/press-upstart2.jpg'; ?>" class="img-responsive"/></a>
                </li>
                <li>
                    <a href="http://greenwichfreepress.com/tag/yogasmoga/" target="_blank"><img src="<?php echo Mage::getBaseUrl('media').'wysiwyg/mobile/presspage/press-greenwich-free.jpg'; ?>"
                                                                                                class="img-responsive"/></a>
                </li>
                <li>
                    <a href="https://www.yahoo.com/?err=404&err_url=http%3a%2f%2ffinance.yahoo.com%2fnews%2fyogasmoga-announces-growth-physical-retail-150000281.html" target="_blank"><img src="<?php echo Mage::getBaseUrl('media').'wysiwyg/mobile/presspage/press-yahoo2.jpg'; ?>"
                                                                                                                                                                                            class="img-responsive"/></a>
                </li>
                <li>
                    <a href="http://wellandgood.com/2014/05/14/yoga-pants-not-just-for-women/" target="_blank"><img src="<?php echo Mage::getBaseUrl('media').'wysiwyg/mobile/presspage/press-wellgood2.jpg'; ?>" class="img-responsive"/></a>
                </li>
                <li>
                    <a href="http://www.bloomberg.com/news/videos/b/ff5d8da1-44b8-48bd-8a3b-e690334b67a6" target="_blank"><img src="<?php echo Mage::getBaseUrl('media').'wysiwyg/mobile/presspage/press-bloomberg2.jpg'; ?>"
                                                                                                                               class="img-responsive"/></a>
                </li>
                <li>
                    <a href="http://www.self.com/flash/fitness-blog/2014/03/fitness-yoga-smoga/" target="_blank"><img src="<?php echo Mage::getBaseUrl('media').'wysiwyg/mobile/presspage/press-self.jpg'; ?>"
                                                                                                                      class="img-responsive"/></a>
                </li>
                <li>
                    <a href="http://wellandgood.com/2013/10/21/the-ultimate-guide-to-yoga-pants/" target="_blank"><img src="<?php echo Mage::getBaseUrl('media').'wysiwyg/mobile/presspage/press-wellgood3.jpg'; ?>" class="img-responsive"/></a>
                </li>
                <li>
                    <a href="http://q.equinox.com/articles/2013/02/yogasmoga" target="_blank"><img src="<?php echo Mage::getBaseUrl('media').'wysiwyg/mobile/presspage/press-equinox.jpg'; ?>"
                                                                                                   class="img-responsive"/></a>
                </li>
                <li>
                    <a href="http://wellandgood.com/2013/02/14/a-hot-new-yoga-fashion-brand-launches-with-indian-roots-and-modern-flair/" target="_blank"><img src="<?php echo Mage::getBaseUrl('media').'wysiwyg/mobile/presspage/press-wellgood4.jpg'; ?>"
                                                                                                                                                               class="img-responsive"/></a>
                </li>
                <li>
                    <a href="http://www.theblogstudio.com/2013/04/1604/" target="_blank"><img src="<?php echo Mage::getBaseUrl('media').'wysiwyg/mobile/presspage/press-blog-studio.jpg'; ?>" class="img-responsive"/></a>
                </li>
            </div>
        </div>

    </div>
</div>

<style>
    .page_block, .slide_related_content {
        float: left;
        width: 100%;
    }

    .block_thumbnail {
        position: relative;
        line-height: 0;
    }

    .overlay-text {
        bottom: 20px;
        color: #fff;
        font: 16px freighttextmedium;
        left: 0;
        letter-spacing: 1px;
        position: absolute;
        width: 100%;
    }

    .overlay-text .text::after {
        content: ">";
        color: #B8153E;
    }

    .block_content {
        padding: 14px 14px 30px;
        float: left;
        text-align: left;
        width: 100%;
        display: none;
    }

    .account-nav.l-align.ys_static_page_dropdown {
        display: none;
    }

    .slide_related_content > div {
        display: none;
        float: left;
        padding: 30px 0 20px;
        width: 100%;
        text-align: left;
    }

    .block_content p {
        font: 18px/1.65em freighttextbook;
        letter-spacing: normal;
        margin: 20px 0 0;
    }

    .slide_related_content > div address {
        font: 18px/1.65em freighttextbook;
        margin: 20px 0 20px;
    }

    .slide_related_content > div p.store_hours {
        font: 12px/18px GraphikRegular;
    }

    .slide_related_content > div p.store_hours span {
        font: 12px/18px Graphik-Semibold;
    }

    .block_content p.title {
        font: 19px/21px ITCAvantGardeStd-Bk;
        margin: 0;
        letter-spacing: 1px;
    }

    .block_content p.sub-title {
        font: 19px/21px freighttextbookitalic;
        margin: 0;
        letter-spacing: 1px;
    }

    .block_content p.sub-title-namaskar {
        font: 19px/21px freighttextbookitalic;
        letter-spacing: 1px;
    }

    .slide_related_content div:first-child {
        display: block;
    }

    .add_bracelet {
        background: #00b900;
        border: none;
        color: #fff;
        font: 14px ITCAvantGardeStd-Bk;
        height: 44px;
        margin: 10px 0 25px;
        letter-spacing: 1px;
        width: 100%;
    }

    .block_content > div > div p:last-child {
        margin-bottom: 0;
    }

    .block_content > div > div {
        padding-bottom: 0;
    }

    .block_thumbnail .close-icn {
        height: 44px;
        position: fixed;
        right: 0;
        top: 88px;
        width: 44px;
        display: none;
        z-index: 5;
    }

    .block_content img {
        margin: 30px 0;
    }

    .flexslider img {
        margin: 0 !important;
    }
</style>
<script type="text/javascript">
    jQuery(document).ready(function ($) {
        $(".sign-in-box h1").html("PRESS");
        $(".flexslider").flexslider({
            after: function (slider) {
                slideContent(slider);
            }
        });

        var closebtnHtml = '<span class="close-icn" style="display:block;"><svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="44px" height="44px" viewBox="0 0 44 44" enable-background="new 0 0 44 44" xml:space="preserve"><g><rect fill="#555555" width="44" height="44"/><line fill="none" stroke="#FFFFFF" stroke-miterlimit="10" x1="14" y1="14" x2="30" y2="30"/><line fill="none" stroke="#FFFFFF" stroke-miterlimit="10" x1="30" y1="14" x2="14" y2="30"/></g></svg></span>';
        $(".page_block .block_thumbnail").append(closebtnHtml);
        $(".page_block .block_thumbnail .close-icn").bind("click", function (e) {
            window.location.href = '/';
        });

    });
    function slideContent(slider) {
        var current_slide = slider.currentSlide + 1;
        var rel_value = slider.find(".slides li:nth-child(" + current_slide + ") img").attr("rel");
        slider.next().children("div").hide();
        if(rel_value!= undefined){
            slider.next().children("div[rel=" + rel_value + "]").fadeIn();
            slider.next().css("min-height", slider.next().children("div[rel=" + rel_value + "]").height());
        }
    }


</script>
