<div class="ys-bottom">
    <div class="account-nav l-align ys_static_page_dropdown">
        <ul class="sub-nav">
            <li><a href="/our-story" data-heading="YS STORY" rel="our_story">Our Story</a></li>
            <li><a href="/our-core-values" data-heading="YS CORE VALUES" rel="our_core_values">Our Core Values</a></li>
            <li><a href="/our-ethics" data-heading="YS ETHICS" rel="our_core_ethics">Our Ethics</a></li>

            <li><a href="/our-stores" data-heading="YS STORES" rel="our_stores">Our Stores</a></li>
            <li><a href="/made-in-usa" data-heading="MADE IN USA" rel="made_in_usa">Made in USA</a></li>
            <li><a href="/principles-of-yoga" data-heading="YOGA PRINCIPLES" rel="principles_of_yoga">Principles of
                    Yoga</a></li>
            <li><a href="/namaskar" data-heading="NAMASK&aacute;R" rel="namaskar_foundation">NAMASK&aacute;R
                    Foundation</a></li>
            <li><a href="/press" data-heading="PRESS" rel="press">Press</a></li>


        </ul>

    </div>

</div>




<div class="page_block" rel="yogas_principles">
    <div class="block_thumbnail">
        <img src="<?php echo $this->getSkinUrl('images/principles-of-yogas.jpg'); ?>" class="img-responsive"/>

        <div class="overlay-text">
<!--            <p class="text">Learn More</p>-->
        </div>
    </div>
    <div style="display:block;" class="block_content has_slider">
        <div class="flexslider">
            <div class="slides">
                <li>
                    <img src="<?php echo $this->getSkinUrl('images/our-story-slide1.jpg'); ?>" class="img-responsive"
                         rel="principles-of-yoga1"/>
                </li>
                <li>
                    <img src="<?php echo $this->getSkinUrl('images/principles-of-yoga-2.jpg'); ?>"
                         class="img-responsive"
                         rel="principles-of-yoga2"/>
                </li>
                <li>
                    <img src="<?php echo $this->getSkinUrl('images/principles-of-yoga-3.jpg'); ?>"
                         class="img-responsive"
                         rel="principles-of-yoga3"/>
                </li>
                <li>
                    <img src="<?php echo $this->getSkinUrl('images/principles-of-yoga-4.jpg'); ?>"
                         class="img-responsive"
                         rel="principles-of-yoga4"/>
                </li>
                <li>
                    <img src="<?php echo $this->getSkinUrl('images/principles-of-yoga-5.jpg'); ?>"
                         class="img-responsive"
                         rel="principles-of-yoga5"/>
                </li>
                <li>
                    <img src="<?php echo $this->getSkinUrl('images/principles-of-yoga-6.jpg'); ?>"
                         class="img-responsive"
                         rel="principles-of-yoga6"/>
                </li>
            </div>
        </div>
        <div class="slide_related_content">
            <div rel="principles-of-yoga1">
                <p class="title">RELAXED BODY AND MIND</p>

                <p>
                    Yoga helps in finding your internal center and thus the benefits of Yoga are wide spread. The Yoga
                    practice creates a more relaxed sense of self through internal silence, making the stresses of our
                    lives manageable. The effectiveness of Yoga lies in its simplicity and its ability to elicit a sense
                    of wholeness, balance and calm.
                </p>
            </div>
            <div rel="principles-of-yoga2">
                <p class="title">EXERCISE AND ELONGATION</p>

                <p>
                    Asanas are Yoga postures that restore your body's flexibility and vitality. Each Asana has evolved
                    over thousands of years to strengthen and elongate the muscular system. The transitions from one
                    Asana to another are equally important as the Asana itself, requiring a concentration and technique
                    that is guaranteed to make you sweat.
                </p>
            </div>
            <div rel="principles-of-yoga3">
                <p class="title">CONSCIOUS BREATHING</p>

                <p>
                    Pranayama is the core principle of regulating your breath in your Yoga practice. 'Prana' means
                    breath + 'Ayama' means to extend, leading to a set of breathing techniques that make you deeply
                    aware and in control. This consciousness and awareness of our breathing is the core element to
                    sustain life.
                </p>
            </div>
            <div rel="principles-of-yoga4">
                <p class="title">BALANCED DIET</p>

                <p>
                    Our bodies are made out of five elements&mdash;air, space, fire, water and earth. The three body
                    types are a combination of these elements&mdash; Vata constitutes air and space&mdash;Pitta is made
                    up of fire and water&mdash;and Kapha is water and earth. When thinking about food we must take into
                    consideration not just taste, but suitability to each body type. Do you know what body type you are?
                </p>
            </div>
            <div rel="principles-of-yoga5">
                <p class="title">POSITIVE THINKING</p>

                <p>
                    Yoga focuses and sharpens your mind. This mental clarity promotes clear decision-making, develops
                    confidence and enhances self-image. The practice increases productivity and effectiveness in your
                    life.
                </p>
            </div>
            <div rel="principles-of-yoga6">
                <p class="title">MEDITATION AND FEELING GROUNDED</p>

                <p>
                    Embrace your inner peace and love. Yoga inspires creativity and imagination and helps develop a
                    deeper appreciation for life. Closing your eyes in meditation improves your patience and compassion.
                </p>
            </div>
        </div>

    </div>
</div>


<style>
    .page_block, .slide_related_content {
        float: left;
        width: 100%;
    }

    .block_thumbnail {
        position: relative;
        line-height: 0;
    }

    .overlay-text {
        bottom: 20px;
        color: #fff;
        font: 16px freighttextmedium;
        left: 0;
        letter-spacing: 1px;
        position: absolute;
        width: 100%;
    }

    .overlay-text .text::after {
        content: ">";
        color: #B8153E;
    }

    .block_content {
        padding: 14px 14px 30px;
        float: left;
        text-align: left;
        width: 100%;
        display: none;
    }

    .account-nav.l-align.ys_static_page_dropdown {
        display: none;
    }

    .slide_related_content > div {
        display: none;
        float: left;
        padding: 30px 0 20px;
        width: 100%;
        text-align: left;
    }

    .block_content p {
        font: 18px/1.65em freighttextbook;
        letter-spacing: normal;
        margin: 20px 0 0;
    }

    .slide_related_content > div address {
        font: 18px/1.65em freighttextbook;
        margin: 20px 0 20px;
    }

    .slide_related_content > div p.store_hours {
        font: 15px/22px GraphikRegular;
    }

    .slide_related_content > div p.store_hours span {
        font: 15px/22px Graphik-Semibold;
    }

    .block_content p.title {
        font: 19px/21px ITCAvantGardeStd-Bk;
        margin: 0;
        letter-spacing: 1px;
    }

    .block_content p.sub-title {
        font: 19px/21px freighttextbookitalic;
        margin: 0;
        letter-spacing: 1px;
    }

    .block_content p.sub-title-namaskar {
        font: 18px/1.65em freighttextbookitalic;
        letter-spacing: 1px;
    }

    .slide_related_content div:first-child {
        display: block;
    }

    .add_bracelet {
        background: #00b900;
        border: none;
        color: #fff;
        font: 14px ITCAvantGardeStd-Bk;
        height: 44px;
        margin: 10px 0 25px;
        letter-spacing: 1px;
        width: 100%;
    }

    .block_content > div > div p:last-child {
        margin-bottom: 0;
    }

    .block_content > div > div {
        padding-bottom: 0;
    }

    .block_thumbnail .close-icn {
        height: 44px;
        position: fixed;
        right: 0;
        top: 88px;
        width: 44px;
        display: none;
        z-index: 5;
    }

    .block_content img {
        margin: 30px 0;
    }

    .flexslider img {
        margin: 0 !important;
    }
</style>
<script type="text/javascript">
    jQuery(document).ready(function ($) {
        $(".sign-in-box h1").html("PRINCIPLES OF YOGA");
        $(".flexslider").flexslider({
            after: function (slider) {
                slideContent(slider);
            }
        });


        var closebtnHtml = '<span class="close-icn" style="display:block;"><svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="44px" height="44px" viewBox="0 0 44 44" enable-background="new 0 0 44 44" xml:space="preserve"><g><rect fill="#555555" width="44" height="44"/><line fill="none" stroke="#FFFFFF" stroke-miterlimit="10" x1="14" y1="14" x2="30" y2="30"/><line fill="none" stroke="#FFFFFF" stroke-miterlimit="10" x1="30" y1="14" x2="14" y2="30"/></g></svg></span>';
        $(".page_block .block_thumbnail").append(closebtnHtml);
        $(".page_block .block_thumbnail .close-icn").bind("click", function (e) {
            window.location.href = '/';
        });

    });
    function slideContent(slider) {
        var current_slide = slider.currentSlide + 1;
        var rel_value = slider.find(".slides li:nth-child(" + current_slide + ") img").attr("rel");
        slider.next().children("div").hide();
        if(rel_value!= undefined){
            slider.next().children("div[rel=" + rel_value + "]").fadeIn();
            slider.next().css("min-height", slider.next().children("div[rel=" + rel_value + "]").height());
        }
    }


</script>
