<div class="ys-bottom">


    <div class="account-nav l-align" style="display:none;">
        <div id="linkwrapper">
            <ul class="sub-nav">
                <li><a rel="link1content" href="#">What is Smogi Bucks?</a></li>
                <li><a rel="link2content" href="#">Earn More Smogi Bucks</a></li>



            </ul>
        </div>

    </div>


    <div style="margin-bottom:0;" id="link1content">

        <div class="story-box smogi-box" style="line-height:0;">
            <a href="#">
                <img style="margin-top:0;" alt="made in usa" src="<?php echo $this->getSkinUrl('images/smogi-1-progressive.jpg'); ?>" class="img-responsive">

                <!--   <span class="ovr-text">WHAT IS<br> SMOGI BUCKS?</span>-->
            </a>

        </div>
        <div  class="smogi-content">
            <p style="padding:25px 0px;"> SMOGI Bucks is SMOGI Love we give back to you for being part of our family.You get SMOGI bucks every
                time you shop with us. It's our way of saying THANK YOU. <br><br>

                And in case you're wondering about the exchange rate, it's pretty simple:</span></p>

            <img alt="made in usa"  src="<?php echo $this->getSkinUrl('images/smogi-2-progressive.jpg'); ?>"
                 class="img-responsive hidden-txt">
            <div class="earn-buck" id="link2content">
                <span class="earn-smogi-title">EARN MORE SMOGI BUCKS</span>

                <img alt="made in usa" src="<?php echo $this->getSkinUrl('images/smogi-3-progressive.jpg'); ?>" class="img-responsive">

                <div style="padding:0;" class="smogi-content">
                    <p style="padding:25px 0 30px;"> It's quite easy-Go Shopping!
                        For every dollar you spend, you earn SMOGI Bucks. <br><br>
                        When you are ready to checkout, you will be given the option to use your SMOGI Bucks toward the
                        final
                        purchase.</p>


                    </span>


                </div>
                <div class="clearfix"></div>
                <div style="padding:0;" class="smogi-content exception">
                    <span>EXCEPTIONS</span>
                    <ul>
                        <li>
                            <p>
                                When you use SMOGI Bucks on an order,
                                you will not earn additional SMOGI Bucks.
                            </p>
                        </li>
                        <li>
                            <p>
                                SMOGI Bucks cannot be applied toward or acquired with Accessories and One 2 Many items.
                            </p>
                        </li>
                    </ul>

                </div>

            </div>

        </div>



    </div>




    <!-----------------------------Earn buck ends -------------------------------------->



</div>


</div>
<style>
    .smogi-content p{color:#545454!important;}
    .exception span{font: 12px/15px Avantgarde-Demi; letter-spacing: 0.1em;}
    .exception p{font: 14px/20px GraphikRegular;padding:22px 0 35px;}
    .earn-smogi-title{
        color: #545454;
        float: left;
        letter-spacing: 0.1em;
        font: 12px/15px Avantgarde-Demi;
        padding: 30px 0px;
    }
    .smogi-content > img.img-responsive{margin-top:0;}
    .smogi-content{line-height:0;padding: 0 12px;}

    .smogi-content.exception li {
        padding: 22px 0 0;
        font: 14px/20px GraphikRegular;
        list-style: decimal;
    }
    .smogi-content.exception>ul li:last-child {
        padding: 22px 0 35px;
        font: 14px/20px GraphikRegular;
        list-style: decimal;
    }
    .smogi-content.exception li p {
        padding: 0 !important;
    }
    .smogi-content.exception > ul {
        padding-left: 14px;
    }
</style>
<script type="text/javascript">
    jQuery(document).ready(function($){
        $(".sign-in-box h1").html("SMOGI BUCKS");
    })
</script>
