<div class="ys-bottom">


    <div class="account-nav l-align ys_static_page_dropdown" style="display: none;">
        <ul class="sub-nav">
            <li><a data-heading="YS FABRIC TECH" rel="tab1" href="/ys-fabric-tech">YS Fabric Tech</a></li>
            <li><a data-heading="YS COLOR TECH" rel="tab2" href="/ys-color-tech">YS Color Tech</a></li>
           


        </ul>

    </div>
    <div class="clearfix"></div>
    <div class="ys-block">

        <!-- --------------------------------1st-box--------------------------- -->


        <!----------------------------------1st-box ends----------------------------->

        <!----------------------------------2nd-box----------------------------->

        <div id="tab2" class="story-box">
            <span class="close-icn" style="display:block">
			<svg xml:space="preserve" enable-background="new 0 0 44 44" viewBox="0 0 44 44" height="44px" width="44px"
                 y="0px" x="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg"
                 id="Layer_1" version="1.1"><g>
                    <rect height="44" width="44" fill="#555555"/>
                    <line y2="30" x2="30" y1="14" x1="14" stroke-miterlimit="10" stroke="#FFFFFF" fill="none"/>
                    <line y2="30" x2="14" y1="14" x1="30" stroke-miterlimit="10" stroke="#FFFFFF" fill="none"/>
                </g></svg>

			</span>

            <div class="txt-cnt">

                <img alt="made in usa" src="<?php echo $this->getSkinUrl('images/color-tech-progressive.jpg'); ?>"
                     class="img-responsive">

                <!--    <span class="ovr-text">YS COLOR TECH</span>
                    <span>True Colors for Today<br>& Tomorrow</span>-->
                <!--                <p class="bottom-text" style="display: block;">Learn More<span> &gt;</span></p>-->
            </div>

            <div style="display: block;" class="inside-content ">
                <div class="our-breath">
                    <!--  <div class="title">A BIT MORE ABOUT US&mdash;</div>
                      <div class="below-txt" style="line-height:50px;">joy, energy & balance</div>-->

                    <p>A black so deep we trademarked it. Introducing&mdash;Carbon 6&trade;.</p>

                    <p>
                        Black&mdash;super slimming & always flattering. And the darker it is, the hotter you look. But
                        when we
                        looked around with clear focus, it was obvious, black had been sold short&mdash;there was no
                        true deep
                        black to be found. </p>

                    <p>
                        All of our colors stay true to you (and don&rsquo;t they have the cutest names too): Tickled
                        Pink,
                        India Blue, Boy Blue & YS Gold. </p>

                </div>
				<div id="email_link" class="see_our_colors" style="position:relative; float: left; width: 100%;margin-top:0;margin-bottom:0;">
                    <p style="font-family:AvantGarde-demi!important;line-height:44px;padding-left: 36px; letter-spacing: 1px;border-bottom:none;">
                        <span class="febric-icn"
                              style="position: absolute; width: 44px; height: 44px; right: initial; left: -8px !important; ">
                            <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg"
                                 xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                                 width="44px" height="44px" viewBox="0 0 44 44" enable-background="new 0 0 44 44"
                                 xml:space="preserve">
<linearGradient id="SVGID_1_" gradientUnits="userSpaceOnUse" x1="10.2402" y1="22.3477" x2="35.2402" y2="22.3477">
    <stop offset="0.0063" style="stop-color:#FED500"/>
    <stop offset="0.0971" style="stop-color:#F69A1E"/>
    <stop offset="0.2072" style="stop-color:#F05123"/>
    <stop offset="0.2569" style="stop-color:#ED2224"/>
    <stop offset="0.2753" style="stop-color:#DF242F"/>
    <stop offset="0.3432" style="stop-color:#B42A50"/>
    <stop offset="0.4042" style="stop-color:#922D66"/>
    <stop offset="0.4564" style="stop-color:#7B2D74"/>
    <stop offset="0.4975" style="stop-color:#6C2E7D"/>
    <stop offset="0.5226" style="stop-color:#662E80"/>
    <stop offset="0.5465" style="stop-color:#623484"/>
    <stop offset="0.6895" style="stop-color:#3F4E9B"/>
    <stop offset="0.764" style="stop-color:#2756A7"/>
    <stop offset="0.818" style="stop-color:#44739B"/>
    <stop offset="0.8818" style="stop-color:#61948A"/>
    <stop offset="0.9356" style="stop-color:#77AE78"/>
    <stop offset="0.9766" style="stop-color:#85BF65"/>
    <stop offset="1" style="stop-color:#8AC75D"/>
</linearGradient>
                                <circle fill="url(#SVGID_1_)" cx="22.74" cy="22.348" r="12.5"/>
</svg>
                        </span>
                        SEE OUR COLORS

                    <div class="arrow-tag narrow" style="position: absolute; top: 0px; right: 3px;">
                        <svg width="44px" height="44px">
                            <line fill="none" stroke="#666666" stroke-miterlimit="10" x1="272.374" y1="109.657"
                                  x2="288.374" y2="109.657"/>
                            <line fill="none" stroke="#666666" stroke-miterlimit="10" x1="14.374" y1="21.39" x2="30.374"
                                  y2="21.39"/>
                            <line fill="none" stroke="#666666" stroke-miterlimit="10" x1="22.374" y1="13.39" x2="22.374"
                                  y2="29.39"/>
                        </svg>
                    </div>
                    <div class="colors_list">
                        <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('page/ys-color-code.phtml')->toHtml();?>
                    </div>
                </div>
                <div class="aurum upper-aurum">
                    <ul class="inner-aurum">
                       
                        <li class=""><span class="febric-icn">
                                <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg"
                                     xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                                     width="44px" height="44px" viewBox="0 0 44 44" enable-background="new 0 0 44 44"
                                     xml:space="preserve">
<g>
    <path fill="#AE8637" d="M19.096,24.109c0,2.016,1.631,3.646,3.646,3.646c2.013,0,3.643-1.631,3.643-3.646
		c0-2.012-3.643-7.168-3.643-7.168S19.096,22.097,19.096,24.109z"/>
    <polygon fill="#AE8637"
             points="27.021,11.593 27.021,12.862 30.825,12.862 30.825,16.667 32.094,16.667 32.094,11.593 	"/>
    <polygon fill="#AE8637"
             points="14.654,28.029 13.386,28.029 13.386,33.104 18.459,33.104 18.459,31.834 14.654,31.834 	"/>
</g>
</svg>
                            </span><span
                                class="innr-txt">Colors that won&rsquo;t Bleed</span>

                            <div class="arrow-tag narrow">
                                <svg width="44px" height="44px">
                                    <line fill="none" stroke="#666666" stroke-miterlimit="10" x1="272.374" y1="109.657"
                                          x2="288.374" y2="109.657"/>
                                    <line fill="none" stroke="#666666" stroke-miterlimit="10" x1="14.374" y1="21.39"
                                          x2="30.374" y2="21.39"/>
                                    <line fill="none" stroke="#666666" stroke-miterlimit="10" x1="22.374" y1="13.39"
                                          x2="22.374" y2="29.39"/>
                                </svg>
                            </div>
                            <ul class="first-li" style="display:none;">
                                <li>
                                    <p>We put our colors through multiple rounds of rigorous testing for each lot of
                                        fabric
                                        so we can prevent even minimal color bleed. All you need to worry about is how
                                        to
                                        style your deep, beautiful and saturated colors.</p>
                                </li>

                            </ul>

                        </li>
                        <li class=""><span class="febric-icn">
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
     viewBox="0 0 44 44" style="enable-background:new 0 0 44 44;" xml:space="preserve">
<style type="text/css">
    .st1{fill:#AE8637 !important;}
</style>
    <g>
        <path class="st1" d="M16.7,15.9L13,12.2l-0.9,0.9l3.7,3.7C16.1,16.5,16.4,16.2,16.7,15.9z"/>
        <path class="st1" d="M22.4,14.1V8.9h-1.3v5.2c0.2,0,0.4,0,0.6,0S22.2,14.1,22.4,14.1z"/>
        <path class="st1" d="M19.4,14.4l-2-4.8l-1.2,0.5l2,4.8C18.5,14.7,18.9,14.5,19.4,14.4z"/>
        <path class="st1" d="M14.8,18.3l-4.8-2l-0.5,1.2l4.8,2C14.4,19.1,14.6,18.7,14.8,18.3z"/>
        <path class="st1" d="M27.7,16.8l3.7-3.7l-0.9-0.9l-3.7,3.7C27.1,16.2,27.4,16.5,27.7,16.8z"/>
        <path class="st1" d="M29.2,19.5l4.8-2l-0.5-1.2l-4.8,2C28.9,18.7,29,19.1,29.2,19.5z"/>
        <path class="st1" d="M13.9,21.9c0-0.2,0-0.4,0-0.6H8.7v1.3H14C13.9,22.3,13.9,22.1,13.9,21.9z"/>
        <path class="st1" d="M27.3,10.1l-1.2-0.5l-2,4.8c0.4,0.1,0.8,0.3,1.2,0.5L27.3,10.1z"/>
        <path class="st1" d="M29.5,21.2c0,0.2,0,0.4,0,0.6s0,0.4,0,0.6h5.2v-1.3H29.5z"/>
        <path class="st1" d="M26.8,27.8l3.7,3.7l0.9-0.9l-3.7-3.7C27.4,27.2,27.1,27.5,26.8,27.8z"/>
        <path class="st1" d="M24.1,29.3l2,4.8l1.2-0.5l-2-4.8C24.9,29,24.5,29.2,24.1,29.3z"/>
        <path class="st1" d="M28.7,25.4l4.8,2l0.5-1.2l-4.8-2C29,24.6,28.9,25,28.7,25.4z"/>
        <path class="st1" d="M16.2,33.6l1.2,0.5l2-4.8c-0.4-0.1-0.8-0.3-1.2-0.5L16.2,33.6z"/>
        <path class="st1" d="M15.8,26.9l-3.7,3.7l0.9,0.9l3.7-3.7C16.4,27.5,16.1,27.2,15.8,26.9z"/>
        <path class="st1" d="M21.1,29.6v5.2h1.3v-5.2c-0.2,0-0.4,0-0.6,0S21.3,29.7,21.1,29.6z"/>
        <path class="st1" d="M14.3,24.2l-4.8,2l0.5,1.2l4.8-2C14.6,25,14.4,24.6,14.3,24.2z"/>
        <circle class="st1" cx="21.7" cy="21.9" r="6.5"/>
    </g>
</svg>
                            </span><span
                                class="innr-txt">Colors that won&rsquo;t fade</span>

                            <div class="arrow-tag narrow">
                                <svg width="44px" height="44px">
                                    <line fill="none" stroke="#666666" stroke-miterlimit="10" x1="272.374" y1="109.657"
                                          x2="288.374" y2="109.657"/>
                                    <line fill="none" stroke="#666666" stroke-miterlimit="10" x1="14.374" y1="21.39"
                                          x2="30.374" y2="21.39"/>
                                    <line fill="none" stroke="#666666" stroke-miterlimit="10" x1="22.374" y1="13.39"
                                          x2="22.374" y2="29.39"/>
                                </svg>
                            </div>
                            <ul class="first-li" style="display:none;">
                                <li>
                                    <p>Color&mdash;it highlights your assets, brightens your mood. And we want that to
                                        last.
                                        But
                                        ever so often, colors fade so quickly&mdash;just ask our competitors. That&rsquo;s
                                        about
                                        to
                                        change. Our colors go through the toughest tests to make sure they last for the
                                        long
                                        haul warm or cold water. Because we have a true love for color, and for you,
                                        that
                                        won&rsquo;t fade away.</p>
                                </li>
                            </ul>

                        </li>
                        <li class=""><span class="febric-icn">
                                <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg"
                                     xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                                     width="44px" height="44px" viewBox="0 0 44 44" enable-background="new 0 0 44 44"
                                     xml:space="preserve">
<path fill="#AE8637" d="M35.273,22.035h-4.802c-0.162-4.021-3.396-7.255-7.418-7.417V9.814h-0.626v4.803
	c-4.021,0.162-7.257,3.396-7.419,7.417h-4.802v0.627h4.802c0.162,4.022,3.396,7.256,7.419,7.418v4.801h0.626V30.08
	c4.021-0.162,7.257-3.396,7.418-7.418h4.802V22.035z M29.219,22.035h-4.56c-0.134-0.823-0.781-1.472-1.605-1.606v-4.558
	C26.384,16.03,29.059,18.705,29.219,22.035z M22.428,15.871v4.558c-0.824,0.134-1.472,0.783-1.606,1.606h-4.559
	C16.423,18.705,19.097,16.03,22.428,15.871z M16.263,22.662h4.559c0.135,0.823,0.782,1.471,1.606,1.606v4.559
	C19.097,28.666,16.422,25.992,16.263,22.662z M23.054,28.826v-4.559c0.824-0.135,1.472-0.783,1.605-1.606h4.56
	C29.059,25.992,26.384,28.666,23.054,28.826z"/>
</svg>
                            </span><span
                                class="innr-txt">Color Accuracy</span>

                            <div class="arrow-tag narrow">
                                <svg width="44px" height="44px">
                                    <line fill="none" stroke="#666666" stroke-miterlimit="10" x1="272.374" y1="109.657"
                                          x2="288.374" y2="109.657"/>
                                    <line fill="none" stroke="#666666" stroke-miterlimit="10" x1="14.374" y1="21.39"
                                          x2="30.374" y2="21.39"/>
                                    <line fill="none" stroke="#666666" stroke-miterlimit="10" x1="22.374" y1="13.39"
                                          x2="22.374" y2="29.39"/>
                                </svg>
                            </div>
                            <ul class="first-li" style="display:none;">
                                <li>
                                    <p>We use the most advanced computerized color matching and dyeing apparatus and
                                        high
                                        performance dye-jets. The dye-jets are custom programmed to use exact amount of
                                        pigmentation so that residual water after the dyeing is clear and run off can be
                                        released without adding harmful chemicals.</p>
                                </li>
                            </ul>

                        </li>
                        <li class=""><span class="febric-icn">
                                <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg"
                                     xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                                     width="44px" height="44px" viewBox="0 0 44 44" enable-background="new 0 0 44 44"
                                     xml:space="preserve">
<path fill="#AE8637" d="M31.41,29.25c-0.591,0-1.124,0.23-1.532,0.596l-5.212-4.461c0.235-0.361,0.375-0.791,0.375-1.254
	c0-1.168-0.874-2.122-2.001-2.27v-6.446c1.127-0.148,2.001-1.102,2.001-2.27c0-1.272-1.03-2.301-2.301-2.301
	c-1.271,0-2.301,1.029-2.301,2.301c0,1.168,0.873,2.122,2,2.27v6.446c-1.127,0.148-2,1.102-2,2.27c0,0.463,0.14,0.893,0.375,1.254
	l-5.213,4.461c-0.407-0.365-0.94-0.596-1.531-0.596c-1.271,0-2.301,1.029-2.301,2.301s1.03,2.301,2.301,2.301
	s2.301-1.029,2.301-2.301c0-0.463-0.14-0.893-0.375-1.252l5.212-4.461c0.408,0.365,0.941,0.594,1.532,0.594s1.124-0.229,1.531-0.594
	l5.212,4.461c-0.235,0.359-0.375,0.789-0.375,1.252c0,1.271,1.03,2.301,2.302,2.301c1.271,0,2.301-1.029,2.301-2.301
	S32.681,29.25,31.41,29.25z"/>
</svg>

                            </span><span
                                class="innr-txt">Carbon 6</span>

                            <div class="arrow-tag narrow">
                                <svg width="44px" height="44px">
                                    <line fill="none" stroke="#666666" stroke-miterlimit="10" x1="272.374" y1="109.657"
                                          x2="288.374" y2="109.657"/>
                                    <line fill="none" stroke="#666666" stroke-miterlimit="10" x1="14.374" y1="21.39"
                                          x2="30.374" y2="21.39"/>
                                    <line fill="none" stroke="#666666" stroke-miterlimit="10" x1="22.374" y1="13.39"
                                          x2="22.374" y2="29.39"/>
                                </svg>
                            </div>
                            <ul class="first-li" style="display:none;">
                                <li>
                                    <p>A black so deep we trademarked it. Introducing&mdash;Carbon 6.<br><br>

                                        Black&mdash;super slimming & always flattering. And the darker it is, the hotter you
                                        look. But when we looked around with clear focus, it was obvious, black had been
                                        sold short&mdash;there was no true deep black to be found.<br><br>

                                        We spent two years creating our own black&mdash;Carbon 6&mdash;using the highest
                                        quality
                                        pigments, Carbon 6 absorbs the highest amount of light, so it&rsquo;s an
                                        intense, pure
                                        black. Simply put, when you wear it, you&rsquo;ll look ravishing.</p>
                                </li>
                            </ul>

                        </li>
                        <li style="" class=""><span class="febric-icn">
                                    <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg"
                                         xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                                         width="44px" height="44px" viewBox="0 0 44 44"
                                         enable-background="new 0 0 44 44" xml:space="preserve">
<g>
    <path fill="#AE8637" d="M23.832,21.864l4.632-4.636c0.604-0.607,1.264-0.929,1.908-0.929c0.96,0,1.891,0.68,2.43,1.778
		c0.429,0.867,0.389,2.018-0.096,2.795c-0.402,0.646-1.06,0.991-1.902,0.991H23.832z"/>
    <path fill="#AE8637" d="M21.648,21.864l-4.632-4.636c-0.606-0.607-1.266-0.929-1.909-0.929c-0.96,0-1.892,0.68-2.431,1.778
		c-0.428,0.867-0.387,2.018,0.097,2.795c0.4,0.646,1.059,0.991,1.9,0.991H21.648z"/>
    <path fill="#AE8637" d="M23.246,14.775c0-0.885,0.166-1.594,0.651-2.049c0.426-0.398,0.999-0.618,1.692-0.618
		c0.395,0,0.771,0.067,1.168,0.202c0.916,0.314,1.688,1.152,1.895,2.041c0.173,0.742,0.034,1.449-0.56,2.043l-4.847,4.934V14.775z"
        />
    <path fill="#AE8637" d="M22.263,14.775c0-0.885-0.164-1.594-0.649-2.049c-0.428-0.398-0.997-0.618-1.692-0.618
		c-0.397,0-0.772,0.067-1.169,0.202c-0.915,0.314-1.688,1.152-1.896,2.041c-0.172,0.742-0.034,1.449,0.561,2.043l4.846,4.934V14.775
		z"/>
    <path fill="#AE8637" d="M23.832,22.832l4.632,4.637c0.604,0.605,1.264,0.928,1.908,0.928c0.96,0,1.891-0.68,2.43-1.777
		c0.429-0.867,0.389-2.02-0.096-2.795c-0.402-0.646-1.06-0.993-1.902-0.993H23.832z"/>
    <path fill="#AE8637" d="M21.648,22.832l-4.632,4.637c-0.606,0.605-1.266,0.928-1.909,0.928c-0.96,0-1.892-0.68-2.431-1.777
		c-0.428-0.867-0.387-2.02,0.097-2.795c0.4-0.646,1.059-0.993,1.9-0.993H21.648z"/>
    <path fill="#AE8637" d="M23.246,29.92c0,0.885,0.166,1.596,0.651,2.051c0.426,0.396,0.999,0.617,1.692,0.617
		c0.395,0,0.771-0.068,1.168-0.201c0.916-0.314,1.688-1.154,1.895-2.043c0.173-0.742,0.034-1.447-0.56-2.043l-4.847-4.932V29.92z"/>
    <path fill="#AE8637" d="M22.263,29.92c0,0.885-0.164,1.596-0.649,2.051c-0.428,0.396-0.997,0.617-1.692,0.617
		c-0.397,0-0.772-0.068-1.169-0.201c-0.915-0.314-1.688-1.154-1.896-2.043c-0.172-0.742-0.034-1.447,0.561-2.043l4.846-4.932V29.92z
		"/>
</g>
</svg>
                            </span><span
                                class="innr-txt">Dyeing Proudly done in USA</span>

                            <div class="arrow-tag narrow">
                                <svg width="44px" height="44px">
                                    <line fill="none" stroke="#666666" stroke-miterlimit="10" x1="272.374" y1="109.657"
                                          x2="288.374" y2="109.657"/>
                                    <line fill="none" stroke="#666666" stroke-miterlimit="10" x1="14.374" y1="21.39"
                                          x2="30.374" y2="21.39"/>
                                    <line fill="none" stroke="#666666" stroke-miterlimit="10" x1="22.374" y1="13.39"
                                          x2="22.374" y2="29.39"/>
                                </svg>
                            </div>
                            <ul class="first-li" style="display:none;">
                                <li>
                                    <p>Unlike many companies who have their dyeing facilities located in China, our
                                        dye-lab is located in the USA, in a geographical area with the toughest
                                        environmental
                                        and pollution standards.
                                    </p>
                                </li>
                            </ul>

                        </li>
						 <li class=""><span class="febric-icn">
                                <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg"
                                     xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                                     width="44px" height="44px" viewBox="0 0 44 44" enable-background="new 0 0 44 44"
                                     xml:space="preserve">
<g>
    <path fill="#AE8637" d="M34.329,16.242c0-2.784-2.257-5.04-5.04-5.04c-0.777,0-1.512,0.183-2.172,0.498
		c-0.866-1.521-2.499-2.55-4.376-2.55s-3.511,1.029-4.379,2.55c-0.658-0.315-1.393-0.498-2.171-0.498c-2.784,0-5.04,2.256-5.04,5.04
		c0,2.008,1.179,3.739,2.88,4.548c-0.541,0.803-0.857,1.771-0.857,2.811c0,2.785,2.257,5.042,5.04,5.042c0.77,0,1.386,0,1.548-0.831
		l0.02-0.002c-0.175-3.362-0.932-5.841-2.4-6.411c0,0,0.962-0.027,3.13,0.607c0.617-1.046,1.864-3.403,1.864-3.403
		s1.228,2.386,1.845,3.525c1.308-0.288,3.662-0.982,3.569-0.942c-1.347,0.659-2.14,3.055-2.688,6.502
		c-0.044,0.275,1.133,0.955,2.167,0.955c2.783,0,5.04-2.257,5.04-5.041c0-1.041-0.316-2.009-0.857-2.812
		C33.149,19.98,34.329,18.25,34.329,16.242"/>
    <path fill="#AE8637" d="M25.754,36.083c-1.159-1.399-1.897-4.013-1.897-7.029c0-2.515,0.625-4.52,1.486-6.015
		c-0.381,0.119-1.645,0.641-1.645,0.641l-0.175-0.321c-0.354-0.659-0.838-1.463-1.148-1.767c-0.287,0.281-0.723,1.028-1.066,1.612
		l-0.193,0.326c0,0-1.204-0.498-1.607-0.611c0.952,1.473,1.388,3.44,1.388,6.136c0,3.019-0.74,5.63-1.898,7.029h3.378H25.754z"/>
</g>
</svg>
                            </span><span
                                class="innr-txt">Eco-Friendly Dyeing</span>

                            <div class="arrow-tag narrow">
                                <svg width="44px" height="44px">
                                    <line fill="none" stroke="#666666" stroke-miterlimit="10" x1="272.374" y1="109.657"
                                          x2="288.374" y2="109.657"/>
                                    <line fill="none" stroke="#666666" stroke-miterlimit="10" x1="14.374" y1="21.39"
                                          x2="30.374" y2="21.39"/>
                                    <line fill="none" stroke="#666666" stroke-miterlimit="10" x1="22.374" y1="13.39"
                                          x2="22.374" y2="29.39"/>
                                </svg>
                            </div>
                            <ul class="first-li" style="display:none;">
                                <li>
                                    <p>While the best black is the YOGASMOGA Carbon 6&mdash;a color that never fades, a
                                        true
                                        Yogi
                                        knows the new black must also come from a dye that does not pollute our
                                        waterways.
                                        We do not use any harmful formaldehyde based dyes that can seep into our
                                        groundwater.</p>
                                </li>

                            </ul>

                        </li>
                    </ul>
                </div>

                <!--  <div class="our-breath">
                      <span>DISCOVER OUR COLORS</span>

                      <p>
                          Color creates harmony. Every person has a special relationship with their own color &mdash; they enjoy it,
                          they desire it, they love it. We take pride in creating deep and saturated colors that everyone can enjoy and fall
                          in love with.
                      </p>


                  </div>-->

                

            </div>
        </div>

        <!----------------------------------2nd-box ends----------------------------->
        <!-- page block end -------------------------------------------------------------------------------------------->


    </div>


    <!--------------------------------------our-story-block ends here------------------------------------>

    <style>
        .inner-aurum li .innr-txt {
            font-family: AvantGarde-demi !important;
        }

        .upper-aurum li ul p {
            font-size: 14px !important;
            line-height: 20px !important;
        }

        .inner-aurum {
            clear: both;
        }

        .upper-aurum > ul > li:first-child {
            border-top: 1px solid #999 !important;
        }

        .inside-content .title {
            font: 24px/26px ITCAvantGardeStd-Bk !important;
            color: #434343 !important;
        }

        .textContainer .our-breath {
            position: relative;
        !important;
        }

        .flexslider.new-slider .slides li > a {
            padding: 0 10px 24px !important;
        }

        .inner-aurum li .innr-txt {
            display: block;
            font-family: AvantGarde-demi !important;
            font-size: 12px !important;
            height: 44px !important;
            letter-spacing: 1px;
            line-height: 44px !important;
            text-transform: uppercase;
            vertical-align: top;
        }

        .txt-cnt .bottom-text {
            bottom: 4px;
            color: #fff;
            font-family: freighttextbook;
            font-size: 18px;
            left: 0;
            line-height: 22px;
            position: absolute;
            bottom: 15px;
            right: 0;
            text-transform: capitalize;
        }

        .txt-cnt .bottom-text span {
            color: #ff0000;
            position: relative;
            bottom: 0;
        }
    </style>

    <style>
        .page_block, .slide_related_content {
            float: left;
            width: 100%;
        }

        .block_thumbnail {
            position: relative;
            line-height: 0;
        }

        .overlay-text {
            bottom: 20px;
            color: #fff;
            font: 16px freighttextmedium;
            left: 0;
            letter-spacing: 1px;
            position: absolute;
            width: 100%;
        }

        .overlay-text .text::after {
            content: ">";
            color: #B8153E;
        }

        .block_content {
            padding: 14px 14px 30px;
            float: left;
            text-align: left;
            width: 100%;
            display: none;
        }

        .account-nav.l-align.ys_static_page_dropdown {
            display: none;
        }

        .slide_related_content > div {
            display: none;
            float: left;
            padding: 25px 0 20px;
            width: 100%;
            text-align: left;
        }

        .block_content p {
            font: 18px/1.65em freighttextbook;
            letter-spacing: normal;
            margin: 20px 0;
        }

        .slide_related_content > div address {
            font: 22px/28px freighttextbook;
            margin: 25px 0 20px;
        }

        .slide_related_content > div p.store_hours {
            font: 12px/18px GraphikRegular;
        }

        .slide_related_content > div p.store_hours span {
            font: 12px/18px Graphik-Semibold;
        }

        .block_content p.title {
            font: 19px/21px ITCAvantGardeStd-Bk;
            margin: 0;
            letter-spacing: 1px;
        }

        .block_content p.sub-title {
            font: 19px/21px freighttextbookitalic;
            margin: 0;
            letter-spacing: 1px;
        }

        .block_content p.sub-title-namaskar {
            font: 19px/21px freighttextbookitalic;
            letter-spacing: 1px;
        }

        .slide_related_content div:first-child {
            display: block;
        }

        .add_bracelet {
            background: #00b900;
            border: none;
            color: #fff;
            font: 14px ITCAvantGardeStd-Bk;
            height: 44px;
            margin: 10px 0 25px;
            letter-spacing: 1px;
            width: 100%;
        }

        .block_content > div > div p:last-child {
            margin-bottom: 0;
        }

        .block_content > div > div {
            padding-bottom: 0;
        }

        .block_thumbnail .close-icn {
            height: 44px;
            position: fixed;
            right: 0;
            top: 88px;
            width: 44px;
            display: none;
            z-index: 5;
        }
		
		

    </style>
    <script type="text/javascript">
        jQuery(document).ready(function ($) {
            $(".sign-in-box .h1").html("YS COLOR TECH");
            $(".flexslider").flexslider({
                after: function (slider) {
                    slideContent(slider);
                }
            });

            var closebtnHtml = '<span class="close-icn"><svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="44px" height="44px" viewBox="0 0 44 44" enable-background="new 0 0 44 44" xml:space="preserve"><g><rect fill="#555555" width="44" height="44"/><line fill="none" stroke="#FFFFFF" stroke-miterlimit="10" x1="14" y1="14" x2="30" y2="30"/><line fill="none" stroke="#FFFFFF" stroke-miterlimit="10" x1="30" y1="14" x2="14" y2="30"/></g></svg></span>';
            $(".page_block .block_thumbnail").append(closebtnHtml);
            $(".page_block .block_thumbnail .close-icn").bind("click", function (e) {
                window.location.href = 'http://yogasmoga.com';
            });

        });
        function slideContent(slider) {
            var current_slide = slider.currentSlide + 1;
            var rel_value = slider.find(".slides li:nth-child(" + current_slide + ") img").attr("rel");
            slider.next().children("div").hide();
            if (rel_value != undefined) {
                slider.next().children("div[rel=" + rel_value + "]").fadeIn();
                slider.next().css("min-height", slider.next().children("div[rel=" + rel_value + "]").height());
            }
        }


    </script>
