
<script>
	jQuery(function($){


		if(window.location.href.indexOf('https://') >= 0)
			_usesecureurl = true;
		else
			_usesecureurl = false;
		var url = homeUrl;
		if(_usesecureurl)
			url = securehomeUrl;


		jQuery.ajax({
			type: 'POST',
			url: url+ 'careers/index/getcaliforniajobs',
			data: {'state': '1'},
			beforeSend:function (data) {
				jQuery("#content-loader").show();
				
			},
			success: function (data) {
				jQuery("#content-loader").hide();
				jQuery("#jobdata").html(data);
				jQuery('.job-title-list a[href*="#"]:not([href="#"])').click(function() {
								//alert();
								if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
								  var target = $(this.hash);
								  target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
								  if (target.length) {
									$('html, body').animate({
									  scrollTop: target.offset().top-104
									}, 1000);
									return false;
								  }
								}
							  });
			},
			error: function() {
				alert('Sorry for inconvinious try after some time');
			},

		});


		jQuery("#job-state-link ul.state-link li a").click(function(e){
				e.preventDefault();
				var state = jQuery(this).attr('rel');
					jQuery.ajax({
						type: 'POST',
						url: url + 'careers/index/getstatejobs',
						data: {'state': state},
						beforeSend:function (data) {
							jQuery("#content-loader").show();
							jQuery("#jobdata").hide();
						},
						success: function (data) {
							jQuery("#content-loader").hide();
							jQuery("#jobdata").show()
							jQuery("#jobdata").html(data);							
							jQuery('.job-title-list a[href*="#"]:not([href="#"])').click(function() {
								//alert();
								if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
								  var target = $(this.hash);
								  target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
								  if (target.length) {
									$('html, body').animate({
									  scrollTop: target.offset().top-104
									}, 1000);
									return false;
								  }
								}
							  });
						},
						error: function() {
							alert('Sorry for inconvinious try after some time');
						},

					});
				});
				

				  
				$('#jobtabs .state-link a').click(function(){
						$("html, body").animate({ scrollTop: 0 }, 400);
						$('#jobtabs .state-link a').removeClass('current');
						$(this).addClass('current');
				  });
				$(window).scroll(function() {  
					 if(jQuery("body").hasClass("career-index-index")){
						var element = jQuery(".side-menu-bar-jobs");   
						leftNav_scroll(element);
					} 
				  });
				
		});
</script>
  
<style>

</style>
<div id="jobtabs" class="2-columns-wrapper" style="padding:29px 40px 0 40px;">
    
	<div class="side-menu-bar-jobs f-left l-align" id="job-state-link">

		<ul class="state-link">
			<li><a rel="1" href="#" class="current">California</a></li>
			<li><a rel="2" href="#">Connecticut</a></li>
			<li><a rel="3" href="#">Massachusetts</a></li>
			<li><a rel="4" href="#">New Jersey</a></li>
			<li><a rel="5" href="#">New York</a></li>
		</ul>
	</div>	
   <div class="pg-content">
	   <div id="content-loader" style="display: none;"><img src="<?php echo $this->getSkinUrl('images/fancybox_loading.gif')?>"/></div>
		<div id="">
			<div id="jobdata"></div>
		</div>
	</div>
 <div class="new-bot-divider"></div>
</div><!--jobtabs ends-->

    

<div class="clear-fix"></div>