<div id="jobtabs" class="2-columns-wrapper" style="padding:29px 40px 0 40px;">
	<h1 style="display:none;">YOGASMOGA Careers</h1>
	<div class="side-menu-bar-jobs f-left l-align" id="job-state-link">

		<ul class="state-link">
			<li><a rel="1" href="#" class="current">California</a></li>
			<li><a rel="2" href="#">Connecticut</a></li>
			<!--<li><a rel="3" href="#">Massachusetts</a></li>-->
			<li><a rel="4" href="#">New Jersey</a></li>
			<li><a rel="5" href="#">New York</a></li>
			<li><a rel="6" href="#">Hawaii</a></li>
		</ul>
	</div>	
   <div class="pg-content">
	   <div id="content-loader" style="display: none;"><img src="<?php echo $this->getSkinUrl('images/fancybox_loading.gif')?>"/></div>
		<div id="">
			<div id="jobdata"></div>
		</div>
	</div>
 <div class="new-bot-divider"></div>
</div>

    

<div class="clear-fix"></div>