<?php $_config = $this->mHelper('config'); ?>
var EWCartReminder = {
	lastValueLog: {},
    rewritePage: function (config) {
		config.each(function(item) {
			var e = $$(item.selector).first();
			if (!e) return;
			e.stopObserving().observe('blur', function(item, event) {
				var e = Event.element(event);
				this.recordValue(item.type, e.value);
			}.bind(this, item));
		}.bind (this));
	},
	
	recordValue: function (type, value) {
		if (type.indexOf('email') >= 0 && value.indexOf('@') < 0) return;
		if (value != this.lastValueLog[type]) {
			this.lastValueLog[type] = value;
			this.ajax(<?php echo json_encode($this->getUrl('ewcartreminder/quote/updateAjax')); ?>, {type: type, value: value});
		}
	},
	
	ajax: function(url, params) {
		if (!params) params = {};
    	url = this.rewriteUrl(url);
    	new Ajax.Request(url, {
            method: 'post',
            parameters: params
        });
    },
    
    rewriteUrl:function(url){
		url = url.replace('http://', window.location.protocol+'//');
        return url.replace('https://', window.location.protocol+'//');
	}
};

Event.observe(document, 'dom:loaded', function(){
	EWCartReminder.rewritePage([
		{type: 'customer_email', 'selector': 'input[id="billing:email"]'},
		{type: 'customer_firstname', 'selector': 'input[id="billing:firstname"]'},
		{type: 'customer_lastname', 'selector': 'input[id="billing:lastname"]'},
		{type: 'customer_telephone', 'selector': 'input[id="billing:telephone"]'}
	]);
});