<?php
/**
 * J2T RewardsPoint2
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@j2t-design.com so we can send you a copy immediately.
 *
 * @category   Magento extension
 * @package    RewardsPoint2
 * @copyright  Copyright (c) 2009 J2T DESIGN. (http://www.j2t-design.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 ?>
  <?php
    //echo Mage::getModel('core/cookie')->get('afterlogindest');
    if(Mage::getModel('core/cookie')->get('afterlogindest') == "cart")
    {
        //Mage::getModel('core/cookie')->delete('afterlogindest');
        
        Mage::app()->getFrontController()->getResponse()->setRedirect(Mage::helper('core/url')->getHomeUrl()."checkout/cart#promotions");
        Mage::getModel('core/cookie')->set('afterlogindest', 'cart123', 0,'/');
    }
    if(Mage::getModel('core/cookie')->get('afterlogindest') == "giftofys")
    {
        Mage::app()->getFrontController()->getResponse()->setRedirect(Mage::helper('core/url')->getHomeUrl()."gift_of_ys#redeemcard");
        Mage::getModel('core/cookie')->set('afterlogindest', 'cart123', 0,'/');
    }
    
    //if(Mage::getSingleton('core/session')->getRedirect() == "cart")
//    {
//        Mage::app()->getFrontController()->getResponse()->setRedirect(Mage::helper('core/url')->getHomeUrl()."checkout/cart");
//        Mage::getSingleton('core/session')->setRedirect('');
//    }
    //if(Mage::getSingleton('core/session')->getRedirect() == "giftofys")
//    {
//        Mage::app()->getFrontController()->getResponse()->setRedirect(Mage::helper('core/url')->getHomeUrl()."gift_of_ys#redeemcard");
//        Mage::getSingleton('core/session')->setRedirect('');
//    }
?>
<div class="dashboard">
	<div class="page-title"><h1>MY ACCOUNT</h1></div>
    <?php echo $this->getChildHtml('hello'); ?>
    <?php echo $this->getChildHtml('info') ?>
   <!-- <div class="box-account box-info">
        <h3 class="subtitle"><?php echo $this->__('Account Information') ?></h3>
        <?php //echo $this->getChildHtml('address') ?>
    </div> --> <!-- chetan commented this before launch 2/14/2013 -->
    <?php echo $this->getChildHtml('info1') ?>
    <?php echo $this->getChildHtml('info2') ?>
</div>
 
<?php /* 
 <ul class="account-link">
    <li><a href="<?php echo Mage::helper('core/url')->getHomeUrl(); ?>customer/address">Address Book</a></li>
    <li><a href="<?php echo Mage::helper('core/url')->getHomeUrl(); ?>sales/order/history">My Orders</a></li>
    <li><a href="<?php echo Mage::helper('core/url')->getHomeUrl(); ?>wishlist">My Wishlist</a></li>
    <li><a href="<?php echo Mage::helper('core/url')->getHomeUrl(); ?>rewardpoints/index/referral/">Referred Friends</a></li>
    <li><a href="<?php echo Mage::helper('core/url')->getHomeUrl(); ?>rewardpoints/index/points">SMOGI BUCKS</a></li>
    <li><a href="<?php echo Mage::helper('core/url')->getHomeUrl(); ?>customer/giftcards/balance">Gift Cards</a></li>
 </ul>
 
<div class="page-head">
    <h3><?php echo $this->__('My Dashboard') ?></h3>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php echo $this->getChildHtml('hello') ?>

<?php echo $this->getChildHtml('top') ?>

<div class="account-box ad-account-info box">
        <div class="box-account box-recent">
            <div class="box-head">
                <h2><?php echo $this->__('Points') ?></h2>
            </div>
            <?php echo $this->getChildHtml('points') ?>
        </div>
</div>

<div class="account-box ad-account-info box">
    <div class="head box-title">
        <h3><?php echo $this->__('Account Information') ?></h3>
    </div>
    <?php echo $this->getChildHtml('info') ?>
    <?php echo $this->getChildHtml('address') ?>
</div>


<?php echo $this->getChildHtml('info1') ?>
<?php echo $this->getChildHtml('info2') ?>
*/ ?>