<?php
/**
 * J2T RewardsPoint2
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@j2t-design.com so we can send you a copy immediately.
 *
 * @category   Magento extension
 * @package    RewardsPoint2
 * @copyright  Copyright (c) 2009 J2T DESIGN. (http://www.j2t-design.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 ?>
 
<?php $points_currently_used = $this->getPointsCurrentlyUsed(); ?>
<?php $couponCode = Mage::getSingleton('checkout/cart')->getQuote()->getCouponCode(); ?>
<?php $pts = $this->getPointsOnOrder();?>

<?php if (!$this->getAutoUse()): ?>
    <?php if (!$this->getCustomerId()):?>
    

        <table class="tblsmogilogin">
            <tr>
                <td align="center">
                <div >
                <h6 style="
    font-family: gotham-m,arial;
    font-size: 16px;
    font-weight: normal;
    line-height: 1.2;">DO YOU HAVE SMOGI BUCKS?</h6>
                </div>
                    <p>Returning customer? Use your SMOGI Bucks from past purchases.</p>
            		
            		<a href="<?php  echo Mage::getUrl('',array('_secure'=>true)); ?>customer/account/login?goto=cart">
            		<button value="<?php echo $this->__('Login') ?>" class="button1 btn-cart1" title="Login" type="button"><span>LOGIN</span></button>
                    </a>
            		
            		<!-- <button value="<?php echo $this->__('Login') ?>" onclick="setLocation('<?php  echo Mage::helper('customer')->getLoginUrl(); ?>')" class="button btn-sec" title="Login" type="button"><span><span><?php echo $this->__('Login') ?></span></span></button>
                	-->
                </td>
            </tr>
        </table>
        <?php /*
        <div class="discount-codes box discount">
            <h2><?php echo $this->__('Reward points'); ?></h2>
            <?php echo $this->getIllustrationImage()?>
            <div class="rewards_point_cart"><?php echo $this->__("This shopping cart is worth %s loyalty point(s).", $pts);?><?php echo Mage::helper('rewardpoints/data')->getEquivalence($pts);?></div>
        </div>
        */ ?>
    <?php endif; ?>
<?php if ($this->getCustomerId()): ?>
    <?php $point_details = $this->getPointsInfo();?>

<?php if ($this->canUseCouponCode() && ($couponCode == "" || $couponCode == null) || !$this->canUseCouponCode()):?>
<div class="smogibox">
    <?php if (!$points_currently_used): ?>
    <form action="<?php echo $this->getUrl('rewardpoints/index/quotation/') ?>" method="post" name="discountFormPoints2" id="discountFormPoints2">
        <fieldset>
            <h6><?php echo $this->__('SMOGI BUCKS*'); ?></h6>
            
            <?php echo $this->getIllustrationImage()?>
            
            <div class="rewards_point_cart"><?php echo $this->__("This shopping cart is worth %s loyalty point(s).", $pts);?><?php echo Mage::helper('rewardpoints/data')->getEquivalence($pts);?></div>
            <?php //if ($point_details['points_money'] > $point_details['customer_points']):?>
            <?php if ($point_details['min_use'] > $point_details['customer_points']):?>
                <p><?php echo $this->__('You have %d SMOGI Buck(s) available.', $point_details['customer_points']); ?><?php echo Mage::helper('rewardpoints/data')->getEquivalence($point_details['customer_points']);?></p>
                <?php //if ($point_details['step_apply']):?>
                <p><?php echo $this->__('To get a discount you need at least %d loyalty point(s).', $point_details['min_use']); ?></p>
                <?php //endif;?>
            <?php else:?>
                <p class="no-display"><?php echo $this->__('Enter quantity of loyalty point(s) you want to use.') ?></p>
                <p><?php echo $this->__('You have <span id="tpoints">%d</span> SMOGI Buck(s) available.', $point_details['customer_points']); ?><?php echo Mage::helper('rewardpoints/data')->getEquivalence($point_details['customer_points']);?></p>

                <?php
                    if($this->isUsable() && $this->getCustomerPoints() > 0)
                    {
                        ?>
                        <br />
                        Enter the amount you want to use <br/>with this purchase.
                        <?php
                    }
                 ?>
                </p>

                <?php if($this->isUsable() && $this->getCustomerPoints() > 0) : ?>
            
                <?php if ($point_details['step_apply']):?>
                    <?php if (!$this->useSlider()):?>
                    <select name="points_to_be_used" id="coupon_code_points_qty" class="input-text">
                        <?php echo $this->pointsToAddOptions($point_details['customer_points'], $point_details['step']);?>
                    </select>
                    <?php else:?>

                    <div class="j2t-slider">
                        <div onclick="new Effect.SwitchOff(this)"><?php echo $this->__('Slide to specify the amount of points to be used.');?></div>
                        <div id="j2t-track1">
                            <div id="j2t-handle1"> </div>
                        </div>
                        <div id='j2t-height_value_1'></div>

                        <?php $option_slider = $this->pointsToAddOptions($point_details['customer_points'], $point_details['step'], true);?>
                        <?php $arr_slider = explode(',',$option_slider);?>

                        <script type="text/javascript" language="javascript">
                        // <![CDATA[
                            window.onload = function() {
                                var s1 = new Control.Slider('j2t-handle1','j2t-track1', {axis:'horizontal', range: $R(<?php echo $arr_slider[0];?>,<?php echo end($arr_slider);?>), values: [<?php echo $option_slider;?>]});
                                s1.options.onChange = function(value){
                                    $('j2t-height_value_1').innerHTML = value;
                                    $('points_to_be_used').value = s1.value;
                                };
                                $('j2t-height_value_1').innerHTML = s1.value;
                                $('points_to_be_used').value = s1.value;
                            }
                        // ]]>
                      </script>
                      <input type="hidden" value="<?php if(isset($arr_slider[0])):?><?php echo $arr_slider[0];?><?php endif;?>"  name="points_to_be_used" id="points_to_be_used" class="input-text" />
                    </div>
                    <?php endif;?>


                <?php else:?>
                    <input <?php if($point_details['full_use']):?>type="hidden"<?php else:?>type="text"<?php endif;?> value="<?php if($point_details['full_use']):?><?php echo $point_details['max_use'];?><?php endif;?>"  name="points_to_be_used" class="input-text" style="width:298px;margin:0 auto;text-align:center;"  id="points_to_be_used"/>
                    
                    <div class="errortext" id="points_error">
                                    <?php //echo strip_tags($this->getMessagesBlock()->getGroupedHtml()); ?>
                                </div>    
                           
                    
                <?php endif;?>
                <?php if($this->getCustomerPoints() > 0) : ?>
                <div class="buttons-set">
                    <button class="button btn-update" value="<?php echo $this->__('Apply') ?>" onclick="" type="submit"><span><span><?php echo $this->__('Apply') ?></span></span>
                    </button>
                </div>
                
                
                 <div style="margin-top : 5px;">
                You will earn <?php echo $pts; ?> <a target="_blank" href ="<?php echo $this->getUrl('smogi-bucks'); ?>">SMOGI Bucks</a><br/> after this purchase.
			<?php	if($points_currently_used == 0 && Mage::getSingleton('core/session')->getCPmsg() > 0) 
			{	
			echo "<br/>You cannot use SMOGI Bucks on Accessories and the Namaskar Bracelet.<br/>"; 
			} ?>
			   </div>
              
                
                <?php endif;?>
                <?php elseif($this->getCustomerPoints() > 0): ?>
                    <p><?php echo $this->__('You must have at least %s point(s) to apply points.', $this->getMinimumBalance()); ?></p>
                <?php endif; ?>
            <?php endif;?>

            <?php //echo Mage::helper('rewardpoints/event')->getCreditPoints(); ?>

        </fieldset>
    </form>
    <?php else: ?>
    <form action="<?php echo $this->getUrl('rewardpoints/index/removequotation/') ?>" method="post" name="discountFormPoints2" id="discountFormPoints2">
        <fieldset>
            <h6><?php echo $this->__('SMOGI BUCKS*'); ?></h6>
            <?php echo $this->getIllustrationImage()?>
            <div class="rewards_point_cart"><?php echo $this->__("This shopping cart is worth %s loyalty point(s).", $pts);?><?php echo Mage::helper('rewardpoints/data')->getEquivalence($pts);?></div>
            <?php if ($points_currently_used > 0):?>
            <p><?php echo $this->__('You are currently using %d Buck(s) of your %d SMOGI Buck(s) available.<span id="double-star" style="display:none;">**</span>', $points_currently_used, $this->getCustomerPoints()); ?></p>
            <?php endif;?>
            <div class="buttons-set">
                <button class="button btn-update" type="button" onclick="discountFormPoints2.submit(false)" value="<?php echo $this->__('Remove Points') ?>"><span><span><?php echo $this->__('Remove') ?></span></span></button>
            </div>
           <!-- <div style="margin-top : 5px;">
                You will earn <?php echo $pts; ?> <a target="_blank" href ="<?php echo $this->getUrl('smogi-bucks'); ?>">SMOGI Bucks</a><br/> after this purchase.
                </div>-->
			 <div class="buttons-set">
			<?php
			$coupon_code = Mage::getSingleton('checkout/session')->getQuote()->getCouponCode();
			$bucksused = Mage::helper('rewardpoints/event')->getCreditPoints();
			//$gcard = Mage::getSingleton('giftcards/session')->getActive();
			$gcard = (Mage::getSingleton('giftcards/session')->getActive() == "1" && Mage::helper('giftcards')->getCustomerBalance(Mage::getSingleton('customer/session')->getCustomer()->getId()));
			
			if(!($coupon_code  || $bucksused || $gcard))
			{
			?>
             *You will earn <?php echo $pts; ?> <a target="_blank" href ="<?php echo $this->getUrl('smogi-bucks'); ?>">SMOGI Bucks</a> after this purchase.
			<?php        
			}
			else
			{
			?>
			*Orders where SMOGI Bucks or Promotions are redeemed are ineligible to earn additional SMOGI Bucks.
			<?php 
			}
			?>
			
			<?php 
					//echo Mage::getSingleton('core/session')->getAccessoriesTot();
					if (Mage::getSingleton('core/session')->getCPmsg() > $points_currently_used && Mage::getSingleton('core/session')->getAccessoriesTot() > 0)
					{	?>
			<td width="545px" style="text-align:right;" rowspan="2">
					<div>
					 <div style="margin-top : 10px;">
					 **Only <?php echo $points_currently_used ?> of your requested <?php echo Mage::getSingleton('core/session')->getCPmsg();//$point_details['max_use']; ?> SMOGI Bucks were applied to your order as <br/>you cannot use SMOGI Bucks on Accessories and the Namaskar Bracelet.<br/>
                         <style type="text/css">#double-star{
                                 display: inline !important;
                             }</style>
					 </div>
					 </div>
					</td>
			<?php }else
		{			?>
		
		<!--<div style="float: right; color: rgb(169, 169, 169); font-family: gothamlight; margin-right: 15px;" >
             *You don't earn smogi bucks on orders where you are using any kind of promotion.
             </div>-->
			 <?php }
			 ?>
			</div>
			
        </fieldset>
    </form>
    <?php endif;?>
</div>

<?php endif;?>
<?php endif;?>



<?php /*if ($this->canUseCouponCode() && ($points_currently_used < 1 || $points_currently_used == null) || !$this->canUseCouponCode()):?>
<?php echo $this->getChildHtml('coupon_original');?>
<?php endif;*/?>

<?php else: ?>
<?php /*?><div class="discount-codes box discount"><?php */?>
<?php if (!$this->getCustomerId()):?>
<div class="discount-codes box discount">
    <h2><?php echo $this->__('Reward points'); ?></h2>
    <div class="rewards_point_cart"><?php echo $this->__("This shopping cart is worth %s loyalty point(s).", $pts);?><?php echo Mage::helper('rewardpoints/data')->getEquivalence($pts);?></div>
</div>
<?php endif; ?>
<?php if ($this->getCustomerId()): ?>
<?php $customerPoints = $this->getCustomerPoints(); ?>
<?php if ($customerPoints):?>
<div class="discount-codes box discount">
    <h2><?php echo $this->__('Reward points'); ?></h2>
    <div class="rewards_point_cart"><?php echo $this->__("This shopping cart is worth %s loyalty point(s).", $pts);?><?php echo Mage::helper('rewardpoints/data')->getEquivalence($pts);?></div>
    <?php if ($points_currently_used > 0):?>
    <p><?php echo $this->__('You are currently using %d point(s) of your %d loyalty point(s) available.', $points_currently_used, $customerPoints); ?></p>
    <?php endif;?>
</div>
<?php endif;?>
<?php endif;?>
<?php endif;?>

<?php if ($this->canUseCouponCode() && ($points_currently_used < 1 || $points_currently_used == null) || !$this->canUseCouponCode()):?>
<?php echo $this->getChildHtml('coupon_original');?>
<?php endif;?>

<script type="text/javascript">
    document.observe("dom:loaded", function() { 
        
        <?php if ($this->canShowRemoveLink() && $points_currently_used > 0):?>
                var points_text = "<?php echo str_replace('"', '\"', $this->__('%s points used', $points_currently_used));?>";
                var reward_link_cart = '<span id="link_j2t_rewards"> <a href="javascript:$(\'discountFormPoints2\').submit();" title="<?php echo Mage::helper('rewardpoints')->__('Remove Points').'"><img src="'.Mage::getDesign()->getSkinUrl('images/j2t_delete.gif').'" alt="'.Mage::helper('rewardpoints')->__('Remove Points').'" /></a></span>'; ?>';
                $$(".totals-rewards").each(function (el){
                    el.innerHTML = el.innerHTML.replace(points_text, points_text+reward_link_cart);
                });
        <?php endif;?>
        
        
        /*if ($('link_j2t_rewards')){
            var reward_link_cart = ' <a href="javascript:$(\'discountFormPoints2\').submit();" title="<?php echo Mage::helper('rewardpoints')->__('Remove Points').'"><img src="'.Mage::getDesign()->getSkinUrl('images/j2t_delete.gif').'" alt="'.Mage::helper('rewardpoints')->__('Remove Points').'" /></a>'; ?>';
            //alert(reward_link_cart);
            $('link_j2t_rewards').innerHTML = reward_link_cart;
        }*/
    });
    
</script>


<?php return; ?>
<?php
/**
 * J2T RewardsPoint2
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@j2t-design.com so we can send you a copy immediately.
 *
 * @category   Magento extension
 * @package    RewardsPoint2
 * @copyright  Copyright (c) 2009 J2T DESIGN. (http://www.j2t-design.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 ?>

<?php $points_currently_used = $this->getPointsCurrentlyUsed(); ?>
<?php $couponCode = Mage::getSingleton('checkout/cart')->getQuote()->getCouponCode(); ?>
<?php $pts = $this->getPointsOnOrder();?>

<?php if (!$this->getAutoUse()): ?>
    <?php if (!$this->getCustomerId()):?>
    <div class="discount-codes">
        <h2><?php echo $this->__('Reward points'); ?></h2>
        <?php echo $this->getIllustrationImage()?>
        <div class="rewards_point_cart"><?php echo $this->__("This shopping cart is worth %s loyalty point(s).", $pts);?><?php echo Mage::helper('rewardpoints/data')->getEquivalence($pts);?></div>
    </div>
    <?php endif; ?>
<?php if ($this->getCustomerId()): ?>
    <?php $point_details = $this->getPointsInfo();?>

<?php if ($this->canUseCouponCode() && ($couponCode == "" || $couponCode == null) || !$this->canUseCouponCode()):?>
<div class="discount-codes">
    <?php if (!$points_currently_used): ?>
    <form action="<?php echo $this->getUrl('rewardpoints/index/quotation/') ?>" method="post" name="discountFormPoints2" id="discountFormPoints2">
        <fieldset>
            <h6><?php echo $this->__('Smogi bucks*'); ?></h6>
            
            <?php echo $this->getIllustrationImage()?>
            
            <!-- div class="rewards_point_cart"><?php // echo $this->__("This shopping cart is worth %s loyalty point(s).", $pts);?><?php // echo Mage::helper('rewardpoints/data')->getEquivalence($pts);?></div -->
            <?php //if ($point_details['points_money'] > $point_details['customer_points']):?>
            <?php if ($point_details['min_use'] > $point_details['customer_points']):?>
                <p><?php echo $this->__('You have %d SMOGI Bucks available.', $point_details['customer_points']); ?><?php echo Mage::helper('rewardpoints/data')->getEquivalence($point_details['customer_points']);?></p>
                <?php //if ($point_details['step_apply']):?>
                <p><?php echo $this->__('To get a discount you need at least %d loyalty point(s).', $point_details['min_use']); ?></p>
                <?php //endif;?>
            <?php else:?>
                <p class="no-display"><?php echo $this->__('Enter quantity of loyalty point(s) you want to use.') ?></p>
                <p><?php echo $this->__('You have %d loyalty point(s) available.', $point_details['customer_points']); ?><?php echo Mage::helper('rewardpoints/data')->getEquivalence($point_details['customer_points']);?></p>

                <?php if($this->isUsable() && $this->getCustomerPoints() > 0) : ?>
                <?php if ($point_details['step_apply']):?>
                    <?php if (!$this->useSlider()):?>
                    <select name="points_to_be_used" id="coupon_code_points_qty" class="input-text">
                        <?php echo $this->pointsToAddOptions($point_details['customer_points'], $point_details['step']);?>
                    </select>
                    <?php else:?>

                    <div class="j2t-slider">
                        <div onclick="new Effect.SwitchOff(this)"><?php echo $this->__('Slide to specify the amount of points to be used.');?></div>
                        <div id="j2t-track1">
                            <div id="j2t-handle1"> </div>
                        </div>
                        <div id='j2t-height_value_1'></div>

                        <?php $option_slider = $this->pointsToAddOptions($point_details['customer_points'], $point_details['step'], true);?>
                        <?php $arr_slider = explode(',',$option_slider);?>

                        <script type="text/javascript" language="javascript">
                        // <![CDATA[
                            window.onload = function() {
                                var s1 = new Control.Slider('j2t-handle1','j2t-track1', {axis:'horizontal', range: $R(<?php echo $arr_slider[0];?>,<?php echo end($arr_slider);?>), values: [<?php echo $option_slider;?>]});
                                s1.options.onChange = function(value){
                                    $('j2t-height_value_1').innerHTML = value;
                                    $('points_to_be_used').value = s1.value;
                                };
                                $('j2t-height_value_1').innerHTML = s1.value;
                                $('points_to_be_used').value = s1.value;
                            }
                        // ]]>
                      </script>
                      <input type="hidden" value="<?php if(isset($arr_slider[0])):?><?php echo $arr_slider[0];?><?php endif;?>"  name="points_to_be_used" id="points_to_be_used" class="input-text" />
                    </div>
                    <?php endif;?>


                <?php else:?>
                    <input <?php if($point_details['full_use']):?>type="hidden"<?php else:?>type="text"<?php endif;?> value="<?php if($point_details['full_use']):?><?php echo $point_details['max_use'];?><?php endif;?>"  name="points_to_be_used" class="input-text" />
                <?php endif;?>
                <?php if($this->getCustomerPoints() > 0) : ?>
                    <button class="btn-sec button" value="<?php echo $this->__('Apply') ?>" onclick="discountFormPoints2.submit(false)" type="button"><span><span><?php echo $this->__('Apply') ?></span></span>
                    </button>
                <?php endif;?>
                <?php elseif($this->getCustomerPoints() > 0): ?>
                    <p><?php echo $this->__('You must have at least %s point(s) to apply points.', $this->getMinimumBalance()); ?></p>
                <?php endif; ?>
            <?php endif;?>

            <?php //echo Mage::helper('rewardpoints/event')->getCreditPoints(); ?>

        </fieldset>
    </form>
    <?php else: ?>
    <form action="<?php echo $this->getUrl('rewardpoints/index/removequotation/') ?>" method="post" name="discountFormPoints2" id="discountFormPoints2">
        <fieldset>
            <h2><?php echo $this->__('Reward points'); ?></h2>
            <?php echo $this->getIllustrationImage()?>
            <div class="rewards_point_cart"><?php echo $this->__("This shopping cart is worth %s loyalty point(s).", $pts);?><?php echo Mage::helper('rewardpoints/data')->getEquivalence($pts);?></div>
            <?php if ($points_currently_used > 0):?>
            <p><?php echo $this->__('You are currently using %d point(s) of your %d loyalty point(s) available.', $points_currently_used, $this->getCustomerPoints()); ?></p>
            <?php endif;?>
            <!-- div class="buttons-set">
                <button class="form-button-alt button" type="button" onclick="discountFormPoints2.submit(false)" value="<?php echo $this->__('Remove Points') ?>"><span><span><?php echo $this->__('Remove Points') ?></span></span></button>
            </div -->
        </fieldset>
    </form>
    <?php endif;?>
</div>

<?php endif;?>
<?php endif;?>



<?php /*if ($this->canUseCouponCode() && ($points_currently_used < 1 || $points_currently_used == null) || !$this->canUseCouponCode()):?>
<?php echo $this->getChildHtml('coupon_original');?>
<?php endif;*/?>

<?php else: ?>
<?php /*?><div class="discount-codes box discount"><?php */?>
<?php if (!$this->getCustomerId()):?>
<div class="discount-codes box discount">
    <h2><?php echo $this->__('Reward points'); ?></h2>
    <div class="rewards_point_cart"><?php echo $this->__("This shopping cart is worth %s loyalty point(s).", $pts);?><?php echo Mage::helper('rewardpoints/data')->getEquivalence($pts);?></div>
</div>
<?php endif; ?>
<?php if ($this->getCustomerId()): ?>
<?php $customerPoints = $this->getCustomerPoints(); ?>
<?php if ($customerPoints):?>
<div class="discount-codes box discount">
    <h2><?php echo $this->__('Reward points'); ?></h2>
    <div class="rewards_point_cart"><?php echo $this->__("This shopping cart is worth %s loyalty point(s).", $pts);?><?php echo Mage::helper('rewardpoints/data')->getEquivalence($pts);?></div>
    <?php if ($points_currently_used > 0):?>
    <p><?php echo $this->__('You are currently using %d point(s) of your %d loyalty point(s) available.', $points_currently_used, $customerPoints); ?></p>
    <?php endif;?>
</div>
<?php endif;?>
<?php endif;?>
<?php endif;?>

<?php if ($this->canUseCouponCode() && ($points_currently_used < 1 || $points_currently_used == null) || !$this->canUseCouponCode()):?>
<?php echo $this->getChildHtml('coupon_original');?>
<?php endif;?>

<script type="text/javascript">
    document.observe("dom:loaded", function() { 
        
        <?php if ($this->canShowRemoveLink() && $points_currently_used > 0):?>
                var points_text = "<?php echo str_replace('"', '\"', $this->__('%s points used', $points_currently_used));?>";
                var reward_link_cart = '<span id="link_j2t_rewards"> <a href="javascript:$(\'discountFormPoints2\').submit();" title="<?php echo Mage::helper('rewardpoints')->__('Remove Points').'"><img src="'.Mage::getDesign()->getSkinUrl('images/btn_window_close.gif').'" alt="'.Mage::helper('rewardpoints')->__('Remove Points').'" /></a></span>'; ?>';
                $$(".totals-rewards").each(function (el){
                    el.innerHTML = el.innerHTML.replace(points_text, points_text+reward_link_cart);
                });
        <?php endif;?>
        
        
        /*if ($('link_j2t_rewards')){
            var reward_link_cart = ' <a href="javascript:$(\'discountFormPoints2\').submit();" title="<?php echo Mage::helper('rewardpoints')->__('Remove Points').'"><img src="'.Mage::getDesign()->getSkinUrl('images/j2t_delete.gif').'" alt="'.Mage::helper('rewardpoints')->__('Remove Points').'" /></a>'; ?>';
            //alert(reward_link_cart);
            $('link_j2t_rewards').innerHTML = reward_link_cart;
        }*/
    });
    
</script>