<script>
    jQuery(function($){

        if(window.location.href.indexOf('https://') >= 0)
            _usesecureurl = true;
        else
            _usesecureurl = false;
        var url = homeUrl;
        if(_usesecureurl)
            url = securehomeUrl;

        $('.sub-nav li a').click(function(e){
            e.preventDefault();
            var state = $(this).attr('rel');
            jQuery.ajax({
                type: 'POST',
                url: url+ 'career/index/mobilestatejobs',
                data: {'state': state},
                beforeSend:function (data) {
                    //jQuery("#content-loader").show();
                },
                success: function (data) {
                    //jQuery("#content-loader").hide();
                    jQuery(".career-page").html(data);
                    /******* code for accordian ***/
                    $(".career-page li .toggle").click(function (e) {
                        e.preventDefault();
                        $(this).parent().siblings().find(".toggle").removeClass('active');
                        $(this).toggleClass('active');
                        $(this).parent('li').toggleClass('active');
                        $(this).parent('li').find(".answer_content").slideUp('fast');
                        $(this).parent('li.active').find(".answer_content").slideDown('fast');
                    });
                    /******* code for accordian ***/
                    $(".sub-nav li a").click(function (e) {
                        e.preventDefault();
                        var target = $(this).attr('rel');
                        $("#"+target).show().siblings(".career-page").hide();

                    });

                },
                error: function() {
                    alert('Sorry for inconvinious try after some time');
                },

            });
    });
 });
</script>


<div class="custom-block">
    <div class="ys-bottom">
        <div style="display: block" class="account-nav l-align ys_static_page_dropdown">
            <ul class="sub-nav static_page">
                <li><a rel="1" class="active_link" data-heading="CAREER"  href="javascript:void(0);">California</a></li>
                <li><a rel="2" data-heading="CAREER" href="javascript:void(0);">Connecticut</a></li>
                <li><a rel="3" data-heading="CAREER"  href="javascript:void(0);">Massachusetts</a></li>
                <li><a rel="4" data-heading="CAREER"  href="javascript:void(0);">New Jersey</a></li>
                <li><a rel="5" data-heading="CAREER"  href="javascript:void(0);">New York</a></li>
            </ul>
        </div>
    </div>
</div>
<!-- START OF PAGE ACCORDION -->

<div class="career-page" id="career1">
    <p class="job-state-title">JOBS: CALIFORNIA</p>
    <ul>
        <li>
            <span class="toggle">
                <svg height="44px" width="44px">
                    <line y2="109.657" x2="288.374" y1="109.657" x1="272.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                    <line y2="21.39" x2="30.374" y1="21.39" x1="14.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                    <line y2="29.39" x2="22.374" y1="13.39" x1="22.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                </svg>
            </span>

            <p>Ecommerce Manager</p>

            <div class="answer_content">
                <div class="job-attributes">
                    <ul>
                        <li><span>Available Positions:</span>2</li>
                        <li><span>Location:</span>NYC Corporate Office</li>
                        <li><span>Reporting To:</span>CEO</li>
                        <li><span>Working With:</span>Finance, India Tech, Distribution Leaders, Design, Product
                        </li>
                        <li><span>Type:</span>Corporate, Full time</li>
                        <li><span>Compensation:</span>Open to discussion</li>
                    </ul>
                </div>

                <div>
                    <p>The role of eCommerce Manager at YOGASMOGA is to oversee the day-today management and
                        operation of a Magento website platform and be responsible for eCommerce P&L. The Manager
                        will work closely with the tech team overseas on projects and implementation and will work
                        with leaders of other distribution channels (e.g. brick & mortar and wholesale) on driving
                        online sales.</p>

                    <p>We are looking for a business-minded but technically savvy, energetic who is eager to join
                        our team and who is comfortable working in a dynamic and intense environment. Successful
                        canditates mush be detail oriented and have strong communication, orgization and execution
                        skills.</p>

                </div>
                <h6>RESPONSIBILITIES</h6>
                <ul>
                    <li>Responsible for P&L of eCommerce platform and daily operations.</li>
                    <li>Collaborate with cross-functional partners to manage all aspects of the eCommerce business
                        including-
                        <ul>
                            <li>business planning</li>
                            <li>content strategy and development</li>
                            <li>promotional compaigns and other online marketing</li>
                            <li>website design</li>
                            <li>customer service</li>
                            <li>web analytics and web technologies</li>
                        </ul>

                    </li>
                    <li>Generate and implement new sales and marketing initiatives (e.g. website content, product,
                        promotions) to increase eCommerce sales and profitability
                    </li>
                    <li>Analyze sources of traffic and the factors that generate and influence traffic that results
                        in sales
                    </li>
                    <li>Plan, define and implement website changes and functional improvements with an overseas tech
                        team.
                    </li>
                    <li>Meet and exceed all agreed performance objectives (sales, conversations, engagement).</li>
                    <li>Act as point person for collaborating with cross-functional partners as project manager to
                        evaluate, prioritize, manage, implement and test eCommerce initiatives.
                    </li>
                    <li>Define and drive the execution of strategic technical product builds with input and support
                        from members of cross functional teams.
                    </li>

                </ul>
                <h6>Desired Skills, Qualifications And Experience</h6>
                <ul>
                    <li>Proven leadership of large eCommerce projects and experience with B2C platforms.</li>
                    <li>Outstanding analytical skills, strong experience interpreting test results & drawing
                        conclusions
                    </li>
                    <li>Extensive knowledge of eCommerce technology and sophisticated analytics.
                        <ul>
                            <li>Experience with Microsoft packages and basis web technologies such as basic HTML,
                                browsers, data files etc.).
                            </li>
                            <li>Experience with Google products such as Analytics and Webmaster tools.</li>
                            <li>Experience with Magento (a plus).</li>
                        </ul>
                    </li>
                    <li>Strong interpersonal and communication skills</li>
                    <li>Strong project management and execution skills.</li>
                </ul>
                <h6>How To Apply:</h6>

                <p>Please email your resume and cover letter to <a href="mailto:jobs@yogasmoga.com">jobs@yogasmoga.com</a>.
                    Please specify what job you are applying for in the subject of the email.</p>

                <p>Thank you for your interest in YOGASMOGA, please note only qualified candidates will be
                    contacted.</p>

                <h6>About YOGASMOGA</h6>

                <p>YOGASMOGA is a designer, manufacturer and retailer of Yoga inspired athletic apparel and
                    accessories. The company's yoga apparel is both fashionable and sporty in nature and has roots
                    in the rapidly growing Yoga movement. YOGASMOGA develops fiber-to-consumer technological
                    solutions to deliver proprietary high performance fabric and athletic gear. While the company
                    works with the most technically advanced fabric and manufacturing technologies. it also pursues
                    a relentless focus on the traditions of Yoga. YOGASMOGA also helps the development of the
                    NAMASKAR foundation, a bracelet driven charity focused on health, education and micro lending in
                    the compan's supply chain countries.</p>


            </div>
        </li>
        <li>
            <span class="toggle">
                <svg height="44px" width="44px">
                    <line y2="109.657" x2="288.374" y1="109.657" x1="272.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                    <line y2="21.39" x2="30.374" y1="21.39" x1="14.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                    <line y2="29.39" x2="22.374" y1="13.39" x1="22.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                </svg>
            </span>

            <p>Marketing Manager</p>

            <div class="answer_content">
                <!-- <span>CAME FROM ?</span>
                <h2 class="job-title">Marketing Manager</h2>-->
                <div class="job-attributes">
                    <ul>
                        <li><span>Available Positions:</span>2</li>
                        <li><span>Location:</span>NYC Corporate Office</li>
                        <li><span>Reporting To:</span>CEO</li>
                        <li><span>Working With:</span>Finance, India Tech, Distribution Leaders, Design, Product
                        </li>
                        <li><span>Type:</span>Corporate, Full time</li>
                        <li><span>Compensation:</span>Open to discussion</li>
                    </ul>
                </div>
                <div>
                    <p>The role of eCommerce Manager at YOGASMOGA is to oversee the day-today management and
                        operation of a Magento website platform and be responsible for eCommerce P&L. The Manager
                        will work closely with the tech team overseas on projects and implementation and will work
                        with leaders of other distribution channels (e.g. brick & mortar and wholesale) on driving
                        online sales.</p>

                    <p>We are looking for a business-minded but technically savvy, energetic who is eager to join
                        our team and who is comfortable working in a dynamic and intense environment. Successful
                        canditates mush be detail oriented and have strong communication, orgization and execution
                        skills.</p>

                    <h6>RESPONSIBILITIES</h6>
                    <ul>
                        <li>Responsible for P&L of eCommerce platform and daily operations.</li>
                        <li>Collaborate with cross-functional partners to manage all aspects of the eCommerce
                            business including-
                            <ul>
                                <li>business planning</li>
                                <li>content strategy and development</li>
                                <li>promotional compaigns and other online marketing</li>
                                <li>website design</li>
                                <li>customer service</li>
                                <li>web analytics and web technologies</li>
                            </ul>

                        </li>
                        <li>Generate and implement new sales and marketing initiatives (e.g. website content,
                            product, promotions) to increase eCommerce sales and profitability
                        </li>
                        <li>Analyze sources of traffic and the factors that generate and influence traffic that
                            results in sales
                        </li>
                        <li>Plan, define and implement website changes and functional improvements with an overseas
                            tech team.
                        </li>
                        <li>Meet and exceed all agreed performance objectives (sales, conversations, engagement).
                        </li>
                        <li>Act as point person for collaborating with cross-functional partners as project manager
                            to evaluate, prioritize, manage, implement and test eCommerce initiatives.
                        </li>
                        <li>Define and drive the execution of strategic technical product builds with input and
                            support from members of cross functional teams.
                        </li>

                    </ul>

                    <h6>Desired Skills, Qualifications And Experience</h6>
                    <ul>
                        <li>Proven leadership of large eCommerce projects and experience with B2C platforms.</li>
                        <li>Outstanding analytical skills, strong experience interpreting test results & drawing
                            conclusions
                        </li>
                        <li>Extensive knowledge of eCommerce technology and sophisticated analytics.
                            <ul>
                                <li>Experience with Microsoft packages and basis web technologies such as basic
                                    HTML, browsers, data files etc.).
                                </li>
                                <li>Experience with Google products such as Analytics and Webmaster tools.</li>
                                <li>Experience with Magento (a plus).</li>
                            </ul>
                        </li>
                        <li>Strong interpersonal and communication skills</li>
                        <li>Strong project management and execution skills.</li>
                    </ul>

                    <h6>How To Apply:</h6>

                    <p>Please email your resume and cover letter to <a href="mailto:jobs@yogasmoga.com">jobs@yogasmoga.com</a>.
                        Please specify what job you are applying for in the subject of the email.</p>

                    <p>Thank you for your interest in YOGASMOGA, please note only qualified candidates will be
                        contacted.</p>

                    <h6>About YOGASMOGA</h6>

                    <p>YOGASMOGA is a designer, manufacturer and retailer of Yoga inspired athletic apparel and
                        accessories. The company's yoga apparel is both fashionable and sporty in nature and has
                        roots in the rapidly growing Yoga movement. YOGASMOGA develops fiber-to-consumer
                        technological solutions to deliver proprietary high performance fabric and athletic gear.
                        While the company works with the most technically advanced fabric and manufacturing
                        technologies. it also pursues a relentless focus on the traditions of Yoga. YOGASMOGA also
                        helps the development of the NAMASKAR foundation, a bracelet driven charity focused on
                        health, education and micro lending in the compan's supply chain countries.</p>


                </div>
            </div>
        </li>

        <li>
            <span class="toggle">
                <svg height="44px" width="44px">
                    <line y2="109.657" x2="288.374" y1="109.657" x1="272.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                    <line y2="21.39" x2="30.374" y1="21.39" x1="14.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                    <line y2="29.39" x2="22.374" y1="13.39" x1="22.374" stroke-miterlimit="10" stroke="#666666"
                          fill="none"/>
                </svg>
            </span>

            <p>Sales Associate</p>

            <div class="answer_content">
                <!--<span> FRIENDLY COMPANY?</span>-->
                <div class="job-attributes">
                    <ul>
                        <li><span>Available Positions:</span>2</li>
                        <li><span>Location:</span>NYC Corporate Office</li>
                        <li><span>Reporting To:</span>CEO</li>
                        <li><span>Working With:</span>Finance, India Tech, Distribution Leaders, Design, Product
                        </li>
                        <li><span>Type:</span>Corporate, Full time</li>
                        <li><span>Compensation:</span>Open to discussion</li>
                    </ul>
                </div>
                <div>
                    <p>The role of eCommerce Manager at YOGASMOGA is to oversee the day-today management and
                        operation of a Magento website platform and be responsible for eCommerce P&L. The Manager
                        will work closely with the tech team overseas on projects and implementation and will work
                        with leaders of other distribution channels (e.g. brick & mortar and wholesale) on driving
                        online sales.</p>

                    <p>We are looking for a business-minded but technically savvy, energetic who is eager to join
                        our team and who is comfortable working in a dynamic and intense environment. Successful
                        canditates mush be detail oriented and have strong communication, orgization and execution
                        skills.</p>

                    <h6>RESPONSIBILITIES</h6>
                    <ul>
                        <li>Responsible for P&L of eCommerce platform and daily operations.</li>
                        <li>Collaborate with cross-functional partners to manage all aspects of the eCommerce
                            business including-
                            <ul>
                                <li>business planning</li>
                                <li>content strategy and development</li>
                                <li>promotional compaigns and other online marketing</li>
                                <li>website design</li>
                                <li>customer service</li>
                                <li>web analytics and web technologies</li>
                            </ul>

                        </li>
                        <li>Generate and implement new sales and marketing initiatives (e.g. website content,
                            product, promotions) to increase eCommerce sales and profitability
                        </li>
                        <li>Analyze sources of traffic and the factors that generate and influence traffic that
                            results in sales
                        </li>
                        <li>Plan, define and implement website changes and functional improvements with an overseas
                            tech team.
                        </li>
                        <li>Meet and exceed all agreed performance objectives (sales, conversations, engagement).
                        </li>
                        <li>Act as point person for collaborating with cross-functional partners as project manager
                            to evaluate, prioritize, manage, implement and test eCommerce initiatives.
                        </li>
                        <li>Define and drive the execution of strategic technical product builds with input and
                            support from members of cross functional teams.
                        </li>

                    </ul>

                    <h6>Desired Skills, Qualifications And Experience</h6>
                    <ul>
                        <li>Proven leadership of large eCommerce projects and experience with B2C platforms.</li>
                        <li>Outstanding analytical skills, strong experience interpreting test results & drawing
                            conclusions
                        </li>
                        <li>Extensive knowledge of eCommerce technology and sophisticated analytics.
                            <ul>
                                <li>Experience with Microsoft packages and basis web technologies such as basic
                                    HTML, browsers, data files etc.).
                                </li>
                                <li>Experience with Google products such as Analytics and Webmaster tools.</li>
                                <li>Experience with Magento (a plus).</li>
                            </ul>
                        </li>
                        <li>Strong interpersonal and communication skills</li>
                        <li>Strong project management and execution skills.</li>
                    </ul>

                    <h6>How To Apply:</h6>

                    <p>Please email your resume and cover letter to <a href="mailto:jobs@yogasmoga.com">jobs@yogasmoga.com</a>.
                        Please specify what job you are applying for in the subject of the email.</p>

                    <p>Thank you for your interest in YOGASMOGA, please note only qualified candidates will be
                        contacted.</p>

                    <h6>About YOGASMOGA</h6>

                    <p>YOGASMOGA is a designer, manufacturer and retailer of Yoga inspired athletic apparel and
                        accessories. The company's yoga apparel is both fashionable and sporty in nature and has
                        roots in the rapidly growing Yoga movement. YOGASMOGA develops fiber-to-consumer
                        technological solutions to deliver proprietary high performance fabric and athletic gear.
                        While the company works with the most technically advanced fabric and manufacturing
                        technologies. it also pursues a relentless focus on the traditions of Yoga. YOGASMOGA also
                        helps the development of the NAMASKAR foundation, a bracelet driven charity focused on
                        health, education and micro lending in the compan's supply chain countries.</p>


                </div>
            </div>
        </li>
    </ul>
</div>









<script type="text/javascript">

    var type = window.location.hash.substr(1);

    jQuery(".sign-in-box h1").html("CAREER");
    jQuery(document).ready(function ($) {

        var questionPos = type.indexOf("?");
        if (questionPos > -1)
            type = type.substring(0, questionPos);

        if (type == "") {
            type = "career1";
        }
        $(".career-page").hide();
        $(".career-page#" + type).show();
        /******* code for accordian ***/
        $(".career-page li .toggle").click(function (e) {
            e.preventDefault();
            $(this).parent().siblings().find(".toggle").removeClass('active');
            $(this).toggleClass('active');
            $(this).parent('li').toggleClass('active');
            $(this).parent('li').find(".answer_content").slideUp('fast');
            $(this).parent('li.active').find(".answer_content").slideDown('fast');
        });
        /******* code for accordian ***/
        $(".sub-nav li a").click(function (e) {
            e.preventDefault();
            var target = $(this).attr('rel');
            $("#"+target).show().siblings(".career-page").hide();

        });

    });
</script>
<style>
    .career-page .job-attributes ul li span {
        display: inline-block;
        font: 11px/19px gothambold;
        margin-right: 6px;
        text-transform: uppercase;
    }

    .career-page .answer_content h6 {
        color: #555;
        font: 11px/19px gothambold;
        text-transform: uppercase;
        margin: 0 0 5px;
    }

    .career-page .answer_content ul {
        list-style: outside none none;

        margin-bottom: 15px;

    }

    .career-page .answer_content ul li {
        list-style: outside none none;
        padding-left: 20px;
        position: relative;
    }

    .career-page .answer_content ul li::before {
        background: #555 none repeat scroll 0 0;
        border-radius: 10px;
        content: "";
        display: inline-block;
        height: 4px;
        left: 0;
        position: absolute;
        top: 7px;
        vertical-align: middle;
        width: 4px;
    }

    .career-page .answer_content p {
        font: 14px/20px GraphikRegular;
        padding: 0 !important;
        margin: 0 0 10px 0 !important;
    }

    .career-page .answer_content ul li li::before {
        background: rgba(0, 0, 0, 0) none repeat scroll 0 0;
        border: 1px solid #555;
        height: 4px;
        width: 4px;
    }


    /***** css custom **/
    .career-page > ul {
        padding: 0 14px;
    }

    .career-page > ul > li:last-child {
        border-bottom: 1px solid #999;
    }

    .career-page > ul > li {
        text-align: left;
        padding: 13px 0;
        border-top: 1px solid #999;
    }

    .career-page > p {
        color: #555;
        font: 19px/75px ITCAvantGardeStd-Bk;
        height: 74px;
        letter-spacing: 1px;
        padding: 0;
        text-align: center;
    }

    .career-page table tr:last-child td {
        border-bottom: 1px solid #999;
    }

    .career-page > ul > li > p {
        font: 12px/18px AvantGarde-Demi;
        letter-spacing: 1px;
        text-transform: uppercase;
    }

    .career-page .toggle {
        position: absolute;
        right: -11px;
        top: 0px;
    }

    .career-page .toggle.active svg line:nth-child(3) {
        stroke: none;
    }

    .career-page ul li > p > span {
        display: inline;
    }

    .career-page ul li.active > p > span {
        display: none;
    }

    .career-page .answer_content {
        display: none;
    }

    .career-page .answer_content > div, .career-page .answer_content > div p {
        font: 14px/20px GraphikRegular;
        padding: 12px 0 0;
    }

    .answer_content .size-chart {
        margin-top: 10px;
    }

    .career-page .answer_content > div p:last-child {
        padding-top: 12px;
        padding-bottom: 17px !important;
    }

    .career-page .answer_content > div p:first-child {
        padding-top: 10px;
    }
  .job-state-title{text-transform:uppercase;}
</style>