<div class="custom-block">
    <div class="ys-bottom">
        <div style="display: block" class="account-nav l-align ys_static_page_dropdown">
            <ul class="sub-nav static_page">
                <li><a rel="1" class="active_link" data-heading="CAREER"  href="javascript:void(0);">California</a></li>
                <li><a rel="2" data-heading="CAREER" href="javascript:void(0);">Connecticut</a></li>
                <li><a rel="3" data-heading="CAREER"  href="javascript:void(0);">Massachusetts</a></li>
                <li><a rel="4" data-heading="CAREER"  href="javascript:void(0);">New Jersey</a></li>
                <li><a rel="5" data-heading="CAREER"  href="javascript:void(0);">New York</a></li>
            </ul>
        </div>
    </div>
</div>

<!-- START OF PAGE ACCORDION -->
        <div class="career-page" id="career1"></div>
<!-- END OF PAGE ACCORDION -->
