<div class="product-grid">
<!-- bannerTop -->
<div class="bannerFluid">
    <img src="{{skin url="images/product/bnr-big1.jpg"}}" alt="Women's Top" />
    <div class="bnrtxt">
        Women's Top
    </div>
</div>
<!-- bannerTop -->

<!-- coloumnLayout -->
<div class="2-columns-wrapper">

<!-- leftNav Category -->
<div class="side-menu-bar f-left l-align">
    <ul class="categorylinks">
        <li><a href="#" class="bld">WHAT’S NEW!</a></li>
        <li><a href="#" class="bld">SHOP THE COLORS!</a></li>
        <li><a href="#" class="bld">TOP SELLERS</a></li>
        <!-- CategoryLink 1 -->
        <li class="sub-head current"><a href="#">TOPS</a>
            <ul class="subnav">
                <li><a href="#">BRAS</a></li>
                <li><a href="#">TANKS / TOPS</a></li>
                <li><a href="#">JACKETS</a></li>
            </ul>
        </li>
        <!-- CategoryLink 1 -->

        <!-- CategoryLink 2 -->
        <li class="sub-head"><a href="#">BOTTOMS</a>
            <ul class="subnav">
                <li><a href="#">PANTS</a></li>
                <li><a href="#">LEGGINGS</a></li>
                <li><a href="#">CROPS</a></li>
                <li><a href="#">SHORTS</a></li>
            </ul>
        </li>
        <!-- CategoryLink 2 -->

        <!-- CategoryLink 3 -->
        <li class="sub-head"><a href="#">ACCESSORIES</a>
            <ul class="subnav">
                <li><a href="#">HEAD BANDS</a></li>
                <li><a href="#">YOGA MATS</a></li>
                <li><a href="#">YOGA TOWELS</a></li>
                <li><a href="#">YOGA FLOPS</a></li>
                <li><a href="#">NAMASKAR BRACELETS</a></li>
            </ul>
        </li>
        <!-- CategoryLink 3 -->
    </ul>
</div>
<!-- leftNav Category -->

<!-- Product Listing -->
<div class="pg-content f-left">
    <!-- productHeading -->
    <h4>Yantra Tanks</h4>
    <!-- productHeading -->

    <!-- productCont -->
    <div class="productCont">
        <div class="prod-img">
            <img src="{{skin url="images/product/dum1.jpg"}}" alt="Women's Top" />
        </div>
        <div class="caption">
            Product<span>$000</span>
        </div>
    </div>
    <!-- productCont -->
    <!-- productCont -->
    <div class="productCont">
        <div class="prod-img">
            <img src="{{skin url="images/product/dum2.jpg"}}" alt="Women's Top" />
        </div>
        <div class="caption">
            Product<span>$000</span>
        </div>
    </div>
    <!-- productCont -->
    <!-- productCont -->
    <div class="productCont">
        <div class="prod-img">
            <img src="{{skin url="images/product/dum3.jpg"}}" alt="Women's Top" />
        </div>
        <div class="caption">
            Product<span>$000</span>
        </div>
    </div>
    <!-- productCont -->
    <!-- productCont -->
    <div class="productCont">
        <div class="prod-img">
            <img src="{{skin url="images/product/dum4.jpg"}}" alt="Women's Top" />
        </div>
        <div class="caption">
            Product<span>$000</span>
        </div>
    </div>
    <!-- productCont -->
    <!-- productCont -->
    <div class="productCont">
        <div class="prod-img">
            <img src="{{skin url="images/product/dum3.jpg"}}" alt="Women's Top" />
        </div>
        <div class="caption">
            Product<span>$000</span>
        </div>
    </div>
    <!-- productCont -->
    <!-- productCont -->
    <div class="productCont">
        <div class="prod-img">
            <img src="{{skin url="images/product/dum1.jpg"}}" alt="Women's Top" />
        </div>
        <div class="caption">
            Product<span>$000</span>
        </div>
    </div>
    <!-- productCont -->
    <!-- productCont -->
    <div class="productCont">
        <div class="prod-img">
            <img src="{{skin url="images/product/dum4.jpg"}}" alt="Women's Top" />
        </div>
        <div class="caption">
            Product<span>$000</span>
        </div>
    </div>
    <!-- productCont -->
    <!-- productCont -->
    <div class="productCont">
        <div class="prod-img">
            <img src="{{skin url="images/product/dum2.jpg"}}" alt="Women's Top" />
        </div>
        <div class="caption">
            Product<span>$000</span>
        </div>
    </div>
    <!-- productCont -->

    <!-- productHeading -->
    <h4>sneak 'n peak bras</h4>
    <!-- productHeading -->

    <!-- productCont -->
    <div class="productCont">
        <div class="prod-img">
            <img src="{{skin url="images/product/dum1.jpg"}}" alt="Women's Top" />
        </div>
        <div class="caption">
            Product<span>$000</span>
        </div>
    </div>
    <!-- productCont -->
    <!-- productCont -->
    <div class="productCont">
        <div class="prod-img">
            <img src="{{skin url="images/product/dum2.jpg"}}" alt="Women's Top" />
        </div>
        <div class="caption">
            Product<span>$000</span>
        </div>
    </div>
    <!-- productCont -->
    <!-- productCont -->
    <div class="productCont">
        <div class="prod-img">
            <img src="{{skin url="images/product/dum3.jpg"}}" alt="Women's Top" />
        </div>
        <div class="caption">
            Product<span>$000</span>
        </div>
    </div>
    <!-- productCont -->
    <!-- productCont -->
    <div class="productCont">
        <div class="prod-img">
            <img src="{{skin url="images/product/dum4.jpg"}}" alt="Women's Top" />
        </div>
        <div class="caption">
            Product<span>$000</span>
        </div>
    </div>
    <!-- productCont -->
    <!-- productCont -->
    <div class="productCont">
        <div class="prod-img">
            <img src="{{skin url="images/product/dum3.jpg"}}" alt="Women's Top" />
        </div>
        <div class="caption">
            Product<span>$000</span>
        </div>
    </div>
    <!-- productCont -->
    <!-- productCont -->
    <div class="productCont">
        <div class="prod-img">
            <img src="{{skin url="images/product/dum1.jpg"}}" alt="Women's Top" />
        </div>
        <div class="caption">
            Product<span>$000</span>
        </div>
    </div>
    <!-- productCont -->
    <!-- productCont -->
    <div class="productCont">
        <div class="prod-img">
            <img src="{{skin url="images/product/dum4.jpg"}}" alt="Women's Top" />
        </div>
        <div class="caption">
            Product<span>$000</span>
        </div>
    </div>
    <!-- productCont -->
    <!-- productCont -->
    <div class="productCont">
        <div class="prod-img">
            <img src="{{skin url="images/product/dum2.jpg"}}" alt="Women's Top" />
        </div>
        <div class="caption">
            Product<span>$000</span>
        </div>
    </div>
    <!-- productCont -->

</div>
<!-- Product Listing -->

</div>
<!-- coloumnLayout -->
</div>
<div class="clear-fix"></div>