<!DOCTYPE HTML>
<html>
<head>
    <meta name="viewport" content="width=device-width">

    <?php
    if ($this->getRequest()->getParam('video') == 'true') {
        ?>
        <meta property="og:image"
              content="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/homepage/video/youtube_fbthumb01.png"/>
        <meta property="og:image"
              content="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/homepage/video/youtube_fbthumb02.png"/>
        <meta property="og:image"
              content="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/homepage/video/youtube_fbthumb03.png"/>
        <meta property="og:title" content="YOGASMOGA | Did You Take a Breath Today?"/>
        <meta property="og:description"
              content="YOGASMOGA makes technical performance clothes for women & men for yoga, running, spin, workouts, and more. Free shipping to US and Canada."/>
        <?php
    } else {
        ?>
        <meta property="og:image"
              content="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/homepage/main_section/fb/facebook-cache-update-01.jpg"/>
        <meta property="og:image"
              content="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/homepage/main_section/fb/facebook-cache-update-02.jpg"/>
        <meta property="og:image"
              content="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/homepage/main_section/fb/facebook-cache-update-03.jpg"/>
        <meta property="og:title" content="YOGASMOGA"/>
        <meta property="og:description"
              content="YOGASMOGA makes technical performance apparel for women & men for yoga, running, spin, workouts, and more. Free shipping to US and Canada."/>
        <?php
    }
    ?>
    <?php echo $this->getChildHtml('head') ?>
    <?php
    //if(Mage::getSingleton('core/session')->getShowVideo())
    if ($this->getRequest()->getParam('video') == 'true') {
//Mage::getSingleton('core/session')->setShowVideo(false);
        ?>
        <script type="text/javascript">
            var loc = window.location;
            history.replaceState("", document.title, loc.pathname + "breathe");
            jQuery(window).load(function () {
                setTimeout(function () {
                    $j("#hmpagevideo").trigger('click')
                }, 1000);
            });
        </script>
        <?php
    }
    ?>
    <script type="text/javascript">
        jQuery(window).load(function () {

            jQuery(".slider_li").css('cursor', 'pointer');
            jQuery(".slider_li").click(function () {
                if (jQuery(this).attr("moveto") != undefined) {
                    var redirectWindow = window.open(jQuery(this).attr('rel'), '_blank');
                    redirectWindow.location;
                }
                else
                    window.location = jQuery(this).attr('rel');
            });

            jQuery("div.showloading").removeClass('showloading');
            setTimeout(function () {
                setfullscreenheight();
            }, 50);
//            var bannerImg = document.getElementById("bannerimg").complete;
//            if(bannerImg){
//                jQuery(".share-strip, .new-arrivals-block").animate({opacity:1},100);
//            }

            jQuery('.namaskar-overlay1').fadeOut('slow');
        });
        jQuery(document).ready(function () {
            setTimeout(function () {
                jQuery("div.page-overlayy").remove();
                jQuery("body").css('overflow', 'auto');
            }, 500);
        });
    </script>
    <div class="namaskar-overlay1">&nbsp;</div>
</head>
<body class="<?php echo $this->getBodyClass() ? $this->getBodyClass() : '' ?>"
      style="margin-right:17px;overflow:hidden;">
<?php echo $this->getChildHtml('after_body_start') ?>
<div class="wrapper">
    <!-- pageOverlay -->
    <div class="page-overlayy" style="background:#fff; position:fixed; top:0; left:0; right:0; bottom:0; z-index:999;">
        &nbsp;</div>
    <!-- pageOverlay -->
    <?php echo $this->getChildHtml('global_notices') ?>
    <!-- shopping cart -->
    <div class="shopping-cart"></div>
    <!-- shopping cart -->
    <div class="page">
        <!-- header -->
        <?php echo $this->getChildHtml('header') ?>
        <!-- header -->
        <!-- pagewrapper -->
        <div id="pagecontainer">
            <!-- sliderBanner -->
			<div    class="home-banner" style="background: url('<?php echo Mage::getUrl('/', array('_secure' => false)); ?>media/wysiwyg/new-design-images/homepage/homepage-hero-imagev2.jpg'); background-size:cover;opacity:1;cursor:pointer"  onclick="window.open('<?php echo Mage::getBaseUrl() . 'women' ?>', '_self');"   >
				
			</div>
           
            <!-- signup new -->
            <div class="clear-fix"></div>
            <!-- middleContainer -->
            <div class="cubix">
                <!-- gridfull -->
                <div class="gridfull ysfabricpart overridefix bucket1">
                    <!-- grid6 -->
                    <div class="grid65 f-left" id="grid1-left">
                        <!-- slider -->
                        <div class="sliderImg" onclick="window.open('<?php echo Mage::getBaseUrl() . 'women/bottoms/zelos-move-legging?color=301 ' ?>', '_self');" style="cursor:pointer">
                            <ul class="gridslider12">


                                <li>
                                    <img onload="showGridContainer(this)" class="img-responsive"
                                         src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/new-design-images/homepage/zelos-crop-bucket-box1v2.jpg' ?>"
                                         title="Shop Women"
                                         alt="Shop Women"/>

                                  <div class="contentSlider sliderContent">
									  <div>
                                            <p class="small-text">FEATURING AURUM<sup>&reg;</sup> MELANGE</p>

                                            <!-- <h3 style="color: #fff!important;" class="large-text">AURUM® <br/>
                                                 SAME GREAT TECH</h3>-->
                                           <p class="large-text">ZELOS MOVE LEGGING</p>
                                            <!--                            <p class="large-text" style="margin-top: -10px;"><span>COLOR INFUSED</span></p>-->
                                            <a href="/women/" class="shopnow-btn"
                                               style="margin-top:1.0366598778004073319755600814664%;background: none !important;width:auto;">Shop Women<!--<span style="color:#ff0000"> &gt;</span>-->	</a>
                                        </div>
										</div>
                                </li>


                            </ul>
                        </div>
                        <!-- slider -->
                    </div>
                    <!-- grid6 -->
                    <!-- grid35 -->
                    <div class="grid35" id="grid1-right">
                        <!-- partOne -->

                        
						<div class="compressBox" onclick="window.open('<?php echo Mage::getBaseUrl() . 'women/bottoms/zelos-move-legging?color=301' ?>', '_self');" style="cursor:pointer">
							
                        </div>
						
                        <!-- partOne -->
                        <!-- partTwo -->
                        <a href="<?php echo $this->getBaseUrl() . 'ys-fabric-tech'; ?>">
                            <div class="iconspartone" id="iconspartone">
                                
								 <div class="row">
								
								<span>
								<img src="<?php echo $this->getSkinUrl('images/new-elements/moisture.png') ?>" alt="Yogasmoga Moisture Wicking"/>
								<span class="iconstxt">ADVANCED MOISTURE MANAGEMENT</span>
								</span>
								<span>
								<img src="<?php echo $this->getSkinUrl('images/new-elements/four-way-stretch.jpg') ?>" alt="Yogasmoga Anti-Pilling"/>
								<span class="iconstxt">4-WAY STRETCH</span>
								</span>

																</div>
																<div class="row">
								<span>
								<img src="<?php echo $this->getSkinUrl('images/new-elements/pilling.png') ?>" alt="Yogasmoga Anti-Pilling"/>
								<span class="iconstxt">RESISTANCE TO PILLING</span>
								</span>
								<span>
								<img src="<?php echo $this->getSkinUrl('images/new-elements/usa.png') ?>" alt="Yogasmoga USA"/>
								<span class="iconstxt">PROUDLY MADE IN THE USA</span>
								</span>
                                </div>
                            </div>
                        </a>
                        <!-- partTwo -->
                    </div>
                    <!-- grid35 -->
                </div>
                <!-- gridfull -->
                <!-- gridfull -->
                <div class="gridfull yscolorpart overridefix bucket1">
					<!-- grid35 -->
                    <div class="grid35">
                        <!-- partOne -->

                        
						<div class="multicolorcont" onclick="window.open('<?php echo Mage::getBaseUrl() . 'men/tops/montauk-polo?color=300' ?>', '_self');" style="cursor:pointer">
							
                        </div>
						
                        <!-- partOne -->
                        <!-- partTwo -->
                        <a href="<?php echo $this->getBaseUrl() . 'ys-fabric-tech'; ?>">
                            <div class="iconspartone" id="iconspartone">
                               <div class="row">
								
								<span>
									<img src="<?php echo $this->getSkinUrl('images/new-elements/four-way-stretch.jpg') ?>" alt="Four Way Stretch"/>
								<span class="iconstxt">4-WAY STRETCH</span>
								</span>
								<span>
								<img src="<?php echo $this->getSkinUrl('images/new-elements/smooth-n-luxurious.jpg') ?>" alt="Smooth & Luxurious"/>
								<span class="iconstxt">SMOOTH &AMP; LUXURIOUS</span>
								</span>
                                </div>
                                <div class="row">

								<span>
								<img src="<?php echo $this->getSkinUrl('images/new-elements/colors-wont-fade.jpg') ?>" alt="Color That Wont't Fade"/>
								<span class="iconstxt">COLORS THAT WON'T FADE</span>
								</span>
								<span>
								<img src="<?php echo $this->getSkinUrl('images/new-elements/pilling.png') ?>" alt="Yogasmoga Anti-Pilling"/>
								<span class="iconstxt">PILLING RESISTANCE</span>
								</span>
                                </div>
                            </div>
                        </a>
                        <!-- partTwo -->
                    </div>
                    <!-- grid35 -->
                    <!-- grid6 -->
                    <div class="grid65 f-right">
                        <!-- slider -->
                        <div class="sliderImg" onclick="window.open('<?php echo Mage::getBaseUrl() . 'men/tops/montauk-polo?color=300' ?>', '_self');" style="cursor:pointer">
                            <ul class="gridslider12">


                                <li>
                                    <img onload="showGridContainer(this)" class="img-responsive"
                                         src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/new-design-images/homepage/montauk-polo-bucket-box1v2.jpg' ?>"
                                         title="Shop Men"
                                         alt="Shop Men"/>

                                    <div class="contentSlider sliderContent">
                                         
                                        <div>
                                           <p class="small-text">FEATURING SONA<sup class="tm">&trade;</sup> PIQUE</p>

                                           <p class="large-text">MONTAUK POLO</p> 
										   <a href="/men" class="shopnow-btn"
                                               style="margin-top:1.0366598778004073319755600814664%;background: none !important;width:auto;">Shop Men</a>
                                        </div>
                                    
                                    </div>
                                </li>


                            </ul>
                        </div>
                        <!-- slider -->
                    </div>
                    <!-- grid6 -->
                    
                </div>
				 <!-- gridfull -->
               
            
                <div class="gridfull factorypart overridefix bucket3">
                    <!-- grid6 -->
                    <div class="grid65 f-left">
                        <!-- slider -->
                        <div class="sliderImg" onclick="window.open('<?php echo Mage::getBaseUrl() . 'made-in-usa' ?>', '_self');" style="cursor:pointer">
                            <img onload="showGridContainer(this)" class="img-responsive"
                                 src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/new-design-images/homepage/made-in-usa-bucket-box1v2.jpg' ?>"
                                 alt="Made In USA" title="Made In USA"/>

                            <div class="contentSlider feat">
                                <div>
                                    <p class="small-text feat">RESPONSIBLE PRODUCTION</p>

                                    <p class="large-text feat">MADE IN USA</p>
                                    <a style="margin-top:1.0366598778004073319755600814664%;background: none !important;width:auto;" href="/women" class="shopnow-btn">Shop What's New</a>
                                </div>
                            </div>
                        </div>
                        <!-- slider -->
                    </div>
                   
                    <!-- grid35 -->
                    <div class="grid35">
                        <!-- partOne --><a href="<?php echo $this->getBaseUrl() . 'made-in-usa'; ?>">
                            <div class="featured-collection-top">
                            </div>
                        </a>
                       
                        <a href="<?php echo $this->getBaseUrl() . 'made-in-usa'; ?>">
                           
							<div class="featured-collection-bottom"></div>
                        </a>
                        <!-- partTwo -->
                    </div>
                    <!-- grid35 -->
                </div>
               
				
				
				 <div class="gridfull nophotoshop overridefix">
				 <div>
                <ul class="slides">	

					 <li class="slider_li" title="YS Fabric Tech" rel="/ys-fabric-tech"
                        style="background: url('<?php echo Mage::getUrl('/', array('_secure' => false)); ?>media/wysiwyg/new-design-images/homepage/proprietary-fabrics.jpg'); background-size:cover; ">
                        

                        <div style="top: 0; padding:0!important" class="over-the-slide ">
                            <div class="banner_text8" style="text-align:center;">
                                <div style="text-transform: uppercase; color: #fff;"
                                     class="banner_avant_grade_demi sweat-detail-bold">30 PROPRIETARY FABRICS<span class="banner-avant-grade-bk-small" style="display:block;">ALL MADE IN USA</span>
                                </div>

                                <div style="text-align:center;" class="text-align-middle">

                                    <a style="color:#fff! important;  margin: 32px 0px 0px ! important; border:none ! important;"
                                       class="learn-more shop-mens1" href="/ys-fabric-tech">Learn More</a>
									   
									
                                </div>
                            </div>

                        </div>
                    </li>
                    </ul>
                </div>
				 </div>
				
				 <div class="gridfull nophotoshop overridefix">
				 <div>
                <ul class="slides">	

					<li class="slider_li" title="Our Ethics" rel="/our-ethics"
                        style="background: url('<?php echo Mage::getUrl('/', array('_secure' => false)); ?>media/wysiwyg/new-design-images/homepage/no-photoshop-homepagev2.jpg'); background-size:cover; ">
                        <!--<img draggable="false"
                             data-src="<?php /*echo Mage::getUrl('/', array('_secure' => true)); */?>media/wysiwyg/new-design-images/homepage/no-photoshop-progressive.jpg"/>-->

                        <div style="top:0; padding:0!important" class="over-the-slide ">
                            <div class="banner_text8" style="text-align:center;">
                                <div style="text-transform: uppercase; color: rgb(255, 255, 255);"
                                     class="banner_avant_grade_demi">#YS<span style="font-family:AvantGardeGothicITCW01X!important;">NO</span>photoshop<!--<span
                                        class="avant_extra_light">here</span>-->
                                </div>

                                <div style="text-align:center;" class="text-align-middle">

                                    <a style="color:#fff! important;  margin: 32px 0px 0px ! important; border:none ! important;"
                                       class="learn-more shop-mens1" href="/our-ethics">Learn More</a>
                                </div>
                            </div>

                        </div>
                    </li>
                    </ul>
                </div>
				 </div>
				 <div class="gridfull nophotoshop overridefix">
				 <div>
                <ul class="slides">	

					<li class="slider_li" title="Our Stores" rel="/our-stores"
                        style="background: url('<?php echo Mage::getUrl('/', array('_secure' => false)); ?>media/wysiwyg/new-design-images/homepage/ten-stores-ysv2.jpg'); background-size:cover; ">
                        

                        <div style="top:0; padding:0!important" class="over-the-slide ">
                            <div class="banner_text7">
                                <div style="text-transform: uppercase; color: #fff;"
                                     class="banner_avant_grade_demi sweat-detail-bold"><span style="display:block">TEN STORES</span><span  style="display:block">AND COUNTING</span>
                                </div>

                                <div style="text-align:center;" class="text-align-middle">

                                    <a style="color:#fff! important;  margin: 32px 0px 0px ! important; border:none ! important;"
                                       class="learn-more shop-mens1" href="/our-stores">See Our Stores</a>
                                </div>
                            </div>

                        </div>
                    </li>
                    </ul>
                </div>
				 </div>
				
				 <div class="gridfull factorypart namaskar-block overridefix bucket3">
                    <!-- grid6 -->
                    <div class="grid65 f-left">
                        <!-- slider -->
                        <div class="sliderImg" onclick="window.open('<?php echo Mage::getBaseUrl() . 'namaskar' ?>', '_self');" style="cursor:pointer">
                            <img onload="showGridContainer(this)" class="img-responsive"
                                 src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/new-design-images/homepage/namaskar-newv2.jpg' ?>"
                                 alt="Carbon6" title="Carbon6"/>

                            <div class="contentSlider feat">
                                <div>
                                    
                                    <a style="margin-top:1.0366598778004073319755600814664%;background: none !important;width:auto;" href="/namaskar" class="shopnow-btn">Learn More</a>
                                </div>
                            </div>
                        </div>
                        <!-- slider -->
                    </div>
                    <!-- grid6 -->
                    <!-- grid35 -->
                    <div class="grid35">
                        <!-- partOne --><a href="<?php echo $this->getBaseUrl() . 'namaskar'; ?>">
                            <div class="featured-collection-top">
                            </div>
                        </a>
                        <!-- partOne -->
                        <!-- partTwo -->
                        <a href="<?php echo $this->getBaseUrl() . 'namaskar'; ?>">
                           <!--<div class="featured-collection-bottom">
								<img class="co" src="<?php echo $this->getSkinUrl('images/new-elements/collection_C6-logo.svg') ?>" alt=""/>
								<img class="seal" src="<?php echo $this->getSkinUrl('images/new-elements/collection_CA-seal.svg') ?>" alt=""/>
							</div>-->
							<div class="featured-collection-bottom"></div>
                        </a>
                        <!-- partTwo -->
                    </div>
                    <!-- grid35 -->
                </div>
				
            </div>
            <div class="text"></div>
            <!-- middleContainer -->
        </div>
        <!-- pagewrapper -->
        <!-- footer -->
        <?php echo $this->getChildHtml('footer'); ?>
        <!-- footer -->
    </div>
    <?php echo $this->getChildHtml('before_body_end'); ?>
</div>
</div>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>

