<!DOCTYPE HTML>
<html>
<head>
    <meta name="viewport" content="width=device-width">
    <?php echo $this->getChildHtml('head') ?>
    <?php
    if ($this->getRequest()->getParam('video') == 'true') {
        ?>
        <meta property="og:image"
              content="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/homepage/video/youtube_fbthumb01.png"/>
        <meta property="og:image"
              content="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/homepage/video/youtube_fbthumb02.png"/>
        <meta property="og:image"
              content="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/homepage/video/youtube_fbthumb03.png"/>
        <meta property="og:title" content="YOGASMOGA | Did You Take a Breath Today?"/>
        <meta property="og:description"
              content="YOGASMOGA makes technical performance clothes for women & men for yoga, running, spin, workouts, and more. Free shipping to US and Canada."/>
        <?php
    } else {
        ?>
        <meta property="og:image"
              content="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/homepage/main_section/fb/facebook-cache-update-01.jpg"/>
        <meta property="og:image"
              content="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/homepage/main_section/fb/facebook-cache-update-02.jpg"/>
        <meta property="og:image"
              content="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>wysiwyg/homepage/main_section/fb/facebook-cache-update-03.jpg"/>
        <meta property="og:title" content="YOGASMOGA"/>
        <meta property="og:description"
              content="YOGASMOGA makes technical performance apparel for women & men for yoga, running, spin, workouts, and more. Free shipping to US and Canada."/>
        <?php
    }
    ?>
    <?php
    if ($this->getRequest()->getParam('video') == 'true') {
        ?>
        <script type="text/javascript">
            var loc = window.location;
            history.replaceState("", document.title, loc.pathname + "breathe");
            jQuery(window).load(function () {
                setTimeout(function () {
                    $j("#hmpagevideo").trigger('click')
                }, 1000);
            });
        </script>
        <?php
    }
    ?>
    <script type="text/javascript">
        jQuery(window).load(function () {
            jQuery(".slider_li").css('cursor', 'pointer');
            jQuery(".slider_li").click(function () {
                if (jQuery(this).attr("moveto") != undefined) {
                    var redirectWindow = window.open(jQuery(this).attr('rel'), '_blank');
                    redirectWindow.location;
                }
                else
                    window.location = jQuery(this).attr('rel');
            });

            jQuery("div.showloading").removeClass('showloading');
            setTimeout(function () {
                setfullscreenheight();
            }, 50);
            jQuery('.namaskar-overlay1').fadeOut('slow');
        });
        jQuery(document).ready(function () {
            setTimeout(function () {
                jQuery("div.page-overlayy").remove();
                jQuery("body").css('overflow', 'auto');
            }, 500);
        });
    </script>
    <div class="namaskar-overlay1">&nbsp;</div>
</head>
<body class="<?php echo $this->getBodyClass() ? $this->getBodyClass() : '' ?>"
      style="margin-right:17px;overflow:hidden;">
<?php echo $this->getChildHtml('after_body_start') ?>
<div class="wrapper">
    <!-- pageOverlay -->
    <div class="page-overlayy" style="background:#fff; position:fixed; top:0; left:0; right:0; bottom:0; z-index:999;">
        &nbsp;</div>
    <!-- pageOverlay -->
    <?php echo $this->getChildHtml('global_notices') ?>
    <!-- shopping cart -->
    <div class="shopping-cart"></div>
    <!-- shopping cart -->
    <div class="page">
        <!-- header -->
        <?php echo $this->getChildHtml('header') ?>
        <!-- header -->
        <!-- pagewrapper -->
        <div id="pagecontainer">

            <h1 style="display:none"><?php echo $this->__('YOGASMOGA: Yoga Clothes, Running, Spin and Athletic Workout Apparel')?></h1>

            <!-- sliderBanner -->
			<?php if(false):?>
			<div  class="home-banner" style="background: url('<?php echo Mage::getUrl('/', array('_secure' => false)); ?>media/wysiwyg/new-design-images/homepage/EDITORIAL_SHERELLE_2_392.jpg') top center; background-size:cover;opacity:1;cursor:pointer;position:relative;"  onclick="window.open('/women/bottoms/leggings/zelos-legging?color=367', '_blank');"   >
			</div>
			<?php endif;?>
			<?php if(true):?>
			<div class="flexslider home-slider" id="bucket1_slider">
                <ul class="slides">
					<li class="slider_li" title="NAMASK&Aacute;R" rel="/women" moveto="/women" style="background: url('<?php echo Mage::getUrl('/', array('_secure' => false)); ?>media/wysiwyg/new-design-images/homepage/MothersDay-Desktop.jpg') 0% 0% / cover; height: 705.527px; width: 100%; float: left; margin-right: -100%; position: relative; opacity: 0; display: block; z-index: 1; cursor: pointer;">
					    <?php /* ?><div  style="padding:0!important" class="over-the-slide ">
                            <div class="banner_text4">
                                <div class="banner_avant_grade_demi"
                                     style="text-transform: uppercase; color: rgb(255, 255, 255);">
                                    <div style="display:block;"><span style="display:block;padding-bottom:2%!important">There is One Constant That <br/>Connects Us - MOM </span>
									 <span class="banner-avant-grade-bk-small">
										 <span style="display:block;">Receive 30% Off On-Line only. </span>
										 <span style="display:block; font-size:20px">Plus Get a Free Scarf and a Limited Edition Card <br/>for Orders Over $100.</span>
										 <span style="display:block;padding-top:2%!important" class="banner_avant_grade_demi code">UseCode: OURMOM</span>
									</span>
                                    </div>
                                </div>
							</div>

                        </div><?php */?>
					</li>
				</ul>
			</div>
			<?php endif?>	
			<div class="clear-fix"></div>
            <!-- middleContainer -->
            <div class="cubix">
                <!-- gridfull -->
                <div class="gridfull ysfabricpart overridefix bucket1">
                    <!-- grid6 -->
                    <div class="grid65 f-left" id="grid1-left">
                        <!-- slider -->
                        <div class="sliderImg" onclick="window.open('<?php echo Mage::getBaseUrl() . 'women/bottoms/crops/vivacity-crop?color=297 ' ?>', '_self');" style="cursor:pointer">
                            <ul class="gridslider12">


                                <li>
                                    <img onload="showGridContainer(this)" class="img-responsive"
                                         src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/new-design-images/homepage/vivacity-crop-bucket-box1v3.jpg' ?>"
                                         title="Shop Women"
                                         alt="Shop Women"/>

                                    <div class="contentSlider sliderContent">
                                        <div>
                                            <!--<p class="small-text">FEATURING AURUM<sup>&reg;</sup> MELANGE</p>-->
                                            <p class="small-text">FEATURING AURUM&reg; </p>
                                            <!-- <h3 style="color: #fff!important;" class="large-text">AURUM® <br/>
                                                 SAME GREAT TECH</h3>-->
                                            <p class="large-text">VIVACITY CROP</p>
                                            <!--                            <p class="large-text" style="margin-top: -10px;"><span>COLOR INFUSED</span></p>-->
                                            <a href="/women/" class="shopnow-btn"
                                               style="margin-top:1.0366598778004073319755600814664%;background: none !important;width:auto;">Shop Women<!--<span style="color:#ff0000"> &gt;</span>-->	</a>
                                        </div>
                                    </div>
                                </li>


                            </ul>
                        </div>
                        <!-- slider -->
                    </div>
                    <!-- grid6 -->
                    <!-- grid35 -->
                    <div class="grid35" id="grid1-right">
                        <!-- partOne -->


                        <div class="compressBox" onclick="window.open('<?php echo Mage::getBaseUrl() . 'women/bottoms/crops/vivacity-crop?color=297' ?>', '_self');" style="cursor:pointer">

                        </div>

                        <!-- partOne -->
                        <!-- partTwo -->
                        <a href="<?php echo $this->getBaseUrl() . 'ys-fabric-tech'; ?>">
                            <div class="iconspartone" id="iconspartone">

                                <div class="row">

								<span>
								<img src="<?php echo $this->getSkinUrl('images/new-elements/advanced-moisture-v3.svg') ?>" alt="Yogasmoga Moisture Wicking"/>
								<span class="iconstxt">Advanced moisture management</span>
								</span>
								<span>
								<img src="<?php echo $this->getSkinUrl('images/new-elements/high-quality-v3.svg') ?>" alt="Yogasmoga Anti-Pilling"/>
								<span class="iconstxt">High Quality Strech</span>
								</span>

                                </div>
                                <div class="row">
								<span>
								<img src="<?php echo $this->getSkinUrl('images/new-elements/eco-friendly-dyeing.svg') ?>" alt="Yogasmoga Eco-Friendly Dyeing"/>
								<span class="iconstxt">Eco-Friendly Dyeing</span>
								</span>
								<span>
								<img src="<?php echo $this->getSkinUrl('images/new-elements/color-that-wont-fade.svg') ?>" alt="Yogasmoga Color That Won't Fade"/>
								<span class="iconstxt">Color That Won't Fade</span>
								</span>
                                </div>
                            </div>
                        </a>
                        <!-- partTwo -->
                    </div>
                    <!-- grid35 -->
                </div>
                <!-- gridfull -->
                <!-- gridfull -->
                <div class="gridfull yscolorpart overridefix bucket1">
                    <!-- grid35 -->
                    <div class="grid35">
                        <!-- partOne -->


                        <div class="multicolorcont" onclick="window.open('<?php echo Mage::getBaseUrl() . 'men/tops/tanks/monsoon-apex-tank?color=184' ?>', '_self');" style="cursor:pointer">

                        </div>

                        <!-- partOne -->
                        <!-- partTwo -->
                        <a href="<?php echo $this->getBaseUrl() . 'ys-fabric-tech'; ?>">
                            <div class="iconspartone" id="iconspartone">
                                <div class="row">

								<span>
									<img src="<?php echo $this->getSkinUrl('images/new-elements/high-breathability-icon.svg') ?>" alt="Yogasmoga High Breathability"/>
								<span class="iconstxt">High Breathability</span>
								</span>
								<span>
								<img src="<?php echo $this->getSkinUrl('images/new-elements/anti-stink-icon.svg') ?>" alt="Yogasmoga Anti-Stink"/>
								<span class="iconstxt">Anti-Stink</span>
								</span>
                                </div>
                                <div class="row">

								<span>
								<img src="<?php echo $this->getSkinUrl('images/new-elements/quick-dry-icon.svg') ?>" alt="Yogasmoga Quick Dry"/>
								<span class="iconstxt">Quick Dry</span>
								</span>
								<span>
								<img src="<?php echo $this->getSkinUrl('images/new-elements/pilling-resistance-icon.svg') ?>" alt="Yogasmoga Pilling Resistance"/>
								<span class="iconstxt">Pilling Resistance</span>
								</span>
                                </div>
                            </div>
                        </a>
                        <!-- partTwo -->
                    </div>
                    <!-- grid35 -->
                    <!-- grid6 -->
                    <div class="grid65 f-right">
                        <!-- slider -->
                        <div class="sliderImg" onclick="window.open('<?php echo Mage::getBaseUrl() . 'men/tops/tanks/monsoon-apex-tank?color=184' ?>', '_self');" style="cursor:pointer">
                            <ul class="gridslider12">


                                <li>
                                    <img onload="showGridContainer(this)" class="img-responsive"
                                         src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/new-design-images/homepage/monsoon-tank-bucket-box1v3.jpg' ?>"
                                         title="Shop Men"
                                         alt="Shop Men"/>

                                    <div class="contentSlider sliderContent">

                                        <div>
                                            <!--<p class="small-text">FEATURING SONA<sup class="tm">&trade;</sup> PIQUE</p>-->
                                            <p class="small-text">FEATURING AURUM&reg; 1064</p>
                                            <p class="large-text">MONSOON TANK</p>
                                            <a href="/men" class="shopnow-btn"
                                               style="margin-top:1.0366598778004073319755600814664%;background: none !important;width:auto;">Shop Men</a>
                                        </div>

                                    </div>
                                </li>


                            </ul>
                        </div>
                        <!-- slider -->
                    </div>
                    <!-- grid6 -->

                </div>
                <!-- gridfull -->


                <div class="gridfull factorypart overridefix bucket1">
                    <!-- grid6 -->
                    <div class="grid65 f-left">
                        <!-- slider -->
                        <div class="sliderImg" onclick="window.open('<?php echo Mage::getBaseUrl() . 'made-in-usa' ?>', '_self');" style="cursor:pointer">
                            <img onload="showGridContainer(this)" class="img-responsive"
                                 src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/new-design-images/homepage/made-in-usa-box1v3.jpg' ?>"
                                 alt="Made In USA" title="Made In USA"/>

                            <div class="contentSlider feat">
                                <div>
                                    <p class="small-text feat">RESPONSIBLE PRODUCTION</p>

                                    <p class="large-text feat">MADE IN USA</p>
                                    <a style="margin-top:1.0366598778004073319755600814664%;background: none !important;width:auto;" href="/women" class="shopnow-btn">Shop What&prime;s New</a>
                                </div>
                            </div>
                        </div>
                        <!-- slider -->
                    </div>

                    <!-- grid35 -->
                    <div class="grid35">
                        <!-- partOne --><a href="<?php echo $this->getBaseUrl() . 'made-in-usa'; ?>">
                            <div class="featured-collection-top">
                            </div>
                        </a>

                        <a href="<?php echo $this->getBaseUrl() . 'made-in-usa'; ?>">

                            <div class="featured-collection-bottom"></div>
                        </a>
                        <!-- partTwo -->
                    </div>
                    <!-- grid35 -->
                </div>



                <div class="gridfull nophotoshop overridefix">
                    <div>
                        <ul class="slides">

                            <li class="slider_li" title="YS Fabric Tech" rel="/ys-fabric-tech"
                                style="background: url('<?php echo Mage::getUrl('/', array('_secure' => false)); ?>media/wysiwyg/new-design-images/homepage/proprietary-fabricsv5.jpg'); background-size:cover; ">


                                <div style="top: 0; padding:0!important" class="over-the-slide ">
                                    <div class="banner_text8" style="text-align:center;">
                                        <div style="text-transform: uppercase; color: #fff;"
                                             class="banner_avant_grade_demi sweat-detail-bold">30 PROPRIETARY FABRICS<span class="banner-avant-grade-bk-small" style="display:block;">ALL MADE IN USA</span>
                                        </div>

                                        <div style="text-align:center;" class="text-align-middle">

                                            <a style="color:#fff! important;  margin: 32px 0px 0px ! important; border:none ! important;"
                                               class="learn-more shop-mens1" href="/ys-fabric-tech">Learn More</a>


                                        </div>
                                    </div>

                                </div>
                            </li>
                        </ul>
                    </div>
                </div>

                <div class="gridfull nophotoshop overridefix">
                    <div>
                        <ul class="slides">

                            <li class="slider_li" title="Our Ethics" rel="/our-ethics"
                                style="background: url('<?php echo Mage::getUrl('/', array('_secure' => false)); ?>media/wysiwyg/new-design-images/homepage/no-photoshop-homepagev3.jpg'); background-size:cover; ">
                                <!--<img draggable="false"
                             data-src="<?php /*echo Mage::getUrl('/', array('_secure' => true)); */?>media/wysiwyg/new-design-images/homepage/no-photoshop-progressive.jpg"/>-->

                                <div style="top:0; padding:0!important" class="over-the-slide ">
                                    <div class="banner_text8" style="text-align:center;">
                                        <div style="text-transform: uppercase; color: rgb(255, 255, 255);"
                                             class="banner_avant_grade_demi">#YS<span style="font-family:AvantGardeGothicITCW01X!important;">NO</span>photoshop<!--<span
                                        class="avant_extra_light">here</span>-->
                                        </div>

                                        <div style="text-align:center;" class="text-align-middle">

                                            <a style="color:#fff! important;  margin: 32px 0px 0px ! important; border:none ! important;"
                                               class="learn-more shop-mens1" href="/our-ethics">Learn More</a>
                                        </div>
                                    </div>

                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
				<?php if(false):?>
                <div class="gridfull nophotoshop overridefix" style="display:none;">
                    <div>
                        <ul class="slides">

                            <li class="slider_li" title="Our Stores" rel="/our-stores"
                                style="background: url('<?php echo Mage::getUrl('/', array('_secure' => false)); ?>media/wysiwyg/new-design-images/homepage/ten-stores-ysv3.jpg'); background-size:cover; ">


                                <div style="top:0; padding:0!important" class="over-the-slide ">
                                    <div class="banner_text7">
                                        <div style="text-transform: uppercase; color: #fff;"
                                             class="banner_avant_grade_demi sweat-detail-bold"><span style="display:block">NINE STORES</span><span  style="display:block">AND COUNTING</span>
                                        </div>

                                        <div style="text-align:center;" class="text-align-middle">

                                            <a style="color:#fff! important;  margin: 32px 0px 0px ! important; border:none ! important;"
                                               class="learn-more shop-mens1" href="/our-stores">See Our Stores</a>
                                        </div>
                                    </div>

                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
				<?php endif;?>
                <div class="gridfull factorypart namaskar-block overridefix bucket3">
                    <!-- grid6 -->
                    <div class="grid65 f-left">
                        <!-- slider -->
                        <div class="sliderImg" onclick="window.open('<?php echo Mage::getBaseUrl() . 'namaskar' ?>', '_self');" style="cursor:pointer">
                            <img onload="showGridContainer(this)" class="img-responsive"
                                 src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/new-design-images/homepage/namaskar-newv2.jpg' ?>"
                                 alt="Namaskar" title="Namaskar"/>

                            <div class="contentSlider feat">
                                <div>

                                    <a style="margin-top:1.0366598778004073319755600814664%;background: none !important;width:auto;" href="/namaskar" class="shopnow-btn">Learn More</a>
                                </div>
                            </div>
                        </div>
                        <!-- slider -->
                    </div>
                    <!-- grid6 -->
                    <!-- grid35 -->
                    <div class="grid35">
                        <!-- partOne --><a href="<?php echo $this->getBaseUrl() . 'namaskar'; ?>">
                            <div class="featured-collection-top">
                            </div>
                        </a>
                        <!-- partOne -->
                        <!-- partTwo -->
                        <a href="<?php echo $this->getBaseUrl() . 'namaskar'; ?>">
                            <!--<div class="featured-collection-bottom">
								<img class="co" src="<?php echo $this->getSkinUrl('images/new-elements/collection_C6-logo.svg') ?>" alt=""/>
								<img class="seal" src="<?php echo $this->getSkinUrl('images/new-elements/collection_CA-seal.svg') ?>" alt=""/>
							</div>-->
                            <div class="featured-collection-bottom"></div>
                        </a>
                        <!-- partTwo -->
                    </div>
                    <!-- grid35 -->
                </div>

            </div>
            <div class="text"></div>
            <!-- middleContainer -->
        </div>
        <!-- pagewrapper -->
        <!-- footer -->
        <?php echo $this->getChildHtml('footer'); ?>
        <!-- footer -->
    </div>
    <?php echo $this->getChildHtml('before_body_end'); ?>
</div>
</div>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
