<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('css/cart.css'); ?>" media="all" />
<style type="text/css">
ul.messages
{
    display: none;
}
</style>
<div class="page-title">
    <h1><?php echo $this->__('Gift of ys') ?></h1>
</div>
<h2 class="giftcard-balance">Your Balance : <?php echo Mage::helper('core')->currency($this->getCurrentBalance()); ?></h2>
<form name="giftcardForm" id="giftcardformmyaccount" action="<?php echo $this->getUrl('customer/giftcards/apply') ?>" method="post">
<table class="myaccount-redeem-giftcard">
    <tr>
        <td>
            <table class="inputtable">
                <tr>
                    <td class="label"><label for="giftcard_code"><?php echo $this->__('Gift Card Code') ?></label></td>
                    <td class="inputholder">
                        <input id="giftcard_code" name="giftcard_code" value="" class="requiredfield" defaulterrormsg="Gift Card Code is required" type="text" />
                    </td>
                </tr>
                <tr>
                    <td class="errortext" colspan="2">
                        <div>Gift Card Code is required.</div>
                        <?php
                            if(strpos(Mage::getSingleton('core/session')->getGlobalMessage(),"error-msg") !== false)
                            {
                                ?>
                                    <div style="display: block;"><?php echo strip_tags(Mage::getSingleton('core/session')->getGlobalMessage()); ?></div>            
                                <?php
                            }
                        ?>
                    </td>
                </tr>
            </table>
        </td>
        <td>
            <button type="submit" title="<?php echo $this->__('Redeem') ?>" class="button btn-redeem" value="<?php echo $this->__('Redeem') ?>"><span><span><?php echo $this->__('Redeem') ?></span></span></button>
        </td>
    </tr>
</table>
</form>
<?php return; ?>
<form name="giftcardForm" action="<?php echo $this->getUrl('customer/giftcards/apply') ?>" method="post">
<table border="0" cellpadding="1" cellspacing="1">
  <tr>
    <td><?php echo $this->__('My Gift Card balance') ?>:</td>
    <td><?php echo Mage::helper('core')->currency($this->getCurrentBalance()); ?></td>
  </tr>
  <tr>
    <td><?php echo $this->__('Enter the Gift Card code') ?>:</td>
    <td><input class="input-text" id="giftcard_code" name="giftcard_code" value="" /></td>
  </tr>
  <tr>
    <td colspan="2" align="center"><button type="button" title="<?php echo $this->__('Redeem') ?>" class="button" onclick="document.forms['giftcardForm'].submit()" value="<?php echo $this->__('Redeem') ?>"><span><span><?php echo $this->__('Redeem') ?></span></span></button></td>
  </tr>
</table>
</form>