<div class="gift-card">
    
    <?php if (Mage::helper('customer')->isLoggedIn()) : ?>
    <h2 class="giftofyshead">GIFT OF YS</h2>
    <div class="discount-form">
        <form></form>
        <form method="post" action="<?php echo $this->getUrl('*/*/giftcardActive'); ?>" name="giftcardActive">
        <div class="input-box">
            <input type="checkbox" value="1" name="giftcard_use" id="giftcard_use" class="checkbox" onclick="document.forms['giftcardActive'].submit()" <?php echo Mage::getSingleton('giftcards/session')->getActive() ? 'checked="checked"' : '' ?> />
            <label for="giftcard_use"><?php echo $this->__('Redeem my <a class="red" target="_blank" href="'.$this->getUrl('gift_of_ys').'">Gift of YS Card</a>. Balance : '); ?>&nbsp;<?php echo Mage::helper('core')->currency(Mage::helper('giftcards')->getCustomerBalance(Mage::getSingleton('customer/session')->getCustomer()->getId())); ?></label>
        </div>
        </form>
        <a href="<?php echo Mage::getUrl('',array('_secure'=>true)); ?>customer/giftcards/balance" class="rdm">
            Add a Gift of YS card to your account
        </a>
    </div>
    <?php else : ?>
    <h2>Do you have a <a target="_blank" href="<?php echo $this->getUrl('gift_of_ys'); ?>">Gift of YS</a> Card?</h2>
    <div class="giftcard-login-msg">
        Please login to use your <a target="_blank" href="<?php echo $this->getUrl('gift_of_ys'); ?>">Gift of YS</a> cards.
        <br />
        <a href="<?php  echo Mage::helper('core/url')->getHomeUrl(); ?>customer/account/login?goto=cart">
            <button value="<?php echo $this->__('Login') ?>" class="button btn-login" title="Login" type="button"><span><span><?php echo $this->__('Login') ?></span></span></button>
        </a>
    </div>
    <?php endif; ?>
</div>
<script type="text/javascript">
//&lt;![CDATA[
    jQuery(document).ready(function($){
    });

var giftcardForm = new VarienForm('giftcard-form');
giftcardForm.submit = function (isRemove) {
    console.log('after');
    if (isRemove) {
        //$('giftcard_code').addClassName('required-entry');
        $('giftcard_use').checked = "checkbox";
        $('giftcard_use').value = "1";
    } else {
        $('giftcard_code').removeClassName('required-entry');
        $('giftcard_use').value = "0";
    }
    return VarienForm.prototype.submit.bind(giftcardForm)();
}
//]]&gt;
</script>