<?php
/**
 * J2T RewardsPoint2
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@j2t-design.com so we can send you a copy immediately.
 *
 * @category   Magento extension
 * @package    RewardsPoint2
 * @copyright  Copyright (c) 2009 J2T DESIGN. (http://www.j2t-design.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
 ?>
 <link media="all" href="<?php echo $this->getSkinUrl('css/cart.css'); ?>" type="text/css" rel="stylesheet">
 <div class="refer-friend">
<div class="page-title">
    <h1><?php echo $this->__('SHARE WITH FRIENDS') ?></h1>
</div>
<script>
    jQuery(document).ready(function($){
        function copytoClipboard(){
            var link =$(".invite_link").html();
            //alert(link);
            $(".cpy_lnk").attr("data-clipboard-text",link);
            var client = new ZeroClipboard($(".cpy_lnk"));

            client.on( "ready", function( readyEvent ) {
                //alert("done");
                client.on( "aftercopy", function( event ) {

                } );
            } );


        }
        copytoClipboard();
    });
</script>

<?php if($this->isAddthis() || $this->isPermanentLink()):?>
<div class="refer-box">
    <?php if($this->isPermanentLink()):?>
        <p class="your_invite_link" data-clipboard-text=""><?php echo $this->__('your invite link') ?></p>
        <p class="invite_link"> <?php echo $this->getReferringUrl() ?></p>
        <p class="cpy_lnk">Copy link</p>
    <?php endif;?>


    <?php if($this->isAddthis()):?>
    <div class="box-account box-recent">
        <fieldset class="group-select">
            <h5><?php echo $this->__('Share referring link') ?></h5>
            <ul>
                <li>
                    <div class="input-box">
                        <label for="j2t-share-title"><?php echo $this->__('Sharing title (may not be used)') ?></label><br />
                        <input onkeyup="j2tReinitializeAddThis();" type="text" name="j2t-share-title" id="j2t-share-title" value="<?php echo $this->__('Great deals here!');?>" class="input-text" />
                    </div>
                    <div class="input-box">
                        <label for="j2t-share-text"><?php echo $this->__('Sharing text (may not be used)') ?></label><br />
                        <textarea onkeyup="j2tReinitializeAddThis();" id="j2t-share-text" name="j2t-share-text" cols="100" rows="5" class="input-text"><?php echo $this->__('Visit this for great deals!');?></textarea>
                    </div>
                </li>
            </ul>
        </fieldset>
    
        <br />
        
        <!-- AddThis Button BEGIN -->
        <?php echo Mage::getStoreConfig('rewardpoints/registration/referral_addthis_code', Mage::app()->getStore()->getId());?>
        <script type="text/javascript">
            var addthis_share =
            {
                url: "<?php echo $this->getReferringUrl();?>",
                title: $('j2t-share-title').value,
                description: $('j2t-share-text').value
            }
        </script>
        
        <script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=<?php echo Mage::getStoreConfig('rewardpoints/registration/referral_addthis_account', Mage::app()->getStore()->getId());?>"></script>
        <!-- AddThis Button END -->
        
        
        <?php /*?>
        <a class="addthis_button" id="j2t-post-share" addthis:url="<?php echo $this->getReferringUrl();?>" addthis:title="<?php echo $this->__('Great deals here!');?>" addthis:description="<?php echo $this->__('Visit this for great deals!');?>"></a>
        <script type="text/javascript">
            function j2tReinitializeAddThis(){
              if (window.addthis){
                 $('j2t-post-share').writeAttribute('addthis:title', $('j2t-share-title').value);
                 $('j2t-post-share').writeAttribute('addthis:description', $('j2t-share-text').value);
                 window.addthis.ost = 0;
                 window.addthis.ready();
              }
           }
            //addthis.button('#j2t-post-share', {}, {url: "<?php echo $this->getReferringUrl();?>", title: $('j2t-share-title').value, description: $('j2t-share-text').value});
            addthis.button('#j2t-post-share');
        </script>
        <?php */?>
    </div>
    <?php endif;?>
</div>
<?php endif;?>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getUrl('rewardpoints/index/referral/') ?>" method="post" id="form-validate">
    <div class="box-invite">
        <fieldset class="group-select" id="j2t-referral-lines">
            <?php /*?><input type="hidden" value="Il1NwrpfsCuSmp03" name="form_key"/><?php */?>
            <?php echo $this->getBlockHtml('formkey')?>
            <p><?php echo $this->__('Invite friends to YOGASMOGA.') ?></p>
            <div class="invite_form">
            <ul class="form-list">
                <li class="fields">
                    <div class="j2t-rewardpoints-referral">
                        <div class="field j2t-rewardpoints-name">
                            <input type="text" name="name[]" value="" placeholder="<?php echo $this->__('Friend\'s name') ?>" title="<?php echo $this->__('Friend\' name') ?>" class="required-entry input-text" id="name" />
                        </div>
                        <div class="field j2t-rewardpoints-email" style="width:100%;">
                            <input type="text" name="email[]" placeholder="<?php echo $this->__('Friend\'s email address') ?>" value="" title="<?php echo $this->__('Friend\'s email address') ?>" class="required-entry input-text" id="email" />
                        </div>
                    </div>
                </li>
            </ul>
            <a class="right" id="j2t-add-line" href="javascript:j2t_add_line();" title="<?php echo $this->__('Add new line') ?>">
               Add Another <span>+</span>
            </a>
			<button class="btn-invite button" type="submit"><span><span><?php echo $this->__('INVITE') ?></span></span></button>
            </div>
        </fieldset>
        
        <script type="text/javascript">
            var elmt_id_j2t = 0;
            function j2t_add_line(){
                var form_list_ul = $('j2t-add-line').up().down("ul");

                var form_list_ul_clone = Element.clone(form_list_ul, true);

                var form_list_ul_clone = form_list_ul.cloneNode(true);
                
//                form_list_ul_clone.down("#label-name").id = "label-name-"+elmt_id_j2t;
                form_list_ul_clone.down("#name").id = "name-"+elmt_id_j2t;
//                form_list_ul_clone.down("#label-email").id = "label-email-"+elmt_id_j2t;
                form_list_ul_clone.down("#email").id = "email-"+elmt_id_j2t;
                
                form_list_ul_clone.down("#name-"+elmt_id_j2t).value = "";
                form_list_ul_clone.down("#email-"+elmt_id_j2t).value = "";
                
                var del_img = document.createElement('p');
                del_img.setAttribute('class', 'remove_link');
                del_img.appendChild(document.createTextNode("Remove"));
                form_list_ul_clone.down(".j2t-rewardpoints-email").insert({
                    bottom: del_img
                });
                del_img.observe('click', function(event) {
                    Event.element(event).up("ul").remove();
                });
                
                $('j2t-add-line').insert({ before: form_list_ul_clone });
                elmt_id_j2t++;
            }
        </script>
    </div>
</form>

<!--<div class="clearer" style="clear:both; margin:0 0 40px;">&nbsp;</div>-->
<script type="text/javascript">
    var dataForm = new VarienForm('form-validate', true);
</script>
<?php //$_referred = $this->getReferred();?>
<!--<h3 class="subtitle">Keep track of your invites</h3>
<?php /*if($_referred->getSize()): */?>
<?php /*echo $this->getPagerHtml() */?>
<table cellspacing="0" class="data-table" id="referred-friends-table">
    <thead>
        <tr>
            <?php /**/?><th><?php /*echo $this->__('Full Name') */?></th><?php /**/?>
            <th><?php /*echo $this->__('Email') */?></th>
            <!--<th><?php /*echo $this->__('Registered?') */?></th>-->
            <th><?php /*echo $this->__('First order?') */?></th>
        </tr>
    </thead>
<!--    <tbody>-->
        <?php /*$_odd = ''; */?>
        <?php /*foreach ($_referred as $_friend): */?>
<!--            <tr>-->
<!--                --><?php ///**/?><!--<td>--><?php ///*echo $_friend->getRewardpoints_referral_name() */?><!--</td>--><?php ///**/?>
<!--                <td>--><?php ///*echo $_friend->getRewardpoints_referral_email() */?><!--</td>-->
                <!--<td><?php /*echo $_friend->getRewardpoints_referral_child_id() ? $this->__('yes') : $this->__('no') */?></td>-->
<!--                <td class="a-right">--><?php ///*echo $_friend->getRewardpoints_referral_status() ? $this->__('yes') : $this->__('no') */?><!--</td>-->
<!--            </tr>-->
        <?php /*endforeach; */?>
<!--    </tbody>-->
<!--</table>-->
<?php /*echo $this->getPagerHtml() */?>
<?php /*else: */?>
<!--    <p>--><?php ///*echo $this->__('After you invite some of your friends you will be able to keep track of their invitations here..'); */?><!--</p>-->
<?php /*endif */?>
</div>