<?php
    echo $this->getLayout()->createBlock('core/template')->setTemplate('page/html/icons_lib.phtml')->toHtml();

    $inviteFriendClassIfLogged = '';

    if(!Mage::getSingleton('customer/session')->isLoggedIn())
        $inviteFriendClassIfLogged = 'invite-friend';
?>
<h1 style="display:none">YOGASMOGA</h1>
<div class="nav is-fixed" role="navigation">

	  <span class="nav-toggle">
		  <div class="icon-menu">
              <svg width="44px" height="43.993px">
                  <use xlink:href="#ys_menu_icon"></use>
              </svg>

          </div>
	  </span>

    <div class="ys-text">
        <a href="<?php echo $this->getUrl('') ?>">
            <!--        <img  src="-->
            <?php //echo $this->getSkinUrl('images/yogasmoga_logo.png') ?><!--" alt="yogasmoga"/>-->
            <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg"
                 xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                 width="154px" height="44px" viewBox="0 0 154 44" enable-background="new 0 0 154 44"
                 xml:space="preserve">
            <use xlink:href="#yogasmoga_logo_white"></use>
</svg>


        </a>
    </div>

    <?php
    $cartTotal = $this->helper('checkout/cart')->getQuote()->getGrandTotal();
    $cartItemsCount = Mage::helper('checkout/cart')->getCart()->getItemsCount();

    /******** original code ***********/
    $cartItemsQuantity = Mage::helper('checkout/cart')->getCart()->getItemsQty();
    /******** original code ***********/

/*************** after adding gift set ***********************/
    // disabling gift set
    if(false) {
        $session = Mage::getSingleton('checkout/session');
        $cartItemsQuantity = 0;
        foreach ($session->getQuote()->getAllItems() as $item) {
            if (Mage::getModel('catalog/product')->load($item->getProductId())->getTypeID() == "configurable") {
                $buyRequest = $item->getBuyRequest();
                $product_type = $buyRequest['type'];

                if (isset($product_type) && $product_type == "gift-bundled")
                    continue;

                //$cartItemsQuantity = $cartItemsQuantity + $item->getQty();
                $cartItemsQuantity++;
            } else if (Mage::getModel('catalog/product')->load($item->getProductId())->getTypeID() == "simple")
                ;
            else
                ++$cartItemsQuantity;
        }
    }
/*************** after adding gift set ***********************/
    ?>


    <?php if ($cartItemsQuantity > '0') { ?>
        <div class="shoping-cart" onclick="window.location='<?php echo $this->getUrl('checkout/onepage'); ?>'">
            <svg xml:space="preserve" enable-background="new 0 0 44 44" viewBox="0 0 44 44" height="44px" width="44px"
                 y="0px" x="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg"
                 id="Layer_1" version="1.1">
    <use xlink:href="#shopping_cart"></use>
</svg>
            <span><a href="<?php echo $this->getUrl('checkout/onepage'); ?>"
                     class="cartgo"><?php echo $cartItemsQuantity; ?></a></span>
        </div>
    <?php } else { ?>
        <div class="shoping-cart" onclick="window.location='<?php echo $this->getUrl('checkout/onepage'); ?>'">
            <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg"
                 xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                 width="44px" height="44px" viewBox="0 0 44 44" enable-background="new 0 0 44 44" xml:space="preserve">
<g>
    <rect x="13.873" y="14.691" fill="none" stroke="#FFFFFF" stroke-miterlimit="10" width="17.461" height="19.208"/>
    <path fill="none" stroke="#FFFFFF" stroke-miterlimit="10" d="M27.777,14.604h-2.619v-3.648c0-0.237-0.2-0.437-0.437-0.437h-4.236
		c-0.236,0-0.437,0.2-0.437,0.437v3.648h-2.619v-3.648c0-1.685,1.371-3.056,3.056-3.056h4.236c1.685,0,3.056,1.371,3.056,3.056
		V14.604z"/>
</g>
</svg>

            <span><a href="javascript:void(0)" class="cartgo"></a></span>
        </div>
    <?php } ?>

    <div class="upper-nav">
        <button class="cross-btn" id="cross-btn" style="display: none;">
            <svg xml:space="preserve" enable-background="new 0 0 44 44" viewBox="0 0 44 44" height="44px" width="44px" y="0px" x="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" id="Layer_1" version="1.1">
<g>
    <rect height="44" width="44" fill="#555555"/>
    <line y2="30" x2="30" y1="14" x1="14" stroke-miterlimit="10" stroke="#FFFFFF" fill="none"/>
    <line y2="30" x2="14" y1="14" x1="30" stroke-miterlimit="10" stroke="#FFFFFF" fill="none"/>
</g>
</svg>

        </button>
        <div class="nav-container" id="menu_container">

            <ul class="nav-menu menu  level1">
                <?php if (!Mage::getSingleton('customer/session')->isLoggedIn()): ?>
                    <li class="menu-item sign-up">
                    <i></i>
				<span class="key">
<!--					<img class="responsive" src="--><?php //echo $this->getSkinUrl('images/key1.png') ?><!--" alt=""/>-->
                <svg xml:space="preserve" enable-background="new 164.167 0 44 44" viewBox="164.167 0 44 44"
                     height="44px" width="44px" y="0px" x="0px" xmlns:xlink="http://www.w3.org/1999/xlink"
                     xmlns="http://www.w3.org/2000/svg" id="Layer_1" version="1.1">
                    <path d="M189.256,16.171c0-2.083-1.689-3.771-3.771-3.771
			c-2.084,0-3.771,1.689-3.771,3.771c0,1.615,1.02,2.981,2.445,3.52L182.627,30h5.715l-1.533-10.309
			C188.237,19.153,189.256,17.786,189.256,16.171z" stroke-miterlimit="10" stroke="#666666" fill="none"/>
                </svg>

				</span>
					<span class="sign-text">
						<a href="javascript:void(0)"
                           onClick="openLogin()"><span><?php echo $this->__('Sign In&nbsp;') ?> /</span></a>
                        <a href="javascript:void(0)" class="menu-link"
                           id="menu_signup"><?php echo $this->__('Sign Up') ?></span></a>
                        </span>

                        <span class="border-line"></span>
                    </li>
                <?php else: ?>
                    <?php $customer = Mage::getSingleton('customer/session')->getCustomer();
                    $customerData = Mage::getModel('customer/customer')->load($customer->getId())->getData(); ?>

                    <li class="username menu-item has-dropdown">
					   <span class="profile_img">
<!--						   <img src="/rangoli/wp-content/themes/rangoli/images/default.jpg" alt=""/>-->
	                    </span>
                        <a class="menu-link m-link "
                           href="javascript:void(0)" onclick="jQuery(this).next().click();">Hi <?php echo $customerData['firstname']; ?></a>
							<span class="arrow-tag toggle-ys-menu">
<!--								<img alt="V" src="--><?php //echo $this->getSkinUrl('images/black-arrw.png')?><!--" class="responsive">-->
								<svg width="44px" height="44px">
                                    <line fill="none" stroke="#666666" stroke-miterlimit="10" x1="272.374" y1="109.657" x2="288.374"
                                          y2="109.657"/>
                                    <line fill="none" stroke="#666666" stroke-miterlimit="10" x1="14.374"
                                          y1="21.39" x2="30.374" y2="21.39"/>
                                    <line fill="none" stroke="#666666" stroke-miterlimit="10" x1="22.374"
                                          y1="13.39" x2="22.374" y2="29.39"/>
                                </svg>
								</span>

                        </span>
                        <ul class="nav-dropdown menu  level2">
                            <li class="menu-item">
                                <a href="<?php echo Mage::getUrl('customer/account'); ?>"
                                   class="menu-link"><?php echo $this->__('My Account') ?><span></span></a>
                            </li>
                            <li class="menu-item">
                                <a class="menu-link"
                                   href="<?php echo Mage::helper('customer')->getLogoutUrl(); ?>"><?php echo $this->__('Sign Out&nbsp;') ?>
                                    <span></span>
                                </a>
                            </li>
                        </ul>
                        <span class="border-line"></span>
                    </li>


                <?php endif; ?>
                <li class="menu-item has-dropdown main-heading yogasmoga_li">
                    <?php /* commented for new design ?>
					<a href="<?php echo $this->getUrl('') ?>" class="menu-link m-link ">
                        <svg width="227.831px" height="46.423px">
                            <use xlink:href="#yogasmoga_logo"></use>
                        </svg>
                    </a>
								<span class="arrow-tag toggle-ys-menu is-active">
<!--									<img class="responsive" src="--><?php //echo $this->getSkinUrl('images/black-arrw.png') ?><!--" alt=""/>-->
									<svg width="44px" height="44px">
                                        <line fill="none" stroke="#666666" stroke-miterlimit="10" x1="272.374" y1="109.657" x2="288.374"
                                              y2="109.657"/>
                                        <line fill="none" stroke="#666666" stroke-miterlimit="10" x1="14.374"
                                              y1="21.39" x2="30.374" y2="21.39"/>
                                        <line fill="none" stroke="#666666" stroke-miterlimit="10" x1="22.374"
                                              y1="13.39" x2="22.374" y2="29.39"/>
                                    </svg>
								</span>
					<?php */ ?>

                    <?php $_helper = Mage::helper('catalog/category') ?>
                    <?php $_categories = $_helper->getStoreCategories() ?>
                    <?php $currentCategory = Mage::registry('current_category') ?>
                    <?php $ccId = Mage::getModel('catalog/layer')->getCurrentCategory()->getId()?>
                    <?php if (count($_categories) > 0): ?>
                    <ul class="nav-dropdown menu level2" style="display: block;">

                        <?php //edited...
                        $identity ='';foreach ($_categories as $_category): ?>
                            <?php $_category = Mage::getModel('catalog/category')->load($_category->getId()) ?>
                            <?php $_subcategories = $_category->getChildrenCategories() ?>

                            <li class="menu-item has-dropdown c-text">
                                <i></i>


                                <?php if($_category->getId() == $ccId){
                                    //edited...
                                    $identity = $_category->getUrlKey();
                                    ?>
                                    <a class="menu-link main-txt" rel="cat_<?php echo $_category->getId().$identity;?>" href="<?php echo $_helper->getCategoryUrl($_category) ?>">
                                        <?php echo $_category->getName() ?>
                                    </a>
                                <?php  } else{
                                    //edited...
                                    $identity = $_category->getUrlKey();
                                    ?>
                                    <a class="menu-link main-txt" rel="cat_<?php echo $_category->getId().$identity;?>" href="<?php echo $_helper->getCategoryUrl($_category) ?>">
                                        <?php echo $_category->getName() ?>
                                    </a>
                                <?php }?>




                                <?php if(trim(strtolower($_category->getName()))=="gift sets"){ ?>

                                    <span class="arrow-tag toggle-ys-menu">
                                        <!--											<img class="responsive" src="--><?php //echo $this->getSkinUrl('images/black-arrw.png') ?><!--" alt=""/>-->
                                        <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg"
                                             xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                                             width="44px" height="44px" viewBox="0 0 44 44"
                                             enable-background="new 0 0 44 44" xml:space="preserve">
                                        <line fill="none" stroke="#666666" stroke-miterlimit="10" x1="272.374" y1="109.657" x2="288.374" y2="109.657"/>
                                            <line fill="none" stroke="#666666" stroke-miterlimit="10" x1="14.374"
                                                  y1="21.39" x2="30.374" y2="21.39"/>
                                            <line fill="none" stroke="#666666" stroke-miterlimit="10" x1="22.374"
                                                  y1="13.39" x2="22.374" y2="29.39"/>
                                        </svg>
                                    </span>
                                    <ul class="nav-dropdown menu level3">
                                        <li class="menu-item">
                                            <i></i>
                                            <a class="menu-link sub_cat gift_set_link" href="gift-sets?style=men" rel="men">Men</a>
                                        </li>
                                        <li class="menu-item">
                                            <i></i>
                                            <a class="menu-link sub_cat gift_set_link" href="gift-sets?style=women" rel="women">Women</a>
                                        </li>
                                    </ul>
                                    <?php
                                }
                                else{ ?>

                                    <?php if(isset($_subcategories) && count($_subcategories)>0){ ?>
                                        <span class="arrow-tag toggle-ys-menu">
                                        <!--											<img class="responsive" src="--><?php //echo $this->getSkinUrl('images/black-arrw.png') ?><!--" alt=""/>-->
                                        <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg"
                                             xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                                             width="44px" height="44px" viewBox="0 0 44 44"
                                             enable-background="new 0 0 44 44" xml:space="preserve">
                                        <line fill="none" stroke="#666666" stroke-miterlimit="10" x1="272.374" y1="109.657" x2="288.374" y2="109.657"/>
                                            <line fill="none" stroke="#666666" stroke-miterlimit="10" x1="14.374"
                                                  y1="21.39" x2="30.374" y2="21.39"/>
                                            <line fill="none" stroke="#666666" stroke-miterlimit="10" x1="22.374"
                                                  y1="13.39" x2="22.374" y2="29.39"/>
                                        </svg>
                                        </span>

                                    <?php } ?>

                                    <?php //if ($currentCategory && $currentCategory->getId() == $_category->getId()): ?>
                                    <?php if (count($_subcategories) > 0): ?>
                                        <ul class="nav-dropdown menu level3">
                                            <?php if($identity=="women"){ //edited... ?>
                                                <?php $womenWhatsnew = Mage::getModel('catalog/category')->load(16) ?>
                                                <li class="menu-item"><a href="<?php echo $womenWhatsnew->getUrl();?>"><?php echo $womenWhatsnew->getName();?></a></li>
                                            <?php } else{?>
                                                <?php $womenWhatsnew = Mage::getModel('catalog/category')->load(19) ?>
                                                <li class="menu-item"><a href="<?php echo $womenWhatsnew->getUrl();?>"><?php echo $womenWhatsnew->getName();?></a></li>
                                            <?php } foreach ($_subcategories as $_subcategory): ?>

                                                <li class="menu-item">
                                                    <i></i>
                                                    <?php //edited...
                                                    $categoryIds = json_decode(trim(Mage::getModel('core/variable')->loadByCode('women_collection_categoryids')->getValue('plain')), true);
                                                    $menCollectionIds = json_decode(trim(Mage::getModel('core/variable')->loadByCode('men_collection_categoryids')->getValue('plain')), true);
                                                    $prints = $categoryIds['prints'];
                                                    $carbon6 = $categoryIds['women_carbon6'];
                                                    $vivacity = $categoryIds['vivacity'];
                                                    $golf = $menCollectionIds['golf'];
                                                    $menCarbon6 = $menCollectionIds['men_carbon6'];



                                                    ?>
                                                    <?php
                                                    //edited...
                                                    if($_subcategory->getId() == 16 ||
                                                        $_subcategory->getId() == 19 ||
                                                        $_subcategory->getId()==$prints  ||
                                                        $_subcategory->getId()==$carbon6  ||
                                                        $_subcategory->getId()==$vivacity ||
                                                        $_subcategory->getId()==$golf ||
                                                        $_subcategory->getId()==$menCarbon6

                                                    ){?>
                                                    <?php }else{
                                                        //edited...
                                                        ?>
                                                        <?php if($_subcategory->getId() != 131 && $_subcategory->getId() != 133){?>
                                                            <a class="menu-link sub_cat" rel="cat_<?php echo $_subcategory->getId();?>" data="cat_<?php echo $_category->getId(); ?>"
                                                               href="<?php echo $_helper->getCategoryUrl($_subcategory) ?>">
                                                                <?php echo $_subcategory->getName() ?></a>
                                                        <?php } else {
                                                            //edited...
                                                            ?>

                                                            <?php if($identity=='women'):?>

                                                                <a class="menu-link sub_cat" rel="cat_<?php echo $_subcategory->getId();?>" data="cat_<?php echo $_category->getId(); ?>"
                                                                   href="<?php echo $_helper->getCategoryUrl($_subcategory) ?>">
                                                                    <?php echo $_subcategory->getName() ?></a>

                                                                <span class="arrow-tag sub_menu_icons">
																<svg width="44px" height="44px">
                                                                    <line fill="none" stroke="#666666" stroke-miterlimit="10" x1="272.374" y1="109.657" x2="288.374"
                                                                          y2="109.657"/>
                                                                    <line fill="none" stroke="#666666" stroke-miterlimit="10" x1="14.374"
                                                                          y1="21.39" x2="30.374" y2="21.39"/>
                                                                    <line fill="none" stroke="#666666" stroke-miterlimit="10" x1="22.374"
                                                                          y1="13.39" x2="22.374" y2="29.39"/>
                                                                </svg>

														 </span>
                                                                <ul class="sub_menu_links">
                                                                    <?php foreach($categoryIds as $ids ):
                                                                        $sub_subcategory = Mage::getModel('catalog/category')->load($ids);?>
                                                                        <li class="menu-item"><a class="menu-link" href="<?php echo $sub_subcategory->getUrl();?>"><?php echo $sub_subcategory->getName();?></a></li>
                                                                    <?php endforeach?>
                                                                </ul>
                                                            <?php else: ?>

                                                                <a class="menu-link sub_cat" rel="cat_<?php echo $_subcategory->getId();?>" data="cat_<?php echo $_category->getId(); ?>"
                                                                   href="<?php echo $_helper->getCategoryUrl($_subcategory) ?>">
                                                                    <?php echo $_subcategory->getName() ?></a>

                                                                <span class="arrow-tag sub_menu_icons">
																<svg width="44px" height="44px">
                                                                    <line fill="none" stroke="#666666" stroke-miterlimit="10" x1="272.374" y1="109.657" x2="288.374"
                                                                          y2="109.657"/>
                                                                    <line fill="none" stroke="#666666" stroke-miterlimit="10" x1="14.374"
                                                                          y1="21.39" x2="30.374" y2="21.39"/>
                                                                    <line fill="none" stroke="#666666" stroke-miterlimit="10" x1="22.374"
                                                                          y1="13.39" x2="22.374" y2="29.39"/>
                                                                </svg>

														 </span>
                                                                <ul class="sub_menu_links">
                                                                    <?php //edited...
                                                                    foreach($menCollectionIds as $ids ):
                                                                        $sub_subcategory = Mage::getModel('catalog/category')->load($ids);?>
                                                                        <li class="menu-item"><a class="menu-link" href="<?php echo $sub_subcategory->getUrl();?>"><?php echo $sub_subcategory->getName();?></a></li>
                                                                    <?php endforeach?>
                                                                </ul>

                                                            <?php endif;?>





                                                        <?php } } ?>

                                                    <?php  $_category = Mage::getModel('catalog/category')->load($_category->getId()) ?>
                                                    <?php $_subsubcategories = $_subcategory->getChildrenCategories() ?>
                                                    <?php if (count($_subsubcategories) > 0): ?>
                                                        <span class="arrow-tag sub_menu_icons">
																<svg width="44px" height="44px">
                                                                    <line fill="none" stroke="#666666" stroke-miterlimit="10" x1="272.374" y1="109.657" x2="288.374"
                                                                          y2="109.657"/>
                                                                    <line fill="none" stroke="#666666" stroke-miterlimit="10" x1="14.374"
                                                                          y1="21.39" x2="30.374" y2="21.39"/>
                                                                    <line fill="none" stroke="#666666" stroke-miterlimit="10" x1="22.374"
                                                                          y1="13.39" x2="22.374" y2="29.39"/>
                                                                </svg>

																	</span>
                                                        <ul class="sub_menu_links">
                                                            <?php foreach ($_subsubcategories as $_subsubcategory): ?>

                                                                <li class="menu-item">
                                                                    <a class="menu-link"  rel="cat_<?php echo $_subcategory->getId() . '_' . $_subsubcategory->getId();?>"
                                                                       href="<?php echo $_helper->getCategoryUrl($_subsubcategory) ?>">
                                                                        <?php echo $_subsubcategory->getName() ?></a>
                                                                </li>

                                                            <?php endforeach; ?>
                                                        </ul>
                                                    <?php endif; ?>

                                                </li>
                                            <?php endforeach; ?>
                                        </ul>
                                    <?php endif; ?>
                                    <?php //endif; ?>

                                <?php } // gift set check finishes ?>
                            </li>
                        <?php endforeach; ?>
                        <?php endif; ?>
                        <li class="menu-item story_icon">
								  <span>
										<svg style="margin-top:-2px;" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 44 44" xml:space="preserve">
										<style type="text/css">
                                            .st0 {
                                                fill: none;
                                                stroke: #CCCCCC;
                                                stroke-miterlimit: 10;
                                            }
                                        </style>
                                            <!--                                          <use xlink:href="#ys_tech"></use>-->
                                            <g id="XMLID_35_">
                                                <polyline id="XMLID_37_" class="st0" points="29.4,160.3 16.3,166.6 22.6,153.5 	"/>
                                                <circle id="XMLID_36_" class="st0" cx="27.8" cy="155.1" r="5.5"/>
                                            </g>
                                            <g id="XMLID_32_">
                                                <rect id="XMLID_34_" x="22.9" y="238.4" class="st0" width="3.9" height="14.7"/>
                                                <circle id="XMLID_33_" class="st0" cx="24.8" cy="232.1" r="2.7"/>
                                            </g>
                                            <g id="XMLID_25_">
                                                <line id="XMLID_31_" class="st0" x1="23.7" y1="18.3" x2="28" y2="25.8"/>
                                                <line id="XMLID_30_" class="st0" x1="16.1" y1="25.9" x2="20.6" y2="18.1"/>
                                                <line id="XMLID_29_" class="st0" x1="26.5" y1="28.5" x2="17.7" y2="28.5"/>
                                                <circle id="XMLID_28_" class="st0" cx="22.1" cy="15.5" r="3"/>
                                                <circle id="XMLID_27_" class="st0" cx="29.5" cy="28.5" r="3"/>
                                                <path id="XMLID_26_" class="st0" d="M17.7,28.5c0,1.7-1.4,3-3,3s-3-1.4-3-3c0-1.7,1.4-3,3-3S17.7,26.8,17.7,28.5"/>
                                            </g>
                                            <g id="XMLID_18_">
                                                <circle id="XMLID_24_" class="st0" cx="24.8" cy="195.5" r="6.6"/>
                                                <circle id="XMLID_23_" class="st0" cx="21" cy="197.7" r="6.6"/>
                                                <circle id="XMLID_22_" class="st0" cx="21" cy="202.1" r="6.6"/>
                                                <circle id="XMLID_21_" class="st0" cx="24.8" cy="204.3" r="6.6"/>
                                                <circle id="XMLID_20_" class="st0" cx="28.6" cy="202.1" r="6.6"/>
                                                <circle id="XMLID_19_" class="st0" cx="28.6" cy="197.7" r="6.6"/>
                                            </g>
                                            <g id="XMLID_15_">
                                                <path id="XMLID_17_" class="st0" d="M-147.1,37c0,0-4.5,0.1-7.3-2.7s-2.7-7.3-2.7-7.3s4.5-0.1,7.3,2.7S-147.1,37-147.1,37z"/>
                                                <path id="XMLID_16_" class="st0" d="M-147.1,37c0,0,4.5,0.1,7.3-2.7s2.7-7.3,2.7-7.3s-4.5-0.1-7.3,2.7S-147.1,37-147.1,37z"/>
                                            </g>
                                            <line id="XMLID_14_" class="st0" x1="-147.1" y1="37" x2="-147.1" y2="44"/>
                                            <g id="XMLID_3_">
                                                <g id="XMLID_5_">
                                                    <line id="XMLID_12_" class="st0" x1="-211.6" y1="-75.5" x2="-185.5" y2="-75.5"/>
                                                    <line id="XMLID_11_" class="st0" x1="-211.6" y1="-80.8" x2="-185.5" y2="-80.8"/>
                                                    <line id="XMLID_10_" class="st0" x1="-211.6" y1="-78.2" x2="-185.5" y2="-78.2"/>
                                                    <line id="XMLID_9_" class="st0" x1="-201.2" y1="-83.5" x2="-185.5" y2="-83.5"/>
                                                    <line id="XMLID_8_" class="st0" x1="-201.2" y1="-86.2" x2="-185.5" y2="-86.2"/>
                                                    <line id="XMLID_7_" class="st0" x1="-201.2" y1="-88.8" x2="-185.5" y2="-88.8"/>
                                                    <line id="XMLID_6_" class="st0" x1="-201.2" y1="-91.5" x2="-185.5" y2="-91.5"/>
                                                </g>
                                                <polygon id="XMLID_4_" class="st0" points="-207.6,-85.6 -210.1,-83.7 -209.1,-86.7 -211.6,-88.5 -208.5,-88.5 -207.6,-91.5
										-206.6,-88.5 -203.5,-88.5 -206,-86.7 -205,-83.7 	"/>
                                            </g>
										</svg>
                                      <?php /* svg commented for new design ?>
										<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg"
										xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
										viewBox="0 0 44 44" style="enable-background:new 0 0 44 44;"
										xml:space="preserve">
										<style type="text/css">
										.st0 {
										fill: none;
										stroke: #CCCCCC;
										stroke-miterlimit: 10;
										}
										</style>
										<!--                                          <use xlink:href="#ys_story"></use>-->
										<g id="XMLID_35_">
										<polyline id="XMLID_37_" class="st0"
										points="29.4,160.3 16.3,166.6 22.6,153.5 	"/>
										<circle id="XMLID_36_" class="st0" cx="27.8" cy="155.1" r="5.5"/>
										</g>
										<g id="XMLID_32_">
										<rect id="XMLID_34_" x="22.9" y="238.4" class="st0" width="3.9"
										height="14.7"/>
										<circle id="XMLID_33_" class="st0" cx="24.8" cy="232.1" r="2.7"/>
										</g>
										<g id="XMLID_25_">
										<line id="XMLID_31_" class="st0" x1="26.4" y1="109.5" x2="30.7" y2="117"/>
										<line id="XMLID_30_" class="st0" x1="18.8" y1="117.1" x2="23.3"
										y2="109.3"/>
										<line id="XMLID_29_" class="st0" x1="29.2" y1="119.7" x2="20.4"
										y2="119.7"/>
										<circle id="XMLID_28_" class="st0" cx="24.8" cy="106.8" r="3"/>
										<circle id="XMLID_27_" class="st0" cx="32.2" cy="119.7" r="3"/>
										<path id="XMLID_26_" class="st0"
										d="M20.4,119.7c0,1.7-1.4,3-3,3c-1.7,0-3-1.4-3-3s1.4-3,3-3C19,116.6,20.4,118,20.4,119.7"/>
										</g>
										<g id="XMLID_18_">
										<circle id="XMLID_24_" class="st0" cx="24.8" cy="195.5" r="6.6"/>
										<circle id="XMLID_23_" class="st0" cx="21" cy="197.7" r="6.6"/>
										<circle id="XMLID_22_" class="st0" cx="21" cy="202.1" r="6.6"/>
										<circle id="XMLID_21_" class="st0" cx="24.8" cy="204.3" r="6.6"/>
										<circle id="XMLID_20_" class="st0" cx="28.6" cy="202.1" r="6.6"/>
										<circle id="XMLID_19_" class="st0" cx="28.6" cy="197.7" r="6.6"/>
										</g>
										<g id="XMLID_15_">
										<path id="XMLID_17_" class="st0"
										d="M23.3,23.5c0,0-4.5,0.1-7.3-2.7s-2.7-7.3-2.7-7.3s4.5-0.1,7.3,2.7S23.3,23.5,23.3,23.5z"/>
										<path id="XMLID_16_" class="st0"
										d="M23.3,23.5c0,0,4.5,0.1,7.3-2.7s2.7-7.3,2.7-7.3s-4.5-0.1-7.3,2.7S23.3,23.5,23.3,23.5z"/>
										</g>
										<line id="XMLID_14_" class="st0" x1="23.3" y1="23.5" x2="23.3" y2="30.5"/>
										<g id="XMLID_3_">
										<g id="XMLID_5_">
										<line id="XMLID_12_" class="st0" x1="-211.6" y1="-75.5" x2="-185.5"
										y2="-75.5"/>
										<line id="XMLID_11_" class="st0" x1="-211.6" y1="-80.8" x2="-185.5"
										y2="-80.8"/>
										<line id="XMLID_10_" class="st0" x1="-211.6" y1="-78.2" x2="-185.5"
										y2="-78.2"/>
										<line id="XMLID_9_" class="st0" x1="-201.2" y1="-83.5" x2="-185.5"
										y2="-83.5"/>
										<line id="XMLID_8_" class="st0" x1="-201.2" y1="-86.2" x2="-185.5"
										y2="-86.2"/>
										<line id="XMLID_7_" class="st0" x1="-201.2" y1="-88.8" x2="-185.5"
										y2="-88.8"/>
										<line id="XMLID_6_" class="st0" x1="-201.2" y1="-91.5" x2="-185.5"
										y2="-91.5"/>
										</g>
										<polygon id="XMLID_4_" class="st0" points="-207.6,-85.6 -210.1,-83.7 -209.1,-86.7 -211.6,-88.5 -208.5,-88.5 -207.6,-91.5
										-206.6,-88.5 -203.5,-88.5 -206,-86.7 -205,-83.7 	"/>
										</g>
										</svg> 
										<?php */ ?>
								  </span>
                            <a href="<?php echo $this->getBaseUrl(); ?>our-story" class="menu-link sub-title">YS story</a></li>
                        <?php /* commented for new designs ?>
						<li class="menu-item tech_icon">
							<span>
							<svg style="margin-top:-2px;" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg"
							xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
							viewBox="0 0 44 44" style="enable-background:new 0 0 44 44;"
							xml:space="preserve">
							<style type="text/css">
							.st0 {
							fill: none;
							stroke: #CCCCCC;
							stroke-miterlimit: 10;
							}
							</style>
							<!--                                          <use xlink:href="#ys_tech"></use>-->
							<g id="XMLID_35_">
							<polyline id="XMLID_37_" class="st0"
							points="29.4,160.3 16.3,166.6 22.6,153.5 	"/>
							<circle id="XMLID_36_" class="st0" cx="27.8" cy="155.1" r="5.5"/>
							</g>
							<g id="XMLID_32_">
							<rect id="XMLID_34_" x="22.9" y="238.4" class="st0" width="3.9"
							height="14.7"/>
							<circle id="XMLID_33_" class="st0" cx="24.8" cy="232.1" r="2.7"/>
							</g>
							<g id="XMLID_25_">
							<line id="XMLID_31_" class="st0" x1="23.7" y1="18.3" x2="28" y2="25.8"/>
							<line id="XMLID_30_" class="st0" x1="16.1" y1="25.9" x2="20.6" y2="18.1"/>
							<line id="XMLID_29_" class="st0" x1="26.5" y1="28.5" x2="17.7" y2="28.5"/>
							<circle id="XMLID_28_" class="st0" cx="22.1" cy="15.5" r="3"/>
							<circle id="XMLID_27_" class="st0" cx="29.5" cy="28.5" r="3"/>
							<path id="XMLID_26_" class="st0"
							d="M17.7,28.5c0,1.7-1.4,3-3,3s-3-1.4-3-3c0-1.7,1.4-3,3-3S17.7,26.8,17.7,28.5"/>
							</g>
							<g id="XMLID_18_">
							<circle id="XMLID_24_" class="st0" cx="24.8" cy="195.5" r="6.6"/>
							<circle id="XMLID_23_" class="st0" cx="21" cy="197.7" r="6.6"/>
							<circle id="XMLID_22_" class="st0" cx="21" cy="202.1" r="6.6"/>
							<circle id="XMLID_21_" class="st0" cx="24.8" cy="204.3" r="6.6"/>
							<circle id="XMLID_20_" class="st0" cx="28.6" cy="202.1" r="6.6"/>
							<circle id="XMLID_19_" class="st0" cx="28.6" cy="197.7" r="6.6"/>
							</g>
							<g id="XMLID_15_">
							<path id="XMLID_17_" class="st0"
							d="M-147.1,37c0,0-4.5,0.1-7.3-2.7s-2.7-7.3-2.7-7.3s4.5-0.1,7.3,2.7S-147.1,37-147.1,37z"/>
							<path id="XMLID_16_" class="st0"
							d="M-147.1,37c0,0,4.5,0.1,7.3-2.7s2.7-7.3,2.7-7.3s-4.5-0.1-7.3,2.7S-147.1,37-147.1,37z"/>
							</g>
							<line id="XMLID_14_" class="st0" x1="-147.1" y1="37" x2="-147.1" y2="44"/>
							<g id="XMLID_3_">
							<g id="XMLID_5_">
							<line id="XMLID_12_" class="st0" x1="-211.6" y1="-75.5" x2="-185.5"
							y2="-75.5"/>
							<line id="XMLID_11_" class="st0" x1="-211.6" y1="-80.8" x2="-185.5"
							y2="-80.8"/>
							<line id="XMLID_10_" class="st0" x1="-211.6" y1="-78.2" x2="-185.5"
							y2="-78.2"/>
							<line id="XMLID_9_" class="st0" x1="-201.2" y1="-83.5" x2="-185.5"
							y2="-83.5"/>
							<line id="XMLID_8_" class="st0" x1="-201.2" y1="-86.2" x2="-185.5"
							y2="-86.2"/>
							<line id="XMLID_7_" class="st0" x1="-201.2" y1="-88.8" x2="-185.5"
							y2="-88.8"/>
							<line id="XMLID_6_" class="st0" x1="-201.2" y1="-91.5" x2="-185.5"
							y2="-91.5"/>
							</g>
							<polygon id="XMLID_4_" class="st0" points="-207.6,-85.6 -210.1,-83.7 -209.1,-86.7 -211.6,-88.5 -208.5,-88.5 -207.6,-91.5
							-206.6,-88.5 -203.5,-88.5 -206,-86.7 -205,-83.7 	"/>
							</g>
							</svg>

							</span>
							<a href="<?php echo $this->getBaseUrl(); ?>ys-fabric-tech" class="menu-link sub-title">YS tech</a>
						</li>
						
						<?php */ ?>
                        <li class="menu-item tech_icon">
							<span>
							<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                                 viewBox="0 0 44 44" style="enable-background:new 0 0 44 44;" xml:space="preserve">

							<g id="XMLID_2_">
                                <path id="XMLID_7_" fill="#777777"  d="M9.9,11.4l11.8,20.5l11.8-20.5H9.9z M11.7,12.4h20.2L21.7,29.9L11.7,12.4z"/>
                                <path id="XMLID_4_" fill="#777777"  d="M14.6,14.1l7.1,12.4l7.1-12.4H14.6z M16.3,15.1h4.9v2h-1.7l2.2,3.9l2.3-3.9h-1.8v-2h4.9
							l-5.4,9.4L16.3,15.1z"/>
                            </g>
							</svg>

							</span>
                            <a href="<?php echo $this->getBaseUrl(); ?>our-stores" class="menu-link sub-title">YS Stores</a>
                        </li>

                        <?php /* commented for new designs ?>
						<li class="menu-item smogi-icon">
							<a href="<?php echo $this->getBaseUrl(); ?>smogi-bucks" class="menu-link sub-title">SMOGI Bucks</a>
							<span>
							<!--								  <img class="responsive" src="--><?php //echo $this->getSkinUrl('images/smogi-icon.png') ?><!--" alt="">-->
							<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px"
							y="0px"
							viewBox="0 0 44 44" style="enable-background:new 0 0 44 44;" xml:space="preserve">
							<style type="text/css">
							.st0 {
							fill: none;
							stroke: #CCCCCC;
							stroke-miterlimit: 10;
							}
							</style>
							<!--    <use xlink:href="#smogi_bucks"></use>-->
							<g id="XMLID_35_">
							<polyline id="XMLID_37_" class="st0" points="-155,197.7 -168.1,204 -161.8,190.9 	"/>
							<circle id="XMLID_36_" class="st0" cx="-156.6" cy="192.5" r="5.5"/>
							</g>
							<g id="XMLID_32_">
							<rect id="XMLID_34_" x="22.9" y="238.4" class="st0" width="3.9" height="14.7"/>
							<circle id="XMLID_33_" class="st0" cx="24.8" cy="232.1" r="2.7"/>
							</g>
							<g id="XMLID_25_">
							<line id="XMLID_31_" class="st0" x1="-150.6" y1="106.8" x2="-146.2" y2="114.3"/>
							<line id="XMLID_30_" class="st0" x1="-158.1" y1="114.4" x2="-153.6" y2="106.6"/>
							<line id="XMLID_29_" class="st0" x1="-147.7" y1="117" x2="-156.5" y2="117"/>
							<circle id="XMLID_28_" class="st0" cx="-152.1" cy="104.1" r="3"/>
							<circle id="XMLID_27_" class="st0" cx="-144.7" cy="117" r="3"/>
							<path id="XMLID_26_" class="st0" d="M-156.5,117c0,1.7-1.4,3-3,3s-3-1.4-3-3s1.4-3,3-3S-156.5,115.3-156.5,117"/>
							</g>
							<g id="XMLID_18_">
							<circle id="XMLID_24_" class="st0" cx="22" cy="17.6" r="6.6"/>
							<circle id="XMLID_23_" class="st0" cx="18.2" cy="19.8" r="6.6"/>
							<circle id="XMLID_22_" class="st0" cx="18.2" cy="24.2" r="6.6"/>
							<circle id="XMLID_21_" class="st0" cx="22" cy="26.4" r="6.6"/>
							<circle id="XMLID_20_" class="st0" cx="25.8" cy="24.2" r="6.6"/>
							<circle id="XMLID_19_" class="st0" cx="25.8" cy="19.8" r="6.6"/>
							</g>
							<g id="XMLID_15_">
							<path id="XMLID_17_" class="st0"
							d="M-147.1,37c0,0-4.5,0.1-7.3-2.7s-2.7-7.3-2.7-7.3s4.5-0.1,7.3,2.7S-147.1,37-147.1,37z"/>
							<path id="XMLID_16_" class="st0"
							d="M-147.1,37c0,0,4.5,0.1,7.3-2.7s2.7-7.3,2.7-7.3s-4.5-0.1-7.3,2.7S-147.1,37-147.1,37z"/>
							</g>
							<line id="XMLID_14_" class="st0" x1="-147.1" y1="37" x2="-147.1" y2="44"/>
							<g id="XMLID_3_">
							<g id="XMLID_5_">
							<line id="XMLID_12_" class="st0" x1="-211.6" y1="-75.5" x2="-185.5" y2="-75.5"/>
							<line id="XMLID_11_" class="st0" x1="-211.6" y1="-80.8" x2="-185.5" y2="-80.8"/>
							<line id="XMLID_10_" class="st0" x1="-211.6" y1="-78.2" x2="-185.5" y2="-78.2"/>
							<line id="XMLID_9_" class="st0" x1="-201.2" y1="-83.5" x2="-185.5" y2="-83.5"/>
							<line id="XMLID_8_" class="st0" x1="-201.2" y1="-86.2" x2="-185.5" y2="-86.2"/>
							<line id="XMLID_7_" class="st0" x1="-201.2" y1="-88.8" x2="-185.5" y2="-88.8"/>
							<line id="XMLID_6_" class="st0" x1="-201.2" y1="-91.5" x2="-185.5" y2="-91.5"/>
							</g>
							<polygon id="XMLID_4_" class="st0" points="-207.6,-85.6 -210.1,-83.7 -209.1,-86.7 -211.6,-88.5 -208.5,-88.5 -207.6,-91.5
							-206.6,-88.5 -203.5,-88.5 -206,-86.7 -205,-83.7 	"/>
							</g>
							</svg>
							</span>
						</li>
						<?php */ ?>
                        <li class="menu-item smogi-icon">
                            <a href="<?php echo $this->getBaseUrl(); ?>gift_of_ys" class="menu-link sub-title">YS Gift Card</a>
							<span>
							<!--<img class="responsive" src="<?php //echo $this->getSkinUrl('images/gift-card-icon-new.pngo') ?>" alt="ys gift card">-->
							<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                                 width="44px" height="44px" viewBox="0 0 44 44" enable-background="new 0 0 44 44" xml:space="preserve">
							<g>
                                <defs>
                                    <rect id="SVGID_1_" x="9" y="13" width="26.807" height="16.983"/>
                                </defs>
                                <clipPath id="SVGID_2_">
                                    <use xlink:href="#SVGID_1_"  overflow="visible"/>
                                </clipPath>
                                <path clip-path="url(#SVGID_2_)" fill="#777777" d="M34.888,29.126H9.917V13.858h24.971V29.126z M35.805,13H9v16.983h26.805V13z"/>
                                <polygon clip-path="url(#SVGID_2_)" fill="none" stroke="#777777" stroke-width="0.707" stroke-miterlimit="10" points="
							40.326,26.249 38.492,27.965 21.066,11.666 22.9,9.95 	"/>
                                <path clip-path="url(#SVGID_2_)" fill="none" stroke="#777777" stroke-width="0.707" stroke-miterlimit="10" d="M26.144,33.528
							l-1.835,1.716L6.882,18.946l1.834-1.716L26.144,33.528z"/>
                            </g>
							</svg>


							</span>
                        </li>
                        <?php /* commented for new designs ?>
						<li style="position:relative;" class="menu-item contact_icon_li"><a href="<?php echo $this->getBaseUrl(); ?>contacts/" class="menu-link sub-title">Contact</a>
							<span class="contact-icon">
							<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg"
							xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
							viewBox="0 0 44 44" style="enable-background:new 0 0 44 44;" xml:space="preserve">
							<style type="text/css">
							.st0 {
							fill: none;
							stroke: #CCCCCC;
							stroke-miterlimit: 10;
							}
							</style>
							<!--                                    <use xlink:href="#contact"></use>-->
							<g id="XMLID_4_">
							<rect id="XMLID_6_" x="20.1" y="59.3" class="st0" width="3.9" height="14.7"/>
							<circle id="XMLID_5_" class="st0" cx="22" cy="53" r="2.7"/>
							</g>
							<path id="XMLID_3_" class="st0" d="M28.4,26.9l0.6,0h6.5v-4.4c0-2.7-6-5-13.5-5c-7.4,0-13.5,2.2-13.5,5v4.4h7l0-3.2
							c0-1.6,2.9-2.9,6.4-2.9s6.4,1.3,6.4,2.9L28.4,26.9z"/>
							</svg>


							</span>

						</li>


						<li style="position:relative;" class="menu-item contact_icon_li"><a href="<?php echo $this->getBaseUrl(); ?>help/" class="menu-link sub-title">Help</a>
							<span class="contact-icon">
							<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg"
							xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
							viewBox="0 0 44 44" style="enable-background:new 0 0 44 44;" xml:space="preserve">


							<style type="text/css">
							.st0{fill:none;stroke:#CCCCCC;stroke-miterlimit:10;}
							</style>
							<!--                                    <use xlink:href="#help"></use>-->
							<g id="XMLID_4_">
							<rect id="XMLID_6_" x="19.8" y="19.1" class="st0" width="3.9" height="14.7"/>
							<circle id="XMLID_5_" class="st0" cx="21.8" cy="12.8" r="2.7"/>
							</g>
							<path id="XMLID_3_" class="st0" d="M-70.9,26.7l0.6,0h6.5v-4.4c0-2.7-6-5-13.5-5c-7.4,0-13.5,2.2-13.5,5v4.4h7l0-3.2
							c0-1.6,2.9-2.9,6.4-2.9s6.4,1.3,6.4,2.9L-70.9,26.7z"/>
							</svg>


							</span>

						</li>
						<li style="position:relative;" class="menu-item contact_icon_li"><a href="/careers" class="menu-link sub-title">Careers</a>
							<span class="contact-icon">
							<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
							viewBox="0 0 44 44" style="enable-background:new 0 0 44 44;" xml:space="preserve">
							<style type="text/css">
							.st0{fill:none;stroke:#CCCBCB;stroke-miterlimit:10;}
							</style>
							<polygon id="XMLID_2_" class="st0" points="25,16.6 25,22.2 19.9,22.2 19.9,27.3 14.2,27.3 14.2,33.4 31.1,33.4 31.1,16.6 "/>
							</svg>


							</span>

						</li>
						<?php */ ?>

                    </ul><span class="border-line"></span>
                </li>
                <!--							  <li class="menu-item"><a href="-->
                <?php //echo $this->getBaseUrl();?><!--our-story" class="menu-link sub-title">YS For USA</a></li>-->
				<?php /* commented for new design ?>
                <li class="menu-item has-dropdown rangoli-link main-heading">
                    <!--								 <span class="rangoli-icon" style="opacity: 1"><img class="responsive" src="-->
                    <?php //echo $this->getSkinUrl('images/rangoli-icon.png') ?><!--" alt=""/></span>-->

								  <span class="arrow-tag toggle-ys-menu">
                                      <svg width="44px" height="44px">
                                          <line fill="none" stroke="#666666" stroke-miterlimit="10" x1="272.374" y1="109.657" x2="288.374"
                                                y2="109.657"/>
                                          <line fill="none" stroke="#666666" stroke-miterlimit="10" x1="14.374"
                                                y1="21.39" x2="30.374" y2="21.39"/>
                                          <line fill="none" stroke="#666666" stroke-miterlimit="10" x1="22.374"
                                                y1="13.39" x2="22.374" y2="29.39"/>
                                      </svg>
<!--									  <img alt="" src="--><?php //echo $this->getSkinUrl('images/black-arrw.png'); ?><!--" class="responsive">-->

								</span>

                    </span>
								<span class="white-img rangoli_text_a" style="display:block; height: 44px">
                                 <a href="<?php echo $this->getUrl('rangoli') ?>"
                                    class="menu-link m-link  rangoli_li_a">
                                     <!--	<img class="responsive" src="-->
                                     <?php //echo $this->getSkinUrl('images/rangoli-text.png') ?><!--" alt=""/>-->

                                     <span><svg  width="168.676px"
                                                 height="45.014px">
                                             <use xlink:href="#rangoli_logo" x="0" y="0" width="168.676px"
                                                  height="45.014px"/>
                                         </svg></span>

                                 </a>
								 </span>

                    <ul class="nav-dropdown menu rangoli_menu">
                        <li class="menu-item has-dropdown c-text ">
                            <a href="/rangoli/read/" class="menu-link main-txt">Read</a>
                            <span><svg>
<!--                                    <use xlink:href="#read" x="0" y="0" width="44px" height="44px"/>-->
                                    <g id="XMLID_24_">
                                        <circle id="XMLID_26_" class="st0" cx="23" cy="67.7" r="3.3"/>
                                        <path id="XMLID_25_" class="st0" d="M23,62.3c-4.7,0-8.8,2.1-11.6,5.5c2.7,3.4,6.9,5.5,11.6,5.5s8.8-2.1,11.6-5.5
		C31.8,64.4,27.7,62.3,23,62.3z"/>
                                    </g>
                                    <g id="XMLID_21_">
                                        <path id="XMLID_23_" class="st0" d="M23,101.4c-4.1,0-7.4,3.3-7.4,7.4c0,2,0.5,3.2,2,5c1.5,1.8,2.1,3.1,2.1,5.1v2.4h6.7V119
		c0-2,0.6-3.3,2.1-5.1c1.5-1.8,2-3.1,2-5C30.4,104.7,27.1,101.4,23,101.4z"/>
                                        <line id="XMLID_22_" class="st0" x1="19.6" y1="117.9" x2="26.4" y2="117.9"/>
                                    </g>
                                    <g id="XMLID_18_">
                                        <polyline id="XMLID_20_" class="st0" points="27.6,244.7 14.5,251 20.8,237.8 	"/>
                                        <circle id="XMLID_19_" class="st0" cx="26" cy="239.5" r="5.5"/>
                                    </g>
                                    <g id="XMLID_15_">
                                        <circle id="XMLID_17_" class="st0" cx="18.9" cy="286.1" r="6.5"/>
                                        <circle id="XMLID_16_" class="st0" cx="27.1" cy="286.1" r="6.5"/>
                                    </g>
                                    <polygon id="XMLID_14_" class="st0" points="23,186.9 25.4,194.5 33.4,194.5 27,199.1 29.4,206.6 23,202 16.6,206.6 19,199.1
	12.6,194.5 20.6,194.5 "/>
                                    <g id="XMLID_11_">
                                        <path id="XMLID_13_" class="st0" d="M12.9,149.6c-1.3,1.3-1.3,3.3,0,4.6l1,1l-1,1c-1.3,1.3-1.3,3.3,0,4.6c1.3,1.3,3.3,1.3,4.6,0
		l5.6-5.6l-5.6-5.6C16.2,148.3,14.1,148.3,12.9,149.6z"/>
                                        <path id="XMLID_12_" class="st0" d="M33.1,149.6c1.3,1.3,1.3,3.3,0,4.6l-1,1l1,1c1.3,1.3,1.3,3.3,0,4.6c-1.3,1.3-3.3,1.3-4.6,0
		l-5.6-5.6l5.6-5.6C29.8,148.3,31.9,148.3,33.1,149.6z"/>
                                    </g>
                                    <g id="XMLID_8_">
                                        <polygon id="XMLID_10_" class="st0"
                                                 points="23,16.6 13.1,15.6 13.1,30.6 23,29.6 32.9,30.6 32.9,15.6 	"/>
                                        <line id="XMLID_9_" class="st0" x1="23" y1="29.6" x2="23" y2="16.6"/>
                                    </g>
                                    <g id="XMLID_3_">
                                        <g id="XMLID_5_">
                                            <path id="XMLID_7_" class="st0"
                                                  d="M23,331.2c0,0-4.5,0.1-7.3-2.7c-2.8-2.8-2.7-7.3-2.7-7.3s4.5-0.1,7.3,2.7S23,331.2,23,331.2z"
                                                />
                                            <path id="XMLID_6_" class="st0"
                                                  d="M23,331.2c0,0,4.5,0.1,7.3-2.7c2.8-2.8,2.7-7.3,2.7-7.3s-4.5-0.1-7.3,2.7S23,331.2,23,331.2z"
                                                />
                                        </g>
                                        <line id="XMLID_4_" class="st0" x1="23" y1="331.2" x2="23" y2="338.1"/>
                                    </g>
                                </svg></span>
                        </li>
                        <li class="menu-item has-dropdown c-text ">
                            <a href="/rangoli/look/" class="menu-link main-txt">Look</a>
                            <span><svg>
<!--                                    <use xlink:href="#look" x="0" y="0" width="44px" height="44px"/>-->
                                    <g id="XMLID_24_">
                                        <circle id="XMLID_26_" class="st0" cx="22" cy="23" r="3.3"/>
                                        <path id="XMLID_25_" class="st0" d="M22,17.6c-4.7,0-8.8,2.1-11.6,5.5c2.7,3.4,6.9,5.5,11.6,5.5s8.8-2.1,11.6-5.5
		C30.8,19.7,26.7,17.6,22,17.6z"/>
                                    </g>
                                    <g id="XMLID_21_">
                                        <path id="XMLID_23_" class="st0" d="M23,101.4c-4.1,0-7.4,3.3-7.4,7.4c0,2,0.5,3.2,2,5c1.5,1.8,2.1,3.1,2.1,5.1v2.4h6.7V119
		c0-2,0.6-3.3,2.1-5.1c1.5-1.8,2-3.1,2-5C30.4,104.7,27.1,101.4,23,101.4z"/>
                                        <line id="XMLID_22_" class="st0" x1="19.6" y1="117.9" x2="26.4" y2="117.9"/>
                                    </g>
                                    <g id="XMLID_18_">
                                        <polyline id="XMLID_20_" class="st0" points="27.6,244.7 14.5,251 20.8,237.8 	"/>
                                        <circle id="XMLID_19_" class="st0" cx="26" cy="239.5" r="5.5"/>
                                    </g>
                                    <g id="XMLID_15_">
                                        <circle id="XMLID_17_" class="st0" cx="18.9" cy="286.1" r="6.5"/>
                                        <circle id="XMLID_16_" class="st0" cx="27.1" cy="286.1" r="6.5"/>
                                    </g>
                                    <polygon id="XMLID_14_" class="st0" points="23,186.9 25.4,194.5 33.4,194.5 27,199.1 29.4,206.6 23,202 16.6,206.6 19,199.1
	12.6,194.5 20.6,194.5 "/>
                                    <g id="XMLID_11_">
                                        <path id="XMLID_13_" class="st0" d="M12.9,149.6c-1.3,1.3-1.3,3.3,0,4.6l1,1l-1,1c-1.3,1.3-1.3,3.3,0,4.6c1.3,1.3,3.3,1.3,4.6,0
		l5.6-5.6l-5.6-5.6C16.2,148.3,14.1,148.3,12.9,149.6z"/>
                                        <path id="XMLID_12_" class="st0" d="M33.1,149.6c1.3,1.3,1.3,3.3,0,4.6l-1,1l1,1c1.3,1.3,1.3,3.3,0,4.6c-1.3,1.3-3.3,1.3-4.6,0
		l-5.6-5.6l5.6-5.6C29.8,148.3,31.9,148.3,33.1,149.6z"/>
                                    </g>
                                    <g id="XMLID_8_">
                                        <polygon id="XMLID_10_" class="st0"
                                                 points="-262,23.1 -271.9,22.1 -271.9,37.1 -262,36.1 -252.1,37.1 -252.1,22.1 	"/>
                                        <line id="XMLID_9_" class="st0" x1="-262" y1="36.1" x2="-262" y2="23.1"/>
                                    </g>
                                    <g id="XMLID_3_">
                                        <g id="XMLID_5_">
                                            <path id="XMLID_7_" class="st0"
                                                  d="M23,331.2c0,0-4.5,0.1-7.3-2.7c-2.8-2.8-2.7-7.3-2.7-7.3s4.5-0.1,7.3,2.7S23,331.2,23,331.2z"
                                                />
                                            <path id="XMLID_6_" class="st0"
                                                  d="M23,331.2c0,0,4.5,0.1,7.3-2.7c2.8-2.8,2.7-7.3,2.7-7.3s-4.5-0.1-7.3,2.7S23,331.2,23,331.2z"
                                                />
                                        </g>
                                        <line id="XMLID_4_" class="st0" x1="23" y1="331.2" x2="23" y2="338.1"/>
                                    </g>
                                </svg></span>
                        </li>
                        <li class="menu-item has-dropdown c-text ">
                            <a href="/rangoli/learn/" class="menu-link main-txt">Learn</a>
                            <span><svg>
<!--                                    <use xlink:href="#learn" x="0" y="0" width="44px" height="44px"/>-->
                                    <g id="XMLID_24_">
                                        <circle id="XMLID_26_" class="st0" cx="-262" cy="85.3" r="3.3"/>
                                        <path id="XMLID_25_" class="st0" d="M-262,79.9c-4.7,0-8.8,2.1-11.6,5.5c2.7,3.4,6.9,5.5,11.6,5.5c4.7,0,8.8-2.1,11.6-5.5
		C-253.2,82-257.3,79.9-262,79.9z"/>
                                    </g>
                                    <g id="XMLID_21_">
                                        <path id="XMLID_23_" class="st0" d="M23,13.1c-4.1,0-7.4,3.3-7.4,7.4c0,2,0.5,3.2,2,5c1.5,1.8,2.1,3.1,2.1,5.1v2.4h6.7v-2.4
		c0-2,0.6-3.3,2.1-5.1c1.5-1.8,2-3.1,2-5C30.4,16.4,27.1,13.1,23,13.1z"/>
                                        <line id="XMLID_22_" class="st0" x1="19.6" y1="29.5" x2="26.4" y2="29.5"/>
                                    </g>
                                    <g id="XMLID_18_">
                                        <polyline id="XMLID_20_" class="st0" points="27.6,244.7 14.5,251 20.8,237.8 	"/>
                                        <circle id="XMLID_19_" class="st0" cx="26" cy="239.5" r="5.5"/>
                                    </g>
                                    <g id="XMLID_15_">
                                        <circle id="XMLID_17_" class="st0" cx="18.9" cy="286.1" r="6.5"/>
                                        <circle id="XMLID_16_" class="st0" cx="27.1" cy="286.1" r="6.5"/>
                                    </g>
                                    <polygon id="XMLID_14_" class="st0" points="23,186.9 25.4,194.5 33.4,194.5 27,199.1 29.4,206.6 23,202 16.6,206.6 19,199.1
	12.6,194.5 20.6,194.5 "/>
                                    <g id="XMLID_11_">
                                        <path id="XMLID_13_" class="st0" d="M12.9,149.6c-1.3,1.3-1.3,3.3,0,4.6l1,1l-1,1c-1.3,1.3-1.3,3.3,0,4.6c1.3,1.3,3.3,1.3,4.6,0
		l5.6-5.6l-5.6-5.6C16.2,148.3,14.1,148.3,12.9,149.6z"/>
                                        <path id="XMLID_12_" class="st0" d="M33.1,149.6c1.3,1.3,1.3,3.3,0,4.6l-1,1l1,1c1.3,1.3,1.3,3.3,0,4.6c-1.3,1.3-3.3,1.3-4.6,0
		l-5.6-5.6l5.6-5.6C29.8,148.3,31.9,148.3,33.1,149.6z"/>
                                    </g>
                                    <g id="XMLID_8_">
                                        <polygon id="XMLID_10_" class="st0"
                                                 points="-262,23.1 -271.9,22.1 -271.9,37.1 -262,36.1 -252.1,37.1 -252.1,22.1 	"/>
                                        <line id="XMLID_9_" class="st0" x1="-262" y1="36.1" x2="-262" y2="23.1"/>
                                    </g>
                                    <g id="XMLID_3_">
                                        <g id="XMLID_5_">
                                            <path id="XMLID_7_" class="st0"
                                                  d="M23,331.2c0,0-4.5,0.1-7.3-2.7c-2.8-2.8-2.7-7.3-2.7-7.3s4.5-0.1,7.3,2.7S23,331.2,23,331.2z"
                                                />
                                            <path id="XMLID_6_" class="st0"
                                                  d="M23,331.2c0,0,4.5,0.1,7.3-2.7c2.8-2.8,2.7-7.3,2.7-7.3s-4.5-0.1-7.3,2.7S23,331.2,23,331.2z"
                                                />
                                        </g>
                                        <line id="XMLID_4_" class="st0" x1="23" y1="331.2" x2="23" y2="338.1"/>
                                    </g>
                                </svg></span>
                        </li>
                        <li class="menu-item has-dropdown c-text ">
                            <span>
                                <svg viewBox="0 0 44 44" height="44px" width="44px" y="0px" x="0px"> <g>     <path d="M12.274,16.006c-1.265,1.265-1.265,3.315,0,4.58l0.973,0.972   l-0.973,0.972c-1.265,1.265-1.265,3.315,0,4.579c1.265,1.265,3.314,1.265,4.579,0l5.552-5.551l-5.552-5.552   C15.589,14.742,13.539,14.742,12.274,16.006z" stroke-miterlimit="10" stroke="#CCCCCC" fill="none"/>     <path d="M32.536,16.006c1.265,1.265,1.265,3.315,0,4.58l-0.973,0.972   l0.973,0.972c1.265,1.265,1.265,3.315,0,4.579c-1.265,1.265-3.314,1.265-4.579,0l-5.552-5.551l5.552-5.552   C29.222,14.742,31.271,14.742,32.536,16.006z" stroke-miterlimit="10" stroke="#CCCCCC" fill="none"/> </g> </svg>
                            </span>
                            <a href="/rangoli/love-yogasmoga/" class="menu-link main-txt">Love</a>
							
                        </li>
                        <li class="menu-item has-dropdown c-text_small r_grey_text">
                            <a href="/rangoli/smogis/" class="menu-link main-txt">SMOGIs</a>
                            <span><svg>
<!--                                    <use xlink:href="#smogis" x="0" y="0" width="44px" height="44px"/>-->
                                    <g id="XMLID_24_">
                                        <circle id="XMLID_26_" class="st0" cx="-262" cy="85.3" r="3.3"/>
                                        <path id="XMLID_25_" class="st0" d="M-262,79.9c-4.7,0-8.8,2.1-11.6,5.5c2.7,3.4,6.9,5.5,11.6,5.5c4.7,0,8.8-2.1,11.6-5.5
		C-253.2,82-257.3,79.9-262,79.9z"/>
                                    </g>
                                    <g id="XMLID_21_">
                                        <path id="XMLID_23_" class="st0" d="M-243-62.1c-4.1,0-7.4,3.3-7.4,7.4c0,2,0.5,3.2,2,5c1.5,1.8,2.1,3.1,2.1,5.1v2.4h6.7v-2.4
		c0-2,0.6-3.3,2.1-5.1c1.5-1.8,2-3.1,2-5C-235.6-58.8-239-62.1-243-62.1z"/>
                                        <line id="XMLID_22_" class="st0" x1="-246.5" y1="-45.6" x2="-239.6" y2="-45.6"/>
                                    </g>
                                    <g id="XMLID_18_">
                                        <polyline id="XMLID_20_" class="st0" points="27.6,244.7 14.5,251 20.8,237.8 	"/>
                                        <circle id="XMLID_19_" class="st0" cx="26" cy="239.5" r="5.5"/>
                                    </g>
                                    <g id="XMLID_15_">
                                        <circle id="XMLID_17_" class="st0" cx="18.9" cy="286.1" r="6.5"/>
                                        <circle id="XMLID_16_" class="st0" cx="27.1" cy="286.1" r="6.5"/>
                                    </g>
                                    <polygon id="XMLID_14_" class="st0" points="23.4,13.1 25.9,20.7 33.8,20.7 27.4,25.3 29.8,32.9 23.4,28.2 17,32.9 19.5,25.3
	13,20.7 21,20.7 "/>
                                    <g id="XMLID_11_">
                                        <path id="XMLID_13_" class="st0" d="M-307.3,181.4c-1.3,1.3-1.3,3.3,0,4.6l1,1l-1,1c-1.3,1.3-1.3,3.3,0,4.6c1.3,1.3,3.3,1.3,4.6,0
		l5.6-5.6l-5.6-5.6C-304,180.1-306,180.1-307.3,181.4z"/>
                                        <path id="XMLID_12_" class="st0" d="M-287,181.4c1.3,1.3,1.3,3.3,0,4.6l-1,1l1,1c1.3,1.3,1.3,3.3,0,4.6c-1.3,1.3-3.3,1.3-4.6,0
		l-5.6-5.6l5.6-5.6C-290.3,180.1-288.3,180.1-287,181.4z"/>
                                    </g>
                                    <g id="XMLID_8_">
                                        <polygon id="XMLID_10_" class="st0"
                                                 points="-262,23.1 -271.9,22.1 -271.9,37.1 -262,36.1 -252.1,37.1 -252.1,22.1 	"/>
                                        <line id="XMLID_9_" class="st0" x1="-262" y1="36.1" x2="-262" y2="23.1"/>
                                    </g>
                                    <g id="XMLID_3_">
                                        <g id="XMLID_5_">
                                            <path id="XMLID_7_" class="st0"
                                                  d="M23,331.2c0,0-4.5,0.1-7.3-2.7c-2.8-2.8-2.7-7.3-2.7-7.3s4.5-0.1,7.3,2.7S23,331.2,23,331.2z"
                                                />
                                            <path id="XMLID_6_" class="st0"
                                                  d="M23,331.2c0,0,4.5,0.1,7.3-2.7c2.8-2.8,2.7-7.3,2.7-7.3s-4.5-0.1-7.3,2.7S23,331.2,23,331.2z"
                                                />
                                        </g>
                                        <line id="XMLID_4_" class="st0" x1="23" y1="331.2" x2="23" y2="338.1"/>
                                    </g>
                                </svg></span>
                        </li>
                        <li class="menu-item has-dropdown c-text_small r_grey_text ys-loc">
                            <a href="/rangoli/ys-locations/" class="menu-link main-txt">YS
                                Locations</a>
                            <span><svg>
<!--                                    <use xlink:href="#locations" x="0" y="0" width="44px" height="44px"/>-->
                                    <g id="XMLID_35_">
                                        <polyline id="XMLID_37_" class="st0" points="27.6,25.2 14.5,31.5 20.7,18.4 	"/>
                                        <circle id="XMLID_36_" class="st0" cx="26" cy="20" r="5.5"/>
                                    </g>
                                    <g id="XMLID_32_">
                                        <rect id="XMLID_34_" x="22.9" y="238.4" class="st0" width="3.9" height="14.7"/>
                                        <circle id="XMLID_33_" class="st0" cx="24.8" cy="232.1" r="2.7"/>
                                    </g>
                                    <g id="XMLID_25_">
                                        <line id="XMLID_31_" class="st0" x1="-150.6" y1="106.8" x2="-146.2" y2="114.3"/>
                                        <line id="XMLID_30_" class="st0" x1="-158.1" y1="114.4" x2="-153.6" y2="106.6"/>
                                        <line id="XMLID_29_" class="st0" x1="-147.7" y1="117" x2="-156.5" y2="117"/>
                                        <circle id="XMLID_28_" class="st0" cx="-152.1" cy="104.1" r="3"/>
                                        <circle id="XMLID_27_" class="st0" cx="-144.7" cy="117" r="3"/>
                                        <path id="XMLID_26_" class="st0"
                                              d="M-156.5,117c0,1.7-1.4,3-3,3s-3-1.4-3-3s1.4-3,3-3S-156.5,115.3-156.5,117"/>
                                    </g>
                                    <g id="XMLID_18_">
                                        <circle id="XMLID_24_" class="st0" cx="24.8" cy="195.5" r="6.6"/>
                                        <circle id="XMLID_23_" class="st0" cx="21" cy="197.7" r="6.6"/>
                                        <circle id="XMLID_22_" class="st0" cx="21" cy="202.1" r="6.6"/>
                                        <circle id="XMLID_21_" class="st0" cx="24.8" cy="204.3" r="6.6"/>
                                        <circle id="XMLID_20_" class="st0" cx="28.6" cy="202.1" r="6.6"/>
                                        <circle id="XMLID_19_" class="st0" cx="28.6" cy="197.7" r="6.6"/>
                                    </g>
                                    <g id="XMLID_15_">
                                        <path id="XMLID_17_" class="st0"
                                              d="M-147.1,37c0,0-4.5,0.1-7.3-2.7s-2.7-7.3-2.7-7.3s4.5-0.1,7.3,2.7S-147.1,37-147.1,37z"/>
                                        <path id="XMLID_16_" class="st0"
                                              d="M-147.1,37c0,0,4.5,0.1,7.3-2.7s2.7-7.3,2.7-7.3s-4.5-0.1-7.3,2.7S-147.1,37-147.1,37z"/>
                                    </g>
                                    <line id="XMLID_14_" class="st0" x1="-147.1" y1="37" x2="-147.1" y2="44"/>
                                    <g id="XMLID_3_">
                                        <g id="XMLID_5_">
                                            <line id="XMLID_12_" class="st0" x1="-211.6" y1="-75.5" x2="-185.5" y2="-75.5"/>
                                            <line id="XMLID_11_" class="st0" x1="-211.6" y1="-80.8" x2="-185.5" y2="-80.8"/>
                                            <line id="XMLID_10_" class="st0" x1="-211.6" y1="-78.2" x2="-185.5" y2="-78.2"/>
                                            <line id="XMLID_9_" class="st0" x1="-201.2" y1="-83.5" x2="-185.5" y2="-83.5"/>
                                            <line id="XMLID_8_" class="st0" x1="-201.2" y1="-86.2" x2="-185.5" y2="-86.2"/>
                                            <line id="XMLID_7_" class="st0" x1="-201.2" y1="-88.8" x2="-185.5" y2="-88.8"/>
                                            <line id="XMLID_6_" class="st0" x1="-201.2" y1="-91.5" x2="-185.5" y2="-91.5"/>
                                        </g>
                                        <polygon id="XMLID_4_" class="st0" points="-207.6,-85.6 -210.1,-83.7 -209.1,-86.7 -211.6,-88.5 -208.5,-88.5 -207.6,-91.5
		-206.6,-88.5 -203.5,-88.5 -206,-86.7 -205,-83.7 	"/>
                                    </g>
                                </svg></span>
                        </li>
                        <li class="menu-item has-dropdown c-text_small r_grey_text ">
                            <?php if (!Mage::getSingleton('customer/session')->isLoggedIn()): ?>
                                <a href="javascript:void(0)" onClick="openLogin()" class="menu-link main-txt">Connect</a>
                            <?php else: ?>
                                <a href="/rangoli/connect/" class="menu-link main-txt">Connect</a>
                            <?php endif ?>
                            <span><svg>
<!--                                    <use xlink:href="#connect" x="0" y="0" width="44px" height="44px"/>-->
                                    <g id="XMLID_24_">
                                        <circle id="XMLID_26_" class="st0" cx="-262" cy="85.3" r="3.3"/>
                                        <path id="XMLID_25_" class="st0" d="M-262,79.9c-4.7,0-8.8,2.1-11.6,5.5c2.7,3.4,6.9,5.5,11.6,5.5c4.7,0,8.8-2.1,11.6-5.5
		C-253.2,82-257.3,79.9-262,79.9z"/>
                                    </g>
                                    <g id="XMLID_21_">
                                        <path id="XMLID_23_" class="st0" d="M-243-62.1c-4.1,0-7.4,3.3-7.4,7.4c0,2,0.5,3.2,2,5c1.5,1.8,2.1,3.1,2.1,5.1v2.4h6.7v-2.4
		c0-2,0.6-3.3,2.1-5.1c1.5-1.8,2-3.1,2-5C-235.6-58.8-239-62.1-243-62.1z"/>
                                        <line id="XMLID_22_" class="st0" x1="-246.5" y1="-45.6" x2="-239.6" y2="-45.6"/>
                                    </g>
                                    <g id="XMLID_18_">
                                        <polyline id="XMLID_20_" class="st0" points="312.5,82.1 299.3,88.4 305.6,75.3 	"/>
                                        <circle id="XMLID_19_" class="st0" cx="310.8" cy="76.9" r="5.5"/>
                                    </g>
                                    <g id="XMLID_15_">
                                        <circle id="XMLID_17_" class="st0" cx="18.9" cy="22" r="6.5"/>
                                        <circle id="XMLID_16_" class="st0" cx="27.1" cy="22" r="6.5"/>
                                    </g>
                                    <polygon id="XMLID_14_" class="st0" points="-239.6,155 -237.2,162.5 -229.2,162.5 -235.6,167.2 -233.2,174.7 -239.6,170
	-246,174.7 -243.6,167.2 -250,162.5 -242,162.5 "/>
                                    <g id="XMLID_11_">
                                        <path id="XMLID_13_" class="st0" d="M-307.3,181.4c-1.3,1.3-1.3,3.3,0,4.6l1,1l-1,1c-1.3,1.3-1.3,3.3,0,4.6c1.3,1.3,3.3,1.3,4.6,0
		l5.6-5.6l-5.6-5.6C-304,180.1-306,180.1-307.3,181.4z"/>
                                        <path id="XMLID_12_" class="st0" d="M-287,181.4c1.3,1.3,1.3,3.3,0,4.6l-1,1l1,1c1.3,1.3,1.3,3.3,0,4.6c-1.3,1.3-3.3,1.3-4.6,0
		l-5.6-5.6l5.6-5.6C-290.3,180.1-288.3,180.1-287,181.4z"/>
                                    </g>
                                    <g id="XMLID_8_">
                                        <polygon id="XMLID_10_" class="st0"
                                                 points="-262,23.1 -271.9,22.1 -271.9,37.1 -262,36.1 -252.1,37.1 -252.1,22.1 	"/>
                                        <line id="XMLID_9_" class="st0" x1="-262" y1="36.1" x2="-262" y2="23.1"/>
                                    </g>
                                    <g id="XMLID_3_">
                                        <g id="XMLID_5_">
                                            <path id="XMLID_7_" class="st0"
                                                  d="M23,331.2c0,0-4.5,0.1-7.3-2.7c-2.8-2.8-2.7-7.3-2.7-7.3s4.5-0.1,7.3,2.7S23,331.2,23,331.2z"
                                                />
                                            <path id="XMLID_6_" class="st0"
                                                  d="M23,331.2c0,0,4.5,0.1,7.3-2.7c2.8-2.8,2.7-7.3,2.7-7.3s-4.5-0.1-7.3,2.7S23,331.2,23,331.2z"
                                                />
                                        </g>
                                        <line id="XMLID_4_" class="st0" x1="23" y1="331.2" x2="23" y2="338.1"/>
                                    </g>
                                </svg></span>
                        </li>
                        <li class="menu-item has-dropdown c-text_small r_grey_text">
                            <a href="/rangoli/about/" class="menu-link main-txt">About</a>
                            <span><svg>
<!--                                    <use xlink:href="#about" x="0" y="0" width="44px" height="44px"/>-->
                                    <g id="XMLID_24_">
                                        <circle id="XMLID_26_" class="st0" cx="-262" cy="85.3" r="3.3"/>
                                        <path id="XMLID_25_" class="st0" d="M-262,79.9c-4.7,0-8.8,2.1-11.6,5.5c2.7,3.4,6.9,5.5,11.6,5.5c4.7,0,8.8-2.1,11.6-5.5
		C-253.2,82-257.3,79.9-262,79.9z"/>
                                    </g>
                                    <g id="XMLID_21_">
                                        <path id="XMLID_23_" class="st0" d="M-243-62.1c-4.1,0-7.4,3.3-7.4,7.4c0,2,0.5,3.2,2,5c1.5,1.8,2.1,3.1,2.1,5.1v2.4h6.7v-2.4
		c0-2,0.6-3.3,2.1-5.1c1.5-1.8,2-3.1,2-5C-235.6-58.8-239-62.1-243-62.1z"/>
                                        <line id="XMLID_22_" class="st0" x1="-246.5" y1="-45.6" x2="-239.6" y2="-45.6"/>
                                    </g>
                                    <g id="XMLID_18_">
                                        <polyline id="XMLID_20_" class="st0" points="312.5,82.1 299.3,88.4 305.6,75.3 	"/>
                                        <circle id="XMLID_19_" class="st0" cx="310.8" cy="76.9" r="5.5"/>
                                    </g>
                                    <g id="XMLID_15_">
                                        <circle id="XMLID_17_" class="st0" cx="213.4" cy="148.5" r="6.5"/>
                                        <circle id="XMLID_16_" class="st0" cx="221.5" cy="148.5" r="6.5"/>
                                    </g>
                                    <polygon id="XMLID_14_" class="st0" points="-239.6,155 -237.2,162.5 -229.2,162.5 -235.6,167.2 -233.2,174.7 -239.6,170
	-246,174.7 -243.6,167.2 -250,162.5 -242,162.5 "/>
                                    <g id="XMLID_11_">
                                        <path id="XMLID_13_" class="st0" d="M-307.3,181.4c-1.3,1.3-1.3,3.3,0,4.6l1,1l-1,1c-1.3,1.3-1.3,3.3,0,4.6c1.3,1.3,3.3,1.3,4.6,0
		l5.6-5.6l-5.6-5.6C-304,180.1-306,180.1-307.3,181.4z"/>
                                        <path id="XMLID_12_" class="st0" d="M-287,181.4c1.3,1.3,1.3,3.3,0,4.6l-1,1l1,1c1.3,1.3,1.3,3.3,0,4.6c-1.3,1.3-3.3,1.3-4.6,0
		l-5.6-5.6l5.6-5.6C-290.3,180.1-288.3,180.1-287,181.4z"/>
                                    </g>
                                    <g id="XMLID_8_">
                                        <polygon id="XMLID_10_" class="st0"
                                                 points="-262,23.1 -271.9,22.1 -271.9,37.1 -262,36.1 -252.1,37.1 -252.1,22.1 	"/>
                                        <line id="XMLID_9_" class="st0" x1="-262" y1="36.1" x2="-262" y2="23.1"/>
                                    </g>
                                    <g id="XMLID_3_">
                                        <g id="XMLID_5_">
                                            <path id="XMLID_7_" class="st0"
                                                  d="M22,24.6c0,0-4.5,0.1-7.3-2.7S12,14.6,12,14.6s4.5-0.1,7.3,2.7S22,24.6,22,24.6z"/>
                                            <path id="XMLID_6_" class="st0"
                                                  d="M22,24.6c0,0,4.5,0.1,7.3-2.7s2.7-7.3,2.7-7.3s-4.5-0.1-7.3,2.7S22,24.6,22,24.6z"/>
                                        </g>
                                        <line id="XMLID_4_" class="st0" x1="22" y1="24.6" x2="22" y2="31.6"/>
                                    </g>

                                </svg></span>
                        </li>

                    </ul>
                    <span class="border-line"></span>
                </li>
				<?php */ ?>
                    <li class="menu-item additional_links">
                        <ul>
                            <li><a href="javascript:void(0);">&copy; 2015 YOGASMOGA</a></li>
							<li><a href="<?php echo $this->getBaseUrl(); ?>contacts/">Contact</a></li>
							<li><a href="<?php echo $this->getBaseUrl(); ?>help/">Help</a></li>
							<li><a href="<?php echo $this->getBaseUrl(); ?>careers/">Careers</a></li>
                            <li><a href="<?php echo $this->getBaseUrl(); ?>privacy-policy/">Privacy Policy</a></li>
                            <li><a href="<?php echo $this->getBaseUrl(); ?>terms-and-conditions/">Terms &amp; Conditions</a></li>
                        </ul>
                    </li>

            </ul>
        </div>
    </div>
</div>

<script>
    jQuery(document).ready(function($){
        var child = "cat_<?php echo  Mage::getModel('catalog/layer')->getCurrentCategory()->getId();?>";

        if($("a[rel='"+child+"']").attr("data")!==undefined) {
             var parent = $("a[rel='"+child+"']").attr("data");
            $("a[rel='" + parent + "']").next().click();
        }

        $("a[rel='"+child+"']").next().click();

    });
</script>