<?php  $currentUrl = Mage::helper('core/url')->getCurrentUrl();?>
<script type="text/javascript">
    var currenturl = <?php echo $currentUrl; ?>
    var s1 = <?php echo $currentUrl; ?>;
    jQuery("ul.sub-nav li").each(function(){
        var s2 = jQuery(this).find("a").attr("href");
        if(s1 == s2)
        {
            jQuery(this).addClass("current");
        }
    });
</script>
<div class="account-nav top-divider">
	<ul class="sub-nav">
		<li><a href="<?php echo Mage::getUrl('',array('_secure'=>true)); ?>customer/account/index">Dashboard <span class="arr">&gt;</span></a></li>
		<li><a href="<?php echo Mage::getUrl('',array('_secure'=>true)); ?>sales/order/history">My Orders <span class="arr">&gt;</span></a></li>
		<li><a href="<?php echo Mage::getUrl('',array('_secure'=>true)); ?>wishlist">Wish list <span class="arr">&gt;</span></a></li>
		<li><a href="<?php echo Mage::getUrl('',array('_secure'=>true)); ?>gift_of_ys">Redeem Gift Card <span class="arr">&gt;</span></a></li>
		<li>&nbsp;</li>
	    <li><a href="<?php echo Mage::getUrl('',array('_secure'=>true)); ?>customer/account/edit">Edit Account Info <span class="arr">&gt;</span></a></li>
	    <li><a href="<?php echo Mage::getUrl('',array('_secure'=>true)); ?>customer/address">Address Book <span class="arr">&gt;</span></a></li>
	    <li><a href="<?php echo Mage::getUrl('',array('_secure'=>true)); ?>rewardpoints/index/referral/">Share with friends <span class="arr">&gt;</span></a></li>
	</ul>
</div>