<div class="namaskar-overlay1">&nbsp;</div>
<script type="text/javascript">
    jQuery(window).load(function(){
        jQuery('body').css('overflow','auto');
        jQuery('.namaskar-overlay1').fadeOut('slow');
    })
</script>
<!-- startCMSPages -->
<div class="gridCMSPages">
	<!-- gridBlockOne -->
	<div class="gridFullWidth ystopsection">
		<!-- BlockLeft -->
		<div class="block33">
			<!-- leftNavigation -->
			<div class="cmsNavigation">
				<ul>
					<li><a href="/ys-fabric-tech">YS Fabric Tech</a></li>
					<li><a href="/ys-color-tech">Ys Color Tech</a></li>
					<li><a href="/design-elements" class="current">YS Design Elements</a></li>
				</ul>
			</div>
			<!-- leftNavigation -->

			<!-- CMSheadingBlock -->
			<div class="headingBlock">
				<h1 class="positionAbs">YS Design<br />Elements</h1>
			</div>
			<!-- CMSheadingBlock -->
		</div>
		<!-- BlockLeft -->

		<!-- BlockRight -->
		<div class="block66 posRel">
			<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/de-banner.jpg" alt="" class="img-responsive" />
			<div class="positionAbs" id="ysbannertxt" style="top:32.4%">
				<span class="topHead">YS DESIGN ELEMENTS</span>
				<h4>
					WE SWEAT THE DETAILS
					<span class="smallHead">UNCOMPROMISED DETERMINATION TO ACHIEVE EXCELLENCE</span>
				</h4>
				<!--div class="htext white" style="margin-top:145px;">Don't forget to breathe when you see our beautiful design features.<br />Every Stitch. Every Inch. Every Yard. Every detail matters.</div-->
			</div>
<div class="htext white" style="position:absolute; width:100%; margin:0; bottom:40px;">Don't forget to breathe when you see our beautiful design features.<br />Every Stitch. Every Inch. Every Yard. Every detail matters.</div>
		</div>
		<!-- BlockRight -->
	</div>
	<!-- gridBlockOne -->

	<!-- gridBlockTwo -->
	<div class="gridFullWidth marginbottom50">
		<!-- BlockOne -->
		<div class="block30">
			<!-- contentPart -->
			<div class="textContainer">
				<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/de-gusset.jpg" alt="" class="img-responsive" />
				<div class="cntntheading">
					THE YS GUSSET
				</div>
				<div class="contnttxt">
					<p>Soft to the touch, our advanced YS Gusset is lined with soft, delicate & highly breathable antimicrobial and moisture wicking Auro Mesh fabric that lets you feel fresh all day long.</p>
					<ul class="arw-list">
						<li>The custom jacquard weave in our gusset lining combines generous breathability with delicate design to give you your own little secret.</li>
					</ul>
				</div>
			</div>
			<!-- contentPart -->
		</div>
		<!-- BlockOne -->

		<!-- BlockTwo -->
		<div class="block30">
			<!-- contentPart -->
			<div class="textContainer">
				<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/de-pocket.jpg" alt="" class="img-responsive" />
				<div class="cntntheading">
					UP-&-IN POCKET
				</div>
				<div class="contnttxt">
					<p>Our secret pockets discretely hold your essentials, so all the attention stays in the right places.</p>
					<ul class="arw-list">
						<li>This smooth, sleek pocket goes up & in, without cutting into the figure flattering design.</li>
						<li>Our slim pockets keep your essentials invisible to the  naked eye yet easily accessible when you need them.</li>
					</ul>
				</div>
			</div>
			<!-- contentPart -->
		</div>
		<!-- BlockTwo -->

		<!-- BlockThree -->
		<div class="block30">
			<!-- contentPart -->
			<div class="textContainer">
				<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/de-waistband.jpg" alt="" class="img-responsive" />
				<div class="cntntheading">
					SKINNY-NO MUFFIN<br />WAISTBAND
				</div>
				<div class="contnttxt">
					<p>A waistband that banishes Muffin Top. Our crafted waistband is designed to highlight your curves while toning and hugging in your waist for an outstanding fit.</p>
					<ul class="arw-list">
						<li>Our skinny waistband holds you in using high memory retention Lycra<sup>&reg;</sup> as opposed to bulky and extra fabric.</li>
					</ul>
				</div>
			</div>
			<!-- contentPart -->
		</div>
		<!-- BlockThree -->
	</div>
	<!-- gridBlockTwo -->

	<!-- gridBlockThree -->
	<div class="gridFullWidth iconrh">
		<!-- BlockOne -->
		<div class="block30">
			<!-- contentPart -->
			<div class="textContainer">
				<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/de-cut.jpg" alt="" class="img-responsive" />
				<div class="cntntheading">
					THE SLIMMIE CUT
				</div>
				<div class="contnttxt">
					<p>The Slimmie Cut strategically cinches in your waist. The tight cut at the knees tones and slims while preventing ride up.</p>
				</div>
			</div>
			<!-- contentPart -->
		</div>
		<!-- BlockOne -->

		<!-- BlockTwo -->
		<div class="block30">
			<!-- contentPart -->
			<div class="textContainer">
				<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/de-bra.jpg" alt="" class="img-responsive" />
				<div class="cntntheading">
					SPORTS BRA<br />KEY ZONE VENTS
				</div>
				<div class="contnttxt">
					<p>Highly breathable Zari Mesh vents strategically placed to cool you down, so you look hot.</p>
				</div>
			</div>
			<!-- contentPart -->
		</div>
		<!-- BlockTwo -->

		<!-- BlockThree -->
		<div class="block30">
			<!-- contentPart -->
			<div class="textContainer">
				<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/de-back-cut.jpg" alt="" class="img-responsive" />
				<div class="cntntheading">
					NO DIG-IN<br />RACER BACK CUT
				</div>
				<div class="contnttxt">
					<p>Our perfect racer back cut showcases your sexy shoulders and provides freedom of movement. The straps are designed to sit at a specific angle so they don’t dig in.</p>
				</div>
			</div>
			<!-- contentPart -->
		</div>
		<!-- BlockThree -->
	</div>
	<!-- gridBlockThree -->

	<!-- bottomDivider -->
	<div class="bottomdivider"></div>
	<!-- bottomDivider -->

</div>
<!-- endCMSPages -->