<div class="namaskar-overlay1">&nbsp;</div>
<script type="text/javascript">
    jQuery(window).load(function(){
        jQuery('body').css('overflow','auto');
        jQuery('.namaskar-overlay1').fadeOut('slow');
    })
</script>
<!-- startCMSPages -->
<div class="gridCMSPages">
	<!-- gridBlockOne -->
	<div class="gridFullWidth ystopsection">
		<!-- BlockLeft -->
		<div class="block33">
			<!-- leftNavigation -->
			<div class="cmsNavigation">
				<ul>
					<li><a href="/our-story">our story</a></li>
					<li><a href="/our-core-values">our core values</a></li>
					<li><a href="/our-ethics">our ethics</a></li>
                    <!--<li><a href="/our-stores">our stores</a></li>-->
					<li><a href="/made-in-usa" class="current">made in usa</a></li>
					<li><a href="/principles-of-yoga">principles of yoga</a></li>
					<li><a href="/namaskar">namaskÁr foundation</a></li>
					<li><a href="/press">press</a></li>
				</ul>
			</div>
			<!-- leftNavigation -->

			<!-- CMSheadingBlock -->
			<div class="headingBlock">
				<div class="positionAbs h1">made in<br/> usa</div>
				<h1 style="display:none;">Made in USA</h1>
			</div>
			<!-- CMSheadingBlock -->
		</div>
		<!-- BlockLeft -->

		<!-- BlockRight -->
		<div class="block66">
			<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/miu-b2.jpg" alt="MADE IN USA" class="img-responsive" />
		</div>
		<!-- BlockRight -->
	</div>
	<!-- gridBlockOne -->

	<!-- gridBlockContent -->
	<div class="gridBlockContent">
		<span>RESPONSIBLE PRODUCTION</span>
		<div class="h3">STREAMLINING, HELPING, REDUCING, RAISING
			<span>EVERYTIME YOU PURCHASE YOGASMOGA PRODUCTS</span>
		</div>
	</div>
	<!-- gridBlockContent -->

	<!-- gridBlockTwo -->
	<div class="gridFullWidth marginbottom50">
		<!-- BlockLeft -->
		<div class="block50">
			<!-- contentPart -->
			<div class="textContainer">
				<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/ys-miu-worker.jpg" alt="YOU HELP FACTORY WORKERS & THEIR FAMILIES" class="img-responsive" id="" />
				<div class="cntntheading">
					YOU HELP
					<span>FACTORY WORKERS & THEIR FAMILIES</span>
				</div>
				<div class="contnttxt">
					<p>Many consumers don’t realize that every piece of clothing that is made any where in the world is stitched together by a human: Every piece of clothing generally goes through the same labor-intensive stitching process. Labor at times accounts for 50 percent of the cost of manufacturing.</p>
<p>We chose to manufacture our products in factories in the US. Many domestic factories have been left behind in the quest by brands to chase the cheapest labor abroad. We take pride in giving the opportunity to domestic workers who are qualified technicians with a lot of experience but not enough work so we deliver the highest quality product to our customers. </p>
				</div>
			</div>
			<!-- contentPart -->
		</div>
		<!-- BlockLeft -->

		<!-- BlockRight -->
		<div class="block50">
			<!-- contentPart -->
			<div class="textContainer">
				<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/miu2.jpg" alt="YOU STREAMLINE THE AMERICAN ECONOMY" class="img-responsive" id="" />
				<div class="cntntheading">
					YOU STREAMLINE
					<span>THE GLOBAL SUPPLY CHAIN</span>
				</div>
				<div class="contnttxt">
					<p>In today’s world, business and manufacturing is globalized. Globalization has caused us to become interconnected but also interdependent. Manufacturing that used to happen in our backyards has shifted to factories thousands of miles away.</p>
					<p>Our commitment to manufacturing in the US means that every time you buy a piece of YOGASMOGA clothing it comes straight from our backyard and not from half way across the world.</p>
				</div>
			</div>
			<!-- contentPart -->
		</div>
		<!-- BlockRight -->
	</div>
	<!-- gridBlockTwo -->

	<!-- gridBlockThree -->
	<div class="gridFullWidth">
		<!-- BlockLeft -->
		<div class="block50">
			<!-- contentPart -->
			<div class="textContainer">
				<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/miu3.jpg"  alt="YOU REDUCE THE CARBON FOOTPRINT" class="img-responsive" id="" />
				<div class="cntntheading">
					YOU REDUCE
					<span>THE CARBON FOOTPRINT</span>
				</div>
				<div class="contnttxt lineheight18">
					<p>Our awareness of increasingly limited environmental resources creates an even deeper appreciation for what we have to work with. It necessitates a fundamental commitment to decreasing our environmental impact. We think critically about every aspect of our clothing production - from sourcing of trims to delivering the finished product to you - which is why our carbon footprint is significantly smaller than most of our competitors. </p>
<p>For more on our eco-friendly production, see <a href="/our-ethics" class="f11">OUR ETHICS</a>. </p>
				</div>
			</div>
			<!-- contentPart -->
		</div>
		<!-- BlockLeft -->

		<!-- BlockRight -->
		<div class="block50">
			<!-- contentPart -->
			<div class="textContainer">
				<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/miu4.jpg" alt="YOU RAISE AMERICAN WORKERS' WAGES" class="img-responsive" id="" />
				<div class="cntntheading">
					YOU RAISE
					<span>AMERICAN WORKERs' WAGES</span>
				</div>
				<div class="contnttxt lineheight18">
					<p>We realize that the decisions we make as a company have serious consequences for families and individuals. There is a certain satisfaction to be had to revive factories that have been abandoned and are on their last leg.</p>
					<p>We feel a sense of achievement that we are doing our part to stimulate the domestic economy - hiring individuals at our headquarters in New York City, at our stores and in all of our various factories. Workers that are manufacturing  YOGASMOGA apparel domestically have health insurance and 401(k) plans.</p>
				</div>
			</div>
			<!-- contentPart -->
		</div>
		<!-- BlockRight -->
	</div>
	<!-- gridBlockThree -->

	<!-- bottomDivider -->
	<div class="bottomdivider"></div>
	<!-- bottomDivider -->

</div>
<!-- endCMSPages -->