<div class="namaskar-overlay1">&nbsp;</div>
<script type="text/javascript">
    jQuery(window).load(function () {
        jQuery('body').css('overflow', 'auto');
        jQuery('.namaskar-overlay1').fadeOut('slow');
    })
</script>
<!-- startCMSPages -->
<div class="gridCMSPages">
    <!-- gridBlockOne -->
    <div class="gridFullWidth ystopsection">
        <!-- BlockLeft -->
        <div class="block33">
            <!-- leftNavigation -->
            <div class="cmsNavigation">
                <ul>
                    <li><a href="/our-story">our story</a></li>
                    <li><a href="/our-core-values">our core values</a></li>
                    <li><a href="/our-ethics">our ethics</a></li>
                    <li><h1 style="font:11px/19px gothambold !important;margin:0"><a href="/our-stores" class="current">our
                                stores</a></h1></li>
                    <li><a href="/made-in-usa">made in usa</a></li>
                    <li><a href="/principles-of-yoga">principles of yoga</a></li>
                    <li><a href="/namaskar">namaskÁr foundation</a></li>
                    <li><a href="/press">press</a></li>
                </ul>
            </div>
            <!-- leftNavigation -->

            <!-- CMSheadingBlock -->
            <div class="headingBlock">
                <h1 class="positionAbs">YS STORES</h1>
            </div>
            <!-- CMSheadingBlock -->
        </div>
        <!-- BlockLeft -->

        <!-- BlockRight -->
        <div class="block66 posRel">
            <img src="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/new-design-images/YS-Store-yogasmoga-retail.jpg"
                 alt="" class="img-responsive"/>

            <div class="positionAbs" id="ysbannertxt" style="top:32.4%;">
                <span class="topHead">YOGASMOGA RETAIL EXPERIENCE</span>
                <h4>
                    FROM NYC TO THE WORLD
                    <span class="smallHead">WE GO WHEREVER LIFE TAKES YOU</span>
                </h4>
                <!--div class="htext white">
                    Honoring the tenets of Yoga, we aspire to create world-class products.<br />Growing up in the Himalayas, the birthplace & capital of Yoga, our founders instinctively<br />infuse the timeless principles, spirit and practice of Yoga into everything we do. From our<br />cosmopolitan aesthetic, to our product technology, right down to creating our very own way<br />to give back, we’ve meticulously designed every part of the whole, one breath at a time.
                </div-->
            </div>
            <!--<div class="htext white" style="position:absolute; width:100%; margin:0; bottom:40px;">
                                Honoring the tenets of Yoga, we aspire to create world-class products.<br />Growing up in the Himalayas, the birthplace & capital of Yoga, our founders instinctively<br />infuse the timeless principles, spirit and practice of Yoga into everything we do. From our<br />cosmopolitan aesthetic, to our product technology, right down to creating our very own way<br />to give back, we’ve meticulously designed every part of the whole, one breath at a time.
                            </div>-->
        </div>
        <!-- BlockRight -->
    </div>
    <!-- gridBlockOne -->
    <div class="gridFullWidth">
        <div id="ysbannertxt" class="gridCMSPages">
            <span style="color:#555;display:block;border-bottom:1px solid #555;margin:17px auto 15px" class="topHead ">IMAGINE: A STRONG COMMUNITY</span>
            <h4 style="color:#555;width:100%;font:36px/40px ITCAvantGardeProMd;margin-bottom:0;" class="topHead ">
                REFLECT, CONNECT, LEARN, GROW
                <span style="color:#555;" class="smallHead cntntheading">ONE BREATH AT A TIME</span>
            </h4>
        </div>
    </div>

    <!-- gridBlockTwo -->
    <div class="gridFullWidth marginbottom50">
        <div class="gridFullWidth">
            <div class="block33">
                <img src="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/new-design-images/YS-Stores-020815_04.jpg"
                     alt="" class="img-responsive"/>
            </div>
            <div class="block33">
                <img src="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/new-design-images/YS-Stores-020815_05.jpg"
                     alt="" class="img-responsive"/>
            </div>
            <div class="block33">
                <img class="img-responsive"
                     src="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/new-design-images/ys_stores_address/ys-stores-beverly-hills.jpg"
                     alt=""/>
            </div>
        </div>

        <div class="gridFullWidth">
            <div class="block33">
                <div class="cntntheading">
                    <div class="content-wrapper">
                        YOGASMOGA TOWNHOUSE
                        <span>68 GREENWICH AVE <br/>GREENWICH, CT 06830<br/>203 861 YOGA (9642)</span>
                    </div>

                </div>


            </div>

            <div class="block33">
                <div class="cntntheading">
                    <div class="content-wrapper">
                        YOGASMOGA BRENTWOOD
							<span>11911 SAN VICENTE BLVD, #150<br/> LOS ANGELES, CA 90049<br/>
											 310 471 YOGA (9642)</span>
                    </div>
                </div>

            </div>
            <div class="block33">
                <div class="cntntheading">
                    <div class="content-wrapper">
                        YOGASMOGA BEVERLY HILLS
                        <span>9458 Dayton Way<br/>Beverly Hills, CA 90210<br/>310 273 YOGA(9642)</span></div>


                </div>


            </div>
        </div>
        <div class="gridFullWidth">
            <div class="block33">
                <div class="contnttxt">
                    <span style="font-size:16px;font-family: AvantGardeGothicITCW01X;text-transform:lowercase">greenwich@yogasmoga.com</span>

                    <p style="text-align:center">
                        <span style="font-weight:bold">Store Hours</span><br/>Monday–Friday 10am–6pm<br/>
                        Saturday-Sunday 11am-6pm </p>

                    <p style="font-family:gothambook;">We chose this two-story townhouse on Greenwich Avenue as our
                        first store for its strong community feel. The exposed brick walls create a cozy atmosphere and
                        neutral palette for our bright collections. We are currently renovating the upstairs space for
                        yoga classes and other wellness events. </p>
                </div>


            </div>

            <div class="block33">
                <div class="contnttxt">
                    <span style="font-size:16px;font-family: AvantGardeGothicITCW01X;text-transform:lowercase">brentwood@yogasmoga.com</span>

                    <p style="text-align:center"><span style="font-weight:bold">Store Hours</span><br/>Monday–Friday
                        10am–8pm<br/>
                        Saturday–Sunday 11am–7pm </p>

                    <p style="font-family:gothambook;">Centrally located on the corner of San Vicente Boulevard and
                        Montana Avenue, we chose this space for its accessibility and neighborhood vibe. Our bright and
                        sunny Brentwood store is wrapped in floor-to-ceiling windows that fill the space with natural
                        light and warm, welcoming energy. </p>
                    <!--<p style="font-family:gothambook;">Just around the corner from Rodeo Drive, our Beverly Hills store is a calming retreat from the buzz of the city streets. Exposed beams, bright light and a cozy community space welcomes locals and visitors alike to shop our unique collection, relax and learn more about the YOGASMOGA story.</p>-->

                </div>


            </div>

            <div class="block33">
                <div class="contnttxt">
                    <span style="font-size:16px;font-family: AvantGardeGothicITCW01X;text-transform:lowercase">beverlyhills@yogasmoga.com</span>

                    <p style="text-align:center"><span
                            style="font-weight:bold">Store Hours</span><br/>Monday–Friday 11am–7pm<br/>
                        Saturday-Sunday 11am–6pm </p>

                    <p style="font-family:gothambook;">Just around the corner from Rodeo Drive, our Beverly Hills store
                        is a calming retreat from the buzz of the city streets. Exposed beams, bright light and a cozy
                        community space welcomes locals and visitors alike to shop our unique collection, relax and
                        learn more about the YOGASMOGA story.</p>

                </div>


            </div>
        </div>
        <div style="border-bottom:1px solid #fff!important;" class="bottomdivider">&nbsp;</div>

        <div class="gridFullWidth">
		 <div class="block33">
                <!--------------- svg start----------->
               <img src="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/new-design-images/ys_stores_address/fashion-island.jpg"
                     alt="" class="img-responsive"/>

                <!--------------- svg ends----------->
            </div>
          
			<div class="block33 white-line-seperator">
                <!--------------- svg starts----------->
               <img src="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/new-design-images/ys_stores_address/yogasmoga-pru.jpg"
                     alt="" class="img-responsive"/>
                <!--------------- svg ends----------->
            </div>
            <div class="block33">
                <!--------------- svg starts----------->
                <img src="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/new-design-images/ys_stores_address/ys-malibu.jpg"
                     alt="" class="img-responsive"/>
                <!--------------- svg ends----------->
            </div>
			


        </div>
        <div class="gridFullWidth">
            <div class="block33">
                <div class="cntntheading">
                    <div class="content-wrapper">
                        YOGASMOGA NEWPORT BEACH <br/>
                        <span style="display:inline;">AT</span> FASHION ISLAND <span>1119 Newport Center Drive <br/>Newport Beach, CA 92660<br/>949 721 9642
								</span>
                    </div>


                </div>


            </div>

             <div class="block33">
                <div class="cntntheading">
                    <div class="content-wrapper">
                        YOGASMOGA
                        <span style="display:inline;">AT </span>“THE PRU”
								<span>800 BOYLSTON STREET, #131<br/>BOSTON, MA 02199<br/>888 990 YOGA (9642)
								<br/><br/></span>
                    </div>

                </div>


            </div>
            <div class="block33">
                <div class="cntntheading">
                    <div class="content-wrapper">
                        YOGASMOGA MALIBU <br/> <span>3900 CROSS CREEK RD<br/>MALIBU, CA 90265<br/>888 990 YOGA (9642)
									</span>
                    </div>


                </div>


            </div>
        </div>
        <div class="gridFullWidth">
              <div class="block33">
                <div class="contnttxt">
                    <span style="font-size:16px;font-family: AvantGardeGothicITCW01X;text-transform:lowercase">fashionisland@yogasmoga.com</span>

                    <p style="text-align:center;">
                        <span style="font-weight:bold">Store Hours</span><br/>Monday–Friday 10am–9pm<br/>
                        Saturday 10am–7pm<br/>Sunday 11am-6pm
                    </p>

                    <p style="font-family:gothambook;">Now open in between Macy's and Nordstrom, our Fashion Island store is an upscale, open-air space perfect for in-store classes. Richly colored wood displays showcase our unique and colorful collection, inviting visitors to shop, relax and learn more about the YOGASMOGA story.

                    </p>

                </div>


            </div>

          <div class="block33">
                <div class="contnttxt">
                    <span style="font-size:16px;font-family: AvantGardeGothicITCW01X;text-transform:lowercase">boston.pru@yogasmoga.com</span>

                    <p style="text-align:center">
                        <span style="font-weight:bold">Store Hours</span><br/>Monday–Saturday 10am–9pm<br/>
                        Sunday 11am–8pm<br/>&nbsp;
                    </p>

                    <p style="font-family:gothambook;">YOGASMOGA is now open at The Shops at the Prudential Center. The Pru, as it is most colloquially known, is an urban shopping center located at the base of the Prudential Tower. This location is special to us because we are able to bring our Made In USA product from Fall River, Massachusetts closer to your Boston doorstep.</p>

                </div>


            </div>

             <div class="block33">
                <div class="contnttxt">
                    <span style="font-size:16px;font-family: AvantGardeGothicITCW01X;text-transform:lowercase">malibu@yogasmoga.com</span>

                    <p style="text-align:center">
                        <span style="font-weight:bold">Store Hours</span><br/>Monday–Saturday 10am–7pm<br/>
                        Sunday 11am–6pm
                    </p>
					<p style="margin: 0;line-height: 15px;">&nbsp;</p>
                    <p style="font-family:gothambook;">Now open in the Malibu Country Mart: a large outdoor, lifestyle center or "boutique mall" located at the Civic Center of Malibu. Wearing your YOGASMOGAs while basking in the sun is the best way to experience this sunny beach city.</p>

                </div>


            </div>
        </div>
        <div style="border-bottom:1px solid #fff!important;" class="bottomdivider">&nbsp;</div>
        <div class="gridFullWidth">
		 <div class="block33">
                <!--------------- svg starts----------->
               <img src="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/new-design-images/ys_stores_address/ys-san-francisco.jpg"
                     alt="" class="img-responsive"/>
                <!--------------- svg ends----------->
            </div>
           
                        <div class="block33 white-line-seperator">
                <!--------------- svg starts----------->
                <svg viewBox="0 0 512 377">
                    <style type="text/css">
                        .st0 {
                            fill: #AE8637;
                        }

                        .st1 {
                            fill: none;
                            stroke: #FFFFFF;
                            stroke-width: 3.0808;
                            stroke-miterlimit: 10;
                        }

                        .st2 {
                            fill: #FFFFFF;
                        }

                        .st3 {
                            fill: none;
                            stroke: #FFFFFF;
                            stroke-width: 2.7808;
                            stroke-miterlimit: 10;
                        }
                    </style>
                    <g id="BG-color">
                        <rect class="st0" width="512" height="377"/>
                    </g>
                    <g id="Graphic">
                        <g>
                            <circle class="st1" cx="256" cy="188.5" r="129.5"/>
                            <circle class="st1" cx="256" cy="188.5" r="83.1"/>
                            <g>
                                <g>
                                    <path class="st2" d="M190.2,259.3c2,1.9,3.1,4.6,3,7.1l-2.6,0c0.1-1.7-0.7-3.8-2.2-5.2c-2.8-2.8-7.3-2.6-10.2,0.4
										c-3,3.1-2.8,7.5,0.1,10.3c1.9,1.8,4.2,2.1,5.9,1.9l0.2,2.6c-2.7,0.4-5.8-0.6-7.9-2.7c-4.2-4-4.3-10-0.3-14.2
										C180.1,255.6,186.2,255.4,190.2,259.3z"/>
                                    <path class="st2" d="M199.9,285l-6.9-4.4l-4.4,3.1l-2.4-1.6l17.2-12l1.6,1l-3.7,20.7l-2.4-1.6L199.9,285z M195.4,278.9l5,3.2
										l1.4-7.7L195.4,278.9z"/>
                                    <path class="st2"
                                          d="M210.8,293.1l7.9,3.3l-1,2.4l-10.5-4.4l7.5-17.9l2.6,1.1L210.8,293.1z"/>
                                    <path class="st2" d="M228.6,281.8l2.7,0.8l-5.3,18.7l-2.7-0.8L228.6,281.8z"/>
                                    <path class="st2"
                                          d="M244.6,292.9l-0.4,2.6l-6.3-1l-1.4,9l-2.7-0.4l2.9-19.2l11,1.7l-0.4,2.6l-8.2-1.3l-0.8,4.9L244.6,292.9z"/>
                                    <path class="st2" d="M258.8,285.4c5.5-0.2,9.8,4,10,9.7c0.2,5.7-3.9,10.1-9.4,10.3c-5.5,0.2-9.8-4-10-9.7
										C249.2,290,253.3,285.6,258.8,285.4z M259.3,302.8c4-0.1,6.8-3.3,6.7-7.5c-0.1-4.2-3.2-7.3-7.1-7.1c-4,0.1-6.8,3.4-6.7,7.5
										C252.3,299.8,255.3,302.9,259.3,302.8z"/>
                                    <path class="st2" d="M277.3,293.9l2.1,8.9l-2.7,0.6l-4.5-18.9l6.6-1.6c1.7-0.4,2.9-0.3,3.9,0.2c1.4,0.6,2.4,1.9,2.8,3.4
										c0.4,1.6,0,3.1-0.9,4.3c-0.5,0.6-1.1,1.1-2,1.5l8.9,7.4l-3.3,0.8l-8.8-7.3L277.3,293.9z M280.5,290.5c1.2-0.3,1.8-0.7,2.1-1.2
										c0.3-0.5,0.5-1.2,0.3-1.9c-0.2-0.7-0.6-1.2-1.1-1.6c-0.5-0.3-1.2-0.4-2.4-0.2l-3.8,0.9l1.2,4.9L280.5,290.5z"/>
                                    <path class="st2" d="M294.3,283.6l6.1,12.9l-2.5,1.2l-8.3-17.5l1.8-0.8l16.6,7.9l-6.1-12.9l2.5-1.2l8.3,17.5l-1.8,0.8
										L294.3,283.6z"/>
                                    <path class="st2" d="M308.9,269.9l2.3-1.6l10.9,16l-2.3,1.6L308.9,269.9z"/>
                                    <path class="st2" d="M333.4,268.7l-6,5.5l1.9,5.1l-2.1,1.9l-7.1-19.8l1.4-1.3l19,8.9l-2.1,1.9L333.4,268.7z M326.4,271.5l4.4-4
										l-7.1-3.3L326.4,271.5z"/>
                                </g>
                                <g>
                                    <path class="st2"
                                          d="M198.8,107.9l6.9-4.8l1.5,2.1l-9.2,6.3l-10.8-15.7l2.2-1.5L198.8,107.9z"/>
                                    <path class="st2" d="M218.9,94.1l-7.3,3.3l0.2,5.3l-2.6,1.2l-0.5-20.6l1.7-0.8l15,14.2l-2.6,1.2L218.9,94.1z M211.5,94.6
										l5.4-2.4l-5.6-5.3L211.5,94.6z"/>
                                    <path class="st2" d="M237.2,89.9c0.6,0.9,1.6,1.3,2.7,1.1c0.8-0.1,1.6-0.7,2-1.4c0.3-0.5,0.4-1.1,0.2-2.2l-2-13.4l2.7-0.4
										l2,13.2c0.2,1.5,0.2,2.5-0.2,3.3c-0.7,1.8-2.3,3.1-4.3,3.4c-2.2,0.3-4.3-0.5-5.4-2.3L237.2,89.9z"/>
                                    <path class="st2" d="M259.9,72.8c5.4,0.2,9.4,4.6,9.2,10.1c-0.2,5.6-4.5,9.7-9.9,9.5c-5.4-0.2-9.4-4.6-9.2-10.1
										C250.2,76.7,254.5,72.6,259.9,72.8z M259.3,89.8c3.9,0.1,6.9-2.8,7-7c0.1-4.1-2.7-7.3-6.6-7.4c-3.9-0.1-6.9,2.9-7,7
										C252.6,86.5,255.5,89.7,259.3,89.8z"/>
                                    <path class="st2"
                                          d="M276.3,91.5l8.2,1.9l-0.6,2.5L273,93.4l4.3-18.6l2.7,0.6L276.3,91.5z"/>
                                    <path class="st2"
                                          d="M290.8,95.8l7.8,3.2l-1,2.4l-10.4-4.2l7.1-17.7l2.5,1L290.8,95.8z"/>
                                    <path class="st2" d="M313.4,105.1l-6.8-4.3l-4.3,3.1l-2.4-1.5l16.9-11.8l1.6,1l-3.6,20.3l-2.4-1.5L313.4,105.1z M308.9,99.1
										l5,3.2l1.3-7.6L308.9,99.1z"/>
                                </g>
                                <g>
                                    <path class="st2"
                                          d="M210.9,169.6h-10.6v9h-2.7v-19.1h2.7v7.5h10.6v-7.5h2.7v19.1h-2.7V169.6z"/>
                                    <path class="st2" d="M227.4,159.2c5.4,0,9.5,4.2,9.5,9.8c0,5.6-4.1,9.8-9.5,9.8s-9.5-4.2-9.5-9.8
										C217.9,163.5,222,159.2,227.4,159.2z M227.4,176.3c3.9,0,6.8-3.1,6.8-7.2c0-4.1-2.9-7.2-6.8-7.2s-6.8,3.1-6.8,7.2
										C220.6,173.2,223.5,176.3,227.4,176.3z"/>
                                    <path class="st2" d="M243.9,176h8.4v2.6h-11.2v-19.1h2.7V176z"/>
                                    <path class="st2" d="M257.2,159.5h2.7v19.1h-2.7V159.5z"/>
                                    <path class="st2" d="M265.6,178.6v-19.1h5.7c3,0,5,0.7,6.5,1.8c2.3,1.7,3.8,4.6,3.8,7.7c0,3.2-1.4,6-3.8,7.7
										c-1.6,1.1-3.5,1.8-6.6,1.8H265.6z M276.7,163.7c-1.2-1-2.8-1.6-5.4-1.6h-2.9V176h2.9c2.7,0,4.2-0.6,5.4-1.6
										c1.4-1.3,2.3-3.2,2.3-5.3C279,166.9,278.1,165,276.7,163.7z"/>
                                    <path class="st2" d="M296.4,173.7h-8l-2,4.9h-2.8l7.9-19.1h1.9l7.9,19.1h-2.8L296.4,173.7z M289.5,171.1h5.9l-2.9-7.1
										L289.5,171.1z"/>
                                    <path class="st2"
                                          d="M309.7,169.9v8.7H307v-8.7l-6.5-10.4h3.1l4.8,7.7l4.8-7.7h3.1L309.7,169.9z"/>
                                    <path class="st2" d="M207.6,199.1c1-4.5,4.7-8,9.8-8c5.9,0,10,4.2,10,9.9c0,3.1-1.2,5.7-4.1,9.2L212,223.7h15.9v2.8h-20.5v-1.8
										l13.4-16.1c2.9-3.4,3.6-5.5,3.6-7.6c0-4.1-2.9-7.1-6.9-7.1c-3.8,0-6.3,2.5-7.2,6.1L207.6,199.1z"/>
                                    <path class="st2" d="M245.8,191.1c8.6,0,11.8,7.7,11.8,18s-3.1,18-11.8,18s-11.8-7.7-11.8-18S237.2,191.1,245.8,191.1z
										 M245.8,224.2c6.5,0,8.8-6.5,8.8-15.2s-2.2-15.2-8.8-15.2c-6.5,0-8.8,6.5-8.8,15.2S239.3,224.2,245.8,224.2z"/>
                                    <path class="st2" d="M263.1,196.3l7.8-4.7h2v35h-3v-31.1l-6.8,3.8V196.3z"/>
                                    <path class="st2" d="M301.9,191.6v2.9h-14l-1.5,10.3c1.5-0.7,3.1-1.1,4.9-1.1c6.7,0,11.8,5.2,11.8,11.8
										c0,6.5-5.1,11.8-11.7,11.8c-4.1,0-7.8-2-9.9-5.2l2.4-1.6c1.6,2.3,4.3,3.9,7.5,3.9c5.1,0,8.7-4.1,8.7-8.9c0-4.9-3.9-8.9-8.9-8.9
										c-2.4,0-4.6,1-6.2,2.5l-2-0.3l2.4-17H301.9z"/>
                                </g>
                            </g>
                        </g>
                    </g>
                </svg>
                <!--------------- svg ends----------->
            </div>
			
            <div class="block33">
                <!--------------- svg starts----------->
                <svg viewBox="0 0 512 377">
                    <style type="text/css">
                        .st0 {
                            fill: #AE8637;
                        }

                        .st1 {
                            fill: none;
                            stroke: #FFFFFF;
                            stroke-width: 3.0808;
                            stroke-miterlimit: 10;
                        }

                        .st2 {
                            fill: #FFFFFF;
                        }

                        .st3 {
                            fill: none;
                            stroke: #FFFFFF;
                            stroke-width: 2.7808;
                            stroke-miterlimit: 10;
                        }
                    </style>
                    <g id="BG-color">
                        <rect class="st0" width="512" height="377"/>
                    </g>
                    <g id="Graphic">
                        <g>
                            <circle class="st1" cx="256" cy="188.5" r="129.5"/>
                            <circle class="st1" cx="256" cy="188.5" r="83.1"/>
                            <g>
                                <g>
                                    <path class="st2" d="M190.2,259.3c2,1.9,3.1,4.6,3,7.1l-2.6,0c0.1-1.7-0.7-3.8-2.2-5.2c-2.8-2.8-7.3-2.6-10.2,0.4
											c-3,3.1-2.8,7.5,0.1,10.3c1.9,1.8,4.2,2.1,5.9,1.9l0.2,2.6c-2.7,0.4-5.8-0.6-7.9-2.7c-4.2-4-4.3-10-0.3-14.2
											C180.1,255.6,186.2,255.4,190.2,259.3z"/>
                                    <path class="st2" d="M199.9,285l-6.9-4.4l-4.4,3.1l-2.4-1.6l17.2-12l1.6,1l-3.7,20.7l-2.4-1.6L199.9,285z M195.4,278.9l5,3.2
											l1.4-7.7L195.4,278.9z"/>
                                    <path class="st2"
                                          d="M210.8,293.1l7.9,3.3l-1,2.4l-10.5-4.4l7.5-17.9l2.6,1.1L210.8,293.1z"/>
                                    <path class="st2" d="M228.6,281.8l2.7,0.8l-5.3,18.7l-2.7-0.8L228.6,281.8z"/>
                                    <path class="st2"
                                          d="M244.6,292.9l-0.4,2.6l-6.3-1l-1.4,9l-2.7-0.4l2.9-19.2l11,1.7l-0.4,2.6l-8.2-1.3l-0.8,4.9L244.6,292.9z"/>
                                    <path class="st2" d="M258.8,285.4c5.5-0.2,9.8,4,10,9.7c0.2,5.7-3.9,10.1-9.4,10.3s-9.8-4-10-9.7
											C249.2,290,253.3,285.6,258.8,285.4z M259.3,302.8c4-0.1,6.8-3.3,6.7-7.5c-0.1-4.2-3.2-7.3-7.1-7.1c-4,0.1-6.8,3.4-6.7,7.5
											C252.3,299.8,255.3,302.9,259.3,302.8z"/>
                                    <path class="st2" d="M277.3,293.9l2.1,8.9l-2.7,0.6l-4.5-18.9l6.6-1.6c1.7-0.4,2.9-0.3,3.9,0.2c1.4,0.6,2.4,1.9,2.8,3.4
											c0.4,1.6,0,3.1-0.9,4.3c-0.5,0.6-1.1,1.1-2,1.5l8.9,7.4l-3.3,0.8l-8.8-7.3L277.3,293.9z M280.5,290.5c1.2-0.3,1.8-0.7,2.1-1.2
											c0.3-0.5,0.4-1.2,0.3-1.9c-0.2-0.7-0.6-1.2-1.1-1.6s-1.2-0.4-2.4-0.2l-3.8,0.9l1.2,4.9L280.5,290.5z"/>
                                    <path class="st2" d="M294.3,283.6l6.1,12.9l-2.5,1.2l-8.3-17.5l1.8-0.8l16.6,7.9l-6.1-12.9l2.5-1.2l8.3,17.5l-1.8,0.8
											L294.3,283.6z"/>
                                    <path class="st2" d="M308.9,269.9l2.3-1.6l10.9,16l-2.3,1.6L308.9,269.9z"/>
                                    <path class="st2" d="M333.4,268.7l-6,5.5l1.9,5.1l-2.1,1.9l-7.1-19.8l1.4-1.3l19,8.9l-2.1,1.9L333.4,268.7z M326.4,271.5l4.4-4
											l-7.1-3.3L326.4,271.5z"/>
                                </g>
                                <g>
                                    <path class="st2" d="M158.4,127c1.4-2.3,3.7-4,6.1-4.4l0.6,2.5c-1.6,0.3-3.5,1.5-4.5,3.3c-2,3.3-0.9,7.5,2.6,9.7
											c3.7,2.2,7.8,1.1,9.9-2.4c1.3-2.2,1.1-4.5,0.5-6.1l2.5-0.7c0.9,2.5,0.7,5.7-0.8,8.2c-3,4.9-8.7,6.3-13.5,3.4
											C157.1,137.5,155.5,131.7,158.4,127z"/>
                                    <path class="st2" d="M172.4,108.8c3.7-3.9,9.6-4,13.7-0.2s4.3,9.7,0.6,13.7c-3.7,3.9-9.6,4-13.7,0.2S168.7,112.8,172.4,108.8z
											 M184.8,120.5c2.7-2.8,2.4-7.1-0.6-9.9c-3-2.8-7.3-2.8-9.9,0c-2.7,2.8-2.4,7.1,0.6,9.9C177.9,123.3,182.1,123.3,184.8,120.5z"/>
                                    <path class="st2" d="M193.6,103.7l5.1,7.4l-2.2,1.6L185.6,97l5.5-3.8c1.4-1,2.6-1.3,3.7-1.2c1.5,0.1,2.9,0.9,3.8,2.1
											s1.1,2.9,0.7,4.3c-0.2,0.7-0.6,1.4-1.3,2.1l10.8,3.6l-2.7,1.9l-10.7-3.5L193.6,103.7z M195.2,99.4c1-0.7,1.4-1.3,1.5-1.9
											s0-1.3-0.4-1.8s-1-0.9-1.6-1s-1.3,0-2.3,0.7l-3.1,2.2l2.8,4L195.2,99.4z"/>
                                    <path class="st2"
                                          d="M201.4,86.6l11.8-5.6l1.1,2.3l-4.7,2.2l7,14.9l-2.5,1.2l-7-14.9l-4.7,2.2L201.4,86.6z"/>
                                    <path class="st2" d="M230.1,83.5l0.7,2.5l-6,1.7l1.8,6.1l8.1-2.3l0.7,2.5l-10.7,3.1l-5.3-18.3l10.5-3l0.7,2.5l-7.9,2.3l1.4,4.7
											L230.1,83.5z"/>
                                    <path class="st2" d="M259.2,88l-1.9,0l-5.4-8.9l-0.3,12.8l-2.7-0.1l0.4-19.1l1.9,0l7.1,11.8l7.6-11.5l1.9,0l-0.4,19.1l-2.7-0.1
											l0.3-12.8L259.2,88z"/>
                                    <path class="st2" d="M284.3,91.1l-7.8-1.9l-3.1,4.3l-2.7-0.7l12.3-16.6l1.9,0.5l3,20.4l-2.7-0.7L284.3,91.1z M278.1,86.9
											l5.7,1.4l-1.1-7.6L278.1,86.9z"/>
                                    <path class="st2" d="M290.8,98.3l8.3-17.2l5.2,2.5c2.7,1.3,4.2,2.8,5.1,4.5c1.4,2.6,1.5,5.8,0.1,8.6s-3.9,4.8-6.8,5.3
											c-1.9,0.4-4,0.1-6.7-1.2L290.8,98.3z M307.2,89.7c-0.6-1.5-1.8-2.7-4.2-3.8l-2.6-1.2l-6,12.5l2.6,1.2c2.4,1.2,4.1,1.3,5.6,0.9
											c1.9-0.5,3.5-1.9,4.4-3.8C307.9,93.6,307.9,91.4,307.2,89.7z"/>
                                    <path class="st2" d="M322.9,103.8l-1.5,2.1l-5-3.7l-3.8,5.1l6.8,5l-1.5,2.1l-9-6.6l11.3-15.3l8.8,6.5l-1.5,2.1l-6.6-4.9
											l-2.9,3.9L322.9,103.8z"/>
                                    <path class="st2" d="M329.2,112.9l-6.5,6.2l-1.9-2l13.8-13.2l4.6,4.8c1.2,1.3,1.7,2.3,1.7,3.5c0.1,1.5-0.4,3-1.5,4.1
											s-2.7,1.5-4.1,1.3c-0.8-0.1-1.5-0.3-2.3-0.9l-1.9,11.2l-2.3-2.4l1.8-11.1L329.2,112.9z M333.7,113.8c0.8,0.9,1.5,1.2,2.1,1.2
											s1.3-0.2,1.8-0.7c0.5-0.5,0.8-1.1,0.8-1.7s-0.2-1.3-1.1-2.1l-2.6-2.8l-3.5,3.4L333.7,113.8z"/>
                                    <path class="st2" d="M343.4,137.9l-4.3-6.8l-5.2,0.9l-1.5-2.4l20.4-3.4l1,1.6l-12,16.8l-1.5-2.4L343.4,137.9z M341.9,130.6
											l3.1,5l4.5-6.2L341.9,130.6z"/>
                                </g>
                                <g>
                                    <path class="st2"
                                          d="M210.9,169.6h-10.6v9h-2.7v-19.1h2.7v7.5h10.6v-7.5h2.7v19.1h-2.7V169.6z"/>
                                    <path class="st2" d="M227.4,159.2c5.4,0,9.5,4.2,9.5,9.8c0,5.6-4.1,9.8-9.5,9.8c-5.4,0-9.5-4.2-9.5-9.8
											C217.9,163.5,222,159.2,227.4,159.2z M227.4,176.3c3.9,0,6.8-3.1,6.8-7.2c0-4.1-2.9-7.2-6.8-7.2c-3.9,0-6.8,3.1-6.8,7.2
											C220.6,173.2,223.5,176.3,227.4,176.3z"/>
                                    <path class="st2" d="M243.9,176h8.4v2.6h-11.2v-19.1h2.7V176z"/>
                                    <path class="st2" d="M257.2,159.5h2.7v19.1h-2.7V159.5z"/>
                                    <path class="st2" d="M265.6,178.6v-19.1h5.7c3,0,5,0.7,6.5,1.8c2.3,1.7,3.8,4.6,3.8,7.7c0,3.2-1.4,6-3.8,7.7
											c-1.6,1.1-3.5,1.8-6.6,1.8H265.6z M276.7,163.7c-1.2-1-2.8-1.6-5.4-1.6h-2.9V176h2.9c2.7,0,4.2-0.6,5.4-1.6
											c1.4-1.3,2.3-3.2,2.3-5.3C279,166.9,278.1,165,276.7,163.7z"/>
                                    <path class="st2" d="M296.4,173.7h-8l-2,4.9h-2.8l7.9-19.1h1.9l7.9,19.1h-2.8L296.4,173.7z M289.5,171.1h5.9l-2.9-7.1
											L289.5,171.1z"/>
                                    <path class="st2"
                                          d="M309.7,169.9v8.7H307v-8.7l-6.5-10.4h3.1l4.8,7.7l4.8-7.7h3.1L309.7,169.9z"/>
                                    <path class="st2" d="M207.6,199.1c1-4.5,4.7-8,9.8-8c5.9,0,10,4.2,10,9.9c0,3.1-1.2,5.7-4.1,9.2L212,223.7h15.9v2.8h-20.5v-1.8
											l13.4-16.1c2.9-3.4,3.6-5.5,3.6-7.6c0-4.1-2.9-7.1-6.9-7.1c-3.8,0-6.3,2.5-7.2,6.1L207.6,199.1z"/>
                                    <path class="st2" d="M245.8,191.1c8.6,0,11.8,7.7,11.8,18s-3.1,18-11.8,18s-11.8-7.7-11.8-18S237.2,191.1,245.8,191.1z
											 M245.8,224.2c6.5,0,8.8-6.5,8.8-15.2s-2.2-15.2-8.8-15.2s-8.8,6.5-8.8,15.2S239.3,224.2,245.8,224.2z"/>
                                    <path class="st2" d="M263.1,196.3l7.8-4.7h2v35h-3v-31.1l-6.8,3.8V196.3z"/>
                                    <path class="st2" d="M301.9,191.6v2.9h-14l-1.5,10.3c1.5-0.7,3.1-1.1,4.9-1.1c6.7,0,11.8,5.2,11.8,11.8
											c0,6.5-5.1,11.8-11.7,11.8c-4.1,0-7.8-2-9.9-5.2l2.4-1.6c1.6,2.3,4.3,3.9,7.5,3.9c5.1,0,8.7-4.1,8.7-8.9c0-4.9-3.9-8.9-8.9-8.9
											c-2.4,0-4.6,1-6.2,2.5l-2-0.3l2.4-17H301.9z"/>
                                </g>
                            </g>
                        </g>
                    </g>
                </svg>
                <!--------------- svg ends----------->
            </div>
        </div>
        <div class="gridFullWidth">
		 <div class="block33">
                <div class="cntntheading">
                    <div class="content-wrapper">
                        YOGASMOGA SAN FRANCISCO <br/><span>66 KEARNY ST<br/>SAN FRANCISCO, CA 94108<br/>888 990 YOGA (9642)   </span>
                    </div>


                </div>


            </div>
            

           <div class="block33">
                <div class="cntntheading">
                    <div class="content-wrapper">
                        YOGASMOGA LA JOLLA <br/><span> 7863 GIRARD AVE<br/>LA JOLLA, CA 92037<br/>888 990 YOGA (9642)
								  </span>
                    </div>


                </div>


            </div>
            <div class="block33">
                <div class="cntntheading">
                    <div class="content-wrapper">
                        YOGASMOGA <span style="display:inline;">X</span> THE VILLAGE<br/><span style="display:inline;"> AT </span>CORTE
                        MADERA
						<span>1618 REDWOOD HWY<br/>CORTE MADERA, CA 94925<br/>888 990 YOGA (9642)
								<br/></span>
                    </div>

                </div>


            </div>
        </div>
        <div class="gridFullWidth">
		<div class="block33">
                <div class="contnttxt">
                    <span style="font-size:16px;font-family: AvantGardeGothicITCW01X;text-transform:lowercase">sanfran.unionsquare@yogasmoga.com</span>

                    <p style="text-align:center">
                        <span style="font-weight:bold">Store Hours</span><br/>Monday–Saturday 10am–8pm<br/>
                        Sunday 11am–7pm
                    </p>
						<p style="margin: 0;line-height: 15px;">&nbsp;</p>
                    <p style="font-family:gothambook;">Our expansive and luxurious retail space is now open in the Financial District of San Francisco, on Kearny St. Our San Francisco fans reached out to us so we answered them with open hearts.</p>

                </div>


            </div>
           

            <div class="block33">
                <div class="contnttxt">
                    <span style="font-size:16px;font-family: AvantGardeGothicITCW01X;text-transform:lowercase">lajolla@yogasmoga.com</span>

                    <p style="text-align:center">
                        <span style="font-weight:bold">Store Hours</span><br/>Monday–Saturday 10am–7pm<br/>
                        Sunday 10am–6pm
                    </p>
					<p style="margin: 0;line-height: 15px;">&nbsp;</p>
                    <p style="font-family:gothambook;">YOGASMOGA is now open in the jewel of Southern California, La Jolla. With vacation sunshine all year-round, you will find yourself immersed in luxurious retail while taking in the rays.</p>

                </div>


            </div>

            <div class="block33">
                <div class="contnttxt">
                    <span style="font-size:16px;font-family: AvantGardeGothicITCW01X;text-transform:lowercase">cortemadera@yogasmoga.com</span>

                    <p style="text-align:center">
                        <span style="font-weight:bold">Store Hours</span><br/>Monday–Friday 10am–8pm<br/>
                        Saturday 10am–7pm<br/>Sunday 11am-6pm
                    </p>

                    <p style="font-family:gothambook;">The Village at Corte Madera is an open-air shopping center
                        located in Corte Madera, CA,
                        including premuim shops, restaurants and many more. Breathe the open air while you walk through
                        The Village's breezy layout and explore our premium collection of yoga inspired athletic
                        apparel.</p>

                </div>


            </div>
        </div>
        <div style="border-bottom:1px solid #fff!important;" class="bottomdivider">&nbsp;</div>

        <div class="gridFullWidth">
		 <div class="block33">
                <!--------------- svg starts----------->
                <svg viewBox="0 0 512 377">
                    <style type="text/css">
                        .st0 {
                            fill: #AE8637;
                        }

                        .st1 {
                            fill: none;
                            stroke: #FFFFFF;
                            stroke-width: 3.0808;
                            stroke-miterlimit: 10;
                        }

                        .st2 {
                            fill: #FFFFFF;
                        }

                        .st3 {
                            fill: none;
                            stroke: #FFFFFF;
                            stroke-width: 2.7808;
                            stroke-miterlimit: 10;
                        }
                    </style>
                    <g id="BG-color">
                        <rect class="st0" width="512" height="377"/>
                    </g>
                    <g id="Graphic">
                        <g>
                            <circle class="st1" cx="256" cy="188.5" r="129.5"/>
                            <circle class="st1" cx="256" cy="188.5" r="83.1"/>
                            <g>
                                <g>
                                    <path class="st2" d="M189.1,265.9l-8.8,11.2l-2.2-1.7l12-15.2l1.5,1.2l0.3,18.4l8.8-11.2l2.2,1.7l-12,15.2l-1.5-1.2L189.1,265.9
											z"/>
                                    <path class="st2" d="M212.2,283.8l-1.2,2.3l-5.7-2.9l-3,5.8l7.6,3.9l-1.2,2.3l-10.1-5.2l8.9-17.2l9.9,5.1l-1.2,2.3l-7.4-3.8
											l-2.3,4.4L212.2,283.8z"/>
                                    <path class="st2" d="M222.1,300.2l-1.9-0.5l-1-20.3l2.7,0.7l0.7,14.7l8.1-12.4l1.9,0.5l1,14.8l7.8-12.5l2.7,0.7l-10.8,17.2
											l-1.9-0.5l-1.1-15.1L222.1,300.2z"/>
                                    <path class="st2"
                                          d="M264.3,296l0.6,8.9l-2.8,0.2l-0.6-8.9l-7.3-10.1l3.1-0.2l5.4,7.5l4.4-8.1l3.1-0.2L264.3,296z"/>
                                    <path class="st2" d="M279.9,282.5c5.3-1.4,10.5,1.8,11.9,7.3c1.4,5.5-1.6,10.7-6.9,12.1s-10.5-1.8-11.9-7.3
											C271.6,289.1,274.6,283.8,279.9,282.5z M284.2,299.3c3.8-1,5.9-4.8,4.9-8.8c-1-4.1-4.7-6.4-8.5-5.4c-3.8,1-5.9,4.8-4.9,8.8
											C276.7,298,280.4,300.2,284.2,299.3z"/>
                                    <path class="st2" d="M299.9,286.6l4.1,8.2l-2.5,1.2l-8.6-17.4l6.1-3c1.6-0.8,2.8-0.9,3.9-0.7c1.5,0.3,2.8,1.3,3.5,2.7
											c0.7,1.4,0.7,3.1,0.1,4.4c-0.3,0.7-0.8,1.3-1.6,1.9l10.3,5.2l-3,1.5l-10.2-5.1L299.9,286.6z M302.2,282.6
											c1.1-0.6,1.6-1.1,1.8-1.7c0.2-0.6,0.2-1.3-0.1-1.9c-0.3-0.6-0.8-1.1-1.4-1.3c-0.6-0.2-1.3-0.2-2.4,0.4l-3.5,1.7l2.2,4.5
											L302.2,282.6z"/>
                                    <path class="st2" d="M308.8,270.2l2.2-1.7l4.9,6.5l1.4-11.3l2.9-2.2l-1.5,12.5l13.7,2.7l-2.8,2.1l-12.8-2.5l5.9,7.7l-2.2,1.7
											L308.8,270.2z"/>
                                </g>
                                <g>
                                    <path class="st2" d="M179.7,129.9l-1.2,1.5l-18.5-7.6l1.8-2.1l13.3,5.6l-7.6-12.4l1.2-1.5l13.6,5.3l-7.8-12.1l1.8-2.1l10.8,16.8
											l-1.2,1.5l-13.9-5.4L179.7,129.9z"/>
                                    <path class="st2" d="M193.9,100.2l1.6,2l-5,3.8l3.9,5.1l6.7-5.2l1.6,2l-8.8,6.8l-11.6-15.1l8.6-6.7l1.6,2l-6.5,5l3,3.9
											L193.9,100.2z"/>
                                    <path class="st2" d="M204.7,101.3c1.6,0.7,3.5,0.9,5.3,0c1.6-0.8,2.4-2.6,1.6-4.1c-1.4-2.6-5.1-1-8.1-1.2
											c-1.6-0.1-3.2-0.8-4.1-2.6c-1.3-2.4-0.2-5.6,2.7-7.2c2.1-1.1,4.1-1,5.4-0.7l-0.5,2.5c-1.3-0.3-2.6-0.1-3.6,0.5
											c-1.4,0.7-2.4,2.3-1.6,3.8c1.1,2.1,5,0.7,7.9,1c1.5,0.1,3.2,0.7,4.2,2.7c1.6,3,0.3,6.1-2.6,7.7c-2.3,1.2-4.9,1.3-7.4,0.3
											L204.7,101.3z"/>
                                    <path class="st2"
                                          d="M212.4,81.4l12.4-4.3l0.8,2.4l-4.9,1.7l5.4,15.6l-2.6,0.9l-5.4-15.6l-4.9,1.7L212.4,81.4z"/>
                                    <path class="st2" d="M239,74c2.7-0.4,5.4,0.3,7.4,1.8l-1.5,2.1c-1.3-1-3.4-1.6-5.4-1.3c-3.8,0.6-6.3,4.2-5.7,8.2
											c0.7,4.3,4.2,6.6,8.2,6c2.5-0.4,4.1-2.1,5-3.5l2.2,1.4c-1.3,2.3-3.9,4.2-6.8,4.7c-5.6,0.9-10.4-2.6-11.3-8.1
											C230.1,79.7,233.5,74.8,239,74z"/>
                                    <path class="st2" d="M266.8,83.5l-10.6-0.5l-0.5,9l-2.7-0.1l1-19l2.7,0.1l-0.4,7.5l10.6,0.5l0.4-7.5l2.7,0.1l-1,19l-2.7-0.1
											L266.8,83.5z"/>
                                    <path class="st2" d="M286.1,84.7l-0.6,2.5l-6.1-1.5l-1.6,6.2l8.2,2.1l-0.6,2.5l-10.8-2.7l4.6-18.5l10.6,2.6l-0.6,2.5l-7.9-2
											l-1.2,4.8L286.1,84.7z"/>
                                    <path class="st2" d="M291.9,93.8c0.5,1.7,1.5,3.3,3.3,4.1c1.6,0.7,3.5,0.3,4.2-1.3c1.2-2.7-2.4-4.6-4.1-7.1
											c-0.9-1.4-1.3-3-0.5-4.8c1.1-2.5,4.3-3.7,7.3-2.3c2.2,1,3.3,2.6,3.9,3.8l-2.3,1.2c-0.6-1.2-1.5-2.1-2.6-2.6
											c-1.4-0.6-3.3-0.4-3.9,1.1c-1,2.2,2.5,4.3,4.1,6.8c0.8,1.3,1.4,3,0.5,5c-1.3,3.1-4.6,4-7.6,2.7c-2.4-1-4.1-3-4.8-5.6L291.9,93.8
											z"/>
                                    <path class="st2"
                                          d="M312.3,87.5l11,7.1l-1.4,2.2l-4.4-2.8l-8.9,13.9l-2.3-1.5l8.9-13.9l-4.4-2.8L312.3,87.5z"/>
                                    <path class="st2" d="M330.2,110.2l-1.7,1.9l-4.7-4.2l-4.3,4.8l6.3,5.6l-1.7,1.9l-8.3-7.4l12.7-14.2l8.1,7.2l-1.7,1.9l-6.1-5.4
											l-3.3,3.7L330.2,110.2z"/>
                                    <path class="st2" d="M335.6,119.8l-7,5.6l-1.7-2.1l14.9-11.9l4.2,5.2c1.1,1.4,1.4,2.5,1.4,3.6c0,1.5-0.7,2.9-1.9,3.9
											s-2.8,1.3-4.2,1c-0.8-0.2-1.5-0.5-2.2-1.1l-2.9,11l-2.1-2.6l2.8-10.9L335.6,119.8z M340,121.2c0.8,1,1.4,1.3,2,1.4
											c0.6,0.1,1.3-0.1,1.8-0.5s0.9-1,0.9-1.6c0.1-0.6-0.1-1.3-0.9-2.2l-2.4-3l-3.8,3.1L340,121.2z"/>
                                </g>
                                <g>
                                    <path class="st2"
                                          d="M210.9,169.6h-10.6v9h-2.7v-19.1h2.7v7.5h10.6v-7.5h2.7v19.1h-2.7V169.6z"/>
                                    <path class="st2" d="M227.4,159.2c5.4,0,9.5,4.2,9.5,9.8c0,5.6-4.1,9.8-9.5,9.8s-9.5-4.2-9.5-9.8
											C217.9,163.5,222,159.2,227.4,159.2z M227.4,176.3c3.9,0,6.8-3.1,6.8-7.2c0-4.1-2.9-7.2-6.8-7.2s-6.8,3.1-6.8,7.2
											C220.6,173.2,223.5,176.3,227.4,176.3z"/>
                                    <path class="st2" d="M243.9,176h8.4v2.6h-11.2v-19.1h2.7V176z"/>
                                    <path class="st2" d="M257.2,159.5h2.7v19.1h-2.7V159.5z"/>
                                    <path class="st2" d="M265.6,178.6v-19.1h5.7c3,0,5,0.7,6.5,1.8c2.3,1.7,3.8,4.6,3.8,7.7c0,3.2-1.4,6-3.8,7.7
											c-1.6,1.1-3.5,1.8-6.6,1.8H265.6z M276.7,163.7c-1.2-1-2.8-1.6-5.4-1.6h-2.9V176h2.9c2.7,0,4.2-0.6,5.4-1.6
											c1.4-1.3,2.3-3.2,2.3-5.3C279,166.9,278.1,165,276.7,163.7z"/>
                                    <path class="st2" d="M296.4,173.7h-8l-2,4.9h-2.8l7.9-19.1h1.9l7.9,19.1h-2.8L296.4,173.7z M289.5,171.1h5.9l-2.9-7.1
											L289.5,171.1z"/>
                                    <path class="st2"
                                          d="M309.7,169.9v8.7H307v-8.7l-6.5-10.4h3.1l4.8,7.7l4.8-7.7h3.1L309.7,169.9z"/>
                                    <path class="st2" d="M207.6,199.1c1-4.5,4.7-8,9.8-8c5.9,0,10,4.2,10,9.9c0,3.1-1.2,5.7-4.1,9.2L212,223.7h15.9v2.9h-20.5v-1.9
											l13.4-16.1c2.9-3.4,3.6-5.6,3.6-7.6c0-4.1-2.9-7.1-6.9-7.1c-3.8,0-6.3,2.5-7.2,6.1L207.6,199.1z"/>
                                    <path class="st2" d="M245.8,191.1c8.6,0,11.8,7.7,11.8,18s-3.1,18-11.8,18s-11.8-7.7-11.8-18S237.2,191.1,245.8,191.1z
											 M245.8,224.2c6.5,0,8.8-6.5,8.8-15.2s-2.2-15.2-8.8-15.2c-6.5,0-8.8,6.5-8.8,15.2S239.3,224.2,245.8,224.2z"/>
                                    <path class="st2" d="M263.1,196.3l7.8-4.7h2v35h-3v-31.1l-6.8,3.8V196.3z"/>
                                    <path class="st2" d="M301.9,191.6v2.9h-14l-1.5,10.3c1.5-0.7,3.1-1.1,4.9-1.1c6.7,0,11.8,5.3,11.8,11.8
											c0,6.5-5.1,11.8-11.7,11.8c-4.1,0-7.8-2.1-9.9-5.2l2.4-1.6c1.6,2.3,4.3,3.9,7.5,3.9c5.1,0,8.7-4.1,8.7-8.9
											c0-4.9-3.9-8.9-8.9-8.9c-2.4,0-4.6,1-6.2,2.5l-2-0.3l2.4-17H301.9z"/>
                                </g>
                            </g>
                        </g>
                    </g>
                </svg>
                <!--------------- svg ends----------->
            </div>
			
			            <div class="block33">
                <!--------------- svg starts----------->
                <svg viewBox="0 0 512 377">
                    <style type="text/css">
                        .st0 {
                            fill: #AE8637;
                        }

                        .st1 {
                            fill: none;
                            stroke: #FFFFFF;
                            stroke-width: 3.0808;
                            stroke-miterlimit: 10;
                        }

                        .st2 {
                            fill: #FFFFFF;
                        }

                        .st3 {
                            fill: none;
                            stroke: #FFFFFF;
                            stroke-width: 2.7808;
                            stroke-miterlimit: 10;
                        }
                    </style>
                    <g id="BG-color">
                        <rect class="st0" width="512" height="377"/>
                    </g>
                    <g id="Graphic">
                        <g>
                            <circle class="st1" cx="256" cy="188.5" r="129.5"/>
                            <circle class="st1" cx="256" cy="188.5" r="83.1"/>
                            <g>
                                <g>
                                    <path class="st2" d="M181.2,258.1l-10,10.2l-2-1.9l13.6-13.9l1.4,1.4l-1.7,18.3l10-10.2l2,1.9l-13.6,13.9l-1.4-1.4L181.2,258.1z
												"/>
                                    <path class="st2" d="M202.2,278.5l-1.5,2.2l-5.3-3.5l-3.6,5.4l7.2,4.8l-1.5,2.2l-9.5-6.3l10.7-16.2l9.2,6.1l-1.5,2.2l-6.9-4.6
												l-2.8,4.2L202.2,278.5z"/>
                                    <path class="st2" d="M210.2,295.9l-1.8-0.7l1.2-20.3l2.6,1l-1,14.7l9.4-11.4l1.8,0.7l-0.6,14.8l9.1-11.6l2.6,1L221.1,300
												l-1.8-0.7l0.6-15.1L210.2,295.9z"/>
                                    <path class="st2" d="M245.1,300.8c0.4,1,1.3,1.6,2.5,1.7c0.9,0.1,1.7-0.3,2.3-0.9c0.4-0.4,0.6-1,0.7-2.2l0.8-13.8l2.8,0.2
												l-0.8,13.6c-0.1,1.5-0.4,2.5-0.9,3.3c-1,1.6-2.9,2.6-5,2.5c-2.2-0.1-4.1-1.4-4.8-3.4L245.1,300.8z"/>
                                    <path class="st2" d="M269.2,292.6l0.2,2.6l-6.4,0.5l0.6,6.5l8.6-0.7l0.2,2.6l-11.3,1l-1.7-19.3l11-1l0.2,2.6l-8.3,0.7l0.4,5
												L269.2,292.6z"/>
                                    <path class="st2" d="M279.7,293.4l2.3,8.8l-2.7,0.7l-4.9-18.8l6.6-1.7c1.7-0.5,2.9-0.3,3.9,0.1c1.4,0.6,2.5,1.8,2.9,3.4
												c0.4,1.6,0.1,3.1-0.8,4.3c-0.5,0.6-1,1.2-1.9,1.6l9.1,7.2l-3.2,0.9l-9-7.1L279.7,293.4z M282.8,289.9c1.2-0.3,1.8-0.7,2.1-1.3
												s0.4-1.2,0.2-1.9c-0.2-0.7-0.6-1.2-1.1-1.5s-1.2-0.4-2.4-0.1l-3.8,1l1.3,4.8L282.8,289.9z"/>
                                    <path class="st2" d="M298.1,292.1c1.6,0.8,3.5,1.1,5.4,0.3c1.6-0.8,2.6-2.5,1.9-4.1c-1.2-2.7-5.1-1.3-8.2-1.7
												c-1.6-0.3-3.2-1-4-2.8c-1.2-2.6,0.1-5.7,3.2-7.1c2.2-1,4.3-0.8,5.5-0.4l-0.6,2.5c-1.3-0.4-2.6-0.3-3.7,0.2
												c-1.5,0.7-2.5,2.2-1.8,3.7c1,2.2,5,1,8,1.5c1.5,0.2,3.2,1,4.1,3c1.4,3.1,0,6.2-3.1,7.6c-2.4,1.1-5.1,1.1-7.5-0.1L298.1,292.1z"
                                        />
                                    <path class="st2" d="M317.2,273.5l1.5,2.2l-5.3,3.6l3.6,5.4l7.1-4.8l1.5,2.2l-9.4,6.3l-10.8-16.1l9.2-6.2l1.5,2.2l-6.9,4.6
												l2.8,4.1L317.2,273.5z"/>
                                    <path class="st2"
                                          d="M330.7,265.8l6.1,6.4l-2,1.9l-6.1-6.4l-12.1-3l2.2-2.1l9,2.2l-1.8-9l2.2-2.1L330.7,265.8z"/>
                                </g>
                                <g>
                                    <path class="st2" d="M177.6,124.9c1.8,0.1,3.6-0.4,4.9-1.9c1.2-1.3,1.3-3.3,0-4.4c-2.2-1.9-5.1,0.9-8,1.7
												c-1.6,0.4-3.3,0.4-4.8-0.9c-2.1-1.8-2.2-5.2,0-7.7c1.6-1.8,3.5-2.4,4.8-2.6l0.4,2.5c-1.3,0.2-2.4,0.8-3.2,1.7
												c-1,1.2-1.4,3-0.2,4.1c1.8,1.6,4.9-1.1,7.7-1.9c1.5-0.4,3.3-0.4,4.9,1c2.5,2.2,2.5,5.6,0.3,8.1c-1.7,2-4.1,3-6.8,2.9
												L177.6,124.9z"/>
                                    <path class="st2" d="M196.2,101.7l-8.4,6.5l5.5,7.1l-2.2,1.7l-11.7-15.1l2.2-1.7l4.6,5.9l8.4-6.5l-4.6-5.9l2.2-1.7l11.7,15.1
												l-2.2,1.7L196.2,101.7z"/>
                                    <path class="st2" d="M207.9,83.2c4.9-2.3,10.4-0.1,12.8,4.9c2.3,5,0.3,10.6-4.5,12.9s-10.4,0.1-12.8-4.9
												C201.1,91.1,203,85.5,207.9,83.2z M215.1,98.7c3.5-1.6,4.9-5.6,3.2-9.4c-1.7-3.7-5.7-5.3-9.2-3.7s-4.9,5.7-3.2,9.4
												C207.6,98.7,211.5,100.3,215.1,98.7z"/>
                                    <path class="st2" d="M229.5,86.4l2,8.8l-2.7,0.6l-4.2-18.6l6.5-1.5c1.7-0.4,2.9-0.2,3.9,0.3c1.3,0.7,2.3,1.9,2.7,3.4
												c0.3,1.5-0.1,3.1-1,4.2c-0.5,0.6-1.1,1.1-2,1.5l8.7,7.4l-3.2,0.7l-8.6-7.3L229.5,86.4z M232.7,83c1.2-0.3,1.7-0.7,2.1-1.2
												s0.5-1.2,0.3-1.9s-0.6-1.2-1.1-1.5s-1.2-0.5-2.4-0.2l-3.7,0.8l1.1,4.8L232.7,83z"/>
                                    <path class="st2"
                                          d="M243.2,73.5l13.1-0.7l0.1,2.6l-5.2,0.3l0.9,16.5l-2.7,0.1l-0.9-16.5l-5.2,0.3L243.2,73.5z"/>
                                    <path class="st2" d="M285.3,87.1L275,84.6l-2.1,8.7l-2.7-0.6l4.4-18.6l2.7,0.6l-1.7,7.3l10.3,2.4l1.7-7.3l2.7,0.6l-4.4,18.6
												l-2.7-0.6L285.3,87.1z"/>
                                    <path class="st2" d="M298.5,81.1l2.5,1l-7.3,17.6l-2.5-1L298.5,81.1z"/>
                                    <path class="st2"
                                          d="M302.7,101.2l7.3,4.2l-1.3,2.3l-9.7-5.5l9.4-16.6l2.4,1.3L302.7,101.2z"/>
                                    <path class="st2"
                                          d="M315.4,109.5l6.6,5.3l-1.6,2l-8.7-6.9l11.9-14.9l2.1,1.7L315.4,109.5z"/>
                                    <path class="st2" d="M327.3,116.9c-0.3,1.7,0,3.6,1.3,5.1c1.2,1.3,3.1,1.7,4.4,0.5c2.2-2-0.3-5.2-0.8-8.2
												c-0.2-1.6,0-3.3,1.5-4.6c2.1-1.9,5.4-1.6,7.6,0.9c1.6,1.8,2,3.8,2,5.1l-2.6,0.1c0-1.4-0.5-2.5-1.3-3.4c-1.1-1.2-2.8-1.7-4-0.6
												c-1.8,1.6,0.5,5,1,7.9c0.2,1.5,0,3.3-1.6,4.8c-2.5,2.2-5.8,1.8-8.1-0.7c-1.8-1.9-2.5-4.5-2.1-7.1L327.3,116.9z"/>
                                </g>
                                <g>
                                    <path class="st2"
                                          d="M210.9,169.6h-10.6v9h-2.7v-19.1h2.7v7.5h10.6v-7.5h2.7v19.1h-2.7V169.6z"/>
                                    <path class="st2" d="M227.4,159.2c5.4,0,9.5,4.2,9.5,9.8c0,5.6-4.1,9.8-9.5,9.8c-5.4,0-9.5-4.2-9.5-9.8
												C217.9,163.5,222,159.2,227.4,159.2z M227.4,176.3c3.9,0,6.8-3.1,6.8-7.2c0-4.1-2.9-7.2-6.8-7.2c-3.9,0-6.8,3.1-6.8,7.2
												C220.6,173.2,223.5,176.3,227.4,176.3z"/>
                                    <path class="st2" d="M243.9,176h8.4v2.6h-11.2v-19.1h2.7V176z"/>
                                    <path class="st2" d="M257.2,159.5h2.7v19.1h-2.7V159.5z"/>
                                    <path class="st2" d="M265.6,178.6v-19.1h5.7c3,0,5,0.7,6.5,1.8c2.3,1.7,3.8,4.6,3.8,7.7c0,3.2-1.4,6-3.8,7.7
												c-1.6,1.1-3.5,1.8-6.6,1.8H265.6z M276.7,163.7c-1.2-1-2.8-1.6-5.4-1.6h-2.9V176h2.9c2.7,0,4.2-0.6,5.4-1.6
												c1.4-1.3,2.3-3.2,2.3-5.3C279,166.9,278.1,165,276.7,163.7z"/>
                                    <path class="st2" d="M296.4,173.7h-8l-2,4.9h-2.8l7.9-19.1h1.9l7.9,19.1h-2.8L296.4,173.7z M289.5,171.1h5.9l-2.9-7.1
												L289.5,171.1z"/>
                                    <path class="st2"
                                          d="M309.7,169.9v8.7H307v-8.7l-6.5-10.4h3.1l4.8,7.7l4.8-7.7h3.1L309.7,169.9z"/>
                                    <path class="st2" d="M207.6,199.1c1-4.5,4.7-8,9.8-8c5.9,0,10,4.2,10,9.9c0,3.1-1.2,5.7-4.1,9.2L212,223.7h15.9v2.9h-20.5v-1.9
												l13.4-16.1c2.9-3.4,3.6-5.6,3.6-7.6c0-4.1-2.9-7.1-6.9-7.1c-3.8,0-6.3,2.5-7.2,6.1L207.6,199.1z"/>
                                    <path class="st2" d="M245.8,191.1c8.6,0,11.8,7.7,11.8,18s-3.1,18-11.8,18s-11.8-7.7-11.8-18S237.2,191.1,245.8,191.1z
												 M245.8,224.2c6.5,0,8.8-6.5,8.8-15.2s-2.2-15.2-8.8-15.2s-8.8,6.5-8.8,15.2S239.3,224.2,245.8,224.2z"/>
                                    <path class="st2" d="M263.1,196.3l7.8-4.7h2v35h-3v-31.1l-6.8,3.8V196.3z"/>
                                    <path class="st2" d="M301.9,191.6v2.9h-14l-1.5,10.3c1.5-0.7,3.1-1.1,4.9-1.1c6.7,0,11.8,5.3,11.8,11.8
												c0,6.5-5.1,11.8-11.7,11.8c-4.1,0-7.8-2.1-9.9-5.2l2.4-1.6c1.6,2.3,4.3,3.9,7.5,3.9c5.1,0,8.7-4.1,8.7-8.9
												c0-4.9-3.9-8.9-8.9-8.9c-2.4,0-4.6,1-6.2,2.5l-2-0.3l2.4-17H301.9z"/>
                                </g>
                            </g>
                        </g>
                    </g>
                </svg>
                <!--------------- svg ends----------->
            </div>
			 <div class="block33">
                <!--------------- svg start----------->
                <svg viewBox="0 0 512 377">
                    <style type="text/css">
                        .st0 {
                            fill: #AE8637;
                        }

                        .st1 {
                            fill: none;
                            stroke: #FFFFFF;
                            stroke-width: 3.0808;
                            stroke-miterlimit: 10;
                        }

                        .st2 {
                            fill: #FFFFFF;
                        }

                        .st3 {
                            fill: none;
                            stroke: #FFFFFF;
                            stroke-width: 2.7808;
                            stroke-miterlimit: 10;
                        }
                    </style>
                    <g id="BG-color">
                        <rect class="st0" width="512" height="377"/>
                    </g>
                    <g id="Graphic">
                        <g>
                            <circle class="st1" cx="256" cy="188.5" r="129.5"/>
                            <circle class="st1" cx="256" cy="188.5" r="83.1"/>
                            <g>
                                <g>
                                    <path class="st2" d="M190.2,259.3c2,1.9,3.1,4.6,3,7.1l-2.6,0c0.1-1.7-0.7-3.8-2.2-5.2c-2.8-2.8-7.3-2.6-10.2,0.4
										c-3,3.1-2.8,7.5,0.1,10.3c1.9,1.8,4.2,2.1,5.9,1.9l0.2,2.6c-2.7,0.4-5.8-0.6-7.9-2.7c-4.2-4-4.3-10-0.3-14.2
										C180.1,255.7,186.2,255.4,190.2,259.3z"/>
                                    <path class="st2" d="M199.9,285l-6.9-4.4l-4.4,3.1l-2.4-1.6l17.2-12l1.6,1l-3.7,20.7l-2.4-1.6L199.9,285z M195.4,278.9l5,3.2
										l1.4-7.7L195.4,278.9z"/>
                                    <path class="st2"
                                          d="M210.8,293.1l7.9,3.3l-1,2.4l-10.5-4.4l7.5-17.9l2.6,1.1L210.8,293.1z"/>
                                    <path class="st2" d="M228.6,281.8l2.7,0.8l-5.3,18.7l-2.7-0.8L228.6,281.8z"/>
                                    <path class="st2"
                                          d="M244.6,292.9l-0.4,2.6l-6.3-1l-1.4,9l-2.7-0.4l2.9-19.2l11,1.7l-0.4,2.6l-8.2-1.3l-0.8,4.9L244.6,292.9z"/>
                                    <path class="st2" d="M258.8,285.4c5.5-0.2,9.8,4,10,9.7c0.2,5.7-3.9,10.1-9.4,10.3s-9.8-4-10-9.7
										C249.2,290,253.3,285.6,258.8,285.4z M259.3,302.8c4-0.1,6.8-3.3,6.7-7.5c-0.1-4.2-3.2-7.3-7.1-7.1c-4,0.1-6.8,3.4-6.7,7.5
										C252.3,299.8,255.3,302.9,259.3,302.8z"/>
                                    <path class="st2" d="M277.3,293.9l2.1,8.9l-2.7,0.6l-4.5-18.9l6.6-1.6c1.7-0.4,2.9-0.3,3.9,0.2c1.4,0.6,2.4,1.9,2.8,3.4
										c0.4,1.6,0,3.1-0.9,4.3c-0.5,0.6-1.1,1.1-2,1.5l8.9,7.4l-3.3,0.8l-8.8-7.3L277.3,293.9z M280.5,290.5c1.2-0.3,1.8-0.7,2.1-1.2
										c0.3-0.5,0.4-1.2,0.3-1.9c-0.2-0.7-0.6-1.2-1.1-1.6s-1.2-0.4-2.4-0.2l-3.8,0.9l1.2,4.9L280.5,290.5z"/>
                                    <path class="st2" d="M294.3,283.6l6.1,12.9l-2.5,1.2l-8.3-17.5l1.8-0.8l16.6,7.9l-6.1-12.9l2.5-1.2l8.3,17.5l-1.8,0.8
										L294.3,283.6z"/>
                                    <path class="st2" d="M308.9,269.9l2.3-1.6l10.9,16l-2.3,1.6L308.9,269.9z"/>
                                    <path class="st2" d="M333.4,268.7l-6,5.5l1.9,5.1l-2.1,1.9l-7.1-19.8l1.4-1.3l19,8.9l-2.1,1.9L333.4,268.7z M326.4,271.5l4.4-4
										l-7.1-3.3L326.4,271.5z"/>
                                </g>
                                <g>
                                    <path class="st2" d="M174.2,138.1l-1.1,1.6l-19.2-5.7l1.6-2.3l13.8,4.2l-8.8-11.6l1.1-1.6l14.1,3.9l-9-11.3l1.6-2.3l12.4,15.6
										l-1.1,1.6l-14.4-4L174.2,138.1z"/>
                                    <path class="st2" d="M190.2,111.6l-5.9,5.5l1.9,4.9l-2.1,1.9l-7.3-19.3l1.4-1.3l18.8,8.5l-2.1,1.9L190.2,111.6z M183.3,114.5
										l4.3-4l-7-3.1L183.3,114.5z"/>
                                    <path class="st2"
                                          d="M200.8,106.4l7.1-4.6l1.4,2.2l-9.3,6.1l-10.4-16l2.3-1.5L200.8,106.4z"/>
                                    <path class="st2"
                                          d="M209.5,88.2l5.3,13l-2.5,1l-7.2-17.6l1.8-0.7l15.9,8.6l-5.3-13l2.5-1l7.2,17.6l-1.8,0.7L209.5,88.2z"/>
                                    <path class="st2" d="M233.9,92.2c-1.4-1.1-2.5-2.7-2.9-5.3l-1.9-11l2.7-0.5l1.9,11.2c0.3,1.8,0.9,2.8,1.8,3.5
										c1.1,0.9,2.6,1.3,4.2,1s2.9-1.1,3.6-2.3c0.6-1,0.9-2.1,0.6-3.9L242,73.7l2.7-0.5l1.9,11c0.4,2.5,0,4.4-1,5.9
										c-1.2,1.8-3.1,3.1-5.4,3.5S235.5,93.4,233.9,92.2z"/>
                                    <path class="st2"
                                          d="M251.5,72.9l13.1,0.2l0,2.6l-5.2-0.1l-0.3,16.5l-2.7,0l0.3-16.5l-5.2-0.1L251.5,72.9z"/>
                                    <path class="st2" d="M290.6,78c2.6,0.8,4.8,2.6,5.8,4.8l-2.3,1.2c-0.7-1.5-2.3-3-4.3-3.6c-3.7-1.1-7.5,1-8.7,4.9
										c-1.3,4.1,0.9,7.8,4.8,9c2.4,0.7,4.6-0.1,6-1l1.3,2.2c-2.2,1.5-5.3,2.1-8.1,1.2c-5.4-1.7-8.2-6.9-6.6-12.3
										C280.1,79.3,285.4,76.4,290.6,78z"/>
                                    <path class="st2" d="M302.1,93.7l-4.2,7.9l-2.4-1.3l9-16.8l5.9,3.1c1.5,0.8,2.3,1.7,2.7,2.7c0.6,1.4,0.6,3-0.2,4.3
										c-0.7,1.4-2.1,2.3-3.5,2.6c-0.8,0.2-1.5,0.1-2.4-0.2l1.7,11.2l-2.9-1.6L304,94.7L302.1,93.7z M306.6,93.2
										c1.1,0.6,1.8,0.6,2.4,0.5c0.6-0.2,1.1-0.6,1.4-1.2s0.4-1.3,0.2-1.9c-0.2-0.6-0.6-1.1-1.7-1.7l-3.4-1.8l-2.3,4.3L306.6,93.2z"/>
                                    <path class="st2" d="M325.4,105.9l-1.6,2l-4.9-3.9l-4,5l6.6,5.2l-1.6,2l-8.8-6.9l11.8-15l8.6,6.7l-1.6,2l-6.4-5.1l-3,3.9
										L325.4,105.9z"/>
                                    <path class="st2" d="M337.5,118l-1.9,1.8l-4.2-4.6l-4.7,4.3l5.7,6.2l-1.9,1.8l-7.6-8.2l14-12.9l7.4,8l-1.9,1.8l-5.5-6l-3.6,3.3
										L337.5,118z"/>
                                    <path class="st2" d="M349,120.4l1.5,2.3l-6.8,4.3l11,2.3l1.9,3l-12.1-2.5l-3.7,13.2l-1.9-2.9l3.4-12.3l-8,5.1l-1.5-2.3
										L349,120.4z"/>
                                </g>
                                <g>
                                    <path class="st2"
                                          d="M210.9,169.6h-10.6v9h-2.7v-19.1h2.7v7.5h10.6v-7.5h2.7v19.1h-2.7V169.6z"/>
                                    <path class="st2" d="M227.4,159.2c5.4,0,9.5,4.2,9.5,9.8c0,5.6-4.1,9.8-9.5,9.8c-5.4,0-9.5-4.2-9.5-9.8
										C217.9,163.5,222,159.2,227.4,159.2z M227.4,176.3c3.9,0,6.8-3.1,6.8-7.2c0-4.1-2.9-7.2-6.8-7.2c-3.9,0-6.8,3.1-6.8,7.2
										C220.6,173.2,223.5,176.3,227.4,176.3z"/>
                                    <path class="st2" d="M243.9,176h8.4v2.6h-11.2v-19.1h2.7V176z"/>
                                    <path class="st2" d="M257.2,159.5h2.7v19.1h-2.7V159.5z"/>
                                    <path class="st2" d="M265.6,178.6v-19.1h5.7c3,0,5,0.7,6.5,1.8c2.3,1.7,3.8,4.6,3.8,7.7c0,3.2-1.4,6-3.8,7.7
										c-1.6,1.1-3.5,1.8-6.6,1.8H265.6z M276.7,163.7c-1.2-1-2.8-1.6-5.4-1.6h-2.9V176h2.9c2.7,0,4.2-0.6,5.4-1.6
										c1.4-1.3,2.3-3.2,2.3-5.3C279,166.9,278.1,165,276.7,163.7z"/>
                                    <path class="st2" d="M296.4,173.7h-8l-2,4.9h-2.8l7.9-19.1h1.9l7.9,19.1h-2.8L296.4,173.7z M289.5,171.1h5.9l-2.9-7.1
										L289.5,171.1z"/>
                                    <path class="st2"
                                          d="M309.7,169.9v8.7H307v-8.7l-6.5-10.3h3.1l4.8,7.7l4.8-7.7h3.1L309.7,169.9z"/>
                                    <path class="st2" d="M207.6,199.1c1-4.5,4.7-8,9.8-8c5.9,0,10,4.2,10,9.9c0,3.1-1.2,5.7-4.1,9.2L212,223.7h15.9v2.8h-20.5v-1.8
										l13.4-16.1c2.9-3.4,3.6-5.5,3.6-7.6c0-4.1-2.9-7.1-6.9-7.1c-3.8,0-6.3,2.5-7.2,6.1L207.6,199.1z"/>
                                    <path class="st2" d="M245.8,191.1c8.6,0,11.8,7.7,11.8,18s-3.1,18-11.8,18s-11.8-7.7-11.8-18S237.2,191.1,245.8,191.1z
										 M245.8,224.2c6.5,0,8.8-6.5,8.8-15.2s-2.2-15.2-8.8-15.2s-8.8,6.5-8.8,15.2S239.3,224.2,245.8,224.2z"/>
                                    <path class="st2" d="M263.1,196.3l7.8-4.7h2v35h-3v-31.1l-6.8,3.8V196.3z"/>
                                    <path class="st2" d="M301.9,191.6v2.9h-14l-1.5,10.3c1.5-0.7,3.1-1.1,4.9-1.1c6.7,0,11.8,5.2,11.8,11.8
										c0,6.5-5.1,11.8-11.7,11.8c-4.1,0-7.8-2-9.9-5.2l2.4-1.6c1.6,2.3,4.3,3.9,7.5,3.9c5.1,0,8.7-4.1,8.7-8.9c0-4.9-3.9-8.9-8.9-8.9
										c-2.4,0-4.6,1-6.2,2.5l-2-0.3l2.4-17H301.9z"/>
                                </g>
                            </g>
                        </g>
                    </g>
                </svg>

                <!--------------- svg ends----------->
            </div>
        </div>

        <div class="gridFullWidth">
		<div class="block33">
                <div class="cntntheading">
                    <div class="content-wrapper">
                        YOGASMOGA<br/> <span style="display:inline;">AT </span>THE WESTCHESTER<br/>
							<span>125 WESTCHESTER AVE<br/>WHITE PLAINS, NY 10601<br/>888 990 YOGA (9642) 
									</span>
                    </div>


                </div>


            </div>

              <div class="block33">
                <div class="cntntheading">
                    <div class="content-wrapper">
                        YOGASMOGA<span style="display:inline;"> X</span> The Mall<br/>
                        <span style="display:inline;">AT </span>Short Hills<br/>
								<span style="display:inline;">1200 MORRIS TPKE<br/>
										SHORT HILLS, NJ 07078<br/> 888 990 YOGA (9642)</span></div>


                </div>


            </div>
			<div class="block33">
                <div class="cntntheading">
                    <div class="content-wrapper">
                        YOGASMOGA <span style="display:inline;">AT</span> WALNUT CREEK
                        <span>1275 BROADWAY PLAZA, #E04<br/>WALNUT CREEK, CA 94925<br/>888 990 YOGA (9642)</span>
                    </div>

                </div>
            </div>
        </div>
        <div class="gridFullWidth">
		 <div class="block33">
                <div class="contnttxt">
                    <span style="font-size:16px;font-family: AvantGardeGothicITCW01X;text-transform:lowercase">westchester@yogasmoga.com</span>

                    <p style="text-align:center">
                        <span style="font-weight:bold">Store Hours</span><br/>Monday–Saturday 10am–9pm<br/>
                        Sunday 11am–7pm<br/>&nbsp;
                    </p>

                    <p style="font-family:gothambook;">YOGASMOGA is coming soon to The Westchester Mall in White Plains, NY. We are bringing vivacity and balance to the ultimate shopping experience in Westchester County, New York.</p>

                </div>


            </div>
           <div class="block33">
                <div class="contnttxt">
                    <span style="font-size:16px;font-family: AvantGardeGothicITCW01X;text-transform:lowercase">shorthills@yogasmoga.com	</span>

                    <p style="text-align:center">
                        <span style="font-weight:bold">Store Hours</span><br/>Monday–Saturday 10am–9pm<br/>
                        Sunday 11am–6pm
                    </p>

                    <p style="margin: 0;line-height:15px;">&nbsp;</p>

                    <p style="font-family:gothambook;">YOGASMOGA is coming soon to The Mall at Short Hills located in
                        Short Hills, NJ.
                        Experience yoga inspired premium athletic apparel along with New Jersey's
                        most extraordinary collection of quality retail in one beautiful location.</p>

                </div>


            </div>

             <div class="block33">
                <div class="contnttxt">
                    <span style="font-size:16px;font-family: AvantGardeGothicITCW01X;text-transform:lowercase">walnutcreek@yogasmoga.com</span>

                    <p style="text-align:center">
                        <span style="font-weight:bold">Store Hours</span><br/>Monday–Friday 10am–9pm<br/>
                        Saturday 10am–7pm<br/>Sunday 11am-6pm
                    </p>

                    <p style="font-family:gothambook;">YOGASMOGA is coming to Broadway Plaza located in Walnut Creek,
                        CA: an open-air shopping center anchored by Neiman Marcus, Nordstrom, and home to more than 35
                        fine retailers and
                        restaurants. We hope to join this welcoming fashion space with open minds and open hearts.</p>

                </div>


            </div>
        </div>
        
      
       



    </div>

    <div class="bottomdivider"></div>
    <!-- bottomDivider -->

</div>
<!-- endCMSPages -->
<style>
    .gridFullWidth.marginbottom50 .block33 {
        box-sizing: border-box !important;
        float: left !important;
        width: 33.33% !important;
    }

    .white-line-seperator svg {
        border-left: 1px solid #fff;
        border-right: 1px solid #fff;
        position: relative;
        width: 100%;
        z-index: 3;
    }
</style>