<div class="namaskar-overlay1">&nbsp;</div>
<script type="text/javascript">
    jQuery(window).load(function () {
        jQuery('body').css('overflow', 'auto');
        jQuery('.namaskar-overlay1').fadeOut('slow');
    })
</script>
<!-- startCMSPages -->
<div class="gridCMSPages">
    <!-- gridBlockOne -->
    <div class="gridFullWidth ystopsection">
        <!-- BlockLeft -->
        <div class="block33">
            <!-- leftNavigation -->
            <div class="cmsNavigation">
                <ul>
                    <li><a href="/our-story">our story</a></li>
                    <li><a href="/our-core-values">our core values</a></li>
                    <li><a href="/our-ethics">our ethics</a></li>
                    <li><h1 style="font:11px/19px gothambold !important;margin:0"><a href="/our-stores" class="current">our
                                stores</a></h1></li>
                    <li><a href="/made-in-usa">made in usa</a></li>
                    <li><a href="/principles-of-yoga">principles of yoga</a></li>
                    <li><a href="/namaskar">namaskÁr foundation</a></li>
                    <li><a href="/press">press</a></li>
                </ul>
            </div>
            <!-- leftNavigation -->

            <!-- CMSheadingBlock -->
            <div class="headingBlock">
                <h1 class="positionAbs">YS STORES</h1>
            </div>
            <!-- CMSheadingBlock -->
        </div>
        <!-- BlockLeft -->

        <!-- BlockRight -->
        <div class="block66 posRel">
            <img src="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/new-design-images/YS-Store-yogasmoga-retail.jpg"
                 alt="" class="img-responsive"/>

            <div class="positionAbs" id="ysbannertxt" style="top:32.4%;">
                <span class="topHead">YOGASMOGA RETAIL EXPERIENCE</span>
                <h4>
                    FROM NYC TO THE WORLD
                    <span class="smallHead">WE GO WHEREVER LIFE TAKES YOU</span>
                </h4>
                <!--div class="htext white">
                    Honoring the tenets of Yoga, we aspire to create world-class products.<br />Growing up in the Himalayas, the birthplace & capital of Yoga, our founders instinctively<br />infuse the timeless principles, spirit and practice of Yoga into everything we do. From our<br />cosmopolitan aesthetic, to our product technology, right down to creating our very own way<br />to give back, we’ve meticulously designed every part of the whole, one breath at a time.
                </div-->
            </div>
            <!--<div class="htext white" style="position:absolute; width:100%; margin:0; bottom:40px;">
                                Honoring the tenets of Yoga, we aspire to create world-class products.<br />Growing up in the Himalayas, the birthplace & capital of Yoga, our founders instinctively<br />infuse the timeless principles, spirit and practice of Yoga into everything we do. From our<br />cosmopolitan aesthetic, to our product technology, right down to creating our very own way<br />to give back, we’ve meticulously designed every part of the whole, one breath at a time.
                            </div>-->
        </div>
        <!-- BlockRight -->
    </div>
    <!-- gridBlockOne -->
    <div class="gridFullWidth">
        <div id="ysbannertxt" class="gridCMSPages">
            <span style="color:#555;display:block;border-bottom:1px solid #555;margin:17px auto 15px" class="topHead ">IMAGINE: A STRONG COMMUNITY</span>
            <h4 style="color:#555;width:100%;font:36px/40px ITCAvantGardeProMd;margin-bottom:0;" class="topHead ">
                REFLECT, CONNECT, LEARN, GROW
                <span style="color:#555;" class="smallHead cntntheading">ONE BREATH AT A TIME</span>
            </h4>
        </div>
    </div>

    <!-- gridBlockTwo -->
    <div class="gridFullWidth marginbottom50">
        <!-- BlockLeft -->
        <div class="block33">
            <!-- contentPart -->
            <div class="textContainer">
                <img src="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/new-design-images/YS-Stores-020815_04.jpg"
                     alt="" class="img-responsive"/>

                <div class="cntntheading">
                    YOGASMOGA TOWNHOUSE
                    <span>68 GREENWICH AVE <br/>GREENWICH, CT 06830<br/>203 861 YOGA (9642)</span>
                    <span style="font-size:16px;font-family: AvantGardeGothicITCW01X;text-transform:lowercase">greenwich@yogasmoga.com</span>
                </div>
                <div class="contnttxt">
                    <p style="text-align:center">
                        <span style="font-weight:bold">Store Hours</span><br/>Monday–Saturday 10am–6pm<br/>
                        Sunday 11am-6pm </p>

                    <p style="font-family:gothambook;">We chose this two-story townhouse on Greenwich Avenue as our
                        first store for its strong community feel. The exposed brick walls create a cozy atmosphere and
                        neutral palette for our bright collections. We are currently renovating the upstairs space for
                        yoga classes and other wellness events. </p>
                </div>
            </div>
            <!-- contentPart -->
        </div>
        <!-- BlockLeft -->

        <!-- BlockRight -->
        <div class="block33">
            <!-- contentPart -->
            <div class="textContainer">
                <img src="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/new-design-images/YS-Stores-020815_05.jpg"
                     alt="" class="img-responsive"/>

                <div class="cntntheading">
                    YOGASMOGA BRENTWOOD
					
					<span>11911 SAN VICENTE BLVD, #150<br/> LOS ANGELES, CA 90049<br/>
                                     310 471 YOGA (9642)<br/>
									<span
                                        style="font-size:16px;font-family: AvantGardeGothicITCW01X;text-transform:lowercase">brentwood@yogasmoga.com</span>
									</span>
                </div>
                <div class="contnttxt">
                    <p style="text-align:center"><span style="font-weight:bold">Store Hours</span><br/>Monday–Friday
                        10am–8pm<br/>
                        Saturday–Sunday 10am–7pm </p>

                    <p style="font-family:gothambook;">Centrally located on the corner of San Vicente Boulevard and
                        Montana Avenue, we chose this space for its accessibility and neighborhood vibe. Our bright and
                        sunny Brentwood store is wrapped in floor-to-ceiling windows that fill the space with natural
                        light and warm, welcoming energy. </p>
                    <!--<p style="font-family:gothambook;">Just around the corner from Rodeo Drive, our Beverly Hills store is a calming retreat from the buzz of the city streets. Exposed beams, bright light and a cozy community space welcomes locals and visitors alike to shop our unique collection, relax and learn more about the YOGASMOGA story.</p>-->

                </div>
            </div>
            <!-- contentPart -->
        </div>
        <div class="block33"><!-- contentPart -->
            <div class="textContainer"><img class="img-responsive"
                                            src="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/new-design-images/ys_stores_address/ys-stores-beverly-hills.jpg"
                                            alt=""/>

                <div class="cntntheading">YOGASMOGA BEVERLY HILLS 
					<span>9458 Dayton Way<br/>Beverly Hills, CA 90210<br/>310 273 YOGA(9642)<br/>
						<span style="font-size:16px;font-family: AvantGardeGothicITCW01X;text-transform:lowercase">beverlyhills@yogasmoga.com</span>
					</span>
				</div>
                <div class="contnttxt"><p style="text-align:center"><span
                            style="font-weight:bold">Store Hours</span><br/>Monday–Saturday 11am–7pm<br/>
                        Sunday 11am–6pm </p>

                    <p style="font-family:gothambook;">Just around the corner from Rodeo Drive, our Beverly Hills store
                        is a calming retreat from the buzz of the city streets. Exposed beams, bright light and a cozy
                        community space welcomes locals and visitors alike to shop our unique collection, relax and
                        learn more about the YOGASMOGA story.</p>

                </div>
            </div>
            <!-- contentPart --></div>

			<div style="border-bottom:1px solid #fff!important;" class="bottomdivider">&nbsp;</div>

        <!--Edit to new block-->


        

        <div class="block33"><!-- contentPart -->
            <div class="textContainer">
				<img class="img-responsive" src="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/new-design-images/ys_stores_address/ys-store-seals-la-jolla-popup.png" alt=""/>

                <div class="cntntheading">YOGASMOGA <br/>La Jolla Pop-up<br/>
					<span style="display:inline;">7863 Girard Ave. Suite 107<br/>La Jolla, CA 92037<br/>open until novemBER 18<sup style="vertical-align:top;line-height:20px;">TH</sup>
							<br/>
							<span style="font-size:16px;font-family: AvantGardeGothicITCW01X;text-transform:lowercase">lajolla@yogasmoga.com</span>
					</span>
				</div>
                <div class="contnttxt">
                    <p style="text-align:center">
                        <span style="font-weight:bold">Store Hours</span><br/>Monday–Saturday 10am–7pm<br/>
                        Sunday 10am–6pm
                    </p>

                    <p style="font-family:gothambook;">Now open to our SMOGIs is our La Jolla Pop-up. A 900 square foot retail space,
					we are excited with the opportunity to offer the best in yoga inspired athletic apparel to the La Jolla, CA area. 
					This is a warm-up to the permanent space that is coming in November so stay tuned and just breathe.</p>

                </div>
            </div>
            <!-- contentPart --></div>
			
			 <div class="block33 white-line-seperator"><!-- contentPart -->
            <div class="textContainer">
				<img class="img-responsive" src="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/new-design-images/ys_stores_address/ys-store-seals-fashion-island.png" alt=""/>

                <div class="cntntheading">YOGASMOGA NEWPORT BEACH <br/>
					<span style="display:inline;">AT</span> FASHION ISLAND <span>1119 Newport Center Drive <br/>Newport Beach, CA 92660<br/>949 721 9642	
                        <br/> <br/>
                      <!--  <span style="font-size:16px;font-family: AvantGardeGothicITCW01X;text-transform:lowercase"></span>-->
					</span>
				</div>
                <div class="contnttxt">
                    <p style="text-align:center;margin-bottom:11px;">
                        <span style="font-weight:bold">Store Hours</span><br/>Monday–Friday 10am–9pm<br/>
                        Saturday 10am–7pm<br/>Sunday 11am-6pm
                    </p>

                    <p style="font-family:gothambook;">Fashion Island is an upscale open-air lifestyle center in Newport Beach, 
					California. Stay tuned while we create the best in yoga inspired athletic apparel experience for our SMOGIs.
					</p>

                </div>
            </div>
            <!-- contentPart --></div>
			 <div class="block33"><!-- contentPart -->
            <div class="textContainer"><img class="img-responsive"
                                            src="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/new-design-images/ys_stores_address/ys-store-seals-short-hills.png"
                                            alt=""/>

                <div class="cntntheading">YOGASMOGA<span style="display:inline;"> X</span> The Mall<br/>
					<span style="display:inline;">AT </span>Short Hills<br/>
						<span style="display:inline;">1200 MORRIS TPKE, #179 <br/>
								SHORT HILLS, NJ 07078<br/> 888 990 YOGA (9642)<br/>				
								<span style="font-size:16px;font-family: AvantGardeGothicITCW01X;text-transform:lowercase">shorthills@yogasmoga.com	</span>
						</span>
				</div>
                <div class="contnttxt">
				
                    <p style="text-align:center">
                        <span style="font-weight:bold">Store Hours</span><br/>Monday–Saturday 10am–9pm<br/>
                        Sunday 11am–6pm
                    </p>

                    <p style="font-family:gothambook;">YOGASMOGA is coming soon to The Mall at Short Hills located in Short Hills, NJ. 
					Experience yoga inspired premium athletic apparel along with New Jersey's 
					most extraordinary collection of quality retail in one beautiful location.</p>

                </div>
            </div>
            <!-- contentPart --></div>
			 <div style="border-bottom:1px solid #fff!important;" class="bottomdivider">&nbsp;</div>
			  <div class="block33"><!-- contentPart -->
            <div class="textContainer"><img class="img-responsive"
                                            src="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/new-design-images/ys_stores_address/ys-store-seals-westchester.png"
                                            alt=""/>

                <div class="cntntheading">YOGASMOGA<br/>  <span style="display:inline;">AT </span>THE WESTCHESTER<br/>
					<span>125 WESTCHESTER AVE, #3350<br/>WHITE PLAINS, NY 10601<br/>888 990 YOGA (9642) 
							<br/>
					  <span style="font-size:16px;font-family: AvantGardeGothicITCW01X;text-transform:lowercase">westchester@yogasmoga.com</span>
					</span>
				</div>
                <div class="contnttxt">
				<br/>
                    <p style="text-align:center">
                        <span style="font-weight:bold">Store Hours</span><br/>Monday–Saturday 10am–9pm<br/>
                        Sunday 11am–7pm
                    </p>
					
                    <p style="font-family:gothambook;">Coming soon to The Westchester Mall in White Plains, NY, YOGASMOGA at The Westchester
					will be our 6th retail location in the US.
					We are bringing vivacity and balance to the ultimate shopping experience in Westchester County, New York. </p>

                </div>
            </div>
            <!-- contentPart --></div>
			  <div class="block33 white-line-seperator"><!-- contentPart -->
				<div class="textContainer">
				<img class="img-responsive" src="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/new-design-images/ys_stores_address/ys-store-seals-prudential-center.png" alt=""/>

                <div class="cntntheading">YOGASMOGA 
					<span style="display:inline;">AT </span>“THE PRU” 
						<span>800 BOYLSTON STREET, #131<br/>BOSTON, MA 02199<br/>888 990 YOGA (9642)
                        <br/><br/>
                        <span style="font-size:16px;font-family: AvantGardeGothicITCW01X;text-transform:lowercase">boston.pru@yogasmoga.com</span>
						</span></div>
                <div class="contnttxt">
				<br/>
                    <p style="text-align:center">
                        <span style="font-weight:bold">Store Hours</span><br/>Monday–Saturday 10am–9pm<br/>
                        Sunday 11am–8pm
                    </p>

                    <p style="font-family:gothambook;">YOGASMOGA is coming soon to The Prudential Center in Boston, MA. The Pru, as it is most colloquially known, 
					is an urban shopping center located at the base of the Prudential Tower. We hope to enter this space with a calm and balanced collection of 
					the best yoga inspired athletic apparel in the US.</p>

                </div>
            </div>
            <!-- contentPart --></div>
			  <div class="block33"><!-- contentPart -->
            <div class="textContainer"><img class="img-responsive"
                                            src="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/new-design-images/ys_stores_address/ys-store-seals-corte-madera.png"
                                            alt=""/>

                <div class="cntntheading">YOGASMOGA <span style="display:inline;">X</span> THE VILLAGE<br/><span style="display:inline;"> AT </span>CORTE MADERA
				<span>1618 REDWOOD HWY<br/>CORTE MADERA, CA 94925<br/>888 990 YOGA (9642)
                        <br/>
                        <span style="font-size:16px;font-family: AvantGardeGothicITCW01X;text-transform:lowercase">cortemadera@yogasmoga.com</span>
				</span></div>
                <div class="contnttxt">
                    <p style="text-align:center">
                        <span style="font-weight:bold">Store Hours</span><br/>Monday–Friday 10am–8pm<br/>
                        Saturday 10am–7pm<br/>Sunday 11am-6pm
                    </p>

                    <p style="font-family:gothambook;">The Village at Corte Madera is an open-air shopping center located in Corte Madera, CA,
					including premuim shops, restaurants and many more. Breathe the open air while you walk through
					The Village's breezy layout and explore our premium collection of yoga inspired athletic apparel.</p>

                </div>
            </div>
            <!-- contentPart --></div>
			 <div style="border-bottom:1px solid #fff!important;" class="bottomdivider">&nbsp;</div>
			   <div class="block33"><!-- contentPart -->
            <div class="textContainer"><img class="img-responsive"
                                            src="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/new-design-images/ys_stores_address/ys-store-seals-san-francisco.png"
                                            alt=""/>

                <div class="cntntheading">YOGASMOGA SAN FRANCISCO <br/><span>66 KEARNY ST<br/>SAN FRANCISCO, CA 94108<br/>888 990 YOGA (9642)                        <br/>
                        <span style="font-size:16px;font-family: AvantGardeGothicITCW01X;text-transform:lowercase">sanfran.unionsquare@yogasmoga.com</span>
						</span>
				</div>
                <div class="contnttxt">
                    <p style="text-align:center">
                        <span style="font-weight:bold">Store Hours</span><br/>Monday–Saturday 10am–8pm<br/>
                        Sunday 11am–7pm
                    </p>

                    <p style="font-family:gothambook;">Coming soon to the Financial District of San Francisco will live our expansive and luxurious 
					retail experience on 66 Kearny St. 
					Our San Francisco fans reached out to us so we are coming in with open hearts.</p>

                </div>
            </div>
            <!-- contentPart --></div>
			 <div class="block33 white-line-seperator"><!-- contentPart -->
            <div class="textContainer"><img class="img-responsive"
                                            src="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/new-design-images/ys_stores_address/ys-store-seals-la-Jolla.png"
                                            alt=""/>

                <div class="cntntheading">YOGASMOGA LA JOLLA <br/><span> 7863 GIRARD AVE, #101<br/>LA JOLLA, CA 92037<br/>888 990 YOGA (9642)
                        <br/>
                        <span style="font-size:16px;font-family: AvantGardeGothicITCW01X;text-transform:lowercase">lajolla@yogasmoga.com</span>
						</span>
				</div>
                <div class="contnttxt">
                    <p style="text-align:center">
                        <span style="font-weight:bold">Store Hours</span><br/>Monday–Saturday 10am–7pm<br/>
                        Sunday 10am–6pm
                    </p>

                    <p style="font-family:gothambook;">Coming in November 2015, you'll have a chance to experience YOGASMOGA in the jewel 
					of Southern California, La Jolla.
					With vacation sunshine all year-round, you will find yourself immersed in luxurious retail while taking in the rays.</p>

                </div>
            </div>
            <!-- contentPart --></div>
						 <div class="block33"><!-- contentPart -->
            <div class="textContainer"><img class="img-responsive"
                                            src="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/new-design-images/ys_stores_address/ys-store-seals-mailibu.png"
                                            alt=""/>

                <div class="cntntheading">YOGASMOGA MALIBU <br/> <span>3900 CROSS CREEK RD, STE 3A<br/>MALIBU, CA 90265<br/>888 990 YOGA (9642)
                        <br/>
                        <span style="font-size:16px;font-family: AvantGardeGothicITCW01X;text-transform:lowercase">malibu@yogasmoga.com</span>
						</span>
				</div>
                <div class="contnttxt">
                    <p style="text-align:center">
                        <span style="font-weight:bold">Store Hours</span><br/>Monday–Saturday 10am–7pm<br/>
                        Sunday 11am–6pm
                    </p>

                    <p style="font-family:gothambook;">Coming in November 2015 will be our Malibu store located in the Malibu Country Mart: a large outdoor
					lifestyle center or "boutique mall" located at the Civic Center of Malibu. 
					Wearing your YOGASMOGAs while basking in the sun is the best way to experience this sunny beach city.</p>

                </div>
            </div>
            <!-- contentPart --></div>
			 <div style="border-bottom:1px solid #fff!important;" class="bottomdivider">&nbsp;</div>
			 	 <div class="block33"><!-- contentPart -->
            <div class="textContainer"><img class="img-responsive"
                                            src="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/new-design-images/ys_stores_address/ys-store-seals-walnutcreek.png"
                                            alt=""/>

                <div class="cntntheading">YOGASMOGA  <span style="display:inline;">AT</span> WALNUT CREEK <span>1275 BROADWAY PLAZA, #E04<br/>WALNUT CREEK, CA 94925<br/>888 990 YOGA (9642)<br/>
                        <span style="font-size:16px;font-family: AvantGardeGothicITCW01X;text-transform:lowercase">walnutcreek@yogasmoga.com</span>
						</span>
				</div>
                <div class="contnttxt">
                    <p style="text-align:center">
                        <span style="font-weight:bold">Store Hours</span><br/>Monday–Friday 10am–9pm<br/>
                        Saturday 10am–7pm<br/>Sunday 11am-6pm
                    </p>

                    <p style="font-family:gothambook;">YOGASMOGA is coming to Broadway Plaza located in Walnut Creek, 
					CA: an open-air shopping center anchored by Neiman Marcus, Nordstrom,and home to more than 35 fine retailers and
					restaurants. We hope to join this welcoming fashion space with open minds and open hearts.</p>

                </div>
            </div>
            <!-- contentPart --></div>
			 
        <!-- BlockLeft --> <!-- BlockRight -->
        <!--Edit to new block end-->
        <!-- BlockRight -->
    </div>
    <!-- gridBlockTwo -->


    <!-- gridBlockOne -->

    <!-- gridBlockOne -->

    <!-- bottomDivider -->
    <div class="bottomdivider"></div>
    <!-- bottomDivider -->

</div>
<!-- endCMSPages -->
<style>
    .gridFullWidth.marginbottom50 .block33 {
        box-sizing: border-box !important;
        float: left !important;
        width: 33.33% !important;
    }
	.white-line-seperator img{ border-left: 1px solid #fff;
    border-right: 1px solid #fff;
    position: relative;
    z-index: 3;}
</style>