<div class="namaskar-overlay1">&nbsp;</div>
<script type="text/javascript">
    jQuery(window).load(function(){
        jQuery('body').css('overflow','auto');
        jQuery('.namaskar-overlay1').fadeOut('slow');
    })
</script>
<!-- startCMSPages -->
<div class="gridCMSPages">
	<!-- gridBlockOne -->
	<div class="gridFullWidth ystopsection">
		<!-- BlockLeft -->
		<div class="block33">
			<!-- leftNavigation -->
			<div class="cmsNavigation">
				<ul>
					<li><a href="/our-story">our story</a></li>
					<li><a href="/our-core-values">our core values</a></li>
					<li><a href="/our-ethics" class="current">our ethics</a></li>
                    <!--<li><a href="/our-stores" >our stores</a></li>-->
					<li><a href="/made-in-usa">made in usa</a></li>
					<li><a href="/principles-of-yoga">principles of yoga</a></li>
					<li><a href="/namaskar">namaskÁr foundation</a></li>
					<li><a href="/press">press</a></li>
				</ul>
			</div>
			<!-- leftNavigation -->

			<!-- CMSheadingBlock -->
			<div class="headingBlock">
				<div class="positionAbs h1">our<br /> ethics</div>
				<h1 style="display:none">YOGASMOGA Ethics</h1>
			</div>
			<!-- CMSheadingBlock -->
		</div>
		<!-- BlockLeft -->

		<!-- BlockRight -->
		<div class="block66 posRel">
			<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/ethicsHero.jpg" alt="" class="img-responsive" />
			<div class="positionAbs" id="ysbannertxtThree" style="top:32.4%">
				<span class="topHead">WHAT WE DO</span>
				<div class="h4">
					BE RESPECTFUL<br />OF OUR ENVIRONMENT
					<span class="smallHead">BUILDING A PATHWAY TO GREATER GOOD</span>
				</div>
				<!--div class="htext white" style="margin-top:103px;">
					We believe that if we don’t take good care of our world, it may fast disappear.<br />We have a responsibility to our planet.
				</div-->
			</div>
<div class="htext white" style="position:absolute; width:100%; margin:0; bottom:40px;">
					We believe that if we don’t take good care of our world, it may fast disappear.<br />We have a responsibility to our planet.
				</div>
		</div>
		<!-- BlockRight -->
	</div>
	<!-- gridBlockOne -->

	<!-- gridBlockTwo -->
	<div class="gridFullWidth marginbottom50">
		<!-- BlockLeft -->
		<div class="block50">
			<!-- contentPart -->
			<div class="textContainer">
				<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/oe-no-chemicals.jpg" alt="" class="img-responsive" />
				<div class="cntntheading">
					NO HARMFUL<br />CHEMICALS
				</div>
				<div class="contnttxt">
					<p>We have developed a dyeing process that is efficient and eco-friendly. We use the most advanced computerized color matching and dyeing apparatus and high performance dye-jets. The dye-jets are custom programmed to use exact amount of pigmentation so that residual water after the dyeing is clear and run off can be released without adding harmful chemicals such as formaldehyde based dyes that can destroy our groundwater.</p>
					<p>Our dye-lab is located in the USA, in a geographical area with the toughest environmental and pollution standards. We are very proud to have developed processes that meet and exceed these strict environmental regulations.</p>
				</div>
			</div>
			<!-- contentPart -->
		</div>
		<!-- BlockLeft -->

		<!-- BlockRight -->
		<div class="block50">
			<!-- contentPart -->
			<div class="textContainer">
				<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/oe-footprint.jpg" alt="" class="img-responsive" />
				<div class="cntntheading">
					REDUCING<br />THE CARBON FOOTPRINT
				</div>
				<div class="contnttxt">
					<p>Significant work has been done to solve for and create a supply chain as close to YOGASMOGA HQ (New York City) as possible.</p>
					<p>We do not produce in China and do not ship goods 12,500 miles across the globe –– this reduces our fossil fuel usage dramatically. While we can make cheap goods in China, we have made the conscious decision not to do so. We manufacture as close to home as possible with goods travelling 1/4th the distance as compared to our competitors, dramatically reducing our carbon footprint.</p>
					<p>We source trims such as elastics and threads as close to our production facilities as possible, thus reducing fossil fuel usage.</p>
				</div>
			</div>
			<!-- contentPart -->
		</div>
		<!-- BlockRight -->
	</div>
	<!-- gridBlockTwo -->

	<!-- gridBlockThree -->
	<div class="gridFullWidth marginbottom50">
		<!-- BlockLeft -->
		<div class="block50">
			<!-- contentPart -->
			<div class="textContainer">
				<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/oe-production.jpg" alt="" class="img-responsive" />
				<div class="cntntheading">
					RESPONSIBLE PRODUCTION<br />PARTNERS
				</div>
				<div class="contnttxt lineheight18">
					<p>YOGASMOGA has a very vigorous selection process of production partners. We work only with the best manufacturers who have demonstrated a commitment to adhere to the highest ethical and environmental conscious standards.</p>
					<p>Our production facilities have been awarded the Platinum Certificate of Compliance from WRAP (Worldwide Responsible Accredited Production). Our facilities are also participating suppliers of the Fair Labor Association. (Just in case you were wondering –– Yes its kind of a big deal to achieve these certifications!)</p>
					<p>They also have extensive green environment programs including recycling, energy saving production measures, use of clean fuels like LPG's, reforestation and use of biodegradable chemicals.</p>
				</div>
			</div>
			<!-- contentPart -->
		</div>
		<!-- BlockLeft -->

		<!-- BlockRight -->
		<div class="block50">
			<!-- contentPart -->
			<div class="textContainer">
				<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/oe-supply-chain.jpg" alt="" class="img-responsive" />
				<div class="cntntheading">
					ACCOUNTABLE FOR EACH<br />COMPONENT IN THE SUPPLY CHAIN
				</div>
				<div class="contnttxt lineheight18">
					<p>YOGASMOGA is committed to owning every piece of the supply chain. We assume responsibility for every step in the production process from sourcing fiber to bringing you the finished apparel. We research & develop it, we manufacture it, we dye it, we cut it, we stitch it, we pack it, we ship it - why? - so you can proudly enjoy it!</p>
					<p>We require a Manufacturer's Affidavit of Origin on all yarns that we purchase, ensuring adherence to the highest quality yarns. We strongly believe that sourcing the best raw materials available to us results in the best performing products. Life is sometimes as simple as the choices you make.</p>
					<p>We work directly with all our suppliers even for the smallest components such as trims, labels and threads that make up the product. We believe that sub contracting even these smaller items can and will compromise quality. We look closer and go deeper to deliver the very best to you.</p>
				</div>
			</div>
			<!-- contentPart -->
		</div>
		<!-- BlockRight -->
	</div>
	<!-- gridBlockThree -->

	<!-- gridBlockFour -->
	<div class="gridFullWidth">
		<!-- BlockLeft -->
		<div class="block50">
			<!-- contentPart -->
			<div class="textContainer">
				<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/oe-photosphere.jpg" alt="" class="img-responsive" />
				<div class="cntntheading">
					#NOPHOTOSHOP HERE
				</div>
				<div class="contnttxt">
					<p>YOGASMOGA believes in the accurate representation of all visual images. As a rule, We do not allow any body retouching in our photography. All photographers have to
	commit to this rule. No exceptions. We make an extraordinary effort to work with teachers and everyday practitioners of yoga for visual representation of our products.</p>
				</div>
			</div>
			<!-- contentPart -->
		</div>
		<!-- BlockLeft -->

		<!-- BlockRight -->
		<div class="block50">
			<!-- contentPart -->
			<div class="textContainer">
				<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/oe-yoga-community.jpg" alt="" class="img-responsive" />
				<div class="cntntheading">
					SUPPORTING<br />THE YOGA COMMUNITY
				</div>
				<div class="contnttxt">
					<p>The mission of YOGASMOGA is to elevate people’s lives through the deep knowledge, essence and ethos of yoga. We aim to build deep and meaningful relationships with the yoga community. A core principle at YOGASMOGA is to support instructors who share our values and are an integral part of this community.</p>
				</div>
			</div>
			<!-- contentPart -->
		</div>
		<!-- BlockRight -->
	</div>
	<!-- gridBlockFour -->

	<!-- bottomDivider -->
	<div class="bottomdivider"></div>
	<!-- bottomDivider -->

</div>
<!-- endCMSPages -->