<div class="namaskar-overlay1">&nbsp;</div>
<script type="text/javascript">
    jQuery(window).load(function () {
        jQuery('body').css('overflow', 'auto');
        jQuery('.namaskar-overlay1').fadeOut('slow');
    })
</script>
<!-- startCMSPages -->
<div class="gridCMSPages">
    <!-- gridBlockOne -->
    <div class="gridFullWidth ystopsection">
        <!-- BlockLeft -->
        <div class="block33">
            <!-- leftNavigation -->
            <div class="cmsNavigation">
                <ul>
                    <li><a href="/our-story">our story</a></li>
                    <li><a href="/our-core-values">our core values</a></li>
                    <li><a href="/our-ethics">our ethics</a></li>
                    <li><h1 style="font:11px/19px gothambold !important;margin:0"><a href="/our-stores" class="current">our
                                stores</a></h1></li>
                    <li><a href="/made-in-usa">made in usa</a></li>
                    <li><a href="/principles-of-yoga">principles of yoga</a></li>
                    <li><a href="/namaskar">namaskÁr foundation</a></li>
                    <li><a href="/press">press</a></li>
                </ul>
            </div>
            <!-- leftNavigation -->

            <!-- CMSheadingBlock -->
            <div class="headingBlock">
                <h1 class="positionAbs">YS STORES</h1>
            </div>
            <!-- CMSheadingBlock -->
        </div>
        <!-- BlockLeft -->

        <!-- BlockRight -->
        <div class="block66 posRel">
            <img src="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/new-design-images/YS-Store-yogasmoga-retail.jpg"
                 alt="" class="img-responsive"/>

            <div class="positionAbs" id="ysbannertxt" style="top:32.4%;">
                <span class="topHead">YOGASMOGA RETAIL EXPERIENCE</span>
                <h4>
                    FROM NYC TO THE WORLD
                    <span class="smallHead">WE GO WHEREVER LIFE TAKES YOU</span>
                </h4>
                <!--div class="htext white">
                    Honoring the tenets of Yoga, we aspire to create world-class products.<br />Growing up in the Himalayas, the birthplace & capital of Yoga, our founders instinctively<br />infuse the timeless principles, spirit and practice of Yoga into everything we do. From our<br />cosmopolitan aesthetic, to our product technology, right down to creating our very own way<br />to give back, we’ve meticulously designed every part of the whole, one breath at a time.
                </div-->
            </div>
            <!--<div class="htext white" style="position:absolute; width:100%; margin:0; bottom:40px;">
                                Honoring the tenets of Yoga, we aspire to create world-class products.<br />Growing up in the Himalayas, the birthplace & capital of Yoga, our founders instinctively<br />infuse the timeless principles, spirit and practice of Yoga into everything we do. From our<br />cosmopolitan aesthetic, to our product technology, right down to creating our very own way<br />to give back, we’ve meticulously designed every part of the whole, one breath at a time.
                            </div>-->
        </div>
        <!-- BlockRight -->
    </div>
    <!-- gridBlockOne -->
    <div class="gridFullWidth">
        <div id="ysbannertxt" class="gridCMSPages">
            <span style="color:#555;display:block;border-bottom:1px solid #555;margin:17px auto 15px" class="topHead ">IMAGINE: A STRONG COMMUNITY</span>
            <h4 style="color:#555;width:100%;font:36px/40px ITCAvantGardeProMd;margin-bottom:0;" class="topHead ">
                REFLECT, CONNECT, LEARN, GROW
                <span style="color:#555;" class="smallHead cntntheading">ONE BREATH AT A TIME</span>
            </h4>
        </div>
    </div>

    <!-- gridBlockTwo -->
    <div class="gridFullWidth marginbottom50">
        <div class="gridFullWidth">
            <div class="block33">
                <img src="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/new-design-images/YS-Stores-020815_04.jpg"
                     alt="" class="img-responsive"/>
            </div>
            <div class="block33">
                <img src="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/new-design-images/YS-Stores-020815_05.jpg"
                     alt="" class="img-responsive"/>
            </div>
            <div class="block33">
                <img class="img-responsive"
                     src="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/new-design-images/ys_stores_address/ys-stores-beverly-hills.jpg"
                     alt=""/>
            </div>
        </div>

        <div class="gridFullWidth">
            <div class="block33">
                <div class="cntntheading">
                    <div class="content-wrapper">
                        YOGASMOGA TOWNHOUSE
                        <span>68 GREENWICH AVE <br/>GREENWICH, CT 06830<br/>203 861 YOGA (9642)</span>
                    </div>

                </div>


            </div>

            <div class="block33">
                <div class="cntntheading">
                    <div class="content-wrapper">
                        YOGASMOGA BRENTWOOD
							<span>11911 SAN VICENTE BLVD<br/> LOS ANGELES, CA 90049<br/>
											 310 471 YOGA (9642)</span>
                    </div>
                </div>

            </div>
            <div class="block33">
                <div class="cntntheading">
                    <div class="content-wrapper">
                        YOGASMOGA BEVERLY HILLS
                        <span>9458 Dayton Way<br/>Beverly Hills, CA 90210<br/>310 273 YOGA (9642)</span></div>


                </div>


            </div>
        </div>
        <div class="gridFullWidth">
            <div class="block33">
                <div class="contnttxt">
                    <span style="font-size:16px;font-family: AvantGardeGothicITCW01X;text-transform:lowercase">greenwich@yogasmoga.com</span>

                    <p style="text-align:center">
                        <span class="store-hours">Store Hours</span><br/>Monday–Saturday 10am–6pm<br/>
                        Sunday 11am-6pm </p>

                    <p style="font-family:gothambook;">We chose this two-story townhouse on Greenwich Avenue as our
                        first store for its strong community feel. The exposed brick walls create a cozy atmosphere and
                        neutral palette for our bright collections. We are currently renovating the upstairs space for
                        yoga classes and other wellness events. </p>
                </div>


            </div>

            <div class="block33">
                <div class="contnttxt">
                    <span style="font-size:16px;font-family: AvantGardeGothicITCW01X;text-transform:lowercase">brentwood@yogasmoga.com</span>

                    <p style="text-align:center"><span class="store-hours">Store Hours</span><br/>Monday–Friday
                        10am–8pm<br/>
                        Saturday–Sunday 10am-7pm </p>

                    <p style="font-family:gothambook;">Centrally located on the corner of San Vicente Boulevard and
                        Montana Avenue, we chose this space for its accessibility and neighborhood vibe. Our bright and
                        sunny Brentwood store is wrapped in floor-to-ceiling windows that fill the space with natural
                        light and warm, welcoming energy. </p>
                    <!--<p style="font-family:gothambook;">Just around the corner from Rodeo Drive, our Beverly Hills store is a calming retreat from the buzz of the city streets. Exposed beams, bright light and a cozy community space welcomes locals and visitors alike to shop our unique collection, relax and learn more about the YOGASMOGA story.</p>-->

                </div>


            </div>

            <div class="block33">
                <div class="contnttxt">
                    <span style="font-size:16px;font-family: AvantGardeGothicITCW01X;text-transform:lowercase">beverlyhills@yogasmoga.com</span>

                    <p style="text-align:center"><span class="store-hours">Store Hours</span><br/>Monday–Saturday 11am–7pm<br/>
                        Sunday 11am–6pm </p>

                    <p style="font-family:gothambook;">Just around the corner from Rodeo Drive, our Beverly Hills store
                        is a calming retreat from the buzz of the city streets. Exposed beams, bright light and a cozy
                        community space welcomes locals and visitors alike to shop our unique collection, relax and
                        learn more about the YOGASMOGA story.</p>

                </div>


            </div>
        </div>
        <div style="border-bottom:1px solid #fff!important;" class="bottomdivider">&nbsp;</div>

        <div class="gridFullWidth">
		 <div class="block33">
                <!--------------- svg start----------->
               <img src="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/new-design-images/ys_stores_address/fashion-island.png"
                     alt="" class="img-responsive"/>

                <!--------------- svg ends----------->
            </div>
          
			<div class="block33 white-line-seperator">
                <!--------------- svg starts----------->
               <img src="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/new-design-images/ys_stores_address/boston-our-store.jpg"
                     alt="" class="img-responsive"/>
                <!--------------- svg ends----------->
            </div>
            <div class="block33">
                <!--------------- svg starts----------->
                <img src="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/new-design-images/ys_stores_address/malibu-our-store.jpg"
                     alt="" class="img-responsive"/>
                <!--------------- svg ends----------->
            </div>
			


        </div>
        <div class="gridFullWidth">
            <div class="block33">
                <div class="cntntheading">
                    <div class="content-wrapper">
                        YOGASMOGA NEWPORT BEACH <br/>
                        <span style="display:inline;">AT</span> FASHION ISLAND <span>1119 Newport Center Drive <br/>Newport Beach, CA 92660<br/>949 721 YOGA (9642)
								</span>
                    </div>


                </div>


            </div>

             <div class="block33">
                <div class="cntntheading">
                    <div class="content-wrapper">
                        YOGASMOGA
                        <span style="display:inline;">X </span>“THE PRU”
								<span>800 BOYLSTON STREET<br/>BOSTON, MA 02199<br/>888 990 YOGA (9642)
								<br/><br/></span>
                    </div>

                </div>


            </div>
            <div class="block33">
                <div class="cntntheading">
                    <div class="content-wrapper">
					     YOGASMOGA<span style="display:inline;"> X </span>MALIBU<BR/> COUNTRY MART<br/>
                       <span>3900 CROSS CREEK RD<br/>MALIBU, CA 90265<br/>424 346 5002
									</span>
                    </div>


                </div>


            </div>
        </div>
        <div class="gridFullWidth">
              <div class="block33">
                <div class="contnttxt">
                    <span style="font-size:16px;font-family: AvantGardeGothicITCW01X;text-transform:lowercase">fashionisland@yogasmoga.com</span>

                    <p style="text-align:center;">
                        <span class="store-hours">Store Hours</span><br/>Monday–Friday 10am–9pm<br/>
                        Saturday 10am–7pm<br/>Sunday 11am-6pm
                    </p>

                    <p style="font-family:gothambook;">Now open in between Macy's and Nordstrom, our Fashion Island store is an upscale, open-air space perfect for in-store classes. Richly colored wood displays showcase our unique and colorful collection, inviting visitors to shop, relax and learn more about the YOGASMOGA story.

                    </p>

                </div>


            </div>

          <div class="block33">
                <div class="contnttxt">
                    <span style="font-size:16px;font-family: AvantGardeGothicITCW01X;text-transform:lowercase">boston.pru@yogasmoga.com</span>

                    <p style="text-align:center">
                        <span class="store-hours">Store Hours</span><br/>Monday–Saturday 10am–9pm<br/>
                        Sunday 11am–8pm<br/>&nbsp;
                    </p>

                    <p style="font-family:gothambook;">YOGASMOGA is now open at The Shops at the Prudential Center. The Pru, as it is most colloquially known, is an urban shopping center located at the base of the Prudential Tower. This location is special to us because we are able to bring our Made In USA product from Fall River, Massachusetts closer to your Boston doorstep.</p>

                </div>


            </div>

             <div class="block33">
                <div class="contnttxt">
                    <span style="font-size:16px;font-family: AvantGardeGothicITCW01X;text-transform:lowercase">malibu@yogasmoga.com</span>

                    <p style="text-align:center">
                        <span class="store-hours">Store Hours</span><br/>Monday–Saturday 10am–6pm<br/>
                        Sunday 11am–6pm
                    </p>
					<p style="margin: 0;line-height: 15px;">&nbsp;</p>
                    <p style="font-family:gothambook;">Now open in the Malibu Country Mart: a large outdoor, lifestyle center or "boutique mall" located at the Civic Center of Malibu. Wearing your YOGASMOGAs while basking in the sun is the best way to experience this sunny beach city.</p>

                </div>


            </div>
        </div>
        <div style="border-bottom:1px solid #fff!important;" class="bottomdivider">&nbsp;</div>
        <div class="gridFullWidth">
		 <div class="block33">
                <!--------------- svg starts----------->
               <img src="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/new-design-images/ys_stores_address/san-francisco.png"
                     alt="" class="img-responsive"/>
                <!--------------- svg ends----------->
            </div>
           
                        <div class="block33 white-line-seperator">
                <img src="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/new-design-images/ys_stores_address/lajolla.png"
                     alt="" class="img-responsive"/>
            </div>
			
            <div class="block33">
                <img src="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/new-design-images/ys_stores_address/cortemadera.png"
                     alt="" class="img-responsive"/>
            </div>
        </div>
        <div class="gridFullWidth">
		 <div class="block33">
                <div class="cntntheading">
                    <div class="content-wrapper">
                        YOGASMOGA SAN FRANCISCO <br/><span>66 KEARNY ST<br/>SAN FRANCISCO, CA 94108<br/>415 934 YOGA (9642)   </span>
                    </div>


                </div>


            </div>
            

           <div class="block33">
                <div class="cntntheading">
                    <div class="content-wrapper">
                        YOGASMOGA <span style="display:inline;">X</span><br/>LA PLAZA LA JOLLA <br/><span> 7863 GIRARD AVE <br/>LA JOLLA, CA 92037<br/>858 732 YOGA (9642) 
								  </span>
                    </div>


                </div>


            </div>
            <div class="block33">
                <div class="cntntheading">
                    <div class="content-wrapper">
                        YOGASMOGA <span style="display:inline;">X</span> THE VILLAGE<br/><span style="display:inline;"> AT </span>CORTE
                        MADERA
						<span>1530 REDWOOD HWY<br/>CORTE MADERA, CA 94925<br/>415 548 6110
								<br/></span>
                    </div>

                </div>


            </div>
        </div>
        <div class="gridFullWidth">
		<div class="block33">
                <div class="contnttxt">
                    <span style="font-size:16px;font-family: AvantGardeGothicITCW01X;text-transform:lowercase">sanfran.unionsquare@yogasmoga.com</span>

                    <p style="text-align:center">
                        <span class="store-hours">Store Hours</span><br/>Monday–Saturday 10am–8pm<br/>
                        Sunday 11am–7pm
                    </p>
						<p style="margin: 0;line-height: 15px;">&nbsp;</p>
                    <p style="font-family:gothambook;">Our expansive and luxurious retail space is open in the Financial District of San Francisco, on Kearny St. Our San Francisco fans reached out to us so we answered them with open hearts.</p>

                </div>


            </div>
           

            <div class="block33">
                <div class="contnttxt">
                    <span style="font-size:16px;font-family: AvantGardeGothicITCW01X;text-transform:lowercase">lajolla@yogasmoga.com</span>

                    <p style="text-align:center">
                        <span class="store-hours">Store Hours</span><br/>Monday–Saturday 10am–7pm<br/>
                        Sunday 10am–6pm
                    </p>
					<p style="margin: 0;line-height: 15px;">&nbsp;</p>
                    <p style="font-family:gothambook;">YOGASMOGA is now open in the jewel of Southern California, La Jolla. With vacation sunshine all year-round, you will find yourself immersed in luxurious retail while taking in the rays.</p>

                </div>


            </div>

            <div class="block33">
                <div class="contnttxt">
                    <span style="font-size:16px;font-family: AvantGardeGothicITCW01X;text-transform:lowercase">cortemadera@yogasmoga.com</span>

                    <p style="text-align:center">
                        <span class="store-hours">Store Hours</span><br/>Monday–Friday 10am–8pm<br/>
                        Saturday 10am–7pm<br/>Sunday 11am-6pm
                    </p>

                    <p style="font-family:gothambook;">The Village at Corte Madera is an open-air shopping center
                        located in Corte Madera, CA,
                        including premium shops, restaurants and many more. Breathe the open air while you walk through
                        The Village's breezy layout and explore our premium collection of yoga inspired athletic
                        apparel.</p>

                </div>


            </div>
        </div>
        <div style="border-bottom:1px solid #fff!important;" class="bottomdivider">&nbsp;</div>

        <div class="gridFullWidth">
		 <div class="block33">
                 <img src="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/new-design-images/ys_stores_address/westchester.png"
                     alt="" class="img-responsive"/>
            </div>
			
			            <div class="block33 white-line-seperator">
               <img src="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/new-design-images/ys_stores_address/short-hills.png"
                     alt="" class="img-responsive"/>
            </div>
			 <div class="block33">
                <img src="<?php echo Mage::getBaseUrl('media') ?>wysiwyg/new-design-images/ys_stores_address/walnut-creek.png"
                     alt="" class="img-responsive"/>
            </div>
        </div>

        <div class="gridFullWidth">
		<div class="block33">
                <div class="cntntheading">
                    <div class="content-wrapper">
                        YOGASMOGA<br/> <span style="display:inline;">X </span>THE WESTCHESTER<br/>
							<span>125 WESTCHESTER AVE<br/>WHITE PLAINS, NY 10601<br/>914 367 YOGA (9642) 
									</span>
                    </div>


                </div>


            </div>

              <div class="block33">
                <div class="cntntheading">
                    <div class="content-wrapper">
                        YOGASMOGA<span style="display:inline;"> X</span> The Mall<br/>
                        <span style="display:inline;">AT </span>Short Hills<br/>
								<span style="display:inline;">1200 MORRIS TURNPIKE<br/>
										SHORT HILLS, NJ 07078<br/> 973 315 9671</span></div>


                </div>


            </div>
			<div class="block33">
                <div class="cntntheading">
                    <div class="content-wrapper">
                        YOGASMOGA <span style="display:inline;">X</span>  WALNUT CREEK <BR/>AT BROADWAY PLAZA
                        <span>1166 BROADWAY PLAZA<br/>WALNUT CREEK, CA 94596<br/>925 378 6942</span>
                    </div>

                </div>
            </div>
        </div>
        <div class="gridFullWidth">
		 <div class="block33">
                <div class="contnttxt">
                    <span style="font-size:16px;font-family: AvantGardeGothicITCW01X;text-transform:lowercase">westchester@yogasmoga.com</span>

                    <p style="text-align:center">
                        <span class="store-hours">Store Hours</span><br/>Monday–Saturday 10am–9pm<br/>
                        Sunday 11am–7pm<br/>&nbsp;
                    </p>

                    <p style="font-family:gothambook;">YOGASMOGA is now open at The Westchester Mall in White Plains, NY. We are bringing vivacity and balance to the ultimate shopping experience in Westchester County, New York. </p>

                </div>


            </div>
           <div class="block33">
                <div class="contnttxt">
                    <span style="font-size:16px;font-family: AvantGardeGothicITCW01X;text-transform:lowercase">shorthills@yogasmoga.com	</span>

                    <p style="text-align:center">
                        <span class="store-hours">Store Hours</span><br/>Monday–Saturday 10am–9pm<br/>
                        Sunday 11am–6pm
                    </p>

                    <p style="margin: 0;line-height:15px;">&nbsp;</p>

                    <p style="font-family:gothambook;">YOGASMOGA is now open at The Mall at Short Hills. Experience yoga inspired premium athletic apparel along with New Jersey's most extraordinary collection of quality retail in one beautiful location. </p>

                </div>


            </div>

             <div class="block33">
                <div class="contnttxt">
                    <span style="font-size:16px;font-family: AvantGardeGothicITCW01X;text-transform:lowercase">walnutcreek@yogasmoga.com</span>

                    <p style="text-align:center">
                        <span class="store-hours">Store Hours</span><br/>Monday–Friday 10am–9pm<br/>
                        Saturday 10am–7pm<br/>Sunday 11am-6pm
                    </p>

                    <p style="font-family:gothambook;">YOGASMOGA is now open at Broadway Plaza located in Walnut Creek,
                        CA: an open-air shopping center anchored by Neiman Marcus, Nordstrom, and home to more than 35
                        fine retailers and
                        restaurants. We hope to join this welcoming fashion space with open minds and open hearts.</p>

                </div>


            </div>
        </div>
        
      
       



    </div>

    <div class="bottomdivider"></div>
    <!-- bottomDivider -->

</div>
<!-- endCMSPages -->
<style>
    .gridFullWidth.marginbottom50 .block33 {
        box-sizing: border-box !important;
        float: left !important;
        width: 33.33% !important;
    }

    .white-line-seperator svg {
        border-left: 1px solid #fff;
        border-right: 1px solid #fff;
        position: relative;
        width: 100%;
        z-index: 3;
    }
</style>