<div class="namaskar-overlay1">&nbsp;</div>
<script type="text/javascript">
	jQuery(window).load(function(){
		jQuery('body').css('overflow','auto');
		jQuery('.namaskar-overlay1').fadeOut('slow');
	})
</script>
<!-- startCMSPages -->
<div class="gridCMSPages pressPage">
	<!-- gridBlockOne -->
	<div class="gridFullWidth">
		<!-- BlockLeft -->
		<div class="block33">
			<!-- leftNavigation -->
			<div class="cmsNavigation minh250">
				<ul>
					<li><a href="/our-story">our story</a></li>
					<li><a href="/our-core-values">our core values</a></li>
					<li><a href="/our-ethics">our ethics</a></li>
					<li><h1 style="font:11px/19px gothambold !important;margin:0"><a href="/our-stores">our stores</a></h1></li>
					<li><a href="/made-in-usa">made in usa</a></li>
					<li><a href="/principles-of-yoga">principles of yoga</a></li>
					<li><a href="/namaskar">namaskÁr foundation</a></li>
					<li><a href="/press" class="current">press</a></li>
				</ul>
			</div>
			<!-- leftNavigation -->
		</div>
		<!-- BlockLeft -->


		<!-- BlockTwo -->
		<div style="background:#f7e8eb;" class="block30 bgf7e8eb pressBlock">
			<a target="_blank" href="http://bostinno.streetwise.co/2015/11/06/boston-yoga-yogasmoga-apparel-opens-in-the-pru-november-16/">
				<!-- contentPart -->
				<div class="textContainer">
					<div class="pressHead">
						BOSTINNO
					</div>
					<div class="presstxt">
						<p> Mass.–Made Yoga<br />  Apparel Co. Yogasmoga <br /> Opens in the Pru<span>11/06/2015</span></p>

					</div>
				</div>
				<!-- contentPart -->
			</a>
		</div>
		<!-- BlockTwo -->

		<!-- BlockLeft -->
		<div style="background:#99174C;" class="block30 bg5DC1B3 pressBlock">
			<a target="_blank" href="http://www.huffingtonpost.com/laura-dunn/women-in-business-qa-tapa_b_8060760.html?ir=India&adsSiteOverride=in&m=true">
				<!-- contentPart -->
				<div class="textContainer">
					<div class="pressHead">
						HUFFINGTON POST
					</div>
					<div class="presstxt">
						<p>  Women in Business<br />Q&amp;A: Tapasya Bali<span>8/31/2015</span></p>

					</div>
				</div>
				<!-- contentPart -->
			</a>
		</div>
		<!-- BlockLeft -->



	</div>
	<!-- gridBlockOne -->

	<!-- gridBlockTwo -->
	<div class="gridFullWidth">

		<!-- BlockLeft -->
		<div class="block33 pressBlock">
			<!-- CMSheadingBlock -->
			<div class="headingBlock minh250">
				<h1 class="positionAbs">Press</h1>
			</div>
			<!-- CMSheadingBlock -->
		</div>
		<!-- BlockLeft -->

		<!-- BlockLeft -->
		<div style="background:#5DC1B3;" class="block30 bg5DC1B3 pressBlock">
			<a target="_blank" href="http://www.bloomberg.com/news/articles/2015-04-27/yoga-wars-what-a-lululemon-challenger-from-goldman-sachs-means-for-retail">
				<!-- contentPart -->
				<div class="textContainer">
					<div class="pressHead">
						BLOOMBERG
					</div>
					<div class="presstxt">
						<p> YOGA WARS:<br />What a Lululemon challenger from
							Goldman Sachs means for retail<span>04/27/2015</span></p>

					</div>
				</div>
				<!-- contentPart -->
			</a>
		</div>
		<!-- BlockLeft -->

		<!-- BlockTwo -->
		<div class="block30 bg6B6951 pressBlock" style="background:#6B6951">
			<a target="_blank" href="http://www.businessinsider.com/yogasmoga-raises-65-million-at-a-74-million-valuation-2015-4">
				<!-- contentPart -->
				<div class="textContainer">
					<div class="pressHead">
						BUSINESS INSIDER
					</div>
					<div class="presstxt">
						<p>YOGASMOGA <br />  wants to bring authenticity back to the culture of yoga.<span>04/02/2015</span></p>
					</div>
				</div>
				<!-- contentPart -->
			</a>
		</div>
		<!-- BlockTwo -->


	</div>
	<!-- gridBlockTwo -->

	<!-- gridBlockThree -->
	<div class="gridFullWidth">

		<!-- BlockTthree -->
		<div class="block30 bg67335a pressBlock">
			<a target="_blank" href="http://wellandgood.com/2015/03/29/yogasmoga-activewear-become-the-next-lululemon/">
				<!-- contentPart -->
				<div class="textContainer">
					<div class="pressHead">
						well+good
					</div>
					<div class="presstxt">
						<p>The activewear company<br/> that’s going to be compared to Lululemon<span>03/29/2015</span></p>
					</div>
				</div>
				<!-- contentPart -->
			</a>
		</div>
		<!-- BlockThree -->

		<!-- BlockThree -->
		<div class="block30 bgc5218c pressBlock">
			<a target="_blank" href="http://www.cnbc.com/id/102425705">
				<!-- contentPart -->
				<div class="textContainer">
					<div class="pressHead">
						CNBC<br />
					</div>
					<div class="presstxt">
						<p>Escaping The Cube<br /><span>02/13/2015</span></p>
					</div>
				</div>
				<!-- contentPart -->
			</a>
		</div>
		<!-- BlockThree -->

		<!-- BlockTwo -->
		<div class="block30 bg5744a8 pressBlock">
			<a target="_blank" href="http://finance.yahoo.com/news/yogasmoga-releases-proprietary-fabric-technology-141700438.html;_ylt=AwrBJR6RiPJT1W4A9AyTmYlQ">
				<!-- contentPart -->
				<div class="textContainer">
					<div class="pressHead">
						YAHOO!<br />FINANCE
					</div>
					<div class="presstxt">
						<p>YOGASMOGA&reg; RELEASES<br />NEW PROPRIETARY FABRIC<br />TECHNOLOGY: AIRH&trade;<span>08/05/2014</span></p>
					</div>
				</div>
				<!-- contentPart -->
			</a>
		</div>
		<!-- BlockTwo -->





	</div>
	<!-- gridBlockThree -->

	<!-- gridBlockFour -->
	<div class="gridFullWidth">


		<!-- BlockThree -->
		<div class="block30 bg1266ac pressBlock">
			<a target="_blank" href="http://upstart.bizjournals.com/resources/executive-forum/2014/07/03/why-an-india-born-entrepreneur-sells-made-in-the.html?page=all">
				<!-- contentPart -->
				<div class="textContainer">
					<div class="pressHead">
						UPSTART
					</div>
					<div class="presstxt">
						<p>WHY AN INDIA-BORN ENTREPRENEUR<br />SELLS MADE IN THE USA<br />YOGA WEAR<span>06/12/2014</span></p>
					</div>
				</div>
				<!-- contentPart -->
			</a>
		</div>
		<!-- BlockThree -->


		<!-- BlockLeft -->
		<div class="block30 bgc3262c pressBlock">
			<a target="_blank" href="http://www.greenwichfreepress.com/tag/yogasmoga/">
				<!-- contentPart -->
				<div class="textContainer">
					<div class="pressHead">
						GREENWICH!<br />FREE PRESS
					</div>
					<div class="presstxt">
						<p>IT'S A STORE. IT'S A LIFESTYLE.<br />YOGASMOGA RENOVATES<br />68 GREENWICH AVE<span>06/12/2014</span></p>
					</div>
				</div>
				<!-- contentPart -->
			</a>
		</div>
		<!-- BlockLeft -->

		<!-- BlockTwo -->
		<div class="block30 bg5744a8 pressBlock">
			<a target="_blank" href="http://finance.yahoo.com/news/yogasmoga-announces-growth-physical-retail-150000281.html">
				<!-- contentPart -->
				<div class="textContainer">
					<div class="pressHead">
						YAHOO!<br />FINANCE
					</div>
					<div class="presstxt">
						<p>YOGASMOGA&reg; ANNOUNCES<br />GROWTH INTO<br />PHYSICAL RETAIL STORES<span>06/12/2014</span></p>
					</div>
				</div>
				<!-- contentPart -->
			</a>
		</div>
		<!-- BlockTwo -->




	</div>
	<!-- gridBlockThree -->
	<div class="gridFullWidth">

		<!-- BlockThree -->
		<div class="block30 bg67335a pressBlock">
			<a target="_blank" href="http://wellandgood.com/2014/05/14/yoga-pants-not-just-for-women/">
				<!-- contentPart -->
				<div class="textContainer">
					<div class="pressHead">
						well+good
					</div>
					<div class="presstxt">
						<p>yoga pants:<br />NOT JUST FOR WOMEN<span>05/14/2014</span></p>
					</div>
				</div>
				<!-- contentPart -->
			</a>
		</div>
		<!-- BlockThree -->

		<!-- BlockLeft -->
			<div style="background:#5DC1B3;" class="block30 bg5DC1B3 pressBlock">
			<a target="_blank" href="http://www.bloomberg.com/news/videos/b/ff5d8da1-44b8-48bd-8a3b-e690334b67a6">
				<!-- contentPart -->
				<div class="textContainer">
					<div class="pressHead">
						BLOOMBERG
					</div>
					<div class="presstxt">
						<p>From Goldman Derivatives<br />to Downward-Facing Dog<span>04/14/2014</span></p>

					</div>
				</div>
				<!-- contentPart -->
			</a>
		</div>
		<!-- BlockLeft -->

		<!-- BlockTwo -->
		<div class="block30 bgc5218c pressBlock">
			<a target="_blank" href="http://www.self.com/flash/fitness-blog/2014/03/fitness-yoga-smoga/">
				<!-- contentPart -->
				<div class="textContainer">
					<div class="pressHead">
						self
					</div>
					<div class="presstxt">
						<p>CHECK OUT  YOGASMOGA,<br />THE  SELFIEST YOGA BRAND<br />WE'vE EVER SEEN<span>03/19/2014</span></p>
					</div>
				</div>
				<!-- contentPart -->
			</a>
		</div>
		<!-- BlockTwo -->


	</div>
	<div class="gridFullWidth">
		<!-- BlockTwo -->
		<div class="block30 bg67335a pressBlock">
			<a target="_blank" href="http://wellandgood.com/2013/10/21/the-ultimate-guide-to-yoga-pants/">
				<!-- contentPart -->
				<div class="textContainer">
					<div class="pressHead">
						well+good
					</div>
					<div class="presstxt">
						<p>THE ULTIMATE GUIDE<br />TO YOGA PANTS<span>0/21/2013</span></p>
					</div>
				</div>
				<!-- contentPart -->
			</a>
		</div>
		<!-- BlockTwo -->


		<!-- BlockThree -->
		<div class="block30 bg323f48 pressBlock">
			<a target="_blank" href="http://q.equinox.com/articles/2013/02/yogasmoga">
				<!-- contentPart -->
				<div class="textContainer">
					<div class="pressHead">
						EQUINOX
					</div>
					<div class="presstxt">
						<p>YOGASMOGA IS NOT<br />YOUR AVERAGE GYM WEAR<span>02/14/2013</span></p>
					</div>
				</div>
				<!-- contentPart -->
			</a>
		</div>
		<!-- BlockThree -->

		<!-- BlockLeft -->
		<div class="block30 bg67335a pressBlock">
			<a target="_blank" href="http://wellandgood.com/2013/02/14/a-hot-new-yoga-fashion-brand-launches-with-indian-roots-and-modern-flair/">
				<!-- contentPart -->
				<div class="textContainer">
					<div class="pressHead">
						well+good
					</div>
					<div class="presstxt">
						<p>A HOT NEW YOGA FASHION BRAND<br />LAUNCHES WITH INDIAN ROOTS<br />AND MODERN FLAIR<span>02/14/2013</span></p>
					</div>
				</div>
				<!-- contentPart -->
			</a>
		</div>
	
	</div>
	<div class="gridFullWidth">
		<!-- BlockTwo -->
		<div class="block30 bg288788 pressBlock">
			<a target="_blank" href="http://www.theblogstudio.com/2013/04/1604/">
				<!-- contentPart -->
				<div class="textContainer">
					<div class="pressHead">
						THE BLOG<br />STUDIO
					</div>
					<div class="presstxt">
						<p>A NEW BRAND THAT<br />WE CAN GET BEHIND: YOGASMOGA<span>02/10/2013</span></p>
					</div>
				</div>
				<!-- contentPart -->
			</a>
		</div>
		<!-- BlockTwo -->


		<!-- BlockThree -->
		
	
	</div>
	<!-- bottomDivider -->
	<div class="bottomdivider"></div>
	<!-- bottomDivider -->

</div>
<!-- endCMSPages -->