<div class="namaskar-overlay1">&nbsp;</div>
<script type="text/javascript">
	jQuery(window).load(function(){
		jQuery('body').css('overflow','auto');
		jQuery('.namaskar-overlay1').fadeOut('slow');
	})
</script>
<div class="gridCMSPages pressPage">
	<!-- gridBlockOne -->
	<div class="gridFullWidth">
		<!-- BlockLeft -->
		<div class="block33">
			<!-- leftNavigation -->
			<div class="cmsNavigation minh250">
				<ul>
					<li><a href="/our-story">our story</a></li>
					<li><a href="/our-core-values">our core values</a></li>
					<li><a href="/our-ethics">our ethics</a></li>
					<!--<li><a href="/our-stores">our stores</a></li>-->
					<li><a href="/made-in-usa">made in usa</a></li>
					<li><a href="/principles-of-yoga">principles of yoga</a></li>
					<li><a href="/namaskar">namaskÁr foundation</a></li>
					<li><a href="/press" class="current">press</a></li>
				</ul>
			</div>
			<!-- leftNavigation -->
		</div>
		<!-- BlockLeft -->


		<!-- BlockTwo -->
		<div style="background:#46c655;" class="block30 bgf7e8eb pressBlock">
			<a target="_blank" href="http://www.wellandgood.com/good-looks/yogasmoga-activewear-growth/">
				<!-- contentPart -->
				<div class="textContainer">
					<div class="pressHead">
						well+good
					</div>
					<div class="presstxt">
						<p> Yogasmoga is showing Signs of becoming A Major Fitness Fashion Force<span>02/26/2016</span></p>

					</div>
				</div>
				<!-- contentPart -->
			</a>
		</div>
		<!-- BlockTwo -->

		<!-- BlockLeft -->
		<div style="background:#602b85;" class="block30 bg5DC1B3 pressBlock">
			<a target="_blank" href="http://ny.racked.com/2016/2/8/10938774/yogasmoga-nyc-store-2016">
				<!-- contentPart -->
				<div class="textContainer">
					<div class="pressHead">
						RACKED NEW YORK
					</div>
					<div class="presstxt">
						<p> Yogasmoga Will Open Its first NYC store this spring<span>02/08/2016</span></p>

					</div>
				</div>
				<!-- contentPart -->
			</a>
		</div>
		<!-- BlockLeft -->



	</div>
	<!-- gridBlockOne -->

	<!-- gridBlockTwo -->
	<div class="gridFullWidth">

		<!-- BlockLeft -->
		<div class="block33 pressBlock">
			<!-- CMSheadingBlock -->
			<div class="headingBlock minh250">
				<div class="positionAbs h1">Press</div>
				<h1 style="display:none">YOGASMOGA in the Press</h1>
			</div>
			<!-- CMSheadingBlock -->
		</div>
		<!-- BlockLeft -->

		<!-- BlockLeft -->
		<div style="background:#c4218c;" class="block30 bgc5218c pressBlock">
			<a target="_blank" href="http://wwd.com/retail-news/specialty-stores/yogasmoga-makes-move-on-manhattan-10346750/print-preview/">
				<!-- contentPart -->
				<div class="textContainer">
					<div class="pressHead">
						WWD
					</div>
					<div class="presstxt">
						<p> Yogasmoga makes Its move on Manhattan<span>02/11/2016</span></p>

					</div>
				</div>
				<!-- contentPart -->
			</a>
		</div>
		<!-- BlockLeft -->

		<!-- BlockTwo -->
		<div class="block30 bg6B6951 pressBlock" style="background:#005476;">
			<a target="_blank" href="http://www.chainstoreage.com/article/fast-growing-lululemon-rival-open-its-first-nyc-store">
				<!-- contentPart -->
				<div class="textContainer">
					<div class="pressHead">
						Chain Store Age
					</div>
					<div class="presstxt">
						<p>Fast-Growing Lululemon Rival to open Its first NYC Store<span>02/08/2016</span></p>
					</div>
				</div>
				<!-- contentPart -->
			</a>
		</div>
		<!-- BlockTwo -->


	</div>
	<!-- gridBlockTwo -->

	<!-- gridBlockThree -->
	<div class="gridFullWidth">

		<!-- BlockTthree -->
		<div class="block30 bg67335a pressBlock" style="background:#ff7630;">
			<a target="_blank" href="http://www.latimes.com/health/la-he-fitness-fashion-html-20150903-htmlstory.html">
				<!-- contentPart -->
				<div class="textContainer">
					<div class="pressHead">
						LA TIMES
					</div>
					<div class="presstxt">
						<p>Photos: The Hottest L.A. Trend In Fashion? Fitness Clothing<span>09/04/2015</span></p>
					</div>
				</div>
				<!-- contentPart -->
			</a>
		</div>
		<!-- BlockThree -->

		<!-- BlockThree -->
		<div class="block30 bgc5218c pressBlock" style="background:#9a174d;">
			<a target="_blank" href="http://www.huffingtonpost.com/laura-dunn/women-in-business-qa-tapa_b_8060760.html">
				<!-- contentPart -->
				<div class="textContainer">
					<div class="pressHead">
						HUFFINGTON POST<br />
					</div>
					<div class="presstxt">
						<p>Women in Business<br/> Q&A: Tapasya Bali<span>08/31/2015</span></p>
					</div>
				</div>
				<!-- contentPart -->
			</a>
		</div>
		<!-- BlockThree -->

		<!-- BlockTwo -->
		<div class="block30 bg5744a8 pressBlock" style="background:#2bc8d0;">
			<a target="_blank" href="http://www.bloomberg.com/news/articles/2015-04-27/yoga-wars-what-a-lululemon-challenger-from-goldman-sachs-means-for-retail">
				<!-- contentPart -->
				<div class="textContainer">
					<div class="pressHead">
						BLOOMBERG
					</div>
					<div class="presstxt">
						<p>YOGA WARS: What a Lululemon Challenger From Goldman Sachs Means For Retail<span>04/27/2015</span></p>
					</div>
				</div>
				<!-- contentPart -->
			</a>
		</div>
		<!-- BlockTwo -->





	</div>
	<!-- gridBlockThree -->

	<!-- gridBlockFour -->
	<div class="gridFullWidth">


		<!-- BlockThree -->
		<div class="block30 bg1266ac pressBlock" style="background:#1f4948;">
			<a target="_blank" href="http://www.businessinsider.in/A-startup-that-wants-to-kill-Lululemon-just-raised-6-5-million-at-a-74-million-valuation/articleshow/46787005.cms">
				<!-- contentPart -->
				<div class="textContainer">
					<div class="pressHead">
						BUSINESS INSIDER
					</div>
					<div class="presstxt">
						<p>YOGASMOGA wants to bring authenticity back to the culture of yoga.<span>04/02/2015</span></p>
					</div>
				</div>
				<!-- contentPart -->
			</a>
		</div>
		<!-- BlockThree -->


		<!-- BlockLeft -->
		<div class="block30 bgc3262c pressBlock" style="background:#46c655;">
			<a target="_blank" href="http://www.wellandgood.com/good-sweat/yogasmoga-activewear-become-the-next-lululemon/">
				<!-- contentPart -->
				<div class="textContainer">
					<div class="pressHead">
						well+good
					</div>
					<div class="presstxt">
						<p>The activewear company that’s going to be compared to Lululemon<span>03/29/2015</span></p>
					</div>
				</div>
				<!-- contentPart -->
			</a>
		</div>
		<!-- BlockLeft -->

		<!-- BlockTwo -->
		<div class="block30 bg5744a8 pressBlock" style="background:#c4218c;">
			<a target="_blank" href="http://www.cnbc.com/2015/02/17/starting-a-business-that-runs-in-their-blood.html">
				<!-- contentPart -->
				<div class="textContainer">
					<div class="pressHead">
						CNBC<br />
					</div>
					<div class="presstxt">
						<p>Escaping The Cube<br/><span>02/13/2015</span></p>
					</div>
				</div>
				<!-- contentPart -->
			</a>
		</div>
		<!-- BlockTwo -->




	</div>
	<!-- gridBlockThree -->
	<div class="gridFullWidth">

		<!-- BlockThree -->
		<div class="block30 bg67335a pressBlock" style="background:#268b25">
			<a target="_blank" href="http://www.greenwichtime.com/business/article/New-yoga-store-on-Greenwich-Ave-aims-to-be-more-5756999.php#photo-6856137)">
				<!-- contentPart -->
				<div class="textContainer">
					<div class="pressHead">
						GREENWICH TIME
					</div>
					<div class="presstxt">
						<p>New Yoga Store on Greenwich Ave<br/>Aims to Be &#8216;More Than Black Pants&#8217;<span>09/15/2014</span></p>
					</div>
				</div>
				<!-- contentPart -->
			</a>
		</div>
		<!-- BlockThree -->

		<!-- BlockLeft -->
			<div style="background:#1c57cb;" class="block30 bg5DC1B3 pressBlock">
			<a target="_blank" href="http://upstart.bizjournals.com/resources/executive-forum/2014/07/03/why-an-india-born-entrepreneur-sells-made-in-the.html?page=all">
				<!-- contentPart -->
				<div class="textContainer">
					<div class="pressHead">
						UPSTART
					</div>
					<div class="presstxt">
						<p>Why an India-Born Entrepreneur Sells Made in the USA Yoga Wear<span>06/12/2014</span></p>

					</div>
				</div>
				<!-- contentPart -->
			</a>
		</div>
		<!-- BlockLeft -->

		<!-- BlockTwo -->
		<div class="block30 bgc5218c pressBlock" style="background:#46c655;">
			<a target="_blank" href="http://www.wellandgood.com/good-advice/yoga-pants-not-just-for-women/">
				<!-- contentPart -->
				<div class="textContainer">
					<div class="pressHead">
						well+good
					</div>
					<div class="presstxt">
						<p>yoga pants: NOT JUST FOR WOMEN<span>05/14/2014</span></p>
					</div>
				</div>
				<!-- contentPart -->
			</a>
		</div>
		<!-- BlockTwo -->


	</div>
	<div class="gridFullWidth">
		<!-- BlockTwo -->
		<div class="block30 bg67335a pressBlock" style="background:#2bc8d0;">
			<a target="_blank" href="http://www.bloomberg.com/news/videos/b/ff5d8da1-44b8-48bd-8a3b-e690334b67a6">
				<!-- contentPart -->
				<div class="textContainer">
					<div class="pressHead">
						BLOOMBERG
					</div>
					<div class="presstxt">
						<p>From Goldman Derivatives<br/>to Downward-Facing Dog<span>04/14/2014</span></p>

					</div>
				</div>
				<!-- contentPart -->
			</a>
		</div>
		<!-- BlockTwo -->


		<!-- BlockThree -->
		<div class="block30 bg323f48 pressBlock" style="background:#c4218c;">
			<a target="_blank" href="http://www.self.com/flash/fitness-blog/2014/03/fitness-yoga-smoga/">
				<!-- contentPart -->
				<div class="textContainer">
					<div class="pressHead">
						self
					</div>
					<div class="presstxt">
						<p>CHECK OUT YOGASMOGA, THE SELFIEST YOGA BRAND WE&#8217;vE EVER SEEN<span>03/19/2014</span></p>
					</div>
				</div>
				<!-- contentPart -->
			</a>
		</div>
		<!-- BlockThree -->

		<!-- BlockLeft -->
		<div class="block30 bg67335a pressBlock" style="background:#46c655;">
			<a target="_blank" href="http://www.wellandgood.com/good-looks/the-ultimate-guide-to-yoga-pants/">
				<!-- contentPart -->
				<div class="textContainer">
					<div class="pressHead">
						well+good
					</div>
					<div class="presstxt">
						<p>THE ULTIMATE GUIDE<br/>TO YOGA PANTS<span>10/21/2013</span></p>
					</div>
				</div>
				<!-- contentPart -->
			</a>
		</div>
	
	</div>
	<div class="gridFullWidth">
		<!-- BlockTwo -->
		<!--<div class="block30 bg67335a pressBlock" style="background:#005476;">
			<a target="_blank" href="#">
				<!-- contentPart 
				<div class="textContainer">
					<div class="pressHead">
						EQUINOX
					</div>
					<div class="presstxt">
						<p>YOGASMOGA IS NOT YOUR AVERAGE GYM WEAR<span>02/14/2013</span></p>
					</div>
				</div>
				<!-- contentPart 
			</a>
		</div>-->
		<!-- BlockTwo -->


		<!-- BlockThree -->
		<div class="block30 bg323f48 pressBlock" style="background:#46c655;">
			<a target="_blank" href="http://wellandgood.com/2013/02/14/a-hot-new-yoga-fashion-brand-launches-with-indian-roots-and-modern-flair/">
				<!-- contentPart -->
				<div class="textContainer">
					<div class="pressHead">
						well+good
					</div>
					<div class="presstxt">
						<p>A HOT NEW YOGA FASHION BRAND LAUNCHES WITH INDIAN ROOTS AND MODERN FLAIR<span>02/14/2013</span></p>
					</div>
				</div>
				<!-- contentPart -->
			</a>
		</div>
		<!-- BlockThree -->

		<!-- BlockLeft -->
		<div class="block30 bg67335a pressBlock" style="background:#ff7630;">
			<a target="_blank" href="http://www.theblogstudio.com/2013/04/1604/">
				<!-- contentPart -->
				<div class="textContainer">
					<div class="pressHead">
						THE BLOG STUDIO
					</div>
					<div class="presstxt">
						<p>A NEW BRAND THAT WE CAN GET BEHIND: YOGASMOGA<span>02/10/2013</span></p>
					</div>
				</div>
				<!-- contentPart -->
			</a>
		</div>
	
	</div>
	<!-- bottomDivider -->
	<div class="bottomdivider"></div>
	<!-- bottomDivider -->

</div>
<!-- endCMSPages -->
<style>
.presstxt p{padding:0 4%;}
</style>