<form action="" method="post" id="share-smogi" style="display: block;">
    <p class="signup-title" style="margin: 10px 0px">
        <strong style="text-transform: uppercase">Share Smogi Email</strong>
    </p>
    <!--<small>Your Email Address</small>-->
    <p><input type="text" style="width:225px;padding:8px 10px;"  name="share_smogi_email" id="smogi_email_address" class="watermark" placeholder="Email Address" autocomplete="off" value="" class="requiredfield" defaulterrormsg="Email Address is required" autocapitalize="off"/></p>
    <p class="button-area">
        <input type="submit"  style="width:175px;padding:8px 15px;background:#5ec52f;border:1px solid #eee" value="Share" id="share-button-mailc"/>
    </p>

    <p style="margin: 0px auto; font-size: 12px; visibility: hidden; min-height: 20px; width: 236px;" id="err-msg">All fields are required.</p>
    <p class="thanks" style="display:none;"></p>
</form>

<script type="application/javascript">
    jQuery(document).ready(function($){

        $("#share-smogi").submit(function(event){
            event.preventDefault();

            $("#err-msg").css("visibility","hidden");

            var formid = "#share-smogi";
            var email_id = $.trim($("#smogi_email_address").val());

            if(email_id == "" || email_id == "Email Address")
            {
                event.preventDefault();
                $("#err-msg").css("visibility","visible");
                $("#err-msg").text("Please enter an email address.");
                return;
            }
            if(!validateEmail(email_id)){
                event.preventDefault();
                $("#err-msg").css("visibility","visible");
                $("#err-msg").text("Enter a valid email.");
                return;
            }

            if(window.location.href.indexOf('https://') >= 0)
                _usesecureurl = true;
            else
                _usesecureurl = false;
            var url = homeUrl + 'share_smogibucks.php';
            if(_usesecureurl){
                url = securehomeUrl + 'share_smogibucks.php';
            }


            jQuery.ajax({
                url     :   url,
                type    :   'POST',
                data    :   {'email':email_id},
                beforeSend: function() {

                    jQuery("#share-smogi #share-button-mailc").attr('value',"SHARING UP...");


                },
                success: function (data) {
                    //alert(data);
                    data = eval('(' + data + ')');
                    var status = data.status;



                    if (status == "success") {
                       // jQuery("#share-smogi").parent().hide();
                        jQuery("#share-smogi #share-button-mailc").attr("value","Share");
                        jQuery(".thanks").html("Thank you for sharing.")
                        jQuery(".thanks").show();
                    }
                    else
                    {
                        jQuery("#share-button-mailc").val("share");
                        jQuery("#share-button-mailc").show();
                        jQuery("#share-smogi #err-msg").html(data.error).css("visibility","visible");
                    }
                }
            });
        });
    });
</script>