<div class="namaskar-overlay1">&nbsp;</div>
<script type="text/javascript">
    jQuery(window).load(function(){
        jQuery('body').css('overflow','auto');
        jQuery('.namaskar-overlay1').fadeOut('slow');
    });
	
	jQuery(document).ready(function(){
		var colorblockW = jQuery('.ysdiscover-colors .colorFilterGrid a').width();
		var colorblockH = 86.324 * colorblockW/100;
		jQuery('.ysdiscover-colors .colorFilterGrid a').height(colorblockH);
	});	
	jQuery(window).resize(function(){
		var colorblockW = jQuery('.ysdiscover-colors .colorFilterGrid a').width();
		var colorblockH = 86.324 * colorblockW/100;
		jQuery('.ysdiscover-colors .colorFilterGrid a').height(colorblockH);
	});
</script>
<!-- startCMSPages -->
<div class="gridCMSPages">
	

<!-- gridBlockOne -->
	<div class="gridFullWidth ystopsection">
		<!-- BlockLeft -->
		<div class="block33">
			<!-- leftNavigation -->
			<div class="cmsNavigation">
				<ul>
					<li><a href="/ys-fabric-tech">YS Fabric Tech</a></li>
					<li><a href="/ys-color-tech" class="current">Ys Color Tech</a></li>
					<li><a href="/design-elements">YS Design Elements</a></li>
				</ul>
			</div>
			<!-- leftNavigation -->

			<!-- CMSheadingBlock -->
			<div class="headingBlock">
				<h1 class="positionAbs">YS Color<br />Tech</h1>
			</div>
			<!-- CMSheadingBlock -->
		</div>
		<!-- BlockLeft -->

		<!-- BlockRight -->
		<div class="block66 posRel">
			<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/ct-banner.jpg" alt="" class="img-responsive" />
			<div class="positionAbs" id="ysbannertxt" style="top:32.4%">
				<span class="topHead">Ys Color Tech</span>
				<h4>
					True colors
					<span class="smallHead">FOR TODAY & TOMORROW</span>
				</h4>
				<!--a href="javascript:void(0)" class="linkheader white" id="discoverColor">Discover Our Colors</a-->
			</div>

		</div>
		<!-- BlockRight -->
	</div>
	<!-- gridBlockOne -->
	<!-- gridBlockFour -->
	<div class="gridFullWidth ysdiscover-colors title-block">
		<a name="discoverColor"></a>
		<!-- BlockOne -->
		<div class="block100">
			<!-- contentPart -->
			<div class="textContainer">
				<strong>DISCOVER OUR Colors</strong>
			</div>
			<!-- contentPart -->
		</div>
		<!-- BlockOne -->
		
	</div>
	<!-- gridBlockFour -->

	<!-- gridBlockFive -->
	<div class="gridFullWidth ysdiscover-colors">
		<div class="colorFilterGrid">
			<a href="<?php echo Mage::getBaseUrl()?>catalogsearch/result/?q=ys+gold" class="ys-gold"><span>ys gold</span></a>
			<a href="<?php echo Mage::getBaseUrl()?>catalogsearch/result/?q=corallion" class="corallion">
				<span>
					<span class="text-shop">Shop</span>
					CORALLION
				</span>
				<span class="spn_hover">				
					<img src="<?php echo $this->getSkinUrl('images/colorgrid/corallion.png') ?>" alt=""/>
				</span>	
			</a>
			<a href="<?php echo Mage::getBaseUrl()?>crimson-rose" class="crimson-rose">
				<span>
					<span  class="text-shop">Shop</span>
					CRIMSON<br />rose
				</span>
				<span class="spn_hover">
					<img src="<?php echo $this->getSkinUrl('images/colorgrid/crimson-rose.png') ?>" alt=""/>
				</span>	
			</a>
			<a href="<?php echo Mage::getBaseUrl()?>catalogsearch/result/?q=vermelho" class="vermelho">
				<span>
					<span  class="text-shop">Shop</span>
					VERMELHO
				</span>
				<span class="spn_hover">
					<img src="<?php echo $this->getSkinUrl('images/colorgrid/vermelho.png') ?>" alt=""/>
				</span>	
			</a>
			<a href="<?php echo Mage::getBaseUrl()?>klarit-red" class="klarit-red">
				<span>
					<span  class="text-shop">Shop</span>
					KLARIT RED
				</span>
				<span class="spn_hover">
					<img src="<?php echo $this->getSkinUrl('images/colorgrid/klarit-red.png') ?>" alt=""/>
				</span>	
			</a>
			<a href="<?php echo Mage::getBaseUrl()?>catalogsearch/result/?q=tickled+pink" class="tickled-pink">
				<span>
					<span  class="text-shop">Shop</span>
					TICKLED<br />pink
				</span>
				<span class="spn_hover">
					<img src="<?php echo $this->getSkinUrl('images/colorgrid/tickled-pink.png') ?>" alt=""/>
				</span>	
			</a>
			<a href="<?php echo Mage::getBaseUrl()?>catalogsearch/result/?q=violet+twilight" class="violet-twilight">
				<span>
					<span  class="text-shop">Shop</span>
					violet<br/> twilght
				</span>
				<span class="spn_hover">
					<img src="<?php echo $this->getSkinUrl('images/colorgrid/violet-twilight.png') ?>" alt=""/>
				</span>	
			</a>
			<a href="<?php echo Mage::getBaseUrl()?>catalogsearch/result/?q=seattle+mist" class="seattle-mist">
				<span>
					<span  class="text-shop">Shop</span>
					seattle<br /> mist
				</span>
				<span class="spn_hover">
					<img src="<?php echo $this->getSkinUrl('images/colorgrid/seattle-mist.png') ?>" alt=""/>
				</span>	
			</a>
			<a href="<?php echo Mage::getBaseUrl()?>catalogsearch/result/?q=shangri+la" class="shangri-la">
				<span>
					<span  class="text-shop">Shop</span>
					shangri-la
				</span>
				<span class="spn_hover">
					<img src="<?php echo $this->getSkinUrl('images/colorgrid/shangri-la.png') ?>" alt=""/>
				</span>	
			</a>
			<a href="<?php echo Mage::getBaseUrl()?>catalogsearch/result/?q=boy+blue" class="boy-blue">
				<span>
					<span  class="text-shop">Shop</span>
					boy blue
				</span>
				<span class="spn_hover">
					<img src="<?php echo $this->getSkinUrl('images/colorgrid/boy-blue.png') ?>" alt=""/>
				</span>	
			</a>
			<a href="<?php echo Mage::getBaseUrl()?>catalogsearch/result/?q=jodhpur+blue" class="jodhpur-blue">
				<span>
					<span  class="text-shop">Shop</span>
					jodhpur<br/> blue
				</span>
				<span class="spn_hover">
					<img src="<?php echo $this->getSkinUrl('images/colorgrid/jodhpur.png') ?>" alt=""/>
				</span>	
			</a>
			<a href="<?php echo Mage::getBaseUrl()?>catalogsearch/result/?q=india+blue" class="india-blue">
				<span>
					<span  class="text-shop">Shop</span>
					india<br/> blue
				</span>
				<span class="spn_hover">
					<img src="<?php echo $this->getSkinUrl('images/colorgrid/india-blue.png') ?>" alt=""/>
				</span>	
			</a>
			<a href="<?php echo Mage::getBaseUrl()?>midnight-blue" class="midnight-blue">
				<span>
					<span  class="text-shop">Shop</span>
					midnight<br/> blue
				</span>
				<span class="spn_hover">
					<img src="<?php echo $this->getSkinUrl('images/colorgrid/midnight-blue.png') ?>" alt=""/>
				</span>	
			</a>
			<a href="<?php echo Mage::getBaseUrl()?>verdi" class="verdi">
				<span>
					<span  class="text-shop">Shop</span>
					verdi
				</span>
				<span class="spn_hover">
					<img src="<?php echo $this->getSkinUrl('images/colorgrid/verdi.png') ?>" alt=""/>
				</span>	
			</a>
			<a href="<?php echo Mage::getBaseUrl()?>catalogsearch/result/?q=lime+lite" class="lime-lite">
				<span>
					<span  class="text-shop">Shop</span>
					lime lite
				</span>
				<span class="spn_hover">
					<img src="<?php echo $this->getSkinUrl('images/colorgrid/lime-light.png') ?>" alt=""/>
				</span>	
			</a>
			<a href="<?php echo Mage::getBaseUrl()?>spanish-grey" class="spanish-grey">
				<span>
					<span  class="text-shop">Shop</span>
					spanish<br/> grey
				</span>
				<span class="spn_hover">
					<img src="<?php echo $this->getSkinUrl('images/colorgrid/spanish-grey.png') ?>" alt=""/>
				</span>	
			</a>
			<a href="<?php echo Mage::getBaseUrl()?>grey-caviar" class="grey-caviar">
				<span>
					<span  class="text-shop">Shop</span>
					grey<br/> caviar
				</span>
				<span class="spn_hover">
					<img src="<?php echo $this->getSkinUrl('images/colorgrid/grey-caviar.png') ?>" alt=""/>
				</span>	
			</a>
			<a href="<?php echo Mage::getBaseUrl()?>catalogsearch/result/?q=carbon+6" class="carbon6">
				<span>
					<span  class="text-shop">Shop</span>
					carbon 6
				</span>
				<span class="spn_hover">
					<img src="<?php echo $this->getSkinUrl('images/colorgrid/carbon-6.png') ?>" alt=""/>
				</span>
			</a>
		</div>
		
	</div>
	<!-- gridBlockFive -->
	<!-- gridBlockTwo -->
	<div class="gridFullWidth marginbottom50">
		<!-- BlockOne -->
		<div class="block30">
			<!-- contentPart -->
			<div class="textContainer">
				<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/ct-friendly.jpg" alt="" class="img-responsive" />
				<div class="iconBlock">
					<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/Icon-Color-EcoDye.png" alt="" />
				</div>
				<div class="cntntheading">
					ECO-FRIENDLY DYEING
				</div>
				<div class="contnttxt">
					<p>While the best black is the YOGASMOGA Carbon 6 -a color that never fades, a true Yogi knows the new black must also come from a dye that does not pollute our waterways. We do not use any harmful formaldehyde based dyes that can seep into our groundwater.</p>
				</div>
			</div>
			<!-- contentPart -->
		</div>
		<!-- BlockOne -->

		<!-- BlockTwo -->
		<div class="block30">
			<!-- contentPart -->
			<div class="textContainer">
				<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/ct-colors.jpg" alt="" class="img-responsive" />
				<div class="iconBlock">
					<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/Icon-Color-Accuracy.png" alt="" />
				</div>
				<div class="cntntheading">
					COLORS THAT WON't Bleed
				</div>
				<div class="contnttxt">
					<p>We put our colors through multiple rounds of rigorous testing for each lot of fabric so we can prevent even minimal color bleed. All you need to worry about is how to style your deep, beautiful and saturated colors.</p>
				</div>
			</div>
			<!-- contentPart -->
		</div>
		<!-- BlockTwo -->

		<!-- BlockThree -->
		<div class="block30">
			<!-- contentPart -->
			<div class="textContainer">
				<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/ct-fade.jpg" alt="" class="img-responsive" />
				<div class="iconBlock">
					<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/Icon-Color-USAdye.png" alt="" />
				</div>
				<div class="cntntheading">
					COLORS THAT WON'T Fade
				</div>
				<div class="contnttxt">
					<p>Color – it highlights your assets, brightens your mood. And we want that to last. But ever so often, colors fade so quickly – just ask our competitors. That’s about to change. Our colors go through the toughest tests to make sure they last for the long haul – warm or cold water. Because we have a true love for color, and for you, that won’t fade away.</p>
				</div>
			</div>
			<!-- contentPart -->
		</div>
		<!-- BlockThree -->
	</div>
	<!-- gridBlockTwo -->

	<!-- gridBlockThree -->
	<div class="gridFullWidth iconrh">
		<!-- BlockOne -->
		<div class="block30">
			<!-- contentPart -->
			<div class="textContainer">
				<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/ct-accuracy.jpg" alt="" class="img-responsive" />
				<div class="iconBlock">
					<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/Color-Accuracy-Icon.png" alt="" />
				</div>
				<div class="cntntheading">
					COLOR ACCURACY
				</div>
				<div class="contnttxt">
					<p>We use the most advanced computerized color matching and dyeing apparatus and high performance dye-jets. The dye-jets are custom programmed to use exact amount of pigmentation so that residual water after the dyeing is clear and run off can be released without adding harmful chemicals.</p>
				</div>
			</div>
			<!-- contentPart -->
		</div>
		<!-- BlockOne -->

		<!-- BlockTwo -->
		<div class="block30">
			<!-- contentPart -->
			<div class="textContainer">
				<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/ct-carbon.jpg" alt="" class="img-responsive" />
				<div class="iconBlock">
					<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/Icon-Color-Carbon6.png" alt="" />
				</div>
				<div class="cntntheading">
					CARBON 6
				</div>
				<div class="contnttxt">
					<p>A black so deep we trademarked it.<br />Introducing-Carbon 6.</p>
					<p>Black - super slimming &amp; always flattering. And the darker it is, the hotter you look. But when we looked around with clear focus, it was obvious, black had been sold short &ndash; there was no true deep black to be found.</p>
					<p>We spent two years creating our own black - Carbon 6 - using the highest quality pigments, Carbon 6 absorbs the highest amount of light, so it’s an intense, pure black. Simply put, when you wear it, you’ll look ravishing.</p>
				</div>
			</div>
			<!-- contentPart -->
		</div>
		<!-- BlockTwo -->

		<!-- BlockThree -->
		<div class="block30">
			<!-- contentPart -->
			<div class="textContainer">
				<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/ct-dyeing.jpg" alt="" class="img-responsive" />
				<div class="iconBlock">
					<img src="<?php echo Mage::getBaseUrl('media')?>wysiwyg/new-design-images/Icon-Color-USAdye.png" alt="" />
				</div>
				<div class="cntntheading">
					DYEING PROUDLY DONE<br />IN THE USA
				</div>
				<div class="contnttxt">
					<p>Unlike many companies who have their dyeing facilities located in China, our dye-lab is located in the USA, in a geographical area with the toughest environmental and pollution standards.</p>
				</div>
			</div>
			<!-- contentPart -->
		</div>
		<!-- BlockThree -->
	</div>
	<!-- gridBlockThree -->

	

	<!-- bottomDivider -->
	<div class="bottomdivider"></div>
	<!-- bottomDivider -->

</div>
<!-- endCMSPages -->