<script>
    jQuery("label.shipping_method_radio").click(function(){
        jQuery(this).addClass("active");
        jQuery("label.shipping_method_radio").not(jQuery(this)).removeClass("active");
    });
    jQuery("#checkout-shipping-method-load .method:first-child > p >span:first-child>label.shipping_method_radio").click();
//    var checkedFound = false;
//    jQuery("label.shipping_method_radio").each(function(){
//
//        if(jQuery(this).find("input[type='radio']").prop("checked")==true){
//            jQuery(this).click();
//            checkedFound=true;
//        }
//    });
//    if(!checkedFound){
//        jQuery("label.shipping_method_radio:first-child").click();
//    }

</script>
<form id="co-shippingmethod-form" action="">

    <?php $_shippingRateGroups = $this->getShippingRates(); ?>
    <?php if (!$_shippingRateGroups): ?>
        <p><?php echo $this->__('Sorry, no quotes are available for this order at this time.') ?></p>
    <?php else: ?>
        <?php $shippingCodePrice = array(); ?>
        <?php $_sole = count($_shippingRateGroups) == 1; foreach ($_shippingRateGroups as $code => $_rates): ?>
            <?php $_sole = $_sole && count($_rates) == 1; foreach ($_rates as $_rate): ?>
                <?php $shippingCodePrice[] = "'".$_rate->getCode()."':".(float)$_rate->getPrice(); ?>
                <?php if ($_rate->getErrorMessage()): ?>
                    <p class="shipping_method_errormsg"><?php echo $this->escapeHtml($_rate->getErrorMessage()) ?></p>
                <?php else: ?>
                    <div class="method">
                        <p>
                                <span>
                                    <?php if ($_sole) : ?>
                                        <span class="no-display"><input name="shipping_method" type="radio" value="<?php echo $_rate->getCode() ?>" id="s_method_<?php echo $_rate->getCode() ?>" checked="checked" /></span>
                                        <label class="shipping_method_radio">
                                            <input name="shipping_method_dummy" type="radio" value="<?php echo $_rate->getCode() ?>" id="s_method_<?php echo $_rate->getCode() ?>" checked="checked" class="radio"/>
                                        </label>
                                    <?php else: ?>
                                    <label class="shipping_method_radio">
                                        <input name="shipping_method" type="radio" value="<?php echo $_rate->getCode() ?>" id="s_method_<?php echo $_rate->getCode() ?>"<?php //if($_rate->getCode()===$this->getAddressShippingMethod()) echo ' checked="checked"' ?> class="radio"/>
                                    </label>
                                    <?php endif; ?> 
                                </span>
                                <span>
                                    <label for="s_method_<?php echo $_rate->getCode() ?>"><strong><?php echo $this->escapeHtml($_rate->getMethodTitle()) ?></strong>
                                        <?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
                                        <?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>
                                        (<?php echo $_excl; ?>)
                                        <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                                            (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                                        <?php endif; ?>
                                    </label>
                                </span>
                        </p>
                        <?php
                        $temp = Mage::app()->getLayout()->createBlock('cms/block')->setBlockId($_rate->getCode())->toHtml();
                        //$temp = Mage::getModel('cms/block')->load('revolvingmessage_loggedin')->getContent();
                        //                            $block  = Mage::getModel('cms/block')
                        //                                        ->setStoreId(Mage::app()->getStore()->getId())
                        //                                        ->load('revolvingmessage_loggedin');
                        //                            echo    Mage::app()->getLayout()->createBlock('cms/block')->setBlockId('revolvingmessage_loggedin')->toHtml();
                        //                            echo $block->getContent();
                        //                            echo $temp;
                        if($temp != "")
                        {
                            ?>
                            <div class="shippingdescription">
                                <?php echo $temp; ?>
                            </div>
                            <?php
                        }
                        ?>

                    </div>
                <?php endif ?>
            <?php endforeach; ?>
        <?php endforeach; ?>
    <?php endif; ?>
    <?php if ($_shippingRateGroups): ?>
        <?php //echo $this->getLayout()->createBlock('cms/block')->setBlockId('shipping_note')->toHtml(); ?>
        <!-- <input type="submit" imageurl="<?php echo $this->getSkinUrl('images/checkout/continue_off.png'); ?>" downimageurl="<?php echo $this->getSkinUrl('images/checkout/continue_on.png'); ?>" name="send" class="loginbtn spbutton custombtn checkoutcontinuebtn" value="" /> -->
        <div class="cleaner"></div>
        <div id="shippingmethoderrormsg" class="loginerrormsg errormsg"></div>
    <?php endif; ?>
</form>
<?php return; ?>





<?php $_shippingRateGroups = $this->getShippingRates(); ?>
<?php if (!$_shippingRateGroups): ?>
    <p><?php echo $this->__('Sorry, no quotes are available for this order at this time.') ?></p>
<?php else: ?>
    <dl class="sp-methods">
        <?php $shippingCodePrice = array(); ?>
        <?php $_sole = count($_shippingRateGroups) == 1; foreach ($_shippingRateGroups as $code => $_rates): ?>
            <dt><?php echo $this->escapeHtml($this->getCarrierName($code)) ?></dt>
            <dd>
                <ul>
                    <?php $_sole = $_sole && count($_rates) == 1; foreach ($_rates as $_rate): ?>
                        <?php $shippingCodePrice[] = "'".$_rate->getCode()."':".(float)$_rate->getPrice(); ?>
                        <li>
                            <?php if ($_rate->getErrorMessage()): ?>
                                <ul class="messages"><li class="error-msg"><ul><li><?php echo $this->escapeHtml($_rate->getErrorMessage()) ?></li></ul></li></ul>
                            <?php else: ?>
                            <?php if ($_sole) : ?>
                                <span class="no-display"><input name="shipping_method" type="radio" value="<?php echo $_rate->getCode() ?>" id="s_method_<?php echo $_rate->getCode() ?>" checked="checked" /></span>
                            <?php else: ?>
                            <input name="shipping_method" type="radio" value="<?php echo $_rate->getCode() ?>" id="s_method_<?php echo $_rate->getCode() ?>"<?php if($_rate->getCode()===$this->getAddressShippingMethod()) echo ' checked="checked"' ?> class="radio"/>

                            <?php if ($_rate->getCode() === $this->getAddressShippingMethod()): ?>
                                <script type="text/javascript">
                                    //<![CDATA[
                                    lastPrice = <?php echo (float)$_rate->getPrice(); ?>;
                                    //]]>
                                </script>
                            <?php endif; ?>

                            <?php endif; ?>
                                <label for="s_method_<?php echo $_rate->getCode() ?>"><?php echo $this->escapeHtml($_rate->getMethodTitle()) ?>
                                    <?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
                                    <?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>
                                    <?php echo $_excl; ?>
                                    <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                                        (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                                    <?php endif; ?>
                                </label>
                            <?php endif ?>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </dd>
        <?php endforeach; ?>
    </dl>
    <script type="text/javascript">
        //<![CDATA[
        <?php if (!empty($shippingCodePrice)): ?>
        var shippingCodePrice = {<?php echo implode(',',$shippingCodePrice); ?>};
        <?php endif; ?>

        $$('input[type="radio"][name="shipping_method"]').each(function(el){
            Event.observe(el, 'click', function(){
                if (el.checked == true) {
                    var getShippingCode = el.getValue();
                    <?php if (!empty($shippingCodePrice)): ?>
                    var newPrice = shippingCodePrice[getShippingCode];
                    if (!lastPrice) {
                        lastPrice = newPrice;
                        quoteBaseGrandTotal += newPrice;
                    }
                    if (newPrice != lastPrice) {
                        quoteBaseGrandTotal += (newPrice-lastPrice);
                        lastPrice = newPrice;
                    }
                    <?php endif; ?>
                    checkQuoteBaseGrandTotal = quoteBaseGrandTotal;
                    return false;
                }
            });
        });

        //]]>
    </script>
<?php endif; ?>
