<div id="invite_friends" style="display: none;">
		<div class="invite-form">
		
			<p class="c-align heart-img"><img src="<?php echo $this->getSkinUrl('images/mobile-popup-vday.png')?>"></span></p>
			<p class="c-align"><img src="<?php echo $this->getSkinUrl('images/PopUp-Vday-text.png')?>"></span></p>
			<form id="invite-friend-form" class="bl" action="<?php //echo Mage::getUrl('rewardpoints/index/referral/') ?>" method="post">
				<div class="box-invite heart-ul">
					<fieldset class="group-select" id="j2t-referral-lines">
						<?php echo $this->getBlockHtml('formkey')?>
						<ul class="form-list">
							<li class="fields">
								<div class="j2t-rewardpoints-referral">
									<div class="field j2t-rewardpoints-name">
										<input type="text" name="name[]" value="" placeholder="Friend's Name" title="<?php echo $this->__('Friend\' Name') ?>" class="required-entry input-text friendname" required/>
									</div>
									<div class="field j2t-rewardpoints-email">
										<input type="email" name="email[]" placeholder="Friend's Email" value="" title="<?php echo $this->__('Friend\'s Email') ?>" class=" required-entry input-text friendemail" required/>
								
								</div>
								</div>
							</li>
						</ul>
						
						<!--2-->
						<ul class="form-list">
							<li class="fields">
								<div class="j2t-rewardpoints-referral">
									<div class="field j2t-rewardpoints-name">
										<input type="text" name="name[]" value="" placeholder="Friend's Name" title="<?php echo $this->__('Friend\' Name') ?>" class="required-entry input-text friendname" required/>
									</div>
									<div class="field j2t-rewardpoints-email">
										<input type="email" name="email[]" placeholder="Friend's Email" value="" title="<?php echo $this->__('Friend\'s Email') ?>" class=" required-entry input-text friendemail" required/>
									</div>
								</div>
							</li>
						</ul>
						<!--3-->
						<ul class="form-list">
							<li class="fields">
								<div class="j2t-rewardpoints-referral">
									<div class="field j2t-rewardpoints-name">
										<input type="text" name="name[]" value="" placeholder="Friend's Name" title="<?php echo $this->__('Friend\' Name') ?>" class="required-entry input-text friendname"/>
									</div>
									<div class="field j2t-rewardpoints-email">
										<input type="email" name="email[]" placeholder="Friend's Email" value="" title="<?php echo $this->__('Friend\'s Email') ?>" class=" required-entry input-text friendemail"/>
									</div>
								</div>
							</li>
						</ul>
						<!--4-->
						<ul class="form-list">
							<li class="fields">
								<div class="j2t-rewardpoints-referral">
									<div class="field j2t-rewardpoints-name">
										<input type="text" name="name[]" value="" placeholder="Friend's Name" title="<?php echo $this->__('Friend\' Name') ?>" class="required-entry input-text friendname"/>
									</div>
									<div class="field j2t-rewardpoints-email">
										<input type="email" name="email[]" placeholder="Friend's Email" value="" title="<?php echo $this->__('Friend\'s Email') ?>" class=" required-entry input-text friendemail"/>
									</div>
								</div>
							</li>
						</ul>
						<!--5-->
						<ul class="form-list">
							<li class="fields">
								<div class="j2t-rewardpoints-referral">
									<div class="field j2t-rewardpoints-name">
										<input type="text" name="name[]" value="" placeholder="Friend's Name" title="<?php echo $this->__('Friend\' Name') ?>" class="required-entry input-text friendname"/>
									</div>
									<div class="field j2t-rewardpoints-email">
										<input type="email" name="email[]" placeholder="Friend's Email" value="" title="<?php echo $this->__('Friend\'s Email') ?>" class=" required-entry input-text friendemail"/>
									</div>
								</div>
							</li>
						</ul>
						<div class="action-button">
						<button class="btn-invite button invite-button" type="submit"><span><?php echo $this->__('Send') ?></span></button>
						<p style="min-height:15px;color:#fff;  margin: 0 auto; font-size: 12px; visibility:hidden" class="err-msg">All fields are required.</p>
						<a href="javascript:void(0)" class="close-invite-popup"><span>Close</span></a>
						<p style="font-size:12px;"><sup>*</sup>At least 2 Friend's emails required to Spread the SMOGI Love.</p>
						</div>
					</fieldset>
				</div>
			</form>
		
		</div>
		<div class="thanks-text">
			<p class="c-align heart-img"><img src="<?php echo $this->getSkinUrl('images/heart_up.png')?>"></span></p>
			<h2>THANK YOU FOR 
SPREADING THE SMOGI LOVE</h2> 
			<p class="c-align email-text">You will receive an email with your 35% off promo code.</p>
			<div class="action-button">
				<a href="javascript:void(0)" class="close-invite-popup"><span>Close</span></a>
			</div>
		</div>
		
</div>		
<script>
jQuery(function(){
	//alert(_islogedinuser);
	jQuery(".action-button").on("click","a.close-invite-popup",function(){
		jQuery("#invite_friends").hide();	
	});
	/*jQuery("#invite_friends").show();	
	setTimeout(function(){
			jQuery("#invite_friends").hide();	
			}, 5000);*/
	jQuery(".spread-popup").click(function(){
	jQuery("#invite_friends").show();
		/*if(_islogedinuser){
			openLogin();
		}
		else{
			jQuery("#invite_friends").show();
		}
		*/	
			
			
	});
	
	jQuery("#invite-friend-form").submit(function(event){
        event.preventDefault();
		var formid = "#invite-friend-form";
		var formData = jQuery(this).serialize();
		sharewithfriendPopup(formData);
        
    });
	
	
});
function sharewithfriendPopup(formData){
	
	if(window.location.href.indexOf('https://') >= 0)
        _usesecureurl = true;
    else
        _usesecureurl = false;
    var url = homeUrl + 'mycatalog/myproduct/referfriendpopup';
    if(_usesecureurl)
        url = securehomeUrl + 'mycatalog/myproduct/referfriendpopup';

	jQuery.ajax({

        url     :   url,
        type    :   'POST',
		data 	: 	formData,
		dataType: 'json',
        beforeSend: function() {
           // jQuery("#invite-friend-form .form-loader").html("<img src='/skin/frontend/new-yogasmoga/yogasmoga-theme/images/new-loader.gif' style='width:16px;' />");
		    jQuery("#invite-friend-form .invite-button span").html("Sending...");
            //jQuery("#send-invite").parent().hide();
           // jQuery("#invite-friend-form .form-loader").show();
        },
        success :  function(result){
			
            if(result.datafound=='yes'){
					var i;
					var _success_status = false;
					var message ="One of the emails you entered already exists.";
					for(i=0;i < result.data.length; i++){
						if(result.data[i]['status']=='success'){
						_success_status = true;
						}
					}
					
					if(_success_status){
					jQuery("#invite-friend-form .invite-button span").html("Send");
					jQuery("#invite-friend-form")[0].reset();
					jQuery("#invite_friends .invite-form").hide();
					jQuery("#invite_friends .thanks-text").show();
					}
					else{
						jQuery("#invite-friend-form .invite-button span").html("Send");
						jQuery("#invite-friend-form .action-button .err-msg").html(message).css("visibility","visible");
						jQuery("#invite-friend-form")[0].reset();
					}
			}
		}
    });
}
</script>