
<?php if (!Mage::getSingleton('customer/session')->isLoggedIn()) {

    $title = Mage::getStoreConfig('bluethink/bluethink_group/bluethink_input', Mage::app()->getStore());
    $flag = Mage::getStoreConfig('bluethink/bluethink_group/bluethink_select', Mage::app()->getStore());
    $contents = Mage::getStoreConfig('bluethink/bluethink_group/bluethink_textarea', Mage::app()->getStore());
    $alphabet = "abcdefghijklmnopqrstuwxyzABCDEFGHIJKLMNOPQRSTUWXYZ0123456789";
    $pass = '';                           //password is a string
    $alphaLength = strlen($alphabet) - 1; //put the length -1 in cache
    for ($i = 0; $i < 8; $i++) {
        $n = mt_rand(0, $alphaLength);
        $pass = $pass . $alphabet[$n];      //append a random character
    }
    
//if ($flag) {

        ?>
<?php ?>
<!-- MAil chimp poup -->
<div id="MailpopForm"  style="display:none">
    <link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('popup/css/popup.css'); ?>"/>
    <div  class="sign-up-popup">
      <!--   <a  class="cross_icon" onclick="closeSignup()" href="javascript:void(0)">
            <svg xml:space="preserve" enable-background="new 0 0 55 55" viewBox="0 0 55 55" height="55px" width="55px" y="0px" x="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" id="Layer_1" version="1.1">
            <g>
                <rect height="66" width="66" fill="none"/>
                <line y2="40" x2="40" y1="14" x1="14" stroke-miterlimit="10" stroke="#FFFFFF" fill="none"/>
                <line y2="40" x2="14" y1="14" x1="40" stroke-miterlimit="10" stroke="#FFFFFF" fill="none"/>
            </g>
            </svg>
        </a> -->

        <div  class="signup-info">
            <div class="scroll">
                <div class="main-heading">
			<svg class="svg-logontext" width="410px" height="165px" viewBox="0 0 410 165" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                        <title>Group</title>
                        <desc>Created with Sketch.</desc>
                        <defs></defs>
                        <g id="SIGNUP-25-SMB" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                            <g id="PopupSMB-Desktop_v3" transform="translate(-599.000000, -154.000000)">
                                <g id="Group" transform="translate(594.000000, 154.000000)">
                                    <g id="Text" transform="translate(0.000000, 96.500000)" font-size="32" font-family="AvantGardeGothicITCW01D, ITCAvantGardeStd-Demi, ITC Avant Garde Gothic Std" line-spacing="34" letter-spacing="0.129999995" font-weight="500">
                                        <text id="SIGN-UP-NOW-TO-RECEI">
                                            <tspan x="18" y="24" fill="#AE8536" font-family="Avantgarde-demi">SPREAD THE SMOGI LOVE&nbsp;&nbsp;</tspan>
                                            <tspan x="45" y="60" fill="#FFFFFF" font-size="22"  font-family="Avantgarde-demi">&nbsp;&nbsp;TO YOUR FRIENDS, GET 30% OFF</tspan>
                                        </text>
                                    </g>
                                    <g id="YS-logotype" transform="translate(91.000000, 0.000000)" fill="#AE8536">
                                        <path d="M107.979394,18.9071263 C108.390606,23.1630445 111.450947,24.0480368 113.020436,24.0480368 C115.648266,24.0480368 118.074585,22.0145432 118.074585,19.1772645 C118.074585,15.5975202 115.030628,14.8136225 112.125926,13.8308501 C110.060032,13.2226251 105.66284,11.9117095 105.66284,7.09562762 C105.59567,2.55631304 109.327713,0.0405483376 113.167883,0.0405483376 C116.303585,0.0405483376 119.935691,1.81053299 120.33216,6.63655857 L117.538862,6.63655857 C117.240691,4.99252788 116.419904,2.4717913 113.05484,2.4717913 C110.536777,2.4717913 108.467606,4.20863018 108.467606,6.8420624 C108.443032,9.95279386 110.903755,10.7234332 114.730819,12.0111468 C117.112904,12.9491724 120.882628,14.3031775 120.882628,18.9949627 C120.882628,23.1564153 117.784606,26.4792798 113.06467,26.4792798 C108.846053,26.4792798 105.343372,23.791157 105.174628,18.9071263 L107.979394,18.9071263 L107.979394,18.9071263 Z" id="Fill-3"></path>
                                        <polygon id="Fill-5" points="124.304377 26.0165647 124.304377 0.499285934 128.254313 0.499285934 137.618823 21.906488 146.914526 0.499285934 150.857909 0.499285934 150.857909 26.0165647 148.208781 26.0165647 148.271036 3.31336266 138.485483 26.0165647 136.689909 26.0165647 126.879781 3.31336266 126.950228 26.0165647"></polygon>
                                        <path d="M218.686553,3.71525524 L213.681553,16.5095263 L223.747255,16.5095263 L218.686553,3.71525524 Z M209.938043,26.0173934 L206.894085,26.0173934 L217.431617,0.500114578 L220.156106,0.500114578 L230.592064,26.0173934 L227.523532,26.0173934 L224.59917,18.8496184 L212.850936,18.8496184 L209.938043,26.0173934 Z" id="Fill-7"></path>
                                        <path d="M79.2241532,11.5003703 L66.6649617,11.5003703 L66.6649617,16.7042578 L71.7944723,16.7042578 C71.4520681,17.9488818 70.7394085,18.9846875 69.7154723,19.6708051 C68.6915362,20.3966977 67.3596,20.8093627 65.758983,20.8093627 C62.5888766,20.8093627 58.8388128,18.4991018 58.8388128,13.156002 C58.8388128,8.12281535 62.5577489,5.74129105 65.7278553,5.74129105 C67.5004936,5.74129105 68.8930468,6.39757749 69.9546638,7.32565934 C70.4969404,7.8427335 70.9425574,8.42941381 71.2833234,9.05089719 L78.5114936,9.05089719 C77.1123872,4.1204624 71.9304511,0.0170148338 65.8982383,0.0170148338 C58.4652809,0.0170148338 52.3970255,5.53578721 52.3970255,13.156002 C52.3970255,20.5011069 58.1621957,26.5336389 65.7933872,26.5336389 C69.9546638,26.5336389 75.6100681,24.4321964 78.0658766,18.8090148 C79.1586213,16.3297105 79.3634085,13.3283601 79.2241532,11.5003703" id="Fill-9"></path>
                                        <path d="M197.138021,13.992933 L197.138021,16.3396542 L205.170596,16.3396542 C204.764298,18.3433166 203.545404,20.2508563 201.769489,21.6562373 C200.016511,23.0483601 197.681936,23.9731274 195.014787,23.9731274 C189.492085,23.9731274 184.650915,19.7205238 184.650915,13.2256082 C184.650915,6.82847263 189.485532,2.55598159 195.001681,2.55598159 C197.228128,2.55598159 199.221936,3.21558261 200.866787,4.35414015 C201.939872,5.07671816 202.886809,6.01142916 203.681383,7.11352634 L206.897362,7.11352634 C204.903553,2.9454445 200.155766,0.0435314578 195.057383,0.0435314578 C187.762043,0.0435314578 181.829766,5.5821913 181.829766,13.2256082 C181.829766,20.7745596 187.662106,26.4888921 195.02134,26.4888921 C200.116447,26.4888921 205.13783,23.6930455 207.34134,18.9266824 C208.088404,17.319112 208.409511,15.4762066 208.457021,13.992933 L197.138021,13.992933 Z" id="Fill-11"></path>
                                        <polygon id="Fill-13" points="26.1624702 0.611152941 19.6977468 0.611152941 13.5180872 11.3885033 7.42525745 0.611152941 0.796704255 0.611152941 10.2627894 17.3464573 10.2627894 26.0157361 16.7094915 26.0157361 16.7094915 17.1028358"></polygon>
                                        <path d="M168.321017,20.5214916 L166.438613,23.8078957 L164.543102,20.4601719 C161.430336,19.5287754 159.603634,16.4545043 159.603634,13.2062179 L159.603634,13.1747294 C159.603634,9.58835601 162.021762,5.72190077 166.487762,5.72190077 C171.125783,5.72190077 173.335847,9.96290332 173.335847,13.2774813 C173.335847,16.0965299 171.695911,19.6000389 168.321017,20.5214916 M166.451719,0.0373994885 C159.50206,0.0373994885 153.156932,5.20814118 153.156932,13.550934 L153.156932,13.5840798 C153.156932,20.1403151 158.474847,26.5192205 166.417315,26.5192205 C174.261485,26.5192205 179.782549,20.3822793 179.782549,13.2774813 C179.782549,6.17434066 174.225443,0.0373994885 166.451719,0.0373994885" id="Fill-15"></path>
                                        <path d="M38.8632106,20.5214916 L36.9808064,23.8078957 L35.0836574,20.4601719 C31.9692532,19.5287754 30.1392745,16.4545043 30.1392745,13.2062179 L30.1392745,13.1747294 C30.1392745,9.58835601 32.5606787,5.72190077 37.0250404,5.72190077 C41.6630617,5.72190077 43.8780404,9.96290332 43.8780404,13.2774813 C43.8780404,16.0965299 42.2315511,19.6000389 38.8632106,20.5214916 M36.9922745,0.0373994885 C30.0393383,0.0373994885 23.6942106,5.20814118 23.6942106,13.550934 L23.6942106,13.5840798 C23.6942106,20.1403151 29.0154021,26.5192205 36.9578702,26.5192205 C44.8020404,26.5192205 50.321466,20.3822793 50.321466,13.2774813 C50.321466,6.17434066 44.7659979,0.0373994885 36.9922745,0.0373994885" id="Fill-17"></path>
                                        <path d="M88.425817,0.496302813 L78.4371149,26.0168962 L85.4260936,26.0168962 L86.5843702,22.3277708 L95.4115191,22.3277708 L96.6074766,26.0168962 L103.661987,26.0168962 L93.9829234,0.496302813 L88.425817,0.496302813 Z M90.9143915,8.26070179 L93.7420936,17.1570292 L88.1866255,17.1570292 L90.9143915,8.26070179 Z" id="Fill-2"></path>
                                    </g>
                                </g>
                            </g>
                        </g>
                    </svg>
				
				
                    <!--<span>Spread the SMOGI Love</span> <br/>To Your Friends, Get 30% Off-->
                    <?php /*?><div class="discnt-offr"><img  src="<?php echo $this->getSkinUrl('images/popup-discount.png'); ?>" class="img-responsive"/></div>
                    <!--YOUR FIRST ORDER-->
                    <!--<div class="lmt-ofr">LIMITED TIME ONLY<BR>NOW THROUGH SEPTEMBER 26.</div>--><?php */?>
                </div>
                <div class="popup-form">

                    <form name="" id="popup-mailsignup" class="popup_form" method="post" action="" rel="">
                        <ul>
                            <!--<li><span>Your Email Address</span></li>-->
							<li>
                                <div class="input-box">
									<input type="text" class="input-text" name="firstname" id="fname" data-watermark="First Name">
								</div>
							</li>
							<li>
								<div class="input-box">
									<input type="text" class="input-text" name="lastname" id="lname" data-watermark="Last Name">
								</div>
                            </li>
                            <li><div class="input-box">
                                    <input type="text" class="input-text" id="Memail_address" placeholder="Your Email Address" name="email" value="">
                                </div>
                            </li>
							<li>
							<p class="gender_p">Gender <label><span class="gender_radio">
							<input type="radio" value="1" name="gender"/>M</span>Male</label>
							<label><span class="gender_radio"><input type="radio" value="2" name="gender"/>F</span>Female</label></p>
							</li>
                            <li class="button-area"><span class="form-loader-mail"></span>
                                <!--<span class="tick-mark">
                                    <svg xml:space="preserve" style="enable-background:new 0 0 44 44;" viewBox="0 0 44 44" y="0px" x="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" id="Layer_1" version="1.1">
                                        <style type="text/css">
                                        .st0{fill:none;stroke:#FFFFFF;stroke-miterlimit:10;}
                                        </style>
                                        <polyline points="5.9,25.6 14.6,34.3 39.1,9.8 " class="st0"/>
                                    </svg>
                                </span>-->
                                <input type="submit" class="signup_button" id="signup-button-mailc" value=""/>
                            </li>
                            <li><p style="margin: 0px auto;font-size: 12px;visibility: hidden;min-height: 20px;width: 236px;color:#fff;clear:both;padding-top:5px;" id="err-msg">All fields are required.</p></li>
                            <li><a class="no-thanks" onclick="closeSignup()" >No Thank You, I’m not interested in <br>Made in the USA apparel.</a></li>
                            <li><a class="already_signed_up">I’m already signed up.</a></li>
                        </ul>

                    </form>

                </div>
            </div>

        </div>
    </div>
    <!-- thank you popup -->
    <div style="display:none;" class="thanks-popup">
        <a  class="cross_icon" onclick="closeSignup()" href="javascript:void(0)">
            <svg xml:space="preserve" enable-background="new 0 0 55 55" viewBox="0 0 55 55" height="55px" width="55px" y="0px" x="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" id="Layer_1" version="1.1">
						<g>
                            <rect height="66" width="66" fill="none"/>
                            <line y2="40" x2="40" y1="14" x1="14" stroke-miterlimit="10" stroke="#FFFFFF" fill="none"/>
                            <line y2="40" x2="14" y1="14" x1="40" stroke-miterlimit="10" stroke="#FFFFFF" fill="none"/>
                        </g>
						</svg>
        </a>

        <div class="signup-info">
            <div class="scroll">
                <div class="main-heading">
                    <span class="strong">Thank You</span> <span class="lmt-ofr">Please Check Your email <br>&amp; Feel the SMOGI LOVE</span>
                </div>
                <div class="popup-form">
                    <form name="" id="" class="popup_form" method="" action="" rel="">
                        <ul>
                            <!--<li><span>We've also emailed it to you<br/>in case you forget.</span></li>-->
                            <li>
                                <a  href="/women"><img  src="<?php echo $this->getSkinUrl('images/thanks-popup-womenv3.png'); ?>" class="img-responsive"/>  </a>
                            </li>
                            <li>
                                <a  href="/men"><img  src="<?php echo $this->getSkinUrl('images/thanks-popup-menv3.jpg'); ?>" class="img-responsive"/> </a>
                            </li>
                        </ul>
                    </form>
                </div>
            </div>

        </div>
    </div>
    <!-- thank you popup -->
</div>
<!-- MAil chimp poup -->
<style>
    .ui-loader{display:none!important;}
</style>
<?php
        $name = 'popupcookies';
        $value = 'yes';

        $cookieValue = Mage::getModel('core/cookie')->get($name);

        if (!isset($cookieValue) || $cookieValue!="yes") {

            ?>
         <script>
                       jQuery.noConflict();
                      jQuery(document).ready(function () {
                            //jQuery("#popForm").show();
							//jQuery('#MailpopForm').show();

                        });
                    </script>
                   <?php
       }
        Mage::getModel('core/cookie')->set($name, $value);
        ?>

        <script>
            jQuery.noConflict();
            jQuery(document).ready(function () {

                var url = homeUrl + 'mycatalog/myproduct/checkforsignuppopup';

                jQuery.ajax({
                    url: url,
                    type: 'get',
                    dataType: 'json',
                    success: function(result){

                        if(result!=undefined && result.status!=undefined && result.status=="success"){
                            //jQuery("#popForm").show();
                            jQuery("#MailpopForm").show();
                        }
                    }
                });
            });
        </script>
<script type="application/javascript">
	function closeSignup() {
                jQuery(".sign-up-block .btn").removeClass("active");
                jQuery("#error_msg").html("");
                jQuery("input[type='radio']").prop("checked", false);
                jQuery('#MailpopForm').hide();
                jQuery(".sign-up-popup").show();
                jQuery(".thanks-popup").hide();
                jQuery("#Memail_address").val('');
				
            }
    jQuery(document).ready(function($){
		
		$(".mobile-orange-banner").click(function () {
                    $('#MailpopForm').show();
                   // jQuery('#popForm').show();
                    //alert("dlmcld");
                    //window.location.assign(homeUrl+"one-too-many");
                });
		$("p.gender_p label span.gender_radio input").click(function () {
                    var item=$(this).parent();
					$("p.gender_p label span.gender_radio").removeClass('selected');
					item.addClass("selected");
				});		
				
        $('#Memail_address').on('focus keyup',function(){
            if($(this).val().length > 0){
                $('#signup-button-mailc').addClass('on');
                $('#signup-button-mailc').removeClass('subscribed');
                jQuery("#popup-mailsignup #signup-button-mailc").removeClass('sending');
            }
            else{
                $('#signup-button-mailc').removeClass('on');
            }

        });

        $("#popup-mailsignup").submit(function(event){
            event.preventDefault();
			var formData = jQuery(this).serialize();
            $("#err-msg").css("visibility","hidden");
				
            var formid = "#popup-mailsignup";
            
			var fname = jQuery.trim(jQuery("#fname").val());
			var lname = jQuery.trim(jQuery("#lname").val());
			var gender = jQuery.trim(jQuery("#popup-mailsignup .gender_p .gender_radio.selected input").val());
			
			var email_id = $.trim($("#Memail_address").val());
			
			if(fname == "" || fname == 'First Name'){
				event.preventDefault();
                $("#err-msg").css("visibility","visible");
                $("#err-msg").text("Please enter first name.");
                return;
			}
			if(lname == "" || lname == 'Last Name'){
				event.preventDefault();
                $("#err-msg").css("visibility","visible");
                $("#err-msg").text("Please enter last name.");
                return;
			}
			
            if(email_id == "" || email_id == "Email Address")
            {
                event.preventDefault();
                $("#err-msg").css("visibility","visible");
                $("#err-msg").text("Please enter an email address.");
                return;
            }
            if(!isValidEmailAddress(email_id)){
                event.preventDefault();
                $("#err-msg").css("visibility","visible");
                $("#err-msg").text("Enter a valid email.");
                return;
            }
			if(gender == ""){
				event.preventDefault();
                $("#err-msg").css("visibility","visible");
                $("#err-msg").text("Please select gender.");
                return;
			}

            if(window.location.href.indexOf('https://') >= 0)
                _usesecureurl = true;
            else
                _usesecureurl = false;
            var url = homeUrl + 'mailchimp_signup.php';
            if(_usesecureurl){
                url = securehomeUrl + 'mailchimp_signup.php';
            }


            jQuery.ajax({
                url     :   url,
                type    :   'POST',
                //data    :   {'email':email_id},
				data    :   formData,
                beforeSend: function() {
                   jQuery("#popup-mailsignup #signup-button-mailc").addClass('sending');
                    jQuery('#signup-button-mailc').removeClass('on');
                    jQuery("#popup-mailsignup #signup-button-mailc").attr("value","SIGNING UP...");
                    jQuery("#popup-mailsignup #signup-button-mailc").removeClass('subscribed');
                    jQuery("#popup-mailsignup .form-loader-mail").show();
                    jQuery("#popup-mailsignup .tick-mark").hide();
                },
                success: function (data) {
                    data = eval('(' + data + ')');
                    var status = data.status;
                    jQuery("#popup-mailsignup .form-loader-mail").hide();

                    if (status == "success") {
                        jQuery(".sign-up-popup").hide();
                        jQuery(".thanks-popup").show();
                        jQuery("#popup-mailsignup #signup-button-mailc").removeClass('sending');
                        jQuery("#popup-mailsignup #signup-button-mailc").attr("value","");
                        jQuery("#popup-mailsignup #signup-button-mailc").addClass('subscribed');
                        jQuery("#popup-mailsignup .tick-mark").show();
                        jQuery("#popup-mailsignup #err-msg").html(data.error).css("visibility","hidden");
                        jQuery('#signup-button-mailc').removeClass('on');
                    }
                    else
                    {
                        jQuery("#signup-button-mailc").val("");
                        jQuery("#signup-button-mailc").parent().show();
                        jQuery("#popup-mailsignup #signup-button-mailc").addClass('subscribed');
                        jQuery("#popup-mailsignup #err-msg").html(data.error).css("visibility","visible");
                    }
                }
            });
        });
    });
</script>


<!-- Fahim New Code -->
 <?php  //}
}
 ?>
