
		<div id="popForm"  style="display:none">
		<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('popup/css/popup.css'); ?>"/>
				<div style="display:none;" class="sign-up-popup">
					<a  class="cross_icon" onclick="closeSignup()" href="javascript:void(0)">
                        <svg xml:space="preserve" enable-background="new 0 0 55 55" viewBox="0 0 55 55" height="55px" width="55px" y="0px" x="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" id="Layer_1" version="1.1">
<g>
    <rect height="66" width="66" fill="none"/>
    <line y2="40" x2="40" y1="14" x1="14" stroke-miterlimit="10" stroke="#FFFFFF" fill="none"/>
    <line y2="40" x2="14" y1="14" x1="40" stroke-miterlimit="10" stroke="#FFFFFF" fill="none"/>
</g>
</svg>
                    </a>
					
					<div class="signup-info">
						<div class="scroll">
							<div class="main-heading">
								SIGN UP NOW<BR>TO INSTANTLY GET <span>50% OFF</span>YOUR FIRST ORDER
							</div>
							<div class="popup-form">
								<form name="" id="" class="popup_form" method="" action="" rel="">
									<ul>
									<li><span>Your Email Address</span></li>
									<li><div class="input-box">                               
                                <input type="text" class="input-text" data-watermark="example@example.com" name="email">
                            </div></li>
							<li>
							<button type="submit" class="signup_button" title="" name="" id="">SIGN UP  </button>
							</li>
									
									</ul>
								
								</form>
							</div>
						</div>
					
					</div>
				</div>
				
				<div style="display:none;"class="thanks-popup">
					<a  class="cross_icon" onclick="closeSignup()" href="javascript:void(0)">
                        <svg xml:space="preserve" enable-background="new 0 0 55 55" viewBox="0 0 55 55" height="55px" width="55px" y="0px" x="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" id="Layer_1" version="1.1">
<g>
    <rect height="66" width="66" fill="none"/>
    <line y2="40" x2="40" y1="14" x1="14" stroke-miterlimit="10" stroke="#FFFFFF" fill="none"/>
    <line y2="40" x2="14" y1="14" x1="40" stroke-miterlimit="10" stroke="#FFFFFF" fill="none"/>
</g>
</svg>
                    </a>
					
					<div class="signup-info">
						<div class="scroll">
							<div class="main-heading">
								THANK YOU!<BR>YOUR SPECIAL CODE IS<span>SMOGILOVE</SPAN>
							</div>
							<div class="popup-form">
								<form name="" id="" class="popup_form" method="" action="" rel="">
									<ul>
									<li><span>We've also emailed it to you<br/>in case you forget</span></li>
									<li>
									<a class="shop-link" href="#">SHOP MEN  </a>
									</li>
							<li>
							<a class="shop-link" href="#">SHOP MEN  </a>
							</li>
									
									</ul>
								
								</form>
							</div>
						</div>
					
					</div>
				</div>
			
		</div>
		
		