<?php if (!Mage::getSingleton('customer/session')->isLoggedIn()) {

    $title = Mage::getStoreConfig('bluethink/bluethink_group/bluethink_input', Mage::app()->getStore());
    $flag = Mage::getStoreConfig('bluethink/bluethink_group/bluethink_select', Mage::app()->getStore());
    $contents = Mage::getStoreConfig('bluethink/bluethink_group/bluethink_textarea', Mage::app()->getStore());
    $alphabet = "abcdefghijklmnopqrstuwxyzABCDEFGHIJKLMNOPQRSTUWXYZ0123456789";
    $pass = '';                           //password is a string
    $alphaLength = strlen($alphabet) - 1; //put the length -1 in cache
    for ($i = 0; $i < 8; $i++) {
        $n = mt_rand(0, $alphaLength);
        $pass = $pass . $alphabet[$n];      //append a random character
    }
    //echo $fldddag;


    if(!isset($ipInfo)){

        $root = Mage::getBaseDir();

        include_once($root . '/Ipinfo/Host.php');
        include_once($root . '/Ipinfo/Ipinfo.php');

        $ipInfo = new Ipinfo\Ipinfo();

        if (!empty($_SERVER['HTTP_CLIENT_IP'])) {
            $ip = $_SERVER['HTTP_CLIENT_IP'];
        } elseif (!empty($_SERVER['HTTP_X_FORWARDED_FOR'])) {
            $ip = $_SERVER['HTTP_X_FORWARDED_FOR'];
        } else {
            $ip = $_SERVER['REMOTE_ADDR'];
        }

        $host = $ipInfo->getFullIpDetails($ip);

        if (isset($host)) {
            $request_city = $host->getCity();
            $request_state = $host->getRegion();
            $request_zip = $host->getPostal();
        }
        else {
            $request_city = "N/A";
            $request_state = "N/A";
            $request_zip = "N/A";
        }
    }


    if ($flag) {

        ?>

        <div id="popForm" style="display:none" class="mage-signup">
            <link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('popup/css/popup.css', array('_secure'=>true)); ?>"/>
            <div class="popup_container sign-up-block sign_in_modal" id="transparent_bg">
                <div style="width:100%;" class="overlay-inner-bg" id="content">
                    <!--<a href="javascript:void(0)" onclick="closeSignup()" class="cross_popup">
                        <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg"
                             xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                             width="44px" height="44px" viewBox="0 0 44 44" enable-background="new 0 0 44 44"
                             xml:space="preserve">
<g>
    <rect fill="#555555" width="44" height="44"/>
    <line fill="none" stroke="#FFFFFF" stroke-miterlimit="10" x1="14" y1="14" x2="30" y2="30"/>
    <line fill="none" stroke="#FFFFFF" stroke-miterlimit="10" x1="30" y1="14" x2="14" y2="30"/>
</g>
</svg>
                    </a>-->


                    <div class="left_block left_block_new">
                        <div class="scroll">
                            <div class="top-heading">
                                <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg"
                                     xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
                                     width="500px" height="85px" viewBox="0 0 234.613 85"
                                     enable-background="new 0 0 234.613 85" xml:space="preserve">

                                    <g>
                                        <text transform="matrix(1 0 0 1 -20 51.3672)">
                                            <tspan x="-25" y="0" fill="#A2853F" font-family="'ITCAvantGardeStd-Bk'"
                                                   font-size="24"  y="0" x="-20">SPREAD THE SMOGI LOVE,
                                            </tspan>
                                            <tspan x="50" y="26" fill="#A2853F" font-family="'ITCAvantGardeStd-Bk'"
                                                   font-size="24" y="26" x="-45">GET 35% OFF
                                            </tspan>
                                        </text>
                                    </g>
                                    <g>
                                        <text transform="matrix(1 0 0 1 3.3594 24.0918)" fill="#FFFFFF"
                                              font-family="'ITCAvantGardeStd-Bk'" font-size="24">
                                        </text>
                                    </g>
                                    
</svg>

                                <!--<img class="svg-logontext" src="<?php //echo $this->getSkinUrl('images/30bucks.png') ?>" alt=""/>-->
								<!--<img class="svg-logontext" src="<?php echo $this->getSkinUrl('images/signup-now-15.png') ?>" alt=""/>-->
                            </div>
                            <div class="sign_signup_form">
                                <form rel="signupBox" action="" method="post" class="singup_form" id="singup_form"
                                      name="myFrom">
                                    <input type="hidden" id="location_city" name="location_city" value="<?php echo $request_city;?>"/>
                                    <input type="hidden" id="location_state" name="location_state" value="<?php echo $request_state;?>"/>
                                    <input type="hidden" id="location_zip" name="location_zip" value="<?php echo $request_zip;?>"/>

                                    <input type="hidden" value="" name="csrf_token">
                                    <span style="color:#990000; font-size:14px;"></span>

                                    <ul class="list1">

                                        <li>
                                            <div class="form_field_left">
                                                <input type="text" name="fname" data-watermark="First Name">

                                            </div>

                                            <div class="clearfix"></div>
                                        </li>
                                        <li>
                                            <div class="form_field_left">
                                                <input type="text" name="lname" data-watermark="Last Name">
                                            </div>
                                        </li>

                                        <li>
                                            <input type="text" name="email" data-watermark="Email">
                                        </li>

                                        <li>

                                            <div class="form_field_left">
                                                <div class="field">
                                                    <div class="input-box">
                                                        <input type="password" name="password" rel="password"
                                                               class="watermark_password_orignal"/>
                                                        <input type="text" value="Choose Password"
                                                               class="watermark_password"/>
                                                    </div>
                                                </div>


                                            </div>
                                            <div class="clearfix"></div>
                                        </li>


                                        <!--  <li>
         <div class="form_field_left">
        			<div class="field">
                       <div class="input-box">
                            <input type="password" name="confirmation" placeholder="<?php echo $this->__('Confirm Password') ?>" id="confirmation" class="input-text required-entry validate-cpassword" />
                        </div>
            </div>
        		</div>
        		<div class="clearfix"></div>

        		</li> -->

                                        <li class="gender-link">
                                            <span> <label>Select Gender</label></span>

                                            <div class="f-right">

                                                <?php
                                                $options = Mage::getResourceSingleton('customer/customer')->getAttribute('gender')->getSource()->getAllOptions();
                                                $value = '1';
                                                $_last = count($options);
                                                // $_index = 0;
                                                ?>

                                                <?php foreach ($options as $option): ?>
                                                    <?php if ($option['value'] != ''): ?>
                                                        <div>
                                                            <label class="f<?php echo $option['value'] ?>">
                                                                <input class="custom-radio radio" type="radio"
                                                                       title="<?php echo $option['label'] ?>"
                                                                       value="<?php echo $option['value'] ?>"
                                                                       name="gender"
                                                                    <?php if ($option['value'] == $value) echo 'checked="checked"' ?>>
                                                            </label>
                                                            <span> <?php echo $option['label'] ?> </span>
                                                        </div>
                                                    <?php endif; ?>
                                                    <?php //$_index++; ?>
                                                <?php endforeach; ?>

                                            </div>


                                        </li>

                                        <li>
                                            <input style="display: none;" id="is_subscribed" class="checkbox"
                                                   type="checkbox" checked="checked" value="1" name="is_subscribed">
                                            <input type="hidden" autocomplete="off" maxlength="30" id="isAjax"
                                                   name="isAjax" value="1">

                                            <!-- msz alredy email exist -->

                                            <!--				<p style="text-align: left" class="err_msg"></p>-->
                                            <!-- end -->
                                            <!--<p class="already_signed_up">Already signed up? Sign in here</p>-->

                                            <div class="error" id="error_msg"></div>
                                            <button type="submit" name="sign-up" id="create_account"
                                                    class="create_account btn">
				<span class="tick-mark">
					<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg"
                         xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 44 44"
                         style="enable-background:new 0 0 44 44;" xml:space="preserve">
						<style type="text/css">
                            .st0 {
                                fill: none;
                                stroke: #FFFFFF;
                                stroke-miterlimit: 10;
                            }
                        </style>
                        <polyline class="st0" points="5.9,25.6 14.6,34.3 39.1,9.8 "/>
					</svg>
				</span></button>

                                            <p style="clear:both"><a class="no-thanks" onclick="closeSignup()" >No Thank You, I’m not interested in <br>Made in the USA apparel.</a></p>
                                            <?php /* ?><p style="clear:both"><a class="already_signed_up">I’m already signed up.</a></p><?php */ ?>
                                            <p style="clear:both"><a class="already-text" onclick="openLoginPopup()">I’m already signed up.</a></p>
                                        </li>
                                    </ul>
                                </form>
                            </div>
                        </div>
                        <div class="clearfix"></div>

                    </div>
                </div>
            </div>
        </div>

        <script type="text/javascript">
            jQuery.noConflict();
            var customForm = new VarienForm('singup_form');
        </script>

        <script type="text/javascript">
            jQuery.noConflict();
			function openLoginPopup(){
				closeSignup();
				openLogin();
			}
            function closeSignup() {
                jQuery(".sign-up-block .btn").removeClass("active");
                jQuery("#error_msg").html("");
                jQuery("input[type='radio']").prop("checked", false);
                jQuery('#popForm').hide();
                jQuery('#MailpopForm').hide();
                jQuery(".sign-up-popup").show();
                jQuery(".thanks-popup").hide();
                jQuery("#Memail_address").val('');
				
            }
            jQuery(document).ready(function () {
                // jQuery(".custom-radio:checked").parent().addClass("current");
                jQuery(".custom-radio").click(function () {
                    jQuery(".custom-radio").parent().removeClass("current");
                    jQuery(this).parent().addClass("current");
                    isinputvalid();
                });
                jQuery(".mobile-orange-banner").click(function () {
                    //jQuery('#MailpopForm').show();
                    jQuery('#popForm').show();
                   /* alert("dlmcld");
                    window.location.assign(homeUrl+"one-too-many");*/
                });
                jQuery("#popForm input[type=text],#popForm input[type=password]").on('focus keypress',function(){
                    if(jQuery(this).val().length > 0){

                        jQuery(this).addClass('on');
                    }


                });
                jQuery("#popForm input[type=text],#popForm input[type=password]").on('blur keyup',function(){
                    if(jQuery(this).val().length < 1){

                        jQuery(this).removeClass('on');
                    }

                });

                jQuery('.gender-link .f-right label').click(function(){

                    if(jQuery(this).hasClass('current')){
                        jQuery('.gender-link span label').addClass('on');

                    }
                    else{
                        jQuery('.gender-link span label').removeClass('on');
                    }
                });
            });
        </script>

        <?php
        $name = 'popupcookies';
        $value = 'yes';

        $cookieValue = Mage::getModel('core/cookie')->get($name);

        if (!isset($cookieValue) || $cookieValue!="yes") {

            ?>
         <script>
                       jQuery.noConflict();
                      jQuery(document).ready(function () {
                            jQuery("#popForm").show();

                        });
                    </script>
                   <?php
       }
        Mage::getModel('core/cookie')->set($name, $value);
        ?>

        <script>
            jQuery.noConflict();
            jQuery(document).ready(function () {

                var url = homeUrl + 'mycatalog/myproduct/checkforsignuppopup';

                jQuery.ajax({
                    url: url,
                    type: 'get',
                    dataType: 'json',
                    success: function(result){

                        if(result!=undefined && result.status!=undefined && result.status=="success"){
                            jQuery("#popForm").show();
                            //jQuery("#MailpopForm").show();
                        }
                    }
                });
            });
        </script>

        <script>
            jQuery.noConflict();
            jQuery(document).ready(function () {
                init_watermark();
                jQuery("#create_account").click(function (e) {
                    e.preventDefault();
                    if (customForm.validator && customForm.validator.validate()) {
                        createCustomerAccount();
                    }
                });


            });


            //jQuery.noConflict();
           // jQuery('#signup-form').submit(function(e){


            //});
        </script>
        <?php
    }
} ?>
<?php /*?>
<!-- MAil chimp poup -->
<div id="MailpopForm"  style="display:none">
    <link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('popup/css/popup.css'); ?>"/>
    <div  class="sign-up-popup">
        <!--<a  class="cross_icon" onclick="closeSignup()" href="javascript:void(0)">
            <svg xml:space="preserve" enable-background="new 0 0 55 55" viewBox="0 0 55 55" height="55px" width="55px" y="0px" x="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" id="Layer_1" version="1.1">
            <g>
                <rect height="66" width="66" fill="none"/>
                <line y2="40" x2="40" y1="14" x1="14" stroke-miterlimit="10" stroke="#FFFFFF" fill="none"/>
                <line y2="40" x2="14" y1="14" x1="40" stroke-miterlimit="10" stroke="#FFFFFF" fill="none"/>
            </g>
            </svg>
        </a>-->

        <div  class="signup-info">
            <div class="scroll">
                <div class="main-heading">
                    SIGN UP NOW<BR>TO RECEIVE
                    <div class="discnt-offr"><img  src="<?php echo $this->getSkinUrl('images/popup-discount.png'); ?>" class="img-responsive"/></div>
                    YOUR FIRST ORDER
                    <div class="lmt-ofr">LIMITED TIME ONLY<BR>NOW THROUGH SEPTEMBER 26.</div>
                </div>
                <div class="popup-form">

                    <form name="" id="popup-mailsignup" class="popup_form" method="post" action="" rel="">
                        <ul>
                            <!--<li><span>Your Email Address</span></li>-->
                            <li><div class="input-box">
                                    <input type="text" class="input-text" id="Memail_address" placeholder="Your Email Address" name="email" value="">
                                </div>
                            </li>
                            <li class="button-area"><span class="form-loader-mail"></span>
                                <!--<span class="tick-mark">
                                    <svg xml:space="preserve" style="enable-background:new 0 0 44 44;" viewBox="0 0 44 44" y="0px" x="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" id="Layer_1" version="1.1">
                                        <style type="text/css">
                                        .st0{fill:none;stroke:#FFFFFF;stroke-miterlimit:10;}
                                        </style>
                                        <polyline points="5.9,25.6 14.6,34.3 39.1,9.8 " class="st0"/>
                                    </svg>
                                </span>-->
                                <input type="submit" class="signup_button" id="signup-button-mailc" value=""/>
                            </li>
                            <li><p style="margin: 0px auto;font-size: 12px;visibility: hidden;min-height: 20px;width: 236px;color:#fff;clear:both;padding-top:5px;" id="err-msg">All fields are required.</p></li>
                            <li><a class="no-thanks" onclick="closeSignup()" >No Thank You, I’m not interested in <br>Made in the USA apparel.</a></li>
                            <li><a class="already_signed_up">I’m already signed up.</a></li>
                        </ul>

                    </form>

                </div>
            </div>

        </div>
    </div>
    <!-- thank you popup -->
    <div style="display:none;" class="thanks-popup">
        <a  class="cross_icon" onclick="closeSignup()" href="javascript:void(0)">
            <svg xml:space="preserve" enable-background="new 0 0 55 55" viewBox="0 0 55 55" height="55px" width="55px" y="0px" x="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" id="Layer_1" version="1.1">
						<g>
                            <rect height="66" width="66" fill="none"/>
                            <line y2="40" x2="40" y1="14" x1="14" stroke-miterlimit="10" stroke="#FFFFFF" fill="none"/>
                            <line y2="40" x2="14" y1="14" x1="40" stroke-miterlimit="10" stroke="#FFFFFF" fill="none"/>
                        </g>
						</svg>
        </a>

        <div class="signup-info">
            <div class="scroll">
                <div class="main-heading">
                    <span class="strong">Thank You</span> <span class="lmt-ofr">Please Check Your email <br>&amp; Feel the SMOGI LOVE</span>
                </div>
                <div class="popup-form">
                    <form name="" id="" class="popup_form" method="" action="" rel="">
                        <ul>
                            <!--<li><span>We've also emailed it to you<br/>in case you forget.</span></li>-->
                            <li>
                                <a  href="/women"><img  src="<?php echo $this->getSkinUrl('images/thanks-popup-womenv3.png'); ?>" class="img-responsive"/>  </a>
                            </li>
                            <li>
                                <a  href="/men"><img  src="<?php echo $this->getSkinUrl('images/thanks-popup-menv3.jpg'); ?>" class="img-responsive"/> </a>
                            </li>
                        </ul>
                    </form>
                </div>
            </div>

        </div>
    </div>
    <!-- thank you popup -->
</div>
<!-- MAil chimp poup -->
<style>
    .ui-loader{display:none!important;}
</style>
<!--<script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>-->
<script type="application/javascript">
    jQuery(document).ready(function($){

        $('#Memail_address').on('focus keyup',function(){
            if($(this).val().length > 0){
                $('#signup-button-mailc').addClass('on');
                $('#signup-button-mailc').removeClass('subscribed');
                jQuery("#popup-mailsignup #signup-button-mailc").removeClass('sending');
            }
            else{
                $('#signup-button-mailc').removeClass('on');
            }

        });

        $("#popup-mailsignup").submit(function(event){
            event.preventDefault();

            $("#err-msg").css("visibility","hidden");

            var formid = "#popup-mailsignup";
            var email_id = $.trim($("#Memail_address").val());
            if(email_id == "" || email_id == "Email Address")
            {
                event.preventDefault();
                $("#err-msg").css("visibility","visible");
                $("#err-msg").text("Please enter an email address.");
                return;
            }
            if(!isValidEmailAddress(email_id)){
                event.preventDefault();
                $("#err-msg").css("visibility","visible");
                $("#err-msg").text("Enter a valid email.");
                return;
            }

            if(window.location.href.indexOf('https://') >= 0)
                _usesecureurl = true;
            else
                _usesecureurl = false;
            var url = homeUrl + 'mailchimp_signup.php';
            if(_usesecureurl){
                url = securehomeUrl + 'mailchimp_signup.php';
            }


            jQuery.ajax({
                url     :   url,
                type    :   'POST',
                data    :   {'email':email_id},
                beforeSend: function() {
                   jQuery("#popup-mailsignup #signup-button-mailc").addClass('sending');
                    jQuery('#signup-button-mailc').removeClass('on');
                    jQuery("#popup-mailsignup #signup-button-mailc").attr("value","SIGNING UP...");
                    jQuery("#popup-mailsignup #signup-button-mailc").removeClass('subscribed');
                    jQuery("#popup-mailsignup .form-loader-mail").show();
                    jQuery("#popup-mailsignup .tick-mark").hide();
                },
                success: function (data) {
                    data = eval('(' + data + ')');
                    var status = data.status;
                    jQuery("#popup-mailsignup .form-loader-mail").hide();

                    if (status == "success") {
                        jQuery(".sign-up-popup").hide();
                        jQuery(".thanks-popup").show();
                        jQuery("#popup-mailsignup #signup-button-mailc").removeClass('sending');
                        jQuery("#popup-mailsignup #signup-button-mailc").attr("value","");
                        jQuery("#popup-mailsignup #signup-button-mailc").addClass('subscribed');
                        jQuery("#popup-mailsignup .tick-mark").show();
                        jQuery("#popup-mailsignup #err-msg").html(data.error).css("visibility","hidden");
                        jQuery('#signup-button-mailc').removeClass('on');
                    }
                    else
                    {
                        jQuery("#signup-button-mailc").val("");
                        jQuery("#signup-button-mailc").parent().show();
                        jQuery("#popup-mailsignup #signup-button-mailc").addClass('subscribed');
                        jQuery("#popup-mailsignup #err-msg").html(data.error).css("visibility","visible");
                    }
                }
            });
        });
    });
</script>


<!-- Shivaji New Code -->
 <?php */ ?>
