<?php if(!Mage::getSingleton('customer/session')->isLoggedIn()){
	$title=Mage::getStoreConfig('bluethink/bluethink_group/bluethink_input',Mage::app()->getStore());
	$flag=Mage::getStoreConfig('bluethink/bluethink_group/bluethink_select',Mage::app()->getStore());
		$contents=Mage::getStoreConfig('bluethink/bluethink_group/bluethink_textarea',Mage::app()->getStore());
 $alphabet = "abcdefghijklmnopqrstuwxyzABCDEFGHIJKLMNOPQRSTUWXYZ0123456789";
    $pass = '';                           //password is a string
    $alphaLength = strlen($alphabet) - 1; //put the length -1 in cache
    for ($i = 0; $i <8; $i++) {
        $n = mt_rand(0, $alphaLength);    
        $pass = $pass.$alphabet[$n];      //append a random character
    }
	//echo $fldddag;

if($flag){?>

<div id="popForm" style = "display:none">
<link rel="stylesheet" type="text/css" href="<?php echo $this->getSkinUrl('popup/css/popup.css');?>"/>
<div class="popup_container sign-up-block sign_in_modal" id="transparent_bg">
	<div style="width:100%;" class="overlay-inner-bg" id="content">
		<a href="javascript:void(0)" onclick="closeSignup()" class="cross_popup">  </a>
		
			
	<div class="left_block left_block_new">
	<div class="scroll">
		<div class="top-heading">
			<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
				 width="234.613px" height="30px" viewBox="0 0 234.613 30" enable-background="new 0 0 234.613 30" xml:space="preserve">
<g>
	<g>
		<text transform="matrix(1 0 0 1 3.7056 24.729)" fill="#FFFFFF" font-family="'ITCAvantGardeStd-Bk'" font-size="24">JOIN</text>
	</g>
	<g>
		<path fill="#FFFFFF" d="M132.732,12.367l1.989,6.185h-3.907L132.732,12.367z M130.982,6.969l-7.024,17.741h4.914l0.815-2.563
			h6.208l0.84,2.563h4.962l-6.808-17.741H130.982z"/>
		<g>
			<path fill="#FFFFFF" d="M144.733,19.768c0.288,2.958,2.441,3.572,3.545,3.572c1.848,0,3.554-1.412,3.554-3.385
				c0-2.489-2.14-3.034-4.183-3.717c-1.453-0.422-4.546-1.333-4.546-4.682c-0.047-3.156,2.578-4.905,5.278-4.905
				c2.205,0,4.76,1.23,5.039,4.585h-1.966c-0.209-1.144-0.786-2.895-3.153-2.895c-1.77,0-3.226,1.207-3.226,3.038
				c-0.017,2.163,1.714,2.698,4.404,3.592c1.675,0.653,4.326,1.594,4.326,4.856c0,2.893-2.178,5.203-5.497,5.203
				c-2.967,0-5.43-1.869-5.549-5.264H144.733z"/>
			<polygon fill="#FFFFFF" points="156.213,24.709 156.213,6.971 158.991,6.971 165.576,21.852 172.113,6.971 174.887,6.971
				174.887,24.709 173.023,24.709 173.068,8.927 166.186,24.709 164.922,24.709 158.024,8.927 158.074,24.709 			"/>
			<path fill="#FFFFFF" d="M216.436,24.709h-2.143l7.41-17.738h1.916l7.34,17.738h-2.156l-2.059-4.982h-8.262L216.436,24.709z
				 M222.586,9.206l-3.52,8.894h7.08L222.586,9.206z"/>
			<path fill="#FFFFFF" d="M124.51,14.618h-8.832v3.618h3.607c-0.241,0.864-0.742,1.584-1.462,2.062
				c-0.72,0.505-1.657,0.791-2.782,0.791c-2.229,0-4.866-1.606-4.866-5.32c0-3.499,2.614-5.154,4.844-5.154
				c1.247,0,2.226,0.456,2.973,1.101c0.382,0.359,0.694,0.768,0.935,1.2h5.083c-0.983-3.428-4.628-6.281-8.871-6.281
				c-5.227,0-9.494,3.836-9.494,9.134c0,5.106,4.054,9.3,9.421,9.3c2.926,0,6.903-1.46,8.63-5.369
				C124.464,17.976,124.608,15.889,124.51,14.618"/>
			<path fill="#FFFFFF" d="M207.434,16.351v1.632h5.648c-0.287,1.393-1.143,2.719-2.393,3.695c-1.232,0.968-2.873,1.611-4.75,1.611
				c-3.883,0-7.289-2.956-7.289-7.472c0-4.447,3.4-7.417,7.279-7.417c1.566,0,2.969,0.458,4.125,1.249
				c0.754,0.502,1.422,1.153,1.98,1.918h2.262c-1.402-2.897-4.742-4.915-8.326-4.915c-5.131,0-9.303,3.851-9.303,9.164
				c0,5.248,4.102,9.221,9.275,9.221c3.584,0,7.115-1.944,8.664-5.257c0.527-1.118,0.752-2.4,0.785-3.431H207.434z"/>
			<polygon fill="#FFFFFF" points="87.195,7.048 82.648,7.048 78.303,14.541 74.019,7.048 69.356,7.048 76.014,18.683
				76.014,24.709 80.547,24.709 80.547,18.514 			"/>
			<path fill="#FFFFFF" d="M185.854,6.649c-4.889,0-9.352,3.595-9.352,9.394v0.023c0,4.558,3.742,8.992,9.326,8.992
				c5.516,0,9.4-4.266,9.4-9.206C195.229,10.916,191.32,6.649,185.854,6.649 M187.168,20.889l-1.324,2.285l-1.334-2.326
				c-2.188-0.648-3.473-2.785-3.473-5.044v-0.021c0-2.493,1.701-5.182,4.842-5.182c3.26,0,4.814,2.949,4.814,5.252
				C190.693,17.814,189.541,20.249,187.168,20.889"/>
			<path fill="#FFFFFF" d="M94.811,6.649c-4.89,0-9.352,3.595-9.352,9.394v0.023c0,4.558,3.743,8.992,9.329,8.992
				c5.516,0,9.397-4.266,9.397-9.206C104.185,10.916,100.278,6.649,94.811,6.649 M96.127,20.889l-1.324,2.285l-1.333-2.326
				c-2.19-0.648-3.478-2.785-3.478-5.044v-0.021c0-2.493,1.704-5.182,4.843-5.182c3.261,0,4.819,2.949,4.819,5.252
				C99.654,17.814,98.496,20.249,96.127,20.889"/>
		</g>
	</g>
</g>
</svg>
        </div>
	<div class="sign_signup_form">
	<form rel="signupBox" action="" method="post" class="singup_form" id="singup_form" name="myFrom">
		<input type="hidden" value="" name="csrf_token">					
		<span style="color:#990000; font-size:14px;"></span>
		
	<ul class="list1">
		
		<li>
		<div class="form_field_left">
			<input type="text" name="fname" data-watermark="First Name">
		</div>

		<div class="clearfix"></div>
		</li>
		<li>
		<div class="form_field_left">
			<input type="text" name="lname" data-watermark="Last Name">
		</div>
		</li>

		<li>
			<input type="text" name="email" data-watermark="Email">
		</li>

		<li>

		<div class="form_field_left">
			<div class="field">
                  <div class="input-box">
					  <input type="password" name="password" rel="password" class="watermark_password_orignal"  />
				  <input type="text"  value="Choose Password" 	class="watermark_password" />
				</div>
           </div>
			
		
		</div>
		<div class="clearfix"></div>
		</li>


       <!--  <li>
         <div class="form_field_left">
        			<div class="field">
                       <div class="input-box">
                            <input type="password" name="confirmation" placeholder="<?php echo $this->__('Confirm Password') ?>" id="confirmation" class="input-text required-entry validate-cpassword" />
                        </div>
            </div>
        		</div>
        		<div class="clearfix"></div>
        		
        		</li> -->
          
		<li class="gender-link">
		      <span> <label>Select Gender</label></span>
				  <div class="f-right">
				 
                  <?php
					$options = Mage::getResourceSingleton('customer/customer')->getAttribute('gender')->getSource()->getAllOptions();
					$value = '1';
					$_last = count($options);
				   // $_index = 0;
				  ?>
				  
			<?php foreach ($options as $option):?>
			<?php if($option['value'] != ''): ?>
		    <div>
		 <label class="f<?php echo $option['value'] ?>">
         <input class="custom-radio radio" type="radio" title="<?php echo $option['label'] ?>"
		value="<?php echo $option['value'] ?>" name="gender"
				<?php if ($option['value'] == $value) echo 'checked="checked"' ?>>
			  </label>
				<span> <?php echo $option['label'] ?> </span>
				</div>
					<?php endif; ?>
					<?php //$_index++; ?>
				<?php endforeach;?>
				
				</div>
				
				
		</li>

		<li>
		<input style="display: none;" id="is_subscribed" class="checkbox" type="checkbox" checked="checked" value="1" name="is_subscribed">
         <input type="hidden" autocomplete="off" maxlength="30" id="isAjax" name="isAjax" value="1">

			<!-- msz alredy email exist -->
			<div class="error" id="error_msg"></div>
				<p style="text-align: left" class="err_msg"></p>
			<!-- end -->
			
			<button  type="button" name="sign-up" id="create_account" class="create_account btn"><span class="tick-mark"><img alt="yogasmoga" src="<?php echo $this->getSkinUrl('images/tick-mark.jpg') ?>" class="responsive"></span></button>

			<p class="already_signed_up" >Already signed up? Sign in here</p>
		</li>
	</ul>
</form>
</div></div>
	<div class="clearfix"></div>

			</div>
		</div>
	</div>
</div> 

<script type="text/javascript">
jQuery.noConflict();
var customForm = new VarienForm('singup_form');
</script>

<script type="text/javascript">
jQuery.noConflict();
function closeSignup(){
jQuery('#popForm').hide();
}
jQuery(document).ready(function() {
// jQuery(".custom-radio:checked").parent().addClass("current");
 jQuery(".custom-radio").click(function(){
  jQuery(".custom-radio").parent().removeClass("current");
  jQuery(this).parent().addClass("current");
 });
});
</script>

<?php
$name = 'popupcookies';     
$value = 'yes'; 
// $getCookies = "";    
$getCookies = Mage::getModel('core/cookie')->get($name);
//$getCookies = "";  
if($getCookies==""){

?>
<script>
jQuery.noConflict();
jQuery(document).ready(function() {
jQuery("#popForm").show();

});
</script>
<?php
Mage::getModel('core/cookie')->set($name, $value);
}
?>

<script>
jQuery.noConflict();
jQuery(document).ready(function () {
init_watermark();
jQuery("#create_account").click(function (e) {
	e.preventDefault();
if (customForm.validator && customForm.validator.validate()){
	createCustomerAccount();
}
    });


});


//jQuery.noConflict();
//jQuery('#signup-form').submit(function(e){


//});
</script>
<?php  
}
}?>
